### ISSUE TITLE
Let docker run bind also to a host not only a ip

### ISSUE THREAD

**Issue by frank-dspeed** [docker/docker#10024]
when you do docker run -p host.box:10080:80 you get
````
Cannot start container cbf350dc593e5b27e05a7cef06dd73f890a7d18671e5fadf38fd52065f4bf73a: Bad parameter: invalid host ip host.box
````

but when you would supply the ip to the command it would work i am voting for implaminting host usage at that place because then i can keep my run files same and it will always bind to right ip.

**Comment by phemmer** [comment]
The problem with this idea is that host names don't necessarily have a one-to-one mapping to IP addresses. A hostname can map to multiple IP addresses. As such, this kind of thing would have to be tailored to the end user's setup.

A simple solution would be:

    docker run -p $(getent ahostsv4 host.box | awk '{ print $1 }'):10080:80

**Comment by frank-dspeed** [comment]
ya that true thats true but imagin some one that uses this in his run command will probally have dns setuped for this situation so every host will have local the right response that he expects (the public main ip to use)

**Comment by frank-dspeed** [comment]
in my case i have on every box a host.box entry so that it knows its ip via that dns entry i use it in many scripts but it would in this case simply enable me to do one run command on 1000 of boxes and bind the container to the right ip its more well as at present i transform the run command for every host only because the leak of dns ability in that point

**Comment by frank-dspeed** [comment]
and your suggest command is realy well realy good but thats not fig compatible.

**Comment by thaJeztah** [comment]
Perhaps this makes more sense to be implemented in Fig then; there's a PR for Fig to support environment variables in `fig.yml`;  https://github.com/docker/fig/pull/76#issuecomment-63954578
 thinking something like this;

    DOCKER_HOST_BASE=$(getent ahostsv4 host.box | head -n 1 | awk '{ print $1 }') fig up

**Comment by frank-dspeed** [comment]
not good i will edit fig to simply dns resolve your right with that but every where where i can supply i ip i should be able to supply a host that generaly the right way-

**Comment by cpuguy83** [comment]
I can see binding to a eth device instead of an ip, but by host seems a bit off since host can be external.

**Comment by frank-dspeed** [comment]
i can see that your a good guy cpuguy83 then do binding to a device that solves my needs too and i patched fig as work around till this day comes :dash:

**Comment by phemmer** [comment]
Binding to an interface also has issues. A single interface can have multiple addresses. :-/

**Comment by frank-dspeed** [comment]
phemmer how ?

**Comment by cpuguy83** [comment]
@phemmer That's ok, it would be equivalent to multiple `-p`'s. Though, ip's would have to be checked at each container start.

**Comment by phemmer** [comment]
@frank-dspeed `ip addr add 1.2.3.4/32 dev eth0; ip addr add 1.2.3.5/32 dev eth0`

@cpuguy83 but what happens if an address is added or removed while docker is running? I think such a feature would be misleading, as then users would expect their container to pick up the new address (which it might, but that means docker has to monitor IP addresses on the interfaces).

I'm not opposed to dynamic detection of the bind address, but I don't think this is docker's responsibility. If fig is in use, this sounds like fig's job.

**Comment by frank-dspeed** [comment]
@phemmer your wrong ip addr add will not result in a new ip added to the device it will not show up in ifconfig and the ip if you bind to a interface is not importent all ips of that interface will work you bind to a interface. adding removing ips don't matters then.

**Comment by phemmer** [comment]
@frank-dspeed It doesn't show up in `ifconfig` because `ifconfig` was deprecated years ago. It doesn't support a lot of modern features in the linux kernel. Some distros have even stopped including it by default.

Secondly, you cannot bind to an interface. See [`man 2 bind`](http://linux.die.net/man/2/bind). You specify an address, not an interface. You can bind to `0.0.0.0`, which means all addresses on the system, but there is no way to specify all addresses on an interface.
Additionally, if you bind to one of those addresses, you will not receive traffic for other addresses on the interface.

**Comment by frank-dspeed** [comment]
This can be closed i think i will do my own version of docker-compose now :D
