### ISSUE TITLE
`pkg/archive` needs a refactor, extra maintenance

### ISSUE THREAD

**Issue by jlhawn** [docker/docker#10038]
It handles so much already: Image layer diffs, calculating container changes, copying resources. We could definitely partition it into each of these into the core of it and abstractions for getting/applying container rootfs diffs and changes, and copying files/directories.

**Comment by unclejack** [comment]
*reviewed with @tiborvass*

There's an issue with splitting this up right now. The first problem is that this would force us to split up pkg/chrootarchive as well in a very similar (if not identical) way to mirror the pkg/archive changes.

The other issue is that I'm not sure what the immediate gain would be. We'd have to spend time with this to ensure it's still all OK. I haven't received complaints about not being able to implement changes for this package or that it has grown too big.

The third issue is that we need to figure out how to split this up and what interfaces we need. Not doing it like this will force us to change it further and possibly duplicate a lot of code.

We should arrange to review this together. @cpuguy83 should probably be involved as well.

**Comment by unclejack** [comment]
This issue was opened to discuss the blocking issue for #9871. However, #13171 has been merged and #13171 replaces #9871's.

I think this issue should be closed as there has been no more activity since the 14th of January on this issue and numerous PRs which change pkg/archive has been merged, including Windows support and what not.

I'll close this now. Please feel free to comment.

**Comment by jlhawn** [comment]
:+1:
