### ISSUE TITLE
bridge IPv6 does not match existing bridge configuration fe80::1

### ISSUE THREAD

**Issue by emsi** [docker/docker#10045]
ping @MalteJ
Adding --ipv6 when invoking daemon yields:
````FATA[0000] bridge IPv6 does not match existing bridge configuration fe80::1```

My network configuration is:
```sh
root@emsi-docker:~# ifconfig docker0
docker0   Link encap:Ethernet  HWaddr 56:84:7a:fe:97:99
          inet addr:172.17.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::5484:7aff:fefe:9799/64 Scope:Link
          inet6 addr: 2001:db8::1/48 Scope:Global
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:77925980 errors:0 dropped:0 overruns:0 frame:0
          TX packets:157133033 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:159287511078 (148.3 GiB)  TX bytes:165247062972 (153.8 GiB)
```

I tried ```--fixed-cidr-v6=2001:db8::/64``` as well as ```--fixed-cidr-v6=fe80::/64```.

**Comment by MalteJ** [comment]
Docker checks if the IPv6 address of `docker0` is `fe80::1/64`. If not it fails.
You have two options:
1. Remove the bridge and let Docker create a new one
    `ifconfig docker0 down`
    `brctl delbr docker0`

2. Just set the IPv6 address manually
    `ifconfig docker0 inet6 add fe80::1/64`

**Comment by emsi** [comment]
So it's mandatory to use fe80::/64 prefix? Is there a way to override it?

**Comment by MalteJ** [comment]
fe80 is the link-local IPv6 address.
Yes, it is mandatory.
You can assign global IPv6 addresses via the `--fixed-cidr-v6` flag.

**Comment by emsi** [comment]
I already had a link local fe80::5484:7aff:fefe:9799/64. I mean if it's mandatory to use fe80::1/64.

**Comment by MalteJ** [comment]
yes, it is. `fe80::1` is often used as router. In Docker it is currently hard-coded.

**Comment by emsi** [comment]
OK. I got it. It works now. Thank you :)

Question:
Isn't it better to use fd00::/8 and randomize some prefix? (As per: https://en.wikipedia.org/wiki/Unique_local_address). It would be analogous to 172.16/12. (fe80::/10 are kind of 169.254.0.0/16).

On the other hand I tried to set the prefix with ```--fixed-cidr-v6=2001:db8::/64``` but got the very same error even though my interface had a first ip from that subnet: ``` 2001:db8::1```.

**Comment by MalteJ** [comment]
where do you want to use `fd00::/8`? Instead of the link-local `fe80::/64`?

The `--fixed-cidr-v6` flag should not result in a `bridge IPv6 does not match existing bridge configuration fe80::1` error.
`--fixed-cidr-v6` adds a route to the defined network to your routing table **when the docker0 bridge is created**. Further it assigns addresses from the defined network to your containers.

**Comment by MalteJ** [comment]
Your `docker0` address may be `2001:db8::1/64` but this is not required. You just need to have a route in your routing table `route -A inet6 add 2001:db8::/64 dev docker0`

**Comment by emsi** [comment]
You are right. ```2001:db8::``` is not required if the routing goes through fe80::1.

As for the addressing,  fe80::/64 are for auto-configuration. Every Interface has one IP in this range by default (an application can assume every interface has it). For local networking fe80::/64 seem more appropriate if we want to strech the analogy to the way current docker ipv4 networking is being done. I mean with the masquerading.

On the other hand ideally the default networking design for IPv6 should not employ masquerading.

**Comment by MalteJ** [comment]
Yeah, I have implemented "true IPv6" for a reason ;-)
I don't like the NAT foo.

**Comment by MalteJ** [comment]
I am not sure if you have fully understood Docker's IPv6 routing strategy.
Have a look at http://docs.master.dockerproject.com/articles/networking/#ipv6

**Comment by emsi** [comment]
I like the way it is :)
One little comment, you should probably use 2001:DB8::/32 in the documentation as per rfc 3849.
https://tools.ietf.org/html/rfc3849

p.s. I really appreciate your work :)

**Comment by MalteJ** [comment]
Thank you :smiley: 

I have used a smaller subnet within `2001:db8::/32` so it looks more like the user's subnet ;)

**Comment by emsi** [comment]
Yes, but occasionally  you used ```2000::/64,  2001::/64 and 2002::/64``` as an example.
Plus once you refer correctly "NDP neighbor cache invalidation" and the other time "ARP cache invalidation".

**Comment by MalteJ** [comment]
Yes, you are right. I don't like it but `2000::/64` was shorter than `2001:db8:1::/64`.

Thanks for reporting the NDP neighbor/ARP mistake. I will correct that.

**Comment by aenertia** [comment]
I am having issues with the fe80::1 link local address scheme used. I have a Single public nic which has a /64 subnet routed to it by the Colo. My default gateway on this nic is also fe80::1 to the colo's switch/router. It causes docker containers (either using sub-subnneted /68 /80 ranges or the entire /64 for docker) to fail I think due to some sort of NDP issue upstream of the host. The fe80::1 being both my public nic and the docker bridge default routes I think is part of the problem.

Oddly this works intermitantly and I sitll haven't figured out why. I can see icmp pings from containers exiting the public nic fine when I do a tshark dump but nothing comes back.

**Comment by MalteJ** [comment]
Hi,

could you give us the output of `ip -6 route` and `ip -6 addr`?
If you want you can `x` out the first six bytes of your IPv6 address (e.g. `xxxx:xxxx:xxxx:43::1/64`)

Probably you have some mistakes in your routing table. I suspect your host's eth0 has an IPv6 address with a /64 netmask.

**Comment by aenertia** [comment]
Turned our hetzner started blocking my sub-subnetting. Seems they issue a
/64 but treat it as a /128. Am currently debating this with them. Will
force a nat66 situation which is just ridiculous.

**Comment by MalteJ** [comment]
I have used a Hetzner server for testing Docker IPv6 a few months ago. So it is possible to get it working there :smiley:

**Comment by aenertia** [comment]
Yup I did have it working at one point, which is why I was so confused as
to the behaviour;  but obviously there is an overzealous admin who
considers subsubnetting a breach of the ToS. FYI using Fedora21 with RDO
repo.

<snip>

Dear Sir or Madam
We have noticed that you have been using other IPs in
addition to the main IP mentioned in the above subject line.
As this is not permitted, we regret to inform you that your server has been
deactivated.
Guidelines regarding further course of action may be found in our
wiki: http://wiki.hetzner.de/index.php/Leitfaden_bei_Serversperrung/en.
Yours faithfully
Your Hetzner Support Team

</snip>

**Comment by aenertia** [comment]
So sorted out with hetzner with the unblocking so that removes some of the
issue. But still issues.

I have subsubnneted with my 64 delegation to a <PREFIX>::/64 on the Lan
interface - works fine with the a <PREFIX>>::/80

Docker still has problems.

I have given a  /80 for docker (i.e : DOCKER_NETWORK_OPTIONS=--ipv6
--fixed-cidr-v6="<PREFIX>:1::/80")

Launching a container i.e debian:sid I am unable to get out via v6. I can
see the packets exiting the Lan interface tho from the container and the
path looks ok to me on the host.

Alternatively if I assigned the entire /64 to the docker network i.e (
DOCKER_NETWORK_OPTIONS=--ipv6 --fixed-cidr-v6="<PREFIX>::/64 )

I still have the same issue.

ip neigh show  and ip -6 route shows two fe80::/64 routes one via docker0
and one via my lan

I didn't appear to have a <PREFIX>:1/80 route in the table for the docker0
dev so I manually added this in the hopes it would sort things out. Nope.

I have started fiddling knobs on the ipv6.net sysctl flags but all no joy.

Any ideas?

**Comment by aenertia** [comment]
that should have been I added <PREFIX>:1::/80 to docker0

i.e ip -6 route add <PREFIX>:1::/80 dev docker0

**Comment by MalteJ** [comment]
it would really help to have the complete output of your `ip -6 route` and `ip -6 addr`.
If you like you can send me the information in private.

**Comment by aenertia** [comment]
Hi I am travelling this week but will get back to this.

It sometimes works and sometimes doesn't I have it pinned down to something
in the docker network init fiddling sysctl flags when bringing up the
docker from systemd init scripts.
