### ISSUE TITLE
Container will not refresh env after its --link source container restarted

### ISSUE THREAD

**Issue by resouer** [docker/docker#10164]
We've known that Docker container will refresh /etc/hosts after it's link source container like db is restarted, but why doesn't this happen to env?

**Comment by thaJeztah** [comment]
IIRC, this is a limitation of the way environment variables work (in Docker), and they cannot be altered after the container is created. In most cases it's better to use the host-name to revolve linked containers.


If a maintainer can confirm I'm right here, I can make a PR to add a note to these sections of the documentation (let me know if you want that);

- Container linking; https://docs.docker.com/userguide/dockerlinks/#environment-variables
- Docker Run reference; https://docs.docker.com/reference/run/#env-environment-variables
- Known issues section; https://github.com/docker/docker/issues/8985

**Comment by cpuguy83** [comment]
Env vars cannot be changed for child processes, only the current process (or passed into a new process), so it would be impossible to update an env var.

My thoughts on this?
You already have to know the name of the container (or at least the alias you asked for) to access the env vars at all. So no need to get the container's IP from the env vars, just rely on /etc/hosts for this.  For ports, you have to already know the port number that is being exposed to get at that env var, as there is no way to expose a port and have that be different than the actual listening port... And since each container gets its own networking anyway, using the default/normal ports to listen on means you don't need to do funky things with the ports.

That said, there is a major overhaul of Docker's networking going on, part of that is service discovery improvements. See #9983

I'm closing since this isn't really a Docker issue, at least not beyond what #3155 is asking for.
If you would like to discuss further, please ping in either:

1. #docker on freenode
2. #docker-user mailing list
3. forums.docker.com

**Comment by fredlf** [comment]
From what @cpuguy83 says above, I don't think this qualifies as a Known Issue per se.

**Comment by cpuguy83** [comment]
More like a known technical limitation with work being done to replace the whole thing.

**Comment by thaJeztah** [comment]
@fredlf @cpuguy83 agreed, decided to not include it in my PR and only add the notes to the other sections.

For reference, see https://github.com/docker/docker/issues/10170
