### ISSUE TITLE
Proposal: Append user property to the instance

### ISSUE THREAD

**Issue by krystism** [docker/docker#10209]
Currently, as we know, all the users in the group "docker" can manipulate docker as if they have root privileges. In addition, all the instances are in a global scope. so when i want to list containers, in fact I  list all  users'  instances. But sometimes, in fact, always, I just want to list my containers, I really don't care others. So I think it may be better to append user info to the containers.When the user want to  do a list(exec `docker ps`), just shows the containers owned by the user rather than all the containers.
Of course, you can list all containers just by passing one or more flags, because in fact the docker currently can‘t Completely isolate the containers based user or group as we can just escape the docker to show others instances by calling system commands(like `ps aux`).

**Comment by krystism** [comment]
These can also be extended to manage images. In addition, if user-A have pulled the image "demo" from hub, when user-B requests to pull the same image 'demo', just soft-link A's.

**Comment by thaJeztah** [comment]
I think the "Meta data / Labels" feature (https://github.com/docker/docker/pull/9882) could be used for this once it has been implemented; you would be able to add "labels" to images and containers and apply filters based on those labels.

I would prefer that (labels) over a dedicated "user" property because it is a more generic approach (not everyone may be interested in adding a "user" property to their containers)

**Comment by cpuguy83** [comment]
Closing as this is better hanldled by either:

1) Filtering based on label
2) A proper user access control framework (#15365)
