### ISSUE TITLE
New Feature: Encrypt Images Locally

### ISSUE THREAD

**Issue by xiekeyang** [docker/docker#10210]
Maybe, it is a plus implementation that image could be encrypted locally.
It can protect one user's images from illegally reading and writing.
the similar feature is available on QCOW2 format.

**Comment by unclejack** [comment]
@xiekeyang Encrypting images right now isn't possible and not something to do right now. An easy thing to do would be to encrypt the block device (e.g.: `/dev/sdXN`, `/dev/vdaN`, etc) and store the Docker data on the encrypted block device.

Since information can leak in many ways if images are encrypted individually and the encryption is useless is an attacker gains access to the system, there's no point in encrypting images individually.

I'm going to close this issue because it's not something which makes sense to implement. Linux already has encryption capabilities and encrypting the images wouldn't add much which Linux can't already do on its own at the block device level.

Please feel free to comment.
