### ISSUE TITLE
Permission issues on shared volumes using Vagrant on Windows7 wen running docker run with -v option

### ISSUE THREAD

**Issue by cwallervand** [docker/docker#10274]
Hi. I have been googleing this issues for ages and I still have not been able to find a proper answer. My   use case for Vagrant and Docker is that I have a simple node application that I would like to run in a Docker container on a Vagrant issue. 

The goal is for new developers to just use the command `vagrant up` and the app will be up and running and accessible from the host on say localhost:8080. Also the developers should be able to alter the code on the host machine and this changes should be reflected on the running app in the container. My problem is that when i run `docker run  -v /host/path:/container/path` to mount the shared folder the permission of the files are changed (also the user of the files) so I can not run for example `npm install`

## Computer information ##
Host: Windows 7
Vagrant version: 1.7.2

## Project structure ##
* app
     * Gruntfile.js
     * index.js
     * package.json
* Dockerfile
* Vagrantfile

## Dockerfile ##
```
# Pull base image.
FROM dockerfile/nodejs

#Add /app from host to /workspace in container
ADD /app /workspace

#Install grun cli
RUN npm install -g grunt-cli

#set working directory to be /workspace in container
WORKDIR /workspace

CMD ["/bin/bash"]
```

## Vagrantfile ##
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "yungsang/coreos"

  config.vm.network "forwarded_port", guest: 8080, host: 8080

   config.vm.synced_folder ".", "/workspace"

  
  config.vm.define "CoreOS" do |cos|

    cos.vm.provision "docker" do |d|
      d.build_image "/workspace", args: "-t application_container"
    end

  end

end
```

Docker version on the CoreOS VM is 1.3.3, build 5dc1c5a

On the VM the info on the shared files with the host is: 
```
-rwxr-xr-x 1 core core  698 Jan 22 08:15 Gruntfile.js
-rwxr-xr-x 1 core core  381 Jan 21 14:20 index.js
-rwxr-xr-x 1 core core  643 Jan 13 14:54 package.json
```

If i run `docker run -it -p 8080:8080 application_container /bin/bash` the info on the files shared from  the VM to the container (using ADD in Dockerfile) show:
```
-rwxr-xr-x 1 root root 698 Jan 22 08:15 Gruntfile.js
-rwxr-xr-x 1 root root 381 Jan 21 14:20 index.js
-rwxr-xr-x 1 root root 643 Jan 13 14:54 package.json
```

I am at this point allowed to run both `npm install` and `grunt` which start the application. The application is accessible through localhost:8080. All good, except that I can not do changes to my code on the host and have the changes reflected on the container without restarting the container.

So, running `docker run -it -p 8080:8080 -v /workspace/app:/workspace application_container /bin/bash`should solve my problem, i.e. sync the folder on my host to the folder in the container. However, the file information is:
```
-rwxr-xr-x 1  500  500  698 Jan 22 08:15 Gruntfile.js
-rwxr-xr-x 1  500  500  381 Jan 21 14:20 index.js
-rwxr-xr-x 1  500  500  643 Jan 13 14:54 package.json
```

The user for the files have changed and running `npm install` fails (but I can see that the node_modules folder is actually created in my host folder):
```
npm ERR! Linux 3.17.2
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.35
npm ERR! npm  v2.2.0
npm ERR! path ../nopt/bin/nopt.js
npm ERR! code UNKNOWN
npm ERR! errno -1

npm ERR! UNKNOWN, symlink '../nopt/bin/nopt.js'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /workspace/npm-debug.log
```

The npm debug log can be provided if necessary. Noot sure if this is a Docker issue, an Vagrant issue or something else though.

**Comment by cpuguy83** [comment]
@cwallervand This issue is specifically with your vagrant setup, not Docker.

The permissions for mounted in volumes are not modified at all, but since you are running through shared folders, vagrant is mounting those files from your VM host and mapping those to a different user on the guest OS (CoreOS here?).

The solution?  Tweak vagrant to give you the proper permissions on the shared folder.

Also, instead of doing "npm install", which installs modules locally, you should install the modules globally `npm install -g`.  This ensures the modules are available to your app inside the container without it writing new module files to your project dir which are compiled for Linux.
This has the added benefit in that you can do this in your Dockerfile without having to re-run it when you mount your code into the container.

I'm going to close this since it's not really a Docker issue, although we are trying to help make these issues go away here #7249.  It looks rather dormant, but not entirely.

If you have any questions, please ping here... or preferably on #docker on freenode.

**Comment by CharlieC3** [comment]
Hey @cpuguy83, I have a similar issue and thought it might be useful to post it here.

I'm using Docker containers within a Vagrant VM to build and run my app with heroku build packs. It works well in an OSX/Linux environment, but doesn't seem to work in a Windows (7) environment and can't figure out why.

Essentially, the directory I share into my Vagrant VM is completely open. 777 permissions across the board (I know this is not recommended, but it's just for demo purposes of this problem). I then share the directory into a Docker container with `-v`, and it has full read/write permissions in there as well.

The Docker container may download some files and place them in the shared directory. The files being placed in the shared folder SHOULD be read/write/executable, however it's only read/executable. So if I were to try and delete the files downloaded in the Docker container or Vagrant VM, I get permissions issues (since it's not writable).

In an OSX/Linux environment, I don't encounter this problem. It works as expected, and file permissions are the same across the board (even for the downloaded files).

Do you know why this may be happening? Any ideas, suggestions? Nothing I've found online helped.

**Comment by cwallervand** [comment]
I managed to solve this by using ```mount_options``` for the synced folder configuration in Vagrant like so: 

```
config.vm.synced_folder ".", "/nodeApplication",mount_options: ["dmode=777","fmode=777"]
```

Note that the VM OS must support this kind of syncing (don't remember the name right now, sorry). For instance, it did not work with CoreOS as a VM OS, so I changed it to CentOS 7.0:
```
config.vm.box = "chef/centos-7.0"
```

As you mentioned the 777 mode isn't optimal, but I only used Vagrant for development, not in production. 

Here is a snippet from my Vagrantfile:

```

Vagrant.configure(2) do |config|
  #Set the Vagrant box
  config.vm.box = "chef/centos-7.0"

......

  config.vm.synced_folder ".", "/nodeApplication",mount_options: ["dmode=777","fmode=777"]

  config.vm.define "CentOS" do |cos|

    # Only run on first vagrant up
    cos.vm.provision "bootstrapVM", type: "shell" do |s|
      s.path = "bootstrapVM.sh"
    end

    cos.vm.provision "shell", run: "always", inline: "sudo service docker restart"

    cos.vm.provision "docker", run: "always" do |d|

      d.run "application_image",
        args: "-it -p 8080:8080 -v /nodeApplication/app:/nodeApplication",
        cmd: "/bin/bash -c 'npm install;grunt;'"
    end

  end

end
```

I hope this was helpful
