### ISSUE TITLE
no documentation for what parameters POST /containers/(id)/start takes in remote API docs

### ISSUE THREAD

**Issue by mcfiredrill** [docker/docker#10304]
There is no mention of what the permitted parameters are for starting a container are in the remote documentation API. I *know* that some options are permitted, for example I've been using `"PublishAllPorts"` . I'm not sure if its mostly the same as /containers/create or not.

https://docs.docker.com/reference/api/docker_remote_api_v1.16/#start-a-container

**Comment by thaJeztah** [comment]
Dup of https://github.com/docker/docker/issues/7073 ?

**Comment by mcfiredrill** [comment]
@thaJeztah 
Hmm, slightly different, thats for /containers/create, which I know could probably use some help as well.

**Comment by thaJeztah** [comment]
"oops" :angel: 

Yes, I noticed it was for "create" not "start", I thought both could use some love and perhaps its a good thing to document the endpoints at the same time.

**Comment by draghuram** [comment]
I see the following commen in `start.go`:

<pre>
// This is kept for backward compatibility - hostconfig should be passed when
// creating a container, not during start.
</pre>

Based on this, I guess the doc should clearly state that "hostconfig" should not be passed while starting a container. However, since it is still accepted, we do need to document this structure. I am looking at code to figure out how much of "HostConfig" is really processed in "start" API but if someone with knowledge in this regard can chip in, the process will be faster.

**Comment by thaJeztah** [comment]
@draghuram hold on, because I think I saw a PR recently that fixed this, will see if I can find it

**Comment by thaJeztah** [comment]
Looks like https://github.com/docker/docker/pull/12055 covered this

However, I think the same needs to be done for 1.18 and 1.19 (https://github.com/docker/docker/pull/12055#issuecomment-90225256), so if you want to take that, @draghuram, I'd say go for it!

/cc @cpuguy83 (for the "HostConfig" and just in case I overlooked something)

**Comment by draghuram** [comment]
@thaJeztah, I will see what needs to be done for 1.18 and 1.19.

**Comment by thaJeztah** [comment]
@draghuram great, I've marked this issue "claimed" for you. Remember to mention `closes #10304` in the first comment of your pull request, so that it is linked to this issue

**Comment by draghuram** [comment]
Ok, thanks.
