### ISSUE TITLE
Define client header to support distributed event sessionization

### ISSUE THREAD

**Issue by stevvooe** [docker/docker#10328]
Generally, a docker command instantiation makes several http requests to a running registry. Processing these requests in the registry server to sessionize the request flow is a non-trivial problem. While we have a proposed `Docker-Command` header in https://github.com/dmcgowan/docker/pull/18, it would be smart to include a unique token for each command execution that is added in a header to support trivial sessionization.

Use cases of these session identifiers include producing usable metrics for private registries or added to outgoing webhooks (docker/distribution#42) for later processing.

The header would consist of the command that was run (not the entire cli, ie "push" or "pull") and a session id generated at the start of each instantiation of the docker client process. An example of such a header might be as follows:

```
Docker-Command: push 3eed4669-d1e8-4753-9420-998e530386b1
```

The header could be added to all requests, from the client to the engine and beyond. If taken that far, such a header could support distributed debugging or begin to enable [dapper](http://research.google.com/pubs/pub36356.html)-like analysis.

**Comment by kencochrane** [comment]
I would like this as well, let me know if there is anything I can do to help.

**Comment by duglin** [comment]
Have you thought about two things:
1 - instead of using the cmd in the header used some uuid/session-id?  For a couple of reasons. It feels like a bit of security risk to include info from the cmd line on each request. Since I doubt you'd want to include the entire cmd on there you'll end up with a subset and run the risk of a dup from a previous run. Also, the same command run twice should result in 2 different sessions.  Non, CLI users (meaning normal API users) won't have a cmd line to include.
2 - having the daemon generate the ID on the first request and then each subsequent request include it.  Granted this assumes there is always just a single first request instead of multiple, which I don't know is right or not.

**Comment by duglin** [comment]
Oh, and if it is just a uuid then rename it Docker-Session-ID  :-)

**Comment by stevvooe** [comment]
@duglin 

> 1 - instead of using the cmd in the header used some uuid/session-id? For a couple of reasons. It feels like a bit of security risk to include info from the cmd line on each request. Since I doubt you'd want to include the entire cmd on there you'll end up with a subset and run the risk of a dup from a previous run. Also, the same command run twice should result in 2 different sessions. Non, CLI users (meaning normal API users) won't have a cmd line to include.

As proposed in the ticket, the header would only include the name of the command (ie "push", "pull", etc.) and a session id, which is created for each run of the docker client, rather than the full cli command. Effectively, a "session" is one instantiation of a command and the id is dropped afterwards. I've clarified that above so please check that it's sufficient.

> 2 - having the daemon generate the ID on the first request and then each subsequent request include it. Granted this assumes there is always just a single first request instead of multiple, which I don't know is right or not.

Operations against the registry, such as push and pull, lead to several related requests. They would all retain the same docker session id.

**Comment by duglin** [comment]
If all you want is a unique header/ID for a group of messages I would prefer if you dropped the cli cmd part of it because if people are using the API directly (w/o the CLI) then the grouping isn't necessarily tied to a CLI command.  The grouping could be for some notion that Docker itself might not know about. If we need to associate the grouping with what's going on within the CLI then I would prefer for the cli logs to have that mapping.  The daemon doesn't really need to know it.

**Comment by LK4D4** [comment]
@stevvooe do you think it's still actual?

**Comment by stevvooe** [comment]
@LK4D4 I'd like to explore this but using a structured tracing system, like open tracing. It might also be more valuable to start this effort on the server-side and grow it to the client, rather than starting with the client.

Up to you whether we close and open a more concrete proposal.

**Comment by LK4D4** [comment]
@stevvooe Yeah, if you think that we should start from server-side then it's better to open new issue.
