### ISSUE TITLE
[1.5.0-rc] `docker push registry/app` insists "latest" tag must be present

### ISSUE THREAD

**Issue by burke** [docker/docker#10444]
Our builder uses source git SHAs as tags: we have no `latest` tag.

After upgrading one buildserver to `1.5.0`, I see this:

```
Jan 29 18:45:33.905:	time="2015-01-29T18:45:33Z" level="fatal" msg="Error response from daemon: Tag does not exist for localhost:5000/shopify: latest" 
```

For context, we are not doing, e.g. `docker push registry/app:1234deadbeefcafe` in this case, just `docker push registry/app`. We're just having it synchronize whatever it's got locally to the registry. 

#### Problem/Solution:

`docker push` with no tag specified should not insist on `latest` existing.

**Comment by dmp42** [comment]
cc @dmcgowan @jlhawn

**Comment by stevvooe** [comment]
Classically, docker engine assumes the existence of a "latest" tag for a given image name. Perhaps, there is a bug here, since it was not generated automatically (nor am I the right person to comment on this).

What tag would you expect `docker push registry/app` to push if the tag is not specified?

**Comment by burke** [comment]
What it's done in the past is to push all the tags I do have locally to the registry, with no bias regarding `latest`.

The only time I've ever noticed docker actually assuming `latest` exists is when doing a bare `docker run` with no tag specified.

**Comment by stevvooe** [comment]
@burke Are you running `docker push -a registry/app`? In that case, the existence of latest should not be required, since it will just push all tags.

**Comment by burke** [comment]
Yeah, there's easy ways for me to fix this for my usecase. I could also just as easily append the tagname to my command; I'm not actually relying on it pushing all tags. This issue just exists to document a behavioural change I noticed that didn't appear to be intentional.

**Comment by stevvooe** [comment]
@burke Just looked: `-a` does not actually exist. We'll try to track this down and see if something broke with 1.5.

**Comment by burke** [comment]
FWIW: it does actually do what I want if I create a `latest` tag.

Note that this could also have been introduced in 1.4. We missed that one.

**Comment by crosbymichael** [comment]
@stevvooe need any help or want to pair?

**Comment by crosbymichael** [comment]
From searching:

```bash
michael|~/docker > pt "Tag does not exist for"
graph/manifest.go:
64:             return nil, fmt.Errorf("Tag does not exist for %s: %s", localName, tag)
```

which lead to:

```bash
pt newManifest
graph/manifest.go:
34:     manifestBytes, err := s.newManifest(name, repoInfo.RemoteName, tag)
47:func (s *TagStore) newManifest(localName, remoteName, tag string) ([]byte, error) {

graph/push.go:
273:            mBytes, err := s.newManifest(repoInfo.LocalName, repoInfo.RemoteName, tag)
```

In graph/push.go if len(tag) == 0 it sets the tag to the default tag, i.e. `latest` when it should query for all tags and push them. 


This is a confirmed regression.

**Comment by stevvooe** [comment]
@crosbymichael Looking at graph/push.go, it seems that `(*TagStore).pushRepository` handles empty tag case by pushing all whereas `(*TagStore).pushV2Repository` does not. Looking at getting a PR together for this.

**Comment by crosbymichael** [comment]
SGTM

**Comment by stevvooe** [comment]
@crosbymichael The reality is a little more subtle: the error message is triggered from the "manifest" engine command (`graph/manifest.go`) rather the V2 push flow. I confirmed this by reproducing the issue against a v1 registry, where the error is encountered before the registry version has even been resolved.

Hunting down a better way to fix this.

cc @dmcgowan

**Comment by dmcgowan** [comment]
I am not sure what behavior is attempting to be corrected. It is expected that only one tag may be pushed since the v2 push flow only supports one manifest per push and one tag per manifest. If we were to allow multiple tag pushes to v1 and not v2, then the behavior would be divergent.  Supporting multiple tag push in v2 will require much deeper changes to the client/daemon interaction.

**Comment by crosbymichael** [comment]
What do you mean?  just loop?

**Comment by stevvooe** [comment]
@dmcgowan The issue is that `docker push registry/image`, without a tag, worked in 1.4 but doesn't work in 1.5. I think we can patch this by sending multiple manifest blobs in response to the image manifest command. If you could come up with a better solution, please advise.

**Comment by dmcgowan** [comment]
I understand what the difference is, this was intentional once signature is introduced to avoid generating content the user did not explicitly sign-off on creating. Perhaps the signature code was tied into this flow earlier than it should have.  If the push flow is going to support looping, then signature should be completely disabled since it will be meaningless having manifests generated and signed by the daemon.  Currently the manifest is retrieved for a single tag, signed and returned on push.  Returning and signing multiple manifests would be a non-trivial change, signing by the daemon would only be a temporary stop-gap rendering the current signature meaningless.

If now is not a good time to introduce a change in behavior, then we can go the looping route and completely get rid of the client signature right now.

**Comment by icecrime** [comment]
I'm sorry but I have no idea how you expected us to ship such a breaking change.

**Comment by icecrime** [comment]
I understand the behavior, and I agree there is no easy fix. The only thing I can think of is having the client-side invoke the push API multiple time, but this requires it to know about the list of tags.

**Comment by dmcgowan** [comment]
I am going to work on a change ripping out the client side signature.  It would have the least effect on existing v1 and after v2 code has matured it can be re-added when full provenance is introduced.

**Comment by jlhawn** [comment]
@dmcgowan I think that's a good plan - I've always felt a little iffy about the "sign on push" behavior anyway. I'd like to argue for "sign on build" and/or "sign on tag" behavior in the future.

**Comment by icecrime** [comment]
So this means we'll always rely on the daemon side fallback behavior of generating a manifest and signing it with the daemon key, just like when the push request body is empty? I guess that's a good short term solution, especially as signing is not of much importance yet.

**Comment by dmcgowan** [comment]
Yes exactly like when the push is requested with an empty body. Seems clear to me the client signature code and flow is not ready and not currently needed so removing it is the best solution. This also allows us to defer making any changes to the Docker API related to signatures, allowing us to take a better route with manifest creation.

**Comment by icecrime** [comment]
Alright! Thanks once again for the quick patch.

I got one last thing to ask: considering that several issues were due to
the newly introduced requirement that the client had a key, should we take
another look at the key generation mechanism in light of this PR? Is it
still worth generating the client key, along with all the "migrate daemon
key to /etc/" dance?

On Friday, January 30, 2015, Derek McGowan <notifications@github.com> wrote:

> Yes exactly like when the push is requested with an empty body. Seems
> clear to me the client signature code and flow is not ready and not
> currently needed so removing it is the best solution. This also allows us
> to defer making any changes to the Docker API related to signatures,
> allowing us to take a better route with manifest creation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/10444#issuecomment-72216348>.
>


-- 
Arnaud Porterie

**Comment by dmcgowan** [comment]
Migrating the daemon key makes sense since it is still used.  My patch already removes the creation of the key client side.

**Comment by crosbymichael** [comment]
Didn't mean to be closed
