### ISSUE TITLE
'docker' group considered harmful

### ISSUE THREAD

**Issue by zopyx** [docker/docker#10583]
See

https://www.andreas-jung.com/contents/on-docker-security-docker-group-considered-harmful

**Comment by jfrazelle** [comment]
If you have access to docker you have access to root, we have never implied
otherwise.

**Comment by thaJeztah** [comment]
That's why there's a warning in the section that describes the "docker" group;

https://docs.docker.com/installation/binaries/#giving-non-root-access

In short, everyone that can access the daemon (socket/API) effectively has root access to your host. There are various warnings in the dicumentation for that

**Comment by thaJeztah** [comment]
@ewindisch do you think more warnings are needed?

**Comment by zopyx** [comment]
LOL - Closed due to ignorance about security issues.

2015-02-05 8:41 GMT+01:00 Jessie Frazelle <notifications@github.com>:

**Comment by zopyx** [comment]
Yet another clear indication that you have no security architecture and
that you give a shit about security.

2015-02-05 8:53 GMT+01:00 filtered <zopyxfilter@gmail.com>:
