### ISSUE TITLE
Dockerfile `VOLUME` directive doesn't work for single files

### ISSUE THREAD

**Issue by larsbutler** [docker/docker#10616]
In the [documentation](https://docs.docker.com/userguide/dockervolumes/), individual files can be mounted as a volume using `docker run -v srcfile:destfile`. In a `Dockerfile`, however, this doesn't seem to work: If I specify a file as the source (host) file, it just gets mounted as an empty directory in the container.

I would expect both of these (Dockerfile and command-line) to follow the same code path, but it doesn't seem that is the case.

**Comment by duglin** [comment]
VOLUME in Dockerfiles doesn't allow for you to specific a source - just the list of mount points to create within the container: https://docs.docker.com/reference/builder/#volume

**Comment by larsbutler** [comment]
@duglin Yeah, it definitely seems that's how it work. I would expect the `docker run -v` option to behave the same way, though.

**Comment by duglin** [comment]
@larsbutler I haven't played much with volumes but I believe it does act the same way when you only specify a single field in the -v.  For example, `docker run -v /some/path` will be the same as `VOLUME /some/path` from within a Dockerfile.  The difference you're seeing only pops up when you swap `/some/path` with `/host/path:/some/path` - which is going beyond just creating a mount point and actually linking it to the host's `/host/path` dir.  Since, at `docker build` time, we can't know what the host path will be it doesn't seem possible to have that as a parameter in the Dockerfile VOLUME command.

**Comment by cpuguy83** [comment]
duglin is right.  This would also make for inconsistent builds from host to host, and a security issue for things like DockerHub's automated build.

**Comment by larsbutler** [comment]
Okay, I understand now. Thanks for the quick feedback!

**Comment by coffenbacher** [comment]
I think the explanation on the single file limitation here makes sense, but I can't reconcile it with the docs (http://docs.docker.com/userguide/dockervolumes/#adding-a-data-volume). It seems to explicitly say the opposite?

*The -v flag can also be used to mount a single file - instead of just directories - from the host machine.*

    $ sudo docker run --rm -it -v ~/.bash_history:/.bash_history ubuntu /bin/bash

@duglin is this a documentation bug or am I missing something?

**Comment by duglin** [comment]
@coffenbacher I'm not following. The docs say the same thing as what I said.  You can specify a host path via `docker run` but not during the build (via Dockerfile).  Or did I not understand what you're getting at?

**Comment by coffenbacher** [comment]
Yes, I read closer and you're correct, thanks. I was seeing behavior that didn't match the docs - I saw the empty directory behavior when I used the -v parameter at ```docker run``` time, which brought me to this issue. However, when I went back to repro it today on 1.5 I couldn't, it worked as expected. If anyone finds this with the same issue, probably try updating your Docker client, since that's the main thing I can think of that I changed

**Comment by wotbstars** [comment]
I see it works incorrectly on Docker 1.12.5 on ubuntu. It map incorrectly mount single files as directories. 
Docker 17.04.0 on mac supports single file mounting.

**Comment by bfcapell** [comment]
I have the same issue that @wotbstars reports. After updating from 1.7.1 to 1.12.6 this stopped working

**Comment by adamkdean** [comment]
`Version 17.06.2-ce-mac27 (19124)` is mounting single files as directories for me, that's with `-v/--volume` and `docker run` command.

**Comment by bfcapell** [comment]
If this helps someone: my problem was finally unrelated to the docker version. If you are changing the docker version maybe is because you are doing other infrastructure changes. Well, the most  probable cause for this file-as-directory problem is that docker can't access the file, if that happens it creates a directory.

Specifically in my case the problem was caused by systemd-tmpfiles, that was unawarely enabled. But a much more common cause for this issue is permissions.

**Comment by afayes** [comment]
When specifying a mount for a file, if the file does not exist locally in the source directory then it creates an empty directory for the file. That is what is causing the problem. Solution would be not to create anything in the source directory if the file does not exist. This way the file may be generated at the target location and copied from there to the source
