### ISSUE TITLE
Not App Container Specification compliant

### ISSUE THREAD

**Issue by davetinder** [docker/docker#10643]
My client requires we use a container image system that will allow them to change the back-end at their choosing... ie they want to avoid "vendor lock-in". Docker is the only thing that is compatible with Docker... making it a no-go. Please update Docker to be compatible with ACI so that we can continue to use your product.

https://github.com/appc/spec/blob/master/SPEC.md

**Comment by phemmer** [comment]
This has been discussed in the past: [#9538](https://github.com/docker/docker/issues/9538#issuecomment-65967102) #10131

**Comment by shykes** [comment]
Hi @davetinder. I'm afraid your client was scammed. Every popular open-source project goes through a phase where its competitors feel threatened, and try to convince the community to stop using it. Coming up with a new "standard", then criticizing the established open-source project for failing to implement it, is a common tactic. Of course, the problem is that 1) the so-called standard is immature, unproven, and has virtually zero actual adoption; and 2) there is no actual risk of vendor lock-in, since the project is entirely open-source and not controlled by a single vendor. Docker has several contributors employed by Red Hat, Google, Microsoft, IBM and many small and mid-sized companies. If Docker, inc. went out of business or changed the format tomorrow, the project would live on.

The same is true for Linux, Git and most other popular open-source projects. Sure, Linux could decide to break every single API in the next release of Linux. But within the week, most of the Linux community would probably flock to a new project designed to maintain reverse compatibility. Would you call that vendor lock-in? Docker has received contributions from nearly 1,000 people. Each release (we release every 2 months) involves nearly 100 people. And we keep growing every day.

The Docker project encourages alternative implementations - both of its runtime environment and content distribution formats. We already publish specifications for both (see the project documentation). Could those specifications be improved? Yes. But there are already several alternative implementations in use at large scale, proving that vendor lock-in with Docker is a myth.

One last fact, which you might find funny: one of these alternative implementations of Docker's image distribution system is developed by CoreOS, the very same vendor which is propping up this so-called standard (for the competitive reasons I explained above). They use it to power a competitor to Docker Hub (the commercial offering of Docker, inc.). So, the very people trying to convince you that it's impossible to implement the Docker standard without being a customer of Docker, inc. are doing exactly that to compete with Docker, inc. And even though they are a competitor, the Docker community still actively supports them.

**Comment by shykes** [comment]
Note to other maintainers. There is a high probability that this is a spam account. We just noticed a pattern of new github accounts, created for the sole purpose of requesting support for the "app container specification", then never used again.

On the one hand I want to give the sponsors of this "standard" the benefit of the doubt. Maybe those were genuinely new github users, which decided to create an account specifically for this, and then never had another use for their account. It is entirely possible.

But just in case: please keep an eye out for bogus spam account creating the illusion of demand for this vendor-backed "standard" called "application container specification".

**Comment by shykes** [comment]
See also https://github.com/Jeff85
