### ISSUE TITLE
Ubuntu 12.04 container error

### ISSUE THREAD

**Issue by mrjeffs** [docker/docker#10699]
while adding 19gig directory called freesurfer (a neuroscience tool) to a newly building container using a Dockerfile i got this weird message.
Step 5 : ADD freesurfer /freesurfer
INFO[0221] Untar exit status 1 write /bin/swi_preprocess: no space left on device
is this a similar error to the mac boos2docker 20gig limit problem?
is there a similar procedure documented for Ubuntu?
jeff

**Comment by cpuguy83** [comment]
@mrjeffs this is likely because you are using the devicemapper storage backend (which is default for kernel's without AUFS support) which has a default size.

See https://github.com/docker/docker/tree/master/daemon/graphdriver/devmapper for adjusting your devicemapper settings to fit your needs...

Or use a patched kernel that supports aufs (which you can get from ubuntu backports).

Also, if you need additional help, please check out #docker on freenode, docker-user mailing list, or forums.docker.com

Thanks!
