### ISSUE TITLE
There should be a way for docker to clear its cache

### ISSUE THREAD

**Issue by thecodethinker** [docker/docker#10709]
Shouldn't there be a way for me to easily empty docker's cache in order to save disk space?

Something like `docker clear-cache`

**Comment by duglin** [comment]
This one is kind of interesting.  I don't think we have any "docker daemon management" type of tools or commands.  Although, one could argue that things like "docker pull" does, sort of, do that. So, if we did want to do something like this some options might be:
1) add a new docker command (`docker clear-cache` as being suggested)
2) extend https://github.com/docker/docker/pull/10535 to support something like `docker daemon --clear-cache` which won't start the daemon but instead just performs some admin action.

I can see the number of admin tasks growing over time so we may want to think about a long term solution to this type of request.  I'm leaning more towards the 2nd option - even if its under `docker admin` instead of `docker daemon`.

**Comment by cpuguy83** [comment]
@thecodethinker The thing with the cache is it's all just images layered on top of each other. And the cache layers are used for the final product (which is why it works).

That said, today you can clear out essentially unreachable images (images without tags) with `docker rmi $(docker images --filter dangling=true)`

Proper GC of images, volumes, etc has been much discussed but never implemented.

**Comment by thecodethinker** [comment]
From what I've seen by looking around some of the issues, an admin tool like what @duglin suggested seems really wanted.

Would there be any way to implement something like this with the daemon's API? Or would there need to be a good amount of work done within the daemon?

**Comment by thecodethinker** [comment]
@cpuguy83 I'm not sure if this is a separate issue but when I run `docker images --filter dangling=true` it gives me containers that are being used by other containers.

What is docker's definition of dangling?

**Comment by cpuguy83** [comment]
@thecodethinker dangling means the image ID is not part of a tagged image.
A container can be using a non-tagged image (for instance if you've pulled a new version of `ubuntu`, the container's `ubuntu` is now untagged). These images won't be deleted with the above command since the image is in use.
You can force the removal of these in use images if and only if the container using it is stopped by using the `-f` option:  `docker rmi --f $(docker images --filter dangling=true -q)`

**Comment by thecodethinker** [comment]
Would that cause any damage to the final image? Or are those just the cache
for if I update or change the image?

**Comment by cpuguy83** [comment]
@thecodethinker That's why they are dangling, the layers are not in use by an image that is actually reachable, so in that sense there is no 'final' image for these dangling layers.

**Comment by ankushagarwal** [comment]
This is documented here : http://docs.master.dockerproject.org/reference/commandline/cli/#images
So I guess this issue can be closed
