### ISSUE TITLE
Cannot run docker from inside a Java Application

### ISSUE THREAD

**Issue by dbremmen** [docker/docker#10734]
Hi!
My name is David, I'm building a free online java compiler (www.browxy.com) and I'm trying to add docker so users can execute their programs in a sandboxed area

I'm trying to run docker from inside a java application with java.langProcess using this command:
sudo docker run -it -v /home/compiler/project/43:/home/browxy -w /home/browxy/data browxy java -cp "../libraries/*:../target" HelloWorld

But I receive the error: cannot enable tty mode on non tty input

I read that this is not supported, is there a way or trick to make that work?

Thanks!

**Comment by duglin** [comment]
You may want to ask this one the docker-user google group:
https://groups.google.com/forum/#!forum/docker-user

**Comment by cpuguy83** [comment]
@dbremmen Yes, mailing list (or forums.docker.com, or #docker on freenode) would be a better place for questions.

But here is the answer:
The java process is not providing a TTY to the docker CLI but you've asked for a TTY by specifying `-t` in your command.
So, does the image actually need a TTY? If not, don't specifiy `-t`... if the image doesn't need stdin at all don't specify `-i` either.
If it does need the TTY, then you'll need to setup the TTY for your comand and it should work.

Closing this since it's not an issue.  Happy to help on the mentioned support channels above!
