### ISSUE TITLE
Prevent docker from eating disk space

### ISSUE THREAD

**Issue by MitchK** [docker/docker#10759]
In our operations landscape we only want our Docker registry to grow in disk usage.

Especially in our Continuous Delivery cycles we often have the problem that our CI instance/docker nodes run out of disk space. 

So we need to do ``` docker rmi `docker images -a -q` ``` / ```docker rm -f `docker ps -a -q` ```manually.

Are there any best practices, e.g. not keeping old containers/images?

**Comment by cpuguy83** [comment]
For support on Docker, please see #docker on IRC, docker-user mailing list, or forums.docker.com

To answer your question:
`docker rmi $(docker images -q --filter dangling=true)`
A dangling image is essentially an unreachable image, in the context that the only images you probably want to use are tagged images and not specific image ID's... so a dangling image is one that is not within the tree of a tagged image.

Now, some containers may be using one of these dangling images (and you probably want to update those containers to use the tagged image)  due to pulling newer versions of the image, and as such Docker can't remove that image until no container is using it anymore.

You probably want to make sure you are cleaning up volumes as well.  Docker does not remove volumes unless you tell it to upon removing a container: `docker rm -v <container>`.
You can use https://github.com/cpuguy83/docker-volumes to help with pruning these.


Closing since this isn't really an issue.
