### ISSUE TITLE
docker inspect with an image instead of a container logs errors (trivial)

### ISSUE THREAD

**Issue by burke** [docker/docker#10773]
From a script, I've called `docker inspect ${my_image}`. Everything works as expected, but docker logs a couple "error" lines when it first fails to look up my image as a container, before proceeding to look it up as an image.

It should probably only be logging an error if both lookups fail.

```
INFO[5635] -job container_inspect(registry.chi.shopify.io:80/shopify:0beb47b3f04357bf6a4dfb25784d591fa0358a02) = ERR (1)
ERRO[5635] Handler for GET /containers/{name:.*}/json returned error: No such container: registry.chi.shopify.io:80/shopify:0beb47b3f04357bf6a4dfb25784d591fa0358a02
ERRO[5635] HTTP Error: statusCode=404 No such container: registry.chi.shopify.io:80/shopify:0beb47b3f04357bf6a4dfb25784d591fa0358a02
INFO[5635] GET /v1.17/images/registry.chi.shopify.io:80/shopify:0beb47b3f04357bf6a4dfb25784d591fa0358a02/json
INFO[5635] +job image_inspect(registry.chi.shopify.io:80/shopify:0beb47b3f04357bf6a4dfb25784d591fa0358a02)
```

**Comment by coolljt0725** [comment]
The `docker inspect` look up container first, if fail, then look up a image. So every inspect will look up container and then look up image even if you just want to inspect a image
I suggest to have a flag such as `-i` to specify to inspect a image, and inspect a container by default
This is useful if a container happen to have the same name of a container and I want to inspect a image.  What you guys think? If it is ok, I'll work on a PR

**Comment by cpuguy83** [comment]
Maybe this should just be a debug entry instead of ERROR

**Comment by coolljt0725** [comment]
@cpuguy83 But if I have a image which happened to have a same name of a container (I have really meet this situation) and I want to inspect the information of  the image, I have to rename or remove the container so I can inspect the image, otherwise it always return the container information

**Comment by neurogenesis** [comment]
We're also seeing alerts come out of upstart's docker.log for what looks to be similar behavior. It seems like this shouldn't be an error, but more a handled exception that is logged as info or debug, with a message on inspect of "container or image doesn't exist".

**Comment by phemmer** [comment]
Just chiming in here, but in my opinion, the solution is to drop these down from `error` level to something else, like `info`.

The `error` level is commonly used to indicate an issue within the application (https://stackoverflow.com/questions/2031163/when-to-use-log-level-warn-vs-error). These failed requests are not an issue with the docker daemon, but rather a bad request from the client. Thus they should not be logged as errors.

**Comment by hqhq** [comment]
@phemmer Thanks for your info, I'v posted a new approach, #13537

**Comment by runcom** [comment]
@phemmer these are errors. As I explained in #13537 a bad call to an endpoint which throws a 404 **is** an error and the api/daemon have to log it. I don't see why would we rather threat these errors at the info level. I really expect to see an error in the logs cause every api/web implementation threat a resource not found as an error and log it

**Comment by runcom** [comment]
To put my comment another way. Clients don't decide errors that should show up in daemon logs. It's client own business to make correct calls and because inspect is a cli command it should not mess around with api logs. 
It should not log an error only if both calls fails because it's just wrong not to log the first bad call to container/json

**Comment by phemmer** [comment]
> It's client own business to make correct calls and because inspect is a cli command it should not mess around with api logs.

I completely agree, that's why it's the client's job to log the error, not the daemon.

How do you expect to be able to distinguish client errors from daemon errors? If I want to monitor the docker daemon to make sure the system is healthy, it is impossible to do so if client errors are logged by the daemon as daemon errors.

**Comment by runcom** [comment]
I still think api 404 errors are server side errors, well not daemon error but of course backend api error. The problem here may be in how docker is structured, meaning we should log daemon errors because it's our application and api errors as well because it's daemon public layer, @phemmer wdyt?

**Comment by phemmer** [comment]
> this is not a client error but a server one

Server error means the server did something wrong and needs to be fixed. What needs to be fixed on the server if the client tried to perform an operation on a non-existent resource?

How do you propose solving the issue where I need to monitor the daemon for actual errors? Like if daemon can't launch a container (disk full, etc), or the daemon can't reach the hub, etc? I can't just look for `level="error"` because this contains bad requests from clients as well.

**Comment by runcom** [comment]
what I was saying is it's also a *controlled* server side error (you catch it)

**Comment by duglin** [comment]
Since both are related, see https://github.com/docker/docker/pull/13537

**Comment by duglin** [comment]
I think we should close this issue, not because the premise is wrong but rather because this is just the way docker works right now.  For better or worse, user caused errors are logged as ERRORs in the daemon's log.  I know this isn't technically a user error, but from the daemon's perspective it is.
Once we get #9509 then we can "fix" it so that the only ERRORs that appear in the daemon logs are things that are really wrong with the daemon and not user cause issues.

**Comment by hqhq** [comment]
If we can't have a conclusion about if we should show non exist container/image as daemon side error message. At least we should fix this scenario, use a valid command `docker images` with a valid image id, appears error message on daemon is never right and not acceptable.

Maybe we should reopen #13505 and fix this by:
If people use docker image, then don't take the non exist container as error but just return 404, only show error when both container and image are not exist.

As I said before, #10773 just fixed another problem, which is container and image have the same name, as long as we still offer `docker images xxx` to show container/image without any option, we will face this problem, and I think that's mostly what will happen.

**Comment by hqhq** [comment]
Sorry to see that, now we have no opening PR for this issue, and seems we still have no idea how to fix this problem, any thoughts?

**Comment by duglin** [comment]
@hqhq once #9509 is done I want to go through and see if we can remove all user-generated errors from the daemon log files - I think that would solve this issue.

**Comment by calavera** [comment]
You can use `docker inspect --image $myimage` to avoid container lookup. That's the way to make those logs disappear :smile_cat:  I'm closing this issue.. Thanks for your comments.

**Comment by neurogenesis** [comment]
@runcom I know this particular issue was just closed, but I would like to reiterate a point that has been made in a few different threads as well:

The docker daemon in general emits a lot of unnecessary errors, causing monitoring and alerting to be problematic. The maintainability of a system is highly dependent on the ability to effectively monitor and alert on it. Some guidelines:

1) Client-side errors or request errors should be handled by the client. This is the unix way and is typical of client / server architecture. While it might be helpful to know clients are making bad requests, this should be done at the debug, info, or warning level (depending on severity and impact to the business logic).

1) It's a best practice to log server-side events as errorlevel "ERROR" only when business logic has failed and demands user action to take corrective measures (no disk space, unable to contact endpoints, etc.). This enables effective monitoring and alerting without excessive alerts (pagerduty calls) and prevents complicated filtering rules to decide what's actually a problem or not. Monitoring docker should be as easy as blindly capturing syslog events. That line could accurately have been logged as:

```
INFO[5635] Handler for GET /containers/{name:.*}/json returned error: No such container: registry.chi.shopify.io:80/shopify:0beb47b3f04357bf6a4dfb25784d591fa0358a02
INFO[5635] HTTP Error: statusCode=404 No such container: registry.chi.shopify.io:80/shopify:0beb47b3f04357bf6a4dfb25784d591fa0358a02
```

3) When retry or failover logic is in place, only the final attempt should fail. For example, if the business logic says to pull a remote image if a local image doesn't exist, then an error shouldn't be reported if the local image isn't found (it should be debug or info). This is because the request hasn't actually failed as it is able to pull a remote image. An error should only be logged if a valid user request fails after exhausting retries (info / warnings will help indicate retries are necessary however).

4) Industry standard naming of events should be used in place of custom ones. This allows for seamless integration with existing monitoring solutions (without having to implement a new set of rules just for docker, i.e. CRITICAL|FATAL|ERROR|WARNING|INFO|DEBUG|TRACE).
