### ISSUE TITLE
CoLinux for better performance ?

### ISSUE THREAD

**Issue by stuaxo** [docker/docker#10851]
Reviving CoLinux and using it for Docker on Windows has the potential to run the containers than in using virtualisation.

At the moment it's missing full support for 64bit linux, though I believe they did start the transition.

**Comment by unclejack** [comment]
CoLinux has been very interesting in the past, but it has become less relevant with all the performance increases provided by newer CPU architectures and more advanced virtualization hardware.

Docker will run under CoLinux without any problems if CoLinux for amd64 gets released and the patched kernel is Linux kernel version 3.10 or newert, but it doesn't solve any particular problems virtual machines don't already solve today.

CoLinux also had some limitations like only being able to use a single core and requiring heavily patched kernels. Given how fast the Linux kernel evolves and how frequently it gets patched, it would be hard to justify the amount of time and resources an effort like this requires.

I'll close this issue now since virtual machines already solve the same issue - running Docker containers on Linux systems running a non-Linux system.

**Comment by karim789** [comment]
That answer doesn't makes sens to me, because if VM solved the issues the way you say it does, then we would not bother with LXC or Xen and such and just drop them.
So obviously you are not going to work on colinux, and that's logical, but I don't like the idea of dismissing Colinux principle.

**Comment by stuaxo** [comment]
I guess if 32 bit support ever comes through it will make this easier

https://github.com/docker/docker/issues/136
