### ISSUE TITLE
Base image for "build" command for ONBUILD-based images

### ISSUE THREAD

**Issue by bsideup** [docker/docker#10899]
Hi!

Currently, if we're using some ONBUILD base image, we have to write almost empty Dockerfile with content like this:
```
FROM corp/onbuild-image
```

It looks weird. What we want is some kind of a new parameter of docker build:
```bash
$ docker build --from corp/onbuid-image .
```

So we don't have to create that Dockerfiles for each ONBUILD-based project.

Thanks!

**Comment by thaJeztah** [comment]
I like the idea; for this case it's cleaner than (e.g.) using heredoc.

Related (but different); https://github.com/docker/docker/issues/9731

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.

**Comment by bsideup** [comment]
@jfrazelle probably you misunderstood this issue. It's not about changing Dockerfile format, it's just a shortcut for building "dockerfile-less" projects based on "onbuild" images, that's it

**Comment by rajivbhati12** [comment]
I see it kind of tricky because it impact the basic build principle of dockfile;
meaning:- every step of dockerfile execute in its own container and get save as a temp image for next step; with this thought; for first line to execute it has be static.
Unless we update FROM to perform extra step something like: if imagename[:tag] not found and appears to be more like variable then interpret it as variable

BTW; I am one add to people in queue waiting or this feature, as this can make CI look clean and not hacky 
So, are there plans to enable this feature?
