### ISSUE TITLE
Working on genieacs with docker, can I set static IP for the ubuntu container ?

### ISSUE THREAD

**Issue by Siddeshi** [docker/docker#10895]
general@general-M93p:~$ sudo docker run -t -i ubuntu:14.04 ip link add vipr2 link eth0 type macvlan mode bridge
[sudo] password for general: 
RTNETLINK answers: Operation not permitted
general@general-M93p:~$ 

I tried like this from the suggestion of someone. But I got operation not permitted error ..

So, to run genieacs I need a static IP. When I run the container, its IP gets changed each time..
Can I get a solution for it ?

Thank you.

**Comment by cpuguy83** [comment]
@Siddeshi For now I'd suggest something like github.com/jpetazzo/pipework for something like that.
Also, by default containers do not have the capability to manipulate network settings unless you explicitly enable it with your `docker run` command by adding `--cap-add NET_ADMIN`

For support issues, please use one of the following:

- #docker on freenode IRC
- docker-user mailing list
- forums.docker.com

Closing since this isn't a docker issue.
Please feel free to reach out in any of the mentioned support forums above.

**Comment by Siddeshi** [comment]
Thank you.
