### ISSUE TITLE
Manually stopped containers should not start after daemon restart

### ISSUE THREAD

**Issue by tonistiigi** [docker/docker#11008]
Container with a restart policy (eg `--restart always`) is always restarted on daemon restart, even if the container has already been put to the stopped state manually.

Background: when I update containers I'd like to keep old containers around for a while in order to do a rollback if needed. Now, should the daemon restart, all versions of the containers start again.

```
> docker run -d --restart always --name r0 busybox sleep 1000
> docker stop r0
> docker ps | grep r0 | wc -l
0
> sudo service docker restart
> docker ps | grep r0 | wc -l
1
```

Tested with `v1.4.1` and `v1.5.0`.

I could help out fixing this if it gets confirmed as a bug.

**Comment by phemmer** [comment]
Hrm, looks like #10032 was opened about this issue, and closed without comment :-/

**Comment by tonistiigi** [comment]
@phemmer indeed. ping @jfrazelle

**Comment by jfrazelle** [comment]
hmmm I really don't know why I did that I always leave a comment, apologies

**Comment by jfrazelle** [comment]
This is definitely a bug

**Comment by estesp** [comment]
The difficulty may be in determining which stopped containers with `restart==always` were stopped by daemon shutdown vs. manual stop sometime prior to daemon shutdown.   They will all show as stopped and the only trigger the daemon knows about is restart policy.  I think you almost more likely want a metadata change versus some knowledge that the container was stopped via manual methods as opposed to daemon shutdown.  By metadata I mean you want a temporary change to the container config's policy on restart until/unless you ever start the container again?

Anyway, thought I would throw my thoughts in here given I had looked at this earlier.

**Comment by tonistiigi** [comment]
How about an extra field to `RestartPolicy` named `SkipBoot` (or `ManuallyStopped` or smth like that). When container is manually stopped, it is set to true and daemon startup will check for that field. If container is started again this flag is set back to false.

@estesp @jfrazelle Does this sound ok?

**Comment by duglin** [comment]
Wouldn't a field in there representing the "desired" state be sufficient? Then upon a restart we can just restart the ones whose desired stated is "running" (and restart policy allowed it).

**Comment by tonistiigi** [comment]
ping @jfrazelle

Any comment about the config change? I don't really have a preference myself. Maybe `Desired` or `DesiredState` can give a wrong impression that this is something more than a restart policy(or wrong impression when you pause a container for example). bcd6a2f uses `SkipBoot` but I'd be happy to change it and turn it into a PR then.

**Comment by z0mbie42** [comment]
#dibs

**Comment by tonistiigi** [comment]
@z0mbie42 note that there is already a (month old) patch for this bcd6a2fa06d5cc35d59d296e9e135334fe5ce876 but design has not been confirmed. feel free to reuse it if you like.

**Comment by z0mbie42** [comment]
Thanks, I've seen this already, but we are at the Docker's birthday party, and we'll try to implement the second option.

**Comment by nhsiehgit** [comment]
Hi @z0mbie42 
Once you have your PR in please remember to add a `closes` or `fixes` keyword to help make tracking the fixes easier. Thanks!

**Comment by xiaods** [comment]
any update?

**Comment by sunyc** [comment]
Any update on this one? 

I would suggest doing this:

1) Add a "PreviousState" field, with possible value: Stopped, Running.
2) Skip starting container if  PreviousState field is "Running".

**Comment by sunyc** [comment]
And I can send a PR if you would cancel your "dibs"

**Comment by runcom** [comment]
@thefallentree are you still interested in submitting a PR for this? Almost a month passed, so just let me know :)

**Comment by thefallentree** [comment]
I didn't get a response from previous dibs holde and I sort of forgot. But give me another 3 days. I will send in a PR.

**Comment by thaJeztah** [comment]
@thefallentree thanks! No need to apologise; asking the previous "claimer" first was the right thing to do :+1:

**Comment by borikanes** [comment]
@thefallentree did you ever send in the PR?

**Comment by thaJeztah** [comment]
This topic came up today in a conversation on IRC and this looks to be the intended behavior. For reference, read the discussion [starting here](https://botbot.me/freenode/docker-dev/2015-07-06/?msg=43796240&page=5) and [continued here](https://botbot.me/freenode/docker-dev/2015-07-06/?msg=43809513&page=6)

In the last part, I suggested a feature to be able to change the restart-policy of an existing container to prevent it being automatically restarted again, which **might** be accepted.

/cc @crosbymichael @ibuildthecloud

**Comment by ibuildthecloud** [comment]
@thaJeztah I think a restart policy option would be a good idea.  Going off of @crosbymichael's comment: "it cannot read your mind" so lets just tell it what we want it to do.  But then we get into the UI discussion of how to address options for restart policy.  I believe there is something embedded in https://github.com/docker/docker/pull/9759 about that.

**Comment by thaJeztah** [comment]
@ibuildthecloud yup, think that might work too. (Still can envision cases where you want to change the restart policy of an existing container, but treading dangerous ground there, probably two camps pro/against being able to modify a container)

**Comment by avinson** [comment]
Regardless of whether the daemon can read your mind, the reality is that people manually stop containers and then neglect to remove them. Old or broken containers are then automatically restarted after system reboot or daemon upgrade. From an operational standpoint, it would be preferable to invalidate the restart policy when a container is manually stopped. Although this is making some assumptions about the user's intent, the majority of the time the user's intent actually is to invalidate the restart policy.

At the bare minimum, if we don't modify the "always" policy to do this then there needs to be an additional policy, call it "always-unless-stopped", that would allow for this behavior.

**Comment by icecrime** [comment]
I agree with @crosbymichael here: the day we "fix" this behavior, we have as many opened issues from people saying "the container I stopped manually didn't restart with the daemon!".

- I don't think we should silently invalidate the restart policy when a container is manually stopped
- I don't think a new policy is the right call (what about the container you already have running with `--restart=always`, are you going to recreate them? if you can, why do you care about all this in the first place?)
- I hate to say this, but I'm wondering if #11442 is not our best bet after all...

**Comment by ianbytchek** [comment]
:+1:

I keep old app containers for a short period of time after deploying the new one, so that if something is broken I can simply restart one of them. When the server restarts, in my case CoreOS does it every once in a while when gets automatically updated, I get tens of containers running simultaneously while I need only one that wasn't manually stopped. I'd assume I'm not the only one doing this?

**Comment by abronan** [comment]
Adding my perspective on this. Let's say we have a hundred nodes cluster with Swarm, at some point we'll use globally scheduled containers (meaning that you issue a `docker run` and we create/start a container on every single node of the cluster because they are used for monitoring purposes for example). 

This global container is started using `--restart=always`. Then we decide to stop this global container (accessible through a single virtual ID) because we messed up with a flag in the entrypoint. We re-create a global container with the right flags and at some point there is an automated and planned rolling upgrade on the Swarm machines. The globally scheduled container we stopped at first will restart on machine reboot, making the problem a *hundred times* worse.

On a single docker daemon this is not really an issue and I think that the default behavior of `always` makes sense. But from an operational standpoint using a huge cluster, this behavior can have a huge impact. So if changing the default `always` policy is something that couldn't be considered, at least adding a new one would make sense.

**Comment by thaJeztah** [comment]
Related to https://github.com/docker/docker/issues/11008#issuecomment-121415506; Thinking of using containers that publish a fixed port

```
docker run -d -p 123:80 --restart=always --name=version1 myapp:v1
docker stop version1
docker run -d -p 123:80 --restart=always --name=version2 myapp:v2
```

Restarting the daemon after this will (probably) lead to a race condition, after which either "version1" or "version2" will be running. At least we should have a solution for that.

**Comment by dorr-fg** [comment]
+1
The scenarios described above really need a solution. I believe a way to change the restart policy for an already created container is the way to go. If you look at how services in upstart or Windows work, they always have a way to be set as "manual" instead of automatic startup. This is a good pattern that IMHO should be followed in Docker as well.

**Comment by ianbytchek** [comment]
@dorr-fg agree. Being able to change the restart policy would be a perfect feature and solution. At least until there's a better one.

**Comment by avinson** [comment]
@icecrime -- thanks for your response

> what about the container you already have running with --restart=always, are you going to recreate them?

Yes

> if you can, why do you care about all this in the first place?

Because I'm not the sole docker user on the systems I administer. I probably wouldn't be following this issue so closely if I hadn't seen various developers make this mistake over and over and over again.. even the experienced ones that have been educated about this particular nuance of docker. In day-to-day use, this often leads to old versions of containers being restarted and various other cruft. The only workaround is to delete all stopped containers prior to any docker or kernel upgrade but I consider that as less-than-ideal since someone may have intentionally not removed a container after stopping it to save some data or be able to roll back. 

Without changing the behavior of restart=always or adding a new policy, periodically deleting all stopped containers will continue to be the only option. Allowing the policy of an existing container to be altered would be a nice feature but I doubt that will solve the operational headaches as most people simply won't bother to do that after manually stopping a container.

**Comment by icecrime** [comment]
Alright, I think it's clear we can't leave this as it is, and after discussing with @avinson I understand this better.

- Changing the behavior of `--restart=always` is not the right solution: this is working as designed, and I'll remove the `bug` label.
- Making it possible to invalidate the restart policy is not the right solution: people who forget to remove unused container today will forget to invalidate the restart policy tomorrow.

That leaves us with adding a new policy, that will become the de facto default for people who want this behavior. I'm not the best UX person, so I'll leave it to other maintainers to argue between `--restart=always_unless_stopped`, `--restart=always:unless_stopped`, ... ;-) The behavior, as discussed above, should be that containers always get restarted unless they were explicitly stopped.

Adding this to 1.9.0 milestone: feel free to step up and contribute a patch!

**Comment by salarelv** [comment]
Maybe just add a new command eg stop-forever that will remove the flag?
