### ISSUE TITLE
Oracle Linux 6.6 on Ubuntu: Segmentation fault

### ISSUE THREAD

**Issue by PositiveAlex** [docker/docker#11171]
Hey, once again.

I was faced with a problem when I'm running my server written in C++, compiled for RHEL6, on docker oraclelinux:6.6 while the host system is ubuntu.

gdb shows this information:

Program terminated with signal 11, Segmentation fault.
#0  0x00007f26f5c862b9 in __memset_sse2 () from /lib64/libc.so.6

On the other hand, when I start my program on a real rhel6 OS, it works as usual, no problems.

Of course, I digged the internet, but I didn't get any relevant answer...

Any thoughts ?

p.s.
`--privileged` mode doesn't help.

----

docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

uname -a
Linux xxx 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

docker -D info
Containers: 4
Images: 157
Storage Driver: aufs
 Root Dir: /u01/docker_files/aufs
 Backing Filesystem: extfs
 Dirs: 165
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 8
Total Memory: 15.67 GiB
Name: xxx
ID: TAWD:SMXU:J7TV:VWNM:XBJF:JJD5:FBTJ:2QYY:5BOK:BCY3:5KTK:6JJS
Debug mode (server): false
Debug mode (client): true
Fds: 34
Goroutines: 32
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /u01/docker_files
WARNING: No swap limit support

**Comment by phemmer** [comment]
I doubt this is docker related, or even an issue with using ubuntu as the host system.
I see 2 likely causes:

1. Your application is compiled for a different version of RHEL/OracleLinux (6.6 vs 6.3, etc).
2. Your application is compiled with optimizations for a different CPU. (gcc flag `-march`). Or with optimizations that make it unstable (`-O`).

I would try compiling it inside a container, using the same origin image (dockerfile `FROM`), and on the same host (or at least the same CPU type) as the one you're running it on.

**Comment by PositiveAlex** [comment]
@phemmer, 
also I tried to run it on 6.2 redhat, but the same problem as on 6.6. official build is for 6.5, but devs insured me that it should be working on 6.6 too, well, reality is a bit different.

Thank you, I will try to build it inside and/or ask for actual build options.

**Comment by cpuguy83** [comment]
Host shouldn't matter unless there's some weird kernel issue.
I would expect that the OL image is missing a required dep, different versions of libc, or something.

**Comment by estesp** [comment]
It may have something to do with expectations on `/dev/shm` in the container; although you would think that might be a more common issue, as SSE2-related mmap-family operations should be in a lot of binaries?  There is a hint that it could be namespace/mount related to `/dev/shm` because a very similar report was made about corosync and lxc here: http://marc.info/?l=openais&m=137992522414570&w=2

Too bad there really isn't any follow-on that helps solve the issue, but maybe that's a starting point to look at `/dev/shm` difference between a real RHEL6 host and inside a container.

If you are able to build with "`-O0`" (turn off optimizations) and try again, that would be interesting.  I'm rusty on `gcc` flags, but I'm sure there may even be some to turn on/off various CPU features (like using SSE2 instruction set?)

**Comment by cpuguy83** [comment]
Did you ever find out the issue here?
Can we close?

**Comment by PositiveAlex** [comment]
Ya, sure. Thanks.

вт, 18 авг. 2015, 5:50, Brian Goff <notifications@github.com>:
