### ISSUE TITLE
Record a video / screencast on how to install Docker on Ubuntu

### ISSUE THREAD

**Issue by spf13** [docker/docker#11193]
The installation documentation could really benefit from a video which walked the user through how to install Docker on Ubuntu. Typically these videos work well when there is narration over them explaining what to do.

The installation instructions for Ubuntu are available at https://docs.docker.com/installation/ubuntulinux/

Simple Screen Recorder appears to be a pretty solid screen recording option on linux http://www.maartenbaert.be/simplescreenrecorder/

When complete please upload to Youtube under a Creative Commons license and submit a pull request to add the video to the installation documentation page.

**Comment by gowtham66867** [comment]
External environmental factors or scripts running on the host created the resource contention
that triggered systemd’s re‐allocation and exposed the latent Docker CPU‐quota propagation
bug (Red Hat Bugzilla #1925343 and Docker Issue #11193 - Docker 27.4.0 + systemd) leaving
the EliteAAA container hard‐capped at ~2 cores instead of 40.
● Docker Issue #11193: "CPU quota not properly handled when container is moved between
cgroups"
o Initially Reported: Docker 1.8
o Partially Fixed: Docker 20.10.6 (April 2021)
o Fully Fixed: Docker 28.0.0 (January 2025)
o The fix involved changing how Docker interacts with cgroup hierarchies managed by
systemd, adding notification hooks to detect when systemd changes cgroup
parameters.

Need to know if using Docker 28.0.0 will fix the above issue in RHEL 8.10 as it mentions solving in Ubuntu?
