### ISSUE TITLE
Why port env vars for link is being deprecated?

### ISSUE THREAD

**Issue by zuoyue** [docker/docker#11255]
We have been using only the standard env vars to connect containers across hosts without ambassador. For example, we could create a mysql container on one host and expose its 3306 port to random public port and create a wordpress container on another host and get the mysql address and port via MYSQL_PORT_3306_TCP. It was very convenient without using an ambassador. The mysql container could be further put behind a proxy and the proxy ip/port could be passed to wp so that the mysql container can be moved around.

However, we found that this support is being deprecated by changes like this: https://github.com/docker-library/wordpress/commit/9aae24350b9c4ede3d5db9cdac1ba88c3202fe98

and seems "hosts" is more preferred instead. Can we understand why is that? "hosts" only provided ip address and we had to go back to always using the well known port and to me it limited the use of the container in lots of scenarios. So using MYSQL_PORT_3306_TCP to pass in a arbitrary port other than 3306 is not recommended?

**Comment by cpuguy83** [comment]
@zuoyue First, nothing has been deprecated.

In general we are looking at better methods of service discovery, and env vars are really terrible for this, especially how they are implemented with links.
... for instance, you have to know that you want port 3306 in order to consume the value of that port, which is always 3306.

If you are using a container you should use a standard port, because the containerized process has it's own network stack anyway.
If you are connecting to some non-containerized service, then use whatever service discovery you want, including setting an env var.

Closing this since it's not a docker issue.
And again, nothing has been deprecated on the Docker side.
Thanks for letting us know you still use this!

If you have an issue with this change to the wordpress image, please file an issue in github.com/docker-library/wordpress

**Comment by zuoyue** [comment]
Sorry I have to reply again just to clarify couple things: 1) In our scenario, we assigned an arbitrary port to MYSQL_PORT_3306_TCP based on its placement and its value is not 3306 any more. 2) I understand a docker container has its own network stack, but it doesn't mean it always has its own globally unique IPs, so standard port may not work in lots of scenarios.

I am glad to know that it has not been deprecated and I will file issues under the wordpress repo. Before you close this again, I am just wondering where we can give our inputs on the future service discovery discussion?

**Comment by cpuguy83** [comment]
@zuoyue #9983
