### ISSUE TITLE
Docker hub build stuck in pending state

### ISSUE THREAD

**Issue by rbrutgers** [docker/docker#11270]
Our dockerfiles are on Dockerhub, where we were able to build them automatically when a change was pushed to gihub, using a webhook on github.  However, our docker hub builds are stuck in a pending state.  Haven't found much documentation on this issue.  How can we go about troubleshooting this issue?  Thanks.

**Comment by cpuguy83** [comment]
Closing since this is not a Docker issue
Please send all DockerHub questions to support@docker.com

As a note, the automated build system was taken down earlier today to investigate if the Hub was vulnerable to a recently disclosed hardware-based security vulnerability called "RowHammer".
See also status.docker.com.
