### ISSUE TITLE
Make docker-machine, docker-swarm and docker-compose part of Docker installation

### ISSUE THREAD

**Issue by goloroden** [docker/docker#11279]
When I install Docker, I additionally need to install docker-machine & co. manually.

I'd like to see the installation of these tools integrated into the installation of Docker itself, so you only have to do one installation and you end up with having everything at hands.

What do you think about this?

**Comment by phemmer** [comment]
In my own personal preference, I would not want this. I never use docker machine, and docker swarm I don't install on the same hosts as docker itself.

Aside from personal preference, there are logistical issues with the idea. Each application has it's own versioning and release cycle. Docker swarm is at 0.1.0 while docker is at 1.5.0, and each is released when a new version is ready. Bundling them together would make releasing new versions of each component a lot harder/slower.

To me, this is something that should be taken up by the OS package maintainer. It's not an uncommon practice to use meta-packages for things like this. For example, you might install a `docker-suite` package, which would have dependencies on all the different docker packages and implicitly pull them in when installed.

**Comment by MrMMorris** [comment]
I agree that having all of them install would be overkill. Maybe an opt-in, but all I use is compose and only in local/CI.

**Comment by wyaeld** [comment]
What if they were handled by some sort of plugin/addon like api, so it doesn't have to be manual, but is also simple to use.  Something like

`docker install swarm`
`docker install machine`

**Comment by RickWieman** [comment]
I agree with @phemmer. It's one of the responsibilities of the operating system's package manager (or at least it should be).
I'd say you don't want code inside Docker that installs some other stand-alone Docker-related application... Especially when `docker install machine` equals `apt-get install docker-machine` (for example).

**Comment by goloroden** [comment]
I understand your concerns, and I think you are right.

Anyway, having a bunch of different ways to install tools that somehow belong together is not so nice.

Hence, I really like the suggestion by @wyaeld:

```
$ docker install swarm
$ docker install machine
```

+1 for this :-)

**Comment by RickWieman** [comment]
> Anyway, having a bunch of different ways to install tools that somehow belong together is not so nice.

By that you mean that you can only install one `docker` package through your package manager and then use Docker to install for example Swarm and Machine?

**Comment by goloroden** [comment]
By that I mean that e.g. if I want to run Docker on OS X, I need to:

- Install boot2docker using a graphical installer
- Install docker-compose via curl
- Need to remember to additionally install cli completion
- Install docker-machine via curl

where the two curl calls are 99% similar, but not perfectly equal. The one file is called `docker-machine_darwin-amd64`, while the other is called `docker-compose-Darwin-x86_64`.

Of course all of this is doable, but it neither feels comfortable nor consistent. And with this in mind, having something simple such as

    $ docker install compose

where I do not need to look up version numbers, file names, additional download paths & co. would be awesome :-).

**Comment by RickWieman** [comment]
I agree that it is a bit of a hassle to get it all installed at this moment, but isn't it just a matter of time before these can be installed easily through e.g. `brew`? There is already a `docker` recipe in there for example, so why not add ones for Machine/Compose/etc. instead of extending Docker itself?

Not that I don't like the `docker install` idea, but it still feels more like a package manager thing than something Docker should solve. If you want a package manager free installation, we could also create a Docker Suite installer for example, that does the steps you described above for you (where you can select which packages you want). I think that's a cleaner solution than adding the installation process to the Docker client. That way, we can provide both ways: you either download the Docker Suite installer and run that one (especially nice for Windows for example) or install the `docker-xyz` packages through your favorite package manager.

**Comment by goloroden** [comment]
Yes, some kind of setup suite would be fine, too :-)

**Comment by cpuguy83** [comment]
Or what about `docker run swarm`, which is already a thing?

**Comment by RickWieman** [comment]
But for Machine, that would be a chicken and egg problem, right? Because you'd need Docker for that, but you want to deploy Docker via Machine.

**Comment by xaibeha** [comment]
+1 for @phemmer 's suggestion. Please don't do your own docker-specific software management but rather use the system's:

Docker should manage containers and images; host binaries should be managed by the host system's facilities. Just one example,
```
dpkg -S `which docker-compose`
```
is very useful to have.

Please resist the temptation to "simplify" things by having yet another cross-platform tool-specific thing; in the end the workflow just feels native nowhere.

**Comment by jamshid** [comment]
+1 this is a problem, e.g. try writing a simple setup README for a mix of engineers using either Mac or Windows. It's a mess of confusing, contradictory links and curls, boot2docker vs docker-machine vs kitematic. Really sours new users on the idea that docker simplifies their life.

+1 `docker-compose` should be installed whenever `docker` is installed, it's too useful not be, and it's the primary interface for many users. 

Until boot2docker and kitematic GUIs are more complete (e.g. with docker-compose.yml editing), drop them from install instructions. Let's not kid ourselves, anybody using docker has to be familiar with command-line so stick to that and keep package managers like brew up to date. IMO `brew install docker` should install docker, docker-compose and docker-machine. `docker-machine create --driver virtualbox` should download and install Virtual Box, or at least show a link.

Linux package managers are a lost cause and cause more problems because of old versions. IMO stick to curl downloads and let Ubuntu and RedHat deal with their Atomics/Core distribs.

**Comment by cpuguy83** [comment]
@RickWieman docker-machine supports setting up/configuring swarm.

**Comment by RickWieman** [comment]
@cpuguy83 Cool, I didn't know that. In that case, forget what I said :blush:

**Comment by thaJeztah** [comment]
Together with the 1.8 release, we will also be releasing "Docker Toolbox" for Windows and OS X. Docker Toolbox is an installer that will install these tools; for reference, see the installation docs; https://github.com/docker/docker/blob/master/docs/installation/mac.md and https://github.com/docker/docker/blob/master/docs/installation/windows.md

The docker toolbox repository can be found here; https://github.com/docker/toolbox

**Comment by bfirsh** [comment]
Thanks for the report @goloroden. Hope Toolbox fixes this for you. :)
