### ISSUE TITLE
 docker build -f error doesn't match cause

### ISSUE THREAD

**Issue by cevich** [docker/docker#11289]
Cloned from [Red Hat Bugzilla:](https://bugzilla.redhat.com/show_bug.cgi?id=1196814)

Docs mention that if the argument to ``-f,--file`` is relative, CWD must be the context directory.  However, when outside the context directory, the error message doesn't reflect reality.  Also, the documented option handling is contrary to what the ``help`` output shows (see additional info).

**Version-Release number of selected component (if applicable):**
``docker 1.5.0``

**Steps to Reproduce:**
1. ``mkdir -p /tmp/dirone/dirtwo``
2. ``touch /tmp/dirone/dirtwo/dock_er_file``
3. ``cd /tmp``
4. ``docker build -t test -f dock_er_file /tmp/dirone/dirtwo``

**Actual results:**
The Dockerfile (dock_er_file) must be within the build context (/tmp/dirone/dirtwo)

**Expected results:**
Build must be executed from context when -f,--file option path is relative.

**Additional info:**
It would be much more intuitive if this worked like the ``docker help build`` describes (instead of  the docs):

     -f, --file=          Name of the Dockerfile(Default is 'Dockerfile')

IMHO this makes more sense, this option gives the filename and the ``URL|PATH`` argument gives the location (and context).  Check if the filename contains any ``/`` or ``\`` characters, and if so fail with a message that the filename must be simple, containing no path components.  Then docker can treat ``PATH|URL`` as per usual, assuming there will never be any relative components in filename and therefor ``PATH|URL + filename == context + dockerfile``.

**Comment by duglin** [comment]
I think this is working correctly.
Change your scenario slightly and you'll see why:
```
cd [project home]
cd dockerfiles
docker build -f Dockerfile.dev ..
docker build -f Dockerfile.prod ..
```
here I'm telling docker to build my project (which has a build context up one level from current dir) twice and I'm pointing it to a different Dockerfile each time.  The -f option doesn't point to some file within some "other" context, it points to a file "on disk" - which means its relative to the current dir unless they give an absolute path.  We discussed this a while ago and we decided that (like make -f) when people give a reference to a file they expect it to be relative to the current dir/system and not some other context.

Now, having said all of that, notice that when the filename is passed via the REST API its converted to be relative to the build context, which makes sense because there is no other context it can be relative to.

If you think the docs are misleading we can tweak them but functionally I think this is correct.

**Comment by cevich** [comment]
That's a slightly different issue than what I'm reporting, because relative is relative (forward backward and sideways).  It's impossible to predict where the absolute ``..`` actually is: Consider filesystem mounts occurring after change of CWD, or you arrived in CWD via symlinks, where ``..`` can means different things to different processes.

IMHO, it would be nice if it worked as I suggested above, since it seems a bit more intuitive.  I don't see any pressing need or reason to hold onto old conventions like make.  Heck even that's been replaced with (arguably) better systems, many times over.

In any case, I'm also practical, so a documentation fix is perfectly fine.   I think the ``--help`` just needs to mention the "relative" idea from the docs, so people know what to expect at a glance.

**Comment by duglin** [comment]
The docs right now say:
https://docs.docker.com/reference/commandline/cli/
- - - - - 
By default the docker build command will look for a Dockerfile at the root of the build context. The -f, --file, option lets you specify the path to an alternative file to use instead. This is useful in cases where the same set of files are used for multiple builds. The path must be to a file within the build context. If a relative path is specified then it must to be relative to the current directory.
- - - - - 
I think that says what you want said, but I think you want something under `docker build --help` too, right?
If so, the only issue with that is that we're limited to 80 chars per option line.  I'm not sure how I feel about this, but what about, instead of:
```
Usage: docker build [OPTIONS] PATH | URL | -
...
  -f, --file=          Name of the Dockerfile(Default is 'Dockerfile')
```
we have:
```
Usage: docker build [OPTIONS] PATH | URL | -
...
  -f, --file=          Name of the Dockerfile (Default is 'PATH/Dockerfile')
```
Do you think that would have made it clearer?

**Comment by cevich** [comment]
Precisely, the docs are fine.  Yep, I expected some careful --help-smithing would be required.  Actually your suggestion seems pretty close to perfect IMHO.  I think it's enough of a reminder that for any non-trivilal uses, RTFM is suggested.  Good by me, FWIW :grinning:

**Comment by duglin** [comment]
PR #11325
