### ISSUE TITLE
How to assign static IP or Hostname to each docker image when ever it is running?

### ISSUE THREAD

**Issue by Pratap6** [docker/docker#11344]
Hi,
I'm unable to assign static IP or hostname to each of my docker images when it is starting, please suggest me any approaches are there to resolve my issue.
docker Image starting command:     docker run -i -t -p 8070:8080 tomcatv1 /bin/bash

Here how to assign static IP to tomcatv1 docker image
please do the needful.

**Comment by coolljt0725** [comment]
For assigning static IP to a container, you can't do it through docker, but  you can use a network plugin such as `pipework` to do that
For assigning hostname to a container,you only can do that with `--hostname` during creation use `docker run ` or `docker create`, when the container is created, hostname can't be changed.
If I understand correctly, all the configuration of a container can't be changed once it  was created but the container name.

**Comment by Pratap6** [comment]
@coolljt0725 
Thanks for your quick response. please provide me any snippet is there..

I assigned hostname to container at time of creation 
docker run --hostname="tom" -i -t -p 8070:8080 tomcatv1 /bin/bash
root@tom:/#

but I'm unable to ping that new hostname(tom) from outside of the host machine.

!thanks

**Comment by cpuguy83** [comment]
@Pratap6 Yes, docker does not update anything on the host to make that hostname pingable.
You would need to reach the contianer either by IP Address, or through your forwarded port, 8070.

The way you have your command setup you should be able to reach a service in the container running on port 8080 from port 8070 on the host.

I'm closing this since it's a support question.

For support, please see any of these:
1) docker-user mailing list
2) #docker on IRC
3) forums.docker.com

Thanks!

**Comment by Pratap6** [comment]
@cpuguy83,
@coolljt0725 
Thanks for your response,  please suggest me any good links for assigning static IP's to a each docker container , At time of starting the docker image.

And also please suggest me on pipework network plugin to do static IP assigning to containers.

! thanks
