### ISSUE TITLE
Can Docker really support distributed system?

### ISSUE THREAD

**Issue by tdoan1971** [docker/docker#11440]
I see a good benefic of Docker but I wonder if it can fully support a distributed system?
My system has a WebApp, MySQL, and several other backend, middle tier components. Each component run on a separated RHEL6.5 VM host and each component has 2 or 3 processes/applications such as: nginx, freeswitch, redis, tomcat web, ruby rails, etc.

My question is that can I dockerize all components, have component's containers communicated in the same host and across different VM hosts?
If you have experiences and knowledges, please share.

Thanks,

**Comment by phemmer** [comment]
Questions like this are probably better suited for the mailing list: https://groups.google.com/forum/#!forum/docker-user

The issue tracker is generally for bugs and feature requests.

**Comment by unclejack** [comment]
As @phemmer has stated above, this kind of question is better suited for the forums https://forums.docker.com/ and the Google groups.

The short answer is that yes, you can probably run all components of your apps in containers.

This isn't a Docker bug or problem. This bug tracker is meant to discuss bugs and problems discovered while using and developing Docker.

Since this isn't a bug, the question is far too general and the discussion would have to touch too many subjects to provide the kind of requested detail, I'm going to close this now. 

Please ask this question on the forums or on the docker-user Google group.
