### ISSUE TITLE
Query on docker port binding while deploying a website

### ISSUE THREAD

**Issue by pavanadepu** [docker/docker#11517]
I have created a container from training/webapp image using the below command:
     sudo docker run -d -p 5000:5000 training/webapp python app.py

I am able to access my "Hello World" website.

When I try to change the ports using the below command, the container created but the website is not accessible(I have already removed the old container). 
     sudo docker run -d -p 5001:5001 training/webapp python app.py

It seems, still the website is trying to listen on port 5000 only. And as there is no active container mapped to 5000, the access is enied.

Can someone help me in resolving this issue.

**Comment by unclejack** [comment]
@pavanadepu The application is still listening on port 5000. If you want to listen on another port on the host, such as port 5001, you can use the following command `sudo docker run -d -p 5001:5000 training/webapp python app.py`. This can also be found in the documentation.

This issue tracker is meant solely for the following: 1) reporting bugs, 2) requesting features, 3) reporting unusual behavior which might be a bug 4) submitting proposals and 5) sending pull requests to contribute changes to the code.

Please use the following resources to learn more about Docker and how to use it:
1) go through the tutorial at https://www.docker.com/tryit/
2) read the docs at https://docs.docker.com/
3) ask questions on https://forums.docker.com/ or https://groups.google.com/forum/#!forum/docker-user
4) join the #docker channel on Freenode

Since your question has been answered, I'm going to close this issue. Please take a look at points 3) and 4) from the list above in order to get help in the future.

**Comment by pavanadepu** [comment]
unclejack, thanks much for the response.

In my case, I have remove my container after executing the command "sudo docker run -d -p 5000:5000 training/webapp python app.py. With this I am assuming that there is no web application running.

And now I would like to start the container by running the webapp on a different port such as 5001.
So, when I tried the command ""sudo docker run -d -p 5001:5001", there shouldn't be any application running on port 5000. Correct me if my understanding is wrong.

I just wanted to make my container generic. That means, the web app should be running on the port that the user specified before starting a container.
