### ISSUE TITLE
Query on Docker Remote API

### ISSUE THREAD

**Issue by pavanadepu** [docker/docker#11515]
Hi Team,

I am trying to create a container using the Remote API "containers/create".
I am able to create the container successfully, but the container got created with a random name.

1. I would like to know the way to pass a name to the container while creating it.
2. Is there a way to override the existing container? 
    (I knew the workaround of removing the existing container and the recreating a new one. But, I    am looking for a single call which will override the existing container)

Quick help is very much appreciated.

Thanks,
Pavan

**Comment by thaJeztah** [comment]
Hi @pavanadepu, the GitHub issue tracker is more for reporting bugs and feature requests. 

Could you close this issue and ask you question on the #docker IRC channel, forums.docker.com or docker-user GoogleGroup?

**Comment by unclejack** [comment]
@pavanadepu Support for the remote API isn't provided directly via GitHub issues. Many similar issues have been reported in the past, but there was no code attached and providing any kind of assistance was impossible.

There are Docker client libraries in many languages. Please look at those to see how those libraries handle the features of the remote API you're interested in using. A good list of remote API clients can be found here: https://docs.docker.com/reference/api/remote_api_client_libraries/

Please post this question and similar questions on the docker-user Google group (https://groups.google.com/forum/#!forum/docker-user) or on the forums (https://forums.docker.com/).

This issue tracker is meant solely for the following: 1) reporting bugs, 2) requesting features, 3) reporting unusual behavior which might be a bug 4) submitting proposals and 5) sending pull requests to contribute changes to the code.

Please use the following resources to learn more about Docker and how to use it:
1) go through the tutorial at https://www.docker.com/tryit/
2) read the docs at https://docs.docker.com/
3) ask questions on https://forums.docker.com/ or https://groups.google.com/forum/#!forum/docker-user
4) join the #docker channel on Freenode

Since your question has been answered, I'm going to close this issue. Please take a look at points 3) and 4) from the list above in order to get help in the future.
