### ISSUE TITLE
Differentiate mounting and sharing

### ISSUE THREAD

**Issue by plista-ld** [docker/docker#11519]
Currently these is few if no distinction between mounting and sharing a volume:
1. every mounted file/directory is automatically shared
2. --volumes-from [container] does not allow to choose which shared volume to mount

It is somewhat mentioned in issue #9277, but not that explicitely.

Would it be possible to:
- add a specific option or flag for mounts that should not be shared ? (like "-v my_host_file:my_container_file:local")
- extent the -v option to mount from a container (like "-v src:container_id:src_container_path:dest_container_path)

**Comment by cpuguy83** [comment]
@plista-ld See the progress in #8484 which would indeed allow the `-v` syntax you are looking for.
Alternatively, today you can just lookup the the path in the container's inspect output and use it directly as a bind mount.

There is also #5910 which allows you to, when using selinux, specify a private volume, which cannot be used by other containers (and is enforced by selinux).

Closing since these issues are addressed elsewhere.
Thanks!

**Comment by plista-ld** [comment]
@cpuguy83 the inspect workaround works perfectly, thanks !
