### ISSUE TITLE
About simplifying docker test

### ISSUE THREAD

**Issue by x1022as** [docker/docker#11524]
Docker test is really a hard thing.almost every docker feature or bugfix will go with a test. Sometimes one line change in docker will take a lot of code in test. And docker is still in development, test is gonna be bigger and bigger.
Is it possible to reuse codes in test to simplify this, maybe could build a frame to fulfill with when new test needed. Thus it will be easier to add test and lines of code may be less.
Just a childish thought,If you think it's foolish, please ignore

**Comment by vivekchopra** [comment]
+kind/enhancement

**Comment by unclejack** [comment]
The integration-cli tests already have a library in place to avoid duplicating certain pieces of code. This will be improved further and there will be even less duplicated code.

The tests seem really big right now because there are a lot of tests. However, they could have been a lot bigger if we didn't have the library of helper functions to avoid duplicating the exact same code for every single test.
