### ISSUE TITLE
The commit API endpoint does not use structured responses.

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#11612]
**Problem**
 
The commit API endpoint does not use structed responses.
 
**Solution**
 
Create a new struct for the response type for `postCommit` in `/api/server/server.go` and use it to encode
and decode the response in the server and also on the client in `/api/client/commands.go`.

**Comment by jalev** [comment]
#dibs

**Comment by jamiehannaford** [comment]
@crosbymichael What sort of information is exposed by the "commit" job? Only an ID is being returned right now, but that is retrieved by [tailing the stdout buffer](https://github.com/docker/docker/blob/master/api/server/server.go#L540) - is what you mean? I don't think you mean fn return type, since all the other API functions use `error` too

**Comment by runcom** [comment]
@jamiehannaford yes, only the ID is exposed from the commit job. Take a look here for more info https://github.com/docker/docker/pull/11665/files#diff-44a527ea72ea9572e1cf71c7f1e2a0f0L1175

**Comment by jamiehannaford** [comment]
@crosbymichael @runcom @LK4D4 Pretty sure this can be closed now :)
