### ISSUE TITLE
Bitflag checking style.

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#11668]
There is some places where bitflags checked like:
`Mask&flag == flag`, but preferred style is `Mask&flag != 0`.
Find all such places and fix them

**Comment by jimmypuckett** [comment]
#dibs

**Comment by duglin** [comment]
From my comment in the PR:
'm not sure we want to do this. I may be overly paranoid so I'd want other maintainers to speak up here but this switch only works when the flag is a single bit. Now, in these cases you found that might be true but it assumes that someone has gone through the trouble of tracking down the actual value of each constant and verified that it is indeed just one bit.

Now, what worries me is that I tend to think of constants as things that we shouldn't need to examine too closely - meaning we shouldn't need to know their real value. So, let's say some day someone redefines one of those constants to actually be 2 bits instead of one. This not only breaks this abstraction that I think constants provide but the code as well. I'd prefer if we kept the code not knowing the exact value of the constant and treated it just as a bitmask that could in fact be multiple bits. But I welcome other's thoughts.

**Comment by jimmypuckett** [comment]
@duglin, I am really confused. I went to the docker "birthday party" where they asked us to help out by squashing some of the issues & making a pull request. I was told that the issues had been groomed, so I picked one. As for taking more time to squash, I'm really not interested in investing anymore time until the decision is made if it is wanted or not.

**Comment by duglin** [comment]
@jimmypuckett sorry about that and perhaps this one was already vetted and I'm way off base its just what I thought about as I was looking over the change.  Let's see what others say.

**Comment by tiborvass** [comment]
I think the intent of this issue is to make those flag expressions check whether a flag is set, instead of "it is the only flag set". So it removes exclusivity which is almost always what we want. The PR that will fix this issue will have to be reviewed taking @duglin's valid concern into account: if the intent was to actually check for exclusivity than that part should stay `== flag`.

@jimmypuckett don't worry this is indeed something desired we just have to make sure there are no special cases and if there are we'll comment on the PR. Thanks for taking care of this!

**Comment by duglin** [comment]
Some conversation in the PR https://github.com/docker/docker/pull/11702 too.
