### ISSUE TITLE
Documentation: Proofreading contributer guide docs. http://docs.docker.com/project

### ISSUE THREAD

**Issue by lolilo** [docker/docker#11787]
Fixing typos, grammar, concise wording, etc.

**Comment by lolilo** [comment]
#dibs

**Comment by rrarunan** [comment]
@lolilo when you do a PR, can you please add the `closes` keyword to it? Thanks!

**Comment by kytrinyx** [comment]
There have been some changes to the documentation site since this issue was opened.

According to the redirects.csv file /project now redirects to /engine/project, but I'm getting a 404.

https://github.com/docker/docs.docker.com/blob/master/redirects.csv#L12

Where does this documentation live now?

**Comment by thaJeztah** [comment]
@kytrinyx thanks for looking; the contributors guide now lives in https://github.com/docker/opensource/tree/master/docs

**Comment by LK4D4** [comment]
I think we can close this.
