### ISSUE TITLE
docker push/pull output is really expensive over the wire

### ISSUE THREAD

**Issue by fommil** [docker/docker#11971]
I was running `nethogs` while running `git pull` on a remote machine. It is eating up nearly 50K/s just to update the progress bar! That's pretty crazy. Can we please have the ability to specify a much lower refresh rate?

**Comment by fommil** [comment]
bah! ignore this, it was a rogue process doing the network traffic.

**Comment by jfrazelle** [comment]
good to hear :)

**Comment by fommil** [comment]
actually, I'm reopening. I'm seeing 20KB/s down my ssh channel just in the `Sending build context to Docker daemon` stage. Which is a bit excessive.

**Comment by jfrazelle** [comment]
ping @jlhawn @dmcgowan @dmp42

**Comment by jlhawn** [comment]
I believe that the progress bar updates at a rate that is dependent on how much data has been read through it (currently every 500kB) rather than at a particular time-dependent refresh-rate (say every 10ms) so the data transferred to refresh the progress bar on the client is directly proportional to how fast data is being read through the progress reader. If an image layer is being pulled/pushed at 50MB/s (probably pretty reasonable assuming a local private registry) then that would be (1refresh/500kb / 50MB/1s) 100 refreshes per second. If each progress bar refresh transfers 200 bytes then this would be equivalent to transferring 20kB/s just to refresh the progress bar. If you're doing a parallel pull of layers then multiply this by the number of parallel pulls.

How about we cap the number of refreshes to 10 refreshes per second? that would still seem pretty responsive for a CLI progress bar.

**Comment by fommil** [comment]
yup! Sounds good. The context I was transferring was about 5GB so your calcs sound about right.

**Comment by xiaods** [comment]
how about the status on this concern?

**Comment by LK4D4** [comment]
ping @aaronlehmann 
I know you worked on progress bar recently.

**Comment by aaronlehmann** [comment]
@LK4D4: Do you want me to work on this, or are you asking for an opinion?

**Comment by LK4D4** [comment]
@aaronlehmann just opinion. Is it doable, is it worth efforts?
