### ISSUE TITLE
Proposal:Docker inspect for the container that have same prefix of container name.

### ISSUE THREAD

**Issue by cc272309126** [docker/docker#11984]
I have some container whose prefix  are the same, so I want use docker inspect to get the data config once time. I think this feature are usefull.
it like below steps

1. `docker ps -a` 

```
CONTAINER ID        IMAGE                 COMMAND                CREATED             STATUS              PORTS               NAMES
5112fc65dff7        39225369ceae:latest   "/usr/bin/supervisor   2 hours ago         Up 2 hours                              test12345           
8d84cb3b47bb        39225369ceae:latest   "/usr/bin/supervisor   2 hours ago         Up 2 hours                              test123456          
87085a48a399        39225369ceae:latest   "/usr/bin/supervisor   2 hours ago         Up 2 hours                              test3455            
640f966a6490        39225369ceae:latest   "/usr/bin/supervisor   2 hours ago         Up 2 hours                              mad_engelbart       
19faa0f4f258        39225369ceae:latest   "/usr/bin/supervisor   2 hours ago         Up 2 hours                              sharp_ritchie       
e09e9e5174da        39225369ceae:latest   "/usr/bin/supervisor   6 hours ago         Up 6 hours                              test123  
```
2. `docker inspect test`.
this will return all data that has prefix "test" of the  container name.now it return Error: No such image or container: test
[]

thanks

**Comment by vdemeester** [comment]
Right now you can achieve this by doing something like : ``docker inspect $(docker ps -q --filter "name=test*")``. I think it's more composable than a command that would return you multiple result for only one input..

**Comment by duglin** [comment]
What's interesting is that the `docker inspect` command does allow for multiple container/image names to be passed in on the command line. So the question is whether it should treat "test" like there's an implicit wildcard at the end (e.g. test* ).  Its kind of a neat idea, however this could have pretty large ramifications because for consistency we should then probably make other (all?) commands work the same way (at least in the cases where it supports more than one name/id on the cmd line).  Or perhaps, leave "test" as it is today but support someone explicitly putting a * at the end.  This way if someone has "test" and "test2" but they want to just process "test" w/o touching "test2" they won't get unexpected results.
Something to think about....
@tiborvass any thoughts?

**Comment by calavera** [comment]
I agree with @vdemeester. Closing this as "won't fix".
