### ISSUE TITLE
shared IPC namespace does not share /dev/shm

### ISSUE THREAD

**Issue by thockin** [docker/docker#12046]
If I create container A, then create container B with --ipc=container:A, the two containers do not share a /dev/shm mount.  I think this will prevent POSIX shared memory from working.

@mrunalp
@vishh

**Comment by mrunalp** [comment]
@thockin @vishh The way to make it work in docker is to detect that container A has a user mounted /dev/shm and if yes then share it with B as well when --ipc:container:A is passed as an option.

**Comment by thockin** [comment]
It seems that docker already mounts /dev/shm by default for every
container, so no user-mounted special handling required?

**Comment by mrunalp** [comment]
@thockin The default mounted /dev/shm is within a container's mount namespace, so it isn't possible to share it with another container which has it's own mount namespace (without them sharing mount namespaces). Hence, the workaround of mounting an external /dev/shm which could then be bind mounted into multiple containers.

**Comment by thockin** [comment]
Oh, sure, yeah.  But that is an implementation detail :)

**Comment by phemmer** [comment]
POSIX IPC SHM uses `/proc/sysvipc/shm`, not `/dev/shm`.
`/dev/shm` is a vanilla tmpfs mount. Nothing more special about it than that. It's just standard practice for it to be there.

**Comment by thockin** [comment]
Man pages say /dev/shm, but my experience was that glibc starts
with/dev/shm and if not a tmpfs, scans /proceed/mounts for any tmpfs.

I have never heard of this other path - where did you find that?

**Comment by thockin** [comment]
https://www.technovelty.org/linux/shared-memory-on-linux.html

Ahh, it's the difference between sysV shm and POSIX shm.

**Comment by mrunalp** [comment]
@thockin Agree re: implementation detail :)

Not arguing about what is right but I was just going by TLPI :)
So, is it fair to say that Linux implements POSIX shared memory using /dev/shm?

From TLPI:
> POSIX shared memory allows to us to share a mapped region between unrelated
processes without needing to create a corresponding mapped file. POSIX shared
memory is supported on Linux since kernel 2.4.
> SUSv3 doesn’t specify any of the details of how POSIX shared memory is to be
implemented. In particular, there is no requirement for the use of a (real or virtual)
file system to identify shared memory objects, although many UNIX implementa-
tions do employ a file system for this purpose. Some UNIX implementations create
the names for shared memory objects as files in a special location in the standard
file system. Linux uses a dedicated tmpfs file system (Section 14.10) mounted under
the directory /dev/shm . This file system has kernel persistence—the shared memory
objects that it contains will persist even if no process currently has them open, but
they will be lost if the system is shut down.

**Comment by thockin** [comment]
As I understand it, yes.

**Comment by mrunalp** [comment]
#12159 created to implement this.

**Comment by runcom** [comment]
#12159 merged, I'm closing this

**Comment by cpuguy83** [comment]
Except unfortunately the change was reverted due to some unresolved issues causing CI to break, so I'll re-open. :(
See #15862
