### ISSUE TITLE
Docker API executable not found in $PATH

### ISSUE THREAD

**Issue by gladsonvm** [docker/docker#12105]
I am trying to run a django app in docker container.I can run it using cli. But when using api the response is executable not found in $PATH. I have tried changing ENV in api file also.

**Comment by unclejack** [comment]
@gladsonvm Support for the remote API isn't provided directly via GitHub issues. Many remote API related issues have been reported in the past, but there was no code attached and providing any kind of assistance was impossible.

There are Docker client libraries in many languages. Please look at those to see how those libraries handle the features of the remote API you're interested in using. A good list of remote API clients can be found here: https://docs.docker.com/reference/api/remote_api_client_libraries/

Please post this question and similar questions on the docker-user Google group (https://groups.google.com/forum/#!forum/docker-user) or on the forums (https://forums.docker.com/).

This issue tracker is meant solely for the following: 1) reporting bugs, 2) requesting features, 3) reporting unusual behavior which might be a bug 4) submitting proposals and 5) sending pull requests to contribute changes to the code.

Please use the following resources to learn more about Docker and how to use it:
1) go through the tutorial at https://www.docker.com/tryit/
2) read the docs at https://docs.docker.com/
3) ask questions on https://forums.docker.com/ or https://groups.google.com/forum/#!forum/docker-user
4) join the #docker channel on Freenode

Since your question has been answered, I'm going to close this issue. Please take a look at points 3) and 4) from the list above in order to get help in the future.
