### ISSUE TITLE
Replace Now() with daemonTime in integration-cli

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#12113]
You need to find all usages of `time.Now()` where it used to request some info from daemon(events) and replace it with `daemonTime(t)` like in https://github.com/docker/docker/pull/12090

**Comment by kostickm** [comment]
#dibs

**Comment by kostickm** [comment]
https://github.com/docker/docker/compare/master...kostickm:12113-replace-Now-with-daemonTime

The only other test using time.Now() to request info from daemon(events) was TestBuildCancelationKillsSleep in docker_cli_build_test.go. The test failed without the use of the containerID and regex changes, failing with "more than one container started." It now passes, but I wanted to get a second opinion on if the changes above look good/make sense. Thanks!

**Comment by LK4D4** [comment]
@kostickm It's better to create PR and discuss in form of review.

**Comment by kostickm** [comment]
@LK4D4 Okay I can do that!

**Comment by runcom** [comment]
@LK4D4 @kostickm that test was really reacy because it was not checking for its specific containerID it was creating.. test now passes and it's consistent on #12109 but it still need review

**Comment by kostickm** [comment]
@runcom Is this issue being covered then by #12109 ? There weren't any other tests in integration-cli using time.Now() in this way.

**Comment by runcom** [comment]
@kostickm no #12109 issue is not covering this issue but that failing test only

**Comment by kostickm** [comment]
@runcom Okay I'll wait until 12109 is merged and then look again.

**Comment by kostickm** [comment]
@LK4D4 @runcom Now that #12109 is merged the following are the only uses of time.Now() I see in integration-cli:

docker_cli_daemon_test.go:	if !time.Now().After(res.Time) {
docker_cli_daemon_test.go:	if !time.Now().After(res.Time) {

docker_utils.go:	dir := filepath.Join(dest, fmt.Sprintf("daemon%d", time.Now().UnixNano()%100000000))
docker_utils.go:	startTime := time.Now().Unix()
docker_utils.go:		if time.Now().Unix()-startTime > 5 {
docker_utils.go:		return time.Now()

It seems we can disregard the use in docker_utils.go, and docker_cli_daemon_test.go does not appear to be using time.Now() in the same way as #12109.

Is there any more to be done here? Should I update docker_cli_daemon_test.go to use daemonTime(t) instead of time.Now() in its current place?

**Comment by LK4D4** [comment]
@kostickm No, I think it's okay.
