### ISSUE TITLE
I can't access web app inside docker

### ISSUE THREAD

**Issue by arcticlion** [docker/docker#12131]
```
$ sudo docker run -d -P training/webapp python app.py
```

```
root@vpn:~# docker ps
CONTAINER ID        IMAGE                    COMMAND             CREATED             STATUS              PORTS                     NAMES
e3efda65c3e8        training/webapp:latest   "python app.py"     39 minutes ago      Up 39 minutes       0.0.0.0:49153->5000/tcp   stoic_pasteur 
```

When I enter `103.41.134.126:49153`(my VPS's Ip), but It doesn't response.

**Comment by wyaeld** [comment]
what does `curl localhost:49153` from the VPS shell do?

**Comment by arcticlion** [comment]
@wyaeld 

```
root@vpn:~# curl localhost:49155
Hello world!root@vpn:~# 
```

**Comment by duglin** [comment]
check your firewall

**Comment by arcticlion** [comment]
@duglin I use ufw

```
root@vpn:~# ufw allow 49155/tcp
Rule added
Rule added (v6)
root@vpn:~# ufw status
Status: active

To                         Action      From
--                         ------      ----
49155                      ALLOW       Anywhere
49155/tcp                  ALLOW       Anywhere
49155 (v6)                 ALLOW       Anywhere (v6)
49155/tcp (v6)             ALLOW       Anywhere (v6)
```

**Comment by wyaeld** [comment]
I can see that 49155 is open, and telnet shows I can connect, but your
initial issue shows the app running on 49153

**Comment by arcticlion** [comment]
@wyaeld Oh, It works! It's very strange. It doesn't response at all before.

To save this problem, I stop container before, then I run again and the port changed.

**Comment by wyaeld** [comment]
Ohh... the problem you are having is because of the `-P` flag.

If you use it by itself, it publishes any exposed ports onto something within the available range on the host.  It doesn't automatically publish them onto the same port.  However the range around 49150 seems to be a default somewhere.

If you are just getting started, you'll probably find it easier to explicitly publish the port onto the one you want to open with ufw.  Try using `-p 49155:whatever_your_image_exposes`

**Comment by arcticlion** [comment]
@wyaeld Thanks for help.
