### ISSUE TITLE
Docker must not require VT-X and must offer 32-bit versions for VR development

### ISSUE THREAD

**Issue by RepublicOfAppsLLC** [docker/docker#12149]
Hi,

Thanks for making boot2docker and this windows installer available, much appreciated!

I work at a studio developing backend services for VR gaming. I'm trying to setup dockerized versions of our backend services so that our fronted VR developers can test against these services on their Windows boxes.

The problem is that Occulus and most VR headsets REQUIRE VT-X to be turned OFF for decent performance. Whereas boot2docker and docker require it to be ON (by virtue of requiring it and also because they're 64-bit).

So we need a 32-bit version of boot2docker and docker to support any kind of Docker containers for VR development since most of the VR headsets require VT-X OFF and 64-bit docker/boot2docker require VT-X ON.

We need to test connecting to docker while the VR headset is running (to see the results of data returned from the dockerized services in the headset's HUD).

I don't know how to do this currently.

Please make a version of docker that is 32-bit and does not require VT-X.

This is a showstopper for us ...

Thanks!

**Comment by ahmetalpbalkan** [comment]
@RepublicOfAppsLLC I believe this issue belongs to https://github.com/boot2docker/boot2docker. Currently VT-X is required because Boot2Docker uses VirtualBox to run Linux VM on windows/mac. We can change this to Hyper-V but it also will not meet your needs. Do you have a suggestion here?

**Comment by unclejack** [comment]
@RepublicOfAppsLLC You haven't said anything about the CPU you're using or anything related to the problems you're seeing with VT-X enabled. You also haven't told us what version of Windows you're using. All of this is very relevant.

Is the performance problem related to a driver which is misbehaving with VT-X? Is there an actual benchmark we can run to produce numbers with VT-X on/off? How did you conclude that VT-X is actually the problem behind the issues you were seeing?

Should it really be faster with VT-X disabled, it's most likely because there's a bug somewhere. However, in every single case I've seen so far, the absence of VT-X makes things worse for VMs and for the host.

**Comment by RepublicOfAppsLLC** [comment]
This is on a brand new core i-5.  Just to be clear: both the cpu and the motherboard support VT-X on this machine.  And I turned it on and boot2docker ran and VirtualBox and it worked fine with VT-X on.

What runs slowly with VT-X on is Occulus VR which our developers are using.  It's Occulus VR that needs VT-X OFF to run efficiently on Windows (it's a complex graphics rendering need).  The problem is, we need both Occulus VR (with VT-X off) and boot2docker (with VT-X on) to run at the SAME time on same Windows machine so that we can test hitting web services inside a docker container from Occulus.  That's not possible since we can't have VT-X both on and off at the same time on the same machine.

The problem is that docker and boot2docker require 64-bit and the VT-X is required by VirtualBox *only* because of the 64-bit requirement of docker and boot2docker.  If docker and boot2docker supported 32-bit, then we could run VirtualBox with VT-X off and there would be no problem ...

Make sense?

What do we need to do to make both docker and boot2docker support 32-bit?

This is going to become a more frequent and widespread issue as more and more developers start working on VR ...

Any ideas?  :-)

Thanks!

**Comment by ahmetalpbalkan** [comment]
https://github.com/boot2docker/boot2docker/issues/620
https://github.com/boot2docker/windows-installer/issues/65

**Comment by unclejack** [comment]
@RepublicOfAppsLLC Ok, I understand. The immediate workaround you can use is to run boot2docker on a separate machine and hit the service on that machine.

I know this might not sound like anything particularly useful right now, but you'll still have problems with a non-VT enabled VM if you're as sensitive to performance as it seems you are. You're probably going to want to try to use a more powerful CPU and leave VT-x on.

As @ahmetalpbalkan has commented above, this issue is being tracked on the boot2docker repository. Docker itself is also going to be on multiple architectures (including x86) at some point, but it's something that's being worked on in multiple ways.

I'm going to close this issue as it's not a Docker bug. Please feel free to comment.
