### ISSUE TITLE
Docker selects wrong container based on name after extended container thrashing

### ISSUE THREAD

**Issue by rbair23** [docker/docker#12174]
I wish I had something more concrete and concise to report, however I have seen this phenomenon twice but have not nailed down what is happening. I have a system where I am creating and destroying hundreds of containers every day (5 at a time, probably 10 times an hour or so). I have a container called 'db' that is long lived (has been up 11 days now).

After some time (it just occurred to me, so about 11 days of this) when I do:

docker logs -f db

instead of getting the db logs, I am getting the logs for a different container. If I use the long or short id instead of the name, I get the correct logs.

**Comment by phemmer** [comment]
Sounds like it's matching a container who's ID starts with `db` (eg `dbb8937ac66c`) rather than one who's name exactly matches `db`. Can you confirm whether this is the case next time it happens?

I think I even recall an issue on this subject, but can't find anything.

**Comment by thaJeztah** [comment]
This sounds like that problem yes, in which case this would be a duplicate of https://github.com/docker/docker/issues/8069. That issue is closed in https://github.com/docker/docker/pull/9705, which will be in the next (1.6) release.

@rbair23 can you check if you have a (stopped) container who's ID starts with `db` (https://github.com/docker/docker/issues/12174#issuecomment-90904656)?

If you want to test the upcoming 1.6 release, the release-candidates for docker-1.6 can be found here; https://github.com/docker/docker/pull/11635#issuecomment-90205104

**Comment by rbair23** [comment]
Thanks for the pointer, that could very well be it. Right now it is back to working and docker ps -a doesn't show anything with "db" at the start of the id. This sounds totally plausible. I will take a look at the RC (and in the meantime, change the db name to be a bit longer).

Thanks!

**Comment by rbair23** [comment]
I had the misbehavior again today and verified that indeed, there was an id with "db" as the first two characters. I've changed my container name to be something less prone to collisions :-). Thanks!

**Comment by thaJeztah** [comment]
thanks for reporting back, @rbair23! docker 1.6 should be released soon, so you can get rid of the workaround :)
