### ISSUE TITLE
The ENV instruction should support a list of inputs

### ISSUE THREAD

**Issue by achanda** [docker/docker#12203]
An user might want to set a number of environment variables in their container. Right now, the way to do this is by something like:
```
ENV FOO foo
ENV BAR bar
ENV BAZ baz
```
This involves committing each intermediate image, which extends build time. This can be avoided if `ENV` could take a list of inputs. Then the previous example will reduce to
```
ENV ["FOO foo","BAR bar","BAZ baz"]
```
which is one commit.

**Comment by thaJeztah** [comment]
This is already supported via the `ENV foo=bar bar=baz` syntax, see [Dockerfile reference](https://docs.docker.com/reference/builder/#env).

Also, we're trying to avoid adding more JSON notation to the Dockerfile syntax.

Do you agree with closing this issue, because I think the `=` syntax will give what you're asking here?

**Comment by achanda** [comment]
@thaJeztah It does. Thanks for the pointer.

**Comment by thaJeztah** [comment]
You're welcome; the `=` syntax was a recent addition, and easy to overlook. Thanks for thinking along to improve Docker; it's appreciated!
