### ISSUE TITLE
Race condition with Python multiprocessing queues inside a docker container

### ISSUE THREAD

**Issue by nthiery** [docker/docker#12277]
While building a docker container for the SageMath software, we ran
into an issue involving Python's multiprocessing queues which are used
by our testing framework. The error is very systematic (always the
same three test files that fail). It very much sounds like a race
condition. However it's not clear whether the issue is in docker,
Python's mqueues, or in our usage of them in our testing framework.

Being stuck after quite some digging around we post it here in case
someone would have an idea.

Minimal steps to reproduce:
```
# Install docker (here for Debian / Ubuntu):
> sudo apt-get install docker.io

# Run a docker container with Sage:
> sudo docker run -t -i sagemath/sage su - sage
Last login: Thu Nov 27 15:28:05 GMT 2014
[sage@63182b1b1561 ~]$ uname -a
Linux 63182b1b1561 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

[sage@63182b1b1561 ~]$ cd sage
[sage@63182b1b1561 sage-6.4.1]$ ./sage -v
Sage Version 6.4.1, Release Date: 2014-11-23

[sage@63182b1b1561 sage-6.4.1]$ cat > bla.py << EOF
> r"""
>         sage: from sage.interfaces.qsieve import qsieve
>         sage: q = qsieve(next_prime(10^20)*next_prime(10^21), block=False)
> """
> EOF

[sage@63182b1b1561 sage-6.4.1]$ ./sage -t --verbose bla.py 
init.sage does not exist ... creating
no stored timings available
Running doctests with ID 2015-03-04-07-53-04-191d76e2.
Doctesting 1 file.
sage -t bla.py
Trying (line 2):    from sage.interfaces.qsieve import qsieve
Expecting nothing
ok [0.00 s]
Trying (line 3):    k = 19; n = next_prime(10^k)*next_prime(10^(k+1))
Expecting nothing
ok [0.00 s]
Trying (line 5):    q = qsieve(next_prime(10^20)*next_prime(10^21), block=False)
Expecting nothing
ok [0.23 s]


Trying (line 6):    sig_on_count()
Expecting:
    0
ok [0.00 s]
1 item passed all tests:
   4 tests in bla
4 tests in 1 item.
4 passed and 0 failed.
Test passed.
Process DocTestWorker-1:
Traceback (most recent call last):
  File "/home/sage/sage-6.4.1/local/lib/python/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/sage/sage-6.4.1/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 1839, in run
    task(self.options, self.outtmpfile, msgpipe, self.result_queue)
  File "/home/sage/sage-6.4.1/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 2159, in __call__
    result_queue.put(result, False)
  File "/home/sage/sage-6.4.1/local/lib/python/multiprocessing/queues.py", line 102, in put
    raise Full
Full
    Bad exit: 1
**********************************************************************
Tests run before process (pid=108) failed:
sage: from sage.interfaces.qsieve import qsieve ## line 2 ##
sage: k = 19; n = next_prime(10^k)*next_prime(10^(k+1)) ## line 3 ##
sage: q = qsieve(next_prime(10^20)*next_prime(10^21), block=False) ## line 5 ##
sage: sig_on_count() ## line 6 ##
0

**********************************************************************
----------------------------------------------------------------------
sage -t bla.py  # Bad exit: 1
----------------------------------------------------------------------
Total time for all tests: 0.4 seconds
    cpu time: 0.0 seconds
    cumulative wall time: 0.0 seconds
[sage@63182b1b1561 sage-6.4.1]$ logout
```

Various things we tried:

- Running the same thing under LXC: works smoothly

- Adding a micro delay in our testing framework before the failing
  line: works smoothly. Same thing if we query anything about the
  queue, like asking if it's empty.

- Running the container in privileged mode: same failure

- Trying several invited OS: debian "jessie", arch linux, Ubuntu: same
  failure

- Tweaking the parameters of the docker daemon to chose a different
  storage driver: with archlinux we tried: devicemapper, overlay,
  btrfs (on a dedicated partition). On mac with boot2docker: aufs.
  Same failure

- Checking the resource limits: running `lpcs -l` reported no real
  difference

- Toying around with /dev/shm (in privileged mode): size up to 2GB,
  owner, permissions: same failure

Help, pointers, suggestions most welcome.

Cheers,
                                 Nicolas

References:
- Sage ticket: http://trac.sagemath.org/ticket/17924
- Discussion on Sage's mailing list: https://groups.google.com/d/msg/sage-devel/8hWBzBMjKXI/5DfW8H3nKbAJ

PS 1: thanks for the hard work on docker; it's really handy!
PS 2: all the actual testing and exploring work was done by Vincent Neri.
PS 3: I am attending PyCon 15 until Friday 17th

/cc @hivert @rgbkrk @jpetazzo

**Comment by olliewalsh** [comment]
I'm not familiar with SageMath, and I'm pretty green when it comes to docker but the OS is my realm and I need python multiprocessing to work reliably in a docker container so I've taken a quick look into this :-)

Adding some debug info (write the pid and result to a file when `result_queue.put()` is called from `sage.docker.forker`): 2 processes are calling `result_queue.put()`!!!

As this is a `multiprocessing.queue.Queue` with `size==1` raising a `queue.Full` exception is definitely the correct behaviour. Docker and python multiprocessing are almost certainly not the culprits (at least not directly).

Next, it's interesting that this works:

    r"""
            sage: from sage.interfaces.qsieve import qsieve
            sage: q = qsieve(next_prime(10^20)*next_prime(10^21), block=True)
    """

Peeking at the source: If `block==True` then a different `sage.interfaces.qseive` implementation using `os.popen()` is used, if not then an implementation using `pexpect.spawn` is used... so it looks like a problem with the interaction of `sage.doctest.forker` and `pexpect.spawn`.
 
I also can see that it's using pexpect v2.x. In 2.x, `pexpect.spawn()` ignores SIGHUP (this is an option since v3.0 that defaults to True). I can also see that `sage.doctest.forker` uses SIGHUP to gracefully signal a child process to exit.
Upgrading to pexpect 3.x and modifying qseive to pass `ignore_sighup=False` to `pexpect.spawn()` may resolve the issue.

Also interesting is that this works:

    r"""
            sage: from sage.interfaces.qsieve import qsieve
            sage: q = qsieve(next_prime(10^20)*next_prime(10^21), block=False)
            sage: q.quit()
    """

`q.quit()` sends a SIGKILL to the `pexpect.spawn`  child process. Maybe this *should always* be done when disregading the `qseive` result. I donno - as I said, no experience with SageMath until now.

What I really can't figure out yet is, regardless of the `pexpect.spawn`/`sage.doctest.forker` SIGHUP behaviour, why both child processes call `result_queue.put()`! This doesn't appear to be possible from inspecting the source!
I also don't understand why this only occurs in a docker container...

Hope this helps, or at least gives some pointers as to what's happening.

**Comment by LK4D4** [comment]
@olliewalsh Wow! Nice research, thank you.
@nthiery Would you mind take a look?

**Comment by nthiery** [comment]
Oh wow, nice investigation indeed! Thanks so much.

I'll ping my fellow Sage dev that know better this area of the code.

**Comment by cpuguy83** [comment]
Any update here?

**Comment by nthiery** [comment]
Thanks for asking.

Following the suggestion here, some Sage dev managed to investigate and track down a race condition in our usage of Python's multiprocessing queue (which are used simultaneously by our test system and some functions being tested). There remain two similar issues that need to be tracked down. For details, see: http://trac.sagemath.org/ticket/17924

By the way: @embray mentionned to me the other day that they had encountered issues with a similar smell when running astropy under docker. So somehow running code using Python multiprocessing queues under Docker seems to be putting some specific pressure on it.

It might be good to better understand this phenomenon even if it does not seem to be a Docker issue per se. I let you decide if you want to close this issue or not at this point.

**Comment by cpuguy83** [comment]
Maybe it's a matter of having more resources available (or rather fewer default restrictions, as is the case with ulimit, probably).

**Comment by olliewalsh** [comment]
Didn't look like a limits issue. I'm guessing signals are delayed ever so slightly when running within a container, which has exposed a race condition

**Comment by nthiery** [comment]
Thanks @cpuguy83  and @olliewalsh for the insight.
We indeed checked the resource limits and they were almost identical with and without docker, and among the many experiments Vincent Neri tried, I am pretty sure he had some with thighter limits outside docker, and this did not trigger the issue.

**Comment by thaJeztah** [comment]
@nthiery @olliewalsh I see http://trac.sagemath.org/ticket/17924 is closed, is this ok to be closed?
