### ISSUE TITLE
Breaking out of Docker into real file system.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [docker/docker#12317]
I managed to map a volume then create a directory in it on my host os.
I then ssh'd into the docker image and cd'd into that directory.

Then I deleted the directory from my host os using del key on keyboard in nautalius.
This just moves it to the recycle bin.

when I did a cd .. in my terminal ssh'd to docker image it went up a level and I was able to traverse up more to get into home directory.

I can provide more information if required, just seems qwerky probably not a security concern.

**Comment by thaJeztah** [comment]
Thanks for reporting. Please, in future, and even if you only *suspect* it to be a security issue, report them via security@docker.com as described in the [README](https://github.com/docker/docker/blob/master/README.md#security-disclosure).

I'm going to ping some people to have some eyes on this;

ping @ewindisch @jfrazelle @crosbymichael

**Comment by ewindisch** [comment]
To exploit this you must already be root on the host, or have access to the Docker socket (which is equivalent to being privileged/root on the host)

**Comment by thaJeztah** [comment]
True; that was my initial impression as well, and it surely is a corner-case, still it doesn't sound good. Are there other situations where a folder gets moved?

**Comment by ewindisch** [comment]
Docker itself doesn't move the volume source directories. It's an operational concern for users to make sure they don't do this or have tools doing this. We should have this documented.

**Comment by thaJeztah** [comment]
> We should have this documented.

Agreed. I'm currently typing on my phone, but if you have thoughts already on how this should be put in words, that'd be great :)

**Comment by alban** [comment]
If any directory inside the volume belongs to a regular user, then a subdirectory can be moved on the host without being root. For example, even if the volume `/mnt/volume` belongs to root, if `/mnt/volume/tmp/bob` belongs to bob, then bob on the host can move `/mnt/volume/tmp/bob/data/`  to `/home/bob/backup/data/` without being root.

Workaround: if all volumes in Docker are separate partitions (or mounted with `mount -o loop`), then it should not be an issue because `mv` cannot move directories across devices.

A kernel fix is being prepared:
http://lists.linuxfoundation.org/pipermail/containers/2015-April/035788.html

**Comment by thaJeztah** [comment]
Thanks for the extra info, @alban!

**Comment by thaJeztah** [comment]
Added the "kernel" label (don't think it'll hurt), also;

/cc @cpuguy83 for any thoughts on https://github.com/docker/docker/issues/12317#issuecomment-92692061

**Comment by cpuguy83** [comment]
Yeah... not much to add.
I'm not exactly surprised that someone with access to a file can move it outside the bindmount.

**Comment by ewindisch** [comment]
Unless we're going to have a task to document this, I recommend we close.
