### ISSUE TITLE
docker cpu performance issue

### ISSUE THREAD

**Issue by blackfader** [docker/docker#12322]
hi all
background

one lvs have a xen virtual machine and a docker container ，I find xen cpu idle 80%，and docker container cpu idle is 0。

xen and docker pv and net IO is same。

docker container cpu performance far less xen cpu？

I test use sysbench

```
/usr/local/bin/octsysbench --test=cpu --cpu-max-prime=80000 --num-threads=24 run
```

docker container spend 30s and xen spend 35s，this explain docker cpu is better xen。

but run php-fpm，xen idle 80，docker idle is 0！

ps： docker container use cgroup cpu.cfs_quota_us limit cpu performance, docker version is 1.4.1

I use strace watch what spend cpu in php-fpm .

```
strace -t -p pid -c
```

I find php-fpm use Imagick->thumbnailimage  spend too much cpu time

```
53.92   2.734511     455751    6288000          0          0          6 Imagick->thumbnailimage               
37.07   0.142861      47620     766882          0          0          3 Imagick->thumbnailimage
```

first row is docker container ，this call Imagick->thumbnailimage   use 455751 cpu time，second row is xen ，this call  Imagick->thumbnailimage   use 47620 cpu time。

why cpu performance far less xen？

**Comment by unclejack** [comment]
@blackfader Please provide the full output of `docker info` and `docker version`.

**Comment by blackfader** [comment]
[root@w-docker23 098047a3092ca25192c0acc4579b5fc0e80fa69821f96cb4f4eafcc40545b2a5]# docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
[root@w-docker23 098047a3092ca25192c0acc4579b5fc0e80fa69821f96cb4f4eafcc40545b2a5]# docker info
Containers: 1
Images: 28
Storage Driver: devicemapper
 Pool Name: docker-253:1-1048805-pool
 Pool Blocksize: 65.54 kB
 Data file: /usr/local/docker/devicemapper/devicemapper/data
 Metadata file: /usr/local/docker/devicemapper/devicemapper/metadata
 Data Space Used: 3.713 GB
 Data Space Total: 536.9 GB
 Metadata Space Used: 6.423 MB
 Metadata Space Total: 12.88 GB
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.12.35-100.el6.x86_64
Operating System: <unknown>
CPUs: 24
Total Memory: 63.02 GiB
Name: w-docker23.add.bjcc.qihoo.net
ID: P7KS:BMJ7:GHHC:UDIV:VR3F:4RFP:6JOU:2XGE:VCTB:DAYI:XNIK:JDYL

**Comment by unclejack** [comment]
@blackfader Please read below:
1) You're using a custom kernel on RHEL 6/CentOS 6. RHEL6 and CentOS6 don't support custom kernels, only the official 2.6.32. We don't support such custom setups either.
2) The exact CPU accounting and usage depends on the environment. Docker does nothing to lower/increase it when doing simple processing, compared to running the code outside of a container. Performance depends on your hardware, kernel, system configuration - code running in a container gets pretty much the same processing performance as running that code directly on the host.
3) The memory accounting cgroups might have some overhead, but I don't think it's that high.
4) Were you running 3.12.35-100.el6.x86_64 both on the Xen domU and on the Docker host? If not, any comparison is pointless.

Please keep in mind that memory usage and CPU performance are pretty much the same in a Docker container as in an LXC container (or directly on the host) for pretty much any application. Docker doesn't do anything to lower/increase CPU performance over the features provided by the kernel (namespaces, cgroups).

This doesn't look like a bug or problem of any kind in Docker or in the kernel. I'm going to close this issue now because this issue tracker is for bugs, feature requests and proposals.

We can continue the discussion.
