### ISSUE TITLE
default parameters does not enable docker container monitoring

### ISSUE THREAD

**Issue by pbhavsar211** [docker/docker#12348]
we can no find that cpu, memory etc. monitoring is enables on docker container, however documentation says that we have to set custom parameters to make it enable.  "Generally, to enable it, all you have to do is to add some kernel command-line parameters: cgroup_enable=memory swapaccount=1."

how to add kernel parameters ?

**Comment by wonderflow** [comment]
I think what you want is in this document [ubuntulinux.md](https://github.com/docker/docker/blob/master/docs/sources/installation/ubuntulinux.md).

### Adjust memory and swap accounting

When users run Docker, they may see these messages when working with an image:

    WARNING: Your kernel does not support cgroup swap limit. WARNING: Your
    kernel does not support swap limit capabilities. Limitation discarded.

To prevent these messages, enable memory and swap accounting on your system. To
enable these on system using GNU GRUB (GNU GRand Unified Bootloader), do the
following.

1. Log into Ubuntu as a user with `sudo` privileges.

2. Edit the `/etc/default/grub` file.

3. Set the `GRUB_CMDLINE_LINUX` value as follows:

    	GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"

4. Save and close the file.

5. Update GRUB.

		$ sudo update-grub

6. Reboot your system.

**Comment by thaJeztah** [comment]
@wonderflow thanks for looking that up, I was planning to add the link but forgot.

It may be worth mentioning that the example may not work if you're running docker on a cloud provider, where kernel configuration may not be configurable.

@pbhavsar211 I think this should answer your question, also, check the documentation for the Linux distro you're running, because it's possible that the instructions are different for your distro.

I'm going to close this issue, because I think this is answered, but feel free to continue the discussion.
