### ISSUE TITLE
Containers Syslog message format.

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#12377]
Okay, there are some problems with Syslog format for containers. Some people want readability, some parseability.
Let's decide what we want before release, because I don't want mark `syslog` as experimental for whole 1.6.
There are examples of `journalctl` and ubuntu `syslog` outputs in #12329 
ping @jfrazelle @crosbymichael @icecrime @calavera @tiborvass @ibuildthecloud @wlan0 @x1022as

**Comment by ianblenke** [comment]
We would prefer json whenever possible for completeness and sanity. We mostly use "journalctl -f -o json" today, output through netcat and logstash/fluentd to elasticsearch for ELK. The applications themselves are setup to also log in json so they can be more easily indexed by elasticsearch for easier kibana dashboard views later.

**Comment by LK4D4** [comment]
ping @Sirupsen as log guru

**Comment by LK4D4** [comment]
Okay, after reading https://github.com/gliderlabs/logspout/blob/master/adapters/syslog/syslog.go#L33 I'm not okay with stdlib defaul format at all.
I propose to mark syslog as experimental and probably release it in 1.6.1 as stable.

**Comment by LK4D4** [comment]
Or I can try to fork stdsyslog tomorrow to have customizable formats.

**Comment by ibuildthecloud** [comment]
@LK4D4 what are your complaints with the stdlib format?

It's never possible to pick one format everyone agrees on, so probably the best approach is to just make it configurable.  Having said that I think we can easily choose a default right now that is acceptable and low risk to change at this point.  Then in 1.7 we can enhance it.

Syslog has the following fields

priority:  Priority is a combination of severity and facility.  The facility should be LOG_DAEMON.  It currently is LOG_USER, but I think DAEMON is more appropriate.  More info on that below. 

tag: Tag is some identifier for the user space program.  I propose the format be `argv[0]<CONTAINER_NAME>`.  So basically `docker<sad_einstein>`.   First, we should include the binary name in there so one can easily grep the logs for all docker messages.  Second, we should include the container name (not the ID).  Logspout https://github.com/gliderlabs/logspout/blob/master/adapters/syslog/syslog.go#L47 has chosen to log the name also and not the ID.  The big problem with the ID is that if I run some docker command, for example from a script, there is nothing I can put in the command that will help me associate the logs with that container.  For short lived container this is problematic as I would have to record the container ID somewhere.

hostname:  The hostname should be the hostname of the server.  This is mainly because stdlib syslog forces this to the system hostname.  If we were to fork the syslog library we could let this be an option and then log the container hostname, but we should really turn the facility to be LOG_USER in that case.  I think it makes more sense to log the server hostname.  I think for most people they will expect that hostname to be the server hostname.  If you are aggregating the logs it seems a bit more natural to me.  But, obviously there will be use cases for logging the container hostname.  In the future we should make this configurable.

pid: The pid of the docker daemon.  If we were to choose to log the hostname as the container hostname, then this should also be the container PID.  This isn't possible right now with the stdlib syslog.  I think it's fine to add an option for this later.

message:  The log message.  This should be just the log string.  In the future we can add an option to allow this to be a structured JSON blob.

In the end the output will look like

    Apr 10 02:49:33 ubuntu docker-1.5.0-dev<sad_einstein>[103905]: [1] 10 Apr 09:49:33.393 # Server started, Redis version 2.8.19

If this is acceptable to everyone I can easily put in a PR for these changes.

**Comment by LK4D4** [comment]
Your final format looks like current apart from ":" symbol. Do I understand right?

**Comment by x1022as** [comment]
Hundreds and  thousands containers produce logs continually. Maybe parseability of the whole logs is more important. This is what tags do, containerID will be great.
Once specific container log is picked out, readability is more import , json format may not be a good choice.

**Comment by thaJeztah** [comment]
> Your final format looks like current

IIRC, Current format uses container-id, not -name, which (@ibuildthecloud mentioned in another PR) is making it not really useful for RancherOS (and the reasons described in the comment above)

**Comment by ibuildthecloud** [comment]
@LK4D4 final format removes ": " and uses container name.  By removing the ": " it makes the binary<container_name> look like one coherent thing that is a single column.  The format is easily parseble with cut or awk.

I'm going to preemptively put in a PR for my proposed changes.  Just in case I'm not attentive in following this thread.

**Comment by ibuildthecloud** [comment]
Created #12391 because who doesn't love yet another PR about syslog

**Comment by phemmer** [comment]
Apr 10 02:49:33 ubuntu docker-1.5.0-dev<sad_einstein>[103905]: [1] 10 Apr 09:49:33.393 # Server started, Redis version 2.8.19

Why the angle brackets? I checked, and both syslog-ng and systemd-journald properly handle the tag with angle brackets, but it is still not a common practice to have a tag which includes them, and I worry that it may break parsers. Plus it just makes parsing more difficult.

Can we use a delimiter instead? For example a slash (`/`)? Using `/` as the delimeter has precedent as it's what postfix uses to identify its daemons (`postfix/smtpd`, `postfix/anvil`, etc...).

E.G.:

        Apr 10 02:49:33 ubuntu docker-1.5.0-dev/sad_einstein[103905]: [1] 10 Apr 09:49:33.393 # Server started, Redis version 2.8.19

----

I would also question the inclusion of the PID. I think the PID in this case is irrelevant as it's not the source of the message, it's the relay. But I think this is less of an issue.

**Comment by phemmer** [comment]
See also #12296 which has debate on using container name vs ID.
I personally don't like using container names, and I think there's going to be a lot of strong opinions on both sides (as is made obvious by the fact that the proposed format already is switching).

**Comment by ibuildthecloud** [comment]
@phemmer PID is added by golang, can't really change that at the moment.  I've updated #12391 to use forward slash and container ID.

**Comment by LK4D4** [comment]
I think we'll introduce some customizable format in future where you can get any container info.
