### ISSUE TITLE
Dockerfile should thow an error when detecting single quotes in a dockerfile

### ISSUE THREAD

**Issue by csaintc** [docker/docker#12381]
This works:
`FROM iojs:onbuild`
`VOLUME ["/usr/src/app"]`
`ADD ["./", "/usr/src/app"]`
`RUN npm install`
`EXPOSE 8081`

This doesn't work:
`FROM iojs:onbuild`
`VOLUME ['/usr/src/app']`
`ADD ['./', '/usr/src/app']`
`RUN npm install`
`EXPOSE 8081`

`INFO[0004] No source files were specified`

**Comment by thaJeztah** [comment]
Which version of docker are you using? I think *some* improvements were made in this area. However, no full resolution, because in some cases, it's not possible to determin if JSON was the *intended* format, or it just "looks like" JSON (ie, `[...]` is valid in shell)

This could well be a duplicate though, I'll check

**Comment by thaJeztah** [comment]
Hm, still looking, but the PR that I thought improved this, was in a different area. There's this, https://github.com/docker/docker/pull/11203#issuecomment-82004574 though. Will see if I can find other relevant issues.

To be clear; everything agrees that this could be improved, it's just that it's not always possible to detect properly (because the Dockerfile instructions support both "regular" and "JSON" formats. Automatically deciding which format is used is hard, because it potentially breaks Dockerfiles.

Right now; the strategy used is; if it's valid JSON -> treat as JSON, otherwise treat as "regular" syntax.

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
