### ISSUE TITLE
Why does docker need to run as parent for all containers it started? 

### ISSUE THREAD

**Issue by sunyc** [docker/docker#12402]
I couldn't find articles talking about this, can someone shed some light on? 

Because it seems pretty intuitive to me that if docker can self-discover containers running on the host will make upgrading it much easier.

**Comment by thaJeztah** [comment]
There are some existing discussions on this topic here https://github.com/docker/docker/issues/6851 and https://github.com/docker/docker/issues/2658, possibly more, that contain a lot of info on this.

If you need more information, please ask this question on https://forums.docker.com, https://groups.google.com/forum/m/#!forum/docker-user or in the #docker IRC channel.

I'm going to close this issue, because the issue tracker is intended for tracking bugs and feature requests, which this is not. Feel free to continue the discussion after closing
