### ISSUE TITLE
Docker should return the exit code of commands terminated by signal

### ISSUE THREAD

**Issue by metcalfc** [docker/docker#12448]
#354 appears to have fixed this for exit codes with commands that exit cleanly. #6734 seems to be focused on delineating between the docker command exit status and the command exit status.

Clean exits work as expected:

```
$ docker run debian:latest  /usr/bin/perl -e 'exit 1'
$ echo $?
1
```

If my process gets killed I expect an error code to match:

```
$  /usr/bin/perl -e 'kill -9,$$'
[1]    73715 killed     /usr/bin/perl -e 'kill -9,$$'
$  echo $?
137
```

But that isn't the case in a container:

```
$  docker run debian:latest  /usr/bin/perl -e 'kill -9,$$'
$  echo $?
0
```

**Comment by cpuguy83** [comment]
I'm not sure what perl itself is doing here, but you can't send SIGKILL to pid 1, which is what your perl process is running as.
If you look at the output of `docker ps -a`, the captured exit code is indeed 0.

**Comment by metcalfc** [comment]
![](http://www.legaljuice.com/files/2014/08/doh.gif)

Indeed. For future generations about to make the same mistake:

```
$  docker run debian:latest  bash -c "/usr/bin/perl -e 'kill -9,$$'; exit $?"
$  echo $?
137
```

**Comment by johnneil** [comment]
I think the rule that you cannot SIGKILL pid 1 (from 'man 2 kill') only applies to the actual host init process, not whatever command docker is running as pid 1 inside the container, because docker already handles gracefully pid 1 completing.

It would be nice if foreground 'docker run' as well as 'docker wait' were able to report any signal completion status from the initial docker run process.  The shell workaround above changes the signal information by translating to a terminal message plus exit status of 128 + signal which is harder to automatically detect and sending the docker run command through an intermediate shell requires careful quoting of reserved shell characters.

In particular, if foreground 'docker run' and 'docker wait' killed themselves with the exact same signal pid 1 completed with, then the command signal completion information would propagate to the caller completely unchanged.  Thus the caller gets the exact same completion information whether or not the command was run through docker.  if it is a compatibility problem for these commands to work this way, then enable the behavior with an option.

**Comment by cpuguy83** [comment]
@johnneil The key is you can't `SIGKILL` pid 1 from _inside_ the container. You can test this as such

```bash
$ docker run -d --name test busybox top
$ docker exec -it test /bin/sh
/ # # now we are in busybox
/ # ps aux
PID   USER     COMMAND
    1 root     top
    5 root     /bin/sh
    9 root     ps aux
/ # kill -9 1
/ # ps aux
PID   USER     COMMAND
    1 root     top
    5 root     /bin/sh
   11 root     ps aux

/ # # Ok, let's send TERM instead
/ # kill 1
$ # now we're out of the container because pid 1 exited
```

The right way to run a process in the container is to make sure it's _not_ wrapped in a shell command, or at least exec'd from the shell command... for exmaple `/bin/sh -c 'exec my_app'`, but of course keeping in mind you can't `SIGKILL` the process from inside the container.

**Comment by johnneil** [comment]
Ahhh... I was thinking this example was exiting with a signal:

`$ docker run nv:centos57 /usr/bin/perl -e 'kill -9,$$'`

But if you append another command to it it's apparent the kill has no effect.  In fact I cannot make the above example die  with any signal value.  So I now agree with the statement that this is not a bug.  

However, if you still want to detect signal completion of a docker run command natively, you have to write a container wrapper that runs the command in a child process and then communicates the signal completion to the  docker caller somehow.  Tricky.  It would be nice if docker handled this automatically when desired.

**Comment by cpuguy83** [comment]
Yes, this is going to be highly dependent on what's running.
Some stuff has default signal handlers, for instance if I run a ruby `while true do; sleep 1; end`, it will terminate on TERM/INT signals by default even as PID 1. It would seem Perl does not do this.
Some things do not load their default signal handlers if it is running as PID 1, and so they would need to be setup manually.

**Comment by jamesla** [comment]
Did anybody figure out how to make this work in the end?

I have the following docker-compose file (for simplicity).

```
version: '3'

services:
 test:
  image:
    debian:latest
  command:
    bash -c 'asdsdf'
```

Which gives the following output:

```
$ docker-compose up; echo $status
Starting test_1 ...
Starting test_1 ... done
Attaching to test_1
test_1  | bash: asdsdf: command not found
jsscbasebox_test_1 exited with code 127
0
```

Weirdly enough if I convert the docker file to do the command without bash -c IE

```
command:
    asdfsdf
```

Then the correct error is returned. The issue here is that doing it this way I can't chain multiple commands.

Did anybody come up with a solution to this problem?

**Comment by kidbrax** [comment]
@jamesla you could use the --exit-code-from switch as documented in https://docs.docker.com/compose/reference/up/ when using compose, but i don't think it works with docker run.
