### ISSUE TITLE
[windows] [FATA0000] Are you trying to connect to a TLS-enabled daemon without TLS?

### ISSUE THREAD

**Issue by moszeed** [docker/docker#12475]
I installed the new Docker 1.6 with Chocolatey
``
choco install docker 
``

then i want to pull the "node" image
``
docker pull node
``

but immediately after starting, following message appears
``
FATA[0000] Get http:///var/run/docker.sock/v1.18/images/json: dial unix /var/run/docker.sock: Es wurde eine Adresse verwendet, die mit dem angeforderten Protokoll nicht kompatibel ist.. Are you trying to connect to a TLS-enabled daemon without TLS?
``
- the failure is on "Powershell", "cmd" and "cmder"
- its happen with and without admin rights

so i`m out of ideas ..
thanks

**Comment by thaJeztah** [comment]
The error you're seeing, is that the Windows Docker client tries to communicate with the Docker Engine, but is unable to.

The installation via chocolatey will only install the Docker *client*, not the Docker Engine (daemon), which currently only runs on Linux.

This is also mentioned on the [chocolatey page](https://chocolatey.org/packages/docker)

> Docker client for Windows is not a Docker container engine for Windows. You can use this to manage your Linux machines running as Docker hosts at the moment until the containers support comes out in the next version of Windows Server.

If you don't have an existing Docker host running the Docker Engine, you can follow the instructions for the [windows installer](https://docs.docker.com/installation/windows/#installation), which will install Boot2Docker, a light-weight Linux virtual machine with the Docker Engine.

Alternatively, you can use [Docker Machine](http://docs.docker.com/machine/) to set up a Docker Engine locally (in a virtual machine) or "in the cloud", using various cloud providers. Docker Machine is still in beta, so it may have some hiccups :)

Hope this helps! 

I'm going to close this issue because I think this is not a bug, feel free to comment here if you think it should not be closed,

**Comment by ahmetalpbalkan** [comment]
![image](https://cloud.githubusercontent.com/assets/159209/7217301/fafeddc6-e5d6-11e4-82e0-f1e0620574d4.jpg)

It's very clear to me.

**Comment by thaJeztah** [comment]
@ahmetalpbalkan hm, yes. :smile:

I was looking at the [chocolatey](https://docs.docker.com/installation/windows/#references) part;

> If you have Docker hosts running and if you don't wish to do a Boot2Docker installation, you can install the docker.exe using unofficial Windows package manager Chocolately. For information on how to do this, see ...

If people don't read, I can't think of anything unless something like this is added:

> **This is only the Docker Client. You will need a working Docker Engine to run containers and use this software**.

Nothing we can do here.

**Comment by ahmetalpbalkan** [comment]
@thaJeztah chocolatey page also has:

> Docker client for Windows is not a Docker container engine for Windows. You can use this to manage your Linux machines running as Docker hosts at the moment until the containers support comes out in the next version of Windows Server.

**Comment by thaJeztah** [comment]
@ahmetalpbalkan yeah, hence my last "nothing we can do here" (reading-glasses-as-a-service ?) :smile:
