### ISSUE TITLE
Can we please have a static binary download of the docker client for OS X

### ISSUE THREAD

**Issue by far-blue** [docker/docker#12501]
As docker-machine replaces boot2docker there needs to be a new, easy and preferably scriptable way to pull a binary release of the docker client for OS X. I see no reason why the existing system via get.docker.io for Linux can't be expanded to provide the OS X client binary.

**Comment by tianon** [comment]
You mean like https://get.docker.com/builds/Darwin/x86_64/docker-1.6.0 or
https://get.docker.com/builds/Darwin/x86_64/docker-latest ?

**Comment by tianon** [comment]
(which I swear used to be documented somewhere, but I can't seem to find anything documenting those locations at the moment besides the release script itself)

**Comment by far-blue** [comment]
Yes, exactly something like that - except, you know, mentioned somewhere ;) You can't even browse the directory structure because the index pages either deliver a Linux-only script or a 404. Discoverability would be a great benefit :)

Still, I suppose on the plus side, if it is already there but just not mentioned then it is easy to close this issue! :D

**Comment by thaJeztah** [comment]
Hi @far-blue thanks for reporting this; this is indeed something that's needed.

There's already an issue for that here; https://github.com/docker/docker/issues/7974.

I'm going to close this issue, because I think this is a duplicate of https://github.com/docker/docker/issues/7974, please continue the discussion there!
