### ISSUE TITLE
docker ps display NAMES, it's an array, why is there still a docker rename API?

### ISSUE THREAD

**Issue by allencloud** [docker/docker#12538]
Hi, all
When I use a command `docker ps`, it displays like this with a column named NAMES

CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

NAMES means an array of names of a container, What kind of situation does a container have several names? 

If it indeed has several names, then what is the sense of  `docker rename` API ?

**Comment by allencloud** [comment]
I found that docker rename change an old name to a new name?

Then what kind of a situation can a container have several names?

**Comment by buddhamagnet** [comment]
Some clarification before I continue. Quite right, the container struct contains:

```go
Names      []string          `json:",omitempty"`
```

...but the recent API contains a rename command. Happy to work on this.

**Comment by buddhamagnet** [comment]
#dibs

**Comment by cpuguy83** [comment]
@allencloud It used to display more than just the canonical name of the container.
Easiest way is to show you:

```bash
$ docker run -d --name redisdb redis
$ docker run --name myapp --link redisdb:db my_app
```

In this case, the `redisdb` container would also be displayed as `myapp/db`.
But the additional names were removed because 1) take up too much space, and 2) doing this had some performance impact.

The column name is not updated to make sure we didn't break anybody parsing this output.

**Comment by cpuguy83** [comment]
@buddhamagnet I don't think there is anything actionable.

**Comment by allencloud** [comment]
Thank you very much, I think I can follow you now @cpuguy83
