### ISSUE TITLE
make docs failing with 404 error 

### ISSUE THREAD

**Issue by clnperez** [docker/docker#12571]
At Step 11 of building from the Dockerfile in docs/, the docker build fails with a 404 Not Found error. 

It looks like https://raw.githubusercontent.com/docker/distribution/ has an issue.

[snip]
Step 11 : ADD https://raw.githubusercontent.com/docker/distribution/${DISTRIB_BRANCH}/docs/index.md https://raw.githubusercontent.com/docker/distribution/${DISTRI
B_BRANCH}/docs/deploying.md https://raw.githubusercontent.com/docker/distribution/${DISTRIB_BRANCH}/docs/configuration.md https://raw.githubusercontent.com/docker
/distribution/${DISTRIB_BRANCH}/docs/storagedrivers.md https://raw.githubusercontent.com/docker/distribution/${DISTRIB_BRANCH}/docs/notifications.md /docs/source$
/registry/
INFO[0040] Got HTTP status code >= 400: 404 Not Found  
Makefile:89: recipe for target 'docs-build' failed

make: *** [docs-build] Error 1

More at http://pastebin.com/QVx0hLVX

**Comment by clnperez** [comment]
I was able to recreate this in two environments, one brand new on Ubuntu, and the other my normal dev env (running Fedora).

**Comment by clnperez** [comment]
@SvenDowideit

**Comment by thaJeztah** [comment]
@chinperez, this was a temporary problem, because a PR was merged that depended on a PR in the distribution repo.

The problem has been solved now, so if you update / rebase your fork, everything should work ok again.

Please let me know if the problem was solved, thanks!

**Comment by MWers** [comment]
That fixes it for me. 

I came across this issue when trying to checkout and build the version of the docs at tag `v1.6.0` (which is broken). Glad to see subproject versions explicitly defined in `docs/Dockerfile`, which should keep this from happening in the future. 

```
ENV COMPOSE_BRANCH release
ENV SWARM_BRANCH v0.2.0
ENV MACHINE_BRANCH master
ENV DISTRIB_BRANCH release/2.0
```

**Comment by thaJeztah** [comment]
Yes, it was a bit unfortunate, and the process may need a bit of tweaking. Now that all subprojects are included in the documentation, it can be a bit of a challenge to keep them in sync.

FYI; there's a separate branch for the documentation, which is used to release the actual documentation for the website and is "cherry picked" from the "master" branch (and allows us to push updates to the documentation in between releases).

I'm going to close this issue, because it should be resolved, but feel free to continue the discussion.

Thanks for reporting, it's much appreciated; if you have thoughts on how the process could be improved; we're always open for suggestions!

**Comment by clnperez** [comment]
Fixed, thanks @thaJeztah! I just used the make docs on my branch for PR #12573.

I haven't worked much with automated CI, so I'm curious about how the Jenkins build of the PR that broke this passed. Maybe there's a little extra that could be added there? That seems like the obvious fix, though, so if that was it, it would have been added by now probably. :)

**Comment by MWers** [comment]
Thanks for the heads up on the docs branch, @thaJeztah! I saw it mentioned in `docs/README.md` but I hadn't been using it for docs builds.
