### ISSUE TITLE
--restart don't restart on service docker restart nor on system boot up

### ISSUE THREAD

**Issue by Garito** [docker/docker#12593]
Hi!
I've 5 containers:
1.- Elasticsearch
2.- Logstash
3.- MongoDB
4.- Redis
5.- Nginx

All of them with --restart=on-failure:3

But if I restart the docker service with sudo service docker restart or I reboot my server the restart policy works in a random way (sometimes it restart some containers sometimes it doesn't)

Is the --restar policy the way to restart containers on startup or service restart?

Thanks!

**Comment by phemmer** [comment]
Please see the documentation: https://docs.docker.com/reference/run/#restart-policies-restart

**on-failure**: Restart only if the container exits with a non-zero exit status.

**Comment by Garito** [comment]
yeah I've readed this

but this http://docs.docker.com/articles/host_integration/ too

So seems that there is a weird situation here:

or we need a new policy like: anyway:3 to try to restart the container 3 times before stop no matter witch exit code is raise cause I don't feel confortable configuring a container that tries again and again to start up becase an error code and an always restart policy

or the host integration help is unacurated or wrong

dont' you think so?

In the same threat: how is the prefered way to start a container on boot? the process manager stuff?

Thanks

**Comment by cpuguy83** [comment]
@Garito `--restart=always` should be safe. If the container fails to restart it backs off gradually on the frequency for which it tries to start it.

I would also check and make sure you've started your containers correctly such that pid1 in the container actually responds to signals and exits properly on SIGTERM, otherwise it will get SIGKILL'd when docker restarts... and as such will have a non-zero exit value.

**Comment by Garito** [comment]
@cpuguy83 fair enought
Thanks a lot!
