### ISSUE TITLE
TestEventsLimit is too long

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#12675]
We can parallelize `run`s. Also better use just `true` as command. Also makes sense to use `--rm` to produce more events(4) with one run, so you need to run just 16 containers.

**Comment by fntlnz** [comment]
#dibs

**Comment by fntlnz** [comment]
I had some troubles to start only that specific test because in [docs/sources/project/test-and-docs.md](https://github.com/docker/docker/blob/master/docs/sources/project/test-and-docs.md#running-individual-or-multiple-named-testsd) it says to use something like 
```
TESTFLAGS='-check.f DockerSuite.TestBuild*' make test
```

In the end I managed to do it with:
```
TESTFLAGS='-test.run="DockerSuite.TestEventsLimit"' make test-integration
```

Am i doing something wrong/missing something?
