### ISSUE TITLE
System CA pool excluded when registry CA is used from /etc/docker

### ISSUE THREAD

**Issue by dmcgowan** [docker/docker#12756]
Currently if a user specifies a CA for a private registry in `/etc/docker/certs.d/REGISTRY/ca.crt`, the TLS configuration is configured to use a new CA pool with only that CA. If the registry does a redirect to a URL which is under a new domain with a certificate valid using the system CA pool but not the specified private registry CA, the operation will fail as an unknown certificate. The expected behavior would be to add the registry CA to the list of trusted roots along with the system roots.

See also distribution issue https://github.com/docker/distribution/issues/426

@ping moxiegirl @docker/distribution-maintainers

**Comment by phemmer** [comment]
I've run into similar issues myself on other projects trying to add custom certs. The difficulty is that the default cert pool is inaccessible ([`x509.systemRootsPool()`](https://golang.org/src/crypto/x509/root.go)). It might be good to raise the issue on the official golang tracker (ask them to export the function). Otherwise the code will have to be copied out.

**Comment by phemmer** [comment]
Opened https://github.com/golang/go/issues/13335 to track this upstream.

**Comment by stevvooe** [comment]
@phemmer I am not sure there should be separate cert pools...

**Comment by phemmer** [comment]
Not sure what you mean. Right now the pools are separate. We have one CertPool for user provided CAs, and one CertPool for the system provided CAs (which we don't have direct access to).
To fix this issue, we need to get access to a CertPool which contains the system provided CAs. We can then add user provided CAs to that CertPool instead of creating one from scratch.

**Comment by stevvooe** [comment]
@phemmer Right now, each registry has its own CA. I don't see why we don't just use the system CA for this.

There is an argument that one should only narrowly trust registry instances, so this model is good. However, it presents a massive challenge to the average user.

**Comment by phemmer** [comment]
> I don't see why we don't just use the system CA for this.

That's what the upstream issue I opened is for. It is not currently possible to access the system CA pool.

Unless you're saying use the system pool without the ability to add anything to it at runtime. Meaning users would have to install their CA certs in the system locations. If so, this wouldn't be feasible for clients, as a user might not have permissions to add certs to the system CA pool. It also means the CA would be trusted for things other than docker.

**Comment by stevvooe** [comment]
@phemmer You bring up an interesting point. 

To provide some context, I am looking at trying to reduce the incidence of this solution:

http://stackoverflow.com/questions/26710153/remote-access-to-a-private-docker-registry

Most users typically have access to root to add a cert to the system CA pool, but seem to get hung up around adding the cert individually for each registry host, which is understandable. I see this as the more dire of the situations, since people are using `--insecure-registry`.

That said, the go issue is spot on.

Although, they outright deleted my comment. Not sure why.

**Comment by tonyhb** [comment]
@dmcgowan @stevvooe the system cert pool is being exported as of this commit in golang: https://github.com/golang/go/commit/a62ae9f62fcfca02075b70e6e0aa757f4fd8f5ec

By the looks of things this will be included in go 1.7 which should enable us to fix this issue cleanly.

**Comment by aaronlehmann** [comment]
Thanks for pointing this out.

Sounds like another good reason to get #22000 sorted out so Docker can adopt newer Go versions.

**Comment by HuKeping** [comment]
Seems go1.7 will get this done

**Comment by brona90** [comment]
I don't quite understand how to get around the x509 error. I am using a mac. Is there a process someone can point me to for telling docker what certs to use default?

**Comment by stevvooe** [comment]
@brona90 This issue is really about fixing the way the cert chain is handled. If you're having problems using docker 4 mac, I'd recommend filing an issue over at https://github.com/docker/for-mac.

**Comment by justincormack** [comment]
@brona90 from the beta release next week (around 19 Sept) Docker for Mac should use your system certs, so if you install the certs on the Mac it should just work.

**Comment by jlhawn** [comment]
🎉 😍
