### ISSUE TITLE
TestDaemonICCPing

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#12908]
Seems to be breaking overlay build

https://jenkins.dockerproject.com/job/Docker%20Master%20(overlay%20on%20overlay)/574/console

ping @mavenugo

```
DockerDaemonSuite.TestDaemonICCPing                         2.30

----------------------------------------------------------------------
FAIL: docker_cli_daemon_test.go:625: DockerDaemonSuite.TestDaemonICCPing

waiting for daemon to start
daemon started
docker_cli_daemon_test.go:650:
    // Pinging another container must fail with --icc=false
    pingContainers(c, d, true)
docker_cli_daemon_test.go:1155:
    c.Assert(err, check.NotNil)
... value = nil

exiting daemon
waiting for daemon to start
daemon started
exiting daemon
```

**Comment by mavenugo** [comment]
@jfrazelle will take a look at it.

**Comment by jfrazelle** [comment]
no rush :) probably something weird

**Comment by LK4D4** [comment]
Failing on my machine every time.

**Comment by mavenugo** [comment]
@jfrazelle @LK4D4 Based on the debugging session yesterday, we figured that (in atleast a few scenarios), we were facing distro issues relating to `br_netfilter` as described and fixed in #11405 
I was initially worried if the ICCPing test is throwing false-positives. Though this newly introduced test is causing us all pain :), I think it is a good thing.

Please let me know if this issue is still seen outside of #11405. If not, should we close this in lieu of #11405 merging soon ?

**Comment by LK4D4** [comment]
I think it won't be closed by that PR. We need reconfigure our jenkins machines to `modprobe br_netfilter`.

**Comment by jfrazelle** [comment]
I can do this weekend ;)
