### ISSUE TITLE
Ubuntu upgrade documentation incorrect

### ISSUE THREAD

**Issue by Kryten0807** [docker/docker#12906]
I'm not sure where the problem lies, but the upgrade documentation for Ubuntu is messed up.

Here's what the docs say at (http://docs.docker.com/installation/ubuntulinux/#upgrade-docker):

```
Upgrade Docker
To install the latest version of Docker, use the standard -N flag with wget:

$ wget -N https://get.docker.com/ | sh
```

Executing this command when you have Docker installed does nothing - it simply downloads the contents of https://get.docker.com/index.html and saves it in the current directory as `index.html`.

If you execute the downloaded script, you get a warning message:

```
Warning: "docker" or "lxc-docker" command appears to already exist.
Please ensure that you do not already have docker installed.
You may press Ctrl+C now to abort this process and rectify this situation.
```

Being the cautious sort, I cancelled, then attempted to uninstall (via `apt-get purge`) docker before proceeding. This worked.

But I don't know if I needed to do that. The warning above seems to indicate that I did need to, but I wouldn't know that from the documentation.

First,

The command given in the documentation needs to be changed,

then either:

1. the documentation needs to advise users to uninstall docker before attempting to upgrade, or

1. the warning message in the install script needs to be amended (or dropped) if it's not accurate

Thanks

**Comment by pdevine** [comment]
This is quasi-related to issue #5228.  The install script doesn't support upgrades, and even if it did, it would most likely blow up on ubuntu/debian/mint because it would need to remove the lxc-docker-$version package first because of potential conflicts.

In the short term, the documentation should be updated to say "remove any previous versions of docker", but in the long term, we really need a sane strategy for upgrades.

**Comment by jmakanjuola** [comment]
Kryten0807,

You can upgrade docker by running the following commands below:

apt-get clean update
apt-get install docker.io -y
sh -c "curl https://get.docker.io/gpg | apt-key add -"
sh -c "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
apt-get update
apt-get install lxc-docker -y
apt-get clean update
docker versions

**Comment by cpuguy83** [comment]
@jmakanjuola docs should be updated

**Comment by jmakanjuola** [comment]
@cpuguy83 the pleasure is all mine :+1:

**Comment by pangloss** [comment]
Thanks @jmakanjuola for the instructions.

A warning though: they seem to be partially incorrect. The first 2 lines seem to pointlessly install docker 1.0.1. Otherwise the instructions seem ok. They can be simplified to just:

```bash
sh -c "curl https://get.docker.io/gpg | apt-key add -"
sh -c "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
apt-get update
apt-get install lxc-docker -y
```

Someone really should update the instructions on the website! :crying_cat_face:

**Comment by jfrazelle** [comment]
the above instructions are no longer relevant closing
