### ISSUE TITLE
Proposal: prevent root/users from running containers 

### ISSUE THREAD

**Issue by ianmiell** [docker/docker#12949]
I'd like to propose/explore the idea of preventing containers from running as root with a daemon config. This would be useful for a workflow we envisage for an environment where we could run Docker on desktops in a secure enterprise environment.

I've written a basic proof of concept which seems to work:

https://github.com/ianmiell/docker/tree/disallow_root

Does anyone have any views on the feasibility of this, or where this might go - for example, do people want to exclude more users in a list, or by uid? Suggestions welcome.

**Comment by thaJeztah** [comment]
Perhaps you can add more information on your use-case; I.e. Why disable running the container as root.

If security on the host is your concern, you may be interested in user namespaces, which is currently being worked on here: https://github.com/docker/docker/pull/12648

**Comment by ianmiell** [comment]
Hi, thanks for that. I'll have a look. Prima facie, it appears to address
my needs.

However, my understanding was that this was highly experimental, and likely
not to make it for a good while yet?

My use case is working at a security-paranoid place, there is a need to
reassure people that administrators can prevent a container running with
uid zero (and perhaps other uids). If this does the same (it seems to), and
is likely to happen I could forget about this :)

**Comment by thaJeztah** [comment]
I know @estesp is pushing hard to get this in (at least in an initial form), and many people are looking forward to it.

I'll leave this issue open for now, perhaps @estesp is able to add some information. I *suspect* however! that the maintainers will prefer https://github.com/docker/docker/pull/12648, because it's probably more flexible and largely will cover what you're proposing here.

Even if this proposal is rejected, thanks for taking the time writing this. We greatly appreciate people thinking along on how Docker can be improved!

**Comment by thaJeztah** [comment]
Let me also include @ewindisch and @diogomonica in this discussion, they are better suited for giving their opinion from a security perspective.

**Comment by ianmiell** [comment]
Hi @ewindisch! (We were talking last week).
This arose from a conversation we had internally following our call.
Obviously, the proposal in #12648 is a more complete solution, so if it's
going to happen anytime in the near future that would help us enormously. I
had thought issues with volumes etc were going to render it fairly
intractable.

**Comment by ewindisch** [comment]
@thaJeztah running as root in a user namespace is still much less secure than running as a non-root user. Some kind of restriction here is still worthwhile.

**Comment by thaJeztah** [comment]
@ewindisch thanks for kicking in; in that case, @ianmiell, perhaps you should expand the description a bit to make it a full "proposal", and add a full use case this may help the maintainers make a decision. (if I'm not mistaken, you're a writer, so :))

**Comment by ewindisch** [comment]
@ianmiell the problem I see with this patchset is that it doesn't also enforce '--cap-drop SETUID'. Without this, your users will be able to use setuid binaries to escalate to root, and using bind-mount volumes will be able to write to arbitrary files on the host. Ideally, I'd like to see '-u' automatically set '--cap-drop ALL' and require users to manually use '--cap-add', although this would break some Dockerfiles...

**Comment by diogomonica** [comment]
This is a great topic, and definitely worth pursuing.

I think there is something to be said for a configuration of this sort. I feel like @ewindisch idea of this being tied together with --cap-drop SETUID is a good idea. Are there other capabilities that we would like to drop?

My only issue with pursuing this path is the fact that now --disallow-root might break the principle of least surprise.

**Comment by ewindisch** [comment]
@diogomonica honestly, if we forbid CAP_SETUID, there would be no legitimate way to execute code as root, so none of the other root-level privileges would be usable. That's effectively the same thing as disabling all of the capabilities, so we may as well make it explicit.

I believe that authentication and authorization here provide means to address the issue of principle of least surprise, rather than supporting said suggested flag. It can be a negative experience to be unauthorized to perform a function, but it's one which users are acquainted with.

Rather than having granular authorization, I propose considering two user classes: "privileged" and "unprivileged". The unprivileged users would only be able to execute code with a non-root UID and --cap-drop ALL. Future updates would allow giving each user their own 'docker ps' and would provide UID mappings via user namespaces. Perhaps once we have user-namespaces have a third tier which is, "unprivileged-map-root"? However, the fewer user classes to support, the better.

**Comment by ianmiell** [comment]
I may have misunderstood (and am no security expert), but I'm wondering
whether we'd want to forbid CAP_SETUID in this secure scenario.

The scenario I'm envisaging involves an environment in which approved
images are created via a separate process from a limited set of rpms and
limited network access.

Hunting around my system I see that ping appears to be a suid program, for
example. I think our sec team will be (indeed are) comfortable with ping
being in docker containers provided it comes from approved rpms, and we
wouldn't want to prevent it being available.

I'm also wondering how apache (for example) would be started in this
scenario. A quick play and it seems it's non-trivial to get it to work.

**Comment by ianmiell** [comment]
Actually, a little more digging and hacking and it (apache as non-root)
seems quite do-able, if fiddly.

I think there may be a rich seam to mine of reference images that don't
need root capabilities but can run useful services that normally do.

**Comment by ewindisch** [comment]
Yes, with vetted images, you're right that the problem is constrained. It's just that once go down this rabbit-hole, we realize that we don't necessarily **need** to provide a curated set of images if, by default, they are disallowed root. (with the assumption the user is able to download and run arbitrary binaries as their *own* user anyway)

Just brainstorming here... but what about feature / security flags for images? That is, an unprivileged user pulls an image and it's marked "nosetuid"? Then, an admin may change the setuid flag for that image? Images signed appropriately could have such flags approved. Local admin to docker could flip the bit and allow a container image to be run +setuid by an unprivileged user.

User experience would be quite simple. Unprivileged users (something we don't have today) would be able to run any image as their user, given that it cannot do setuid, except where otherwise restricted by image policies. Local and remote admins would be able to approve certain images to run with this capability.

**Comment by ianmiell** [comment]
I've enquired internally, and the whole area of running services as root is solved, ie there are specific packages 

So disabling suid should not be a problem (for us) after all.

I like the idea of the security flags for images. It would be great to have control at that level, and we could switch on suid in a controlled 'build' context, and off in a less controlled one.

I'm not sure where this leaves us with my original PoC. Am keen to keep this discussion going, and happy to take direction on where my effort needs to go.

**Comment by ianmiell** [comment]
@ewindisch let me know where you'd like me to take this - proposal? further hacking? (see above comment)

**Comment by ianmiell** [comment]
@ewindisch @diogomonica @thaJeztah 

I'm reading through this doc with interest (there goes my weekend): https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.6_Benchmark_v1.0.0.pdf 

What would be great is if there were some kind of "--safe" flag for the daemon that would prevent run containers from doing damage. It would, eg:

- ensure all caps are dropped
- prevent sharing of resources with the host (mounts, priv ports, ipc, process, ulimit)

is this worth pursuing?

**Comment by NgoHuy** [comment]
I don't think we should drop all caps. I suggest we add default `docker` user when building image and it's default user when no `-u` option in args. But when `-u` option is appear and `-u root `  and `-v /:/mount_point` we fail to protect system.

**Comment by NgoHuy** [comment]
when `-u root` appears, it's only allowed when using `sudo` or root, right

**Comment by LK4D4** [comment]
user namespaces were implemented and can be used for high-security deploys.
