### ISSUE TITLE
docker login exits with fatal "inappropriate ioctl for device" when run from cloud-init

### ISSUE THREAD

**Issue by fvant** [docker/docker#12959]
I am running a script to run a container from a cloud-init script (so as root).

docker ps works fine but docker login always exits with that fatal error.
BTW i do have a .dockercfg file and provide only   -u 'myuser'  server   in the script.  (adding a -e and/or -p have same result)

Running the same script in a ssh shell works fine.  Could the code try to read from console, which is not there when script is run at boot??

docker info:

Containers: 0
Images: 37
Storage Driver: devicemapper
 Pool Name: docker-202:1-263638-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.452 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 2.298 MB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 3.14.35-28.38.amzn1.x86_64
Operating System: Amazon Linux AMI 2015.03
CPUs: 1
Total Memory: 996.3 MiB

docker version:

Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef/1.5.0

Environment: AWS

How reproducible:  consistently, duplicating the docker login line, behave the same

**Comment by fvant** [comment]
mkdir /home/root and exporting HOME as /home/root before doing docker login did the trick.

**Comment by adamkdean** [comment]
Following on from @fvant, the reason that works is because docker needs access to the `HOME` directory.

> when you log in, the command stores encoded credentials in $HOME/.docker/config.json on Linux or %USERPROFILE%/.docker/config.json on Windows. [Source](https://docs.docker.com/engine/reference/commandline/login/)

In my situation, I have a host machine which runs a Jenkins container with `/var/run/docker.sock` mapped through as a volume. This causes a few side effects from time to time, as while the client runs in the guest container, the commands are executed on the host. The most common issue this present is when you try to map a volume, as the docker run command is actually ran on the host.

With docker login, both the client and server appear to require access to the same directory/file, `$HOME/.docker/config.json`. The way I solved this was to run my Jenkins container with `--volume /home/username:/home/username`, and in my build script, `export HOME="/home/username"`. Now both the docker server (running on host), and the docker client (running in a guest container), are looking at the same io location.

Hope this helps anyone else confused by the matter.

**Comment by nyetwurk** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910822
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910823
Please, for those of you participating in this thread, go vote for the above bugs and mark them as affecting you, or they will never get fixed.

All of these workarounds do nothing towards getting the root cause addressed...
