### ISSUE TITLE
Container Cache quit the container

### ISSUE THREAD

**Issue by liwh** [docker/docker#12989]
Docker Version:  Docker version 1.5.0, build a8a31ef
Docker Info: 
```
Containers: 16
Images: 27
Storage Driver: aufs
 Root Dir: /data/service/docker/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 59
Execution Driver: native-0.2
Kernel Version: 3.10.0-1-tlinux2-0014.tl2
Operating System: Tencent tlinux 2.0 (Final)
CPUs: 16
Total Memory: 62.66 GiB
ID: TIW7:57I2:GTXU:PQ2T:4YWU:ATY4:CRIJ:F4OM:7LRO:7R56:TOIL:YRQU
```

When i start the container, The container Exited with the oom-killer.
I use the dmesg get the log:

Actual Results:
```
[1101553.629028] memory: usage 524288kB, limit 524288kB, failcnt 824
[1101553.629030] memory+swap: usage 525776kB, limit 1048576kB, failcnt 0
[1101553.629031] kmem: usage 0kB, limit 9007199254740991kB, failcnt 0
[1101553.629032] Memory cgroup stats for /system.slice/docker-d535c8c3f295bbfcd6482e05dad73dd2548807607a3378d9fd2131d23ed6dfdd.scope: cache:524288KB rss:0KB rss_huge:0KB mapped_file:0KB swap:1488KB inactive_anon:0KB active_anon:0KB inactive_file:342156KB active_file:182004KB unevictable:0KB
```

What is the problem,  and why the cache no recycle?

**Comment by unclejack** [comment]
@liwh The issue you've run into has nothing to do with Docker itself. It's only related to the kernel and the distribution you're using. The problem you've reported isn't a Docker bug and this isn't a general support forum.

The behavior you're seeing also depends on the configuration of that system, on the kernel version and on the actual distribution's configuration for the kernel. Depending on the actual configuration of the system involved, it might not be a problem at all.

Even if that is indeed a kernel problem, a distribution specific problem or both, this issue tracker isn't an adequate issue tracker for kernel and distribution specific problems which aren't directly related to Docker.

This is an issue tracker for Docker bugs, features and pull requests. Please take this into account when opening an issue.

This isn't a Docker bug, this is a question which is more appropriate for
1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker channel on Freenode.

1) and 2) should be better for longer conversations.

I'm going to close the issue now because this isn't a Docker issue or bug. The discussion can continue.
