### ISSUE TITLE
Can't set port mapping if in any other network namespace (host other container)

### ISSUE THREAD

**Issue by erkules** [docker/docker#13035]
When starting a container in another (container/host) network  namespace 

    $ docker run --rm -p 5000:5000 --name test -ti --net host ubuntu
    $ docker port test
    
    $ docker run --rm -p 5001:5001 --name test -ti  ubuntu
    $ docker port test
    5001/tcp -> 0.0.0.0:5001

Same as with attaching to another conatainers namespace.

I would like to be able to to the port mapping also for containers attaching another namespace

    $ docker -v
    Docker version 1.6.0, build 4749651

**Comment by paetling** [comment]
I am also seeing this issue. 
```
paetling ~ (master)*$ docker -v
Docker version 1.7.0, build 0baf609
paetling ~ (master)*$ docker info
Containers: 10
Images: 146
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 166
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.5-boot2docker
Operating System: Boot2Docker 1.7.0 (TCL 6.3); master : 7960f90 - Thu Jun 18 18:31:45 UTC 2015
CPUs: 8
Total Memory: 5.821 GiB
Name: boot2docker
ID: EZ5R:MXXS:SOGT:2TGW:MZUE:S6MM:GDBJ:6DLR:2TKY:MRRQ:HIQA:OEQN
Debug mode (server): true
File Descriptors: 61
Goroutines: 109
System Time: 2015-07-13T13:10:59.635886222Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
paetling ~ (master)*$ uname -a
Darwin Philips-MacBook-Pro-2.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
```
Steps to reproduce: 
1. `docker run  --detach=true docker.gamechanger.io/gcweb sleep 10000`
2. `docker run  --detach=true --net=container:90034320030c -p 8001:80  docker.gamechanger.io/gcweb sleep 10000`
3. `docker ps`
```
4c864bc07be0        docker.gamechanger.io/gcweb       "sleep 10000"          20 minutes ago      Up 20 minutes                               prickly_mayer              
90034320030c        docker.gamechanger.io/gcweb       "sleep 10000"          26 minutes ago      Up 26 minutes       80/tcp                  cocky_jang  
```

As you can see, the second container I created is not exposing any ports.  I think anytime you use something other than the default as the --net option, ports will not be forwarded to the host.  You specifically mention this with respect to --net=host](https://docs.docker.com/reference/run/#mode-host).  I think the fix is just as simple as making this more clear in the docs that this is not allowed

**Comment by jfrazelle** [comment]
you cant expose ports when using `--net=host` this is by design
