### ISSUE TITLE
Most links broken in: CIS Docker 1.6 Benchmark pdf

### ISSUE THREAD

**Issue by pmario** [docker/docker#13049]
Hi folks, 
I'm not sure if this is the right place to post it, but anyway.

Summary:

I did read [Understanding Docker Security and Best Practices](http://blog.docker.com/2015/05/understanding-docker-security-and-best-practices/) and downloaded: CIS_Docker_1.6_Benchmark_v1.0.0.pdf from CIS page.

It seems all links that contain hyphens are broken!

----

long version:

OS: Windows 8.1
PDF reader: SumatraPDF 2.5.2 and FF 27 build in ... same problem

I did read the blog post "http://blog.docker.com/2015/05/understanding-docker-security-and-best-practices/" and downloaded: CIS_Docker_1.6_Benchmark_v1.0.0.pdf from https://benchmarks.cisecurity.org/downloads/show-single/index.cfm?file=docker16.100  which by the way is overly complicated. 

On page 13, there is an external link:

 - looks like this: `http://www.projectatomic.io/docs/docker-storage-recommendation`
 - but links to: `http://www.projectatomic.io/docs/docker-%C2%AD%E2%80%90storage-%C2%AD%E2%80%90recommendation`

This creates a 404

It seems all links, that contain hyphens are broken. eg: page 14

 - looks like: `https://docs.docker.com/installation/binaries/#check-­kernel-­dependencies`
 - links to: `https://docs.docker.com/installation/binaries/#check-­‐kernel-­‐dependencies`

Docker docs page finds the right page, but doesn't jump to the anchor. 

I did test all links up to page 16.

**Comment by dksh** [comment]
Hi @pmario 

This document was published by the Center for Internet Security (cisecurity.org).
CIS Security Benchmarks are actually authored as community based projects so you can hop on over to their website and get involved there.

1. Go to https://benchmarks.cisecurity.org/community/projects/
1. Click "CIS Docker Benchmarks"
1. Click "Join Project"
1. Fill out the form and register.

Once you join you will be able to see the ticket I just created for this issue here
https://community.cisecurity.org/collab/public/index.php?path_info=projects%2F115%2Ftickets%2F82

> which by the way is overly complicated.
The CIS PDF documents can indeed be verbose. Any suggestions for clarity are welcome over on community.cisecurity.org
However, CIS benchmarks are the basis for some nifty audit automation tools so I encourage you to check them out!

**Comment by praving5** [comment]
We will look into it. Any issues with respect to CIS Docker benchmark should be reported to CIS and not here. In future, please write to feedback@cisecurity.org and cc pravingoyal101@rediffmail.com. For now, just re-construct the link as appropriate.

**Comment by pmario** [comment]
>Once you join you will be able to see the ticket I just created for this issue here
https://community.cisecurity.org/collab/public/index.php?path_info=projects%2F115%2Ftickets%2F82

Hmmm,  "registry wall" for a "public/index.php" .. similar to the download page :/  .. Sry I don't wan to join. 

Should I close this issue?

**Comment by cpuguy83** [comment]
Yes, let's close this, especially since it looks like CIS is working on it.
