### ISSUE TITLE
docker in docker consulting

### ISSUE THREAD

**Issue by blackfader** [docker/docker#13043]
hi all
    I want to run a docker daemon container in a docker machine。
    I success run a docker in docker model。
    but I have a question：
            docker daemon in container： docker images it is no images。
    So， I try 
    ```
    docker run -d  -v "/var/lib/docker:/var/lib/docker"  test/docker:1.6.0
    ```
    volume /var/lib/docker , 'docker daemon in container' have images in docker machine.

     but, is it any have problems in this way?
     example:
          I have two container 'docker daemon in container',build images at the same time, they write /var/lib/docker at the same time.
          and any else  problems?
      
     anybody played this?

[root@app08 script]# docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
[root@app08 script]# docker info
Containers: 1
Images: 402
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.12.35-100.el6.x86_64
Operating System: <unknown>
CPUs: 24
Total Memory: 63.01 GiB
Name: xxx
ID: PAV5:HCVI:3AA7:AAUV:HMU4:AB5W:VV4A:AM5O:2URC:F655:R2D3:5ND5
[root@app08 script]# uname -a
Linux app08.add.bjdt.qihoo.net 3.12.35-100.el6.x86_64 #3 SMP Wed Jan 14 17:38:58 CST 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cpuguy83** [comment]
I"m not sure I fully understand this but....
Bind-mounting the docker socket into a container is not docker-in-docker. You are connecting to the host's daemon over this socket, as such you will see all the images/containers from the host.

To run docker-in-docker you also need to use `--privileged`

For docker support please see #docker on IRC or docker-user mailing list.

Closing since this is not a Docker issue.
