### ISSUE TITLE
Support setting OOM score

### ISSUE THREAD

**Issue by phemmer** [docker/docker#13116]
One thing that would be useful is prioritizing certain containers when it comes to the OOM killer. Right now, docker only supports a simple on/off. It would be much more useful to be able to score containers, so that if a process has to be killed, it favors certain containers.
This behavior is controlled by the `/proc/$pid/oom_score_adj` tunable. A score of `-1000` disables the OOM killer, and the max score of `1000` makes it a near certain target for the OOM killer.

Additionally, since `-1000` disables the OOM killer, this setting would deprecate the current `--oom-kill-disable` parameter.

**Comment by thaJeztah** [comment]
For reference; earlier discussion on this topic here: https://github.com/docker/docker/issues/12528.

The `--oom-kill-disable` flag was introduced in https://github.com/docker/docker/pull/11034, and isn't in a release yet, so ***if*** this is something that's wanted, it would be preferable to decide on this **before** the 1.7 release, to prevent having to introduce *and* deprecate that flag.

/cc @HuKeping @hqhq @thockin @LK4D4

**Comment by hqhq** [comment]
Yes, `oom_score_adj` is more flexible, technically is't per process, while `oom-kill-disable` is per cgroup, but we can hack `oom_score_adj` to make it per cgroup because it will be inherited to child processes.
I'm +1 to add `oom_score_adj ` support, but I don't think it would deprecate `oom-kill-disable`, because `oom-kill-disable` is more obvious and clear for what it does. And I think kernel support both of them for some reasons, I don't remember either of them is for backward compatibility.
