### ISSUE TITLE
Attempt to write a readonly database: attempt to write a readonly database

### ISSUE THREAD

**Issue by jwaldrip** [docker/docker#13122]
Getting the following issue when trying to run a container. `/var/lib/docker` is mounted as a drive, it is not on the main disk.

```
core@ip-10-21-2-62 ~ $ docker run -it ubuntu bash
Unable to find image 'ubuntu:latest' locally
Pulling repository ubuntu
07f8e8c5e660: Download complete
e9e06b06e14c: Download complete
a82efea989f9: Download complete
37bea4ee0c81: Download complete
Status: Downloaded newer image for ubuntu:latest
FATA[0016] Error response from daemon: Attempt to write a readonly database: attempt to write a readonly database
```

**Comment by vidarh** [comment]
I also see this.

Log output:
Jun 04 12:06:02 ip-172-31-36-75.ec2.internal dockerd[513]: time="2015-06-04T12:06:02Z" level="error" msg="Handler for POST /containers/create returned error: Attempt to write a readonly database: attempt to write a readonly database"
Jun 04 12:06:02 ip-172-31-36-75.ec2.internal dockerd[513]: time="2015-06-04T12:06:02Z" level="error" msg="HTTP Error: statusCode=500 Attempt to write a readonly database: attempt to write a readonly database"

I have confirmed that /var/lib/docker/linkgraph.db *is* writeable by using the sqlite command line client and creating a test table in it.

This is on CoreOS 647.0.0. docker --version:
Docker version 1.5.0, build a8a31ef-dirty

I've unfortunately been unable to test on 1.6.x

**Comment by vidarh** [comment]
Digging a bit more, the Docker daemon in our case is holding two file handles to *two different* /var/lib/docker/linkgraph.db:

    # ls -la /proc/513/fd/ | grep linkgraph
    lrwx------ 1 root root 64 Jun  4 12:18 113 -> /var/lib/docker/linkgraph.db
    lrwx------ 1 root root 64 Jun  3 16:57 3 -> /var/lib/docker/linkgraph.db

lsof shows these (and repeated entries for every thread):

    docker      513 31346             root    3u      REG              202,9      5120       5237 /var/lib/docker/linkgraph.db
    docker      513 31346             root  113u      REG             202,16     79872         13 /var/lib/docker/linkgraph.db

As you can see these have two different inodes (5237, 13). stat gives:

    File: '/var/lib/docker/linkgraph.db'
    Size: 79872           Blocks: 168        IO Block: 4096   regular file
    Device: ca10h/51728d    Inode: 13          Links: 1

Using debugfs (debugfs -w /dev/xvda9 -R 'link <5237> /test.db', after the equivalent with our Docker-partition on /dev/xvdp failed and I got suspicious it might be a different drive) it looks like the problem is that docker has managed to start before the /var/lib/docker partition was mounted. It then holds a /var/lib/docker/linkgraph.db open already, /var/lib/docker is mounted on top, and another instances of linkgraph.db is opened.

(sqlite /test.db afterwards revealed the database was empty other than the schema)

So anyone seeing this likely have a bug in startup dependencies between Docker and the mount. 

After debugging this I'm unsure if it's sensible for Docker to try to handle this better or not. 

Simply trying to re-open linkgraph.db plus emitting a warning might be a simple defensive step against the effects of this and a number of similar problems (or at least would make it possible to recover from without restarting docker by dumping/re-creating/fixing the sqlite file), though I'm not sure what risks there might be with masking this problem.

**Comment by nskforward** [comment]
Reproduced during access to SQLite3 file by PHP

root@vm:/var/www/mfloor/docker# docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:38:58 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:38:58 2016
 OS/Arch:      linux/amd64

root@vm:/var/www/mfloor/docker# docker info
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 36
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 997.1 MiB
Name: vm.youplace.net
ID: 44DW:CLXF:PDQ7:I44S:42KF:SNKN:WW3M:SW3V:LETQ:5RN2:D7P7:AEL5
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

**Comment by thaJeztah** [comment]
@nskforward This issue is about the SQLite database that Docker itself used to store links between containers as of docker 1.10, we no longer use a SQLite database for this (see this PR https://github.com/docker/docker/pull/16032), so this issue can be closed

For your error, I suspect you have the SQLite database stored in a location where the PHP process doesn't have write-access. It's not a bug in Docker.
