### ISSUE TITLE
Proposal: Add "runtime" labels support when building

### ISSUE THREAD

**Issue by vdemeester** [docker/docker#13178]
## Background

External tools, like [docker/compose](https://github.com/docker/compose) are currently using name convention to identify image they build as part as their workflow, in order to find them back and manage them. As proposed in this [issue #1403](https://github.com/docker/compose/issues/1403), it would be easier and more flexible to use *labels* for this use cases.

The current way to add labels to images are to add ``LABEL`` lines in ``Dockerfile``. This proposal aims to add a flag(s) to the ``build`` command to allow settings labels to images when building them **and** support this in the API as well (so external tools can work with it).

Although the main use case that comes in mind for me is the use in external tools like compose, I think it's good to be abel to add image label as part of the building, that weren't defined in the ``Dockerfile``.

## Syntax

To be coherent, the syntax should act the same as when using the ``run`` command (``--label`` and ``--label-files``).

```bash
$ docker build --label key=value -t myimage .
$ docker build --label key1=value1 --label key2=value2 -t myimage .
$ docker build --label-file=mybuildinglabels -t myimage .
```

Let me now how you feel about that. I can work on it if this is something the community finds it useful.

**Comment by ibuildthecloud** [comment]
I believe we talked about this a bit during the initial label implementation and I agree it is a very useful feature.  The only way to add Labels to an image today is through a Dockerfile or a commit.  I've never tried the commit and the the commit CLI doesn't support it, but theoretically through the remote API it works.

I agree with the design of this proposal, as it matches `run`. :+1:

**Comment by thaJeztah** [comment]
Thanks, and I'm +1

We will need to decide whether the command-line labels will be *merged* or will *replace* the existing `LABEL` definitions in the Dockerfile. 

For the *compose* use-case, the labels should be *merged* (compose should not replace user defined labels with the compose labels). (Also, obviously, compose uses the Remote API, not the CLI)

**Comment by vdemeester** [comment]
@ibuildthecloud I'm not sure it's possible using the API for the commit, or at least it's not documented in https://docs.docker.com/reference/api/docker_remote_api_v1.18/.

@thaJeztah Yes, we need to discuss how /label conflict/ would be handle. If a ``--label`` from ``docker build`` takes over the ``LABEL`` definition or not — and if not, how should docker react (error or /warn and ignore/). We also need to discuss if it should be configurable or not (I would say no, adds complexity for nothing).

I think most of the time, ``LABEL`` defined in the ``Dockerfile`` should not be overridden by the ones defined when building. Note that, currently, the ``docker run --label`` overrides the value specified in the image — not sure it's important for this though.

**Comment by derfred** [comment]
+1, I have a couple of internal images that combine to repositories. One contains the application code, the other the infrastructure code. I would like to embed the git sha1's as labels in the resulting images

**Comment by coolljt0725** [comment]
What I concern about this is: we use a Dockerfile to distribute our application and we should make sure everyone use the same Dockerfile should build the completely same image, but if we can use a `--lable`  on build, different user can build an image with different `label`

**Comment by vdemeester** [comment]
@coolljt0725 Yes, that's why the idea would be to be able to add lables, and not override them (the *merged* vs *replaced*). That way you can just add metadata for a given image not removing or replacing some.

**Comment by vdemeester** [comment]
#dibs on this
I'll work on that this week and submit a PR to discuss on the possible(s) implementation(s) there.

**Comment by thaJeztah** [comment]
@vdemeester thanks! make sure to mention the "merge" vs "override" issue when creating the PR so that that is not overlooked during the design review :)

**Comment by vdemeester** [comment]
> I'm sorry but I'm going to be -1 on this one for a single reason: if we can have a command-line flag to basically provide additional instructions, why not ENV? EXPOSE? VOLUME? I don't want to open this door.

Closing this one for the same reason as th PR :wink:

**Comment by mrichard** [comment]
just curious if this is in 1.8.1?

**Comment by kleptog** [comment]
@mrichard no, it looks like this isn't going to happen. This feature has been rejected by @icecrime IMHO without taking into the consideration the use cases. It can be worked around by using a Makefile to generate the Dockerfile and building that.

Now, maybe he has a point and rather than adding random labels we just want `docker build` to have a `--version` option to allow you to add versioning information to the image. But that would mean a whole lot more work than what this feature request required (for example, you'd want to be able to filter on it).

**Comment by thaJeztah** [comment]
@kleptog docker 1.9 will allow you to set build-time args, so this will
be possible:

```Dockerfile
FROM ubuntu:14.04

# Define the "foo" arg and set a default value
ARG foo=defaultfoo

# Create a label "mylabel" and set it to the value of $foo
LABEL mylabel=$foo
```


Building without passing a build-time arg:

```
docker build -t foo .
docker inspect foo
```

produces:

```
...
"Labels": {
    "mylabel": "defaultfoo"
},
...
```

And specifying a custom value:

```
docker build -t foo --build-arg foo=commit123 .
docker inspect foo
```

produces:
```
...
"Labels": {
    "mylabel": "commit123"
},
...
```

**Comment by kleptog** [comment]
Oh nice, that's much better and solves the problem nicely. and I see that 1.9 is scheduled for end of this month. This release is full of nice new features!

**Comment by tony-spataro-rs** [comment]
Excellent! Thanks much for your consideration; this will fit the bill nicely (and is more generally useful than a `--label` flag).

**Comment by jantman** [comment]
For what it's worth, this solution does not fit my organization's needs because it requires knowledge of the labels inside the Dockerfile.

Our use case is that we have a generic ``docker-image-build`` Jenkins job that builds any repo with ``./Dockerfile`` in it, and pushes it to our registry. We want these images labeled with the repository, commit, and build URL.

If labels are really supposed to be _metadata_, it doesn't make sense to me to define them inside the Dockerfile, where they really become part of the artifact itself, not metadata about it.

**Comment by hansenms** [comment]
@jantman I just want to echo your comments. We build Docker images as part of our CI process. We would like them labeled with say the SHA1 hash of the git repo (or other meta data) to make debugging, etc. a bit easier. I would think that this is a pretty common use case, but can't seem to find any good ways to do it. What would be nice if one could do something like:

    LABEL com.mycompany.myproduct.sha1=$(git rev-parse HEAD)

Or somthing like that.

**Comment by jantman** [comment]
@hansenms that can be done, but it's a bit of a pain as it needs to be declared in the ``Dockerfile``, i.e.:

```
ARG git_commit
ARG git_url
ARG build_url

# regular Dockerfile stuff here

LABEL com.myorg.commit=$git_commit com.myorg.repo=$git_url com.myorg.build_url=$build_url
```

and then build with a command like ``docker build --build-arg git_commit=$COMMIT --build-arg git_url=$URL --build-arg build_url=$BUILD_URL``

What I'd really like is for ``docker build`` (and the relevant API) to accept arguments for labels, so that I could just ``docker build --label com.myorg.commit=$COMMIT --label com.myorg.repo=$URL --label com.myorg.build_url=$BUILD_URL`` and not have to put anything label-related in the Dockerfile; that should be handled internally to Docker. I really feel that calling this "metadata" is inaccurate; I want to be able to add metadata _to_ a Docker build, not need to have it be an explicit part of the Dockerfile. The way it stands now, if we want to add a new standard label to our Docker containers, we need dozens of teams to update tens - soon to be hundreds - of Dockerfiles to accept the new arg. Or else we need to programmatically edit Dockerfiles in the build process, which means we're not actually building the source we say we are...

**Comment by hansenms** [comment]
@jantman thanks. I was just looking at that. I had docker 1.8 installed, and the arguments were introduced in 1.9 (I think), so I has missed that. Still, it is not quite what I wan't either. Say for instance that you have multiple git repos that are cloned and compiled for a stack that you are putting together in an image. Now you need to first pull those git repos locally before building the docker image so that you can pass the arguments to the build command. Sure, it can be done, but it is ugly and error prone. Better would be to let the build process pull various labels and version information to label the images with those values.

I will probably pursue something with the ARGs, but still, I think it is a bit ugly. In any case, thanks for your comments. It was helpful.

**Comment by jantman** [comment]
Sure! And yes, the build args were introduced in 1.9. We were still running 1.6 on the Docker build slaves for our CI system, and had to upgrade for this.

**Comment by hansenms** [comment]
@jantman I actually already discovered a problem with using the ARGs for the situation above. Scenario is this: during build, my image clones a few gitrepos and in order to LABEL the image with the version or SHA1 hash of those repos, I pull them locally and then pass the SHA1 hash in with an ARG. However, in one case, one of the repos changed between when I did the local pull and when I did the docker build, so now the LABEL doesn't match the actual code that was built in the image. 

What I really need is a way to add metadata (LABELs or something else) to reflect specific build events appropriately. Passing it in on the command line is really not the best option no matter how it is done.

**Comment by xeger** [comment]
@hansenms bit tangential to this issue, but I have some advice about your race condition w/ git repositories.

As you're probably aware, cloning private git repositories inside an image build is inadvisable for security reasons; in addition, if your image's dependencies must be fetched both before and during the image build, one encounters the race condition that you have described.

For both of these reasons, I have adopted the Golden Rule of building private Docker images: fetch your dependencies _before_ of the image build; `COPY` them and install them during the build.

For instance: Ruby on Rails projects could do a `bundle package` before invoking `docker build`, allowing for a much wider range of SSH keys or other Git options to be used. Node projects would perform `npm install` before building and copy `node_modules` into the build, etc. Whatever package manager you're working with, likely has a way to pre-fetch dependencies.

Needless to say, applying the Golden Rule requires you to run some shell commands on the host before building the image; it isn't suitable for DockerHub Automated Builds, but it works great with CI environments.

In your case, fetching the dependencies once would also ensure that the metadata you pass to `docker build` is consistent with what gets built into your image.

**Comment by hansenms** [comment]
@xeger thanks for the comments. With our private repos, I do exactly as you say for reasons of security and other stuff. In general for our own main projects, I do exactly as you say since I may want to build a docker image with a specific version rather than the latest one. 

But I also have other dependencies that may not be the focus of that particular build and the whole purpose of the build may be so see if our stuff is breaking with the very latest versions of certain packages. It is actually a handy way of keeping an eye on whether some breaks are about to happen given what is at the head of some other related projects. In that case, it makes a lot of sense to just clone those packages during the build and then LABEL the image with the versions so that when a given image breaks, it is easy to inspect them and see what versions it was running and what changed since last passing build. 

Also as you say for environments such as DockerHub, it is also problematic. 

Moreover, it is hard for me to understand why one would not allow the build process to set metadata LABELs. Maybe I am missing something. 

I think what I may do is just build a text log inside the images with all the labels and then simply create a container from the image and cat the file.

**Comment by jantman** [comment]
@hansenms I was going to say the same thing, but @xeger beat me to it.

The way we accomplish this is by using common tooling (a Jenkins job) to build Docker images. Each image has its own git repository, with ``./Dockerfile`` in it. However, our build job also looks for ``./prebuild.sh``, ``./postbuild.sh`` and ``./postpush.sh`` and executes them if present; that's where we do things like cloning repos, and anything else that has to be done on the host. It would be much easier if Dockerfiles had a LOCAL_RUN option that would execute commands on the build host at the appropriate point in the build, but that's not the case. On the whole, we've had to put a lot of hacks in place to work around limitations in Dockerfiles.

**Comment by hansenms** [comment]
@jantman, @xeger 

Thanks for the comments and suggestions. I am experimenting with various strategies. I am concerned that the need to clone lots of repos locally is going to prevent us from making some of these images on external build systems. So what I am doing right now is something like this. I will have something like this in the Dockerfile:

```
RUN cd /opt/code && \
    git clone https://github.com/myproject/myprepo.git && \
    cd myrepo && \
    mkdir build && \
    cd build && \
    cmake ../ && \
    make -j $(nproc) && \
    make install && \
    git rev-parse HEAD >> /opt/code/myrepo_sha1.txt
```

Or something like that. After building, you can simply look at those tags:

    docker run --rm my_docker_image cat /opt/code/myrepo_sha1.txt

One could of course maintain all of these hashes and versions in a single file (json or something) in the image. It would be like a build manifest and then one could simply get all the metadata in one go and do whatever searching and processing is needed.

I think both strategies have advantages and disadvantages for sure and they are all just workarounds to overcome limitations in the Dockerfiles but if it gets the job done, then OK. 

Thoughts?

**Comment by xeger** [comment]
Flat-file metadata bundled into the image is certainly a valid solution; it's what we did before build-time labeling came along. Each approach has its pros and cons; if it works for you, then use it with impunity!

**Comment by hansenms** [comment]
@xeger What do you mean with "before build-time labeling came along". Isn't that the whole point, there is no way to create LABELs during a docker build. Or is that a new feature?

**Comment by xeger** [comment]
@hansenms one can use `--build-arg` to provide variable inputs to the Dockerfile, so that `LABEL` and other instructions can consume information from the build environment. For instance:

```
# in Dockerfile
ARG gitref unknown
LABEL org.git.ref ${gitref}

# on CLI
docker build --build-arg gitref=`git rev-parse --verify HEAD`
```

This is build-time labeling in the sense that I can influence the built image without changing the Dockerfile.

You have a chicken-and-egg problem that makes it hard to provide accurate build args, but a `--label` flag to `docker build` would have the same problem .. the best solution for your issue, it seems, would be to allow the Dockerfile to "capture" build state (e.g. "which version of this dependency did I end up installing during my last `RUN` instruction?) and then apply that build state to future instructions.

The Docker team has been careful about determinism during image builds: images built repeatedly from a given build context should ideally be identical. Among other benefits, determinism allows for layer caching, which speeds up image builds. Allowing build state to be captured and used as build args, would promote non-deterministic builds and make layer caching complex or impossible.

**Comment by hansenms** [comment]
@xeger, understood. 

I guess my view on this is that as long as you can do git clone, wget, apt-get update, etc. etc. within a Dockerfile, images built repeatedly from the same context can and will vary. The fact that there is no way to capture what those variations may be really doesn't change that. It just makes it opaque. 

The flat file metadata is really the only way to capture that right now. It is fine, but it would be more elegant and standardized if there was a way to capture such metadata. The command line build-args are also problematic for some automated build systems, e.g., it is hard to do what you propose on Docker Hub. 

In any case, I understand the position of the Docker team and I respect that my "important" features may in fact be distractions that could create unintended consequences. But in case these sorts of features were being discussed for the roadmap, I wanted to register a vote in favor.

**Comment by hansenms** [comment]
@xeger @jantman 

If it is of interest, I wrote up how we handle it here:

http://hansenms.github.io/devops/tips/2016/02/26/docker-build-manifest.html
