### ISSUE TITLE
How to link docker container with service running outside docker

### ISSUE THREAD

**Issue by sourav82** [docker/docker#13177]
Is there any way to link docker container with some service (say db, ldap etc.) not running as docker container?

Service may run on a VM or server but not using docker. I was wondering if there is any way to link a docker container with that service.

**Comment by vdemeester** [comment]
There was a discussion about that in docker/compose (https://github.com/docker/compose/issues/1110). To sumarize, one way is to use ``--add-host`` flag, but you depend on the environment variables and a random port, there's no real way to do that I think.

> --add-host=""    : Add a line to /etc/hosts (host:IP)

**Comment by runcom** [comment]
Since dB, ldap can run listening on tcp, yes you have a way, just use the network as you would normally do If services aren't on the same host. 

I'm going to close this since it's not an issue but feel free to ping me if you think it's otherwise, also for question like this please consider asking in #docker on IRC

**Comment by runcom** [comment]
Thanks @vdemeester for explaining that also!

**Comment by sourav82** [comment]
Thanks @vdemeester and @runcom
