### ISSUE TITLE
`docker run --rm ...` keeps container around on error

### ISSUE THREAD

**Issue by felixrabe** [docker/docker#13248]
I would expect `docker run --rm -v bad/path:...` to remove the container after complaining about the relative `bad/path`, but it does not. ([Docs](https://docs.docker.com/reference/run/#clean-up-rm))

Example:

    $ docker ps -a
    CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
    d39efd547404        debian:jessie       "/bin/bash"         30 seconds ago                                              distracted_yonath   
    $ docker run --rm -ti -v "~/i:/i" debian:jessie
    FATA[0000] Error response from daemon: cannot bind mount volume: ~/i volume paths must be absolute. 
    $ docker ps -a
    CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
    a43adf871c65        debian:jessie       "/bin/bash"         2 seconds ago                                               cocky_poincare      
    d39efd547404        debian:jessie       "/bin/bash"         57 seconds ago                                              distracted_yonath   

(I should have written the `~` outside of the quotes to make the path expand to my home directory.)

Successful execution with a correct path will remove the container afterwards.

**Comment by felixrabe** [comment]
Btw, this was with Docker 1.6.2 on OS X 10.9 with Boot2Docker.

**Comment by runcom** [comment]
@felixrabe thanks for this, we are actually aware of this. Turns out we don't remove the container if something went wrong during the startup, just in case you want to debug why it crashed running. Also --rm is actually implemented client side but there are varius issues proposing this handling to be daemon side (I'll find the issue because I was working on this but don't have a link right now :))

**Comment by runcom** [comment]
@felixrabe #6757
