### ISSUE TITLE
Docker forgets about --no-cache when building an image inside a virtualenv python

### ISSUE THREAD

**Issue by hayderimran7** [docker/docker#13262]
SPECS:
Docker version: 1.6.0
Kernel : 3.12.39-47-default
Platform : Opensuse
PROBLEM:
I hope there is a sane reason of why this is happening, I have been observing this again and again, whenever i build an image and then later i activate a python virtualenv for working on some other stuff, and build the same image again, it starts from scratch like `--no-cache` is being set even though i do not pass it at all to `docker build` command.   
Same thing happens otherwise, build an image while python virtualenv is activated in shell, snap out of virtualenv by issuing `deactivate` and try `docker build` again, it just starts from scratch as if `--no-cache` is set . 

Without virtualenv, it behaves as it is. Without `--no-cache` it uses all cached layers and builds instantly .

**Comment by vdemeester** [comment]
I'm not sure this is a Docker issue as well — should be closed here and asked in the forums or stackoverflow, or …

But quickly regarding your porblem, I don't know much about virtualenv but if it modify the current folder, and you copy the current folder inside you container, the cache will be invalidated..

**Comment by thaJeztah** [comment]
@hayderimran7 I'm going to close this issue, because (based on just the provided information) this doesn't sound like a bug in Docker.

As @vdemeester explained, Docker determines if the cache should be used, based on a "checksum" of the files used in the build-context and (in the current releases) meta-data of those files (including "mtime").

If you need help with this, feel free to ask this question;

- In the #docker IRC channel on freenode
- On https://forums.docker.com
- In the [docker-user](https://groups.google.com/forum/#!forum/docker-user) Google Group
