### ISSUE TITLE
Support for JSON/XML output formats for various docker command line arguments

### ISSUE THREAD

**Issue by johnsamuelwrites** [docker/docker#13274]
It will be useful to have structured output from docker commands
For example:

$ docker ps --format [xml|json]

Structured output can be directly used with other applications without the need for parsing.

docker-py (https://github.com/docker/docker-py, https://docker-py.readthedocs.org/en/latest/api/) currently provides this option.

**Comment by runcom** [comment]
@johnsamuelwrites can't you just use API directly?

**Comment by vdemeester** [comment]
Agree with @runcom, I think you should use api you're making tools that interact with docker instead of the cli.

**Comment by thaJeztah** [comment]
I see this kind of feature requests appear from time to time. Perhaps someone should create a basic Docker client that acts as a simple wrapper for the API and outputs the raw, unmodified JSON.

I don't think this should be in the "core" Docker functionality, as it will largely duplicate the API

**Comment by runcom** [comment]
@thaJeztah problem is sometimes the client (command line) does more than just formatting the response from the API.
For the client you talked about, I think any http client can do that just calling the API unless you're talking about a docker-cli wrapper

**Comment by johnsamuelwrites** [comment]
While taking a look at the (classical) Unix/Linux commands, a majority of them do not provide any XML/JSON outputs. But most recent ones like journalctl have introduced JSON output.

http://linuxmanpages.net/manpages/fedora19/man1/journalctl.1.html

$  journalctl -o json-pretty 
or
$  journalctl -o json

Having structured output gives a lot more flexibility to the end users.

**Comment by thaJeztah** [comment]
@runcom true, and I fully understand that. Most requests I've seen are around *retrieving* info (`docker ps`, `docker images`), which could almost be achieved with some simple shell scripts calling `curl`.

@johnsamuelwrites interesting. I'm not entirely sure though. I know some Docker CLI commands already expose JSON (e.g. `docker inspect`). On one hand, that's convenient, on the other hand; it will become confusing; when should I use the API, and when the CLI, if both offer the same?

**Comment by runcom** [comment]
@johnsamuelwrites does `journalctl` offers some HTTP API? cause the point for me is, though it could be useful, docker hasn't the need to format its commands output due to we have json API.
Also, `journalctl` example does not apply to many docker's commands. In `journalctl` there's some kind of need to expose json cause you may want to parse log entries and this makes sense. Commands like `info`, `stats` and others already expose JSON via API and others like `run` I don't see the need to expose json (me, if you could make me and example about when this will be useful it'd be great)

**Comment by thaJeztah** [comment]
Outputting JSON was suggested in https://github.com/docker/docker/pull/10255#issuecomment-97553217. I added the suggestion to combine that with a `--format` option, for optimum use.

Given, that is, that #12931 is not accepted in its current form, see https://github.com/docker/docker/pull/12931#issuecomment-98272280

**Comment by brimworks** [comment]
Note that if you directly use the API setting up the connection to the correct endpoint is often non-trivial since it involves reading various environment variables and potentially setting up TLS with the right client certificate. It would be much easier if you could run `docker <cmd> --format=json`.

**Comment by cpuguy83** [comment]
@brimworks This works already on many commands `--format {{ json . }}`

**Comment by adeimos** [comment]
This could be very useful to monitor, for example, a swarm. For example, something like:

docker -H myswarm:3333 info

**Comment by brimworks** [comment]
@cpuguy83  Unfortunately, it doesn't seem to work with version 1.9.1 for the `docker history` and `docker events` commands, it gives this error: `flag provided but not defined: --format`.

Thanks,
-Brian

**Comment by AkihiroSuda** [comment]
Is this closable because now most commands supports `--format {{json .}}`?

some PRs:

- `ps`/`network ls`/`volume ls`: https://github.com/docker/docker/pull/26519
- `events`: https://github.com/docker/docker/pull/26268

**Comment by thaJeztah** [comment]
Yes, I think this can be closed
