### ISSUE TITLE
Proposal: Help text for commands could link to documentation

### ISSUE THREAD

**Issue by bfirsh** [docker/docker#13298]
Now with the hard limit on help text width, the documentation for options is much less descriptive, so it can be quite hard to tell what each option does.

For each command, we could link off the documentation for more information:

```
$ docker run --help
Usage: docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container

  -a, --attach=[]            Attach to STDIN, STDOUT or STDERR
  --add-host=[]              Add a custom host-to-IP mapping (host:ip)
...
  -v, --volume=[]            Bind mount a volume
  --volumes-from=[]          Mount volumes from the specified container(s)
  -w, --workdir=             Working directory inside the container

For more information on this command and its options, see the docs:
https://docs.docker.com/reference/run/
```

**Comment by thaJeztah** [comment]
The problem in this particular case (docker run) is that a lot of information is spread over the Command Line Reference (https://docs.docker.com/reference/commandline/cli/#run) and the Docker Run Reference (https://docs.docker.com/reference/run/); Perhaps each command should get its own page and the Command Line Reference only used as an index; this would make it easier to automatically generate the URL

I like the idea though; I think the domain-name should be dynamically inserted as well, so that a "Master" / "Development" build can point to http://master.dockerproject.com and an "Experimental" build to http://experimental.docker.com

**Comment by thaJeztah** [comment]
We do have separate pages for all subcommands, so programmatically generating a link would be possible now.

However, ideally, I'd like the help output to be useful 
- improving the overall output and description (https://github.com/docker/docker/issues/18797, https://github.com/docker/docker/issues/18385, https://github.com/docker/docker/issues/25615, https://github.com/docker/docker/issues/25615)
- incorporating more information from the man pages in the help output

@bfirsh @dnephin wdyt should we close this issue in favor of the other issues linked?

**Comment by dnephin** [comment]
#25615 is listed twice, did you mean to link a different issue?

I think it would be better to include the full help in the `--help` instead of link to it. That is what `git` does.

**Comment by thaJeztah** [comment]
> #25615 is listed twice, did you mean to link a different issue?

hm, possibly, or I just lost track, haha

> I think it would be better to include the full help in the --help instead of link to it. That is what git does.

Alright, let's close this one
