### ISSUE TITLE
docker-completion is slow

### ISSUE THREAD

**Issue by mcandre** [docker/docker#13340]
Docker tab completion in bash can take 5 seconds or more, far longer than other tab completions like git-completion or lftp-completion. How can we speed this up?

**Comment by coolljt0725** [comment]
It takes long because it will connect to the docker daemon to search the images or containers.
If you have a lot of containers or images, it will take long. I think it's not easy to speed up

**Comment by mcandre** [comment]
Yes, I publish several images, though I often delete my temporary containers and images.

Here's the rest of the information:

```
$ docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): darwin/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

$ docker info
Containers: 1
Images: 182
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 184
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.18.11-tinycore64
Operating System: Boot2Docker 1.6.0 (TCL 5.4); master : a270c71 - Thu Apr 16 19:50:36 UTC 2015
CPUs: 4
Total Memory: 1.961 GiB
Name: boot2docker
ID: MCKR:WP3W:YXR7:M66R:E4QC:CSQZ:ZQAJ:E6D7:TXNH:P7J5:2RAT:TB4K
Debug mode (server): true
Debug mode (client): false
Fds: 19
Goroutines: 32
System Time: Wed May 20 22:35:38 UTC 2015
EventsListeners: 0
Init SHA1: 9145575052383dbf64cede3bac278606472e027c
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: mcandre
Registry: [https://index.docker.io/v1/]

$ uname -a
Darwin mockingjay.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
```

**Comment by thaJeztah** [comment]
I think @coolljt0725 is right here; completion of container and image-names depends on requesting that information from the daemon, which can be slow.

It might be worth checking if you have the latest version of the completion script installed, because some improvements have been made a while ago to improve the performance a bit.

You can find the bash completion script here https://github.com/docker/docker/blob/master/contrib/completion/bash/docker and instructions for installing can be found in the file.

I'm going to close this issue, because we are aware of the performance issues, but unfortunately cannot improve those further at this moment.

Thanks for reporting this, we appreciate the feedback!
