### ISSUE TITLE
centos/rhel7: unable to decode ApplyLayer JSON response: invalid character 'i' in literal true (expecting 'r')

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#13373]
so on the centos and rhel machines i am seeing this for test-integration-cli
https://jenkins.dockerproject.com/job/Docker%20Master/label=centos-devicemapper/1545/console

```
time="2015-05-21T00:03:05Z" level=warning msg="port allocator - using fallback port range 49153-65535 due to error: open /proc/sys/net/ipv4/ip_local_port_range: no such file or directory" 
Error response from daemon: unable to decode ApplyLayer JSON response: invalid character 'i' in literal true (expecting 'r')
```

ping @mrjana @mavenugo 

let me know if you want access to these machines, ill hook u up

**Comment by mrjana** [comment]
ping @aboch

**Comment by jfrazelle** [comment]
any word on this...

**Comment by jfrazelle** [comment]
its breaking our master builds

**Comment by jfrazelle** [comment]
maybe @vbatts or @rhatdan can help

**Comment by aboch** [comment]
Relevant code has not changed when ported to libnetwork.
Still looking into it...

**Comment by aboch** [comment]
(Might already be obvious to others)

I think real issue which fails the integ-cli test is conveyed by:
 
`Error response from daemon: unable to decode ApplyLayer JSON response: invalid character 'i' in literal true (expecting 'r')`

Where the cli http client reports the error returned by the server in func (cli *DockerCli) clientRequest(). Looks like the server had issue reported by chrootarchive pkg.

Not sure why the integ-cli test that failed is not even reported in the o/p.

I do not believe 

'time="2015-05-21T00:03:05Z" level=warning msg="port allocator - using fallback port range 49153-65535 due to error: open /proc/sys/net/ipv4/ip_local_port_range: no such file or directory"'

is related, as this is only a bridge warning log message, and does not trigger any error to be reported to the caller.

**Comment by vbatts** [comment]
hmm. That file exists for me. what is your setup?

```bash
[root@bananaboat ~]# cat /etc/*release
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Red Hat Enterprise Linux Workstation release 6.6 (Santiago)
Red Hat Enterprise Linux Workstation release 6.6 (Santiago)
[root@bananaboat ~]# uname -r
2.6.32-504.16.2.el6.x86_64
[root@bananaboat ~]# cat /proc/sys/net/ipv4/ip_local_port_range
32768   61000
```

**Comment by jfrazelle** [comment]
**centos machine**

```
root@jenkins-centos:~# cat /etc/*release
CentOS Linux release 7.1.1503 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.1.1503 (Core) 
CentOS Linux release 7.1.1503 (Core) 
root@jenkins-centos:~# uname -r
3.10.0-123.8.1.el7.x86_64
root@jenkins-centos:~# cat /proc/sys/net/ipv4/ip_local_port_range
32768	61000
```

so I have the file but the tests are failing because....
I cant get it in the container

```
root@jenkins-centos:~# docker run --rm -it --privileged ubuntu:14.04 cat /proc/sys/net/ipv4/ip_local_port_range
cat: /proc/sys/net/ipv4/ip_local_port_range: No such file or directory
```

**Comment by vbatts** [comment]
hrm, ...
```bash
root@rhel7 ~ (master) # cat /etc/*release
NAME="Red Hat Enterprise Linux Workstation"
VERSION="7.0 (Maipo)"
ID="rhel"
VERSION_ID="7.0"
PRETTY_NAME="Red Hat Enterprise Linux Workstation 7.0 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.0:beta:workstation"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.0
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION=7.0
Red Hat Enterprise Linux Workstation release 7.0 Beta (Maipo)
Red Hat Enterprise Linux Workstation release 7.0 Beta (Maipo)
root@rhel7 ~ (master) # uname -r
3.10.0-229.4.2.el7.x86_64
root@rhel7 ~ (master) # docker run --rm -it --privileged ubuntu:14.04 cat /proc/sys/net/ipv4/ip_local_port_range
cat: /proc/sys/net/ipv4/ip_local_port_range: No such file or directory
root@rhel7 ~ (master) # cat /proc/sys/net/ipv4/ip_local_port_range
32768   61000
```

**Comment by vbatts** [comment]
wacky. I've just tested the same on fedora20 and rhel6 and `docker run --rm -it --privileged ubuntu:14.04 cat /proc/sys/net/ipv4/ip_local_port_range` finds the file, but not on rhel7.

**Comment by jfrazelle** [comment]
ya so LOL we have centos 7 and rhel  7 so we are in the sad group of this

**Comment by vbatts** [comment]
I've tracked down that the issue is already a known issue, and is fixed for a future release. I've escalated the issue, hopefully that will deliver it sooner for RHEL7.1 (and subsequently centos 7.1)

**Comment by jfrazelle** [comment]
you rule @vbatts is there something i can do to patch in the meantime because our builds are broken :)

**Comment by vbatts** [comment]
alright, so i'm thinking we might want to exclude the tests that trigger this, for an interim. The issue is fixed and will definitely be included in the RHEL7.2 release, but possibly sooner in an 7.1.z update. Either way, it won't be immediate.

It looks like, in the `test-unit` target, the `github.com/docker/docker/api/server`, `github.com/docker/docker/builder` and `github.com/docker/docker/daemon` hit this.

**Comment by icecrime** [comment]
Thanks @vbatts. I'm removing this from 1.7.0 milestone then, @jfrazelle should we exclude the tests?

**Comment by jfrazelle** [comment]
I think we should because i hate red

**Comment by jfrazelle** [comment]
we should just skip if it cant read that file

**Comment by tiborvass** [comment]
+1 on skipping

**Comment by jfrazelle** [comment]
actually we cant really skip becuase it cant even run dind, on those machines because it cant get the range....

**Comment by jfrazelle** [comment]
ping @vbatts 

this is a red herring

the real error is actually

```
time="2015-06-02T18:56:10.072818047Z" level=debug msg="Loading 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158" 
time="2015-06-02T18:56:10.073684701Z" level=debug msg="Start untar layer" 
time="2015-06-02T18:56:10.114243024Z" level=error msg="Handler for POST /images/load returned error: unable to decode ApplyLayer JSON response: invalid character 'i' in literal true (expecting 'r')" 
time="2015-06-02T18:56:10.114349411Z" level=error msg="HTTP Error" err="unable to decode ApplyLayer JSON response: invalid character 'i' in literal true (expecting 'r')" statusCode=500 
time="2015-06-02T18:56:10.126939660Z" level=info msg="Processing signal 'terminated'" 
time="2015-06-02T18:56:10.127372660Z" level=debug msg="starting clean shutdown of all containers..." 
time="2015-06-02T18:56:10.127476026Z" level=debug msg="Clean shutdown succeded" 
```

thanks @aboch for pointing that out

this is NOT a networking issue, ill update the title

**Comment by jfrazelle** [comment]
and we need this fixed for 1.7.0 because idk what the real problem is, something with the docker load

**Comment by vbatts** [comment]
ohman

**Comment by estesp** [comment]
there is a hole in error condition handling in the reexec to do chroot'ed untar via the `applyLayer` path: if the result isn't successful, then the response will not be valid JSON.. it (stdout) could be empty, or whatever errors that happen that end up getting written in some textual form to `stdout`; e.g. this `fatal()` call ends the process, and the result is obviously not going to be a JSON stream format with a single int64 encoded (the size that the caller expected): https://github.com/docker/docker/blob/master/pkg/chrootarchive/diff.go#L42

For long term we probably need to figure out how to pass errors back out so that it can be debugged when things go wrong, but for this specific issue, if we have a good failing scenario we can make a special build that dumps the re-exec'ed errors somewhere stable so it can be figured out.  In other news, that `5111...` layer sounds like the emptyfs layer ID, right?

**Comment by vbatts** [comment]
@estesp yes, that is "scratch"

**Comment by jfrazelle** [comment]
@estesp what i posted were the daemon logs from the test daemon in the container... what other logs do we need

**Comment by estesp** [comment]
Wow, that's an awesome catch @crosbymichael .. hopefully everyone else caught what happened here :)

So because stdout was being used for JSON output, and some other init code happened to dump a log message, it messed up the JSON output..
