### ISSUE TITLE
Allow newlines inside CMD array form or improve error messages  [feature request]

### ISSUE THREAD

**Issue by kuc** [docker/docker#13404]
Currently executing something like this
```
CMD ["java",
	"-version"]
```
will give you very enigmatic error:
```
time="2015-05-22T14:19:59+02:00" level=info msg="Unknown instruction: \"-VERSION\"]"
```
and malformed `CMD` instruction is silently skipped/ignored(?)

This works, but it's not very intuitive:
```
CMD ["java",\
	"-version"]
```

**Comment by cpuguy83** [comment]
ping @duglin 

I don't think the `\` is unintuitive, however since it is the json format it's certainly less natural.

**Comment by duglin** [comment]
First, if you upgrade to a newer Docker it should stop building with an error on an unknown instruction instead of just ignoring it.

Second, knowing that a newline character should be treated like an implicit `\` requires that we know we're in the middle of a `[` expression.  I know bash has this type of logic but changing our parser to support this would be non-trivial.  Mainly for backwards compatibility reasons, we have a lot of command specific parsing and for the most part everything is line based.  In that mode its easy to know when to continue to the next line because it ends with a `\`.  But, in order to support what you want we'd need to mix the "reading from the Dockerfile" logic with the "interpret the command" logic and I'm not sure we can do that today - at least not w/o a total rewrite of the parser.

If we had a more consistent Dockerfile syntax, one where we didn't have specialized parsers per command, we might be able to do what you're asking for (and I agree it would be an interesting idea) but given our current code-base I don't see it happening.

There are ideas floating around about how to change things (e.g. moving the Dockerfile processing to the client, a new Dockerfile syntax, support shell scripts, etc...) and if we do change the Dockerfile syntax we'll take this request into account.  But for now I think we'll need to close this.  Thanks for the idea though!

**Comment by duglin** [comment]
One thing I forgot to mention, which is another pain point in all of this, the presence of `[` doesn't necessarily means we're using json. It could be part of a normal shell command. Granted, we might be able to tell that we're missing a `]` but my point is that we can't assume its json.

**Comment by kuc** [comment]
@duglin I use Docker 1.6.2 and it indeed stops building, but don't report that problem is with malformed `CMD` command from previous line.

Anyway, thanks for comprehensive response!

**Comment by duglin** [comment]
@kuc yea the error can't be detected (easily) for the previous line because unless we understood all of sh/bash we can't be sure that what's on the line is invalid.  For all we know: `["java",` could be a valid command  :-)
