### ISSUE TITLE
docker.io does not exist anymore in backports.

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#13429]
A little email just to tell you that the documentation about installing Docker on Debian Jessie (https://docs.docker.com/installation/debian/) is not up-to-date as it seems that the docker.io does not exist anymore in backports.

The installation through wget -qO- https://get.docker.com/ | sh works though. I would just add a mention about systemctl enable docker to have Docker starts at each machine start.

Kind regards,
Philippe

**Comment by thaJeztah** [comment]
This is a known issue, there are a few ones opened (sorry, on my phone at the moment); the problem is that its not *yet* available in back ports; it's currently under review and depends on some other changes.

In short; the institutions will become valid again, and also @jfrazelle is working on official .deb packages.

Will look for the related issue numbers as soon as I'm home :)

**Comment by jfrazelle** [comment]
this is fixed now
