### ISSUE TITLE
No response to Application from zookeeper cluster after few hours

### ISSUE THREAD

**Issue by Pratap6** [docker/docker#13455]
Hi,

Zookeeper horizontal cluster is created with 3 nodes. Application is running on docker container. Application is getting properties from zookeeper znode.

After few hours application is going to unresponsive mode. Everything is getting fine when we restart application's docker container.

Environment: Linux Centos 6.5/Ubuntu 14.04
ULIMIT : 10000 on host machine

Command to start container: 

docker run -it -e HOST_PORT=IP1:2181,IP2.2:2181,IP3:2181 -e CONNECTION_FAILED=IGNORE -e REGRESON=TRUE -e RELOAD_CONTEXT=AUTO -e RESOURCE_ENABLE=TRUE -e GENERATE_PING=get -e SHARED=0 -e SHARED_ZNODE=/abcznode -e SESSION_TIMEOUT=30000 -p hostIP:8020:8080 --privileged=true myproject1

Please help us!

Thanks!

**Comment by thaJeztah** [comment]
Could you add the requested information? If you have relevant logs or other information that could be helpful here, please provide that as well. Be sure to remove sensitive data from log files and, for long logs, preferably in a "gist", and not as a comment here

**Comment by unclejack** [comment]
This issue doesn't have a lot of details to describe the actual problems and the requested information hasn't been provided so far.
Since guessing what kernel and Docker version were being used, whether the system was fully updated and how the systems were being connected, there's no way this can be debugged on this issue tracker.

This isn't a general support forum. This is something to be discussed on one of the following: 1) the forums: https://forums.docker.com/ 2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user 3) the #docker channel on Freenode.

Should the problem be tracked down to an actual Docker bug, this issue can be opened again. Figuring out whether this is an actual Docker bug can be done by having a conversation on one of the three support forums.

Meanwhile, please keep in mind that this is an issue tracker for Docker bugs, features and pull requests. Please take this into account when opening an issue.

This discussion is more appropriate for
1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker channel on Freenode.

1) and 2) should be better for longer conversations.
