### ISSUE TITLE
API reference WEB vs GitHub not in sync?

### ISSUE THREAD

**Issue by KostyaSha** [docker/docker#13466]
https://github.com/docker/docker/blob/master/docs/sources/reference/api/docker_remote_api_v1.16.md#start-a-container 
vs 
https://docs.docker.com/reference/api/docker_remote_api_v1.16/#start-a-container
/cc @cpuguy83

**Comment by thaJeztah** [comment]
Hi @KostyaSha, the documentation on the website may not always be in sync with the GitHub repository, because it is only updated periodically.

Because some parts of the documentation are only useful for the upcoming release, not all changes can be put "live" before the release, which can result in some parts being outdated.

Last thing I heard is that the documentation will be updated together with the upcoming 1.7 release, but if you want to see the documentation with all updates from GitHub, have a look at https://docs.master.dockerproject.com. In this case; https://docs.master.dockerproject.com/reference/api/docker_remote_api_v1.16/#start-a-container

I'm going to close this issue, because we are aware that the documentation on https://docs.docker.com sometimes contains outdated parts.

Thanks for reporting!

**Comment by KostyaSha** [comment]
@thaJeztah Because of this bad documentation docker libraries removing and deprecating API 
https://github.com/docker-java/docker-java/commit/ca54f9c758087bce519f5b59fdd5c4a0482dc313#commitcomment-11351498

**Comment by thaJeztah** [comment]
@KostyaSha thanks for letting us know, I'll see if there's anything I can do here, but it's currently quite stressful because of the upcoming release and Dockercon. If we are unable to achieve that, please refer to the https://docs.master.dockerproject.com/ website, because those are the most up-to-date docs (but **do** contain features that are not yet in the current release)

cc @SvenDowideit @moxiegirl I don't think there are, but if any updates to the docs are scheduled before the release, is there a chance to get doc-changes for the existing API <= 1.18 included somehow?

**Comment by KostyaSha** [comment]
@thaJeztah it will be very useful to keep already released api docs actual. Thanks for reply.

**Comment by moxiegirl** [comment]
@thaJeztah With the current crunch, we are unlikely to cherry-pick at the moment. I realize it is frustrating @KostyaSha we are working on infrastructure changes that should alleviate this problem in the near future.

**Comment by gesellix** [comment]
I would suggest to include code comments like those https://github.com/docker/docker/blob/master/daemon/start.go#L27 in the official docs, too.

**Comment by thaJeztah** [comment]
@gesellix we always welcome pull-requests if you see things that can be improved in the docs! :-)

**Comment by gesellix** [comment]
@thaJeztah ok you got me ... give me 5 minutes or so...  :-)

**Comment by thaJeztah** [comment]
@gesellix thanks! We really try to keep track, but Docker is a fast moving project, and things are easily overlooked.

**Comment by KostyaSha** [comment]
@moxiegirl hi, could you help understand when last time this site was synced https://docs.docker.com/reference/api/docker_remote_api_v1.19/  ?

**Comment by moxiegirl** [comment]
@KostyaSha The site was updated this morning 7/8 around 11:30.  The file that is visible is coming from our **docs** branch.  To see the history see this:

https://github.com/docker/docker/blob/docs/docs/reference/api/docker_remote_api_v1.9.md

It is possible that a change was made right after the release branch cut over. In which case, we would need to cherry pick the change in.  You'd need to show me which change you are looking for and when it was done.

**Comment by gesellix** [comment]
@moxiegirl it appears to me that the changes from PR #13615 have been lost with the commit https://github.com/docker/docker/commit/0bd5953a88f52131143970e82423f0120448ab03#diff-078e30c97da6f3da4c0ad81bdb709d96
can you confirm?

**Comment by moxiegirl** [comment]
@gesellix I see the change in master not in `docs `branch.  That says the change was not pulled into an RC --- and I don't see a cherry-pick mark on that PR.

**Comment by gesellix** [comment]
could that be fixed by cherry-picking it now or would you need/prefer a fresh PR?

**Comment by KostyaSha** [comment]
> https://github.com/docker/docker/blob/docs/docs/reference/api/docker_remote_api_v1.9.md

Was confused by content, but then realised that it 1.9 and not 1.19

**Comment by gesellix** [comment]
@moxiegirl shall I submit another PR or would a cherry-pick be easier?

**Comment by moxiegirl** [comment]
@gesellix I think a new PR is better.  Thanks for doing that.
