### ISSUE TITLE
Container name instead of container id tag for syslog log driver

### ISSUE THREAD

**Issue by gionn** [docker/docker#13474]
Hi,

we were evaluating the possibility to deprecated our actual logging delivery pipeline based on a logstash-forwarder containers on each host, and start using the new syslog driver introduced by #10568.

Unfortunately the actual implementation is pushing the container id as the unique identification string, that is pretty much useless when trying to identify problems on a centralized kibana interface.

Using the container name instead of the container id would be great since we use a proper naming scheme depending on services we are deploying via docker.

Thanks.

**Comment by phemmer** [comment]
See #12296

**Comment by runcom** [comment]
@gionn this will be eventually made configurable with a `--log-opt` (see #13015, #12876 for some discussion around this) there is an ongoing discussion about this..

**Comment by thaJeztah** [comment]
In addition to the PRs already mentioned, there's an open PR to implement this for syslog; https://github.com/docker/docker/pull/12668.

Thanks for reporting this, I'm going to close this issue, because this is something that we're aware of and actively worked on.

Please subscribe to the linked PRs to stay informed on development.
