### ISSUE TITLE
libnetwork: TestDaemonICCPing

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#13556]
on certain machines these are super unstable and fail all the time

**Comment by jfrazelle** [comment]
mainly with modern kernels

**Comment by anchal-agrawal** [comment]
+1

@jfrazelle  I have a similar issue on a fresh fork of the repo on my Boot2Docker setup. A bunch of tests on the `test-integration-cli` bundle (including `TestNetworkNat`) fail after the `test-unit` bundle passes successfully. This isn't reproducible on my Ubuntu machine.

Here's some debug info.

#### `docker version`:
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): darwin/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

#### `docker info`:
Containers: 3
Images: 145
Storage Driver: aufs
Root Dir: /mnt/sda1/var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 151
Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.0.3-boot2docker
Operating System: Boot2Docker 1.6.2 (TCL 5.4); master : 4534e65 - Wed May 13 21:24:28 UTC 2015
CPUs: 4
Total Memory: 1.957 GiB
Name: boot2docker
ID: LAKT:D6LV:Q7MZ:3PNL:HSWM:CHM3:4T2Y:IGST:UCM7:EC7I:2GBN:4ZH5
Debug mode (server): true
Debug mode (client): false
Fds: 13
Goroutines: 19
System Time: Thu May 28 16:22:51 UTC 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: anchal
Registry: [https://index.docker.io/v1/]

#### `uname -a`:
Darwin Anchals-MacBook-Pro.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

### Additional info:
The full terminal output for the `test-integration-cli` bundle on my setup is in this [gist](https://gist.github.com/anchal-agrawal/753427cb76a6decd4fac).

**Comment by mavenugo** [comment]
@jfrazelle @anchal-agrawal  will take a look at it.

**Comment by vdemeester** [comment]
Yeah I can confirm that too.

```bash
$ docker info
Containers: 11
Images: 477
Storage Driver: btrfs
 Build Version: Btrfs v4.0
 Library Version: 101
Execution Driver: native-0.2
Kernel Version: 4.0.4-2-ARCH
Operating System: Arch Linux
CPUs: 4
Total Memory: 15.56 GiB
Name: hokkaido
ID: PZA5:ZBFH:VJBE:XGRD:F7VF:MG3C:XYSJ:WLBJ:DSLH:7NLV:HEAH:LV6G
$ uname -a
Linux hokkaido 4.0.4-2-ARCH #1 SMP PREEMPT Fri May 22 03:05:23 UTC 2015 x86_64 GNU/Linux
```

**Comment by jfrazelle** [comment]
reopened because the problem still exists with TestDaemonICCPing

**Comment by mavenugo** [comment]
@jfrazelle I looked into the issue with TestDaemonICCPing on Boot2Docker. Its failing because the `br_netfilter` module is not being loaded in b2d. But, we recently added the `modprobe br_netfilter` in libnetwork project and is vendored-in. But unfortunately, the `modprobe` fails in a dind environment due to the missing `/lib/modules` directory inside the dind test environment.

Bind mounting `-v /lib/modules/:/lib/modules/` solves the problem
`DOCKER_RUN_DOCKER := docker run --rm -it --privileged -v /lib/modules/:/lib/modules/ $(DOCKER_ENV    S) $(DOCKER_MOUNT) "$(DOCKER_IMAGE)"`

am not suggesting this as a solution :). But I think enabling `br_netfilter` module by default in b2d will be the right solution.

But, if we feel that we should let the `modprobe` in the code to be working in such a dind environment, then we have to bind mount `/lib/modules`. WDYT ?

**Comment by mavenugo** [comment]
ping @anchal-agrawal @tiborvass can you guys confirm if the above workaround works in your setup ?

**Comment by mavenugo** [comment]
@jfrazelle from http://ebtables.netfilter.org/documentation/bridge-nf.html, 
`Since Linux kernel 3.18-rc1, you have to modprobe br_netfilter to enable bridge-netfilter.` and that answers your observation on why this is seen in modern kernels.

**Comment by jfrazelle** [comment]
br_netfilter is Y on my kernel and I see it...

**Comment by mrjana** [comment]
@jfrazelle can you also make sure that `/proc/sys/net/bridge/bridge-nf-call-iptables` is set to 1 in your machine? If it is 0 even if you have br_netfilter you will see this test failing.

**Comment by anchal-agrawal** [comment]
@mavenugo I couldn't run the full `test-integration-cli` bundle successfully because it timed out after 30m and some tests failed (`TestNetworkNat` passed though). [Here's](https://gist.github.com/anchal-agrawal/fc436ec921e0a3846e63) the full output.

I ran `TestDaemonICCPing` individually and it passed with your workaround.

**Comment by jfrazelle** [comment]
shoot i also forgot my commit that added `modproble br_netfilter` is gone w
the changes ok i think we can close, I was relying on that on the servers
sorry, i can make a script, and locally I can check tomorrow about proc ;)

**Comment by mrjana** [comment]
We ported your changes to libnetwork so that is still there.
