### ISSUE TITLE
Docker run: display percentage of pulling if the image not found locally

### ISSUE THREAD

**Issue by chanwit** [docker/docker#13550]
Description of problem:
When the image is not found locally, `docker run redis`, for example, shows:
```
Unable to find image 'redis:latest' locally
```
Then it's silently downloading the image from a remote hub.

This behaviour makes a new user think something's going wrong as it looks like hanging, especially for someone, like me, who's connecting to hub from the other side of the world.

This behaviour directly affects `swarm` too (docker/swarm#336) as nothing is displayed during the image is being pulled via `run`. And it's simply impossible to fix via `swarm`.

How reproducible:
Run an image.

Steps to Reproduce:
`docker run redis`

Actual Results:
```
Unable to find image 'redis:latest' locally
```

Expected Results:
```
Unable to find image 'redis:latest' locally
Pulling image 'redis:latest' .... 100% // like what's displayed by docker pull
```

Additional info:
I cc @aluzzardi and @vieux as we've discussed this already in the context of `swarm`.

**Comment by chanwit** [comment]
Sorry that I think I misunderstood about this issue. Docker `run` already shows the pulling percentage.

**Comment by aluzzardi** [comment]
@chanwit 

Here's what happens:

`docker run` actually does this:
- `docker create image`
- It receives a `404` back, signaling the image doesn't exist locally
- The CLI will try to pull the image `docker pull image`
- create again: `docker create image`
- then start: `docker start image`

@vieux already made a change so that we do the same thing.

Problem: when the cli sends a `docker pull`, we pull on the **entire** cluster
