### ISSUE TITLE
FR: Check linux kernel version.

### ISSUE THREAD

**Issue by ikeji** [docker/docker#13618]
Feature request:
Accidentaly I run the docker in linux kernel 3.2.
"docker run" looks works correctly but it failed to chroot.

By the [document][1], Docker requires linux kernel 3.10.
Can you add the kernel version check in [setup script][2] or docker service?

[1]: https://docs.docker.com/installation/binaries/
[2]: https://get.docker.com/

**Comment by ikeji** [comment]
This is a feature request. not bug report.
I searched same request, but I can't find.

**Comment by thaJeztah** [comment]
This has been discussed at some point, but unfortunately it's sometimes not enough to check *just* the kernel version. For reference, the discussions on https://github.com/docker/docker/issues/8969 and https://github.com/docker/docker/pull/9456.

Because of this  Docker currently outputs a *warning* (see https://github.com/docker/docker/pull/13041/files) but doesn't fail hard.

We may make this more strict in the future.

ping @unclejack any additional thoughts on this?

**Comment by unclejack** [comment]
We really need to make Docker refuse to start on kernels older than 3.10. We could provide a special build tag to override this which would be used for CentOS/RHEL 6 (and their derivatives).

I know kernel version alone isn't enough to figure out if Docker will work on that system, but it's a good enough to get rid of anything older than 3.10. Even two years later, we're still getting reports from people who are trying to run Docker on kernel 3.2.

**Comment by thaJeztah** [comment]
@unclejack sounds like a relatively easy change, interested in creating a PR? 🍦🎁💝

**Comment by unclejack** [comment]
I've sent a PR to do this in the past and #13618 was also doing this.

Is there any point in keeping this open?

**Comment by thaJeztah** [comment]
I guess there isn't :(
