### ISSUE TITLE
16gb are not enough to build an image: how can I use less space?

### ISSUE THREAD

**Issue by bitliner** [docker/docker#13619]
My simple image requires more than 16gb to run the docker build process.

What should I do to consume less space?

result of `docker info` is:

```
Containers: 35
Images: 330
Storage Driver: devicemapper
 Pool Name: docker-9:3-102133194-pool
 Data file: /home/bitliner/docker-runtime/devicemapper/devicemapper/data
 Metadata file: /home/bitliner/docker-runtime/devicemapper/devicemapper/metadata
 Data Space Used: 5847.1 Mb
 Data Space Total: 102400.0 Mb
 Metadata Space Used: 12.5 Mb
 Metadata Space Total: 2048.0 Mb
Execution Driver: native-0.2
Kernel Version: 3.14.32-xxxx-grs-ipv6-64
```

result of `docker version` is:

```
Client version: 1.0.1
Client API version: 1.12
Go version (client): go1.2.1
Git commit (client): 990021a
Server version: 1.0.1
Server API version: 1.12
Go version (server): go1.2.1
Git commit (server): 990021a
```

**Comment by unclejack** [comment]
@bitliner Please make sure to update Docker on your system. You're running a very old version of Docker. Given that you're running kernel 3.14 and devicemapper, I really think you might also run into many other devicemapper related problems.

Here are the steps I'd recommend:
1) upgrade to the latest docker release
2) keep your system fully updated
3) ensure that you're running the latest kernel for your Linux distribution
4) Whenever you want to reclaim space allocated in the same layer as something like `RUN ./do-something-which-takes-a-lot-of-space` in your Dockerfile, you should append something like ` && cleanup-after-the-command-which-created-the-files`.
5) you can try alternative graph drivers such as AUFS

Since this isn't a real problem and the bug report is against an older version of Docker with many known bugs which would cause such problems (less than ideal link and hard links handling, etc), I'm going to close this now.

Please feel free to comment.
