### ISSUE TITLE
Is there a way to force refresh local images list?

### ISSUE THREAD

**Issue by oilbeater** [docker/docker#13628]
There are two docker with different versions run in the same host. Let them be dockA and dockB.

When use dockA to pull an image A , command 'dockB images' couldn't show the info of image A. After restart dockB, the image can be shown by command 'dockB images'.

Simplify as:

    dockA pull imageA
    dockA images

I can see the info of imageA

    dockB images

No info about ImageA

    service dockB restart
    dockB images

The info of imageA appears

I guess it may be cache related issues for performance consideration, is there a way to force refresh the result of docker images? 
Thanks

**Comment by phemmer** [comment]
You're running 2 different docker daemons out of the same graph dir (`/var/lib/docker`)? If so, this is a very bad idea. This can easily lead to corruption of the data in that directory.

**Comment by thaJeztah** [comment]
To answer your question; no, there no such command. In a "normal" setup, only a single daemon manages the images, so there's no reason to manually reload.

But I agree what @phemmer says; running two daemons on the same graph dir sounds like a bad idea.

I'm going to close this issue, because the above should answer your question. I don't think this is something we want to implement in docker, because in normal setups, there's no need.

Feel free to comment here after the issue was closed

**Comment by oilbeater** [comment]
Yeah, I agree that the way I use docker is wired just for some simple test.

However the graph dir might be changed by other tools and if docker itself cannot keep consistent with the changes, this may confused the user.

To force reload the images by restart is too heavy and dangerous for running container, so I believe a command to reload the images is helpful.
