### ISSUE TITLE
Error pulling docker pull jjaideep2000/apigee-127:V2

### ISSUE THREAD

**Issue by jjaideep2000** [docker/docker#13692]
I'm getting the following error while trying to pull jjaideep2000/apigee-127:V2

Pulling repository jjaideep2000/apigee-127
1fdfb2d8a92f: Error pulling image (V2) from jjaideep2000/apigee-127, HTTP code 400 
6941bfcbbfca: Download complete 
41459f052977: Download complete 
fd44297e2ddb: Download complete 
03e6d49e9840: Error pulling dependent layers 
FATA[0010] Error pulling image (V2) from jjaideep2000/apigee-127, HTTP code 400 

Can someone help? 

Thanks in advance -:)

**Comment by thaJeztah** [comment]
If it's just that image you're having problems with, this sounds like an issue with the Docker Hub, not Docker. Could you open a ticket at https://support.docker.com ?

I'm going to close this issue, because this looks like an issue with Docker Hub, but feel free to comment if you think I closed this by mistake
