### ISSUE TITLE
Adopting "convenience" APIs for often-needed/used commands

### ISSUE THREAD

**Issue by kevinSuttle** [docker/docker#13719]
Forgive me if this has been discussed elsewhere, but being a beginner Docker dev, I am noticing there is a lot API UX improvement to be had with commonly-used commands. 

*Example*: Me: "Hm. how do I do X? [_Googles. Ends up on StackOverflow, where an answer has been upvoted by a few hundred other people_] To me, this represents an opportunity to improve the CLI/API. 

`docker rmi -f $(docker images -q -a -f dangling=true)`

Why not `docker rm --dangling` or something a little more guessable?

Another example:

` docker inspect --format '{{ .NetworkSettings.IPAddress }}' {$CID}`

Why not `docker ip $CONTAINER_NAME`? 

Does that make sense? Is this overlooking something obvious and non-trivial?

**Comment by kevinSuttle** [comment]
Found some more here as well. 
http://viget.com/extend/how-to-use-docker-on-os-x-the-missing-guide

Are there people on the docker team specifically focused on CLI UX?

**Comment by duglin** [comment]
@kevinSuttle the hard part is trying to find a balance between being flexible and user-friendly.  Your example of `docker ip $CONTAINER_NAME` is a good one.  That would certainly be more user-friendly but then it would probably mean a new top-level command for each possible property of interest on a container - which may in fact make the UX worse in the long run.

Instead, I wonder if it wouldn't be better to define some short-cuts. For example:
```
docker rmi @dangling
```
so that we're not totally changing what's there today, but instead just offering some short-cuts, or aliases, where the user is asking docker to do the "calculation" of what the short-cut means.

Just a thought.

I'm going to close this, not because its not worth considering, but rather because its not concrete enough to take action on. If you can think of specific new top-level commands to be added, or want to pursue something else (like that alias thing) then it would be best to open up a new issues with the specific proposed change so that the discussion is more concrete/targeted. 

Thanks!

**Comment by thaJeztah** [comment]
> so that we're not totally changing what's there today, but instead just offering some short-cuts, or aliases, where the user is asking docker to do the "calculation" of what the short-cut means.

Agreed, I think most cases can be addressed by using aliases. Determining what are "frequently used" commands is hard to do, because that's something that will differ from user to user.
