### ISSUE TITLE
Aufs vs Devicemapper via get.docker.io installation

### ISSUE THREAD

**Issue by fruitl00p** [docker/docker#13735]
According to the now (official) dockerbench rule [#2.7](https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.6_Benchmark_v1.0.0.pdf) "```2.7 Do not use the aufs storage driver```" Its seems recommended to just use the devicemapper. Shouldn't the [magic install url](https://get.docker.io/) reflect this and _not_ install the -extra linux image packages in order to allow for AUFS?

I'd say just dropping the aufs packages and requirements for (at least) Ubuntu 14.04+ would suffice?

Thanks!

**Comment by fruitl00p** [comment]
As this isn't a true 'bug' in the form of misconduct of the application (and i've searched the issues already)   i stand by my issue as stated: either refrain from aufs or do not push it as a guidline ;)

**Comment by thaJeztah** [comment]
Hm, interesting remark. There's a lot of discussion around the storage drivers. Ideally, we'd promote "overlay" to be the default driver, because it's part of recent kernels, however, there are still [some issues](https://github.com/docker/docker/issues?q=is%3Aopen+is%3Aissue+label%3A%2Fsystem%2Foverlay) that need to be fixed.

Devicemapper also has it's share of issues and the *default* settings for devicemapper are really not recommended for production use (this requires additional configuration that cannot be done automatically), and isn't the best user-experience out of the box.

And afaik, "BTRFS" is not available by default..

So we're a bit "between a rock and a hard place", where AUFS at this moment gives a nice balance between those issues. I'm not sure there are still issues related to kernel crashes with aufs on a fully updated system (I haven't heard of those in quite a while).

I *do* agree that it's confusing, because of the recommendation in that document.

For reference, this is the text in the linked document;

> The 'aufs' storage driver is the oldest storage driver. It is based on a Linux kernel patch-set
that is unlikely to be merged into the main Linux kernel. 'aufs' driver is also known to
cause some serious kernel crashes. 'aufs' just has legacy support from Docker. Most
importantly, 'aufs' is not a supported driver in many Linux distributions using latest Linux
kernels.

@crosbymichael @diogomonica @ewindisch @NathanMcCauley what are your thoughts here?

**Comment by fruitl00p** [comment]
(just for the record: we've been running on AUFS everywhere and haven't seen any kernel issues as well... so moving to devicemapper wouldn't actually be my preference, but i do like to adhere to best practices as much as i can... )

**Comment by fruitl00p** [comment]
@thaJeztah @GordonTheTurtle revived this issue from the queue and it seems there is still no hard preference for one or the other.... (as currently AUFS still seems the way to go...)

Also pointing to [Select a storage driver.](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/) from the docs should heb everyone i guess... 

My stance right now is: just go with the defaults ... (which is AUFS for ubuntu for now)
