### ISSUE TITLE
Files have write bit set even when the volume was mounted from the host with read only flag

### ISSUE THREAD

**Issue by edmorley** [docker/docker#13789]
Boot2Docker 1.6.2 on Windows, from within the VM:

Run:
```bash
docker@boot2docker:/c/Users/Ed/src$ touch foo && docker run -it --rm -v /c/Users/Ed/src/foo:/foo:ro centos:7 ls -l foo
```

Expected:
```-r-xr-xr-x 1 1000 ftp 0 Jun  7 03:25 foo```

Actual:
```-rwxrwxrwx 1 1000 ftp 0 Jun  7 03:25 foo```

The reason this is problematic, is that some base images (eg mysql) [recommend](https://github.com/docker-library/docs/tree/master/mysql#using-a-custom-mysql-configuration-file) using host volume mounts as a way to add your custom config into the container. However in the case of mysql, it bails if the conf file is world-writable. eg:
```bash
db_1  | Warning: World-writable config file '/etc/mysql/conf.d/my.cnf' is ignored
db_1  | Warning: World-writable config file '/etc/mysql/conf.d/my.cnf' is ignored
db_1  | Warning: World-writable config file '/etc/mysql/conf.d/my.cnf' is ignored
```

I was hoping to work around this by adding the read-only flag (``:ro``) to the volume parameter passed to docker - but this doesn't affect the file permissions showing inside the container, so I still get the error above.

I know I can create a new Dockerfile with a ``FROM mysql``, copy the config in and ``RUN chmod ...``, however this seems overkill (and also currently hits a different bug: docker-library/mysql#74).

**Comment by edmorley** [comment]
docker@boot2docker:/c/Users/Ed/src$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
docker@boot2docker:/c/Users/Ed/src$ docker info
Containers: 4
Images: 119
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 127
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.0.3-boot2docker
Operating System: Boot2Docker 1.6.2 (TCL 5.4); master : 4534e65 - Wed May 13 21:24:28 UTC 2015
CPUs: 8
Total Memory: 1.957 GiB
Name: boot2docker
ID: IFFH:DGAO:TNEI:WTMS:DMIT:S2TH:523T:SRJ5:C5DI:AGDS:2D2D:FYXN
Debug mode (server): true
Debug mode (client): false
Fds: 32
Goroutines: 53
System Time: Sun Jun  7 03:39:31 UTC 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
docker@boot2docker:/c/Users/Ed/src$ uname -a
Linux boot2docker 4.0.3-boot2docker #1 SMP Wed May 13 20:54:49 UTC 2015 x86_64 GNU/Linux

**Comment by thaJeztah** [comment]
Unfortunately, this won't be possible, or at least, not possible without dangerous side-effects.

When using a bind-mounted volume, docker literally *mounts* those files/directories in the container, keeping the permissions on the files and folders as-is; owner (uid), group (gid) and permissions of the files are the same as they are on the host (because they *are* the same files)

Passing the `:ro` option, makes Docker mount the files using a read-only mount, but will *not* make changes to the files themselves. This **will** make them read-only;

```bash
$ docker run -it --rm -v $(pwd)/foo:/foo:ro ubuntu bash -c "ls -la /foo && touch foo"                                               
-rwxrwxrwx 1 www-data www-data 0 Jun  7 10:46 /foo
touch: cannot touch 'foo': Read-only file system
```

What you're asking for is to actually *change* the permissions on those files, thus, changing the permissions of the files on your host. This is *not* something we want. Imagine what would happen of someone did;

    $ docker run -v /c/Users:/users:ro ubuntu

And all files and folders in `C:\Users` end up being read-only.

*However*, given the fact that owner and permissions are the same on the host as in the container, you can change the permissions of the file *before* mounting it in the container.

For example (I used the uid/gid for www-data on ubuntu here, but the same applies to mysql);

```bash
touch foo
chown 33:33 foo
chmod 500 foo 

docker run -it --rm -v $(pwd)/foo:/foo:ro ubuntu bash -c "ls -la /foo"

-r-x------ 1 www-data www-data 0 Jun  7 12:00 /foo
```

I'm going to close this issue, because this is not something that's going to be implemented, but I hope my explanation and examples will help you for your use-case.

Feel free to comment here after I've closed the issue.

**Comment by edmorley** [comment]
Thank you for your reply :-)
I wasn't aware that was how the mounts worked - makes sense now, thank you.

Unfortunately I ideally need this to work from a git clone (eg so new contributors can just clone and run docker-compose build), and git only supports remembering the exec bit, not the write bit - so I don't think I can use that solution.

It sounds like perhaps the best way forwards is for me to file an issue against the mysql base image and ask them to add support for setting file permissions as part of container startup or ignoring them outright if a certain ENV variable is set (this is just for local development, the permissions don't really matter).

**Comment by edmorley** [comment]
(Or of course just add another Dockerfile with a ``FROM mysql``, ``COPY ...``, ``RUN chmod 644 ...`` etc, once the mysql base image issue mentioned above is resolved).

**Comment by thaJeztah** [comment]
I think that would be the recommended approach; remember that bind mounted "volumes" are not portable (unless you upload the config file to the production server(s) first). They can be great during development, but less useful in production.

I'm glad to hear my explanation helped you further; I realise working with Docker has a learning curve and sometimes needs a different "mind set" than you're used to. Good luck with finding an approach that works for your use-case!

**Comment by edmorley** [comment]
Actually I wonder if I'm focusing on the wrong root cause?

The bind-mounted volume preserving the file permissions would not be a problem, if the file permissions were not 777 in the first place. 

These files are not world-writable in Windows (they're in my user folder), but yet inside Boot2Docker they are -rwxrwxrwx. Seems like Boot2Docker's auto-mounting of the user directories should use a ``,dmode=755,fmode=644`` here:
https://github.com/boot2docker/boot2docker/blob/b12462f293a5e19552bacb8349abb0f85d450bf6/rootfs/rootfs/etc/rc.d/automount-shares#L11
...though I wonder how many existing projects that would break, that rely on that behaviour!

**Comment by thaJeztah** [comment]
I'm not a boot2docker user myself, but I know there are several issues around that (main cause here is limitations in VBox share, which is used to share you hosts directories with the VirtualBox Virtual Machine)

I suggest to search the Boot2Docker issue tracker, because there are various issues on that and I think there are some Workarounds mentioned in those discussions.

**Comment by aa21** [comment]
Hi, did anyone figure out the easiest workaround for the "World-writable config file is ignored" problem?

**Comment by docwhat** [comment]
If this is due to Boot2Docker and windows, then you can create a docker volume (`docker volume --help`) and copy your config files in there via something like `busybox` or `ubuntu`.  Then adjust the permissions there.

Then mount the volume in your container as the configuration files.

Another alternative is to bake your config file into a docker image right before `docker run` (don't push this to a repository, though).

**Comment by cdalexndr** [comment]
Encountered this issue using elastic apm-server and mounting `apm-server.yml:/usr/share/apm-server/apm-server.yml:ro`:
`Exiting: error loading config file: config file ("apm-server.yml") can only be writable by the owner but the permissions are "-rwxrwxrwx" (to fix the permissions use: 'chmod go-w /usr/share/apm-server/apm-server.y
ml')`

Setting the file as read-only solved this issue.
My problem is that the file is generated on build, and now I have to add another build step to make the file read-only... (bummer)

Regarding the issue where mounted file has the same permissions as host file, a workaround is to copy the file into a temporary location, mark it as read-only and mount it, thus it will have the correct file permissions inside container.
