### ISSUE TITLE
Notifications of outdated packages in the container

### ISSUE THREAD

**Issue by silentmoose** [docker/docker#13842]
i simple version check of each package installed compared to the new package available from the repos. This would help stop people from leaving insecure packages in a container, which i believe could be a huge security issue as docker continues to gain more popularity.

**Comment by thaJeztah** [comment]
Hi @silentmoose, thanks for thinking along, but this is not something we can implement. Checking what's installed inside a container and keeping it up-to-date is the responsibility of the maintainer of that image. In addition, some images contain just a single binary (and no operating system)

When using images from Docker Hub, make sure you always use the "official" images, and images from trusted sources, preferably "automated builds", so that you are able to check what's *inside* the image (how it's build, and want files were used to build the image). For extra security, build your own images.

I'm going to close this issue, because this is not something Docker can control, but feel free to comment here after I closed the issue.

**Comment by silentmoose** [comment]
thanks for your detailed explanation. You could have easily just closed this and forgot about it.

Perhaps there is another way to implement this. The only idea i have is a universal package manager.
