### ISSUE TITLE
Allow Dockerfile ADD For File In .dockerignore

### ISSUE THREAD

**Issue by dsanders11** [docker/docker#13874]
Behavior in Docker 1.5.0 (haven't tested in 1.6.2 but I don't see changes to this behavior mentioned anywhere) does not allow files covered by `.dockerignore` to be used in an `ADD` command in the Dockerfile.

It would be very useful to allow an explicit `ADD` in a Dockerfile for a file that falls under the exclude patterns in `.dockerignore`. For example:

````
ADD . /mydir/

RUN long-running-build-command

ADD docker-entry.sh /mydir/docker-entry.sh
````

If `docker-entry.sh` is not in the `.dockerignore` file for the directory, it will cause the first step and the long build command to be executed again instead of being used from cache whenever `docker-entry.sh` changes. If it is covered by `.dockerignore` then the first two steps will not be executed again any time it is changed, but the third step will fail with `docker-entry.sh: no such file or directory`.

For comparison, `git add` will let you add a file covered by `.gitignore`, although you need to use the `-f` flag to force the add.

**Comment by duglin** [comment]
The order in which docker processes .dockerignore and the Dockerfile are important to understand why doing what you're suggesting would be really hard.  When you do a `docker build`, the docker cli will use the .dockerignore file to decide what **not** to send to the daemon for the build. The Dockerfile itself is never looked at during this processing. And I'm not sure it should be because that would require quite a bit of smarts especially when you throw in things like wildcards into the mix.

So, once on the daemon, then the Dockerfile is processed. At that point trying to add back in a file that was excluded via .dockerignore would be impossible because the daemon doesn't have it available.

If you really want to include just one file I would recommend that you modify your .dockerignore to exclude it via the `!` syntax (e.g.   `!docker-entry.sh` ).

I'm going to close this one for now because I think there's a workaround (`!`).  Please reopen if you think I'm missing something.

**Comment by dsanders11** [comment]
I think you're missing something, yea. I'm not sure how negation in the `.dockerignore` file works around the issue, since that is the equivalent of not having it in the `.dockerignore` file to begin with. That causes the first `ADD` and the subsequent large `RUN` to be executed any time the file changes.

I've got a project with the Dockerfile in the root (as seems to be the custom). It's a large project with lots of directories, so I use `ADD . /mydir/` to add the whole project, rather than reconstructing the entire directory structure in the Dockerfile. Then I want to exclude a few things such as `git` files and some project files that aren't needed.

````
# .dockerignore
.git
.gitignore
development-only-dir
````

So you can see the `docker-entry.sh` script doesn't show up anywhere here, it gets pulled in with the original `ADD . /mydir/`. If that file is modified a lot, it's going to constantly be triggering the Dockerfile build to start back from that first `ADD` every time, even though it is not used in the `RUN`, it is only used as the `ENTRYPOINT` for the image. Adding it to `.dockerignore` fixes that issue, but prevents it from ever being added back, so it can't be used.

That's the main dilemma here. The real work around would be to not do `ADD . /mydir/` but `ADD this-dir that-dir foo bar /mydir/`, which is not good from a maintenance perspective.

The example I give is for an `ENTRYPOINT` script, but I can imagine lots of situations where this comes up. Basically any file that might change a lot should ideally be thrown in at the end of the Dockerfile to avoid constantly invalidating earlier cached layers even though nothing in them has really changed. Entrypoint scripts, config files, documentation, etc. All of those would benefit from not invalidating the earlier cached layers (especially for thrash when uploading to a registry) and only changing a layer that they affect.

I believe I understand why it may be hard to implement, but it would certainly be very useful on larger projects. To clarify my understanding, if you *don't* have a `.dockerignore` file, then the entire build working directory gets sent to the daemon?

**Comment by duglin** [comment]
@dsanders11 yes, w/o a .dockerignore the entire build (context) dir is sent to the daemon.
In order to do what you're suggesting, our .dockerignore processing would need to scan the entire Dockerfile for any ADD/COPY and include that src file in the build context despite it being mentioned in the .dockerignore - and then ignore it during some ADD/COPY commands (like your ADD . /mydir).  That's a lot of extra processing that I think would be hard sell.

When the builder is moved over to the client (and we stop sending the build context to the daemon) we may be able find a solution for you.

**Comment by nikhilo** [comment]
@dsanders11 Were you able to find a workaround for this problem?

**Comment by dsanders11** [comment]
@nikhilo, I was not able to find a workaround. I've just put up with the unnecessary wastage during builds, unfortunately.

**Comment by rainchen** [comment]
I have the exactly the same situation as @dsanders11.

Here is the expectation detail: 

```
ADD . /mydir/ # I will like to exclude docker-entry.sh since it will be changed frequently

RUN long-running-build-command # I would like this layer cached when docker-entry.sh changed

ADD docker-entry.sh /mydir/docker-entry.sh # add docker-entry.sh to image. If I add docker-entry.sh to .dockerignore, this step will be aborted by an error as "no such file or directory"

```

I will like to exclude `docker-entry.sh` since it will be changed frequently, and it's nothing to do with the `long-running-build-command`.

Any solution for current version Docker (v18.03.1-ce) ?

**Comment by lcasassa** [comment]
> That's the main dilemma here. The real work around would be to not do ADD . /mydir/ but ADD this-dir that-dir foo bar /mydir/, which is not good from a maintenance perspective.

I'm with @dsanders11 here. Any other workaround?

Maybe do a `ls` and remove `docker-entry.sh` from the list? How could ye do that? Pass it as a docker variable?

docker build --build-arg LIST_OF_FILES_TO_COPY=$(ls | grep -v docker-entry.sh|xargs) .

```
ARG LIST_OF_FILES_TO_COPY
ADD $LIST_OF_FILES_TO_COPY /mydir/

RUN long-running-build-command
ADD docker-entry.sh /mydir/docker-entry.sh
```

That could work but I'm hating the idea of depending on a complicated docker build line for it to work. I could add it on a make file so users would do `make build` :/

**Comment by thaJeztah** [comment]
I think this could be resolved if an `--exclude` option was added to `COPY`, as proposed in https://github.com/moby/moby/issues/37333. That way the Dockerfile can be the source of truth as to what needs to be copied (or _ignored_ when copying).

This proposal may also be relevant/related; https://github.com/moby/moby/issues/37129 ("Proposal: add support for multiple (named) build-contexts")
