### ISSUE TITLE
Docker Daemon hangs when requesting a network namespace of self

### ISSUE THREAD

**Issue by Tweenagedream** [docker/docker#13897]
Try this 
```
docker run -it --name="supercool" --net="container:supercool" centos7 /bin/bash
```

docker version
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

docker info
```
Containers: 3
Images: 17
Storage Driver: aufs
  Root Dir: /var/lib/docker/aufs
  Backing Filesystem: extfs
  Dirs: 23
  Dirperm1 Supported: fakse
Execution Driver: native-0.2
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 15.32 GiB
```

Running on physical hardware

Command to reproduce is above

Results received: Docker hung
Results expected: Docker giving an error OR starting as normal in its own Network namespace

**Comment by LK4D4** [comment]
It was fixed before libnetwork integration btw.

**Comment by aboch** [comment]
It seems it's fixed in 1.7. It returns the error.

$ ./docker version
Client version: 1.7.0-dev
Client API version: 1.20
Go version (client): go1.4.2
Git commit (client): 08fd887-dirty
OS/Arch (client): linux/amd64
Server version: 1.7.0-dev
Server API version: 1.20
Go version (server): go1.4.2
Git commit (server): 08fd887-dirty
OS/Arch (server): linux/amd64
$ 
$ ./docker run -it --name="abc" --net="container:abc" fedora /bin/bash
Error response from daemon: Cannot start container bcde42821e48256752952d43e8f0aff27bef1024d929d20c391fc1b07cef8869: cannot join own network
$

**Comment by LK4D4** [comment]
@aboch Nice

**Comment by cpuguy83** [comment]
Great, closing since it sounds like this is fixed.
