### ISSUE TITLE
devicemapper: Verify base device UUID upon startup

### ISSUE THREAD

**Issue by rhvgoyal** [docker/docker#13894]
There are so many easy ways that docker device mapper metadata and actual thin pool can get out of sync due to configuration errors. In that case we often hear the problem that image and containers are not in the pool or are missing etc. I think lot of these errors are due to configuration issues.

Users created one type of pool, did some IO. Later something changed and a new pool was setup or user switched to LVM thin pool without cleaning up metadata which was valid only for old pool. 

So to detect these kind of issues, query and save the UUID of base image and during startup make sure saved UUID matches the one in the pool. If not, flag error and docker startup will fail.

This should detect lot of configuration issues pretty early.

**Comment by rhvgoyal** [comment]
@vbatts 

This is merged now. So this issue can be closed, I think.

**Comment by kawa636r** [comment]
This was a very worst idea. 
Actually i can't start Docker because of an lvm resize, and there is not a way to disable this functionality or to reinizialize the udid

**Comment by rhvgoyal** [comment]
@kawa636r 

Can you give more details about how did you resize lvm thin pool. Resizing should not break it down. Pool continues to be same just that it is bigger now.

**Comment by kawa636r** [comment]
Hi Vivek, i've opened an issue here : https://github.com/docker/docker/issues/15721

**Comment by anaderi** [comment]
I got stuck with similar symptoms after running container hit disk limit. 
Managed to fix it by 

    blkdeactivate /dev/mapper/docker-252:1-50331783-pool
    blkdeactivate /dev/loop0

and then starting docker again (`docker-engine-1.8.3-1.el7.centos.x86_64`)

**Comment by LK4D4** [comment]
@anaderi Better to open new issue or continue in #15721

**Comment by jonseymour** [comment]
I had a scenario where I needed to import an existing docker vg into different Azure VM and the Base UUID of the data LV appeared to be different to its original value in the original VM. AFAIK there was no other LVM related configuration that could explain this - just the need to move the VG between two Azure VMs.

Note that I am not 100% sure that the UUID check failed because I moved the vg between VMs - there may be another explanation, but I thought I would not it hear just in case others come across the same issue with Azure VMs.
