### ISSUE TITLE
Plugins documentation is broken on V1.7rc5

### ISSUE THREAD

**Issue by yoanisgil** [docker/docker#13990]
On this page:

https://github.com/docker/docker/blob/v1.7.0-rc5/experimental/plugin_api.md

the link for users willing to use plugins is broken. The feature overview link is also broken:

https://github.com/docker/docker/blob/v1.7.0-rc5/userguide/plugins
https://github.com/docker/docker/blob/v1.7.0-rc5/experimental/experimental.md

**Comment by thaJeztah** [comment]
@yoanisgil help me out a bit, because I can't find a link on this page; https://github.com/docker/docker/blob/v1.7.0-rc5/CHANGELOG.md

(Perhaps I'm just overlooking it :smile:)

**Comment by yoanisgil** [comment]
@thaJeztah  My bad, I copied the wrong link. I just updated the issue description. This might not be a serious issue since links are correct on the master branch.

**Comment by thaJeztah** [comment]
Ah, thanks, glad I wasn't going mad. Looks that this was indeed resolved in https://github.com/docker/docker/pull/13836, but I see that PR isn't added to the milestone, so thanks for paying attention!

**Comment by thaJeztah** [comment]
@icecrime this was already fixed in https://github.com/docker/docker/pull/13836, so I added that PR to the milestone, I'm going to close this issue, but pinged Jess on the PR for cherry-picking.

Thanks again for reporting this, @yoanisgil :+1: I'm going to close this issue because it's already resolved
