### ISSUE TITLE
What does the error message: "error creating aufs mount to .." mean?

### ISSUE THREAD

**Issue by jsuit** [docker/docker#14137]
When I try to build a dockerfile, I get the error message: 
 
error creating aufs mount to /var/lib/docker/aufs/mnt/54f1c9be7a4455861a3412e2f93c84eaf82c0e50eff1565f34e0f06f7a01eea1-init: invalid argument

What does it mean, and more importantly, how do I fix it?

**Comment by cpuguy83** [comment]
It is an error directly from the kernel mount call.
It probably means there is already something mounted there (maybe from an unclean shutdown of docker?)

Check your mount table.
Closing since this is not a Docker issue.

For additional troubleshooting, feel free to hop on #docker on IRC, docker-user ML, or forums.docker.com

Thanks!
