### ISSUE TITLE
Doc: List is not formatted correctly in swarm/scheduler/filter/

### ISSUE THREAD

**Issue by alvinr** [docker/docker#14192]
# Problem

See 

![screen shot 2015-06-24 at 4 06 07 pm](https://cloud.githubusercontent.com/assets/336450/8367753/772a554c-1b56-11e5-83a4-39e841c3e4f7.png)

Looks like this should be a list but it is not formatted as a list. May be a generic issue across all lists - would need to be confirmed.

# Reproduce
See https://docs.docker.com/swarm/scheduler/filter/

**Comment by thaJeztah** [comment]
@alvinr hi Alvin, thanks for reporting this. This part of the documentation is actually in the Swarm repository; https://github.com/docker/swarm/blob/master/docs/scheduler/filter.md

I had a quick look at the source of that document, and I think the problem here is that there's no blank line before the list; there are actually a number of lists in that document that miss a blank line and are not rendered properly.

I copied your issue to the Swarm repository https://github.com/docker/swarm/issues/1021 so will close this one.
