### ISSUE TITLE
Difference between Storage Driver and Backing Filesystem

### ISSUE THREAD

**Issue by amoalsale** [docker/docker#14289]
Hi 
I am trying to understand Docker storage. I am not understanding the difference between Storage Driver and Backing Filesystem correctly.
Can someone please explain it?
What I want to know is -
1. What are all supported backing filesystems?
2. How can I change backing filesystem type?
3. Is storage driver different from backing filesystem?

**Comment by cpuguy83** [comment]
Assumning by `backing filesystem` you mean as is outputed by `docker info`.
In this case `backing filesystem` is the filesystem that the graphdriver is sitting on top of (generally the host fs).

The storage driver (or graph driver) is the CoW/Layering system that docker implements with the help of other filesystems (like aufs, overlay, btrfs).

Closing because this is not an issue.
If you'd like to discuss further, please check out #docker on IRC or the docker-user mailing list.

**Comment by amoalsale** [comment]
Thank you for your timely reply.
