### ISSUE TITLE
Pull override local image even if more recent

### ISSUE THREAD

**Issue by athieriot** [docker/docker#14382]
Hi,

   I have just noticed that, if I have an older image in my repository than I have locally, a ```docker pull <image>``` will erase my local image and just replace it with the one in the repository. Regardless of any timestamps.

   Our use case would be for development purposes, when we are trying a new images (not pushing them) and using a test script which is common for dev and automation.

   Is there a way to tell docker not to pull the image if the local one is newer?

Thanks

**Comment by unclejack** [comment]
This question has come up before and there are closed issues on this topic. Local images shouldn't be tagged with names of remote images. You should use a different tag locally and only tag images with the remote tag when you want to push them.

Please look up previous discussions on this topic on this issue tracker. I'm going to close this now because it's been discussed already.

**Comment by athieriot** [comment]
Oh, all right thanks.

I did search for a possible duplicate but couldn't find any.
Sorry about that.

Thanks for the answer !

**Comment by unclejack** [comment]
The previous issue is https://github.com/docker/docker/issues/10291
