### ISSUE TITLE
Create troubleshooting section to consolidate notes in volumes doc

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#14393]
docs/userguide/dockervolumes.md

See https://github.com/docker/docker/pull/14235 for discussion

**Comment by jhall39** [comment]
Regarding your commit: https://github.com/docker/docker/commit/2920550211f8829b61107f7aaebbabdcaba761b3
I'm using Docker on windows via the version of Git Bash that it installs. I have to do a double forward slash in front of my path to make it work.

    docker run -d -p 8000:80 -v //c/Users/test:/var/www php:5.6-apache

instead of

    docker run -d -p 8000:80 -v /c/Users/test:/var/www php:5.6-apache

Maybe I missed something but this is from the commit that says it closes #14234

**Comment by LK4D4** [comment]
ping @thaJeztah

**Comment by thaJeztah** [comment]
boot2docker is largely replaced by Docker for Windows / Docker for Mac, which both have a troubleshooting section; https://docs.docker.com/docker-for-mac/troubleshoot/, https://docs.docker.com/docker-for-windows/troubleshoot/. I'll close this issue
