### ISSUE TITLE
update docs around volumes

### ISSUE THREAD

**Issue by rwatts3** [docker/docker#14449]
Please provide documentation on how to properly create a bind between the container and the host machine.

**Comment by cpuguy83** [comment]
@rwatts3 First of all, pull requests are always welcome if you find something is missing. This is a community supported project, with thousands of hours poured into it by the community.

Second, if there is a some missing docs, lets keep this issue focused on that.
For support, please see #docker on IRC, the docker-user mailing list, or forums.docker.com

That said, the API is documented here: https://docs.docker.com/reference/api/docker_remote_api_v1.19/#create-a-container

Specifically, to mount a file/folder from the host into the container, see the section on "Binds", in HostConfig.Binds.
A basic configuration looks like so:
```json
{
    "Image": "busybox",
    "HostConfig": {
        "Binds": [
            "/tmp:/host_temp"
         ]
    }
}
```

**Comment by rwatts3** [comment]
Thank you , this helps and I see where documentation may have been updated to better explain this process.  I have another question however.  

What is the process for starting a container using a container_settings.json file.  In the file I'll define the port and host name that I want to use to run my instance.  Essentially I am trying to get to my site running in docker but going to mydomain.com instead of the ip address of my vps

**Comment by ankushagarwal** [comment]
@rwatts3 : docker does not handle that. You should look at the nginx web server and the `server_name` directive to handle your issue.

@thaJeztah : I think this issue can be closed.

**Comment by thaJeztah** [comment]
@rwatts3 for an easy to use solution, you might be interested in https://github.com/jwilder/nginx-proxy, which maps domain-names to containers. However, the GitHub issue tracker is not a support forum, so if you need more help, please use one of these; https://github.com/docker/docker#talking-to-other-docker-users-and-contributors

I'm closing this issue, because I think your question(s) have been answered (Thanks for the ping, @ankushagarwal )
