### ISSUE TITLE
Docker inspect returns all execsids

### ISSUE THREAD

**Issue by bprashanth** [docker/docker#14444]
It looks like docker inspect returns a full list of exec ids for each container. The listing happens here: https://github.com/docker/docker/blob/e69df2589c1220217054abdc6a361b55990b3c0b/daemon/inspect.go#L108
And AFAICT an exec id is only deleted during cleanup: https://github.com/docker/docker/blob/caa4acc7b11cbefb74d0b066d4a0752f4a11c5ee/daemon/container.go#L355

We use execs for container health checks, and inspect for periodic housekeeping. on my 12 hour old cluster, a single container built up a list of 7000 exec ids, resulting in cpu wasted on json decoding (gce n1-standard-1s don't have much to spare). I found https://github.com/docker/docker/issues/12899 but that doesn't address docker inspect output.

As a work around, one can restart old execs if the commnds are the same, but that feels like a hack. I feel like this is WAI at some level, yet I don't understand why, so I'm looking for enlightment :)

**Comment by bprashanth** [comment]
docker version:
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

docker info:
```
Containers: 6
Images: 30
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 42
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy) (containerized)
CPUs: 1
Total Memory: 3.625 GiB
Name: e2e-test-beeps-minion-uvc4
ID: RDE5:QVIF:N7AY:3HE5:QO3N:3BRW:5CJE:4PHV:GQ4D:TH3C:SORU:Z5YT
WARNING: No swap limit support
```
uname -a:
```
Linux e2e-test-beeps-minion-uvc4 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1~bpo70+1 (2015-04-27) x86_64 GNU/Linux
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):
Running on gce

List the steps to reproduce the issue:
 - Create a pod 
 - Keep execing commands into it

Describe the results you received:  unbounded growth of exec ids reported by docker inspect
Describe the results you expected: bounded cpu (/memory) usage in decoding the json returned by docker inspect

**Comment by cpuguy83** [comment]
Closing as this is a dup of... several.

Exec is only ever intended to be used for debugging purposes, not constantly spawning new things in the container.

**Comment by bprashanth** [comment]
@cpuguy83 hmm, is there a better way to periodically exec things in the container (or is that straight-up unsupported)?

**Comment by thockin** [comment]
@icecrime @shykes @crosbymichael  seriously?  This is pretty pathetic - we have this super cool feature, oh but don't use it.

**Comment by icecrime** [comment]
@cpuguy83 Seems like a bug to me, why wouldn't the ExecID cleaned when the exec job terminates?

**Comment by cpuguy83** [comment]
There's a few discussions on this, unfortunately GH issue search is terrible.

**Comment by icecrime** [comment]
Let me try this out, either I'm missing something, or this is a one line change.

**Comment by duglin** [comment]
@icecrime I think the bigger issue here is around what 'docker exec' is for.  I think there are two camps:
1 - its just for debugging and therefore won't be used that often
2 - its a general purpose way to run a secondary process in a container

Personally, I'm not fond of Docker telling people what they should use 'exec' for - if they want to call it a million times then so be it. If they want to have it start a long running process, then so be it.  Why should Docker care as long as the user understands the constraint that once the main (first) process dies, all other processes will die too.

ping @shykes

**Comment by icecrime** [comment]
I think most people on the team here would agree with 1, but still, `exec` is there.

From what I'm seeing, the `ExecConfig` never being cleaned up is necessary for the client to retrieve the `exitCode`, because contrary to containers we don't have proper `wait` and `delete` endpoints. I don't see any easy way without expanding `exec`'s scope (which would really like to avoid).

I proposed what I think is a somewhat acceptable workaround in #14452, let me know how that sounds.

**Comment by crosbymichael** [comment]
I don't understand what the deal is for the comment in the issues. This is clearly a bug so we should fix it.  We do know when the exec processes die within the daemon so this is a trivial fix.

There is no need for extra endpoints, detached or not, etc.  We have all this information in the daemon because the daemon always does a wait on any processes it launches.

**Comment by crosbymichael** [comment]
I will fix this issue

**Comment by icecrime** [comment]
Just my 2cts: yes, the daemon waits and perfectly knows when the exec job is complete. But if we immediately clean up, we break the ability for the client to query the exitCode after the fact. That being said, I hope I'm missing something and there's an easy fix.

**Comment by duglin** [comment]
@icecrime that was my assumption as well.  But if we don't need to worry about querying the exec info once its done running then yes its an easy fix.

**Comment by crosbymichael** [comment]
Yes that is true.  We still need to query for it for getting the exit status but we can remove it from the container inspect because that code path is not hit for the wait endpoint.  I have this part fixed and now looking into the memory issue of keeping that long list of exec state on the daemon without cleanup.

We have a few options for this, run a GC to clean unreferenced exec configs on an interval or other types of cleanup.

**Comment by duglin** [comment]
One option is to keep a "dead list" in the container that isn't returned on "inspect" but is cleaned-up when the container is deleted.
