### ISSUE TITLE
UX: implement "tree view" for docker images

### ISSUE THREAD

**Issue by jberkus** [docker/docker#14482]
For users with large numbers of images on a single machine, it would be extremely useful to implement a "tree view" which shows how images depend on each other, and what running containers depend on what images.

**Comment by cpuguy83** [comment]
See #5001

**Comment by AxelVoitier** [comment]
Too bad they removed it from the core. It was very useful to maintain the images because it get messy very fast (and IMO, something that help maintaining docker setup clean deserve to be considered as a core feature).

Anyway, the functionality as been exported to an external tool from the original PR author of it:
https://github.com/justone/dockviz

**Comment by jfrazelle** [comment]
we had viz and now it is in that external tool
