### ISSUE TITLE
docker.service  does not allow drop-in to override ExecStart

### ISSUE THREAD

**Issue by deas** [docker/docker#14491]
Using the `docker.service` from here and creating a drop-in  `/etc/systemd/system/docker.service.d/override.conf` to tweak command line parameters (as documented at https://docs.docker.com/articles/systemd/)

```
[Service]                                                                                                                       
ExecStart=/usr/bin/docker -d -H fd:// --bip=172.17.42.1/16  
```

ends up with systemd refusing to start the daemon:

```
docker.service has more than one ExecStart= setting, which is only allowed for Type=oneshot services. Refusing. 
```

What is the recommended way to tweak the daemon command-line?

**Comment by tianon** [comment]
You need to add a line before that line with just "ExecStart=" to 'clear'
the setting first:

[Service]
ExecStart=
ExecStart=/usr/bin/docker -d -H fd:// --bip=172.17.42.1/16

**Comment by deas** [comment]
Thanks, that did the trick. Guess its worth being mentioned in the article at docs.docker.com.

**Comment by nhocki** [comment]
#dibs

**Comment by strongqli** [comment]
It seems that the empty line must has a space ' ' at least after '='

**Comment by thaJeztah** [comment]
@strongqli do quotes work (`ExecStart=""`)? If so, perhaps we should update the example in the documentation; https://docs.docker.com/engine/admin/systemd/#custom-docker-daemon-options

**Comment by tianon** [comment]
The completely empty version has been working for me, so I'd be interested in hearing more about your setup (`systemd` version, etc).

**Comment by Dieterbe** [comment]
thanks for the fix, it works.
but this is so weird.  when you have a single ExecStart, and systemd incorrectly states you have multiple and refuses to start docker, and then adding another, empty one (doing the opposite of what the error says) makes it work.

**Comment by thaJeztah** [comment]
I agree it's confusing, but that's the way systemd works :smile:

**Comment by ctxrag** [comment]
am having similar issue: docker does not start.

Jun 09 01:13:22 dtlu16 systemd[1]: Failed to start Docker Application Container Engine.
Jun 09 01:13:22 dtlu16 systemd[1]: docker.service: Unit entered failed state.
Jun 09 01:13:22 dtlu16 systemd[1]: docker.service: Failed with result 'exit-code'.
Jun 09 01:13:22 dtlu16 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Jun 09 01:13:22 dtlu16 systemd[1]: Stopped Docker Application Container Engine.
Jun 09 01:13:22 dtlu16 systemd[1]: docker.service: Start request repeated too quickly.
Jun 09 01:13:22 dtlu16 systemd[1]: Failed to start Docker Application Container Engine.
dtlu@dtlu16:~$ sudo systemctl start docker
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
dtlu@dtlu16:~$ sudo vi /etc/systemd/system/docker.service.d/override.conf
dtlu@dtlu16:~$ sudo vi /etc/systemd/system/docker.service.d/override.conf
dtlu@dtlu16:~$ sudo systemctl start docker
Warning: docker.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
dtlu@dtlu16:~$ systemctl daemon-reload
==== AUTHENTICATING FOR org.freedesktop.systemd1.reload-daemon ===
Authentication is required to reload the systemd state.
Authenticating as: dtlu,,, (dtlu)
Password:
==== AUTHENTICATION COMPLETE ===
dtlu@dtlu16:~$ sudo systemctl start docker
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
dtlu@dtlu16:~$ systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─override.conf
   Active: inactive (dead) (Result: exit-code) since Sat 2018-06-09 01:16:10 PDT; 13s ago
     Docs: https://docs.docker.com
  Process: 2299 ExecStart=/usr/bin/dockerd --host=fd:// --add-runtime=nvidia=/usr/bin/nvidia-container-runtime (code=exited, status=1/FAILURE)
 Main PID: 2299 (code=exited, status=1/FAILURE)

Jun 09 01:16:10 dtlu16 systemd[1]: Failed to start Docker Application Container Engine.
Jun 09 01:16:10 dtlu16 systemd[1]: docker.service: Unit entered failed state.
Jun 09 01:16:10 dtlu16 systemd[1]: docker.service: Failed with result 'exit-code'.
Jun 09 01:16:10 dtlu16 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Jun 09 01:16:10 dtlu16 systemd[1]: Stopped Docker Application Container Engine.
Jun 09 01:16:10 dtlu16 systemd[1]: docker.service: Start request repeated too quickly.
Jun 09 01:16:10 dtlu16 systemd[1]: Failed to start Docker Application Container Engine.
dtlu@dtlu16:~$

**Comment by ctxrag** [comment]
My files look like this: 
dtlu@dtlu16:~$ sudo cat /etc/systemd/system/docker.service.d/override.conf
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd --host=fd:// --add-runtime=nvidia=/usr/bin/nvidia-container-runtime


dtlu@dtlu16:~$ sudo cat /etc/docker/daemon.json
{
    "runtimes": {
	    "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}
{
   “dns”: [“172.20.130.181”]
}

**Comment by thaJeztah** [comment]
@ctxrag unfortunately, systemd doesn't print the actual error; check the daemon logs using `journald` to see why it's not starting.

Looking at your comment, I think it's because you add the `nvidia` runtime both through the flag (`--add-runtime`) and through the daemon.json; you can only use one of both methods, otherwise the daemon will report it as a "conflict" and not start

**Comment by thaJeztah** [comment]
Actually, looks like your `daemon.json` is invalid JSON as well (the dns part)

**Comment by ctxrag** [comment]
Hi Jez, 
what is invalid in daemon.json? 

secondly, I tried all the options and ended up reinstalling the docker and am in good shape now.

**Comment by thaJeztah** [comment]
You can see GitHub highlighting the JSON to be invalid; the daemon.json should be a valid JSON struct; on your example, something like:

```json
{
   "dns": ["172.20.130.181"],
    "runtimes": {
	    "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}
```

Also make sure that the file uses regular quotes (`"`), not curly quotes (`“`), as those are not valid in JSON
