### ISSUE TITLE
Persistence of local data of docker containers (Use case: Logs)

### ISSUE THREAD

**Issue by ee1200231** [docker/docker#14526]
I am using Docker containers + Mesosphere Cluster + Marathon + haproxy for my application.

The number of instances of my containers keep increasing or decreasing as per my scheduling. However, once a container is down, I lose the logs of it as well, which was by default stored inside the container (I think). How can I redirect it to a persistent storage?

**Comment by cpuguy83** [comment]
Hi,

By default docker consumes all the stdout and stderr of a container and stores that in a file on disk. This can be changed to use syslog (docker 1.6), journald (1.7), and in the next release several others (gelf, fluentd as of right now).

This would be the supported way to get your logs out of a container.
If you are storing logs on the container FS, I'd recommend instead sending those logs to stdout/stderr.
If you can't do that, then logs should be placed in a volume on the host and you'd need something to go and consume those logs for you.

Closing since this isn't really a docker issue.
For support please see #docker on IRC, the docker-user mailing list, or forums.docker.com
