### ISSUE TITLE
Docker can't find my images/containers

### ISSUE THREAD

**Issue by rotatingJazz** [docker/docker#14551]
On Ubuntu 14.04, I had faced the "docker won't start after upgrading to 1.7" issue, so I had downgraded to 1.6.2 and it worked fine.

Today, after a reboot, docker runs but cannot find any images or containers. The files still exist on disk, so it's not a hw failure.

````
# docker info
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /datadrive/dockerstore/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-29-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 3.362 GiB
Name: eru
ID: STRT:7755:73RU:BJ6W:3OKG:OUP4:6DGY:Z7O5:QPWF:HYKY:FC5W:KITI
WARNING: No swap limit support
````

The files/meta are on the `devicemapper` directory and the `aufs` one is empty.
````
# ls /datadrive/dockerstore/
aufs  containers  devicemapper  execdriver  graph  init  linkgraph.db  repositories-aufs  repositories-devicemapper  tmp  trust  vfs  volumes

# du -sk /datadrive/dockerstore/
23762420	/datadrive/dockerstore/

# du -sk /datadrive/dockerstore/aufs/
16	/datadrive/dockerstore/aufs/

# du -sk /datadrive/dockerstore/devicemapper/
21634000	/datadrive/dockerstore/devicemapper/
````

````
# cat /etc/default/docker 
DOCKER_OPTS="-g /datadrive/dockerstore"
````

I tried `apt-get install linux-image-extra-$(uname -r)`  as per [this](https://stackoverflow.com/questions/26237360/all-images-and-containers-disappeared-after-host-kernel-downgrade) discussion and rebooted, same problem. :sob: 

What can I do?

**Comment by rotatingJazz** [comment]
Added `--storage-driver=devicemapper` on the `DOCKER_OPTS` and it worked. :grinning:

**Comment by thaJeztah** [comment]
> I had faced the "docker won't start after upgrading to 1.7"

I suspect that the problem you were having, is that devicemapper on your system does not have "udev sync" support. Running without udev sync is known to cause problems and, in some cases, can lead to data corruption.

For that reason, docker 1.7.0 (deliberately) refuses to start if udev sync is not supported, but you can override that behaviour using the `dm.override_udev_sync_check` storage-opt. 

For more information see: https://github.com/docker/docker/pull/11412, https://github.com/docker/docker/pull/14415 and the issue described in https://github.com/docker/docker/issues/4036

So your best options are:

- Switch to the AUFS storage driver (but you will have to save / load your images to migrate them to the new storage driver)
- Build a dynamically linked version of docker: https://github.com/docker/docker/issues/4036#issuecomment-111174341. At this moment, we don't provide dynamically linked binaries for download.
- override the driver to use (`--storage-driver=devicemapper`) and set `--storage-opt dm.override_udev_sync_check=true`. **Use this at your own risk**, because this configuration is known to cause problems, as described in https://github.com/docker/docker/issues/4036

**Comment by rotatingJazz** [comment]
@thaJeztah Thank you! I've overriden the driver and will now make backups and migrate to a clean vm with 1.7.

**Comment by thaJeztah** [comment]
@rotatingJazz great! I know it's a hassle, but wanted to give you the right information so that you understand what's the cause / reason behind this!

If you have ideas on improving this (e.g., by better documentation around this), we welcome pull requests! :smile:
