### ISSUE TITLE
Recommendation for determining ephemeral port of linked container when using hostnames instead of env vars

### ISSUE THREAD

**Issue by danmartinez101** [docker/docker#14566]
In the documentation there is [a note](https://docs.docker.com/compose/env/) that it is no longer recommended to use environment variables for linked containers. Instead it appears we should use the host because this is automatically updated when changes occur(i.e. on container restart).

However, the hosts file doesn't contain a reference to the ephemeral port that is being listened on by the source container. With environment variables, this information appears to be available.

What is the recommended method of determining the host/ip + port that should be used?

**Comment by thaJeztah** [comment]
The consensus is that (in most cases), the port number of a service is known, e.g. PostgreSQL listens on 5432. As can be seen in the examples on that page, in order to obtain information about a service, you'll have to *know* the port-number in order to get the information, which makes the env vars pretty useless (a good example of that is `DB_PORT_5432_TCP_PORT=5432` :smile:)

Having said that, you can still use the `DB_PORT` env var to extract the port number if really needed, but keep in mind that the env vars will be deprecated in a future version (not yet determined).

For the IP address, using the host name is the recommended approach (as mentioned in the documentation)

/cc @mavenugo are there plans to offer discovery mechanisms for port numbers in libnetwork?

**Comment by cpuguy83** [comment]
The env vars never showed the ephemeral port used by the container, only the port specified by `EXPOSE`. So this is a known port.
Env vars are just not good for service discovery since they cannot be changed once started.
