### ISSUE TITLE
Improve documentation for Best Practices: RUN command

### ISSUE THREAD

**Issue by charleswhchan** [docker/docker#14572]
https://docs.docker.com/articles/dockerfile_best-practices/

I read the following suggestion a number of times and I don't quite understand what it means?
> Don’t do RUN apt-get update on a single line. This will cause caching issues if the referenced archive gets updated, which will make your subsequent apt-get install fail without comment.

1. Is it referring to Docker cache or apt cache?
2. What referenced archive is it referring to?

It would be nice if this first bullet can be improved. For example, the information the 2nd bullet is clear.

Also, it is important to clarify the documentation because other people may be using yum package manager and needs to understand the mechanics of the RUN command to follow the best practices.

**Comment by thaJeztah** [comment]
this recommendation is to make effective use of the docker cache, without running into problems (outdated packages). Say, you have this dockerfile;

```Dockerfile
FROM ubuntu:14.04
RUN apt-get update
RUN apt-get install -y curl
```

After building, all layers will be in the docker cache.

At a later stage, I modify my Dockerfile to install an extra package;

```Dockerfile
FROM ubuntu:14.04
RUN apt-get update
RUN apt-get install -y curl nxinx
```

Docker will detect that the first two lines didn't change, so use the cache for that. This results in the `apt-get update` *not* being done (it was in the cache), and potentially, an *outdated* version of curl and nxinx being installed.

That's why it's recommended to combine those lines; combining the `apt-get update` and `apt-get install` in a single run, so that adding a package, will automatically "bust" the cache, and makes sure that the `apt-get update` is also run.

**Comment by charleswhchan** [comment]
Excellent explaination, make sense to me now.

Is this information (or similar) captured some where or already? Perhaps I have overlooked it.
Otherwise, perhaps it can be included in the "best practices"?

**Comment by thaJeztah** [comment]
Well there's a "hint" at it here; https://github.com/docker/docker/blob/master/docs/reference/builder.md#run, but that refers to the "best practices" section for more details. I think it'd make sense in the best practices section :-)

**Comment by charleswhchan** [comment]
#dibs
