### ISSUE TITLE
Cannot find where images are stored

### ISSUE THREAD

**Issue by bitliner** [docker/docker#14582]
`/etc/default/docker` file has

`DOCKER_OPTS="--storage-driver=aufs -g ~/docker-home"`

but I can't fine any image into folders

* ~/docker-home
* /var/lib/docker/aufs

Where the images should be located?

**Comment by cpuguy83** [comment]
There are a couple of things at play here:

1) Does the package that you are using look at `/etc/default/docker` at all (ie, if you are on Ubuntu 15.04 with systemd, then maybe not?)
2) Does upstart/systemd expand `~/`? I'm not sure.
3) `~/` is probably `/root` in this case.

Closing since this isn't really a Docker issue.
For support, please feel free to hit me up on #docker on IRC, there is also the docker-user ML, and forums.docker.com
