### ISSUE TITLE
devicemapper under ubuntu flaky?

### ISSUE THREAD

**Issue by newhook** [docker/docker#14739]
Since upgrading to docker 1.7.1 which made devicemapper the defualt graph driver under ubuntu 14.04.2 LTS I've noticed some strange failures. Here is the latest:

```
+ docker pull registry.customer.io:443/ruby_build
latest: Pulling from registry.customer.io:443/ruby_build
511136ea3c5a: Already exists
5bd56d818842: Already exists
b21b50f44582: Already exists
465cca257df8: Already exists
62b5b5c398f7: Already exists
4a65e9bf4f14: Already exists
4a65e9bf4f14: Already exists
Digest: sha256:954baf25bd0f4b954b244667cc8912a3ab812de11a4284086150a308f7d96f46
Status: Image is up to date for registry.customer.io:443/ruby_build:latest
+ docker run -i --rm -v /home/deploy/deployed/jenkins/jobs/app/workspace:/source registry.customer.io:443/ruby_build
Error response from daemon: Cannot start container 33c51732316f6dde5645f2654abb35c1a1d938f41e1d50498e24e642e5e07572: Error getting container 33c51732316f6dde5645f2654abb35c1a1d938f41e1d50498e24e642e5e07572 from driver devicemapper: Error mounting '/dev/mapper/docker-9:3-97255531-33c51732316f6dde5645f2654abb35c1a1d938f41e1d50498e24e642e5e07572' on '/home/docker/devicemapper/mnt/33c51732316f6dde5645f2654abb35c1a1d938f41e1d50498e24e642e5e07572': no such file or directory
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

I just tried this (6 hours later) and with NO changes everything is back to working? How can I help diagnose the root of this issue?

OS: Ubuntu 14.04.2 LTS (GNU/Linux 3.14.32-xxxx-grs-ipv6-64 x86_64)
Docker version: 1.7.1 (from lxc-docker-1.7.1).

**Comment by thaJeztah** [comment]
Actually, the default graphdriver for Ubuntu 14.04 is AUFS, which can be seen in the install script: [hack/install.sh#L162-L181](https://github.com/docker/docker/blob/v1.7.1/hack/install.sh#L162-L181)

How did you install / upgrade docker? Did you use the script at https://get.docker.com/ubuntu ? Because that will only perform a *minimal* install and will not install AUFS.

It's possible that you're now running devicemapper without Udev-sync support, which is known to cause issues, and strongly discouraged. Also, the *default* settings for devicemapper are not recommended for production use, and require additional manual configuration for improved performance and stability.

I suggest to switch to AUFS as graph driver, which is currently the recommended configuration. You will have to clean your current graph directories.

In case you missed; we very recently launched official apt and yum repositories, more information on that can be found here: http://blog.docker.com/2015/07/new-apt-and-yum-repos/

I'm going to close this issue now, but feel free to comment here after I've closed this

**Comment by newhook** [comment]
I updated with apt-get. The original installation was not from a script, that is unacceptable on a production machine and used the docker defaults.

See https://github.com/docker/docker/issues/14707 for some history on upgrading from 1.7.0 to 1.7.1.

I solved this problem by switching to ufs and changing the deployment scripts to exclicitely set the graph driver to aufs.

**Comment by thaJeztah** [comment]
Thanks @newhook, good to hear you managed to resolve it. Reading the linked issue, I agree that the description in the changelog is cryptic and doesn't cover the possible consequences. It may be "late to the party", but perhaps you have a suggestion on how to improve that and are willing to create a pull request to update the CHANGELOG.md?
