### ISSUE TITLE
Massive metadata for large port ranges

### ISSUE THREAD

**Issue by mattmoor** [docker/docker#14733]
Because of how Docker represents port ranges in the JSON metadata for a layer, a large port range can create a massive metadata file.

```
$ cat Dockerfile 
FROM scratch
EXPOSE 16000-32000/tcp

$ docker build -t foo .
Sending build context to Docker daemon 1.292 MB
Sending build context to Docker daemon 
Step 0 : FROM scratch
 ---> 
Step 1 : EXPOSE 16000-32000/tcp
 ---> Using cache
 ---> b382d4d5c227
Successfully built b382d4d5c227

$ docker images 
REPOSITORY    TAG               IMAGE ID            CREATED             VIRTUAL SIZE
foo           latest            b382d4d5c227        6 minutes ago       0 B

$ docker save -o foo.tar foo
$ tar tvf foo.tar 
drwxr-xr-x 0/0               0 2015-07-18 14:39 b382d4d5c227fb8b0d7dadbd738bdbe064be1fa370f04a68f08835b6f1f0b12d/
-rw-r--r-- 0/0               3 2015-07-18 14:39 b382d4d5c227fb8b0d7dadbd738bdbe064be1fa370f04a68f08835b6f1f0b12d/VERSION
-rw-r--r-- 0/0          641096 2015-07-18 14:39 b382d4d5c227fb8b0d7dadbd738bdbe064be1fa370f04a68f08835b6f1f0b12d/json
-rw-r--r-- 0/0            1024 2015-07-18 14:39 b382d4d5c227fb8b0d7dadbd738bdbe064be1fa370f04a68f08835b6f1f0b12d/layer.tar
-rw-r--r-- 0/0              86 2015-07-18 14:39 repositories

$ tar xf foo.tar b382d4d5c227fb8b0d7dadbd738bdbe064be1fa370f04a68f08835b6f1f0b12d/json -O | python -mjson.tool
{
    "Size": 0,
    "architecture": "amd64",
    "config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": null,
        "Domainname": "",
        "Entrypoint": null,
        "Env": null,
        "ExposedPorts": {
            "16000/tcp": {},
            "16001/tcp": {},
            "16002/tcp": {},
            "16003/tcp": {},
            "16004/tcp": {},
            "16005/tcp": {},
...
```

A bit pathological, but worth highlighting the issue, since the shorthand syntax hides this inefficiency from users.

**Comment by phemmer** [comment]
Could you explain why this is an issue?

**Comment by vdemeester** [comment]
As @phemmer said, what is the issue here ?

**Comment by mattmoor** [comment]
If you bloat a layer's metadata, it (mostly) percolates up to the topmost layer.

The issue with this is largely performance.
 - Considering the v1 registry protocol, the way layer existence is checked is by fetching its JSON.  This is done under the assumption that its a tiny JSON blob, but I've shown a trivial line that bloats it to 650kb.  Not exactly a cheap existence test.

 - Considering the v2 registry manifest format stores ALL layers JSON in a single place, this issue is N times worse on v2 (for N layers).  Unlike v1 (only non-resident layer checks), this also makes polling for image changes very expensive since you have to at least fetch the manifest to know nothing changed.

 - Both v1/v2 must also parse these JSON blobs, which means potential attack vectors if you can push the size of these high enough (and the registry doesn't forcefully cap the allowed size).


As I said, it's a pathological case, but there is clearly a widespread assumption that this file is small/cheap, and this violates that assumption.  So while low priority, this is an issue.

@stevvooe for awareness

**Comment by phemmer** [comment]
What you provided is not the registry protocol. You provided the remote api. The remote api is the communication between the docker client & docker daemon. The registry api is between the docker daemon and the docker registry, and is completely separate.
The registry API does not contain ports at all, as the only port related thing image metadata contains are the result of the `EXPOSE` directive. And this directive does not support a range.

**Comment by stevvooe** [comment]
@mattmoor I agree this is pathological, but what is the use case of such a large port range specified on a Dockerfile? An implementation to do this efficiently and balance specificity with compactness would be a lot more complicated and impose that complexity on consumers of the format.

Should the bug here be in the documentation to identify that this is not free?

**Comment by GreenEA** [comment]
Try standing up freeswitch in Docker, and you discover why it's an issue pretty quickly since it wants some 16K udp ports for media, and Docker can't even start. Granted, this massive range can be reduced, but a FS server certainly could host hundreds of media channels, so I guess these kinds of applications just aren't practical in Docker?

**Comment by cpuguy83** [comment]
I think trying to expose ports like this to the host is probably not right.
I'd ask, why do you need to specify `EXPOSE` for this. Can you use `--net=host` instead? Note that this would also be a fairly significant performance improvement since it would remove the NAT.

Is it purely metadata? There are probably better ways to solve this than using `EXPOSE`.

**Comment by GreenEA** [comment]
Ah – sorry to waste everyone’s time with my own ignorance - I had no idea about –net=host – that is certainly what is called for here.

Thanks!

**Comment by icecrime** [comment]
Tentatively closing as the issue seems to be resolved: please let me know if it needs reopening! Thanks.
