### ISSUE TITLE
Any plan to add cache controll in Dockerfile?

### ISSUE THREAD

**Issue by zz** [docker/docker#14783]
Such as if I want to cache a "RUN" command in 1 week

```
RUN CACHE 604800 pip install numpy
```

**Comment by zz** [comment]
No one need this?

**Comment by rtrauntvein** [comment]
What would be a use case for this?

**Comment by zz** [comment]
@rtrauntvein such as "pip install numpy", some thing need to cost long time running.

**Comment by thaJeztah** [comment]
I don't think this is something we can implement. Docker will already cache any `RUN` instruction, **unless** layers / instructions that `RUN` instructions invalidated the cache. Even if we had this instruction, if the layer *before* the `RUN` instruction is updated, no caching will take place.

The best thing you can do here, is to create a "base" image that contains all the parts of your image that you don't want to change, and build your images on top of that, e.g.

Your base image `Dockerfile.base`
```Dockerfile
FROM ubuntu:14.04
COPY /files/that/dont/change/frequently
RUN build-things-that-dont-change-and-take-a-long-time-to-build
```

`docker build -f Dockerfile.base -t my-base-image`


and the images that you build frequently;
```Dockerfile
FROM my-base-image
COPY project-files
RUN something
```

I'm going to close this issue, because this is not something we can implement. In addition, we currently don't accept changes in the Dockerfile format (see frozen features in the [ROADMAP.md](https://github.com/docker/docker/blob/master/ROADMAP.md))

Feel free to comment here if you think I closed this by mistake.
