### ISSUE TITLE
Allow dots in repository names

### ISSUE THREAD

**Issue by wereHamster** [docker/docker#14789]
I'd like to use a custom Google Cloud Storage bucket to store my container images, and for consistency reasons use DNS names for all my buckets. However docker doesn't allow me to use dots in the repository name, e.g. `docker tag b.gcr.io/test.example.com/my-app` fails with an error.

What are the reasons for not allowing dots and could that restriction be lifted?

docker 1.7

**Comment by thaJeztah** [comment]
I think @stevvooe or @dmcgowan should be able to answer this :+1:

**Comment by onorua** [comment]
I can be wrong, bu [a-z0-9-_.] symbols are allowed in repository names. Your problem is with namespace, which indeed limited to [a-z0-9-_] symbols for some reason, disregard that default namespace value is "docker.io" according to:
https://github.com/docker/docker/blob/master/registry/config.go#L25

**Comment by dmcgowan** [comment]
Currently the restriction is mostly related to legacy reasons and parsing short names (names which do not include a hostname). We consider a fully qualified repository name to include the hostname of the registry along with the image name. When an image is given without the hostname it must be able to be parsed into its fully qualified form to determine the registry to contact. When an image name contains a DNS as the first component the image is considered fully qualified. If DNS names are allowed in any component of the repository name, name expansion would be ambiguous. Now I mention this as a legacy reason because this is only ambiguous as long as short name expansion is assumed and it only applies to "docker.io" since it is the default namespace. The rules could certainly allow for first component to be hostname (dns name + possible port) then DNS components except under the default namespace. Not sure I would be supportive of complicating the rules further just to allow this additional character in parts of the repository name, but I would agree it is unfortunate that the rules are so complicated. We have made attempts to simplify the rules here https://github.com/docker/distribution/pull/303, however this is still not proposing lifting the DNS restriction to the first component.

**Comment by thaJeztah** [comment]
I'm going to close this issue, because I think the question is answered, feel free to comment here after I've closed this issue.

**Comment by stevvooe** [comment]
@dmcgowan With the new `reference` package, which actually defines what is allowed, we could probably allow this. The rules for that package will be that the first component _may_ be a hostname. In the case of the above image names, `gcr.io` would be properly resolved.

The issue of resolving whether or not the first component is a DNS name remains. At some point, we will decouple these concepts and this won't matter.

**Comment by thaJeztah** [comment]
> The issue of resolving whether or not the first component is a DNS name remains. At some point, we will decouple these concepts and this won't matter.

@stevvooe you think we should reopen this, or wait until those questions/decisions are resolved?
