### ISSUE TITLE
Documentation of docker run --user doesn't match actual behaviour

### ISSUE THREAD

**Issue by kblin** [docker/docker#14795]
Description of problem: The `docker run --user` documentation states:
> The default user within a container is root (id = 0), but if the developer created additional users, 
> those are accessible too. 

This is misleading, as it is possible to just pass an arbitrary uid:gid to `-u` and run using that. As stackoverflow is also full of suggestions to use `groupadd && useradd && sudo -u` tricks to achieve the same effect, it seems like many people fall for this.

`docker version`: N/A, but https://docs.docker.com/reference/run/#user as of 2015-07-21 11:22 UTC shows this issue.

`docker info`: N/A

`uname -a`: N/A

Environment details (AWS, VirtualBox, physical, etc.): Docker website

How reproducible: 100%

Steps to Reproduce:
1. Point browser at https://docs.docker.com/reference/run/#user
2. Read misleading documentation
3. Compare with what happens on `docker run debian:jessie /usr/bin/id 1000; docker run -u 1000 debian:jessie /usr/bin/id`

Actual Results:
```
/usr/bin/id: 1000: no such user
uid=1000 gid=0(root) groups=0(root)
```

Expected Results:
```
/usr/bin/id: 1000: no such user
# something blows up because no user with uid 1000 exists
```

Additional info:
The actual behaviour is much more useful than what the documentation describes. The documentation should be updated accordingly.

**Comment by thaJeztah** [comment]
@kblin would you be interested in contributing and creating a PR to improve the docs? The markdown file used to generate that page can be found here; https://github.com/docker/docker/blob/master/docs/reference/run.md

**Comment by kblin** [comment]
On 10/08/15 00:49, Sebastiaan van Stijn wrote:
Hi Sebastiaan,

> @kblin <https://github.com/kblin> would you be interested in
> contributing and creating a PR to improve the docs? The markdown file
> used to generate that page can be found here;
> https://github.com/docker/docker/blob/master/docs/reference/run.md

Sure, I'll have a look.

Cheers,
Kai

-- 
Kai Blin
Samba Developer    http://samba.team

**Comment by cpuguy83** [comment]
Closing since #15510 was merged

**Comment by AnotherOneDeveloper** [comment]
In the current version of documentation I can't find this behavior documented. It might be worth to reopen.

**Comment by thaJeztah** [comment]
@AnotherOneDeveloper looks like it's still there, but it's on the "run reference" page, not the documentation for the run _command_; https://docs.docker.com/engine/reference/run/#user

<img width="799" alt="Screenshot 2024-05-27 at 12 16 18" src="https://github.com/moby/moby/assets/1804568/983fa688-aed4-4863-8508-b0f4134c2fbb">


However, these docs are no longer maintained in this repository, and now live in the CLI repository; https://github.com/docker/cli/blob/v26.1.3/docs/reference/run.md#user

So instead of re-opening this ticket, it may be better to open a ticket in that repository; https://gtihub.com/docker/cli/issues
