### ISSUE TITLE
Cannot use alternate docker build file when building from git repo

### ISSUE THREAD

**Issue by elrac** [docker/docker#14837]
I have a git repo that has two dockerfiles in it. When I attempt to use the alternate dockerfile with -t I get the following error 

> The Dockerfile (Dockerfile-dev) must be within the build context (/var/folders/22/qk_79ksd4bs7_z_c4p1vkq980000gn/T/docker-build-git278991242)

BUG REPORT INFORMATION

Use the commands below to provide key information from your environment:

docker version:

    Client version: 1.7.0
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): 0baf609
    OS/Arch (client): darwin/amd64
    Server version: 1.7.0
    Server API version: 1.19
    Go version (server): go1.4.2
    Git commit (server): 0baf609
    OS/Arch (server): linux/amd64

docker info:

    Containers: 22
    Images: 373
    Storage Driver: aufs
     Root Dir: /mnt/sda1/var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 421
     Dirperm1 Supported: true
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 4.0.5-boot2docker
    Operating System: Boot2Docker 1.7.0 (TCL 6.3); master : 7960f90 - Thu Jun 18 18:31:45 UTC 2015
    CPUs: 2
    Total Memory: 1.956 GiB
    Name: boot2docker
    ID: BK3M:3XOE:MICO:QBSK:2ZEP:5UVW:JNJF:GDK6:B4NW:523M:Y2IG:74BE
    Debug mode (server): true
    File Descriptors: 21
    Goroutines: 34
    System Time: 2015-07-22T00:16:33.802979003Z    
    EventsListeners: 1
    Init SHA1:
    Init Path: /usr/local/bin/docker
    Docker Root Dir: /mnt/sda1/var/lib/docker

uname -a:

    Darwin mini 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64 i386 Macmini3,1 Darwin

Provide additional environment details (AWS, VirtualBox, physical, etc.):

Running using boot2docker on an OSX machine.

List the steps to reproduce the issue:
1.run the following on the command line
    
    docker build -t shaarli -f Dockerfile-dev https://github.com/elrac/docker-shaarli.git

Describe the results you received:

I get the following error

> The Dockerfile (Dockerfile-dev) must be within the build context (/var/folders/22/qk_79ksd4bs7_z_c4p1vkq980000gn/T/docker-build-git278991242)

Describe the results you expected:

I expect it to build using the file Dockerfile-dev in the git repo as the dockerfile.

Provide additional info you think is important:

**Comment by duglin** [comment]
can you try:
```
docker build -t shaarli -f docker-shaarli/Dockerfile-dev https://github.com/elrac/docker-shaarli.git
```
and see if that works?

**Comment by elrac** [comment]
Hi duglin, 
Thank you for the suggestion, unfortunately I tried it and it did not work. My understanding is that the root folder of the repo is the root of the build context when running a build command in that way.

**Comment by duglin** [comment]
ok I think I know what's going on.  The 'git clone' happens into a temp dir on the client but the '-f' flag requires that it either be an absolute path or relative to the current dir.  Since the git clone is to a temp dir there's really no good way for the user to know the name of that dir to use it in the '-f' arg.

I see two choices here:
1 - ban the use of '-f' when doing a git clone
2 - make '-f' relative to the root of the git clone dir **just** for the git case **and** when not an abs path.

@tiborvass any thoughts on this?

**Comment by tiborvass** [comment]
@duglin I don't understand why `**and** when not an abs path`. If it's an abs path it's still relative to the context dir: https://github.com/docker/docker/blob/1b67c38f6f4a709e1d159445b56f0beee8cfad3a/builder/evaluator.go#L219

We could make `-f` relative to the root of the git clone because that's what the context is, I think this would be the right fix.

**Comment by duglin** [comment]
@tiborvass this git clone is done on the CLI side so `/` is the cli's `/` dir, not the top of the build context. Mapping `-f myFile` to $cloneDir/myFile seems reasonable since there's no way for the user to know what $cloneDir will be and we can claim that we did an implicit 'cd' into $cloneDir.  But I'm nervous about mapping `-f /myFile` because when they specify an abs path its almost as if they think they know what they're doing despite the fact that this will most likely result in an error.

**Comment by tiborvass** [comment]
@duglin you're right. I'd usually go with 1), but I guess 2) makes sense here. Either we support git or not.

I know it's off-topic but I'm not sure how git will be handled wrt to trust. If it turns out we can't get or don't want to get feature parity between build from git and from image, then we should probably not bother.

**Comment by duglin** [comment]
@elrac can you try this using 'master' - I actually think it might work based on some recent edits made.

**Comment by duglin** [comment]
I think https://github.com/docker/docker/pull/14546 added support for this.

**Comment by elrac** [comment]
Sorry, I couldn't figure out how to build the docker master branch so that it could be run with Boot2Docker. But this is working as of docker v1.8.0. 

Thank you.
