### ISSUE TITLE
docker inspect date format changed between 1.6 and 1.7

### ISSUE THREAD

**Issue by shapiroj** [docker/docker#14947]
docker 1.6.2
docker inspect -f ".State.StartedAt" 323bf95629f7 
2015-07-22T13:05:00.813480046Z

docker 1.7.1
docker inspect -f ".State.StartedAt" d9e320582e2a
2015-07-22 05:02:38.091530369 +0000 UTC

This breaks all our scripting around docker inspect calls.

**Comment by runcom** [comment]
The problem is in 1.6.2 we were decoding api response into `interface{}`. `time.Time` fields were json encoded as RFC3339 in the response and when decoded into `interface{}` they were just strings so the inspect template treated them as just strings.
From 1.7 we are decoding into `types.ContainerJSON` and when the template gets executed it now gets a `time.Time` and it's formatted that way.
One way to format them as RFC3339 is using the json tag in the format template (i.e. `{{json .State.StartedAt}}`)
