### ISSUE TITLE
[master]: ^C daemon causes panic

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#15081]
here are daemon logs: https://gist.github.com/anonymous/54f6dc3a00a8717fa3b9

havent tested RC but will do tomorrow

**Comment by jfrazelle** [comment]
ping @mrjana its panicing on this line https://github.com/docker/libnetwork/blob/master/sandboxdata.go#L142 lol

**Comment by mrjana** [comment]
@jfrazelle I know that's why I have comment in there that it will panic here if we enter the function with no endpoints attached. So we are not supposed to Leave with 0 endpoints. That is what needs to be fixed. But I am not able to reproduce the problem unfortunately. Is there any reproduction steps(other than running a few containers some with `--net=host` and some with `--net=bridge`)?

**Comment by icecrime** [comment]
@mrjana Sorry we don't have a reproducible use case... However it happened, and will again: any chance we can make the code more robust on that? At least log an error rather than panicking.

**Comment by mrjana** [comment]
@icecrime We can always do the logging instead of panicking and I promise to do that before next RC if I can't root cause the issue before that. Does that work?

But hiding the problem under a log doesn't make the code more robust than panicking because this is some condition that is not supposed to happen in the absence of a bug.

**Comment by icecrime** [comment]
@mrjana I agree, I'd just rather ship a bug that issues a spurious error log, than a bug that takes the daemon down ;-)
