### ISSUE TITLE
fix-broken-link-in-readme.md

### ISSUE THREAD

**Issue by devmeyster** [docker/docker#15112]
The "list of real-world examples" link in the read me is broken. Needs to point to the examples in the Applied Docker category under Use Docker section in the docs

**Comment by charleswhchan** [comment]
There are a whole bunch of examples under "Applied Docker", but the heading itself does not seem to be a linkable anchor. 

Should we link to 'Dockerizing applications: A “Hello world”' (https://docs.docker.com/userguide/dockerizing/)? Is there something more appropriate?

**Comment by devmeyster** [comment]
I suggest linking to Dockerizing MongoDB application since its the first one on the list under Applied Docker section.  (https://docs.docker.com/examples/mongodb/). Once on the page, its pretty clear that there are more example application under that section that follow.  

An alternative could also be to rename or delete the "list of real-world examples link" in the Readme file.

**Comment by thaJeztah** [comment]
Actually, there's already PR merged to fix the missing "index" for https://docs.docker.com/examples/, see the pull request here https://github.com/docker/docker/pull/14696

The changes of that PR aren't live yet (they will go live together with the 1.8 release), so once that is published, the link should work again.

I'm going to close this issue, because this should be resolved soon. Thanks for reporting though!
