### ISSUE TITLE
Pipe command results for ENV

### ISSUE THREAD

**Issue by vyscond** [docker/docker#15224]
it will very helpful (at least for me) if we can expand commands em pipe results for environment variables like 

```
ENV GEM_HOME $(ruby -e 'print Gem.user_dir')
```

For now the ```$(ruby -e 'print Gem.user_dir')``` is not evaluated :(

**Comment by cpuguy83** [comment]
A couple of questions:

1. How come you are changing GEM_HOME?
2. What is the purpose of setting this up like this in the Dockerfile? This can be set in a RUN command and/or in the ENTRYPOINT as part of the startup.

**Comment by thaJeztah** [comment]
I'm going to close this issue, because I think the answer @cpuguy83 provided should give some hints to achieve this. In addition, there's currently a freeze on changes in behavior of the Dockerfile, see [ROADMAP.md](https://github.com/docker/docker/blob/master/ROADMAP.md)

Feel free to comment here if you think I closed this by mistake!

**Comment by vyscond** [comment]
Oh, thanks guys for the tips :) Sorry to open this one before reading the roadmap! :(

**Comment by thaJeztah** [comment]
@vyscond no problem. it's only been added recently :-)
