### ISSUE TITLE
New Docker versions cannot host datastore on NFS share

### ISSUE THREAD

**Issue by bdonnahue** [docker/docker#15239]
In previous versions of Docker I was able to mount an NFS share and symlink the mountpoint to /var/lib/docker so that docker's datastore is hosted via the NFS share. I have backtracked through the versions to the last working version of Docker. This version was 1.3.2

My specs are as follows:
* Operating System: CentOS 7 (vm running on on XenServer 6.5)
* Docker RPM: docker.x86_64  
* RPM Version: 1.3.2-4.el7.centos
* RPM Repo: Extras

I am wondering if anyone can track down what changed between packages that broke this functionality and then fix whatever is broken. I thought this was an SELinux issue but I disabled that and the problem persists.

Here is an example of the error:
```
[root@localhost ~]# setenforce 0
[root@localhost ~]# sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      28
[root@localhost ~]# docker run -ti centos:centos7 /bin/bash
Timestamp: 2015-08-02 16:29:31.725681999 -0400 EDT
Code: System error

Message: operation not supported

Frames:
---
0: setupRootfs
Package: github.com/docker/libcontainer
File: rootfs_linux.go@34
---
1: Init
Package: github.com/docker/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@52
---
2: StartInitialization
Package: github.com/docker/libcontainer.(*LinuxFactory)
File: factory_linux.go@223
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: FATA[0001] Error response from daemon: Cannot start container fba2d602b141aebb19d5bc7db6ade77218b06b2cc999cd659cf2cd24512749ea: [8] System error: operation not supported 
```

**Comment by phihos** [comment]
Hi,

+1 for this issue. I can provide the following information:

Description of problem:

Precondition: Docker daemon is configured to have the graph directory set within a mounted NFS share. Example: `docker daemon -g <NFS mount>/.dockerfiles ...`
When creating a container an *"operation not supported"* error may occurr. An example will be provided below.

`docker version`: 

```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:21:21 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:21:21 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 68
Images: 127
Storage Driver: aufs
 Root Dir: /nfs/.dockerfiles/aufs
 Backing Filesystem: nfs
 Dirs: 263
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-30-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 7.754 GiB
Name: emergency-OptiPlex-790
ID: AUKY:EDGR:AD4L:ZEIB:KUV7:YAIZ:VRHT:PSYX:46KK:JHPC:6Z6I:Y5AX
```
`uname -a`:
```
Linux emergency-OptiPlex-790 3.19.0-30-generic #33-Ubuntu SMP Mon Sep 21 20:58:04 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):

Physical

How reproducible:

Mount a NFS share and configure docker to set the graph directory somewhere within it.
Try to run the *postgres* image.

Steps to Reproduce:

1. Mount a NFS share to /nfs
2. Run docker daemon: `docker daemon -p /nfs/.docker.pid -H unix:///nfs/.docker.sock -g /nfs/.dockerfiles`
3. Export environment variable: export DOCKER_HOST=unix:///nfs/.docker.sock
4. Run `docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres`


Actual Results:

The following error occurrs:
```
Error response from daemon: Cannot start container af37edab33a294fff8df199bdd5e9588d880db76a098f57cbcd8a20ae370b10f: [8] System error: mkdir /nfs/.dockerfiles/aufs/mnt/af37edab33a294fff8df199bdd5e9588d880db76a098f57cbcd8a20ae370b10f/var/lib/postgresql/data: operation not supported
```

Expected Results:

The postgres container should be created and started, since this is the default example on how to run the postgres container.

Additional info:

This error does not occurr when the graph directory is on the local filesystem and not on a network share.
**This error does not occurr, when using devicemapper as storage driver (by `adding -s devicemapper` to the `docker daemon` command).** But *devicemapper* is considerably slower than aufs.

**Comment by cpuguy83** [comment]
AUFS does not support NFS. It is nothing to do with the implementation in Docker, the underlying AUFS filesystem requires local storage.
Also note that you should not be sharing graph dirs between multiple hosts as Docker expects exclusive access to the graph dir.
