### ISSUE TITLE
Categories Docker images for industry trends

### ISSUE THREAD

**Issue by ajeetraina** [docker/docker#15280]
I have an idea. There are millions of Docker images in Docker hub. Say, I come from storage background and want to know what Docker images are available for storage industry. Same case could be if I am working for hardware industry I would be interested to know what system management tools are available. The only option I have is browsing through the tools one after another and that might consume time once Docker repo gets large and large. Why not classify it in terms of industry trends(say, server, cloud, networking, storage, system management, big data, hadoop etc.) so that user can quickly know what containers are present for respective point of interest.

I am not sure if this is the right place but yes, do redirect this thread accordingly.

Thank You.

**Comment by Pensu** [comment]
Sounds like a good idea. Here are my 2 cents: Instead of categorizing based on industry, why not do it based on App ecosystem. I mean, that's the basic stuff we are trying to do, right? Making apps deployment easier. So,  as you said we can categorize them accordingly like cloud apps images, storage apps images, infrastructure apps etc. Let me know what you think about that.

**Comment by ajeetraina** [comment]
Hi Peeyush,

Thanks.You have put it in the right way. I agree with your views.

Ajeet

**Comment by thaJeztah** [comment]
Thanks for creating this proposal @ajeetraina, however, issues and feature requests regarding Docker Hub are not handled in this repository (it's managed by a different team). Usually, you'll have to report those via https://support.docker.com, however, because Docker Hub has just gotten a makeover, you could try opening a feature request in this repo; https://github.com/docker/hub-beta-feedback

I'm going to close this issue here, because there's nothing the maintainer here can do about this, but feel free to comment here after closing
