### ISSUE TITLE
How to associate the docker container and its virtual Ethernet interface in host

### ISSUE THREAD

**Issue by cheyang** [docker/docker#15359]
Each container is associated to a virtual Ethernet interface on the host named like `veth7K7R1J`. I can find it in /sys/class/net/veth7K7R1J/statistics. But I'm wondering how to find this relationship. Is there a way to do this?

**Comment by aidanhs** [comment]
It would be more appropriate to ask this question on the docker mailing list since it's not an issue with Docker :)

In short, have a look at https://github.com/docker-in-practice/docker-comcast/blob/76d9e90cfd0a52600eec47a0452d517e2a60714a/findveth.sh#L12
If you close this issue and post to the docker mailing list I'd be happy to go into more detail.

**Comment by cheyang** [comment]
Sure. thanks. Can you let me know where to post docker mail?

**Comment by cheyang** [comment]
I also asked this question in http://stackoverflow.com/questions/31850150/how-to-associate-the-docker-container-and-its-virtual-ethernet-interface-in-host. Can you reply it. thanks.

**Comment by aidanhs** [comment]
I was more thinking the docker-user mailing list, but have replied there :)
