### ISSUE TITLE
Build Image is giving openSSL Error

### ISSUE THREAD

**Issue by agrawalapoorv** [docker/docker#15434]
ci-builder-3 (out): Build Image error  { [Error: write EPROTO 140735226995456:error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad certificate:../deps/openssl/openssl/ssl/s3_pkt.c:1300:SSL alert number 42
ci-builder-3 (out): ] code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
ci-builder-3 (out): { [Error: write EPROTO 140735226995456:error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad certificate:../deps/openssl/openssl/ssl/s3_pkt.c:1300:SSL alert number 42
ci-builder-3 (out): ] code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
ci-builder-3 (out): 2015-08-09T08:37:01.175Z - warn: [Build Worker] Build failed: 
ci-builder-3 (out): 2015-08-09T08:37:01.175Z - warn: [Build Worker]  Error: write EPROTO 140735226995456:error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad certificate:../deps/openssl/openssl/ssl/s3_pkt.c:1300:SSL alert number 42

**Comment by thaJeztah** [comment]
@agrawalapoorv I'm sorry, but your description does not have enough information for us to know what steps you took to run into this problem.

If this is an error that occurs during *building* an image (what I suspect, based on the title), this is probably because your image doesn't have the required certificates installed inside the image. For some hints, see http://serverfault.com/questions/616051/how-to-debug-certificate-chains-with-openssl

Please keep in mind that the GitHub issue tracker is *not* a general support forum, and only for reporting bugs and feature requests in Docker itself. For other kind of issues, see https://github.com/docker/docker#talking-to-other-docker-users-and-contributors

I'm going to close this issue, but feel free to comment here if you have more information, or think I closed this by mistake
