### ISSUE TITLE
Why there is a "kill" event when I run "docker stop xxx" or "docker restart xxx"?

### ISSUE THREAD

**Issue by mountkin** [docker/docker#15438]
When I run "docker stop xxx" with the binary built from the master or 1.8.0-rcx, I see these event sequences:

```
{"status":"kill","id":"273a26b6855e3875dd8dabdf9232a93e4d5a0548bff8a959e9d5252682fd6f1d","from":"a33df36cfc8e3095ddb25cebc3fcac8f9f4c13f314c79dfe32de97c85f495f28","time":1439184255}
{"status":"die","id":"273a26b6855e3875dd8dabdf9232a93e4d5a0548bff8a959e9d5252682fd6f1d","from":"a33df36cfc8e3095ddb25cebc3fcac8f9f4c13f314c79dfe32de97c85f495f28","time":1439184255}
{"status":"stop","id":"273a26b6855e3875dd8dabdf9232a93e4d5a0548bff8a959e9d5252682fd6f1d","from":"a33df36cfc8e3095ddb25cebc3fcac8f9f4c13f314c79dfe32de97c85f495f28","time":1439184255}
```

Before #13443 there are only 2 events ("die", "stop") emitted when running "docker stop xxx".

@duglin Is this behavior by design or it's a regression?

**Comment by duglin** [comment]
This was intentional.  The idea behind it is that for each action that the daemon takes against a container should be logged so that an admin can see what's being done. For example, the above events make it clear that the container didn't just "die" on its own, but rather because the daemon sent it a signal.

**Comment by mountkin** [comment]
Thanks @duglin 
If it's intentional I'll close this issue.
