### ISSUE TITLE
Best way to share existing file between containers?

### ISSUE THREAD

**Issue by resouer** [docker/docker#15527]
Here's the use case:

container A has a file in its image, say `/tmp/requirements.txt`
container B runs on the same host with A, and it need the txt to start, say:
```
docker run ... --name B ubuntu  pip install /tmp/requirements.txt
```

Now what I am doing is like:

```
docker run ... --name A -v /host_dir:/share ubuntu sh -c 'cp /tmp/requirements.txt /share'
docker run ... --name B -v /host_dir:/tmp ubuntu pip install /tmp/requirements.txt
```

It works, but container A will exit(0) after `cp`.

So, is there any way I can hold the container A after cp?

Or is there any way to share existing file between containers?

volume is done by bind mount, so it will clear the content in the mounted dir, that's why I need to do cp explicitly.

**Comment by cpuguy83** [comment]
The command you are using to start the container is just shell, you can do whatever you need.
Additionally you can start up a 3rd container to handle this instead of overloading your `cp` container with another command.

If your client is on the docker host, you can use `docker cp` to grab the file and place it into the volume.

You could also have both containers inherit the file from a common base image.

Lots of ways to do this, really.

**Comment by resouer** [comment]
@cpuguy83  sorry, my mistake, I can use volumes-from instead and does not have to mount host dir inside container.

**Comment by resouer** [comment]
@cpuguy83  My mistake, if do not provide host dir, -v will copy file from mount point to the host dir, so the requirements.txt will not missing. I can use volumes-from to fix this now! Thanks!
