### ISSUE TITLE
Plugin API: Pass Container ID/labels to plugins.

### ISSUE THREAD

**Issue by hoskeri** [docker/docker#15588]
Since Labels have been added as a mechanism to embed custom metadata for containers, It would be useful for container ID's and/or labels to be passed to the plugins, so that the plugins can derive some context for these operations.

This helps plugin developers avoid having to maintain some state.

Also passing container ID to plugins will help resource management - having to keep track of reference counts, etc.

**Comment by cpuguy83** [comment]
I assume you specifically mean this for volumes.
In #14242 the daemon will now do it's own ref-counting so that shouldn't be much of an issue.
There's been some discussion around creating a uuid per container->volume (so even if multiple containers are using the same volume, create a uuid for the specific mount) that could be passed to the plugin.

We do not want to pass container details to the plugin.
Please see #13420 for these discussions.

**Comment by hoskeri** [comment]
That's okay. I guess any unique id will do, it does not have to point to the container.
