### ISSUE TITLE
Update to use GitHub release downloads

### ISSUE THREAD

**Issue by febbraro** [docker/docker#15609]
Docker Machine and Docker Compose both use Release Assets for all downloadables and checksums. (see: https://github.com/docker/machine/releases). This makes things machine discoverable and capable of automation.

**Comment by thaJeztah** [comment]
I'm not sure we should do this. The currently recommended way is to use the new apt and yum repositories (https://blog.docker.com/2015/07/new-apt-and-yum-repos/), which provide dynamically linked binaries (which solves a number of issues that the statically linked binaries had).

Statically linked binaries can still be found on get.docker.com, as explained here; https://docs.docker.com/installation/binaries/#get-the-docker-binary

I think machine and compose regularly run into the GitHub API rate limit, causing downloads to fail. Docker is downloaded even more, which will that problem even more relevant.

Thanks for suggesting though, I understand your thoughts behind this, just not sure this is something that would work (or only confuse, because multiple download locations would exist then)

/cc @jfrazelle perhaps you have other thoughts on this

**Comment by jfrazelle** [comment]
Yes we host our own to own our availability sorry
