### ISSUE TITLE
[1.8.1] /etc/hosts should not list other containers when using icc=false

### ISSUE THREAD

**Issue by BenHall** [docker/docker#15617]
With 1.8.1 I've noticed that a container has /etc/hosts entries for all the other containers running on the daemon. With icc the containers can't talk to each other so I'm not sure why they would be listed.

**Comment by thaJeztah** [comment]
Yup, I think that would make sense

ping @mavenugo @mrjana I think this is something that libnetwork handles now?

**Comment by mavenugo** [comment]
@BenHall @thaJeztah yes. this is handled in libnetwork and we will look into this.

**Comment by geku** [comment]
Even with `icc=true` all these /etc/hosts entries are not desired in all cases, e.g. when using solutions like [dnsdock](https://github.com/tonistiigi/dnsdock) for service discovery name collisions can occur.

**Comment by aboch** [comment]
Being `icc` a daemon network configuration, it only applies to the default `bridge` network (the one backed by `docker0` bridge)

After https://github.com/docker/docker/pull/17325 auto population of /etc/hosts has been disabled on default bridge network.

Given this issue is related to a no longer existing behavior, I think it should be closed ? @BenHall WDYT ?

**Comment by BenHall** [comment]
As per @aboch comments... :)

**Comment by thaJeztah** [comment]
Thanks @BenHall!
