### ISSUE TITLE
Support copy-on-write VOLUME mount mode

### ISSUE THREAD

**Issue by maxmanuylov** [docker/docker#15655]
I have some folder on host that I want to mount to container. I do not want the container to modify that folder on host, but I nevertheless want it to be writable from inside the container. So I want to mount that folder as copy-on-write VOLUME to read the files from host, but make changes inside the container and do not keep them after container is deleted.

Possible workaround is to use COPY Dockerfile instruction to build a new image with that folder inside but it is not an option when the folder is rather big. Another workaround is described here: https://stackoverflow.com/questions/29550736/can-i-mount-docker-host-directory-as-copy-on-write-overlay/30101039#30101039

But I want it to be simple like this:

```docker run -v /path/on/host:/path/in/container:cow myimage```

**Comment by cpuguy83** [comment]
Hello, this is not something we can support with the `docker run` syntax.
You can use a volume plugin to achieve what you want here.
That said this is pretty much defeating the purpose of volumes.

It sounds like you want to inject files into the container FS and not keep them around after the container is gone. This is really what COPY/ADD do, in addition there is also the new API's in Docker 1.8 which lets you inject new files into a running container (docker cp /path/to/files <container name>:/path/in/container)

**Comment by findepi** [comment]
@cpuguy83 from container isolation perspective, `COPY/ADD` and `docker cp` both do the job. Both, however, defeat the purpose of copy-on-write, as all data needs to be copied (once).
As a developer, I want to spin up a container and build and run a Java app inside it (be it for debugging purposes). I wish I could mount my `~/.m2/repository` inside container, but I want this in a copy-on-write manner, so that whatever process does with this inside container, doesn't litter my own `~/.m2/repository` (I'm considering file owner uid here).

I ended-up mounting `/tmp/just-for-docker-m2-repository` inside container, but it is definitely only a workaround.

**Comment by ssbarnea** [comment]
I was looking for this feature for the same reason: caching or packages (pip, rpm,....). There is a need to mount a CoW copy of a cache for short time to speedup package install and to unmount it after (saving the changes or dropping them based on your decision).  Examples: `~/.cache/pip` or `/var/cache/[yum|dnf]`.

Having cache volumes shared across all containers would create a huge speed boots for operations like this.

For most package manager is not safe to mount the the same volume (cache) to multiple wriitng processes as they could easly endup with partial writes.

**Comment by cpuguy83** [comment]
@ssbarnea Sure, you could do this with overlayfs.
To make it clear, I do not see us adding CoW volumes support into moby. This can and should be implemented outside in a volume driver.

Now, in terms of build, buildkit does support mounting caches into `RUN`, which can be shared or exclusive. https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/experimental.md#run---mounttypecache
