### ISSUE TITLE
This is a test, please ignore, I'm sorry for the noise

### ISSUE THREAD

**Issue by calavera** [docker/docker#15881]
So, so sorry :pensive:

**Comment by calavera** [comment]
+1

**Comment by thaJeztah** [comment]
+1

**Comment by tianon** [comment]
+2

**Comment by duglin** [comment]
-1

-Doug

**Comment by thaJeztah** [comment]
=

**Comment by calavera** [comment]
:stuck_out_tongue_winking_eye: we don't process anything when issues and prs are closed, but apparently we should

**Comment by thaJeztah** [comment]
Yes, I think it should process closed ones as well, we sometimes get "why is this closed, because I can still reproduce this on Docker 0.05" and lots of +1's

Should there be a counter? Even though the "+1s" are annoying (and many times people don't even know what they're +1-ing), they *can* be an indicator that it's a real problem or an issue should be reopened; perhaps we should add a "popular" label to issues with loads of +1's
