### ISSUE TITLE
Document volume options on for `docker run`

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#15896]
The options for the `-v` flag on `docker run` seem to be lacking.
Specifically they only mention `rw` and `ro` as valid flags mean while there are also `z` and `Z`, which can be used independently or concatenated as such: `rw,Z`

**Comment by HackToday** [comment]
hi @cpuguy83  I'd like to take this issue if not owned by anyone.

For document here, could you tell me which doc? 

is this guide ?
http://docs.docker.com/engine/userguide/

**Comment by cpuguy83** [comment]
ping @thaJeztah

**Comment by thaJeztah** [comment]
@HackToday thanks! This issue is created for the `docker run` command, but it may be needed on some other places.

- First of all, the format of the value to pass to `-v` isn't documented in the list at the top in [docs/reference/commandline/run.md](https://github.com/docker/docker/blob/master/docs/reference/commandline/run.md) and [docs/reference/commandline/create.md](https://github.com/docker/docker/blob/master/docs/reference/commandline/create.md). You could take https://github.com/docker/docker/blob/master/docs/reference/run.md#volume-shared-filesystems as an example.
- The options *are* described in the [`--volumes-from` section](https://github.com/docker/docker/blob/master/docs/reference/commandline/run.md#mount-volumes-from-container---volumes-from), but also in https://github.com/docker/docker/blob/master/docs/userguide/dockervolumes.md#mount-a-host-directory-as-a-data-volume; to prevent repeating, perhaps we should link to that page

**Comment by HackToday** [comment]
hi @thaJeztah  Thanks for your reply.
1. For -v, I would check to add that to run.md and create.md
2. for volumes-from. it seems you said you prefer mount-a-host-directory-as-a-data-volume has a link to --volumes-from section ,right ?

**Comment by thaJeztah** [comment]
@HackToday for 2., I'm not 100% sure yet, we need a description, and right now that description is "scattered" over the documentation. So, I think we could have a section explaining the options and link to that from other parts (but I'm not sure what the best place would be for that section :blush:)

**Comment by HackToday** [comment]
Ok. @thaJeztah I will need to check that. Right now, it seems volume-from section is the one fit your needs, if I found other better place, I will add that.

**Comment by HackToday** [comment]
#dibs
