### ISSUE TITLE
How to keep files in the volume dir of container when `-v /foo:/bar`?

### ISSUE THREAD

**Issue by resouer** [docker/docker#15936]
Hi guys,

Here's the problem:

When I do `docker run -v /foo:/bar`, the original files in `/bar` will be hided, that's what bind mount did of course.

But is there anyway I can  keep those files and access them from `/foo`?

**Comment by thaJeztah** [comment]
No, there's currently no way to do this automatically. There's been a PR to do this; https://github.com/docker/docker/pull/9092, but it was closed in light of the new Volumes API (https://github.com/docker/docker/pull/14242), that will be in Docker 1.9 and which allows you to manage volumes separately from the containers that make use of them.

Thinking about this, I'm not 100% sure if the new "named" volumes;

- are automatically propagated with data from the container (in case the volume is empty)
- if automatic propagation is driver dependent (i.e., does the "local" driver automatically propagate, but other drivers may not)
- what happens if multiple containers use the same volume (will that be a race?)

In any case, I don't think the docs are currently clear on this, so that may need some note.

ping @cpuguy83

**Comment by phemmer** [comment]
See #13984

**Comment by thaJeztah** [comment]
@phemmer ah, yes we had that one as well; (albeit not directly related to bind mounts) l'm still interested in the new named volumes here (haven't had the opportunity to test the behavior today)

**Comment by resouer** [comment]
@phemmer @thaJeztah so, any work around for now?

**Comment by cpuguy83** [comment]
@resouer The way to do this would be to not specify a host path.

Seems like we can close this as this?

**Comment by kkeane** [comment]
I would argue against closing this, because this is not a valid workaround.

If you don't specify a host path, then the volume ends up in a place I may not always want, namely hiding somewhere deep under /var/lib/docker; the only way to find it is with docker inspect.

Here is my use case, just to illustrate why this can be useful (and, yes, of course I have an easy workaround, but it's a kludge): one of my dockerized applications writes directly to /var/log/myapp, not via syslog. I want to have direct easy access to the log files on the host, not deep under /var/lib/docker, and I also don't want to have to log on to the container. Instead, I would want to use /var/log/containers/<containername>.

Unfortunately, my application breaks when its subdirectory under /var/log is missing.

Of course, there are other use cases where the current behavior is desirable, so this behavior should be controllable.

**Comment by thaJeztah** [comment]
@kkeane for anonymous volumes; please see the new volume API/UX that will be in Docker 1.9: https://github.com/docker/docker/pull/14242

**Comment by cpuguy83** [comment]
Yes +1 to @thaJeztah. This issue of finding your volumes is solved at this point and will be available in docker 1.9.

**Comment by kkeane** [comment]
Doesn't help me; I'm stuck on Docker 1.7 for unrelated reasons. But I agree; I can't expect new features to be added to old versions.

**Comment by resouer** [comment]
@cpuguy83  @kkeane If I understand right, user can only get volumes info after container already created? 

If so, that does not help me ... 

What I propose here is a `CopyData` flag to reserve my data before bind mount `any kind of volume`

**Comment by leodutra** [comment]
Docker could be so more practical, but docs are bad and directives have no options.
Geez... -v should just keep the damn files on it's place. Why would I bind a volume and desire its content to be hidden?

**Comment by thaJeztah** [comment]
@leodutra could you describe your case? Are you bind-mounting a host-directory into your container? (In that case, the *host* directory's contents becomes visible in the container). If you're using a regular volume, the container's files are copied to the volume of the volume is empty.

I.e. `docker run -v /host/dir:/container/dir` uses files from `/host/dir`. On the other hand `docker run -v mydatevol:/container/dir` copies "/container/dir" to the volume, the first time it's run.

**Comment by leodutra** [comment]
In my case:

   1. created `VOLUME` `/my-volume`;
   2. downloaded and built a Javar `.jar` into it;
   3. defined an entrypoint that executes that `.jar` (`java -jar
   /my-volume/tchutchu.jar`);
   4. ran the image defining a host mount (`-v`) for a host directory.


My `WORKDIR` was set to the same `VOLUME`.

Result:
Entrypoint could never find the `.jar` since it seems the mount binding
override the content of `VOLUME` `/my-volume`. So `.jar` is accessible only
when NOT using the `-v`.

Expected:
Would be great if internal volume stuff moved/was copied to the bound
mounted volume.

Workaround:
Let the `.jar` in `/opt/tchutchu.jar`, set `WORKDIR` to the volume and set
`ENTRYPOINT` to `java -jar /opt/tchutchu.jar`.

**Comment by leodutra** [comment]
In my case:

   1. created `VOLUME` `/my-volume`;
   2. downloaded and built a Javar `.jar` into it;
   3. defined an entrypoint that executes that `.jar` (`java -jar
   /my-volume/tchutchu.jar`);
   4. ran the image defining a host mount (`-v`) for a host directory.


My `WORKDIR` was set to the same `VOLUME`.

Result:
Entrypoint could never find the `.jar` since it seems the mount binding
override the content of `VOLUME` `/my-volume`. So `.jar` is accessible only
when NOT using the `-v`.

Expected:
Would be great if internal volume stuff moved/was copied to the bound
mounted volume.

Workaround:
Let the `.jar` in `/opt/tchutchu.jar`, set `WORKDIR` to the volume and set
`ENTRYPOINT` to `java -jar /opt/tchutchu.jar`.

**Comment by NiklasRosenstein** [comment]
Sorry to revive this old issue -- but I can't follow the rationale behind the different behaviours between named volumes and host path volumes. IMO this is just inconsistent and confusing.

* How exactly does mounting a named volume imply that I **do** want to initialize the volume with the data from the image?

* And how does mounting a host path imply that I **dont** want that initialization to happen?

I might want just the opposite in either case. This behaviour should be controlled with a flag, and ideally there should be one common behaviour in both cases. I think the default of initializing the volume if it is empty makes a lot of sense -- unless that behaviour is explicitly disabled for the volume.

**Comment by ewoutvonk** [comment]
"How exactly does mounting a named volume imply that I do want to initialize the volume with the data from the image?" - I guess it's a safe bet. If the Dockerfile left files there to begin with, they are probably of use. If your volume is empty, you would lose them. If you don't want this, you either need to mount the volume elsewhere or make sure the directory is empty when running docker build. Hence they are copied on first initialization.

"And how does mounting a host path imply that I dont want that initialization to happen?" - Because if you mount a host directory that's not empty, and the container directory isn't either, what do you do then? Sync? Remove files and directories in the host directory? Remove files and directories in the container directory? What if you accidentally bind mounted the root folder to your docker container?

The rationale makes sense to me, but I still have to test the first-run-volume-init thingy, because I didn't know it existed and would very much like it to work.

Additional use case, although not needed anymore: you ship a docker image with default configuration, and you can override specific configuration files or add extra files, without needing to first somehow get those files before launching the container, putting them in the volume and then launching the container with the volume.

**Comment by yrral86** [comment]
If you bind mount a host folder and that folder does not exist, it is created.  In this case, would it not make sense to initialize it from the image just like with a named volume?  Instead, docker just creates an empty folder.  This makes initializing my persistent EBS backed volumes awefully tricky.  I will probably have to instead use named volumes and figure out how to tell docker what folder to use to store the data.

**Comment by cpuguy83** [comment]
@yrral86 

```
docker volume create --opt type=none --opt device=<host path> --opt o=bind
```

**Comment by leodutra** [comment]
I'm coming back to this, after some years to say I discovered most FS, as we can find in Linux and Mac OS, actually have very similar behavior: whenever some volume binding is reassigned, the old path contents are kept in the same physical location and gets "hidden" by any explorer or general commands like `ls`.

In this sense, I assume today it is better for me to learn and carry in my memory this rule than expect every FS to change this behavior.

**Comment by leodutra** [comment]
I'm coming back to this, after some years to say I discovered most FS, as we can find in Linux and Mac OS, actually have very similar behavior: whenever some volume binding is reassigned, the old path contents are kept in the same physical location and gets "hidden" by any explorer or general commands like ls.

In this sense, I assume, today, it is better for me to learn and carry this rule, in my memory, than expect every FS to change this behavior.

**Comment by twje** [comment]
I ran into a similar issue and resolved it by pre-ceding the host volumes before running docker compose. 

For example, Drupal requires a sites and core folder, but I would like that mapped to my host machine for development:

**pre-seed local sites directory**
`
docker run --rm drupal tar -cC ./sites . > sites.tar
tar -xC ./sites -f sites.tar
rm sites.tar
`

**pre-seed local core directory**
`
docker run --rm drupal tar -cC ./core . > core.tar
tar -xC ./core -f core.tar
rm core.tar
`

**provision local development stack**
`docker-compose up`

Certainly not the most efficient solution but is a good work around.

**Comment by ant0x64** [comment]
```bash
docker volume create --opt type=none --opt device=${HOME}/.npm/20.11.0/ --opt o=bind --name node-js_20.11.0
docker run --rm -ti --network=host  -p 3000:3000 -v ${PWD}:/usr/src/app -v node-js_20.11.0:/usr/local/lib/node_modules/npm  node:20.11.0 /bin/bash
```
