### ISSUE TITLE
Docker volumes does not track unused volumes created through plugins

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#15997]
This is a placeholder issue for discussing improvements to the way docker volumes keeps track of (named) volumes created through plugins.

This issue came up in a discussion on IRC (logs can be found [here on botbot.me](https://botbot.me/freenode/docker-dev/2015-09-01/?msg=48716043&page=4))

I'm writing down some thoughts; there may be technical inaccuracies (please comment and I'll correct them :smile:) 

### Description

Docker volume can keep track of volumes in a number of ways;

- Volumes created with the 'local' driver are stored inside `/var/lib/docker`, and can be resolved through the filesystem
- Volumes created through the volumes API (both 'local' and 'plugin') are kept in-memory
- Volumes that are currently used by containers can be resolved through the information stored in the container's JSON

Apart from the above, Docker does not persist any information about volumes. This means that, after a daemon restart, information about *unused* volumes, created through plugins is no longer available. The volumes are still "there", but Docker does not have any notion of their existence.

### Problem

Not keeping track of this information can lead to a number of problems. Some examples;

```bash
docker volume create --name foobar
docker volume create --driver somedriver --name foobar2
docker volume create --driver somedriver --name foobar3

docker run -d -v foobar3:/foo nginx

docker volume

DRIVER              VOLUME NAME
local               foobar
somedriver          foobar2
somedriver          foobar3

restart docker


docker volume

DRIVER              VOLUME NAME
local               foobar
somedriver          foobar3

```

After restarting the daemon, volume `foobar2` is no longer visible. (note: foobar3 actually becomes visible as a "local" volume, which is caused by https://github.com/docker/docker/issues/15994)

Trying to use `foobar2` for a container (but omitting the `--volume-driver`),
will now create a *new* volume, using the default ('local') driver;

```bash
docker run -d -v foobar2:/foo nginx

DRIVER              VOLUME NAME
local               foobar
local               foobar2
somedriver          foobar3
```

#### 1. Persist information about *all* volumes in `/var/lib/docker/volume/<volume-name>`.

For volumes created through plug-ins, this could simply mean to keep a JSON file, containing the minimum required information, probably only "driver" (possibly "Source") is needed at this moment;

```JSON
{
    "Driver": "somedriver",
    "Source": "/some/path/foobar3/_data",
}
```

*advantages:*

- Simple solution
- Consistent with the 'local' driver
- Guarantees "globally" unique volume names (`/var/lib/docker/volume/<volume-name>`)

*disadvantages:*

- Who is "responsible" for keeping track of volumes; the *driver* or *docker*?
- Plugin's may have other ways to create / destroy volumes; information can get out of sync.

#### 2. Extend the volume-plugins interface

Extend the volume-plugins interface to have plugins *return* a list of volumes they have present.

*advantages:*

- The plugin is responsibility for providing and maintaining the volume information
- Information doesn't get out of sync (if a plugin creates / destroys a volume outside of Docker)

*disadvantages:*

- More complicated / moving parts
- No guarantee that volume-names are "globally" unique

#### 3. Combination of the above

Store information about volumes in `/var/lib/docker`, and synchronize this information
by requesting the actual list of volumes from the plugins.

**Comment by erikh** [comment]
/cc @jainvipin @shaleman

#2 works best for a multi-host scenario I think; the driver can always delegate to a master or centralized store to retrieve the appropriate information.

**Comment by srust** [comment]
Hi all,

Thanks @thaJeztah for opening this issue.

### Summary

* Volume driver responsibility is ambiguous in docker command line syntax
* Docker does not track out of band volume changes
* Docker loses volume state across restart

### Description

The external volume support in its current form has introduced a cache coherency problem. By requiring unique names across all local and external volumes, it creates a situation where each volume plugin needs to be queried to check existence for a volume. This solution is error prone when you consider out of band volume creation/deletion, multiple users creating volumes simultaneously, and multi-host environments.

The real problem is that non-existence of volume metadata implies that it is not managed by a driver. If the driver were explicitly described in the volume name, an existence check could be delegated to the plugin. With the docker daemon solely making the existence decision, the burden is now on docker to ensure that its view of the world is up to date.

IMHO, the uniqueness requirement on volume names establishes an unnecessary cache coherency requirement on the docker daemon. My recommendation is to remove this requirement by being more specific about who is responsible for managing a volume. It does not mean doing away with the `volume` set of commands, volume options, or anything else. It means being specific about who is responsible for volume management. The scope of uniqueness for a volume should be a driver, not global.

I know this has been discussed in great detail previously. However, this could all be solved if volume references included driver selectors; the absence of a driver selector can imply docker managed storage.

### Example 1:

````
docker run -v vol@blockbridge:/data1 -v vol:/data2
````

The explicit driver specification pushes the existence burden to the plugin. An unspecified driver expects or creates the volume locally.

### Example 2 (volume options):

````
	docker volume create --name vol --driver blockbridge --opts CAPACITY=32GiB

	docker run -v vol@blockbridge:/data1
````

A volume is pre-created ahead of time with `volume create` with options. At runtime, the driver is specified and the existing volume is used. Any changes on the backend storage from other drivers, docker daemon restarts, etc. do not impact correct operation of the volume for the expected driver.

### Volume Enumeration

Additionally, the volume plugin API should be extended to support a `volume ls` functionality. All volumes on external plugins should not be stored or cached in docker at all (even in memory). When a `volume ls` operation is issued to docker, docker should in turn issue a `volume ls` to each registered plugin and query all available volumes on the driver for that host. This would remove docker entirely from keeping local state that may be invalid.

### Example 3 (volume ls):

Each driver is queried in turn:

````
	docker volume ls

	DRIVER		VOLUME NAME
<local volumes queried>
	local			vol
<driver plugin queried in turn>
	blockbridge		vol
````

### Conclusion

There is no dancing around it. Either we need to build a cache coherency model for the docker daemon or delegate it to the volume drivers. The less caching there is, the less chance there is for stale state and the less recovery logic needed.

Thanks.

**Comment by cpuguy83** [comment]
Indeed, the decision around unique names was pretty much to simplify the API and CLI.
Releasing 1.9 before making any change to delegate to the driver would be a breaking API change... but this was the original API.

**Comment by srust** [comment]
@cpuguy83, thanks for your comment!

To be clear, what I’m proposing is:

* Require volume driver name as part of volume specification (eg: `-v vol@driver:/path`). No driver means local docker managed volume.
* Remove all tracking of external volumes in docker (not stored for volume ls purposes in memory or elsewhere) 
* Pass all volume commands to the plugin (`volume create, remove, ls` proxied to the plugin. `volume ls` is proxied to each registered plugin)

This would:

* Remove ambiguity around which driver a volume belongs to
* Allow out of band volume creation on backend storage to be immediately usable by docker without having to separately “create” the volume in docker in order to track it. Register a plugin, and the volumes are available. And show up in ‘volume ls’. (as an aside, the `volume ls` proxied to the plugin could *also* return the options that the volume was created with, at ls time. This allows docker to display that information without having to store it).
* Have no stale state in docker to revalidate on restart, on backend storage changes, across plugins, or across hosts.

IMHO, this proposal is simpler and less error prone than designing and implementing a cache coherency model for docker. It would also move docker away from keeping state about external volumes, which I've seen in other comments as "desired".

Based on your comment, I’m not sure what you think. Can you please clarify?

Thanks.

**Comment by cpuguy83** [comment]
The way the API was originally designed is as you detailed out here, however the API and CLI semantics were complicated (or at least the CLI was).

@calavera should chime in here as it was his decision really to want to move to what we have in now.

**Comment by erikh** [comment]
It would also be nice to have a signal that says "docker is shutting down, but do not remove these volumes".

**Comment by lukemarsden** [comment]
I am +1 for @srust's proposed solution to this problem:
* making the driver name part of the volume identifier
* pushing responsibility for listing (and all other actions) on volumes to the volume plugins.

When working with @calavera, @crosbymichael and @shykes to design the initial external volumes plugins, I suggested a `docker run -v driver/vol:/path` syntax because, among other things, it means that more than one volume driver can be used for a single container (which isn't possible when `VolumeDriver` is part of the *container* config like it is now). Here @srust is proposing `vol@driver:/path` which effectively equivalent: it makes `driver` part of the volume name, and so allows resolution of which driver to talk to whenever the volume is mentioned.

Looking back over my notes, we ended up with `--volume-driver` in the `docker run` CLI for consistency with the CLI syntax that was in-flight for network plugins at the time.

**Comment by thaJeztah** [comment]
Not looking at technical implications, I'm -1 on including the driver name in the volume name. Including the driver name in the volume name (IMO) takes away the abstraction that named volumes can provide. In many cases, I don't need to be aware of the driver that has been used to create the volume; as long as I know the *name* of the volume.

Not including the driver-name makes picking right driver and options for a volume part of the *create* step of a volume, not the moment the volume is *used*, i.e.;

    docker volume create mysite --driver=bestforsites --opt foo --opt bar
    docker volume create dbdata --driver=bestfordatabases

    docker run -d mysite:/var/www nginx
    docker run -d dbdata:/var/lib/mysql mysql

I think that (at some point) it should be possible to set a *default* volume driver for a host/daemon. This would allow me to, for example, use `flocker` as the default driver for volumes; as a user, I don't  have to be aware of this, as long as the default driver is fully compatible with the 'local' driver. Making the driver-name part of the volume name would complicate that.


> This isn't possible when VolumeDriver is part of the container config like it is now.

While I agree that the `--volume-driver` flag is awkward (I proposed to deprecated the `--volume-driver`; https://github.com/docker/docker/issues/16069), I don't think that including the driver-name will help much; drivers may need additional options and I don't see a clean way to add those.

We currently *do* support using multiple drivers for a single container by inlining the `volume create`;

```
docker run -d \
    -v /some/path:/bindmounted \
    -v /justavolume \
    -v $(docker volume create --driver=fancy --opt foo --opt bar):/data \
    -v $(docker volume create --driver=foobar):/somewhere \
    myimage
```

This will use a bind-mounted volume at `/bindmounted`, a 'local' volume at `/justavolume`, a `fancy` volume at `/data` and  a `foobar` volume at `/somewhere`.

**Comment by erikh** [comment]
On 7 Sep 2015, at 8:34, Sebastiaan van Stijn wrote:

> We currently *do* support using multiple drivers for a single 
> container by inlining the `volume create`;
>
> ```
> docker run -d \
>  -v /some/path:/bindmounted \
>  -v /justavolume \
>  -v $(docker volume create --driver=fancy --opt foo --opt bar):/data \
>  -v $(docker volume create --driver=foobar):/somewhere \
>  myimage
> ```
>
> This will use a bind-mounted volume at `/bindmounted`, a 'local' 
> volume at `/justavolume`, a `fancy` volume at `/data` and  a `foobar` 
> volume at `/somewhere`.

And when the volume name needs to be re-used?

**Comment by thaJeztah** [comment]
> And when the volume name needs to be re-used?

I'm not sure what you're asking; you mean, the same name across multiple drivers? Or the volume reused for other containers?

**Comment by erikh** [comment]
I mean, when you need to use the result that `docker volume create 
—driver=foo` yields again.

**Comment by thaJeztah** [comment]
In that case, I think;

If you don't care about the name/ID of the volume;

```bash
VOL_ID=$(docker volume create --driver=foobar)
docker run -v $VOL_ID:/somewhere myimage
```

Or, if you *do*, assign a name
```bash
docker run -d \
    -v $(docker volume create --driver=foobar --name=myvol):/somewhere \
    myimage

docker run -d \
    -v myvol:/somewhere \
    myimage
```

**Comment by cpuguy83** [comment]
I agree with @thaJeztah

**Comment by srust** [comment]
Thanks for the discussion and dialogue, guys!

@lukemarsden, thanks for the history and information. Appreciate the feedback.

@thaJeztah, I definitely agree. The current CLI syntax and UX is nice. Unfortunately, the technical implications are important. Without some change (as proposed, or something else), docker is in the business of storage management. And will need to become more of a storage manager of the external plugins in order to solve the technical problems.

**Comment by calavera** [comment]
I finally had time to read all this thread, thanks broken Jenkins! :tada:

I think @srust concerns are fare, nothing that we cannot iterate on and see how we like it. I also have some comments about the points expressed here:

> Require volume driver name as part of volume specification (eg: -v vol@driver:/path). No driver means local docker managed volume.

Did you try to create a volume with `--name vol@driver`? As far as I know we don't have any restrictions in the name :wink:

```
root@d:~# ./docker volume create --driver vault --name foo@vault
foo@vault
root@d:~# ./docker volume ls
DRIVER              VOLUME NAME
vault               foo@vault
root@d:~# ./docker run --rm -it --volume foo@vault:/data alpine ash
/ #
```

> Remove all tracking of external volumes in docker (not stored for volume ls purposes in memory or elsewhere)

After using volumes management for a few days, I see how this can be a good idea, the less the daemon has to know the better.

> Pass all volume commands to the plugin (volume create, remove, ls proxied to the plugin. volume ls is proxied to each registered plugin)

AFAIK, the only command that's not proxied to the plugin is `volume ls`. I like the idea of delegating this to the plugins too.

Obviously, changes in the api after 1.9 will require versioning. We can still use content type and accept for that, there is no need to introduce more drastic changes.

**Comment by erikh** [comment]
FWIW, I got around storage options not being preserved (which I needed 
to propagate the pool name in ceph), by splitting the path like so:

`-v pool/image:/mnt`

So the volume has a bit of encoded information in it.

-Erik

**Comment by coolljt0725** [comment]
+1 with @srust 's proposal. The `driver` should be a part of volume identifier, I think the user should aware what driver the volume used, since different driver have different feature and store the data in different place. In this way user can use multiple volume driver in a single `docker run/create` cli and 
different volume driver can have the same volume name.
I have had some implements of this, if you are interested see https://github.com/coolljt0725/docker/commit/18e0f59b261a41e2e4df4ee885a9c96560b5800a
use the sytax `name@driver:/dest` as the volume identifier as @srust 's proposal.
Here is the example.
<pre><code>[lei@fedora ~]$ docker run -v test@convoy:/data -v test:/test busybox
[lei@fedora ~]$ docker volume ls
DRIVER              VOLUME NAME
convoy              test
local               test
</code></pre>
If no driver specified in the volume identifier, use default driver which is specified by `--volume-driver`, if no, use default `local`
the `docker volume` cli should use `name@driver`, if no driver specified, use default `local`
<pre><code>[lei@fedora ~]$ docker volume inspect test
[
    {
        "Name": "test",
        "Driver": "local",
        "Mountpoint": "/var/lib/docker/volumes/test/_data"
    }
]
[lei@fedora ~]$ docker volume inspect test@convoy
[
    {
        "Name": "test",
        "Driver": "convoy",
        "Mountpoint": "/var/lib/convoy/devicemapper/mounts/0f1c1fc2-21e3-4f83-99b1-9c23b9be649b"
    }
]
</code></pre>

**Comment by cpuguy83** [comment]
I'm working on something to address these issues.
The biggest concern here with these changes is awkwardness in the UI.

I also think that having the driver name (or anything related to the driver at all) in `docker run` is not desirable.

**Comment by thaJeztah** [comment]
Thanks @cpuguy83 basically, my biggest concern is shipping a UX with 1.9 and having to change after that, breaking backward compatibility.

**Comment by calavera** [comment]
> I also think that having the driver name (or anything related to the driver at all) in docker run is not desirable.

agreed

> The biggest concern here with these changes is awkwardness in the UI.

I'm pretty sure we can make these changes without changing anything in the UI.

**Comment by HaiNguyen007** [comment]
My same problem, in Rancher UI when I click "View config" of a stack with rancher-nfs volumes => all drivers have "null" as value:
volumes:
  odoo-web-data:
    external: true
    driver: 'null'
  odoo-db-data:
    external: true
    driver: 'null'
