### ISSUE TITLE
[proposal] docker ps format in env

### ISSUE THREAD

**Issue by vieux** [docker/docker#16037]
Hello,

I would like to propose yet another env variable in the client to set the ps format.

Currently you have 2 choices: `--format` or a "complicated" config file.

It would be nice to have it in the env, so we could have something like `eval $(swarm env)` and the docker ps output is cluster friendly.

What do you think ? @calavera @icecrime @jfrazelle @aluzzardi @abronan 
 
I'm sorry if it was already asked, I couldn't find anything.

**Comment by duglin** [comment]
I would prefer if instead of having a ton of env vars we made modifying the "complicated" env file easier.
For example: `docker config set psformat ...`.

**Comment by thaJeztah** [comment]
not against env vars, but +1 to @diglin's suggestion to make the config easier to use

**Comment by thaJeztah** [comment]
crap auto-correct :poo:

**Comment by duglin** [comment]
FYI - I did have something ready to go (a while ago: https://github.com/docker/docker/compare/master...duglin:Config ) but it wasn't clear how much interest there was in this. I'd be more than happy to resurrect it since I'm not thrilled with the idea of 3rd party tools modifying the config file themselves, I'd prefer to offer up an API/cmd-line-tool to help them.

**Comment by thaJeztah** [comment]
Agreed on keeping control over the config; a CLI interface sgtm.

**Comment by LK4D4** [comment]
I think the proposal didn't hit necessary level of interest. Closing it for now.
