### ISSUE TITLE
VolumeDriver parameter is not documented in the API

### ISSUE THREAD

**Issue by bboreham** [docker/docker#16048]
`VolumeDriver` is introduced [here](https://github.com/docker/docker/commit/81fa9feb0cdc0773eff99d7393c16271e84aac08#diff-2660508eef7a8eeadb6d27b8bbf6d718R125), but not documented, as far as I can see.

I believe it should be in docs/sources/reference/api/docker_remote_api_v1.19.md, at least.

Noting that #15342 seeks to move it somewhere else.

**Comment by calavera** [comment]
I added it to v.1.21, you can see it in https://github.com/calavera/docker/blob/6549d6517bf9a7c79d21a86cbf36af10fcdbfbe0/docs/reference/api/docker_remote_api_v1.21.md

It was added for 1.19 only for experimental, I don't think it needs to be documented there.
It is fully supported in 1.20, but as you mention, it's in the Config struct. I rather not port the documentation back because, as #15342 describes, it makes the container configuration not portable.

Thanks for reporting it, I'm going to close the issue as fixed, but feel free to reopen it if you have further comments.
