### ISSUE TITLE
Volume losing host data after vagrant reload

### ISSUE THREAD

**Issue by trompx** [docker/docker#16135]
Hello,

Docker version
```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64
```

Docker infos
```
Containers: 19
Images: 565
Storage Driver: devicemapper
 Pool Name: docker-8:1-267167-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.637 GB
 Data Space Total: 107.4 GB
 Data Space Available: 30.6 GB
 Metadata Space Used: 24.47 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.123 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-63-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 3.861 GiB
Name: test.dev
ID: BR5W:VCC2:HSNR:ADVH:OQH4:535M:QWDI:QF3Y:EYVY:4SVT:DLZS:HU5S
WARNING: No swap limit support
```

uname -a
```
Linux test.dev 3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

I mount in my docker host VM my code in /var/www/app and mount it as a volume in my app docker container :
```
-v /var/www/app:/var/www/app
```

When I vagrant reload / reboot vm, my docker container are automatically restarted (I run them with restart=always), the content is still present in the docker host VM but when I check in my container, the /var/www/app folder is now empty.

Restarting my container with "docker restart myapp" solves the problem and the files are present in the container.

Is there a way to keep volume in sync when reloading vagrant ?

Thanks

**Comment by phemmer** [comment]
If I'm understanding your description correctly, your `/var/www/app` directory on the host is itself a mounted filesystem. If so, this mount needs to be up before launching your containers. If the container is started before this mount is present, the container will be accessing the filesystem underneath the mount point.

I don't know what OS you are using for your VM, or how `/var/www/app` is being mounted, so I can't comment on the exact steps needed to fix this.
If you are unsure how to do this, I would recommend asking the support community for your VM's OS.
You might also try asking on the docker-users mailing list, docker forums, or docker channel on IRC. But since this isn't really an issue with docker, the docker bug tracker isn't really the right place.

However there is one feature which would affect this behavior: #15648. This would allow you to use `--rootmount=shared`. But note I would not consider this the proper solution to the issue, as you would then have a race condition, where when the container first starts up, the directory is empty.

**Comment by trompx** [comment]
@phemmer Exactly I mount a windows folder into my ubuntu 14.04 docker host VM. I was unsure if it was a bug with docker or not. I'll close and will investigate if the folder is mounted before docker restarts and see if it is possible to delay the docker restart after vagrant has synced the folder again.

Thank you for the info and the fast answer :)
