### ISSUE TITLE
docker commit memory issue

### ISSUE THREAD

**Issue by abilashks** [docker/docker#16301]
when i try to commit a docker container my partition reaches 100% always.
below is the docker information

uname -a
Linux abilash-1425 3.8.0-39-generic #58~precise1-Ubuntu SMP Fri May 2 21:33:40 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:16:50 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:16:50 UTC 2015
 OS/Arch:      linux/amd64

docker info
Containers: 13
Images: 205
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 232
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.8.0-39-generic
Operating System: Ubuntu precise (12.04.4 LTS)
CPUs: 4
Total Memory: 7.756 GiB
Name: abilash-1425
ID: ZOM5:A766:HYWH:XI2C:4ZHM:C3QF:6PD5:SBJJ:5A4I:67KN:H44A:FQ66

**Comment by phemmer** [comment]
How big is the partition docker operates on? (`df /var/lib/docker`)
How big is the change set? Have you tried committing a container with minimal changes? (`docker run fooimage touch /foo`)?
Can you compare `du /var/lib/docker` before and after running the `docker commit` to see where the space is going?

**Comment by abilashks** [comment]
df -h
/dev/sda1        56G   30G   23G  58% /
udev            3.9G  4.0K  3.9G   1% /dev
tmpfs           795M  1.1M  794M   1% /run
none            5.0M     0  5.0M   0% /run/lock
none            3.9G  152K  3.9G   1% /run/shm
cgroup          3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sda7        46G  180M   44G   1% /others
/dev/sda8        39G   52K   37G   1% /personal
/dev/sda6        83G   67G   12G  86% /home

du -sh /var/lib/docker
15G	/var/lib/docker

parent image size around 2 GB
changed files in container are very minimal

i am not able to compare docker folder size after running docker commit because my system gets hanged since it reaches 100% disk space

**Comment by abilashks** [comment]
yes tried for other small containers and it worked without any issues

**Comment by unclejack** [comment]
@abilashks You're running an outdated, deprecated, unsupported and buggy kernel: `3.8.0-39-generic`. Please follow the instructions on this page to get a supported kernel installed on Ubuntu 12.04: https://docs.docker.com/engine/installation/ubuntulinux/

You're running out of space because you may have too many images around and may also be running out of inodes. I'm using AUFS on a machine without any kind of problems and commit doesn't use up all disk space.

Please feel free to comment and to continue the discussion. I'll close this issue now because the kernel you're using is known to be badly broken and most certainly unsupported.
