### ISSUE TITLE
Environment Variables not accessible

### ISSUE THREAD

**Issue by michaeljs1990** [docker/docker#16382]
I have been fighting with this for about 8 hours now. I am using this image https://github.com/docker-library/haproxy/blob/master/1.5/Dockerfile which according to the docs won't get the environment variables since it runs the command directly.

So i made my own image importing that one and then adding a command.

```
CMD haproxy -f /config/file.cfg
```

according to the docs haproxy should now have access to my environment variables. but it does not. I even tried running CMD sh -c "haproxy -f config/file.cfg" since running sh -c env shows the variables I need.

**Comment by thaJeztah** [comment]
I see you also opened an issue in the repository of that image; https://github.com/docker-library/haproxy/issues/10, which is a better location to report and discuss this. You could try asking in the #docker-library IRC channel, as described in the [README](https://github.com/docker-library/docs/tree/master/haproxy#user-feedback) of that image.

I'm going to close this issue, because I think it's better to discuss this in the docker-library issue first. If this turns out to be a bug in Docker after that, feel free to comment here, then we can reopen.
