### ISSUE TITLE
keepalived using the docker, docker active stop keepalived can't delete the VIP

### ISSUE THREAD

**Issue by ss75710541** [docker/docker#16391]
`docker version`

```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64
 ```

`docker info`

```
Containers: 3
Images: 148
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.18.7-031807-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 3.86 GiB
Name: mysql2.10-3-10-48.optest.ucloud-bj-bgp-c.dm
ID: ITSW:BRRM:ZOAW:LAUD:ZUKF:7VVR:OMLW:NQG4:R3YT:IITW:3RMG:E7EY
WARNING: No swap limit support
```

`uname -r`

```
3.18.7-031807-generic 
```

 keepalived version is 1.2.13
 node1 10.3.10.47
 node2 10.3.10.48
 VIP 10.3.10.75
 

at 10.3.10.48 run keepalived

```
docker run -d \
    --name=docker-keepalived  \
    --privileged=true \
    --net=host \
    --restart always \
    -v /sbin/modprobe:/sbin/modprobe \
    -v /lib/modules:/lib/modules \
    keepalived
```

docker logs docker-keepalived
 
last logs
 
```
Starting Healthcheck child process, pid=17
Initializing ipvs 2.6
Starting VRRP child process, pid=18
Registering Kernel netlink reflector
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Registering gratuitous ARP shared channel
Registering Kernel netlink command channel
Opening file '/etc/keepalived/keepalived.conf'.
Configuration is using : 6968 Bytes
Using LinkWatch kernel netlink reflector...
Opening file '/etc/keepalived/keepalived.conf'.
Configuration is using : 67015 Bytes
Using LinkWatch kernel netlink reflector...
VRRP_Instance(VI_mysql) Entering BACKUP STATE
Opening script file /etc/keepalived/scripts/to_backup.sh
VRRP_Script(chk_mysql) succeeded
VRRP_Instance(VI_mysql) Transition to MASTER STATE
VRRP_Group(mysql) Syncing instances to MASTER state
VRRP_Instance(VI_mysql) Entering MASTER STATE
Opening script file /etc/keepalived/scripts/to_master.sh
```
ip addr show eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:4a:da:dc brd ff:ff:ff:ff:ff:ff
    inet 10.3.10.48/24 brd 10.3.10.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.3.10.75/24 scope global secondary eth0:0
       valid_lft forever preferred_lft forever
       
docker stop docker-keepalived

The last log without modification

```
Starting Healthcheck child process, pid=17
Initializing ipvs 2.6
Starting VRRP child process, pid=18
Registering Kernel netlink reflector
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Registering gratuitous ARP shared channel
Registering Kernel netlink command channel
Opening file '/etc/keepalived/keepalived.conf'.
Configuration is using : 6968 Bytes
Using LinkWatch kernel netlink reflector...
Opening file '/etc/keepalived/keepalived.conf'.
Configuration is using : 67015 Bytes
Using LinkWatch kernel netlink reflector...
VRRP_Instance(VI_mysql) Entering BACKUP STATE
Opening script file /etc/keepalived/scripts/to_backup.sh
VRRP_Script(chk_mysql) succeeded
VRRP_Instance(VI_mysql) Transition to MASTER STATE
VRRP_Group(mysql) Syncing instances to MASTER state
VRRP_Instance(VI_mysql) Entering MASTER STATE
Opening script file /etc/keepalived/scripts/to_master.sh
```

VIP is not deleted
`ip addr show eth0 `

```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:4a:da:dc brd ff:ff:ff:ff:ff:ff
    inet 10.3.10.48/24 brd 10.3.10.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.3.10.75/24 scope global secondary eth0:0
       valid_lft forever preferred_lft forever
```

Need to manually remove the VIP
`ip add del 10.3.10.75/24 dev eth0`
`ip addr show eth0`

```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:4a:da:dc brd ff:ff:ff:ff:ff:ff
    inet 10.3.10.48/24 brd 10.3.10.255 scope global eth0
       valid_lft forever preferred_lft forever
```

**Comment by phemmer** [comment]
The first thought that springs to mind, is the container properly observing the SIGTERM? If the container is running multiple processes, or if the master process ignores SIGTERM, the container might be getting forcibly killed, which prevents it from doing proper cleanup on shutdown.

Is this `keepalived` container published anywhere? Need a way to duplicate the issue for testing.

**Comment by ss75710541** [comment]
Container is only one keepalived process

**Comment by ss75710541** [comment]
1. Dockerfie

```
FROM centos:centos7
MAINTAINER jyliu <jyliu@dataman-inc.com>

RUN yum install -y epel-release && \
    yum install -y keepalived && \
    yum clean all

ENTRYPOINT ["/usr/sbin/keepalived"]
CMD ["--dont-fork","--log-console"]
```

2. ip addr show eth0
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:50:b6:ed brd ff:ff:ff:ff:ff:ff
    inet 10.3.10.47/24 brd 10.3.10.255 scope global eth0
       valid_lft forever preferred_lft forever
```

3. run 

```
docker run -d \
    --name=keepalived \
    --privileged=true \
    --net=host \
    --restart always \
    -v /sbin/modprobe:/sbin/modprobe \
    -v /lib/modules:/lib/modules \
    keepalived
```

4. ip addr show eth0

```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:50:b6:ed brd ff:ff:ff:ff:ff:ff
    inet 10.3.10.47/24 brd 10.3.10.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 192.168.200.16/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet 192.168.200.17/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet 192.168.200.18/32 scope global eth0
       valid_lft forever preferred_lft forever
```
5. Remove the container

```
docker rm -f keepalived
```

6. ip a show eth0

```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:50:b6:ed brd ff:ff:ff:ff:ff:ff
    inet 10.3.10.47/24 brd 10.3.10.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 192.168.200.16/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet 192.168.200.17/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet 192.168.200.18/32 scope global eth0
       valid_lft forever preferred_lft forever
```

7. the VIP is not deleted

**Comment by cpuguy83** [comment]
This is because you've used --net=host, docker is not going to clean these up for you since docker did not create them.
Is keepalived supposed to be cleaning these up on exit?
If so, are you sure the container is setup to capture signals for keepalived to know that it's time to shutdown?

Closing since this is not really a docker issue.
Feel free to ping on #docker on IRC, docker-user mailing list, or forums.docker.com for help here.
Thanks!

**Comment by ss75710541** [comment]
I don't doubt keepalived receives the stop signal
I kill within the docker keepalived is no problem, the VIP can normal to delete

**Comment by cpuguy83** [comment]
@ss75710541 

Bear in mind that some applications, especially when running as pid 1, will not handle signals.
You can test by doing `docker kill -s TERM <container id>`. If the process is handling signals, the container should stop (check with `docker ps`).

**Comment by sjiveson** [comment]
I also have this issue with VIPs not being removed when the container is stopped. I've tried Keepalived 1.2.13 in a CentOS 7 container and 1.2.19 in an Ubuntu Wily container, on both RancherOS and Ubuntu Wily. I've also compiled from the latest source in case this issue was a problem: https://github.com/acassen/keepalived/issues/159 - without success.

I also have the same issue when using Corosync and Pacemaker. Corosync and Pacemaker are not stopped when I issue `docker kill -s TERM cid`, so I guess that explains that one.

Keepalived is however. I get these log message when stopping the Keepalived containers using `docker stop cid`:

> Stopping Keepalived v1.2.13 (03/06,2015)
> VRRP_Instance(VI_1) removing protocol VIPs.

Which would also suggest the signal is being handled.

Relevant version information on the Ubuntu (vm guest) and RancherOS (bare metal) rigs:

Rig One:

uname -a

Linux hostname 4.2.0-18-generic #22-Ubuntu SMP Fri Nov 6 18:25:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

sudo docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.5.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.5.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

sudo docker info
Containers: 1
Images: 124
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 126
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.2.0-18-generic
Operating System: Ubuntu 15.10
CPUs: 4
Total Memory: 7.797 GiB
Name: redacted
ID: redacted
WARNING: No swap limit support

------------------------------------------------------

Rig Two:

uname -a

Linux hostname 4.2.3-rancher #1 SMP Wed Oct 14 11:25:04 UTC 2015 x86_64 GNU/Linux

docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   5eab58c
 Built:        Wed Oct 14 13:42:27 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   5eab58c
 Built:        Wed Oct 14 13:42:27 UTC 2015
 OS/Arch:      linux/amd64

docker info
Containers: 26
Images: 1775
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.3-rancher
Operating System: RancherOS (containerized)
CPUs: 64
Total Memory: 251.9 GiB
Name: redacted
ID: redacted
