### ISSUE TITLE
Bug : docker command arguments/options error

### ISSUE THREAD

**Issue by chatenilesh** [docker/docker#16392]
$docker run -it ds --privileged
This command ignores the --privileged option, i was not able to perform some operations in docker because of this as i needed privileged access inside my container.

I tried:
$docker run --privileged -it ds 
This worked for me.

$docker run -it ds --asd
The above command starts the container without reporting the error/warning for invalid option "--asd",etc.

basically the issue is:
If you provide the options after the container name those options are ignored.
At least a warning or error must be reported, i wasted 2 days because of this issue.

**Comment by phemmer** [comment]
Unfortunately docker cannot be adjusted to behave as you wish. In the command `docker run -it ds --privileged`, the `--privileged` option is not being ignored, it is being passed to the container's entrypoint.

For example:
```
# cat Dockerfile 
FROM fedora:22
ENTRYPOINT ["/bin/echo","my args are:"]

# docker build -t test . 
Sending build context to Docker daemon 2.048 kB
Step 0 : FROM fedora:22
 ---> ded7cd95e059
Step 1 : ENTRYPOINT /bin/echo my args are:
 ---> Running in ccf3cb9946de
 ---> 86bef7d2d7b8
Removing intermediate container ccf3cb9946de
Successfully built 86bef7d2d7b8

# docker run -it test --privileged
my args are: --privileged
```

Docker has no way of knowing that `--privileged` was erroneously provided to the container entrypoint instead of docker itself. The container might have a `--privileged` argument, and make use of it. If docker were to warn, the warning would be incorrect.

**Comment by cpuguy83** [comment]
what @phemmer 
This is documented in the command help.
