### ISSUE TITLE
Would the docker community  like to accept new performance/stress/stability test cases?

### ISSUE THREAD

**Issue by sunyuan3** [docker/docker#16417]
Currently, only functional test cases are included in the docker community.
I plan to create some new performance/stress/stability test cases. 

For example, performance tests are as follow(included but not limited to): 
CPU usage, Disk IO, network IO, TCP/IP bandwidth and latency,concurrent container quantity.

Benefits are as follow.
(1) They can provide docker users with performance reference. For example, a user need to deploy a server with docker. If the server's memory consumption figure is more than the benchmark data, the user can know much memory is need.
(2) We can use them to track performance history data for each commit to find which patch leads to the increase or the decrease of performance data.

But I wonder if the community would like to accept them. What is the attitude the docker community?

**Comment by thaJeztah** [comment]
Thanks for the suggestion, I'll add some people that might be interested in "tests" and "performance"

/cc @LK4D4 @unclejack @vdemeester

**Comment by unclejack** [comment]
@thaJeztah Thanks for the ping.

@sunyuan3 Reading a statement which says we don't have performance tests is a bit surprising. Have you looked at the unit tests of the various packages from the pkg/ directory?

We've already got Go benchmarks in the unit tests of various packages. The Docker daemon itself isn't tested for performance because stress testing some very specific parts of the code is much more difficult when testing the entire daemon.

Benchmarks have been added to packages which were discovered to be bottlenecks. Work has already been done to solve those problems and improve performance.

Should you be interested in helping with performance benchmarking, improving performance or both, you might want to take a look at @LK4D4's pull request history and mine because we've sent a lot of PRs which improve performance.

Regarding the other part with memory usage, this isn't a problem. Providing any kind of meaningful numbers which apply to everyone's deployment and usage patterns is difficult. Someone might have 10000 images and 100 containers, someone may have 100 images and 10000 containers, some might have 1000 running containers and 100000 stopped containers, some might be pushing images all the time. Different usage patterns will lead to different memory usage. Hardware with different specs will have different performance.

Beyond the resource limits (memory, CPU and others), Docker itself has very little impact (or none) on the performance of software running in containers. Benchmarks in that area will only benchmark the kernel and the hardware.

Finding the exact commit where a performance issue was introduced hasn't been a problem so far from what I know, at least that hasn't been the case so far for any of the performance improvement PRs from @LK4D4, from others and from me.

You'll find some actionable tasks below if you're interested in helping improve performance:
- discover bottlenecks & discuss them over IRC so we can tell you if those are known or not
- send PRs to add benchmarks to packages lacking benchmarks (or add different benchmarks to packages which have benchmarks already)
- send PRs to expand the testing of the code (unit tests, integration-cli tests)
- send PRs to improve the performance of code which has benchmarks already

Keep in mind that performance improvements are useful and they're always welcome, but unit tests and integration-cli are vital to making Docker as bug free as possible and contributions in that area are even more important. Performance problems are discovered and fixed, but a bug which ends up being in a shipped release can be pretty bad.

Anyone else interested in helping with testing and performance should also take this advice into account.

I'll close this issue now because I think your questions have been answered. Please feel free to comment.
