### ISSUE TITLE
Repository contains sources which are not patchable/no PRs accepted here for them

### ISSUE THREAD

**Issue by iskradelta** [docker/docker#16475]
Please remove the sources for the registry API, as no PR is accepted for those sources in this repository, hence those sources must not be in this repository. Improve your build system to fetch/checkout sources as submodules or whatever.

**Comment by phemmer** [comment]
> Improve your build system to fetch/checkout sources as submodules or whatever.

This is not possible.
The practice of storing dependency source code within the project is called vendoring. This is done because:

1. Not all remote sources come from git repos. Submodules only work for git.
2. Fetching remote sources depends on the repo hosting the remote source to be up and available. The docker project cannot guarantee this.
3. Fetching remote sources depends on the remote not changing the code from what  has been tested.  Yes most VCS uses commit IDs which change, but you're trusting the remote system again.
4. Fetching remote sources depends on the remote not removing the commit you pulled your code from.

Vendoring (which is what the practice of storing dependent code in the project repo is called) is such a common pattern that golang 1.5 has even included official support for it: https://golang.org/s/go15vendor

**Comment by unclejack** [comment]
Go based projects vendor dependencies and this project has taken the same approach. This workflow has worked great for a lot of contributors and people trying to hack on Docker. It also works when it comes to building Docker and packaging it for distributions.

This part of the process is something which doesn't seem likely to be changed because it works and it's going to become standard for projects written in Go.

Since your proposal would involve a fundamental change which involves taking a radically different approach than the ones used by Go projects and this was explained, I'm going to close this issue.

Thank you for understanding and for the input.
