### ISSUE TITLE
docker commit consume 3 hours on devicemapper

### ISSUE THREAD

**Issue by Zhang-Haoyu** [docker/docker#16505]
docker commit consume too much time, about 3 hours, any idea?

[environment info]
Host: centos6.6(linux-2.6.32-504)
docker: 1.3.2
graphdriver: devicemapper (centos 6.6 native devimapper)

**Comment by Zhang-Haoyu** [comment]
complement:
$ docker version
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa/1.3.2
OS/Arch (client): linux/amd64
Server version: 1.3.2
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 39fa2fa/1.3.2

$ docker info
Containers: 3
Images: 15
Storage Driver: devicemapper
 Pool Name: docker-8:1-55312960-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 90.97 GB
 Data Space Total: 1.074 TB
 Metadata Space Used: 51.15 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 2.6.32-504.16.2.el6.x86_64
Operating System: <unknown>

**Comment by Zhang-Haoyu** [comment]
strace docker commit, found so many lstat syscall, shown as below
10:37:39.601729 lstat("/var/spool/postfix/maildrop", {st_mode=S_IFDIR|0730, st_size=20480, ...}) = 0 <0.000028>
10:37:39.601869 lstat("/var/spool/postfix/maildrop/31CA72709DD", 0xc2082323f0) = -1 ENOENT (No such file or directory) <0.000060>
10:37:39.602014 open("/var/spool/postfix/maildrop/31CA72709DD", O_WRONLY|O_CREAT|O_CLOEXEC, 0744) = 3 <0.000075>
10:37:39.602173 write(3, "", 0)         = 0 <0.000024>
10:37:39.602261 read(0, "T\0211422598262 203863A\25rewrite_con"..., 32768) = 548 <0.318866>
10:37:39.921325 futex(0x109c4d8, FUTEX_WAKE, 1) = 1 <0.000130>
10:37:39.921643 write(3, "T\0211422598262 203863A\25rewrite_con"..., 548) = 548 <0.000107>
10:37:39.921968 futex(0x109c4d8, FUTEX_WAKE, 1) = 1 <0.000119>
10:37:39.922296 close(3)                = 0 <0.000118>
10:37:39.922614 futex(0x109c4d8, FUTEX_WAKE, 1) = 1 <0.000089>
10:37:39.922891 lchown("/var/spool/postfix/maildrop/31CA72709DD", 0, 90) = 0 <0.000097>
10:37:39.923105 futex(0x109c4d8, FUTEX_WAKE, 1) = 1 <0.000036>
10:37:39.923219 chmod("/var/spool/postfix/maildrop/31CA72709DD", 0744) = 0 <0.000034>
10:37:39.923348 utimensat(AT_FDCWD, "/var/spool/postfix/maildrop/31CA72709DD", {UTIME_OMIT, {1422598262, 0}}, 0) = 0 <0.000026>
10:37:39.923481 read(0, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 32768) = 988 <0.000020>
10:37:39.923600 futex(0xc2080712f0, FUTEX_WAKE, 1) = 1 <0.000021>
10:37:39.923700 lstat("/var/spool/postfix/maildrop", {st_mode=S_IFDIR|0730, st_size=20480, ...}) = 0 <0.000021>
10:37:39.923815 lstat("/var/spool/postfix/maildrop/4CD472E38E8", 0xc208232510) = -1 ENOENT (No such file or directory) <0.000063>

About there are 100000 small files which are about 20KB in container's /var/spool/postfix/maildrop/, I delete the whole directory of /var/spool/postfix/maildrop/, then perform docker commit again, which consume only 1min now.

IMO, snapshot is thing of block level, should has nothing to do with files in container,
maybe I missed something.
Any ideas?

Thanks,
Zhang Haoyu

**Comment by Zhang-Haoyu** [comment]
I read the code flow of docker commit, found that
ExportRw() is performed before creating dm-thin snap, 
and StoreImage(layerdata) is performed after dm thin snap has been created.
Why perform the tar and untar layerdata?
If there are too many small files in container, the process of layerdata's diff, tar, and untar  will
consume much time, i think.
I am a freshman of docker, any helps is appreciated.

**Comment by Zhang-Haoyu** [comment]
I know that kvm's qcow2 snapshot is only a thing of block level,  never care about the files in vm.

**Comment by cpuguy83** [comment]
@Zhang-Haoyu You are using a very out of date version of docker, and are on an unsupported platform, so I'm not sure how much we can help.

ping @rhvgoyal who maintains the devicemapper driver.

**Comment by Zhang-Haoyu** [comment]
Thanks for your reply.
What does "on an unsupported platform" exactly mean? 
Do you mean using centos6.6 (linux-2.6.32-504) as the docker host?
And, I think no other than the process of diff, tar, untar  layerdata contribute much time, not dm thin snap, right?

**Comment by unclejack** [comment]
@Zhang-Haoyu There are a few problems with your setup, as @cpuguy83 has also stated, and slow commit isn't the biggest one:
1) RHEL 6.x and CentOS 6.x aren't supported because Red Hat doesn't support Docker on RHEL 6.x (https://access.redhat.com/solutions/1378023). The CentOS project doesn't support Docker on CentOS 6.x either.
2) That Docker version is very old and many improvements have been implemented since that version. Docker 1.8.2 is the current stable and 1.9.0 will soon follow.
3) You're using Docker with devicemapper with loopback mounted block devices (`Data file: /var/lib/docker/devicemapper/devicemapper/data
Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata`). This contributes to the behavior you've observed.

The problems you've mentioned above with slow tar & untar have been fixed by improving performance in many areas. Devicemapper's code has also improved since Docker 1.3.2 was released.

You should upgrade to CentOS 7.x and use that instead. I'm going to close this issue now because CentOS 6.x is unsupported, we've explained what's wrong with your setup and there's no bug for us to fix in this case.

Please feel free to comment. There's no need to open another issue, we can continue the discussion here.

**Comment by Zhang-Haoyu** [comment]
Thanks so much for your helpful reply.
I will replace loopbak block device with hard disk partion.
