### ISSUE TITLE
Cannot push to docker registry but I am logged in

### ISSUE THREAD

**Issue by lorenzvth7** [docker/docker#16694]
I've a master (with node) and node1 and node2. I've installed docker and OpenShift on them and they are working as a master-node environment. I have created a private docker registry on my node1.
The problem is that I can't push to this registry when I'm on another node.
But I am able to login so I don't know the issue (I already did a login with the token):

```
Please login prior to push:
Username (test-admin): 
WARNING: login credentials saved in /root/.docker/config.json
Login Succeeded
The push refers to a repository [172.30.26.202:5000/openshift/busybox] (len: 1)
d7057cb02084: Image push failed 
Error pushing to registry: Authentication is required.
```

**Comment by thaJeztah** [comment]
This could be an issue with the setup of your registry. There are several existing issues on the docker/distribution issue tracker that may contain useful information on this topic, https://github.com/docker/distribution/issues?utf8=✓&q=is%3Aissue+authentication

Could you search those topics? Asking in the #docker-distribution IRC channel for more interactive help finding a solution would be an alternative as well.

I'm going to close this issue for now, because this issue tracker is not a general support forum, but feel free to comment here after I've closed
