### ISSUE TITLE
Java App w/ log4j2 outputing to STDOUT not working without -t

### ISSUE THREAD

**Issue by ezjacob-maheim** [docker/docker#16725]
Docker Version
```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64
```

I'm having an issues when I deploy a docker container to AWS elasticbeanstalk where the stdout from the java app doesn't print to console when using log4j2. When I run the container with ```docker -dt``` locally I can see the logging but if I run it just detached without th -t  and look at docker logs I don't see any output from the log4j2. AWS ElasticBeanstalk doesn't have an option to run the containers with -t so anyone know of what could be causing this issue? please let me know if I need more detail

**Comment by cpuguy83** [comment]
Hello, this looks like a config issue with log4j2.
Note that there are several stack overflow Q's around the issue of log4j not outputing to stdout in general.

But in any case, for troubleshooting these kinds of issues, it's much easier to help from either the docker-user mailing list, or #docker on IRC.

Closing this here since it doesn't look a Docker issue, but feel free to ping on either of the mentioned locations for help.

Thanks!

**Comment by ezjacob-maheim** [comment]
Not sure where your reading this stdout issue? The app runs fine when running locally without docker. But it doesn't log when I run it in docker with the -t option. Wouldn't this be a docker issue then?

**Comment by cpuguy83** [comment]
@ezjacob-maheim It sounds like your config is expecting a tty for some reason.
The only thing `-t` does is allocate a tty for the container.
