### ISSUE TITLE
Yum repo not working (http status 503)

### ISSUE THREAD

**Issue by smougenot** [docker/docker#16750]
It looks like the repos in https://yum.dockerproject.org are out of order :
```
Error 503 Connection refused

Connection refused

Guru Mediation:

Details: cache-fra1234-FRA 1443948760 2277097692

Varnish cache server
```

**Comment by russmckendrick** [comment]
This was a regular occurrence for both the YUM and APT repos, it looks like the [APT](https://apt.dockerproject.org) repo has been fixed but those changes haven't been applied to the YUM one.

They should look at moving both for Amazon S3 with Cloudfront in front of them to better handle spikes caused by servers automatically updating, especially now these repo's appear to be recommend installation source.

**Comment by thaJeztah** [comment]
Hmf. For reference; https://github.com/docker/docker/issues/16101, and https://github.com/docker/docker/issues/16101#issuecomment-138143486

/cc @jfrazelle

**Comment by nabheet** [comment]
Yup, quite unfortunate! :+1:

**Comment by jfrazelle** [comment]
its back, il look into what happened later looks like the apt repo was
uneffected...

**Comment by jfrazelle** [comment]
also the changes were applied to the yum repo as well...

**Comment by nabheet** [comment]
Thank you!
