### ISSUE TITLE
404 : Understanding docker Link

### ISSUE THREAD

**Issue by Deborah-Digges** [docker/docker#16918]
This link is currently broken:
https://docs.docker.com/misc/introduction/understanding-docker.md

**Comment by thaJeztah** [comment]
Thanks @Deborah-Digges, could you tell us where you found that link? I.e. on what page is that link mentioned?

**Comment by Deborah-Digges** [comment]
Sorry, I should have been more specific.
It's on [docs](https://docs.docker.com/) > Use Docker > [About Docker](https://docs.docker.com/misc/) > About this Guide > [Understanding Docker Section](Understanding Docker section)

**Comment by thaJeztah** [comment]
Thanks @Deborah-Digges. Looks like this is a duplicate of https://github.com/docker/docker/issues/15837, which was fixed in https://github.com/docker/docker/issues/15837. Those changes aren't published yet on the website, but I tested the docs locally and this looks to be fixed indeed.

I'm going to close this issue, because this has been fixed. Thanks for reporting! :+1:
