### ISSUE TITLE
Document the format of image digest status message from /push endpoint

### ISSUE THREAD

**Issue by mattnworb** [docker/docker#16988]
[The docker-maven-plugin](https://github.com/spotify/docker-maven-plugin) can be used for Maven projects to push an image to the user's configured Docker registry at certain points in the build process. The plugin uses [the docker-client library](https://github.com/spotify/docker-client), which communicates with the docker daemon using the Remote API.

When pushing an image, we would like for the plugin to be able to be aware of the registry-assigned digest for the image, so that it can be communicated to downstream plugins / build steps.

docker-client tries to find the image digest by basically grepping through the JSON status messages sent by the /push endpoint. We (docker-maven-plugin maintainers) [discovered that in docker v1.8 the format of the message changed](https://github.com/spotify/docker-client/issues/250) from

```
Digest: sha256:dbad7f727f340f4bfa1160689eaf57a60242bf9a48cc2c4c14f383c9b66e8f06
```

to something like 

```
0.2.1-SNAPSHOT-efd3f71.DIRTY: digest: sha256:8138f3c93c333aa1db6634ae77fce1a50febb9b189ba6fb2121f22810b7841b3 size: 41358
```

1. Would it be possible to document the format of the status message containing the image digest to make it less susceptible to unintended changes in future docker versions?

2. Is there a smarter way for the docker-client library to get the image digest after/during a push?

**Comment by dmcgowan** [comment]
This is not going to be something which is documented since it is used like this internally only and not intended to be used in this manner. There is a smarter way to get the digest through using a custom JSONMessage and intercepting the message before it is formatted for the console. Some recent refactoring is making this look like a much more reasonable change and one we plan to make. This is mainly intended to be used for content trust but it may be possible to add a summary message at the end with all the digests which were pushed. I might suggest adding a proposal after the update to use JSONMessage directly is done.

**Comment by mattnworb** [comment]
@dmcgowan when you say 

> using a custom JSONMessage and intercepting the message before it is formatted for the console

do you mean adding something to the docker CLI to handle this? 

Basically for our purposes, all we would really like is a clear way to be able to find out the digest of an image after it has been pushed, preferably through the remote API used to talk to the docker daemon.

**Comment by LK4D4** [comment]
@dmcgowan @stevvooe @aaronlehmann do you know if something was done about this? Is this still worth to implement?

**Comment by aaronlehmann** [comment]
The digest was added to the `JSONMessage` so it doesn't need to be parsed out of the textual output.

I think we can close this.

**Comment by LK4D4** [comment]
@aaronlehmann Thanks!
