### ISSUE TITLE
How to set a command output in an ENV instruction

### ISSUE THREAD

**Issue by fabala** [docker/docker#16980]
Hi,

In my Dockerfile, I would like to do something like:

ENV MY_USER=\`whoami\`

USER root
COPY ...
RUN chmod ... && chown ...

USER $MY_USER

I.e. storing the current user,
then using root user,
then copying files and setting expected permissions,
then finally restore current user

Any ideas?

**Comment by duglin** [comment]
Please see https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

As of now no more syntax changes are going into the Dockerfile.  However, there is some work underway to allow for a client-side builder.  In that model we're toying with the idea of allowing for some advanced scripting options - one of which would be to allow for things like what you're suggesting.  

So for now I'm going to close this since its not actionable at this time, but watch this space for future work to make this possible.
