### ISSUE TITLE
Permissions on an afs volume don't exist

### ISSUE THREAD

**Issue by bkolobara** [docker/docker#17019]
My setup:

$HOME folder is on afs as part of a corporate network.
When I log in to my machine afs automatically mounts to my file system.
/home/ is empty
$HOME = /afs/users/bkolobara/

Now i want to attach a volume when running a docker container:
`docker run -v ~/Development:/development container_name bash`

I can't access anything inside /development. I tried disabling selinux, starting in --privileged mode giving everyone read/write access to the development folder, but nothing worked.

When running `ls -l /development` inside the container it shows ? for permissions.:

```
drwxr-xr-x. 2 75900 1307 2048 Oct 13 10:59 folder1
??????????? ? ?     ?       ?            ? file1.py
??????????? ? ?     ?       ?            ? file2.py
d?????????? ? ?     ?       ?            ? folder2
```

No idea what is going on.

```
docker version:
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 06:06:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 06:06:01 UTC 2015
 OS/Arch:      linux/amd64

docker info:
Containers: 48
Images: 33
Storage Driver: devicemapper
 Pool Name: docker-253:1-1549027-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 7.248 GB
 Data Space Total: 107.4 GB
 Data Space Available: 38.29 GB
 Metadata Space Used: 9.74 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.138 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 8
Total Memory: 7.551 GiB
Name: test.cern.ch
ID: WSAX:MWDE:7C7Z:JOSI:UX6J:7TLR:C7D3:MDGP:SBUC:I6M3:EOKC:T7NR
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

uname -a:
Linux test.cern.ch 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by cpuguy83** [comment]
I'm really not particularly familiar with afs... but does this require having acl's supported in userspace?
Maybe install the appropriate acl package... but I'm not sure since I have no experience with afs.
Also, would not recommend disabling selinux. Instead you can use the `z` or `Z` option on the volume mount spec to have docker relabel the dir to allow access from the container `-v ~/Development:/development:Z` ...
but this is likely a separate concern than what you are currently seeing.

**Comment by bkolobara** [comment]
I'm also not familiar with afs and can't tell what it requires. But after trying a few times the question marks are gone. I don't think I changed anything on my system.

```
drwxr-xr-x. 2 75900 1307 2048 Oct 13 10:59 folder1
-rwxr-xr-x. 1 75900 1307  127 Oct 12 09:04 file1.py
-rwxr-xr-x. 1 75900 1307  254 Oct 12 09:04 file2.py
drwxr-xr-x. 2 75900 1307 2048 Oct 13 07:54 folder2

```
But I still can't read any of them
` Permission denied`

**Comment by cpuguy83** [comment]
In this case you probably need to use the `z` or `Z` option on your `-v` as shown above.

**Comment by bkolobara** [comment]
I tried now `z` and `Z` and the questionmarks are back. Then I tried without `z` and I still get them now. It looks every time I run the container I get different results.

Now I tried to do a `ls ~/Development` on the host and afterwards run the container and the questionmarsk are gone.

So my guess is that the local `ls` warmed up some cache and the container could read the permissions, but still doesn't let me access anything (even with `z` set). I guess my workstation has a complicated network fs setup and I'm not exactly sure what is going on in the background.

How does docker usually handle network filesystems passed as volumes?

**Comment by cpuguy83** [comment]
Docker just bind-mounts into the container, nothing else.

**Comment by greenboxal** [comment]
The docker daemon and the container process tree doesn't have Kerberos tickets nor have AFS tokens for accessing the volume. You must note that not even `root` can access a AFS cell without tokens (and there is nothing you can do about it).

I tried starting the docker daemon with `pagsh` and `k5start` but it didn't solve the problem. Seems like whatever process mounts the volume, it doesn't have the appropriate tokens.

I'm willing to create a patch for this. I think the following will suffice:

* Allocate a PAG
* Get tickets from a krb5 keytab
* Invoke `aklog` in order to get the AFS token

Can anyone point me places where the volume is mounted in the code? Would help a lot.

**Comment by BertrandNOEL** [comment]
Hey @bkolobara 
Using Docker 1.10, on CentOS 7.2, and SELinux enabled, I can access my AFS files from inside the container.
I created my container this way: `sudo docker run -it -v /afs:/afs centos bash`

The Kerberos and AFS tokens have to be initialized on the host (trying to get an AFS token inside the container will not work anyway). You first have to get the Kerberos token (kinit), and then get the AFS one (aklog).

When your Kerberos ticket expires, you will still see the content of your private folder (I guess there is a cache), but will not be able to write inside. In that case, renew the Kerberos token on the host, and then get the AFS token, and you will get back the rights inside your container

**Comment by greenboxal** [comment]
How are you running the docker daemon?

There is no way on Linux to the AFS token pass down to the container process tree. Besides being spawned by `docker daemon` rather than the docker client which has your credentials- because your shell has it- `runc` breaks the process tree making the PID 0 of the container the session leader.

**Comment by BertrandNOEL** [comment]
I did not say I got any token inside the container. I said I could access my AFS files from inside my container, and the token is handled in the host.

**Comment by thaJeztah** [comment]
Is there anything left to do here, or is this a configuration issue / expected with AFS (due to the token not being present inside the container)?

**Comment by thaJeztah** [comment]
closing because this went stale
