### ISSUE TITLE
Shuting down daemon is slow/can containers be stopped in parallel?

### ISSUE THREAD

**Issue by vlerenc** [docker/docker#17015]
Hi, we have a performance issue when shutting down Docker daemons (usually running hundreds of containers). Is it possible to run the container stop operations in parallel? One takes a few seconds, but if you have hundreds, you wait half an hour or so, which is painful and requires very long timeouts in the rest of the infrastructure we are using. Thanks in advance, Vedran

**Comment by vlerenc** [comment]
I checked the open tickets and found none about that.

The version I am using is 1.6.0. We have 1.8.2 running as well, but not so many containers live there.

Info on one of the 1.6.0 docker daemons:
Containers: 306
Images: 195
Storage Driver: aufs
 Root Dir: /var/vcap/store/docker/docker/aufs
 Backing Filesystem: extfs
 Dirs: 819
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 31.05 GiB
Name: 13feb611-ee33-4ae9-bdbb-5a691e117d01
ID: 5VFH:BBTH:5ETS:QUFY:F5XI:FABU:H426:MRT6:6IM3:2ULM:KJXQ:G5GP

OS: Linux 13feb611-ee33-4ae9-bdbb-5a691e117d01 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Not sure whether this qualifies as a bug.

**Comment by coolljt0725** [comment]
Actually, the docker is run the container stop operations in parallel, each container is being shutdown in a go routine .  Have you ever take half an hour or so to wait the docker daemon shutdown? I think that doesn't make sense since docker daemon will shutdown in 15 seconds no matter if there is container still running.

**Comment by cpuguy83** [comment]
Yep, as @coolljt0725 said, the daemon has a 15second timeout waiting for containers to stop before it kills them, and they are all done in parallel.

Can you provide some daemon logs for when the shutdown takes a long time?
Also, 1.6.0 is extremely old, a lot of the code for handling this has been rewritten since then (though the timeouts and parallel shutdowns were still in place in 1.6.0). So troubleshooting a 1.6.0 daemon may be difficult.

**Comment by vlerenc** [comment]
Ah, thank you. My mistake. We are using Docker embedded within a community Bosh/Cloud Foundry deployment and the outer control script is the culprit that stops the containers one by one. My mistake, I should have checked that first. Best regards, Vedran
