### ISSUE TITLE
docker ip ${container_id}

### ISSUE THREAD

**Issue by elgalu** [docker/docker#17039]
```sh
docker port postgres 5432
#=> 0.0.0.0:32856

docker ip postgres
#=> docker: 'ip' is not a docker command.
#=> See 'docker --help'
```

:'(

**Comment by thaJeztah** [comment]
It's possible to obtain this information with `docker inspect` and a template (`-f` / `--format`), for example;

```bash
docker inspect -f "{{ .NetworkSettings.IPAddress  }}" postgres
172.17.0.1
```

*However*, depending on what you're trying to achieve, it's better to use `--link` or the new discovery mechanisms in docker 1.9 to connect to a container.

The reason we don't have a `ip` subcommand is that there are too many properties on a container to add commands for. The `docker inspect` command allows you to obtain *any* information on a container, and also allows you to format that output.

I'm going to close this issue because this is not something we will implement, but thanks for the suggestion :+1:
