### ISSUE TITLE
1.9: Config.MacAddress gets dropped

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#17131]
In Docker 1.8 if you didn't send a mac address on create `Config.MacAddress` in inspect would equal empty string.  In 1.9 the field is dropped if it is the empty value.  For backwards compatibility this field should not be dropped but be empty string.

**Comment by thaJeztah** [comment]
Thanks for reporting @ibuildthecloud 

/cc @tiborvass

**Comment by gesellix** [comment]
I'd personally prefer to drop the field for such cases, because that would force the client to prepare for missing properties. On the client side, how do you currently handle the empty field? I'd guess that it's the same way it would handle a missing field.
Softly enforcing them to gracefully handle missing or empty fields leads to better backwards compatibility imho.

@ibuildthecloud Maybe I don't fully understand how you're using the `MacAddress` or the `NetworkDisabled` fields, so please explain if I have wrong assumptions :-)

**Comment by runcom** [comment]
We just need to maintain backward compatibility, even if it's better to entirely drop the field we must assure lower versions still maintain the same api.

**Comment by gesellix** [comment]
Hm, yes that's probably more important. Thanks for the quick feedback!

**Comment by runcom** [comment]
Fixing this

**Comment by thaJeztah** [comment]
I know there have been discussions around that in the past, because;

> Docker's Remote API uses an open schema model. In this model, unknown properties in incoming messages are ignored. Client applications need to take this behavior into account to ensure they do not break when talking to newer Docker daemons.

Basically, client applications *should* handle missing properties, but I agree it's good to keep backward compatibility if possible

**Comment by runcom** [comment]
> Client applications need to take this behavior into account to ensure they do not break when talking to newer Docker daemons.

@thaJeztah you're right but this is explicitly breaking old behavior (even if daemon is newer)

**Comment by runcom** [comment]
There seems to be some issue tho, specifically, 504e67b867865a2835e8002c01087a2cfd7bfd0e added a note (https://github.com/docker/docker/commit/504e67b867865a2835e8002c01087a2cfd7bfd0e#diff-2660508eef7a8eeadb6d27b8bbf6d718R15) stating:
> All fields added to this struct must be marked `omitempty` to keep getting  predictable hashes from the old `v1Compatibility` configuration.

ping @tonistiigi , is it safe to populate (empty string) these fields for docker <= 1.8?

**Comment by ibuildthecloud** [comment]
In general though I would say I don't like dropping fields.  Especially for dynamic language clients you constantly have to check if the field exists before checking the value of the field.

**Comment by tonistiigi** [comment]
If you think the empty field makes more sense for some specific fields like `MacAddress` and `ExposedPorts` these can be added back(or changed by API version). It may result a cache bust for some images but as these fields are quite old the effect shouldn't be that big. Also these images will get different IDs compared to `v1.8.3` after v2 pulls if you change the JSON on disk. The comment should stay and any new fields must always be marked omitempty. This is because previous docker versions always updated image configurations on pull meaning configurations changed every time someone updated docker - now we attempt to revert the changes that didn't add anything but an empty field.
