### ISSUE TITLE
How to install Docker in Ubuntu 15.04 offline

### ISSUE THREAD

**Issue by elkebirmed** [docker/docker#17146]

**Comment by thaJeztah** [comment]
Hi @elkebirmed please keep in mind that this is not a support forum, but an issue tracker for bugs, features and pull requests. 

Please ask/discuss this question in:

- https://forums.docker.com/
- the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
- the #docker IRC channel

Since this isn't a bug, I'm going to close this now. Please feel free to comment.
