### ISSUE TITLE
--cluster-advertise only known ips

### ISSUE THREAD

**Issue by vieux** [docker/docker#17248]
I had trouble setup the multi-host networking on ecs.
The issue is I was using the public IPs (54.x) in `--cluster-advertise` and this doesn't work because this IP isn't known by the machine.
You have to use the private one, usually associated with `eth0` 

What about making sure that `--cluster-advertise` returns an error when you cannot bind the ip ? (or at least a warning)

**Comment by vieux** [comment]
ping @mavenugo @mrjana

**Comment by sanimej** [comment]
@vieux If the public IP is configured on the server bind will succeed. Another option might be to check if the route to the cluster-advertise IP and cluster-store IP both go via the same interface.

**Comment by dave-tucker** [comment]
If the expectation is that `--cluster-advertise` should be an address that is present on one of the adapters on the server we should absolutely add a check here and prevent the daemon from starting if it isn't so.

Is `--cluster-advertise` supposed to support use cases where the server may be behind NAT, and is to be clustered with other servers (maybe in different data centers) that are also behind NAT?

**Comment by thaJeztah** [comment]
@vieux does this relate to https://github.com/docker/docker/issues/17047 ?

**Comment by thaJeztah** [comment]
Actually, I think it may be a dup

**Comment by sanimej** [comment]
@dave-tucker If the --cluster-advertise IP is not present in any of the NICs then we do fail in the serf init and daemon won't start. I think the case @vieux ran into was that the IP was valid but it didn't have reachability to the cluster.

I think its quite possible that the kv-store server could be behind NAT. In such cases I am not sure if there is a fool proof way to check the correctness of the --cluster-advertise IP.

**Comment by vieux** [comment]
@sanimej 

@mrjana can correct me if I'm wrong, but I don't think this is correct. Serf init failed, but the daemon started. That was an issue for me. I would like to see the daemon fail to start if serf init fail

**Comment by mavenugo** [comment]
@vieux where should we fail this configuration ? at the discovery (or) at libnetwork ?
there is a difference here. Though overlay driver makes use of the `--cluster-advertise` to advertise the local endpoint for the tunnel, it still works for connectivity between the local containers without it.
Hence, we don't have a hard requirement to fail the daemon bootup due to a misconfigured `--cluster-advertise`.

If you think it is not useful even for the discovery layer to support this, then we could potentially fail at the discovery level and it will become a base requirement for docker discovery in general and hence for all the applications depending on it as well.

An alternative could be to simply throw an error at the libnetwork level cautioning the user that this configuration might not work for multi-host networking.

What would be your preference ?

**Comment by vieux** [comment]
@mavenugo I would say at the libnetwork level, because discovery doesn't care about have a real IP it can bind.

In Swarm most of our used advertise the public IP (54.x) and it works fine.

**Comment by mavenugo** [comment]
fixed via #17381 
Message is added in libnetwork to notify the user.
