### ISSUE TITLE
docker cve

### ISSUE THREAD

**Issue by keloyang** [docker/docker#17292]
where can I find a way to search docker cve and the solutions ?

**Comment by thaJeztah** [comment]
Which CVE's were resolved in a release can be found in the release notes (e.g. https://github.com/docker/docker/releases/tag/v1.8.3)

the solutions can be found in the commit history of the branch, for example: https://github.com/docker/docker/commits/v1.8.3

@keloyang thanks for asking! I'm going to close this issue because this is not a bug or a feature request, but feel free to comment here after I've closed

**Comment by keloyang** [comment]
@thaJeztah Thank you very much.

**Comment by thaJeztah** [comment]
@keloyang if you need more information, or your company requires early access to security notices, feel free to get in contact via security@docker.com to ask what the options are
