### ISSUE TITLE
OpenSuse 13.1 Guide Is Wrong - Files Are Missing

### ISSUE THREAD

**Issue by darrenturn90** [docker/docker#17380]
https://docs.docker.com/installation/SUSE/

Doesn't work. Docker doesn't exist in the repository, making docker useless for my 13.1 installation.

Any clues?

**Comment by thaJeztah** [comment]
The documentation for SUSE was updated since, but those changes are not yet published on the website (the docs will be updated together with the 1.9 release); https://github.com/docker/docker/blob/master/docs/installation/SUSE.md

The new docs state;

> Docker is part of the official openSUSE repositories starting from 13.2. No additional repository is required on your system.

So that may be the difference.

Let us know if that helped, or if additional changes are needed to the documentation! Thanks in advance for testing!

**Comment by darrenturn90** [comment]
Thanks for your reply thaJeztah, however I am using 13.1, and its not included in that distribution.

**Comment by thaJeztah** [comment]
The docs mentions 13.2, but perhaps @flavio can provide more information

**Comment by flavio** [comment]
@darrenturn90: Docker was not part of the official repositories of openSUSE 13.1. Unfortunately we had some packaging issues with openSUSE 13.1 on OBS. Given this release of openSUSE is going to be discontinued pretty soon (Jan 2016), we decided to focus on openSUSE 13.2, Leap, Tumbleweed and Factory.

**Comment by thaJeztah** [comment]
Thanks @flavio!

@darrenturn90 with this information, I'm going to close this issue, because the documentation is correct (not yet live), so I don't think there's anything else to be done here.

Thanks for reporting though, it's always appreciated to have some extra eyes on the docs!
