### ISSUE TITLE
container exited abnormally

### ISSUE THREAD

**Issue by maksonlee** [docker/docker#17397]
container exited abnormally, and the following message was found in /var/log/syslog, how can i get more detailed info?

    systemd[1]: Stopped docker container

here is my environment,
    
    $ docker version
    Client:
     Version:      1.8.3
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   f4bf5c7
     Built:        Mon Oct 12 05:39:44 UTC 2015
     OS/Arch:      linux/amd64
        
    Server:
     Version:      1.8.3
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   f4bf5c7
     Built:        Mon Oct 12 05:39:44 UTC 2015
     OS/Arch:      linux/amd64

    $ docker info
    Containers: 1
    Images: 23
    Storage Driver: aufs
     Root Dir: /media/d/docker/aufs
     Backing Filesystem: extfs
     Dirs: 25
     Dirperm1 Supported: true
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 4.2.0-16-generic
    Operating System: Ubuntu 15.10
    CPUs: 40
    Total Memory: 251.9 GiB
    Name: ch-ubuntu-buildsrv111
    ID: AW2S:AOF6:UQZJ:DIB2:EXUG:RSHW:QG5T:U7II:I6KN:HKZ6:ZD2A:P4GB
    Debug mode (server): true
    File Descriptors: 20
    Goroutines: 37
    System Time: 2015-10-27T18:29:31.692542449+08:00
    EventsListeners: 0
    Init SHA1: e2a9864fe092a3a794747b6eecfcd82b158ce45e
    Init Path: /usr/lib/docker/dockerinit
    Docker Root Dir: /media/d/docker
    WARNING: No swap limit support

**Comment by thaJeztah** [comment]
Running the daemon in debug mode (`-D`) should produce more logs. However, this question is more suitable for asking in the #docker IRC channel, the [Docker-Users mailing list[(https://groups.google.com/forum/#!forum/docker-user), or https://forums.docker.com

I'm going to close this issue, because GitHub is not the best place to discuss this, however, feel free to comment here after I've close this issue :smile:
