### ISSUE TITLE
[discussion]: consider to add a Volume Plugin API to support mapping a raw block device to container.

### ISSUE THREAD

**Issue by moypray** [docker/docker#17391]
Use Case:
  In some scenario,  the container need to use raw block device just like "/dev/blockn" to store data.  Of course if only one container we can use "docker run --device /dev/xxx" option. but what if there are lots of these containers and need to be managed automatically. 

  I think add a new Volume Plugin API is a better solution and valuable to consider. And if we have this API, we can work together with lots of remote Block back end storage server(such like cinder, SAN, ceph rdb. etc..)

thanks!

**Comment by phemmer** [comment]
> but what if there are lots of these containers and need to be managed automatically.

Multiple things accessing a block device directly is bad, and will most certainly lead to corruption of whatever data is stored.
Assuming this block device holds a filesystem, then the filesystem should be mounted on the host, and the directory volume-mounted into the container.
If this isn't a filesystem, but processes are directly manipulating the device, this cannot be supported as the processes need to coordinate with each other to make sure they don't stomp all over each other.

However if what you're proposing is a coordinator so that no 2 containers are running with the device mapped simultaneously, this would be theoretically possible, but I would argue should not docker's responsibility.

But if you're proposing something else entirely, then I apologize :-)

**Comment by moypray** [comment]
Sorry My description may be confused. 
1. "lots of containers"  does NOT mean  they share the Block Device. but like this:
      containerA    use   /dev/block1
      containerB    use   /dev/block2 & /dev/block3.
       .......
      containerXXX   use  /dev/blockxxx

     Each block device is used only by one container(or application) and the block device data could store in remote block device server(like SAN or others).

2. I think there are lots of this kind of application/software use block device directly without any file system to gain a high speed (instead of database).
if  the container run this kind of application/software, this scenario comes up.

**Comment by cpuguy83** [comment]
There is already a volume plugin API that you could use to handle this as you want.
Also, this _really_ seems more like `--device` is what you want and not a volume as volumes are really about providing a filesystem to a container, not raw block devices, where as `--device` is specifically for adding a device to a container.

Closing as there is nothing really to add here.
