### ISSUE TITLE
Support privileged with user namespaces

### ISSUE THREAD

**Issue by mrunalp** [docker/docker#17409]
Currently, privileged isn't supported when user namespaces are on. However, there are many use cases where one would want to run privileged containers side by side with user namespaced containers.

How about we disable (don't apply) user namespace mappings when --privileged is passed, so we can have privilege mean the same whether user namespaces are in use or not?

**Comment by mrunalp** [comment]
@estesp @crosbymichael @LK4D4 ping

**Comment by coolljt0725** [comment]
+1 for this, if use the `--userns-remap`, we can't access to the device add by `--device` on `docker run/create`, I think we should add a flag on `docker run/create` to disable user namespace mapping

**Comment by rhatdan** [comment]
Yes --privileged should mean disable all container separation including user namespace.

**Comment by rhatdan** [comment]
If  you want to disable some separation then you need to do

--securityopt label:disabled
or

--cap-add all

But --privileged should mean root==root

**Comment by LK4D4** [comment]
This was fixed as far as I know.

**Comment by ziermmar** [comment]
How was this fixed? I don't seem to be able to use privileged mode with user namespaces on the latest stable release yet.

**Comment by thaJeztah** [comment]
@ziermmar running `--privileged` on a container with userns enabled will never work (because the container's user doesn't have privileges on the host), that will never change as that's the _intent_ of running with userns enables.

However, https://github.com/docker/docker/pull/20111 allows you to disable userns remapping for a single container, so that you can start a privileged container if userns is enabled on the daemon. That was previously not possible, and is implemented by https://github.com/docker/docker/pull/20111

**Comment by ziermmar** [comment]
Ah, thanks for clearing that up! In my case, I was just missing ```--userns=host``` for the container I wanted to run in ```-privileged``` mode.
