### ISSUE TITLE
Driver btrfs failed to remove root filesystem when base container is based on old version of docker

### ISSUE THREAD

**Issue by dunnock** [docker/docker#17429]
Dear Docker Team,

I have a issue with my autobuild based on latest version of Docker: https://hub.docker.com/r/dunnock/rails-nginx-unicorn/builds/bxorz86zhddgyhbiy7r3czj/

Steps:
1. Inherit container from seapy/rails-nginx-unicorn-pro built with docker 1.6, for instance take the following Dockerfile https://github.com/dunnock/rails-nginx-unicorn
2. Build with docker 1.8, that will fail with the error:

```
Status: Downloaded newer image for seapy/rails-nginx-unicorn-pro:v1.0-ruby2.2.0-nginx1.6.0
 ---> 1acbaca9130c
Step 1 : MAINTAINER ChangHoon Jeong <iamseapy@gmail.com>
 ---> Running in 582f16619b4c
 ---> 8cbd6724c69e
Error removing intermediate container 582f16619b4c: Cannot destroy container 582f16619b4ccf4896f30f3d3d9aa6647a9c1059b922e86c954f17622e213146: Driver btrfs failed to remove root filesystem 582f16619b4ccf4896f30f3d3d9aa6647a9c1059b922e86c954f17622e213146: Failed to destroy btrfs snapshot: operation not permitted
```

Docker Hub automated build is reporting different issue
```
open /var/lib/docker/btrfs/subvolumes/ab960f0cf2707d3625e7635aa7cbd50c57e2c141529b3e99757c64758b4ad305/.wh..wh.plnk/350.689914: no such file or directory
```

To resolve this I had to build new base container instead of seapy one.

Thanks,
Maxim

**Comment by thaJeztah** [comment]
ping @tonistiigi I think you've been working on issues around these files

**Comment by tonistiigi** [comment]
The error from the automated build appears because this old image contains `.plnk` files that shouldn't be there. Unfortunately there's no better fix for that than rebuilding the base image. There's an attempt to show a better warning in #16774 and eventually pulls of such images should just fail. These files are not put in the images in the last versions or docker(at least `1.7`).

For the btrfs error, I'm not sure if its related. Need to test that separately.

**Comment by dunnock** [comment]
Thanks! I've reported to the owner of the base image.

**Comment by thaJeztah** [comment]
Thanks @dunnock, and thanks for reporting!
