### ISSUE TITLE
Docs - Incorrect Link for https://docs.docker.com/misc/

### ISSUE THREAD

**Issue by fauzanariffin** [docker/docker#17439]
Hi,

For the page, https://docs.docker.com/misc/,
Section **'About this guide'** the link to **'Understanding Docker section'** is incorrect.
The correct link is https://docs.docker.com/introduction/understanding-docker/

**Comment by tophj-ibm** [comment]
Looks already fixed in this commit. The website hasn't updated yet.

8fee1c2020186ac100b45e64864b94ae3a169ad5

**Comment by thaJeztah** [comment]
@fauzanariffin @tophj-ibm thanks for reporting, and correct, I tested this morning and this has been fixed; the docs.docker.com website will be updated together with the 1.9 release.

Thanks again! I'm going to close this issue because this has been fixed, but feel free to comment here after I've closed the issue :+1:
