### ISSUE TITLE
Support cpio archive format

### ISSUE THREAD

**Issue by piranna** [docker/docker#17484]

**Comment by piranna** [comment]
Allow to use cpio(.gz) files to initialice a docker container. Besides the file format, the behaviour would be the same as with tar files.

**Comment by thaJeztah** [comment]
Is this for docker import/export, save/load?

**Comment by piranna** [comment]
Yes, but mostly for import. cpio is the format used by Linux kernel initram.

**Comment by unclejack** [comment]
Adding support for `cpio` would be quite involved because there's no maintained `cpio` Go package right now. Adding cpio support using the `cpio` command seems quite simple, but this requires implementing support for cpio throughout the Docker code, writing tests and doing maintenance over time.

`cpio` is used less than tarballs and I don't think it's worth the effort. There are many other improvements to make and issues to fix before implementing something like this.

Is there a reason behind not extracting the cpio archive somewhere, creating a tar archive and importing that? I think this could even be done using a Docker container which accepts a cpio archive on stdin and pipes out a tar archive on stdout. This is simple enough to implement today and it's much easier than implementing `cpio` support for `docker import` and `docker export`.

I'll close this for the time being for the following reasons:
- this ca be easily achieved using a Docker container which converts cpio archives to tarballs and tarballs to cpio archives
- this isn't a feature which has been requested before, it has only been requested once
- cpio archives are less popular than tarballs and they're used mostly for the kernel initramfs
- the effort required to implement and maintain the code for this feature would outweigh the gain of having this feature

Please feel free to comment. This feature request can be opened again.
