### ISSUE TITLE
docker command hangs when detaching with ctrl+p+q when --rm flag. 

### ISSUE THREAD

**Issue by askb** [docker/docker#17516]
docker command does not respond while exiting using `<ctrl+p>` and `<ctrl-q>` and when container is run with `--rm` flag.  

```
docker version:
 docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   b92fd9f-dirty
 Built:        Thu Oct 29 17:15:32 UTC 2015
 OS/Arch:      linux/amd64

docker info:
docker info
Containers: 31
Images: 61
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 67
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-65-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 24.861 GiB
Name: gst-srv211
ID: 72OY:23OP:RSV2:T5II:DWX2:2U4L:OSOK:Q5TW:S5SV:QD5Y:FH5L:SNXM
Debug mode (server): true
File Descriptors: 27
Goroutines: 50
System Time: 2015-10-30T10:17:54.8029752+05:30
EventsListeners: 0
Init SHA1: 
Init Path: /home/abelur/repos/docker-fork/bundles/1.9.0-dev/binary/docker
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```

uname -a:
Linux srv-vm 3.13.0-65-generic #105-Ubuntu SMP Mon Sep 21 18:50:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
1. docker run --rm -it ubuntu:14.04 bash
2. `ctrl+p+q` ===> to detach from the container 
3. `ctrl+c` ===> Need to send a sigterm to detach successfully
 
Note: Repeat the above steps without the `--rm` flag, which results in a expected behaviour. 

Describe the results you received:
We need to send a `ctrl-C` (sigterm) every time a container is started with `docker run --rm` or `--rm=true`. The flag works as expected which removes the container upon `exit` cmd, but the detach is does not work. 
  
```
 docker run --rm=true -it ubuntu:14.04 bash
root@65c55637d6e8:/# 

^C
```

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                 CREATED             STATUS              PORTS               NAMES
65c55637d6e8        ubuntu:14.04        "bash"                  14 seconds ago      Up 13 seconds                           silly_borg

``` 

Describe the results you expected:
* The container should not go to hang state as it would impact the application running within the container (happens occasionally). 
* Container should detach gracefully without the user requiring to provide `ctrl-c` every time. This helps in automating while running tests. 
* At-least to notify the user/admin a deviation from expected behaviour: "Warning: container `<id>` running, not exited" OR "Warning: Container `<id>` not exited on `--rm`, detached on user input `ctrl+p+q`" 

Edit: I have update the issue to avoid confusion on the issue.

**Comment by phemmer** [comment]
This is happening because `docker run --rm` is a client side option. So when you `CTRL+P` `CTRL+Q`, you're detaching, so that no further IO is passed between the client and container, but the client still has to wait for the container to exit so that it can remove it. The container is not actually hung. It's still running normally, you're just not seeing the output.
When you `CTRL+C` the client at this point, you're telling it to stop waiting. But since your `CTRL+P` `CTRL+Q` detached, it can no longer send signals to the container (well it can, this would defeat the point of the detach).

There has been talk of moving container cleanup (`--rm`) to the server side. This would make the `CTRL+P` `CTRL+Q` operation drop you back at the terminal without waiting.

> The container should not go to hang state as it would impact the application running within the container (happens occasionally).

See above, container not actually hung.

> Docker container should be removed upon `ctrl+p+q`, as the container was started with `--rm`.

I don't don't think this is intuitive. `CTRL+P` `CTRL+Q` is meant to detach from the container. If you want to kill it, you should be using `CTRL+C` (or something meant to kill, not detach).

> Container can be exited gracefully and removed instead of the user needing to do `ctrl-c` every time. This helps in automating while running tests.

I'm not sure what you mean by this one. The container can still exit gracefully. If the container exits on its own, without having to send it a signal, or killing it, you don't need to do `CTRL+C`.

> At-least print a warning message if the container is removed, notify the user/admin a deviation from expected behaviour: "Warning: Operation unsupported as container run with --rm=true flag, removing container on exit" OR "Warning: Container not exited on --rm, still running as a result of user input ctrl+p+q"

I'm not sure about this one either. "At-least print a warning message if the container is removed", why? You provided `--rm`, telling docker to remove the container, why a warning when it does so?
Did you mean print a warning when not removed? Such as when you do the `CTRL+P` `CTRL+Q` `CTRL+C`? This I would probably agree with.

&nbsp;

Now, having said all that, there is a way to ensure this container does actually get removed. This is a technique I use almost everywhere that I have a script running a container:

```
(
  cid="$(docker run -tid myimage)"
  trap "docker rm -fv $cid" EXIT
  docker attach $cid
)
```

This will force the shell to call `docker rm -fv $cid` when the subshell (everything between the `()`) exits.
It's a lot more reliable than `docker run --rm`, as the only way to prevent the `docker rm` is if the shell receives a SIGKILL.

**Comment by thaJeztah** [comment]
Thanks for the extensive answer, @phemmer!

Does this answer your question, @askb?

**Comment by thaJeztah** [comment]
btw, that is a nice way of handling the remove, @phemmer; if we ever create a tips & tricks section in the documentation, remind us of including that!

**Comment by askb** [comment]
@phemmer thanks for update. As mentioned I am unable to reproduce application hang presently, which can be ignored for this issue. The issue is more to do with the usability of the command and may not be related to the container or daemon.

> I'm not sure about this one either. "At-least print a warning message if the container is removed",  > why? You provided --rm, telling docker to remove the container, why a warning when it does so?
> Did you mean print a warning when not removed? Such as when you do the CTRL+P CTRL+Q     > CTRL+C? This I would probably agree with.

Yes, Its ok and expected as the container does not get removed, as its the whole purpose of using `CTRL+P+Q`, to detach from the running container. It best to print a warning message when container NOT removed and session is detached.


> I'm not sure what you mean by this one. The container can still exit gracefully. If the container exits > on its own, without having to send it a signal, or killing it, you don't need to do CTRL+C.
The docker command (not the container itself) goes to wait state indefinitely though both the daemon and client are running on the same host, prompting the user to `ctrl+C` (after waiting for long time, actually overnight) and does not return to the bash prompt on the host OS without the `SIGTERM`. 

> I don't don't think this is intuitive. CTRL+P CTRL+Q is meant to detach from the container. If you     > want to kill it, you should be using CTRL+C (or something meant to kill, not detach).
> Also, the --rm option does not mean "kill my container", it means remove it once it exits. Subtle,      > but important distinction.

Agree on this point.

> This is happening because docker run --rm is a client side operation. So when you CTRL+P      
> CTRL+Q, you're detaching, so that no further IO is passed between the client and container, but 
> the client still has to wait for the container to exit so that it can remove it.

The docker client goes into an indefinite wait, therefore its more a dead lock situation in the command, as it does not "gracefully detach" but waits, nor able to reinstate the session from the same terminal.  At-least, the detach should happen successful without the need for the user needing to send a sigterm. If you run the container without `--rm` option, this issue does NOT occur and the behaviour of the detach is different.

**Comment by askb** [comment]
@phemmer @thaJeztah Thanks, I have updated the original issue in question.
