### ISSUE TITLE
Docker remote API with TLS not work  on auto signed CA

### ISSUE THREAD

**Issue by sebglon** [docker/docker#17520]
I followed the site https://docs.docker.com/articles/https/
but at the end , docker --tlsverify ps  return an erro 
```
An error occurred trying to connect: Get https://xxxxx/v1.20/containers/json: x509: certificate signed by unknown authority
```

If i test the same URL with CURL:
curl https://xxxxx/images/json   --cert ~/.docker/cert.pem   --key ~/.docker/key.pem   --cacert ~/.docker/ca.pem

it return Json info.

How can i use TLS conf with auto signed CA?

**Comment by thaJeztah** [comment]
What is the exact command you're using for `docker ps`? I think you'll have to set all options here, e.g. something like;
```
docker --tlsverify --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem  -H=<your-docker-host-ip>:2376 ps
```

Or set the environment variables `DOCKER_TLS_VERIFY`, `DOCKER_HOST`, `DOCKER_CERT_PATH`

There may have been made some changes to that document, that are not yet visible on the website, so it may be worth trying the latest version on GitHub; https://github.com/docker/docker/blob/master/docs/articles/https.md

Let me know if that helps, otherwise I'll check the whole procedure to check if there's an issue

**Comment by sebglon** [comment]
I have tested with twice
``` 
docker --tlsverify --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem  -H=<your-docker-host-ip>:2376 ps
```
and ```DOCKER_TLS_VERIFY, DOCKER_HOST```

But my Docker server is under nginx proxy and i hve made the same pem file on my nginx 
i followeb this site: http://blog.james-carr.org/2013/10/30/securing-dockers-remote-api/

**Comment by thaJeztah** [comment]
In order not to complicate things, I really suggest to get it running without using a proxy first, and work from that.

Please keep in mind that the github issue tracker is for reporting bugs, feature requests and pull requests, and not a general support forum. This question is probably better asked in the #docker IRC channel, or the Docker-Users mailing list on Google groups

**Comment by LK4D4** [comment]
Closing as not an issue
