### ISSUE TITLE
Proposal: API version 1.110

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#17521]
This may seem silly, but I'm going to throw this out there and maybe somebody will have a better idea.  I have to support Docker versions 1.6 to current.  So our code base gets a bit hairy because we use API 1.18 for the most part and then in places where we need new functionality we switch to the right API version, like 1.20.  This really hurts my head.  Docker 1.6 is API version 1.18, 1.7=1.19, etc.  Since those two numbers are always bumped in sync, I'd love it if they were easier to correlate.  So I'm proposing that Docker 1.10 be API version 1.110, 1.11=1.111, 1.12=1.112.  Then I don't have to remember to subtract 12 from API version to get Docker version or vice versa.

**Comment by phemmer** [comment]
Pulling from discussion in #16764

Why are they not the same? Why does docker 1.9.x not use API 1.9?
* API version would never be ahead of docker version, as changing the API requires changing docker itself.
* If the API doesn't change between docker versions, the API can keep the older version number. E.G. Docker 1.9.0 could use API 1.8.0.  
And would this really ever happen? Would there ever be a minor release that doesn't change the API?

Granted, implementing this would be a problem since the current API version is 1.20, while the current docker version is 1.8.
We could use version the APIs from here on as 1.8=>1.20.8, 1.9=>1.20.9, etc until they catch up to each other. But this does feel awkward.
Time for docker 2.0! :-)

**Comment by ibuildthecloud** [comment]
Following Linus Torvalds logic this would be a perfectly valid reason to create Docker 2.0 :smile: 

I think 1.20.9 is not that bad.  At 3 releases a year by 2019 we could release 1.21.

**Comment by calavera** [comment]
Sorry, we're not going to do this.
