### ISSUE TITLE
Volume not mounted

### ISSUE THREAD

**Issue by CyborTronik** [docker/docker#17553]
using docker version: ```1.8.3, build f4bf5c7``` in OpenSUSE 13.2

when I run ```docker run -v /var/tmp/databases/registry:/var/lib/postgresql -it --name postgres postgres:9.3 ```

Then volume is not mounted.
```
:~> docker inspect -f '{{ .Volumes }}' postgres
<no value>
```

**Comment by calavera** [comment]
The volume is mounted. The inspect format is incorrect. We removed that `.Volumes` in docker 1.8, if I remember right. Try `{{ .Mounts }}`, it gives you more information than `{{ .Volumes}}` used to give:

```
➜  docker run -v /var/tmp/databases/registry:/var/lib/postgresql -d --name test alpine top
cfb80b95e6523c3480e9ba0835c62b6f900bbd0bc6bf3c857116bbe3ce247dc9
➜  docker inspect -f '{{ .Volumes }}' test
<no value>
➜  docker inspect -f '{{ json .Mounts }}' test
[{"Source":"/var/tmp/databases/registry","Destination":"/var/lib/postgresql","Mode":"","RW":true}]
➜ 
```

There is more information about that field in the docs:

https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.20.md#create-a-new-image-from-a-containers-changes

I'm going to close this issue since it's not really a problem. Thanks for checking it.
