### ISSUE TITLE
Upgrade Documentation to include changes with SystemD for Ubuntu/Others

### ISSUE THREAD

**Issue by burhan** [docker/docker#17586]
Please refer to #17205 

The documentation should be updated to differentiate between SystemD and normal init scripts when configuring changes to the startup options for docker.

**Comment by zelahi** [comment]
#dibs

I can get started and work on this issue

**Comment by thaJeztah** [comment]
Thanks @zelahi ! When working on this, try not to duolicate information that's already covered in https://docs.docker.com/articles/systemd/. There is also documentation in this page; http://docs.docker.com/articles/configuring/, however the [RHEL/CentOS section](http://docs.docker.com/articles/configuring/#configuring-docker-1) needs to be updated, because that wrongfully mentions that `/etc/sysconfig/docker` is still used, but that's no longer the case.

Feel free to ask me or @moxiegirl for assistance on your PR when needed

**Comment by zelahi** [comment]
Awesome. Thanks @thaJeztah 

I'll get to it and will for sure reach out to @moxiegirl  for assistance. Thank you guys for all you help

**Comment by zelahi** [comment]
I'll get started on this now as I finished working on the other issues I had open =)
