### ISSUE TITLE
awslogs driver support for variables using template markup in awslogs-stream

### ISSUE THREAD

**Issue by CameronGo** [docker/docker#17747]
This is a feature request to allow the use of specific variables or the template markup syntax when specifying the awslogs-stream option.  The current implementation allows you to use a static value for awslogs-stream or else by default it uses the long container ID.  The container ID alone can be difficult to trace and associate with a specific host, so I would like to be able to specify get both the docker hosts hostname along with the short container ID using something like the following:
docker run --log-driver=awslogs --log-opt awslogs-region=us-east-1 \
--log-opt awslogs-group="hello-world" \
--log-opt awslogs-stream="$HOSTNAME-{{.ID}}" \
hello-world

docker version:
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

docker info:
Containers: 8
Images: 2
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 18
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 992.5 MiB
Name: chlorine
ID: DG52:Y3T4:2BGU:HRHN:TVQK:IFII:X26U:V733:VHX3:YU7Z:ZSRC:4UQI

uname -a:
Linux chlorine 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment:
AWS EC2 Container Services running on custom Ubuntu AMI with ecs-agent container.

**Comment by ianneub** [comment]
@samuelkarp I also want this feature, so I started to look at how it could be implemented. The other loggers use the function `loggerutils.ParseLogTag` in order to render the user provided template. Unfortunately this function will work only with the logger config option named `tag`, and will not check `awslogs-stream`.

Here is the relevant portion of the awslogs driver:
https://github.com/docker/docker/blob/692bfdaee3b48f4e5174bb80098692a0ded1aecf/daemon/logger/awslogs/cloudwatchlogs.go#L92

This shows how the `syslog` driver uses `loggerutils.ParseLogTag`:
https://github.com/docker/docker/blob/692bfdaee3b48f4e5174bb80098692a0ded1aecf/daemon/logger/syslog/syslog.go#L65

And here is the source for `loggerutils.ParseLogTag`:
https://github.com/docker/docker/blob/692bfdaee3b48f4e5174bb80098692a0ded1aecf/daemon/logger/loggerutils/log_tag.go#L14

What do you think a good way to handle this situation would be? Here are some ideas:

1. We can change the config option `awslogs-stream` to `tag`.
2. We can also allow a user to specify `tag` which will overwrite `awslogs-stream`.
3. We can rewrite `loggerutils.ParseLogTag` to allow specifying the option name to use.
4. We can write/duplicate the `loggerutils.ParseLogTag` code inside awslogs driver and hard code it to use the `awslogs-stream`.

What do you think?

**Comment by samuelkarp** [comment]
@ianneub, thanks for pinging me.

Of your ideas, I'd lean toward number 3.  Tags have a [different meaning for many AWS resources](https://aws.amazon.com/blogs/aws/resource-groups-and-tagging/), so I'd prefer to avoid introducing the potential for confusion.

**Comment by jhovell** [comment]
+1 

I'd also add the ability to use log tags in awslogs-group as well as awslogs-stream.

Are there any known workarounds for this limitation? Given awslog-streams should be unique per running container, I don't see any way to effectively override awslogs-stream.

ECS task definitions don't really have enough context to specify log groups / streams effectively (e.g. you likely want different log groups for different environments or stacks)

**Comment by CameronGo** [comment]
This one has been quiet for a while.  I see a version/1.9 label applied, though I don't see any comments in that or any subsequent releases about this functionality.  The documentation doesn't seem to indicate any different behavior for the awslogs driver and my test using the log-opt tag on version 1.10.1 is not supported with the awslogs driver.  Does anyone know what the status is or future plans?

**Comment by cpuguy83** [comment]
@CameronGo This would most likely have to be coded up by someone who wants this feature.
Right off the bat, I can say the syntax is not likely to be accepted, but I do believe we have support for go-template thin these options, and that would be the place to start.

**Comment by PeterRJones** [comment]
+1 for this feature

**Comment by mgpotter** [comment]
+1 for this feature

**Comment by samuelkarp** [comment]
@CameronGo @jhovell (any anyone else using ECS) We just added the ability to specify a stream prefix in the ECS task definition as `awslogs-stream-prefix` (the full stream name ends up being `$prefix/$container-name/$task-id`).  See [this blog post](https://aws.amazon.com/blogs/compute/centralized-container-logs-with-amazon-ecs-and-amazon-cloudwatch-logs/) and [our documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html) for details.

**Comment by thaJeztah** [comment]
@samuelkarp @CameronGo https://github.com/docker/docker/pull/27707 was merged, does that satisfy this feature request?

**Comment by samuelkarp** [comment]
@thaJeztah Yes, I believe so.

**Comment by thaJeztah** [comment]
Thanks @samuelkarp, I'll go ahead and close this issue, but @CameronGo let me know if there's still something that needs to be addressed 👍

**Comment by CameronGo** [comment]
Thanks @thaJeztah - yes that is working and fits my needs.  Thanks for checking!

**Comment by thaJeztah** [comment]
Good to hear @CameronGo!

**Comment by hjochums** [comment]
Sorry, but this is not really fixed. Im using the prefix, and its alot better. thx!.

But i still got about 12 log streams, because they a grouped by the service ID.

DOMAIN/stage-DOMAIN/273ac3de-0bca-4bee-a35b-9e0206009380
DOMAIN/stage-DOMAIN/324c52f3-0f5c-4063-8b03-b490885aef3c
DOMAIN/stage-DOMAIN/355251f2-4e7f-4837-86c5-f2f187bf509c
DOMAIN/stage-DOMAIN/4cbd1975-3aad-46e5-a8bd-3241f2233bd0
DOMAIN/stage-DOMAIN/5cc3307b-c5ac-4f1c-9421-f2d2f1f9b0f6
DOMAIN/stage-DOMAIN/62b4cccf-c4a6-474e-8478-58912977168f
DOMAIN/stage-DOMAIN/71e60952-ce6d-4f8b-a901-445b811f6165
...

In an debugging situation, i need to click on all stream to find the error..

**Comment by ozbillwang** [comment]
@ghost 

could you share the `docker run` command and docker version?

I did the same as `--log-opt awslogs-stream="$HOSTNAME-{{.ID}}"`, but I didn't get the docker container id properly.

Here is my log stream name:

```
ip-10-0-2-123.ap-southeast-2.compute.internal-{{.ID}}
```
