### ISSUE TITLE
Upgrading breaks apt-get and docker daemon

### ISSUE THREAD

**Issue by jaredbroad** [docker/docker#17811]
Setup:
 - Upgrading docker from 1.7 -> 1.9,
 - Ubuntu 15.04,
 - Containers folder had 400GB of previous containers,

Error:
 - During the installation process there is a step: "Migrating existing containers"
 - This takes too long with so many containers and installation times out but looks successful.
 - Docker is half installed and get a strange "Invalid arguments" error message from the docker.service logs.

Tried:
 - Trying to apt-get purge lxc-docker fails as it keeps trying to finish installing docker. Tried everything - autoclean, autoremove, apt-get remove, 

Successful:
 - 1. Doing a manual  rm -rf /var/lib/docker, and 2. rebooting, and 3. finish the aufs folder off with the same command:  rm -rf /var/lib/docker

- Finally -- apt-get install docker-engine ---- success! :)

Feel free to close immediately, just wanted to make sure the dev team read this.

**Comment by tonistiigi** [comment]
This can't have anything to do with content addressability as it was just merged couple of days ago.

The message "Migrating existing containers" comes from aufs migration. This migration step is actually very old(pre 1.0) so unlikely that it ever runs, but message is always shown. We should fix the message to avoid confusion.

I'm not aware of any other migration process running on upgrade that could take more time based on the amount of containers. I'm bit confused because "Migrating existing containers" is a message in the daemon logs not during installation.

**Comment by thaJeztah** [comment]
@tonistiigi sorry, for the confusion, I was cc-ing you here, because we were discussing the migration process to the new content addressability, and thought we should prevent that users end up with the same problems as described here

**Comment by tonistiigi** [comment]
@jaredbroad If you have full logs, either from failed installation or failed daemon start, please post them here.

**Comment by jaredbroad** [comment]
Sorry it was too long ago I don't have them saved. The logs weren't helpful though - they didn't show anything other than what I mentioned above. You can see log snippets from my post here: https://github.com/docker/docker/issues/16819

My hunch about the bad install was because every time I tried to remove docker with apt-get it would first try and finish the installation.

**Comment by calavera** [comment]
I'm going to close this seems we're unable to reproduce. Please feel free to reopen if we get more information.
