### ISSUE TITLE
Symlink Mounting Behaviour Changed

### ISSUE THREAD

**Issue by mafopen** [docker/docker#17837]
After updating a development machine from 1.4.1 to 1.9.0 (yes, it's been a while), I have noticed that there have been changes in the behaviour how mounted volumes behave when using a symlink.

With the old version, restarting a container resulted in the symlink being reevaluated, the latest version keeps using the location where the symlink pointed at the time of container creation.

It's just a suspicion, but I think that this might have been changed by the commit in pull request https://github.com/docker/docker/pull/3566, fixing issue https://github.com/docker/docker/issues/3262.

**Comment by imikushin** [comment]
@mafopen Not completely sure it's the same issue, but (from https://github.com/rancher/os/issues/641#issuecomment-155803662):

When we're running a container, bind-mounting our binary (say, `/usr/bin/ros`) to a location which is a symlink in the container's image (perhaps, pointing to some other binary in the image, say, `/bin/busybox`), that symlink isn't replaced with the bind-mounted binary, but instead, the symlink's target is replaced. 

To illustrate: 
```
# docker run --name=alpine-crash -it -v /usr/bin/ros:/sbin/poweroff alpine /bin/sh
FATA[0000] Failed to find an entry point for /bin/sh    

# docker run --rm -it -v /usr/bin/ros:/sbin/qqqqq alpine /bin/sh
/ #
```
In the first example, `/sbin/poweroff` is a symlink to `/bin/busybox`, so when we bind-mount `/usr/bin/ros` into the container, `/bin/busybox` is in fact replaced (bind-mounted to) by `/usr/bin/ros` (and that's why we're seeing the error message from `ros`) while the symlink `/bin/sh` is still there and happily points to `/bin/busybox` :grinning: 

Of course `docker inspect alpine-crash` doesn't show us the truth:
```
    "Mounts": [
        {
            "Source": "/usr/bin/ros",
            "Destination": "/sbin/poweroff",
            "Mode": "",
            "RW": true
        }
    ],
```

**Comment by imikushin** [comment]
The bug "works" for docker versions 1.8.0-1.9.0, at least.

**Comment by ibuildthecloud** [comment]
@imikushin So you are saying 1.8 and 1.9 will both resolve the symlink to the target?  But 1.7 does not?

**Comment by ibuildthecloud** [comment]
I believe the issue here is that symlinks need to be resolved for directories, not files.  The original change was so that if you have `ln -s /run /var/run` in your container and you did `-v /blah:/var/run/blah` you need to create a bind mount at `/run/blah` not `/var/run/blah` because of symlinks.  The behavior should change here.

I think the correct behavior is if the target is a symlink to a file then the parent directory of the target should be resolved and the bind mount should be created there.  So if the target is a symlink in bash-foo we should do.

```bash
mount --bind ${src}:$(readlink -f $(dirname ${dest}))/$(basename ${dest})
```

**Comment by imikushin** [comment]
@ibuildthecloud I'm not saying 1.7 isn't affected. I just know 1.8 and 1.9 are.

**Comment by imikushin** [comment]
@ibuildthecloud I think, the correct term for the programming practice with bash is "bash fu": like kung fu, only using bash :panda_face: 

I think, the ideal behaviour (the least surprise for the user) would be to replace whatever file (regular, directory, symlink or other) in the container with the bind mounted from the host. Not sure if that's possible, though.

**Comment by mafopen** [comment]
I don't think this is the same issue.

From what I understand, your problem is that symlinks are followed for a mount target. In my case the problem is that symlinks for the mount source are only evaluated at docker creation, but not restart.

```
ln -sfn /var/old /var/symlink
docker run --volume /var/symlink:/var/data -w /var/data container
```
Now the docker container's working directory is ``/var/old`` on the host machine.

```
ln -sfn /var/new /var/symlink
docker restart container
```
Now I'd expect the working directory to be ``/var/new`` but it is still ``/var/old``.

**Comment by mafopen** [comment]
I just tested this (https://github.com/docker/docker/issues/17837#issuecomment-156037838) with a clean install on 1.7 and 1.9, but I was not able to reproduce it (i.e., both versions work as expected).

I will close this issue, while I'm digging deeper, and reopen if required. @imikushin, feel free to reopen for your problem.
