### ISSUE TITLE
Using `run` with `--rm` deletes volumes created with `docker volume create`

### ISSUE THREAD

**Issue by metasim** [docker/docker#17907]
# Bug Report Information

## `docker version`

```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64
```

## `docker info`

```
Containers: 0
Images: 6
Server Version: 1.9.0
Storage Driver: devicemapper
 Pool Name: docker-8:2-3222770360-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 545.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 106.8 GB
 Metadata Space Used: 1.004 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 8
Total Memory: 23.38 GiB
Name: x.y.z
ID: MMMV:B5GR:6NIY:ODB7:OV7U:BVJE:VPLR:I56P:D34C:CKKG:ECKU:EWSC

```

## `uname -a`

```
Linux x.y.z 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Steps to reproduce:

1. Create a volume with the new `volume` command:

```
docker volume create --name hello
> hello
docker volume ls
> DRIVER              VOLUME NAME
> local               hello
```
2. Then "mount" it:

```
docker run --rm -it -v hello:/world busybox sh
/ # touch world/foobar
/ # exit
```

3. Then look for volume:

```    
docker volume ls
> DRIVER              VOLUME NAME
```

This seems dangerous behavior given that volumes are considered the persistent component of the system.

----------END REPORT ---------

**Comment by cpuguy83** [comment]
dup of #16809

**Comment by thaJeztah** [comment]
@cpuguy83 I think it may be worth exploring if we can make a distinction between volumes created via `docker volume create`, and volumes implicitly created by `docker run`.

**Comment by cpuguy83** [comment]
Why have a volume if it's not going to persist?

**Comment by phemmer** [comment]
@cpuguy83 it may be baked into the image. You get it whether you want it or not.

**Comment by cpuguy83** [comment]
IMO, volumes exist because they are important and are meant to live beyond the life of a single container.
With the current behavior, I still have to have a non-running container holding a reference to a volume to make sure I don't lose it... which defeats the goal of volume management.

Unwanted inheritance from an image is 2nd fiddle to not losing important data, and a separate issue.

**Comment by thaJeztah** [comment]
My thought is that, if I *explicitly* create a volume (`docker volume create`), before running a container that mounts that volume (with `--rm`) should not remove the volume, because the container is not the "owner" of that volume.

On the other hand, if a one-off container is started that itself creates the volume, the container is "owner" of that volume, so should be allowed to remove it.

Just my thoughts, perhaps I'm looking at it in the wrong way.

**Comment by phemmer** [comment]
@thaJeztah that's exactly how I would expect it to behave.

**Comment by metasim** [comment]
@thaJeztah, @phemmer:  ditto

**Comment by thaJeztah** [comment]
ping @calavera @duglin (because you were in the previous discussion)

**Comment by villlem** [comment]
There is one possible workaround.
Volumes that are used are not removed. So when I create volume that I need to keep around I create container that uses it. I'm currently experimenting with that workaround.

**Comment by mbentley** [comment]
@villlem - While that works, it is cumbersome and actually can make it easier to accidentally delete a volume when you're just trying to utilize a volume that might already exist if you forget to create a container.

I have no clue what sort of effort would be required to add some sort of locking facility, such as a toggle that can be set to allow the volume to be removed automatically (default; what we have now) or prevent deletion automatically.  I think it would be great to be able to enable this at creation time and modified as necessary to allow deletion when ready.  Thoughts on that sort of approach?

**Comment by villlem** [comment]
@mbentley It is cumbersome. I don't like this too. But with some care/automation it works. And it prevents accidental deletion of volume. Without this I force my self not to use `--rm` at all.

**Comment by xlgao-zju** [comment]
@thaJeztah agree with you!

**Comment by marcelhuberfoo** [comment]
I agree with @mbentley and also think that just keeping a container to reference the volume as @villlem proposed is cumbersome. 

For me it seems too that `docker run --rm` somehow implicitly does like a `docker rm -v` as @mbentley mentioned too.

Currently I use the following workaround where I still cleanup the data-loading container but have the volume still available (it's tedious I know):
~~~{.bash}
docker volume create --name hello
> hello
docker volume ls
> DRIVER              VOLUME NAME
> local               hello

docker run --name fillhello -it -v hello:/world busybox sh
/ # touch world/foobar
/ # exit

docker volume ls
> DRIVER              VOLUME NAME
> local               hello

docker rm fillhello
>fillhello

docker volume ls
> DRIVER              VOLUME NAME
> local               hello

sudo ls /var/lib/docker/volumes/hello/_data
>foobar
~~~

**Comment by villlem** [comment]
@marcelhuberfoo if it works for you, that's great. But for me it's greatly error prone. I was trying use of named volumes but I just typing `docker run --rm` accidentally all the time. I create volumes less often than running one-of containers from shell. 

That been said. I don't like this new `--rm` behavior at all. Right now I'm hoping for some sort of @thaJeztah solution or disable this at all. After all I can cleanup dangling volumes later.

**Comment by cpuguy83** [comment]
@villlem I agree, this is terrible (and +1 to removing the functionality), but it's also not new.
It's just that it's really bad functionality when paired with named volumes and real life-cycle management for volumes.

**Comment by marius311** [comment]
Just ran into this, since intuitively I was expecting `docker volume create`'ed volumes to stick around. While I sort of like @thaJeztah's solution since it goes with my intuition, I also realize it would mean that in my head I have to keep track of who the owner of volumes is to anticipate what will happen following any given `docker run --rm` command.

Another idea is instead adding something like `docker run --rm-the-container-but-not-volumes` so that `docker run --rm` behaves the way it always has, and anyone who uses `docker volume create` can train themselves to use the new `--rm-the-container-but-not-volumes` option.

**Comment by calavera** [comment]
> That been said. I don't like this new --rm behavior at all

As @cpuguy83 mentions, this is not a new behavior. It has been the default behavior for a very long time, probably since `--volume` was introduced in docker run back in 2013ish.

I agree that we should not change the `--rm` behavior, because that can break other people's expectations. I don't think we should add a new flag though, because adding flags to implement similar behavior, but not quite the same, is very misleading.

So here comes my proposal, although it might require significant changes:

Make sure the `--rm` logic ignores volumes created with `docker volume create` but preserves it's current behavior for "one-shot-only" volumes. :smile_cat:

Although, the current implementation doesn't allow us to store local volume metadata, it's something that could be really useful, for instance in this case. We could differentiate volumes created with the new management cli from volumes created without it. Once we can differentiate those, we can selectively remove the volumes we really want to remove.

**Comment by cpuguy83** [comment]
@calavera I think we can store these on the container struct for now.

**Comment by mbentley** [comment]
@calavera - I like the approach you suggested; seems easy enough logically to understand without breaking user expectations of current behavior. :+1:

**Comment by thaJeztah** [comment]
I'm +1 to that proposal

> I think we can store these on the container struct for now.

@cpuguy83 but are those persisted on disk? Do we keep that information on a daemon restart?

**Comment by cpuguy83** [comment]
@thaJeztah That's the idea.
So if the volume is not named, and was created by the container, store it in the container struct so that when `rm -v` is used, remove only those.

**Comment by xlgao-zju** [comment]
I think it will be an interesting job to fix this issue. 
So, #dibs

**Comment by jest** [comment]
I wholeheartedly agree with the proponents of keeping the volumes after the removal of the container.

When I read about API and (later) CLI of managing volumes, I thought "finally!" Finally I can sanely manage the data without creating suboptimal data-only containers. I never thought that `docker run --rm` would remove the volumes it hasn't created.

For me, mounting a named volume should work as if `--volumes-from` was used with a data-only container -- at least that's how I interpret manually created volumes.

I give all my thumbs to the solution of @cpuguy83 of removal of volumes that were created with the given container.

**Comment by roderickm** [comment]
Reconciling the sometimes-competing objectives in UX can be difficult. We want intuitive, reliable interfaces while maintaining backward compatibility. The Principle of Least Astonishment may help guide the solution: users report being surprised by persistent volumes that are removed when using `run` with `--rm`, but we want to avoid surprising existing users by changing the behavior of existing deployments.

Data-destructive behavior should be explicit and intuitive. While @calavera's proposed approach would avoid removing volumes created explicitly, it would do so by convention and create another implicit "except-in-the-case-of" rule for new users to learn.

I support a more explicit approach as proposed in #9878. Explicit lock/unlock metadata on volumes would give users confidence that persistent volumes will actually persist. Let `volume create` set the lock automatically, or with an explicit flag like `volume create --lock`. Any attempt to delete the volume before unlocking should fail with a warning to instruct the user to `docker volume unlock` first, or use the `-f` flag to override locks.

**Comment by jest** [comment]
@roderickm proposition sounds reasonable to me

**Comment by metasim** [comment]
@roderickm +1 for **Principle of Least Astonishment** being the driving criterion.

**Comment by pdevine** [comment]
+1 to fixing this.  The current behaviour seems crazy to me.

**Comment by gittycat** [comment]
@metasim Yes call me very astonished. I just ran into this issue. I really thought that I had hit a bug when `--rm` would delete my named volumes but then I found the note in the documentation https://docs.docker.com/engine/reference/run/#clean-up-rm.

Is there a timeline to fix this?

**Comment by cpuguy83** [comment]
@gittycat #19568
