### ISSUE TITLE
bind-mounting to a symlink mount point in a container

### ISSUE THREAD

**Issue by imikushin** [docker/docker#17944]
When we're bind-mounting a file (say, `/usr/bin/ros`) to a location which is a symlink in the container (perhaps, pointing to some other file in the image, say, `/bin/busybox`), that symlink isn't replaced with the bind-mounted binary, but instead, the symlink's target is replaced. 

To illustrate: 

```
# docker run --name=alpine-crash -it -v /usr/bin/ros:/sbin/poweroff alpine /bin/sh
FATA[0000] Failed to find an entry point for /bin/sh

# docker run --rm -it -v /usr/bin/ros:/sbin/qqqqq alpine /bin/sh
/ #
```

In the first example, `/sbin/poweroff` is a symlink to `/bin/busybox`, so when we bind-mount `/usr/bin/ros` into the container, `/bin/busybox` is in fact replaced (bind-mounted to) by `/usr/bin/ros` (and that's why we're seeing the error message from `ros`) while the symlink `/bin/sh` is still there and happily points to `/bin/busybox` :grinning: 

Of course `docker inspect alpine-crash` doesn't show the truth:

```
    "Mounts": [
        {
            "Source": "/usr/bin/ros",
            "Destination": "/sbin/poweroff",
            "Mode": "",
            "RW": true
        }
    ],
```

This was noticed on RancherOS v0.4.0 and master, but "works" as good on other Linux and also on docker-1.9.

`docker version`:

```
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   5eab58c
 Built:        Wed Oct 14 13:42:27 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   5eab58c
 Built:        Wed Oct 14 13:42:27 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:

```
Containers: 1
Images: 1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.3-rancher
Operating System: RancherOS (containerized)
CPUs: 2
Total Memory: 996.3 MiB
Name: rancher-dev
ID: OR2N:QCKU:NVO6:S6LI:NPLR:DBV5:A7ID:C7WK:SZVI:TP6D:TY4J:BAUV
```

`uname -a`:

```
Linux rancher-dev 4.2.3-rancher #1 SMP Wed Oct 14 11:25:04 UTC 2015 x86_64 GNU/Linux
```

/cc @ibuildthecloud

**Comment by LK4D4** [comment]
@imikushin I think it is for not accidentally use symlink which points outside rootfs.

**Comment by imikushin** [comment]
@LK4D4 I'm not sure I'm getting it. 

Also, wouldn't the ideal behaviour (the least surprise for the user) be to bind-mount the host file (or dir) over whatever file (regular, directory, symlink or other) in the container (if necessary replacing it with an empty file or dir)?

**Comment by imikushin** [comment]
@LK4D4 I would like to fix this. Where do I look for the mountpoint resolution code? I've got this patch now, but it apparently doesn't work: https://github.com/imikushin/docker/commit/1d3c1eb8f0d7e412a0b5f3c0d892b2dd3b6f01df

**Comment by LK4D4** [comment]
@imikushin I think here https://github.com/opencontainers/runc/blob/master/libcontainer/rootfs_linux.go#L160

**Comment by crosbymichael** [comment]
I doubt we change how this works because its a sensitive code path and is working as expected.

**Comment by imikushin** [comment]
@crosbymichael Expected by docker users? Let's do a quick poll maybe :wink:

**Comment by imikushin** [comment]
Please retweet: https://twitter.com/imikushin/status/665957621736873985

**Comment by phemmer** [comment]
to throw in some other commentary:
Dereferencing the symlink is how `mount -o bind` behaves. So the current behavior is correct in that regard.
However my personal opinion is that I would prefer it mount on top of the symlink. If symlinks are supposed to (mostly) behave like normal files, that should include mounting on top of them.

Not dereferencing the symlink would be the safer behavior too, as you no longer have to make sure the symlink points outside the jail.

Perhaps a flag? `-v /foo:/bar:L`

**Comment by crosbymichael** [comment]
So how do mounts works with symlinks and what does libcontainer change.  

1. The kernel follows the symlink on the mount syscall. Done... 

Here is the mount syscall in the kernel, and if you see this line, `user_path` gets the kernel path for `dir_name` which is the destination argument to the syscall. https://github.com/torvalds/linux/blob/master/fs/namespace.c#L2672  If you look at the code for `user_path` is defers to a couple of other functions with default args but you will notice that the `LOOKUP_FOLLOW` flag is passed when looking up the path. 

https://github.com/torvalds/linux/blob/master/include/linux/namei.h#L55

Now just for reference we can see the rules for symlinks and what lookup_follow flag does here: https://github.com/torvalds/linux/blob/master/fs/namei.c#L97

2. So what happens in libcontainer?  Because the bind mounts happen before we place the process in a chroot/pivot_root we resolve the link dest inside the container so that the kernel does not resolve it outside as it would do that anyways.  So even if we didn't resolve it, passing that path to the mount syscall will still resolve the symlink and it would probably resolve it outside of the container's filesystem if it was an ABS link and not relative.  Which is bad ;)

3. So what can we do to fix this issue.  The only thing I can think of is to do an `unlink` before calling mount. However, we cannot do that because it modifies the filesystem of the container and changes what is from the image.

So seeing that you are trying to bind mount over `/sbin/poweroff` how about u tell me what you want to do and we can find a solution that fixes your issues in another way?  

Also, lets not do twitter polls ;)

**Comment by fantapop** [comment]
This issue is affecting my team as well. Our use case is that we're mounting in a directory of node_modules during development. One of those modules is optionally npm linked. To allow the mount to work with both a directory and a symlink inside the node_modules directory, we're using fs.realPath to find the actual directory of the module and then mounting that in to where the module is expected on the inside. The module ends up being mounted in at the resolved npm symlink path. This actually works for our purposes on the Linux boxes but osx doesn't handle it well. It complains about too many levels of symlinks even though it's just the one. Maybe it doesn't like that docker inspect had lied about this.

**Comment by justinmchase** [comment]
I'm hitting a similar problem as @fantapop

I am using  version 1.10.3 but my coworker is using 1.12.0 and there seems to be a regression in the way that volume mounting with links works.

I have some npm dependency that I link to for local development and it works for me in the lower version but not in the upper.

For example:

```sh
/code/foo $ npm link
/code/foo $ cd ../bar
/code/bar $ npm link foo
/code/bar $ docker-compose up
```

Then in my docker-compose.yml file I have the following:
```
volumes:
  - ./node_modules/foo:/home/test/node_modules/foo
```

If I just volume link the `node_modules` folder in every case it will fail to resolve the `foo` module. If I just link only the foo module specifically then it works in `v1.10.3` but fails in `v1.12.0`.

Folder linking is a very common way to develop dependent node modules and I'm not sure how to work around this.

**Comment by lukeyeager** [comment]
Why is this labeled as `version/1.8`? I'm still seeing the issue with v1.12.3.

**Comment by thaJeztah** [comment]
the label is automatically applied based on the version it was reported with

**Comment by lukeyeager** [comment]
Oh, got it. I thought it meant a fix was planned for that version. My mistake.

**Comment by imikushin** [comment]
I still would like to fix this, but I need to know what Docker team thinks. 

Just to recap, when you run this:

```
docker run -v /some/local/sh:/bin/sh alpine sh
```

`/some/local/sh` will replace `/bin/busybox` in the container, and `/bin/sh` will remain untouched: it just happens to be a symlink to `/bin/busybox`. Users expect `/bin/sh` to be replaced, **NOT** `/bin/busybox`. The same applies to directories. 

I understand, that to achieve the expected (least surprising for end users) behavior, docker needs to first delete the symlink (the bind-mount target) in the container, then do the usual bind-mount. But I don't see any problem with that.

**Comment by thaJeztah** [comment]
@imikushin we did implement a `--mount` flag for `docker run` and `docker service ..`, which is more "extensible" than the `-v` syntax, which is already overloaded. Perhaps you can write a proposal to add an option to the `--mount` flags (no guarantees, but perhaps maintainers are more open to that suggestion)

**Comment by crosbymichael** [comment]
@tonistiigi have you seen this symlink issue? ;)

**Comment by imikushin** [comment]
@crosbymichael What's so funny about it? I spent **hours** trying to figure out what's going on when I first encountered it a year ago. 

Are there any use cases actually relying on the current behavior? I'd really like to hear about any.

**Comment by crosbymichael** [comment]
@imikushin who said it was funny? @tonistiigi is really good at symlink issues so that is why i'm pinging him to take a peek if he hasn't seen it.

**Comment by tonistiigi** [comment]
First issue is the same behavior as linux(like @crosbymichael already commented):

```
» echo foo > foo
» mkdir a
» echo bar > a/bar
» ln -s a/bar bar
» mount --bind foo bar
» ls -l 
total 8
drwxr-xr-x 2 root root 4096 Nov  8 13:30 a
lrwxrwxrwx 1 root root    5 Nov  8 13:30 bar -> a/bar
-rw-r--r-- 1 root root    4 Nov  8 13:29 foo
» cat a/bar
foo
```

If someone can convince linux to change it we can come back to it.

@fantapop This looks something different. Can you make a new issue with steps to reproduce.

@justinmchase Same thing. From the provided info I can't figure out to structure of the symlinks. If it is a regression, it is likely we can fix it. I don't remember any feature change in this area between 1.10 and 1.12.

**Comment by imikushin** [comment]
@crosbymichael Thanks! I'm looking forward to the resolution.

If deleting the symlinks in the container is not an option, even throwing an error would work. Something like "Error mounting volume to`/bin/sh`, because it is a symlink"

**Comment by imikushin** [comment]
@tonistiigi Thanks for printing this out.
If someone can convince developers to listen to their users... 

The problem in this issue is when you use `mount --bind` on your local filesystem, you can easily know in advance if the mount target is a symlink: `ls -lAh ./bar`

A container, on the other hand, is very often a black box. And read in all freaking docs: the volume will appear at the mount location in the container! Which is simply not the case here.

**Comment by tonistiigi** [comment]
@imikushin If we would change this we would likely break much more users. By resolving the symlink we are consistent with other software and our current users.

Simple example of what we would break is mounting the docker socket `-v /var/run/docker.sock:/var/run/docker.sock`. In most systems `/var/run` is a symlink to `/run` and if we would unlink `/var/run/docker.sock` all applications that use `/run` directly would stop working.

I don't agree with the black box comparison but it's easy to see that the decision why this method was chosen was exactly to simplify user interaction - user should not care that some directories/files are actually symlinks. If you change one it affects the others even if you have no idea some system was using it with another path. All your examples replace the binary correctly so that the destination path points to it. Everything else is just a side effect of the specific image, if you replace a file with an editor is this image it would behave the same way.

Btw, have you tried `docker run -it -v /usr/bin/ros:/usr/local/sbin/poweroff alpine /bin/sh`

**Comment by imikushin** [comment]
@tonistiigi I'm fine with leaving alone `/var/run` being a symlink to `/run` in containers. 

Another story would be if `docker.sock` (the last part of `/var/run/docker.sock`) was the symlink. This is where it gets confusing.

We've found a workaround once we identified what was causing the trouble. But that doesn't make this issue irrelevant.

**Comment by crosbymichael** [comment]
@imikushin regardless, this question should not be directed at Docker because runc handles the runtime and is where this change would take place if accepted. 

You should open a PR/Issue on runc and the maintainers of runc can decide to make the change or not.  

https://github.com/opencontainers/runc

**Comment by imikushin** [comment]
Thanks, @crosbymichael! Will do.

**Comment by crosbymichael** [comment]
Thanks

**Comment by tstibbs** [comment]
Did an issue get raised in runc?

**Comment by robbie-demuth** [comment]
FWIW, it looks like runc explicitly follows symlinks for good reason https://github.com/opencontainers/runc/blob/dbe5acade3d0f84b5c1bd1184b1bbf5a533cdfa1/libcontainer/rootfs_linux.go#L192-L195
