### ISSUE TITLE
Feature request: docker build could have the ability to `--push` 

### ISSUE THREAD

**Issue by askb** [docker/docker#17982]
`docker-build` should be able to `--push` images or individual layers while they are being built to the registry. Each layer once built can be pushed asynchronously (better option) or once the images are built completely.

**Comment by crosbymichael** [comment]
With new image signing and manifest changes its less about layers and more about the image.  Pushing layers will not really help because you care about the result, not the steps.  

The idea does seem pretty helpful but the builder and images are going through alot of changes so, its a simple change but I don't know if it could be added anytime soon.  Will defer to @tiborvass on this because he is working on the builder.

**Comment by askb** [comment]
@crosbymichael @tiborvass I was looking into some of the changes required to implement this and would be happy to help, if no one else has started to work on this yet. Thanks

**Comment by askb** [comment]
#dibs :)

**Comment by LK4D4** [comment]
@tonistiigi Is this still possible?

**Comment by tonistiigi** [comment]
@LK4D4 It's possible but probably not worth it. It's quite narrow use case and very different from how it is currently implemented. The builder code doesn't know anything about pushing and push code doesn't do anything special based on the image source. I think the maintenance cost for these exceptions exceeds the value of this feature. And if we don't run them in parallel I don't see any value from this.

**Comment by LK4D4** [comment]
@tonistiigi Thanks. I'll close this as it requires massive code changes without big profit.

**Comment by manishtomar** [comment]
@tonistiigi Would it be possible to do push using normal technique after the image is built if the option is provided? i.e. basically just call `docker push` after the build is completed. I ask this because many times I've found myself do `docker build ns/repo:tag && docker push ns/repo:tag`. So having `docker build --push repo` will be helpful.

**Comment by tonistiigi** [comment]
@manishtomar buildx https://github.com/docker/buildx now supports `--push` . It is mainly to improve working with multi-platform images but can be used to save typing as well.
