### ISSUE TITLE
Proposal: accept both docker log/logs and docker port/ports

### ISSUE THREAD

**Issue by mrosic** [docker/docker#18007]
At the moment "docker log" and "docker ports" throws an error.
By accepting both "docker log", "docker logs", "docker port" and "docker ports" as valid commands we would make people's lives easier.

**Comment by crosbymichael** [comment]
It would be easier but i don't think many cli apps accept the plural forms of commands just for ease of use.  It would be the same as `git tag` and `git tags`. 

Lets not add these plurals because it would set a precedences for other current and future commands where the non-plural forms may actually be needed and not make sense.
