### ISSUE TITLE
[Proposal]  considering container migration across machines.

### ISSUE THREAD

**Issue by moypray** [docker/docker#18031]
Hi, I saw  the PRs in runc and docker to support container migration using CRIU, that is appreciated.
But the PR only supports migration on one machine.
So I wonder why not support Checkpoint/Restore Containers across machines? And I have this requirement and investigated it too.

**Comment by hqhq** [comment]
Yes that's helpful and necessary, but I'm not sure this is something should be supported by Docker since Docker itself is on one machine, this is more like orchestration work.

**Comment by thaJeztah** [comment]
I agree with @hqhq here; this is something that should be implemented by orchestration software. First we need to have https://github.com/docker/docker/pull/13602 accepted and merged, and work from that.

Thanks for suggesting, though!

I'm going to close this issue, because this won't be implemented as part of docker-engine, but may be possible with orchestration software, once the API is available.
