### ISSUE TITLE
Can not run docker in windows??

### ISSUE THREAD

**Issue by setu1421** [docker/docker#18036]
Docker version:1.9.0
Docker info:An error occurred trying to connect: Get http://localhost:2375/v1.21/info: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the target machine actively refused it.

When i tried to run docker i got this problem:
Starting machine default...
Error setting up host only network on machine start: C:\Program Files\Oracle\Vir                                                                                                                tualBox\VBoxManage.exe hostonlyif ipconfig VirtualBox Host-Only Ethernet Adapter                                                                                                                 #8 --ip 192.168.99.1 --netmask 255.255.255.0 failed:
VBoxManage.exe: error: The host network interface with the given name could not                                                                                                                 be found
VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component HostWr                                                                                                                ap, interface IHost, callee IUnknown
VBoxManage.exe: error: Context: "FindHostNetworkInterfaceByName(Bstr(pszName).ra                                                                                                                w(), hif.asOutParam())" at line 205 of file VBoxManageHostonly.cpp
Looks like something went wrong... Press any key to continue...

**Comment by thaJeztah** [comment]
Thanks for reporting, @setu1421. This looks like a problem with docker-machine / VirtualBox, and is better reported in the docker-machine repository. I did a quick search, and found this issue related to setting up the host-only network; https://github.com/docker/machine/issues/1521 but possibly there are other issues.

I'm going to close this issue here, because this is something that must be resolved in the docker-machine code, not in docker; I suggest to open this issue in that repository (or subscribe to an existing issue there if it exists)

Feel free to comment here after I've closed this issue :+1:
