### ISSUE TITLE
Failed to create the host-only adapter

### ISSUE THREAD

**Issue by kodermax** [docker/docker#18085]
My Os is Windows 7 64-bit
I have the error.
![screenshot_1](https://cloud.githubusercontent.com/assets/590985/11263651/cd703ab0-8e9d-11e5-89d0-0121f12d7ed1.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/590985/11263680/101fc8da-8e9e-11e5-9d19-19c71277000a.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/590985/11263682/11c45570-8e9e-11e5-976b-f465244b5d4a.png)

**Comment by thaJeztah** [comment]
Thanks for reporting @kodermax. This looks to be an issue with docker-machine, could you reopen this issue in the issue tracker for docker-machine, or search for existing issues? I found this one that looks related, but there may be others; https://github.com/docker/machine/issues/1521

I'm going to close this issue, because this is an issue with docker-machine (or a VirtualBox bug), but feel free to comment here after I've closed this issue.

Again, thanks for reporting! It's appreciated :+1:
