### ISSUE TITLE
[Question] How to transition from links to networking?

### ISSUE THREAD

**Issue by schmunk42** [docker/docker#18095]
Currently most of my `docker-compose` files have links, like

```
nginx:
   image: nginx
   links:
      - php:PHPFPM
php:
   image: php
```

With `--x-networking` links are no longer resolved and I need to use something like `myapp_php_1` for the nginx-phpfpm connection.

Is there another way than rewriting `Dockerfile`s or startup scripts to accomplish this?
Eg. could I specify kind of an alias for that?

[edit]
While the example is specific to `docker-compose` the main problem applies also for standard docker-workflows I think.

**Comment by Skarlso** [comment]
After you do the networking stuff, which is easy, all your containers will be available by name from everywhere because they will appear in every containers hosts file.

**Comment by nazar-pc** [comment]
@schmunk42, for names resolution like you need with Docker Compose and networking you'll need DNS service that will provide names resolution to proper IP. Or you can wait till next Compose release, as far as I remember, they'll create shortened aliases in /etc/hosts so that you'll be able to write:
```
nginx:
   image: nginx
PHPFPM:
   image: php
```

I've built set of Docker images that are intended to be used with PHP. As alternative you can try to use them. Consul for DNS resolution is already there, also you can use HAProxy for load balancing. These stuff are not documented yet, but you should get pretty good understanding of how it works from here: https://github.com/nazar-pc/docker-webserver/issues/2

**Comment by thaJeztah** [comment]
@schmunk42 there's no direct alternative yet for aliases in the new networking; it *is* on the roadmap, but I know there's still being worked on the best solution / design. Because there's no full alternative to links yet, we also decided to hold off putting `--link` on the list of "to be deprecated features". Hopefully, design and implementation will be ready for the 1.10 release.

**Comment by schmunk42** [comment]
Thank you all for your feedback. I'll follow the releases and changelogs to see which of those features become available.

This is my hacky solution for now :)

```
nginx:
  command: 'sh -c "sed -i \"s/phpfpm/tests_php_1/\" /etc/nginx/nginx.conf; /root/run.sh"'
```

**Comment by thaJeztah** [comment]
@schmunk42 @nazar-pc FYI; here's the WIP proposal for providing "aliases" in the new networking; https://github.com/docker/docker/issues/18699

**Comment by nazar-pc** [comment]
Thanks, but I've personally solved this issue by having Consul as one of containers in Docker Compose setup and other containers are modifying their `/etc/resolv.conf` to use Consul container(s) for DNS.
But yes, it would be great to finally see DNS feature available out of the box.

**Comment by LK4D4** [comment]
I think that stuff works in compose from-the-box now.
