### ISSUE TITLE
Docker 1.9.1 breaks for custom bridges

### ISSUE THREAD

**Issue by hanikesn** [docker/docker#18145]
Docker 1.9.1 doesn't assigns ip addresses correctly, including double assignment. Docker 1.9.0 doesn't have the problem.

```
 /usr/bin/docker daemon --fixed-cidr=10.10.0.128/25 --bridge=cbr0 --iptables=false --ip-masq=false -H fd://
```

```
4: cbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 08:00:27:62:93:d7 brd ff:ff:ff:ff:ff:ff
    inet 10.10.0.3/24 brd 10.10.0.255 scope global cbr0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe62:93d7/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by cpuguy83** [comment]
Can you explain and give an example of what you mean?

Thanks!

ping @mrjana @mavenugo

**Comment by mavenugo** [comment]
@aboch can you PTAL. I could reproduce the double assignment for the second container. All other containers seems to get the IPs assigned fine. 

@hanikesn apart from the double assignment for the 2nd container, what other issue do you see ?

**Comment by hanikesn** [comment]
The first container gets 10.10.0.128 assigned, but it should be 10.10.0.129.

**Comment by hanikesn** [comment]
This is the vagrant machine were I experience this behaviour: https://gist.github.com/hanikesn/7de29b9e5611c7ebf966

**Comment by mavenugo** [comment]
@hanikesn thats correct. This is a regression most likely introduced by https://github.com/docker/docker/pull/17853.
@aboch can you PTAL asap ?

**Comment by aboch** [comment]
@hanikesn  Thanks for your report.

Regarding
>
The first container gets 10.10.0.128 assigned, but it should be 10.10.0.129.

The `--fixed-cidr` field defines the range of addresses for containers. In this case `10.10.0.128` is in fact the first address in the range specified by `10.10.0.128/25`.

The documentation (https://docs.docker.com/v1.8/articles/networking/#docker0) seems clear:
>
For example with --fixed-cidr=192.168.1.0/25, IPs for your containers will be chosen from the first half of 192.168.1.0/24 subnet.

The fact that the old ipallocator in versions < 1.9.0 and the new ipam in 1.9.0 were issuing the second valid ip in the range (instead of the first one) is to me the bug, which is now resolved in 1.9.1.


Regarding the double assignment issue, I am still working on reproducing it.

**Comment by mavenugo** [comment]
@aboch good point on fixed-cidr being a range and not subnet. Though the fixed-cidr range is `/25`, the actual allocated ip address is `10.10.0.128/24` which is appropriate in this case.

Double assignment is the only valid issue here.

**Comment by hanikesn** [comment]
As 1.9.0 behaves differently this change should probably be documented in the changelog. It could suprise some people.

**Comment by aboch** [comment]
@hanikesn 
After removing the `/var/lib/docker/network/files/local-kv.db` I am able to hit the duplicate ip issue.

**Comment by aboch** [comment]
Fix for this issue is now in master. Brought in via https://github.com/docker/docker/pull/18106

**Comment by thaJeztah** [comment]
Thanks @aboch I'll close this issue.

For anyone here willing to test; builds from master can be found on https://master.dockerproject.org however, those are builds for 1.10-dev, and contain lots of other changes as well; don't run them on a production server, only for testing (for now)
