### ISSUE TITLE
Start docker.socket via systemd, run into failed state. 

### ISSUE THREAD

**Issue by mattma** [docker/docker#18141]
I use `CentOS 7` OS. 

```
Linux xx 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

I do not want to do `wget -qO- https://get.docker.com/ | sh` or `curl`, instead of rolling the `docker.socket` and `docker.service` myself. 

`/etc/systemd/system/docker.socket`, content attached below

```
[Unit]
Description=Docker Socket for the API
PartOf=docker.service

[Socket]
ListenStream=/var/run/docker.sock
SocketMode=0660
SocketUser=root
SocketGroup=docker

[Install]
WantedBy=sockets.target
```

Then Run `systemd` command to start `docker.socket`

```
sudo systemctl daemon-reload
sudo systemctl enable docker.socket
sudo systemctl start docker.socket
```

Then I run into an error state, I could not figure out how to bypass it. 

```
-- Logs begin at Sat 2015-11-21 07:28:07 UTC, end at Sat 2015-11-21 07:52:32 UTC. --
Nov 21 07:29:56 kube-node-02 systemd[1]: Starting Docker Socket for the API.
Nov 21 07:29:56 kube-node-02 systemd[1]: Socket service docker.service not loaded, refusing.
Nov 21 07:29:56 kube-node-02 systemd[1]: Failed to listen on Docker Socket for the API.
Nov 21 07:29:56 kube-node-02 systemd[1]: Starting Docker Socket for the API.
Nov 21 07:29:56 kube-node-02 systemd[1]: docker.socket control process exited, code=exited status=216
Nov 21 07:29:56 kube-node-02 systemd[1]: Failed to listen on Docker Socket for the API.
Nov 21 07:29:56 kube-node-02 systemd[1]: Unit docker.socket entered failed state.
Nov 21 07:32:30 kube-node-02 systemd[1]: Starting Docker Socket for the API.
Nov 21 07:32:30 kube-node-02 systemd[1]: docker.socket control process exited, code=exited status=216
Nov 21 07:32:30 kube-node-02 systemd[1]: Failed to listen on Docker Socket for the API.
```

**Comment by mattma** [comment]
It is not a Docker issue. It is related to my setup.

**Comment by adler-j** [comment]
@mattma, would you please post your solution if you had one?


![](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

**Comment by donwellus** [comment]
Hi @adler-j,
Some time ago I had the same problem in Ubuntu, the problem was that /etc/docker/daemon.json had an issue and I have no idea how it happened, I didn't changed anything, I just had installed docker.io.

When I tried to start the docker service, _journalctl  -xef_ shown me this line below:
unable to configure the Docker daemon with file /etc/docker/daemon.json: file configuration validation failed (2804 is not an ip address)

So I removed the item "2804" and could start up the docker.
It worked for me, I hope it can be helpful for someone else.

File with problem:
$ sudo cat /etc/docker/daemon.json
```
{
  "dns": [
    "172.17.0.1",
    "181.213.132.2",
    "181.213.213.3",
    "2804"
  ],
  "bip": "172.17.0.1/24"
}
```
