### ISSUE TITLE
How to integrate new code to project

### ISSUE THREAD

**Issue by drngsl** [docker/docker#18218]
Hi, I'm a greenhand.
I install the docker according to http://docs.docker.com/engine/installation/ubuntulinux/,
but now I want to add or remove device under running container, while the current docker doesn't support.
of cource, I know there is  resource that achives this operation like https://github.com/imain/docker/tree/devices, so how can i use it in my host?
It'is better for giving me detailed steps.
thanks!

**Comment by unclejack** [comment]
Adding and removing devices dynamically to a running container could be a very bad idea in many cases and it's not supported right now. Should you really have a use case where you absolutely need this and don't need security, you can also try to use the `--privileged` flag.

`docker run` has a `--device` flag which can be used to expose devices in containers.

The documentation can be found here: https://docs.docker.com/engine/reference/run/#runtime-privilege-linux-capabilities-and-lxc-configuration

Documentation regarding contributions to this project can be found at https://github.com/docker/docker/blob/master/CONTRIBUTING.md

Please feel free to use one of the following when you'd like to ask a question:
1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker channel on Freenode.

1) and 2) should be better for longer conversations and more complex questions.

We recommend asking for help regarding general Docker usage and contributing to Docker through the means mentioned above.

Since this issue was more of a question, I'll close it now. Please feel free to continue the conversation on this issue.

**Comment by drngsl** [comment]
@unclejack , thanks.
Now, I want to integrate docker with openstack with nova-docker driver,  and I can create a VM (or container) in openstack , spawn with novadocker driver, and attach volumes (as --device args) that create by cinder. 
Supposing  that i have created an VM, i want to attach an volume to VM with docker, but unfortunately, docker does not support this operation.

**Comment by drngsl** [comment]
@unclejack , I'd like to ask a question, when I create a container with cmd `docker run --privileged --device=/dev/sdc:/dev/vsdc -it ubuntu /bin/bash`, but in the container, why can't i seek the device /dev/vsdc?

**Comment by unclejack** [comment]
@drngsl This isn't a general support forum and the community doesn't provide support for openstack on this issue tracker. Please take a look at the list of places where you can ask questions above.
