### ISSUE TITLE
bind ip address is ignored when publish ports if you use non-default network

### ISSUE THREAD

**Issue by ese** [docker/docker#18237]
Using --ip to launch daemon is supposed to bind published ports to a specific IP.  

If you are running your containers in other network than bridge default then they publish their ports in 0.0.0.0 instead the IP specified at daemon options.

How to reproduce it:

$ docker daemon --ip 10.0.0.1

$ docker network create -d bridge network_test
$ docker run -d  -P --net=network_test redis

$ docker ps
```
   PORTS  
   0.0.0.0:32772->6379/tcp    
```
but expected:
```
   PORTS  
   10.0.0.1:32772->6379/tcp  
```
--
3.19.0-33-generic #38~14.04.1-Ubuntu SMP Fri Nov 6 18:17:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ docker version
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```
$ docker info
```
Containers: 804
Images: 93
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-33-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 6
Total Memory: 9.525 GiB
```

**Comment by ese** [comment]
The problem is the lack of the "com.docker.network.bridge.host_binding_ipv4" in the network configuration.
You can set it when you create the network but it should be populate by the default config.

$ docker network create -o "com.docker.network.bridge.host_binding_ipv4"="10.0.0.1" network_test

**Comment by thaJeztah** [comment]
ping @aboch @mavenugo is this a known issue? ^^

**Comment by aboch** [comment]
@ese 

This behavior is intentional.

With the introduction of libnetwork, for backward compatibility reasons the network specific daemon cli options have been kept as is, as they would apply to the default bridge network. 

For the newly created network, we want user to use the new cli in which we try to provide well known *driver agnostic* explicit options, while the *driver specific* options can be passed in a proper list.

As you found you can still pass those options
`docker network create -o "com.docker.network.bridge.host_binding_ipv4"="10.0.0.1" network_test`

Inheriting them from the old daemon options may not be the right choice, as they may not apply to drivers other than bridge.

**Comment by thaJeztah** [comment]
@aboch do you think we should document the available options for the default bridge driver? Or are they already documented (I can check other locations in the docs, but this page doesn't mention them https://github.com/docker/docker/blob/master/docs/reference/commandline/network_create.md)

**Comment by aboch** [comment]
@thaJeztah 
Agree, we should (I was not able to find them in the docs either)

**Comment by wenchma** [comment]
@ese the `docker daemon --ip 10.0.0.1`  only takes affect on the default `bridge` network.
