### ISSUE TITLE
Cannot build any images after upgrading from 1.7 to 1.9

### ISSUE THREAD

**Issue by huglester** [docker/docker#18235]
Hello everybody,

### Docker version:
```
# sudo docker build -t php55 .
Sending build context to Docker daemon 108.5 kB
Step 1 : FROM ubuntu:14.04
 ---> e9ae3c220b23
Step 2 : ENV HOME /root
 ---> Using cache
 ---> 22f539e3243b
Step 3 : RUN apt-get update
 ---> Running in ab83b1d4d186
[8] System error: stat /sys/fs/cgroup/system.slice/docker-ab83b1d4d186da4a6204199bbf353877273fa851f81f3315d5778b9851fccf63.scope: no such file or directory
```

### Docker info
```
# docker info
Containers: 1
Images: 18
Server Version: 1.9.1
Storage Driver: vfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 2.6.32-042stab106.6
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 8 GiB
Name: dockers
ID: YN2P:DGVV:ZHUP:2X2W:CZUH:7GV7:BH5H:VBMY:LCEM:KBNT:U3FX:THDE

```

### uname -a
```
# uname -a
Linux dockers 2.6.32-042stab106.6 #1 SMP Mon Apr 20 14:48:47 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux
```

### interesting info form systemctl
```
# systemctl status docker
docker.service - Docker Application Container Engine
.......

Nov 25 11:00:08 dockers docker[467]: time="2015-11-25T11:00:08.075563988-05:00" level=warning msg="Your kernel does not support oom control."
Nov 25 11:00:08 dockers docker[467]: time="2015-11-25T11:00:08.075620865-05:00" level=warning msg="Your kernel does not support memory swappiness."
Nov 25 11:00:08 dockers docker[467]: time="2015-11-25T11:00:08.075645936-05:00" level=warning msg="Your kernel does not support kernel memory limit."


````
when I try to build any of the images, I get this:
```bash
# sudo docker build -t rubytest .
Sending build context to Docker daemon 108.5 kB
Step 1 : FROM ubuntu:14.04
 ---> e9ae3c220b23
Step 2 : ENV HOME /root
 ---> Using cache
 ---> 22f539e3243b
Step 3 : RUN apt-get update
 ---> Running in ab83b1d4d186
[8] System error: stat /sys/fs/cgroup/system.slice/docker-ab83b1d4d186da4a6204199bbf353877273fa851f81f3315d5778b9851fccf63.scope: no such file or directory
```

Any idea what I am doing wrong?
This docker is running inside OpenVZ.  But it was working without problems.

I tried all images and all of them return similar error.

Thank you!

**Comment by thaJeztah** [comment]
Looks like you're not using the default kernel for CentOS 7

Kernel 2.6.x is not a supported kernel for Docker and the minimum for CentOS 7 is 3.10, see http://docs.docker.com/engine/installation/centos/#prerequisites

Please make sure your system is fully up to date

Perhaps this issue is related: https://github.com/docker/docker/issues/16256, and using `--exec-opt native.cgroupdriver=cgroupfs` may be able to help here

**Comment by huglester** [comment]
hello @thaJeztah 

this container is inside OpenVZ, this is why we have lower kernel.

Version 1.7 of docker worked perfectly.

There is a topic, on how to run a docker inside OpenVZ container: https://openvz.org/Docker_inside_CT

quite from there: Prerequisites: Kernel 042stab105.4 or later version

It has all the required modules to run the docker (as I understand). But somehow I can't run version 1.9.
I use this repo: 

```
[docker-main-repo]
name=Docker main Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/7
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
```

Maybe I somehow can try downgrading to 1.8, if it does not work, I'd just go back to 1.7

**Comment by thaJeztah** [comment]
You can do a basic check if your system has the requirements using this script; https://github.com/docker/docker/blob/master/contrib/check-config.sh

But still, your system is not supported, and I would really discourage running docker on that, apart from doing some testing/experimenting. Also, ssing the `vfs` graph driver is really discouraged, that driver is really a "last resort" if nothing else works.

I'm going to close this issue, because you're running Docker on a non supported system, but feel free to continue the discussion here.
