### ISSUE TITLE
Docker startup SSH error involving IP address

### ISSUE THREAD

**Issue by jgharris7** [docker/docker#18251]
When starting up the "Quickstart" for Docker I get:
"Error getting IP address: Something went wrong running an SSH Command!"
It also says 
"docker is configured to use the default machine with IP"

Subsequent commands that involve pulling something from github give error messages like 
"An error occured trying to connect: Post http://localhost:2375/v1.21/images/create......." dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the target machine actively refused it.

**Comment by thaJeztah** [comment]
Are you sure the machine is running? You can try `docker-machine ls` to see the status of your machines, and `docker-machine start default` to start the default machine.

After that, `docker-machine env default` should give you instructions on setting the right environment variables.

hope this helps

**Comment by jgharris7** [comment]
I am running docker on Windows-7 64 bit machine. I tried what you suggested and this is the message I get:
![image](https://cloud.githubusercontent.com/assets/8651358/11431962/4b0ba3c8-9471-11e5-81f1-5ee54b9c9329.png)

**Comment by thaJeztah** [comment]
I think it's better to reopen this issue in the docker-machine issue tracker, because this is related to docker machine. There are some issues that look similar to this one, for example this one; https://github.com/docker/machine/issues/2240

Are you okay with closing this issue, and continue in the docker-machine issue tracker?

**Comment by LK4D4** [comment]
Closing this as inactive.
