### ISSUE TITLE
Add hostname support to docker run EXPOSE commands

### ISSUE THREAD

**Issue by AlexChesser** [docker/docker#18269]
Currently, (and forgive me if I am misreading the documentation) there is no in-built way to expose multiple different containers on the same port in the same docker host.

An ideal situation in docker configurations would be to have the single docker host running

    Docker Host
        - container 1: exposed on port 80: hostname: my-container1.local-dev.com
        - container 2: exposed on port 80: hostname: my-container2.local-dev.com

    Production Host
        - client1-live: exposed on port 80: hostname: www.client1.com  
        - client1-staging: exposed on port 80: hostname: client1-staging.mydomain.com
        - client1-uat: exposed on port 80: hostname: client1-uat.mydomain.com
        - client2-live: exposed on port 80: hostname: www.client2.com  
        - client2-staging: exposed on port 80: hostname: client2-staging.mydomain.com
        - client2-uat: exposed on port 80: hostname: client2-uat.mydomain.com

I think for a shared hosting environment, a single vm with `n` docker containers it is inevitable that two will need to map onto the same port. I believe this philosophically maps on to something that docker just "should" do.

Adding to the RUN command would allow developers to work on numerous systems and different VERSIONS of systems locally.

Currently in stack overflow there are a number of questions representing people's desire for a solution. While the third link below appears to provide a workaround, it also appears to be a non-trivial solution where "native" support for hostname & port mapping in the docker RUN command.

http://stackoverflow.com/questions/18497564/assigning-vhosts-to-docker-ports  
http://stackoverflow.com/questions/27828699/multiple-docker-containers-as-web-server-on-a-single-ip  
http://stackoverflow.com/a/23975934/398055  

Again, forgive me if this is already supported and I've just stupidly missed it.

**Comment by thaJeztah** [comment]
Thanks for opening this issue, but this is not something that we can implement; the use-case you're describing is really for web-sites, and will only work if a hostname header is available. In many cases (think of exposing a ssh server), mapping based on a hostname is not possible.

What you're looking for is a reverse proxy that routes traffic to the right container (or even containers), based on the hostname. In that case, only the proxy-server's port 80 is exposed/published and all traffic will go through that server and communicates with the we container through the internal container-container network.

This sounds complicated but there are some really easy to use solutions, for example;

https://github.com/jwilder/nginx-proxy/ and https://github.com/EmileVauge/traefik

With nginx-proxy, all you need to do is start the nginx-proxy container, then start your webcontainers, but add an environment-variable containing the hostname/domainname for that container. For example; `docker run -d -e VIRTUAL_HOST=my.domain.com nginx`. Nginx-proxy will automatically match "my.domain.com" to that container; you don't even have to publish (`-p`) ports, as long as the container exposes port 80 and/or 443.

Hope this helps!

I'm going to close this issue, because this is not something we can implement, but I hope the information above helps you further. Feel free to comment here after I've closed this issue :+1:
