### ISSUE TITLE
Allow naming default bridge

### ISSUE THREAD

**Issue by mitar** [docker/docker#18294]
Currently the default bridge is named always `bridge`. I would be great if there would be a way to name it (while keeping everything else as it is). This would allow better self-documentation.

**Comment by aboch** [comment]
@mitar 
Sorry, can you please explain a little more about the self-documentation ?

Although it seems a simple change, I know a lot of code has to be changed in order to support this.

I am also concerned this would change the default `docker network ls` output where user can identify the three well-known default networks: `bridge, host, null`. 
I see it as a stronghold (like `docker0` bridge name) when debugging issues.

Just trying to weigh the pros and cons.

**Comment by LK4D4** [comment]
This issue spent a long time without any activity. I'm closing it. Feel free to open new.

**Comment by mitar** [comment]
:-(
