### ISSUE TITLE
Cannot provide paths to docker run in windows

### ISSUE THREAD

**Issue by atrauzzi** [docker/docker#18290]
When I try to run this: `winpty docker run --volume="./laravel:/app" composer/composer "$@"`, I get the following error:

```
invalid value "`.\\laravel:\\app`" for flag --volume: \app` is not an absolute path
See 'docker run --help'.
```

Running: `Docker version 1.9.1, build a34a1d5`

**Comment by thaJeztah** [comment]
Hm, sounds like the windows shell converting slashes to backslashes, I think there are some other issues about that, and iirc, there was as workaround to prevent it being "smart".

I *do* see, however, that you're trying to use a relative path (`.\\laravel`) for the host path, that's not supported, and should be an absolute path (e.g. `C:\Users.....`)

**Comment by thaJeztah** [comment]
I think this discussion describes it; https://github.com/docker/docker/issues/13741, and this link http://www.mingw.org/wiki/Posix_path_conversion

**Comment by atrauzzi** [comment]
Requiring an absolute path is not practical though.  This is in the context of a shared project. Not everyone will put it in the same location on their machines.

**Comment by atrauzzi** [comment]
Also, I'm using docker toolbox, not cmd or power shell.

**Comment by thaJeztah** [comment]
> Requiring an absolute path is not practical though. This is in the context of a shared project. Not everyone will put it in the same location on their machines.

You could consider using docker-compose; docker-compose allows you to define bind-mounted volumes relative to the location of the `docker-compose.yml` file. Using a docker-compose file allows you to specify all options needed to run your containers in a single file, which makes it ideal for sharing between team members (ie, just run `docker-compose up -d` will start all containers for the project with the right options).

On Linux, using `--volume $(pwd)/laravel:/app/` is usually the way to convert the current directory to an absolute path (but not sure if there's an alternative to that on Windows :blush:)

> Also, I'm using docker toolbox, not cmd or power shell.

IIRC, toolbox basically starts a cmd or powershell session, with the environment set up to connect to your virtual machine but I don't have access to a Windows box currently, so I'm not able to test a.t.m.

/cc @jeffdm for Docker Toolbox, because this is more an issue with docker-toolbox than docked

**Comment by atrauzzi** [comment]
I'm already using compose to simulate an environment.  This is just a one off command.

**Comment by jeffdm** [comment]
Thanks @thaJeztah.

@atrauzzi I'll investigate the path conversion in docker/toolbox

**Comment by jeffdm** [comment]
See https://github.com/docker/toolbox/issues/282

Thanks!

**Comment by thaJeztah** [comment]
Thanks @jeffdm 

@atrauzzi let's continue the discussion in https://github.com/docker/toolbox/issues/282. I'll close the issue here

**Comment by krishna81m** [comment]
This hack seems to work like a charm if you have downgraded to 1.9 from the AUFS issues in 1.9.1
```
docker create -v //c/Users/myuser:/myuser --name data hello-world
winpty docker run -it --rm --volumes-from data ubuntu
```
