### ISSUE TITLE
docker network autoguessing could be dangerous for local networks

### ISSUE THREAD

**Issue by jhrcz** [docker/docker#18335]
because docker autodetects network when it starts, it could bring problems to lans after moving to other place. when workstations are not connected to switches with arp spoofing protection, it spoof mac address for address associtated to BIP (bridge).

this could take down you local lan if you have one of collision in some of the docker networks.

"not-as-easy" fix is to use arp spoof detection, use ebtables or similar solutions but out of the box, this should be solved by docker daemon itself.

**Comment by jhrcz** [comment]
this is not related to some version, maybe to running networked linux machine

steps to reporoduce:
1. install docker
2. have the same network range for you lan and docker (in our case lan: 172.17.0.0/23, default docker bip 172.17.0.0/24)
3. docker is promoting worskation MAC as 172.17.0.1 which could be the LAN firewall for example.

**Comment by phemmer** [comment]
* Docker uses what IEEE defines as "locally administrated" MAC addresses. Meaning hardware vendors will never use them, so you don't have to worry about collisions. If you have a hardware vendor that is using a MAC address designated locally administrated, the vendor is non-compliant, and there is nothing docker can do about this.
* Docker's containers sit within a separate broadcast domain. The only way for your containers to show up on the public network is if you've joined your host's public interface to the docker bridge. This is not a supported configuration.
* `172.17.0.1` is an IP address, not a MAC address.
* If the docker subnet overlaps the public network your host is a part of, this will not cause problems on the host network. This is because of the fore-mentioned broadcast domain thing. The only effect this will have is that your host machine will have 2 routes to the same subnet, and so your host will have broken network connectivity.

**Comment by thaJeztah** [comment]
I agree, I don't think this is an issue. Connecting a computer with a fixed ip-address to a network can also cause IP collisions, I don't think this is something we can (and should) prevent.

I'm going to close this issue, but feel free to comment after I've closed

**Comment by jhrcz** [comment]
with "docker is promoting worskation MAC as 172.17.0.1" i meant, that the machine sends arps "is-at" with MAC of the workstation telling all other machines where the IP 172.17.0.1 is. so i badly wrote it, wrongly use IP and MAC ;o)

the "different broadcast domain" is not true on linux - it broadcasts the info on all interfaces.

i talk abou default configuration - just intsall docker packages on ubuntu (not in the vm) and you are in trouble.

i could check how docker behaves when moving the notebook betwen different networks and turn off / suspend the ntb.
