### ISSUE TITLE
apt.dockerproject.org not availible from ipv6-only host

### ISSUE THREAD

**Issue by alexanderkjall** [docker/docker#18342]
It's currently not possible to install docker on an debian machine that's ipv6-only:

$ host -t AAAA apt.dockerproject.org
apt.dockerproject.org is an alias for j.global-ssl.fastly.net.
$ host -t AAAA j.global-ssl.fastly.net.
j.global-ssl.fastly.net has no AAAA record

Could you please add a AAAA record so that you can install docker on ipv6-only hosts.

BUG REPORT INFORMATION

Use the commands below to provide key information from your environment:

docker version: 1.9
docker info: N/A
uname -a: Linux geordi 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux

Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
1. install virtual machine with only ipv6
2. add deb https://apt.dockerproject.org/repo debian-jessie main to: /etc/apt/sources.list.d/docker.list 
3. do: apt update

Describe the results you received:
W: Failed to fetch https://apt.dockerproject.org/repo/dists/debian-jessie/main/binary-amd64/Packages  

E: Some index files failed to download. They have been ignored, or old ones used instead.

Describe the results you expected:
able to install docker

Provide additional info you think is important:

----------END REPORT ---------

**Comment by thaJeztah** [comment]
Possibly related to https://github.com/docker/docker/issues/17790

/cc @jfrazelle ?

**Comment by jfrazelle** [comment]
yes closing as dup of that

**Comment by thaJeztah** [comment]
Thanks @jfrazelle I wasn't sure if it was on the same infrastructure :smile:

**Comment by jfrazelle** [comment]
this is fixed wooo
![2016-01-25-13-17-11_1144x610](https://cloud.githubusercontent.com/assets/1445228/12564827/4e81480e-c366-11e5-8a09-378c58521d25.png)

**Comment by thaJeztah** [comment]
Cool!

**Comment by thomasschaeferm** [comment]
For me it doesn't work. I tried the DNS of my ISP and the resolver from Google.

**Comment by jfrazelle** [comment]
I had to turn it off because it broke something, looking at another way

**Comment by andir** [comment]
Are the any news on this issue?
@jessfraz what did break when you did enable IPv6?

**Comment by jessfraz** [comment]
It was SSL with gnu tls on the cloud flare ipv6 proxy that broke, it's all
documented in this issue if you read the thread...

**Comment by slugan** [comment]
[ Duplicating post https://github.com/moby/moby/issues/17790#issuecomment-364378339 since this issue (#17790) was about get.docker.com and not apt.dockerproject.org which is used as Debian Docker repository and which is still IPv4-only ]

Hi, do you think it might be possible to try to enable IPv6 support again?

Some other projects also using deb apt to access Amazon CloudFront hosted repositories with IPv6 + TLS seem to have it working for one year now: nodesource/distributions#170 (deb.nodesource.com).

Amazon indeed introduced IPv6 support in CloudFront in October 2016: https://aws.amazon.com/about-aws/whats-new/2016/10/ipv6-support-for-cloudfront-waf-and-s3-transfer-acceleration/ .

[ P.S.: as per indicated in https://github.com/moby/moby/issues/17790#issuecomment-365105419 IPv6 has already been successfully enabled for download.docker.com, get.docker.com and test.docker.com, but not yet apt.dockerproject.org ]

**Comment by thaJeztah** [comment]
@slugan (copying here as well) apt.dockerproject.org is deprecated, and only kept for legacy releases; all current releases are published to https://download.docker.com (which contains both the apt and yum repositories, as well as static builds)

**Comment by slugan** [comment]
Thanks for the info @thaJeztah!

Here is the process I followed to switch to the new repository on Jessy:
- in /etc/apt/sources.list.d/docker.list, replace:
`deb https://apt.dockerproject.org/repo debian-jessie main`
with:
`deb https://download.docker.com/linux/debian jessie stable`
- install the corresponding GPG key:
`wget -qO- https://download.docker.com/linux/debian/gpg | apt-key add -`
- clean & update the apt cache:
`apt-get clean all && apt-get update`

Everything is indeed working perfectly with IPv6-only connectivity.

Thanks again!
