### ISSUE TITLE
Docker High IO Wait contributing to 90%+ CPU

### ISSUE THREAD

**Issue by yunspace** [docker/docker#18414]
We have 2 AWS `m3.medium` instances created via Tutum. However periodically they would experience high CPU load contributing to higher than 90% CPU. This would result in the instance becoming unreachable in Tutum and we need to restart the instances, the problem would eventually come back within a week or so.

We believe this is more of an Docker issue rather than Tutum. These are our NewRelic graphs for Dev2 and Dev3:

![screen shot 2015-12-04 at 10 52 03 am](https://cloud.githubusercontent.com/assets/218128/11578297/25e37c44-9a78-11e5-9c5a-bdbe990253e6.png)
![screen shot 2015-12-04 at 10 51 48 am](https://cloud.githubusercontent.com/assets/218128/11578298/25e51716-9a78-11e5-99f9-e9a867d5db5e.png)

Details of both machines and are as follows:

*DEV2*
**uname** Linux dev2 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**docker version**
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      linux/amd64

**docker info**
```
Containers: 28
Images: 412
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 624
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-61-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 3.676 GiB
Name: dev2
ID: ZJ2N:4RXO:HFGG:ROEF:GSHD:SM6D:UAD2:H3LS:7K3V:WMJV:ILDQ:GOEQ
WARNING: No swap limit support
```

*DEV3*
same as above for uname and docker version
 
**docker info**
```
Containers: 29
Images: 417
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 743
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-61-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 3.676 GiB
Name: dev3
ID: QZ2E:G6U6:7R5C:UNNX:4PJD:3SG7:EKD2:YHJU:CTP6:VEL5:SHH4:PDM7
WARNING: No swap limit support
```

Our observations so far:
 - This issue only occurs in our Dev environment, where frequent deployments happen in Dev and containers are stopped and started.  
 - The memory usage tends to be quite high over 80% when this happens
 - `docker info` shows No swap limit support

We've increased the sizes of the machines to m3.large which has 7GB of memory to observe what happens. If anyone has similar issues or could offer some suggestions it would be much appreciated.

**Comment by phemmer** [comment]
> We believe this is more of an Docker issue rather than Tutum

What leads you to this idea?

**Comment by thaJeztah** [comment]
> We've increased the sizes of the machines to m3.large which has 7GB of memory to observe what happens

Did this make a difference? Or to early to tell?

**Comment by yunspace** [comment]
@phemmer mainly based on the various file system related issues such #9665 #13885 #12758 etc. They may not be related.

@thaJeztah CPU has been steady around 2-3% with 60% memory for the last 4 days. So far so good.

**Comment by tobowers** [comment]
hmm - we have a few m3.medium boxes (4gb of memory) as well. They are spiking on docker cpu usage too (new to 1.9.1). Our m4.large boxes (7gb of memory) seem unaffected by our upgrade to 1.9.1

**Comment by cpuguy83** [comment]
@thaJeztah Sounds eerily similar to the boot2docker issues with 1.9.x, no?

**Comment by thaJeztah** [comment]
@cpuguy83 Yes, but the original report at the top uses both a different version of docker *and* a different kernel version, so, idk, open to suggestions though.

For reference, this is the issue @cpuguy83 is referring to; https://github.com/docker/docker/issues/18180

**Comment by cpuguy83** [comment]
ah yes, this is 1.8.3.

**Comment by unclejack** [comment]
@yunspace You haven't told us anything about what you're running in Docker and what kind of workloads you're running there. I'm inclined to think there's absolutely nothing on the Docker side which would be causing this, but there might actually be something related to the containers you're running.

**Comment by unclejack** [comment]
This isn't a Docker issue. This is most certainly an issue related to that system's resources and to the software it's running.

Docker allows everyone to run a lot of software and to deploy software quickly, but that doesn't make disk IO faster or increase CPU performance somehow. Disk IO, disk space, RAM and CPU resources also need to be taken into account.

Since this isn't a Docker issue and the discussion can continue without keeping this issue open, I'm going to close this now. Please feel free to continue the discussion.

**Comment by janakaud** [comment]
I'm observing a similar issue, but on a virtual machine running Kubernetes on Docker. The `docker` process consistently shows high CPU 'spikes' (sometimes lasting 2-3 seconds) once in every 10-15 seconds.

I ran a live `tail` on `/var/log/upstart/docker.log` but did not see any 'unusual' activity during such spikes (i.e. the logs being generated are identical to those at non-spike times, which include
GET /containers/json?all=1
GET /containers/json
GET /version

I have stopped all 'client' containers, and the only ones running are related to Kubernetes:
gcr.io/google_containers/exechealthz:1.0
gcr.io/google_containers/skydns:2015-03-11-001
gcr.io/google_containers/kube2sky:1.11
gcr.io/google_containers/etcd:2.0.9
gcr.io/google_containers/pause:2.0

Correct me if I'm wrong, but since it is the docker daemon process that is exhibiting high CPU usage (and not any of the application processes running inside the containers, such as `kube2sky` or `skydns`--which are visible as separate processes on the output of the `top` command), I believe the problem lies with `docker` itself in my case.

My `docker info` output is identical to that given on the issue description above, except for
kernel version (3.13.0-85-generic),
OS version (Ubuntu 14.04 LTS),
CPUs (4),
total memory (5.691 GiB), and
container and image counts (69, 259).

**Comment by cpuguy83** [comment]
@janakaud Are you seeing high I/O wait along with the CPU spikes?
In general the docker daemon is at rest unless there are active requests in the API... with the exception of logging, which could easily cause CPU spikes if there is spikes in log output, or potentially if there is high I/O wait and you are using the default logger.

Could you open a separate issue with more details?
Would need things like iowait, cpu usage, if you can grab a pprof profile (the daemon must be running in debug mode to do this) it would be extremely helpful.
It may also be helpful to provide a stack trace, which you can get by sending `SIGUSR1` to the daemon process and grabbing the stack trace from the daemon logs.

Thanks! I hope we can get to the bottom of your issue.

**Comment by janakaud** [comment]
@cpuguy83 I didn't actually happen to check I/O wait (and now I understand I have posted the question in a somewhat inappropriate place; sorry about that!)
I would try to follow the guidelines you suggested and open a new issue (or try to find a more appropriate issue for posting my findings).
Thanks!

**Comment by csuxh** [comment]
How did you guys sove the IO issue ? I got the same issue everyday on my own virtual machine.

**Comment by djuarezg** [comment]
@csuxh maybe too late but did you solve this issue?
