### ISSUE TITLE
upstart: does not wait for Unix socket if multiple host entries in DOCKER_OPTS

### ISSUE THREAD

**Issue by ssmall** [docker/docker#18516]
#### Issue
I am trying to create an Upstart service that depends on Docker,  however it is failing because `/var/run/docker.sock` does not exist yet, despite the fix in #6647.

`cat /etc/default/docker`:

```
DOCKER_OPTS="${DOCKER_OPTS} -D -H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock"
```

#### Additional info:

`docker version`:

```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

`docker info`:

```
Containers: 0
Images: 155
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 157
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-72-generic
Operating System: Ubuntu precise (12.04.5 LTS)
CPUs: 2
Total Memory: 3.337 GiB
Name: u70f395136dc555e9f25e
ID: 2VO3:C3GC:IWZ3:JZMP:EER4:4UJG:7S3B:LJO3:WHID:LBVD:4WNU:FINA
Debug mode (server): true
Debug mode (client): false
Fds: 12
Goroutines: 16
System Time: Tue Dec  8 23:11:14 UTC 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```

`uname -a`: 
```
Linux u70f395136dc555e9f25e 3.13.0-72-generic #115~precise1-Ubuntu SMP Thu Dec 3 10:52:56 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by AndrewGuenther** [comment]
The problem is this line:
https://github.com/docker/docker/blob/master/contrib/init/upstart/docker.conf#L52
```bash
	if ! printf "%s" "$DOCKER_OPTS" | grep -qE -e '-H|--host'; then
		while ! [ -e /var/run/docker.sock ]; do
			initctl status $UPSTART_JOB | grep -qE "(stop|respawn)/" && exit 1
			echo "Waiting for /var/run/docker.sock"
			sleep 0.1
		done
		echo "/var/run/docker.sock is up"
	fi
```

This checks to see whether or not a host has been specified in `DOCKER_OPTS`, if one is not present, it will wait for the socket. However, @ssmall is specifying that he wants the daemon to run on both the socket *and* a TCP socket. In this case, this check will fail, but the socket may not actually be up. Additionally, this check can fail if you are using *any* socket other than the default socket.

The most logical fix (in my mind) would be to change the grep to exclude `(-H|--host)` parameters which begin with `unix://`

I'll draft up a patch this evening.

**Comment by thaJeztah** [comment]
Thanks @AndrewGuenther!

**Comment by AndrewGuenther** [comment]
#dibs

I've written up a patch, but I need to get on a different machine in the morning to verify.
