### ISSUE TITLE
Image and container garbage collection

### ISSUE THREAD

**Issue by bfirsh** [docker/docker#18601]
It is an extremely common problem for Docker users to run out of disk space due to unused containers and images not being removed. In development, this can be an annoyance and confuse new users. In testing and production, it can be a critical problem. Anecdotally, we have heard of several users who have production systems go down due to Docker filling up their disks.

Docker should automatically remove images where it can, and provide easy-to-use tooling to remove images manually where users may not Docker to automatically delete data.

If we choose not have to any functionality in Docker itself, the common patterns should be clearly documented (e.g. `docker rmi --help` should suggest doing `docker rmi $(docker images -aq)`).
### Possible solutions
- [The concept of "anonymous images" could be removed, and Docker could remove danging images automatically or manually](https://github.com/docker/docker/issues/6802)
- [A command could be added to manually remove images which aren't used by any containers](https://github.com/docker/docker/issues/9054)
- [A command could be added to remove all stopped containers, or documentation could be improved to help you do this.](https://github.com/docker/docker/issues/17868)
- Docker itself could automatically remove containers and images after a certain amount of time, ala https://github.com/rancher/sherdock
### Related
- [docker/docker: Implement a 'clean' command](https://github.com/docker/docker/issues/928)
- [docker/compose: Clean orphan containers](https://github.com/docker/compose/pull/2218)
- [docker/compose: Epic: Use less disk space](https://github.com/docker/compose/issues/53)
- http://stackoverflow.com/questions/17236796/how-to-remove-old-docker-containers/24277052
- [docker/docker: Image Graph operations are racey](https://github.com/docker/docker/issues/16982) - race conditions in graph may be a blocker to doing this reliably

(Maintainers: Consider this a wiki to keep track of everything related to this issue... feel free to edit the description to add/remove/modify stuff.)

**Comment by dmcgowan** [comment]
Might also be worth highlighting the `--filter` flag on the list commands. Deleting all exited containers `docker rm $(docker ps -q --filter "status=exited")` and dangling images `docker rmi $(docker images -q --filter "dangling=true")`

**Comment by cpuguy83** [comment]
Performing gc now that you can reference just any random image layer is now significantly less dangerous.

**Comment by stevvooe** [comment]
@bfirsh The key to any proposal around GC is choosing the roots to GC from. Put as a question, how do you decide what is reachable? In the use cases you've studied, was there any commonality to containers/images that were kept unintentionally? Would enabling `--rm` by default solve 80% of cases?

My worry here is that docker already does GC. There is a loop that assesses reachability via edges and evaluates what action should be taken based on the type of a given edge based on a policy (somewhat like weak vs soft references). The only thing we can do is make this more aggressive and more accurate. This is the crux of the problem. If you go through many of those issues, there is always someone who gets caught out by more aggressive policies, so this is definitely not straightforward.

It sounds like we need to have an effort to make it easier for users to understand the data used by docker, similar to how one might use `df` or `du`. It might be something simple, like this:

```
$ docker usage
TYPE         SIZE
images       1TB
containers  1PB
volumes     100 GB
```

Different options could help to modify the display. We could also have a guide that shows very shell pipelines, such as `docker rmi $(docker images -q --filter "dangling=true")` and how the data from `docker usage` was used to make decisions about which ones to run.

A further addition would be policy specification and application during the rm/rmi process. We could define a set of fields, types and comparators that could be used to apply a policy during a deletion command.

With the simple additions above, we could address many of the concerns encompassed by this issue. Albeit, I'd like to see a goal set on this issue for when we close. As it is currently written, there isn't any way to measure that we are done.

**Comment by aaronlehmann** [comment]
I quite like the `docker usage` idea.

I can comment on my personal development workflow. I end up doing `docker build` frequently. Some of these builds will take almost no disk space, because only a few small layers change, and some will take up far more. It's hard to know in advance, or find out after the fact. Each build uses the same tag, so previous builds will typically become orphan images. Every once in awhile I'll run out of disk space, and try to clean out these dangling images. Sometimes they can't be removed because I accidentally ran one of them without `--rm`. Then I have to go clean out containers, and come back to image cleanup. It works out in the end, but it's an awkward process and there's very little visibility into where disk space is being used.

**Comment by gourao** [comment]
I would imagine that this could be a graph driver feature.  Docker IMO should not be burdened with this complexity.

The existing Graph API already provides sufficient capability for a graph driver to implement GC.

With our portworx graph driver implementation, this is one of the things we are already addressing, FWIW.

**Comment by stevvooe** [comment]
@gourao I'd recommend reading through the descriptions above again. The graphdriver is simply not sufficient to identify all active links, especially in the context of the discussion of this issue. The reference store, for example, can be used as a GC root source, in addition to active containers. A proper implementation _must_ have a consistent view of all the sources of GC roots and the graphdriver must not accept mutations during the deletion period to be correct.

> With our portworx graph driver implementation, this is one of the things we are already addressing, FWIW.

Could you elaborate on this or the intended design? It seems like a graphdriver could implement internal GC but it still has to maintain uncorrupted exported references (ie image ids) for it to be correct.

**Comment by gourao** [comment]
@stevvooe Our graph driver maintains a reference store.  We are in the data path when a container runs, our storage exports the layers in the local namespace. We can at all times know what layers are exported and active. We also maintain access, usage, and reference stats on each layer and can manage lifecycle of the layers in the graph driver.  

I actually do not understand your comment regarding an "implementation must having a consistent view of all sources..."

**Comment by stevvooe** [comment]
@gourao When I am talking about _GC roots_, I am referring to the references that represent the seed of the mark phase. We can also call this the _root set_. During the mark phase of a mark-sweep garbage collector, the process sweeps down from the roots, following references. Every object that is encountered during this mark phase is considered _reachable_. Every object that is not encountered is considered unreachable.

The chief requirement is that the set of reachable and unreachable objects needs to stay consistent during the entire garbage collection cycle. Methods to achieve this range from "stopping the world" to more sophisticated techniques employed in concurrent collectors (pointer mutation, generational collectors, etc.). If the set of reachable objects is not consistent, you risk leaking resources or, worse, deleting resources that are actually in use. This requirement, as far as I understand, extends to the _root set_. The _root set_ must be consistent.

From a user perspective, the behavior of what will remain is about choosing _root set_. For example, if we decide that running containers are in the root set but not stopped containers, a mark phase would not traverse the resources referenced by the stopped containers and they would be freed up. Following from that, we may decide that this behavior is insufficient, since this would delete images that are not used by a running container. With this approach, we can add the images that have a tag reference to the _root set_, ensuring that images are kept around.

With a little imagination, we can easily see how defining this _root set_ can be a tool in defining garbage collection behavior for a healthy production engine. By exposing a policy about what belongs and doesn't belong in this _root set_, we have a very powerful tool that can ensure an engine that will only be using as much data as a user intends.

[Tracing Garbage Collection](https://en.wikipedia.org/wiki/Tracing_garbage_collection#Basic_algorithm) would be a good place to start. The [documentation on Go's garbage collector](https://blog.golang.org/go15gc) is a real world example that can help understand some of the concepts. In particular, they have a solution to the consistency issue that can help with the understanding the constraints.

**Comment by sravanikoilada** [comment]
docker rm $(docker ps -a -q)
this is a simple docker command to remove all the containers...if we just want to remove exited containers then add filter option

**Comment by JonasT** [comment]
It's very simple once you found it, but up to that point a **very unobvious** solution. Everyone I know has googled for this at some point. As I keep reiterating in other tickets, if `docker rm $(docker ps -a -q)` is considered the canonical approach, it should be at least be suggested in the `docker rm --help` output to the user.

**Comment by mickep76** [comment]
It would help if Docker had metadata for when an image was cached/downloaded and when it was last used. This would allow for more granular policies for home cooked GC scripts.

**Comment by thaJeztah** [comment]
@mickep76 see https://github.com/docker/docker/issues/4237

**Comment by ndeloof** [comment]
see https://github.com/ndeloof/docker-gc for a sample implemtation based on docker events to track image usage by containers, as a workaround for missing https://github.com/docker/docker/issues/4237.

**Comment by dnephin** [comment]
https://github.com/yelp/docker-custodian

**Comment by killianbrackey** [comment]
If you find yourself running multiple commands like `docker rm $(docker ps -a -q)` or `docker rmi $(docker images -aq)`, etc often you could check out a script a friend and I put together that runs a some filtered commands with a help menu using `docker-clean [option flags]`.

Check it out and let us know what you think.

https://github.com/ZZROTDesign/docker-clean

**Comment by LK4D4** [comment]
@mlaventure was this fixed by #26108 ?

**Comment by mlaventure** [comment]
Aside the automatic removal part, yes.

I'm personally against having docker having a GC for unused on disk resources though.

**Comment by LK4D4** [comment]
I'm against too. Closing :)

**Comment by Hubbitus** [comment]
In what version of docker it should be present?

**Comment by JonasT** [comment]
@Hubbitus it should be in `1.13.0`: https://github.com/docker/docker/pull/26108#issuecomment-276111241
