### ISSUE TITLE
Installation instructions fail on Ubuntu 14.04

### ISSUE THREAD

**Issue by dsyer** [docker/docker#18629]
I'm just following steps at https://docs.docker.com/engine/installation/ubuntulinux/

```
$ sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF7
[sudo] password for dsyer: 
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.A9tOMKEJ1n --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/docker-maint-testing.gpg --keyring /etc/apt/trusted.gpg.d/git-core-ppa.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF7
gpg: "58118E89F3A912897C070ADBF7" not a key ID: skipping
```

once that fails the next step cannot be completed (the `apt-get update` fails).

**Comment by thaJeztah** [comment]
Looks like you only partially copied the instructions; it should be `58118E89F3A912897C070ADBF76221572C52609D`, not `58118E89F3A912897C070ADBF7`;

These are the instructions from that page (wrapped for readability):

    sudo apt-key adv \
      --keyserver hkp://p80.pool.sks-keyservers.net:80 \
      --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

I'll close this issue, because it looks like a copy/paste error, but feel free to comment here after I've closed
