### ISSUE TITLE
Possibility of manual patch?

### ISSUE THREAD

**Issue by heycalmdown** [docker/docker#18652]
Using save and load I can move images from a host to another.
Using docker/distribution I can deploy images with its delta only.

So how about mix them?

Case study:

In a reality of Asian network, we occasionally lost direct connection between countries such as Korea-China or Malaysia-Singapore or so on. I need to handle 7~8 countries in Asia. At those time I move images on public network by ftp-like thing. But multiple images' size easily goes up to multi GB.

If I can move its delta only without distribution, it'd be nice.

**Comment by thaJeztah** [comment]
I think similar proposals can be found here; https://github.com/docker/docker/issues/247 (for docker engine), and here: https://github.com/docker/distribution/issues/1100 (for registries).

However, I don't think this is something that should be handled by the docker daemon; the "registry" (distribution) is for distribution of images. If you want to optimize transport of save/load and export/import, I think it's best to use an external tool for that. Basically those exported files are tar-bals, so it should be possible to do some optimization there.

I'm going to close this issue, because the existing issues cover "p2p" transfer, and other optimizations can be done as an external tool. Feel free to comment here after I've close this issue!

**Comment by heycalmdown** [comment]
Okay, thanks.
