### ISSUE TITLE
Proposal : Container alias

### ISSUE THREAD

**Issue by mavenugo** [docker/docker#18699]
Container network module (CNM) provides network isolation and automatic container name resolution across hosts without the container start dependency issues (as seen in links). As of 1.9, every container in a network can reach any other container using its name. But, there has been a few requests to support container name aliasing. There are 2 types : **Network scoped alias** & **Local scoped provider alias**. The proposal is to support both these alias types using the upcoming embedded DNS support.

### Network scoped alias

This feature will allow the user to provide alternative names / aliases for that container. 
example : `docker run --net=mh1 --name=c1 --alias=a1 --alias=a2 ...`.
Being network scoped, the same container can have different aliases when connected to another network. 
example : `docker network connect mh2 c1 --alias=a3 --alias=a4`.
Other containers in that network will be able to reach the container using its name or aliases scoped to that network.

additional points : 
* User will be allowed to configure same alias name to multiple containers in the same network. The initial implementation will NOT perform automatic load-balancing. We will start with best-effort (or) multiple A records followed by proper load-balancing in the later releases.
* If a container belongs to multiple networks and if multiple containers (across networks) have the same alias, then the resolution priority  will be determined by the DNS resolution logic.
* Need help in finalizing the UX. Some initial options : `--alias`, `--resolve-as`, `--host-alias`, `--hostname,` etc... 

### Local scoped provider alias

This feature will allow the user to provide alias for another container (provider). this is similar to the alias support in links. This provider aliasing is local to that consuming container. This enables the consuming application to remain unmodified and consume a service with its preferred name even if the providing service exposes itself using a different discoverable name. Example : 
`docker run --net=mh1 --name=c2 --container-alias=c1:provider1`
and
`docker network connect mh2 c2 --container-alias=c3:provider2`.
In this case, the application running in container c2 can use `provider1` to access container c1 running in network mh1 and use `provider2` to reach container c3 in network mh2.

additional points : 
* Since this is a consumer-localized alias, the aliased name of a service must be restricted only to that consumer-container. We will support that using server-side search domain with the resolution priority managed and maintained by the embedded DNS server.
* If a container belongs to multiple networks and if multiple containers (across networks) have the same alias, then the resolution priority  will be determined by the DNS resolution logic.
* Need help in finalizing the UX. Some initial options : `--container-alias x:y`, `--resolve-as x:y`, etc...

### alias is not link

Though the `Local scoped provider alias` feature looks similar to the alias feature provided by link, the similarity ends there. In order to maintain backward compatibility of links, we are not planning on reusing `link` keyword as the way to provide `Local scoped provider alias` for user defined networks (`bridge` network will continue to support link as it is today). `Link` also uses other static mechanisms such as injecting environment variables. Whereas, networks and aliases are dynamic in nature and hence injecting environment variables into containers will not work. Also, we will be using embedded DNS for all of the name resolution while links use /etc/hosts mechanism. Hence we should not be reusing `link` option for this feature. 
Though we are proposing `--alias` as an engine UX, compose and higher level systems can choose to call it `link` the same way it has been used in the apps and it can make use of `network` and `--alias` as the way to achieve its `link` functionality (minus ENV variables).

**Comment by sanimej** [comment]
> If a container belongs to multiple networks and if multiple containers (across networks) have the same alias, then the resolution priority will be determined by the DNS resolution logic.

For container name resolution in the embedded DNS server each network is considered to be a domain. So in this case the IP returned will be the first network in which the lookup was done. There is no defined order for the network domain lookup; hence the user shouldn't make any assumptions about which IP will be returned in this case.

**Comment by aanand** [comment]
FYI, I don't think Compose should continue to use the `links` key but with the implementation swapped out to use networks + aliases, for the same reason that Engine will not repurpose `--link` - it doesn't behave exactly the same (mainly: no environment variables).

Since we're already planning to make people change their Compose files if they want use networking, it's a good time to switch them over to a different syntax for declaring consumer-local aliases.

**Comment by thaJeztah** [comment]
Just had a quick chat with @mavenugo, and I like the general idea. I'll read through it more carefully, but overal "+1"

**Comment by thaJeztah** [comment]
ping @docker/maintainers this is a proposal to provide an alternative to "links" in custom networks, please check and comment

**Comment by mavenugo** [comment]
@thaJeztah just to be clear, it is not an alternative to `links` :) it is just an alternative to the alias feature provided by links. The rest of the connectivity and discovery are all in place from 1.9 release.

**Comment by stevvooe** [comment]
@mavenugo Rather than try to build a model that let's one influence the mapping of container names in DNS, why not expose the DNS mapping directly as part of the network configuration? I'm guessing these could be A names in DNS, pointing at SRV or CNAME records. Seems like aliases on a global-level overlaps quite a bit here.

Regarding the local aliases, that makes sense to be able to remap remote containers to local link names, if I understand correctly. On a "global" level, it just seems very odd to have control of this at the engine level.

**Comment by mavenugo** [comment]
@stevvooe 
> Rather than try to build a model that let's one influence the mapping of container names in DNS, why not expose the DNS mapping directly as part of the network configuration?

Technically that is correct. But, we are not exposing the DNS configuration details to the operators. It is currently abstracted away behind the docker UX / API. Infact, we were using `/etc/hosts` records till 1.9 and DNS implementation is underway. But I believe that is implementation detail that the UX must hide.

Having said that, the Container local alias is the important requirement, while the global alias is part of this proposal due to the request : https://github.com/docker/libnetwork/issues/737.

BTW. `global` level is still namespaced at the `network` boundary and any such global aliasing must ensure that boundary. Yes, it can be made as network configuration instead of engine configuration. But that doesn't have a smooth user experience. Having said that, am open to that suggestion, since the mapping is infact eventually consistent across hosts and it is not bound strictly to container life-cycle.

**Comment by stevvooe** [comment]
It really sounds like this alias addition should only be local.

Building a half-baked implementation of global aliases sounds like it belongs in service discovery. Getting that right is challenging and the alias model may not go far enough for it work correctly in all cases.

**Comment by mavenugo** [comment]
@stevvooe I actually agree with that assessment as well.

let me ping @dnephin @aanand & @dave-tucker to make sure they are fine with that as well from a compose requirement standpoint.

**Comment by adamtulinius** [comment]
If going with the "Local scoped provider alias"-option, a really basic usecase seems to be forgotten (I think; I have a really hard time figuring out what the proposal really means, with all these mentions of a producing and a consuming container):

Environments where the container name can't be controlled, when using Mesos among others, really just need to be able to overrule the name from --name when starting the container. No need to have actual aliases (since the value from --name is going to be gibberish anyways), just a simple override.

Whatever solution is chosen, I really hope this will be possible.

**Comment by mavenugo** [comment]
@adamtulinius this proposal is not about overriding the --name. But to provide container aliases.

PTAL https://github.com/docker/libnetwork/issues/737#issuecomment-158229066 (I think it mentions the mesos use-case that you are looking for) which is addressed by the `Network scoped alias` section in this proposal. Will this satisfy your use-case ?

**Comment by adamtulinius** [comment]
> @adamtulinius this proposal is not about overriding the --name. But to provide container aliases.

I'm sorry; I thought it was two closely related proposals :-)

> PTAL docker/libnetwork#737 (comment) (I think it mentions the mesos use-case that you are looking for) which is addressed by the Network scoped alias section in this proposal. Will this satisfy your use-case ?

I think so.

**Comment by mwootendev** [comment]
+1 I have a definite need for this.

**Comment by calavera** [comment]
I'm going to be honest, I really really really don't want to add a 4th flag to `docker run` to manage container name-ish, regardless the context. `--name`, `--link` and `--hostname` are plenty of flags to name containers for different contexts. Modifying those flags to support new functionalities might be better than adding yet a new flag.

I would think again about @dave-tucker's proposal in https://github.com/docker/libnetwork/issues/737#issuecomment-160202956. It sounds like a good starting point. If backwards compatibility is stopping us, maybe we should have very clear why we need to keep it in this very specific case and consider if it's really worth it.

**Comment by tianon** [comment]
IMO, if Docker's going to be running a DNS server, then it only makes sense
to expose ways for the user to control that DNS server in interesting ways,
including having it return custom records for their own purposes (since a
DNS server is so firmly in the service-discovery realm).

**Comment by dnephin** [comment]
> Having said that, the Container local alias is the important requirement, while the global alias is part of this proposal due to the request : docker/libnetwork#737.

@mavenugo why do you say that container local aliases are the important requirement? 

Given that:
* neither of these are backwards compatible with links
* we don't want to carry over the limitations of links
* either of these options satisfy the minimum requirements from compose

I would say that one or the other is required, but I don't see a reason that "container scoped alias" is the required option. It seems counter-intuitive to me that containers on the same network would find different containers for the name "db". This was a side-effect of links, but I don't see how it's a feature.

I think the "Network scoped alias" is a better option because it doesn't have any of the limitations of links, and is a simpler implementation. 

> It really sounds like this alias addition should only be local.

> Building a half-baked implementation of global aliases sounds like it belongs in service discovery. Getting that right is challenging and the alias model may not go far enough for it work correctly in all cases.

@stevvooe by local do you mean local to a container or local to the network?   Both options are effectively trying to solve the discovery problem. I don't think any solution is going to solve the problem for all cases, but this proposal takes care of bridging the gap in functionality we lost from links, which is what is important right now.

**Comment by dnephin** [comment]
> I really really really don't want to add a 4th flag to docker run to manage container name-ish, regardless the context. --name, --link and --hostname are plenty of flags to name containers for different contexts. 

> I would think again about @dave-tucker's proposal in docker/libnetwork#737 (comment). It sounds like a good starting point.

That proposal covers why we can't use `name`, but I think the suggestion to use `hostname` is a mistake. It changes the purpose of `hostname` from an internal identifier to being the discoverable name. It would satisfy the "network scoped alias", but I think it's somewhat counter-intuitive since you would expect `--hostname` to only set `/etc/hostname`.

Using `hostname` instead of `name` as the default discoverable identifier is a tangent I think, and not really relevant here. We're not really concerned about the default, more about being able to specify multiple names. I agree it would make more sense to use hostname, but it's too late for that since 1.9 is using container name already.

We can't use `link` because it doesn't work the same way, but I think it is designed to solve the same problem. My understanding is that we would remove `link` in the future, so we'd be back to having just 3 options, but we give users a chance to migrate off of `link` incrementally, instead of forcing them off during an upgrade, or breaking things by changing the definition of `link`.

Do you think it's reasonable to add a new flag if it means adding documenting the deprecation of `link` at the same time?

**Comment by mavenugo** [comment]
@tianon @stevvooe though we are working on having an embedded DNS server (to replace /etc/hosts based name resolution), we are not at the point yet to make it a general purpose entity and allow custom records. It can certainly be considered for the future when we have a strong SD functionality implemented end to end. In the current state, I would prefer to hide that detail behind the docker UX and provide just the required functionality.

To @calavera's point, we can try and avoid new UX options. But before getting to specifics of these UX option, I would like to get the general feedback on : 

1. Does it make sense to provide both of the alias functionality proposed here (Network scoped and Container-local scoped) ?
2. Is it a good idea to reuse existing user-facing entities (such as `link` and `hostname`) and implement these proposed new functionalities, which will end up breaking backward compatibility (such as no ENV variable injection for link & incorrect `/etc/hostname` update, etc...) ?

**Comment by jippi** [comment]
:+1:

**Comment by ByteFlinger** [comment]
1 - Any system making use of this new alias functionality will have to be designed around it (as it does not exist today) and therefore could be designed around a globally scoped alias. Wouldn't a locally scoped alias only provide a more user friendly function (simpler parent -> child relationship naming, such as "db") which can be achieved with a global scope anyway?

2 - Any new functionality will not behave the same as before so personally I think that is not a good idea, thought I guess some people aren't so keen on yet more flags...

**Comment by icecrime** [comment]
> 1. Does it make sense to provide both of the alias functionality proposed here (Network scoped and Container-local scoped) ?

Do we have a choice if we want docker-compose to work? Given that the service name in a `docker-compose.yml` is distinct from the actual container name, and that we want to support both legacy links (a.k.a container-local scoped) and the new networking model (a.k.a network scoped), I don't really see an alternative here (unless we accept a backward incompatible change to links, cf. question 2).

> 2. Is it a good idea to reuse existing user-facing entities (such as link and hostname) and implement these proposed new functionalities, which will end up breaking backward compatibility (such as no ENV variable injection for link & incorrect /etc/hostname update, etc...) ?

Breaking backward compatibility as in "my docker-compose.yml doesn't give me the expected result anymore because I used to rely on ENV variable injection" is not an option. Extending the meaning of existing flags to avoid adding a *n*th flag which deals with name related stuff is worth exploring.

**Comment by aanand** [comment]
OK so it seems like it's worth making this clear: we can preserve backwards compatibility without *any* aliasing features. Legacy Compose files with links will continue to work, because Compose will not attempt to use networks when spinning them up: every container will still join the bridge network, and links (including environment variables) will still work.

In order to use networks, users will have to upgrade their Compose files to the v2 file format. The question is: how smooth can we make that upgrade path? Some scenarios:

1. `links` continues to work for users exactly as it does today, including environment variables, but the implementation is swapped out for networks. This one sounds unlikely to actually happen.

    ```yaml
    version: 2
    services:
      web:
        build: .
        links:
          - postgres:db
      postgres:
        image: postgres
      ```

2. As above, but environment variables go away. This sucks for people using them, and there's no way for us to know whether the application code is expecting them, so we can't do any kind of targeted warning.

3. `links` goes away and is replaced by a new config option for container-local aliasing. It's functionally the same as scenario 2, but because it's a *new option*, we're forcing people to pay attention to the upgrade docs and therefore have an opportunity to warn them about env vars not being there any more.

    ```yaml
    version: 2
    services:
      web:
        build: .
        local_alias:
          - postgres:db
      postgres:
        image: postgres
      ```

4. `links` goes away. We add a new config option for network-wide aliasing, so each service can publish as multiple names. It should cover most people's needs, but there'll be scenarios where it doesn't work (e.g. two services expect to be able to reach to a `db` host, but each one needs to be hooked up to a *different* service).

    ```yaml
    version: 2
    services:
      web:
        build: .
      postgres:
        image: postgres
        alias:
          - db
      ```

5. We provide both options described in 3 and 4.

**Comment by mavenugo** [comment]
to map the proposal with @aanand's compose requirement comment above, this proposal addresses 
1, 3, 4 (and 5) above.

**Comment by icecrime** [comment]
Thanks for clarifying @aanand. I would currently think option 3 maps more closely to what links are today, so I would lean toward this one. And *maybe* (**maybe**) that means we could reuse the `--link` Engine flag, but document that ENV variable injection only happens when used over bridge network?

**Comment by tianon** [comment]
I agree with @icecrime, per-container aliases of other containers sounds great -- I personally really like links because as-is a one-directional connection covers a huge number of use cases (some service that has some kind of database).

**Comment by thaJeztah** [comment]
Yes, I think per-container aliases are a great way to re-use standard "building blocks" (containers/services) with minimal configuration. i.e., I *know* the database is reachable through `db`, without worrying about *other* db's on the same network. Loosing automatic sharing of environment-variables should not be the biggest hurdle, permits properly documented.

**Comment by mavenugo** [comment]
@icecrime @tianon @thaJeztah thanks for your valuable feedback. Since we are evaluating reusing `link`, lets do a full disclosure on the behavior changes

1. no ENV variable injection
2. Name resolution using DNS server (not /etc/hosts)
3. `--ICC=false` daemon flag may not be honored for user created networks (for non-bridge drivers)
4. container start dependencies will not be strict. (Containers with local-aliases can come up in any order and the resolution will happen dynamically as the container is brought up).

With these changes, are we still inclined in reusing `link` over introducing a new flag ?

**Comment by cpuguy83** [comment]
Would `--link` create a network specifically for the two containers?
Would `--link` error out if the the specified container is not part of the new container's `--net`?

**Comment by mavenugo** [comment]
@cpuguy83 
If your question is to understand the existing behavior, `--link` is not compatible with user defined networks and we retain the link behavior only on the default `bridge` network.

If your question is on the behavior change that would introduce by this PR if we reuse `--link`, then 

> Would --link create a network specifically for the two containers?

No

>  Would --link error out if the the specified container is not part of the new container's --net?

No. If I understand @icecrime @thaJeztah @tianon they are interested in reusing link only for the alias feature. But all other cases (including these will not be honored). Infact, these are some of the reasons why this proposal is not trying to reuse link for the alias capability.

**Comment by sanimej** [comment]
> container start dependencies will not be strict. (Containers with local-aliases can come up in any order and the resolution will happen dynamically as the container is brought up).

Is this also a Compose requirement ? Doing the dependency check has some conveniences for the user, like catching typos in the service name.

**Comment by moxiegirl** [comment]
Prior to @calavera's comment it looked like the UX was going to be a bit of a worry from a docs perspective.  Like the current direction from a UX perspective.  Once implemented,  major UX plus if the CLI returns an info message when people use the new/improved `--link` flag.  

As an aside, we already prepped users from some change around `--links` in the current docs.  I refer to them as "legacy links` and prominent disclaimers where applicable:

![image](https://cloud.githubusercontent.com/assets/1347209/11962801/7dd0a1b6-a897-11e5-8b83-354b7727d12a.png)

**Comment by icecrime** [comment]
Here's my proposal, of which I'm going to be honest I'm not fully convinced myself.

> **Definition:** links are a way to express unidirectional dependency of one container (the parent) to another (the child), for example of an application to a `postgres` database container. As part of a link definition, the *parent* container can be attributed a symbolic name which the *child* container can use to refer to it (e.g., `docker run --link postgres:db --name myapp myapp` makes `db` an alias for `postgres` specifically in the context of the `myapp` container).

> **Legacy links behavior:** when using single-host (a.k.a bridge) networking, links behave by additionally sharing environment variables from the parent container into the child container. (to be completed with other legacy differences such as the use of `/etc/hosts` and such)

Those that makes sense? Do you think that reusing the name is too confusing? My feeling is that all aspects of legacy links besides network connectivity are so niche that it's fair to assume a huge majority of people won't even feel a difference.

**Comment by moxiegirl** [comment]
Alternatives to "link"
`--byname`
`--handle`
`--nickname` 
`--pet-name`

`--byname` is my favorite I think because there is nothing about it that implies bi-directionality.  Metaphor "You know him as Arnaud. I know him as icecrime"

**Comment by thaJeztah** [comment]
`--connect`?

**Comment by moxiegirl** [comment]
`connect` can connote bidirectional  and it is a more general term.  Kinda lacks the implied metaphor of `byname` or `nickname` or even `handle` -- the last being a bit military.

**Comment by nazar-pc** [comment]
:+1: to proposal and `#5` from https://github.com/docker/docker/issues/18699#issuecomment-166363166

Local scoped aliases gives more precise control, but are unnecessary more complex than network scoped aliases for simpler use-cases. Eventually, it is possible to use multiple networks and then local scoped aliases can be avoided completely. Need specific link - create network for that.

Containers that are aware of such cases might have env var to specify target alias of service to be used in specific instance, I already have that in my images and it works fine. I'm currently using `/etc/resolv.conf` manipulations for dynamic injection of Consul's instances IPs within the same network (heavily relying on `/etc/hosts` changes by Docker Compose).

**Comment by ByteFlinger** [comment]
I also like proposal 5 from #18699 and on top of that,  is there a reason to introduce 2 different flags instead of one? You could maybe have only an "alias" flag and if the user supplies a colon in the string,  it is locally mapped otherwise network mapped (kind of like some docker flags already work, such as - - volume on docker run command)

**Comment by icecrime** [comment]
After more thinking and discussions about it, my recommendation is to:

- Move forward, hopefully for Engine 1.10, with per-container, local aliasing support. This is the most urgent as it unlocks full networking support in Compose. For this, I suggest we reuse the `--links` CLI flag which, for the most important aspect, will preserve its meaning.
- We hear there's a use case for global aliases, but it's trickier, and overlaps with the broader concept of services.

**Comment by tianon** [comment]
Perhaps as a middle ground, we could supply some of the non-IP-related
environment variables with "--link" ?  Using the environment variables as
an indicator of a link being set up has been useful, so I'd hate to see
that go completely away.  Having the registered environment variables of
the linked container passed through is definitely useful for automatic
configuration, but it is pretty controversial too.

**Comment by mavenugo** [comment]
thanks @icecrime. I will start to make progress on `local scoped alias` to help compose exit experimental for the networking support in 1.10.
We can continue to discuss on the global alias here or in another issue so that we get a full picture especially it seems to overlap a lot with the concept of services. We dont want to end up introducing a sub-standard version of service and suffer compatibility issues in the future.

**Comment by mavenugo** [comment]
@tianon we are thinking of using SRV records for such variables (but not targeting 1.10). As you know ENV variables injection is static, whereas network connectivity is dynamic (using the `network connect` UX). Hence I would prefer to not consider that for this use-case.

**Comment by tianon** [comment]
Right, I realize that -- that's why I was specifically talking about
the non-IP-related environment variables (for example, "--link mysql" will
create "MYSQL_NAME", "MYSQL_ENV_...", etc).

**Comment by mavenugo** [comment]
@tianon since these local aliases are network specific and we are planning on supporting the alias for both `docker run` (during container start time) and `docker network connect` (which is essentially dynamic network connection - after the container has started), injecting the env variables for the dynamic connection case will not work. Also, since we support multi-host networking, we need a way to distribute these environment variables (have to check all the variables that we support) across the cluster. Since we have migrating away from /etc/hosts to DNS (for both name resolution and alias), we are planning on using the SRV record as the dynamic way to provide service records for the networks a container is connected to. AFAIK, the only way one can inject the env variable is before the container is run. Once it is up and running, injecting these variables will not have any effect.

**Comment by cpuguy83** [comment]
One thing we should be able to do with this aliasing is have a way to update the alias such that if the linked container is replaced the consumer can use the new container.

**Comment by tianon** [comment]
Ok, fair enough.  How about TXT records?

**Comment by mavenugo** [comment]
I guess that depends on the variable itself. If it arbitrary and unformatted, TXT records is applicable. But SRV records fits the cases mentioned in rfc2782. and advanced applications which makes use of SRV will work without any changes.

**Comment by sanimej** [comment]
@cpuguy83 
> One thing we should be able to do with this aliasing is have a way to update the alias such that if the linked container is replaced the consumer can use the new container.

It will happen automatically. With the DNS based name resolution, the alias will just be a reference to the actual linked container's name. Actual name resolution will be for the linked container's name and it will have the correct reachability info.

**Comment by yank1** [comment]
I want to ask a question.

In my production environment, we monitor the /etc/hosts by [inotify](https://github.com/go-fsnotify/fsnotify). If it changes, My program will rescan it to see which container in my network. And then change the Nginx config file with name pattern.

It's very useful, because I can automaticly config a Load Balance with Docker Compose scale command.

Will it still work in the future? Or I can do it with another way.

**Comment by thaJeztah** [comment]
@yank1 probably better to listen to docker events, and use something like https://github.com/jwilder/nginx-proxy/ or https://github.com/EmileVauge/traefik.

**Comment by nazar-pc** [comment]
It would be better if it would not be so fragile. I'm personally also heavily rely on `/etc/hosts` modifications because it doesn't require any access to docker host and is completely within container.
If there will be any Docker-specific `/proc/*` directory to track such changes or any other events source I'd be glad so see that, but there is no easy alternative otherwise.

I have set of Docker images where all you need to use them is just `docker-compose up -d` and no access to any files from host - you can scale anything anyhow and it just magically works, for instance `docker-compose --x-networking scale mariadb=20` will result in cluster from 20 MariaDB instances and HAProxy instance will automatically recognize changes and will balance load across these 20 instances. If we lose it - we'll be extremely sad.

**Comment by thockin** [comment]
There is no reasonable way to atomically update files across namespaces.
Docker could invent its own protocol here, eg, write a flag file that
indicates that a non-atomic update is done, or could cross namespace
boundaries, but those are pretty ugly options.

**Comment by nazar-pc** [comment]
I think something like `/proc/docker/networks/<network_name>/containers/<container_id>`, `/proc/docker/networks/<network_name>/hosts/<hostname>/<container_id>`, `/proc/docker/networks/<network_name>/aliases/<alias>/<container_id>` (where target file contains IP(s) of container withing mentioned network) and/or similar can be provided by Docker engine itself so that it will not overlap with neither `/etc/hosts` nor DNS itself, but would allow any container to inspect configuration of network(s) it has access to and respond to changes using tools like inotify.

**Comment by thaJeztah** [comment]
@nazar-pc it sounds like you're looking for an introspection feature, such as proposed here; https://github.com/docker/docker/issues/8427. I don't think we should conflate those discussions

**Comment by aanand** [comment]
I made an error of omission when describing Compose's requirements, so let me hopefully explain the situation a bit better.

We want to move people away from using links and towards a setup where:

1. Every container joins an app-wide default network.
2. A container for each service is reachable by other containers on that network at a hostname identical to the service name. *(This might, in future, become a proxy container which load balances over all available backends, if there's more than one, but that's a discussion for another time.)*

**Old world:**

```yaml
foo:
  image: user/foo
  links: ["bar"]
bar:
  image: user/bar
```

- Every `foo` container can access a `bar` container at the hostname `bar`
- `foo` containers are unreachable from any other containers in the app

**New world:**

```yaml
foo:
  image: user/foo
bar:
  image: user/bar
```

- Every container in the app can access a `foo` container at the hostname `foo`
- Every container in the app can access a `bar` container at the hostname `bar`

On top of this base requirement, we might want to add the ability to define extra network-wide or container-local aliases, but **this behaviour is the most important one to have on day 1**, because it represents a fundamental change to how users write Compose files.

It's a very good idea to couple this change to the [new Compose file format](https://github.com/docker/compose/issues/2504), because that'll give us a clean break. Users of the old file format will continue to get the old behaviour, without any networks at all, while users of the new format must delete their `links` and possibly update their application code.

After discussing this with @dnephin, we feel that if all Engine provides is container-local aliases, this behaviour becomes – if not impossible – then at least difficult and unwieldy to implement, because we're essentially implementing network-wide aliasing *using* container-local aliasing:

1. Every container must be created with a set of aliases to other containers which may or may not exist yet:
    - Each `foo` container must be created with an alias from the container name `myapp_bar_1` to the hostname `bar`
    - Each `bar` container must be created with an alias from the container name `myapp_foo_1` to the hostname `foo`
    - And so on - each service in the Compose file adds another alias to every container
2. When scaling a service beyond one container, or when a new service has been added to the Compose file, we must either recreate every existing container to add new aliases to it for the new containers or use the new [update functionality](https://github.com/docker/docker/pull/15078), assuming that can be made to support the adding of new aliases to an existing container.
3. If we allow the user to specify multiple networks in the Compose file, the number of local aliases could multiply even further, as you'd need one alias per container, per network that container's connected to, per other container on that network.

Given all of this, I think Compose's requirements constitute a strong argument for network-wide aliasing. Without it, rolling out the v2 Compose file format will either depend on implementation work that adds a ton of complexity, or it will have to simply be pushed back until the next release, and networking in Compose will remain in the experimental state.

**Comment by tiborvass** [comment]
*Collective review*

@mavenugo said he would push the code ASAP and we would review it there.
As far as design is concerned, having a global alias seems okay. Not sure about UX, because `--alias` feels like something that could be used instead of `--name`, when in fact it is only a networking feature.

Also, not enough people voiced their opinions.

**Comment by dnephin** [comment]
If the only issue is the cli UX we could just omit it from the cli for now. We only really need it in the API.

**Comment by tiborvass** [comment]
@dnephin good point, and I think we should do that if we want it for 1.10. Maybe with madhu's PR we will be able to play a bit more with it.
