### ISSUE TITLE
Error response from daemon: Cannot start container

### ISSUE THREAD

**Issue by naffan2014** [docker/docker#18709]
docker run -i -t centos /bin/bash
Error response from daemon: Cannot start container f4426a648e255a877439a0e8545cc0fd2cf7ce6658c379a124db4a6f2181bb7d: no such file or directory

how can i do?

**Comment by naffan2014** [comment]
centos 6.5    kernal 2.6.32-358.6.1.el6.x86_64

**Comment by thaJeztah** [comment]
@naffan2014 hm, CentOS 6/RHEL 6 is no longer supported, the last version for those systems is 1.7.1, and that will no longer get patch updates. This could well be a kernel issue.

You could run this script: https://github.com/docker/docker/blob/master/contrib/check-config.sh to check if all requirements for running docker are in place, but other than that, I don't think we'll be able to help you.

I'll close this issue, because CentOS 6 / RHEL 6 is no longer supported, but feel free to comment here after I've closed

**Comment by naffan2014** [comment]
no matter  i sovled it . thank you all the same
