### ISSUE TITLE
Log Tag Variable Not Rendering Properly

### ISSUE THREAD

**Issue by jmhale** [docker/docker#18712]
When using the syslogtag interpolation for `{{.ImageName}}`, the full image name is truncated in syslogtag and the remainder is instead added the message that is sent to syslog, along with the log message. 

If you use `{{.ImageID}}` instead, the ID string remains entirely in syslogtag and does not appear in msg at all.

`docker version`:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 1
Images: 203
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 205
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: OYPI:LLXW:XRF3:TVMG:QI5J:V7YM:O4EE:53U4:SWEF:SUO3:W7JH:KTYG
Debug mode (server): true
 File Descriptors: 20
 Goroutines: 35
 System Time: 2015-12-16T15:56:21.202098879Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
 ```

`uname -a`:
```
Darwin it-15409 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64
```

Environment details (AWS, VirtualBox, physical, etc.):
Docker Machine running on Mac El Capitan using ubuntu:15.10 images.

How reproducible:
Always

Steps to Reproduce:
1. Run a rsyslog container with a template that sends the %msg% and %syslogtag% properties to stdout.
2. Run a vanilla Ubuntu:15.10 container with the `--log-opt tag="{{.ImageName}}"` param.
3. Send a message to syslog using something like `logger test` on the ubuntu container.

Actual Results:
On the Ubuntu container:
```
root@1a189c26e503:/# logger test with ImageName
```
On the rsyslog container:
```
Message: 15.10[1020]: root@1a189c26e503:/# logger test with ImageName
Syslogtag: docker/ubuntu:
```

Expected Results:
On the Ubuntu container:
```
root@240a8ccdea5e:/# logger test with ImageID
```

On the rsyslog container:
```
Message:  root@240a8ccdea5e:/# logger test with ImageID
Syslogtag: docker/5eb72b199374[1020]:
```

Additional info:

rsyslog template:
`$template debug, "Message: %msg%\nSyslogtag: %syslogtag%"`

**Comment by solganik** [comment]
#dibs

**Comment by solganik** [comment]
Hi I had faced the same issue and here is my analysys of the issue cause: 
The Root cause of the issue is that current syslog library (srslog) uses rfc3164 syslog format 
that explicitly distuinguishes between tag and message with ":" character. Since image name in this case is 
ubuntu:trusty the ":trusty" part is considered as part of the message. 
Please find attached link to the rfc page:
https://tools.ietf.org/html/rfc3164

This issue requires recent commit in srslog library:
https://github.com/RackSec/srslog/commit/0d1b0f5f47640add3d70d17c2b0e16c1e44ee794
that allows to select between rfc3164 and rfc5424 log format. Docker needs to choose rfc5424 format in order 
to overcome ":" character ambiguity.

Issue can be reproduced regardless of docker with the following command line :
logger --server=<IP of rsyslog server here> --tcp --port=514 --tag=ubuntu:trusty --rfc3164 log message
by using "rfc5424" format issue is resolved.
logger --server=<IP of rsyslog server here> --tcp --port=514 --tag=ubuntu:trusty --rfc5424 log message
