### ISSUE TITLE
Proposal: Add a `cidfile` flag to docker-build command

### ISSUE THREAD

**Issue by ripcurld00d** [docker/docker#18803]
Proposed in #7727 by @virtuald

> docker run has a --cidfile argument. It's a bit strange that docker build doesn't have a similar thing,
> [...]  a --cidfile option is something that would really only be useful for scripting

Providing this argument can be a nice alternative to the docker-build's quiet mode (read more [here](https://github.com/docker/docker/pull/17428)).

Thoughts?

Thanks.

**Comment by unclejack** [comment]
#17428 was merged. A `cidfile` flag doesn't make sense at all for `docker build` for a few reasons. `docker build` starts and stops multiple containers and there's no single container to have in the `cidfile`. `docker build` also has `--rm` and `--force-rm` flags to ensure containers are always removed, no matter what happens with the build. There's no point in adding such a flag.

The builder code will also be moved out of the Docker daemon. This means it'll be possible to do all kinds of things. This will most likely allow doing quiet builds and the retrieval of the logs of the container which has halted the build.

I'll close this now since it doesn't make sense to implement this now. Please feel free to comment.

**Comment by thaJeztah** [comment]
@unclejack I think the intent here was to write the *image-id* to a file (`--imgid-file`?). But agreed to wait for the builder to be moved out

**Comment by virtuald** [comment]
Yes, the intent was to write the image id to a file, that way you don't have to create unique container names or parse the output of docker build, etc.
