### ISSUE TITLE
Really Need help with Docker on Windows 7

### ISSUE THREAD

**Issue by txappmkr** [docker/docker#18815]
Need help with Docker on Windows 7.
```
>Docker Version 
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      windows/amd64
An error occurred trying to connect: Get http://localhost:2375/v1.21/version: di
al tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the ta
rget machine actively refused it.
```
```
>docker info
An error occurred trying to connect: Get http://localhost:2375/v1.21/info: dial
tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the targe
t machine actively refused it.
```
```
UName -a
MSYS_NT-6.3 XXXXXXL 2.3.0(0.290/5/3) 2015-09-29 10:48 x86_64 MSYS
```

```
C:\Program Files\Oracle\VirtualBox>vboxmanage -version
5.0.12r104815
```
With Oracle Ext Pack, Oracle_VM_VirtualBox_Extension_Pack-5.0.12-104815

```
C:\Users\>docker-machine ls
NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS
```
Docker quick start always fails with
```
Creating Machine default...
Looks like something went wrong... Press any key to continue...
```
Kitematic Fails with
```
Encountered an error: Error: Command failed: C:\Program Files\Docker Toolbox\docker-machine.exe -D create -d virtualbox --virtualbox-memory 2048 default,Docker Machine Version: 0.5.4, build 6643d0e,Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:61936,Error loading driver "virtualbox": dial-http tcp 127.0.0.1:61936: read tcp 127.0.0.1:61937->127.0.0.1:61936: wsarecv: An existing connection was forcibly closed by the remote host.,
```

Checked for standard ways without success, facing this issue from Docker Toolbox 1.8.* onwards.
Reinstalled multiple times from 1.9.1a multiple times, still facing this issue.
Please point me in the right direction, 
Resinstalled both Virtual Box, ExtPack,Docker in the same order multiple times.

**Comment by thaJeztah** [comment]
Have you tried installing the latest version of docker toolbox? The current release is 1.9.1f; see https://github.com/docker/toolbox/releases/ (https://github.com/docker/toolbox/releases/tag/v1.9.1f)

Also, looks like you're connecting to "localhost", have you tried running `docker-machine env default` and follow those instructions to make sure the environment vars are set up properly?

In any case, this looks to be an issue with docker-machine or docker-toolbox, could you check the issue tracker there to see if there's an existing issue? issues mentioning "forcibly" ; https://github.com/docker/toolbox/issues?utf8=✓&q=is%3Aissue+%22forcibly%22+

And "actively";
https://github.com/docker/toolbox/issues?utf8=✓&q=is%3Aissue+actively+

I'm going to close this issue here, because unfortunately we cannot solve this in this repository, as it should be (or may already be) solved in docker-machine or toolbox. Feel free to comment here after I've closed this issue :+1:
