### ISSUE TITLE
Mac OSX Quickstart start.sh Doesn't Detect Shell at Non-Standard Path

### ISSUE THREAD

**Issue by brian-dlee** [docker/docker#18886]
The version of bash that I use on my Mac is installed at /usr/local/bin/bash, so when I run the Docker Quickstart Terminal it fails to detect I'm using bash and starts the shell without the `--login` option. Since it is not started as a login shell, it doesn't load my `.bash_profile`. I've modified my own `Docker Quickstart Terminal.app/.../start.sh` for now, but maybe it should be worked into the code base, so it can be avoided later on.

Here are my changes.

Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh (v1.3.0)
```bash
[OLD]:60: if [ "$USER_SHELL" = "/bin/bash" ] || [ "$USER_SHELL" = "/bin/zsh" ] || [ "$USER_SHELL" = "/bin/sh" ]; then
[NEW]:60: SHELL_NAME=$(basename $USER_SHELL)
[NEW]:61: if [ "$SHELL_NAME" = "bash" ] || [ "$SHELL_NAME" = "zsh" ] || [ "$SHELL_NAME" = "sh" ]; then
```

**Comment by thaJeztah** [comment]
Thanks for reporting, @brian-dlee. Could you reopen this issue in the docker-toolbox issue tracker, because that's where the code for the QuickStart terminal is; https://github.com/docker/toolbox/issues

However, it looks like that script has already been updated;
https://github.com/docker/toolbox/blob/master/osx/mpkg/quickstart.app/Contents/Resources/Scripts/start.sh#L64

So it might be worth checking on the latest release.
