### ISSUE TITLE
Syslog logging driver can't write to DGRAM unix sockets

### ISSUE THREAD

**Issue by dbendelman** [docker/docker#18903]
B"H

I have a local rsyslog that listens on a `/tmp/syslog.sock` unix socket on an EC2 host. I'm trying to get docker to log to this socket but it fails:

```
$ sudo docker run -it --rm --log-driver=syslog --log-opt syslog-address=unix:///tmp/syslog.sock ubuntu:14.04 echo hi
Error response from daemon: Cannot start container f8dbc49cd4177d69c27b13734d6d046ef32471430738bb2ca3306e19c8376a5e: Failed to initialize logging driver: dial unix /tmp/syslog.sock: protocol wrong type for socket
```

Here's the relevant snippet from my rsyslog config:

```
module(load="imuxsock")
input(type="imuxsock" Socket="/tmp/syslog.sock")
```

By default when rsyslog creates unix sockets, it always creates them as SOCK_DGRAM and not SOCK_STREAM:

```
# netstat -nux
Active UNIX domain sockets (w/o servers)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  3      [ ]         DGRAM                    1033577752 /dev/log
unix  2      [ ]         DGRAM                    1033577754 /tmp/syslog.sock
unix  2      [ ]         DGRAM                    1033578652
```

I tried to log something with `logger`, which confirmed that unless I specify that the socket is type DGRAM, it will give the same error:

```
$ logger -u /tmp/syslog.sock testing1
logger: connect /tmp/syslog.sock: Protocol wrong type for socket
$ logger -d -u /tmp/syslog.sock testing2
$
# checking the syslog output, the "testing2" entry was logged properly (but "testing1" never got through due to that error)
```

**Version Information**

```
$ sudo docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

```
$ sudo docker info
Containers: 1
Images: 192
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 194
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 992.5 MiB
Name: syslog-test
ID: [redacted]
Username: [redacted]
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

```
$ uname -a
Linux syslog-test 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```

**Comment by Elemecca** [comment]
I found this issue while trying to solve the same issue you had, although in my case with the standard `/dev/log` socket. It turns out that Go's networking stack, which Docker inherits, is a little strange when it comes to the `unix` protocol scheme. It doesn't just mean `AF_UNIX`, it means `AF_UNIX + SOCK_STREAM`.  If you want `AF_UNIX + SOCK_DGRAM`, you need to use the `unixgram` scheme instead.

In your case that means you want `unixgram:///tmp/syslog.sock` instead of `unix:///tmp/syslog.sock`.

**Comment by Elemecca** [comment]
Or not. As of some recent version (1.9, I think. It worked in 1.8.3) Docker no longer considers `unixgram` to be a valid protocol.
https://github.com/docker/docker/blob/master/daemon/logger/syslog/syslog.go#L127
https://github.com/docker/docker/blob/master/pkg/urlutil/urlutil.go#L14

**Comment by dbendelman** [comment]
Thanks for the insight @Elemecca. Seems like the latest version imposes validation which the `unixgram` trick can't pass.

However, I tried `unixgram` on v1.8.3 and it still didn't work, although there was no error message this time:

```
$ sudo docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64
$ sudo docker run -it --rm --log-driver=syslog --log-opt syslog-address=unixgram:///tmp/syslog.sock ubuntu:14.04 echo hi
hi
$
```

Checking the syslog output, the "hi" entry was not logged. There are other things writing to this syslog server on that same `/tmp/syslog.sock` socket, so the problem is likely with docker.

**Comment by Elemecca** [comment]
OK, looking at the history of those files I linked yesterday, it looks like in Docker 1.8.3 it already didn't consider `unixgram` to be a valid protocol. However, instead of raising an error when an "invalid" URI was provided, it silently acted like none had been provided at all:
https://github.com/docker/docker/blob/v1.8.3/daemon/logger/syslog/syslog.go#L106

That triggered the default connection behavior in the syslog library, which... connects to `/dev/log` as an `AF_UNIX + SOCK_STREAM` socket:
https://golang.org/pkg/log/syslog/#Dial

So it did what I wanted entirely by accident in 1.8.3. In 1.9.1 specifying the "wrong" socket address raises an error, but I can obtain the same behavior by not specifying the address at all.

There are two takeaways from that:
* If you want to connect to the local system's syslog daemon, use `--log-driver=syslog` but don't specify `--log-opt syslog-address` at all.
* The lack of support for `SOCK_DGRAM` sockets in the syslog driver is a real thing, and that feature is something at least two people want.

**Comment by thaJeztah** [comment]
@Elemecca if dgram sockets are known to work, feel free to open a PR to add it to the list of valid protocols I think (speaking for myself) we can accept making that change

**Comment by wzyboy** [comment]
I encountered this issue as well when trying to specify alternative syslog socket. So I opened up a (PR)[https://github.com/docker/docker/pull/21613] to fix this.

**Comment by simaotwx** [comment]
> OK, looking at the history of those files I linked yesterday, it looks like in Docker 1.8.3 it already didn't consider `unixgram` to be a valid protocol. However, instead of raising an error when an "invalid" URI was provided, it silently acted like none had been provided at all: https://github.com/docker/docker/blob/v1.8.3/daemon/logger/syslog/syslog.go#L106
> 
> That triggered the default connection behavior in the syslog library, which... connects to `/dev/log` as an `AF_UNIX + SOCK_DGRAM` socket: https://golang.org/pkg/log/syslog/#Dial
> 
> So it did what I wanted entirely by accident in 1.8.3. In 1.9.1 specifying the "wrong" socket address raises an error (which is a definite improvement), but I can obtain the same behavior by not specifying the address at all.
> 
> There are two takeaways from that:
> 
>     * If you want to connect to the local system's syslog daemon, use `--log-driver=syslog` but don't specify `--log-opt syslog-address` at all.
> 
>     * The lack of support for `SOCK_DGRAM` sockets in the syslog driver is a real thing, and that feature is something at least two people want.

I think this should be the solution – just don't specify the socket.
However, what if you **need** to specify it? This is something that needs to be worked on at some point.
