### ISSUE TITLE
Use under docker1.9 version  Dockerfile to build docker mirror, RUN the gem install fpm ...  error, can not download from rubygems.org

### ISSUE THREAD

**Issue by zxlzh2015** [docker/docker#18913]
Use under docker1.9 version  Dockerfile to build docker mirror, RUN the gem install  fpm  ... error, can not download from rubygems.org

**Comment by thaJeztah** [comment]
Could you provide some more information, and preferably the exact steps to reproduce?

**Comment by zxlzh2015** [comment]
@thaJeztah thanks, my problem has solved, thank you once again

**Comment by zxlzh2015** [comment]
@thaJeztah  My question is as follows:
in Docker1.9.0 Dockerfile in the source file, there is a command is RUN gem install FPM...
Cannot perform the instructions, the reason is unable to access rubygems.org, directly in the rubygems.org is not directly download the FPM,

**Comment by thaJeztah** [comment]
I just tried to `gem install fpm` from inside a container and don't have this issue. Are you using a proxy? I see you're also running into problems when *not* running inside a container (https://github.com/rubygems/rubygems/issues/1426), so I highly suspect this is an issue in your network setup.

I'll close this issue because I don't think this is a bug in docker, but feel free to comment if you think I closed this by mistake
