### ISSUE TITLE
Proposal: when MAINTAINER is changed; don't build the image from scratch

### ISSUE THREAD

**Issue by ripcurld00d** [docker/docker#18921]
When the MAINTAINER instruction is moved to a different line or its value is changed, the image is built all over again.

From what I understand, the MAINTAINER doesn't affect the file-system of the image. Therefore, it's expected that only the image information are going to be updated.

Thanks.

**Comment by ripcurld00d** [comment]
No feedback? :hamster:

**Comment by duglin** [comment]
@ripcurld00d while its true that the MAINTAINER info is just extra metadata about the image, due to how the build process works that metadata isn't just associated with the final build image, rather its associated with the image/layer at that step in the build process.  And this then impacts things like the build cache lookup.  For example, should:
```
FROM scratch
MAINTAINER me@here.com
RUN ls
```
and
```
FROM scratch
RUN ls
```
use the same cached layer/image on the `RUN` step?  I suspect you'd want the answer to be 'yes' and I'm not sure yet if this is an issue or not. The only case I can think of that we might run into problems is when a container (during the build process) can figure out the image it came from and then queries that image for the MAINTAINER info - it'll be empty and that would yield incorrect results.  Definitely an edge case though.

If you really want to explore this it might be an interesting exercise to make the code changes to support this and then see how many testcases fail - if none (aside from ones that should fail) then perhaps its worth considering.

**Comment by justincormack** [comment]
I think `MAINTAINER` is pretty much deprecated in favour of labels now as a way of adding metadata, so I would recommend not using it.

**Comment by ripcurld00d** [comment]
@justincormack then shouldn't we put a note [there](https://docs.docker.com/engine/reference/builder/#/maintainer)? Or at least say something about it [here](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/)?

**Comment by thaJeztah** [comment]
@ripcurld00d have a look at https://github.com/docker/docker/pull/25466 (feel free to comment there with those suggestions if they're not include in the PR yet)
