### ISSUE TITLE
Pulling repository ghost FATA[0006] Could not reach any registry endpoint

### ISSUE THREAD

**Issue by atom2ueki** [docker/docker#18927]
I'm trying to `docker pull ghost:latest` from my docker VPS, but hit an error as below.

##### Docker error:
```Pulling repository ghost FATA[0006] Could not reach any registry endpoint```

##### Docker version: 
```Docker version 1.5.0, build a8a31ef```

##### Docker info: 
```
Containers: 10
Images: 67
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 87
Execution Driver: native-0.2
Kernel Version: 3.13.0-40-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 1
Total Memory: 994 MiB
Name: App-Docker
Registry: [https://index.docker.io/v1/]
```

##### uname -a:
```Linux App-Docker 3.13.0-40-generic #69-Ubuntu SMP Thu Nov 13 17:53:56 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux```

##### System info:
```DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
NAME="Ubuntu"
VERSION="14.04.1 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.1 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

**Comment by atom2ueki** [comment]
Refer to:  [docker-pull-deprecation-for-for-v1-5-clients](https://forums.docker.com/t/docker-pull-deprecation-for-for-v1-5-clients/5071)

which means I need upgrade to v1.6 or higher to resolve the issue.

but is there any official guide to upgrade docker from v1.5 to higher version? since my docker running some production containers.

**Comment by thaJeztah** [comment]
The installation docs explain both how to install and update docker: https://docs.docker.com/engine/installation/ubuntulinux/

However, 1.5.0 was released 10 months ago, and a lot has changed since, so I don't know if upgrading from 1.5 to 1.9 directly will cause problems, so you may want to follow the manual installation procedure, but upgrade to 1.6.2 first, and move from that (http://askubuntu.com/questions/92019/how-to-install-specific-ubuntu-packages-with-exact-version)

I'm going to close this issue, because end of support for 1.5.0 clients on Docker Hub was announced multiple times, so this is expected. I hope the information above will help you further.
