### ISSUE TITLE
Creation of a local volume/container beginning with a '/'

### ISSUE THREAD

**Issue by ColinHebert** [docker/docker#19029]
Currently `utils.RestrictedNamePattern` (dcbd5e0:/utils/names.go)   allows the user to sneak in a `/` at the beginning of the name.

This effectively allows the creation of a local volume starting with a `/`:
```
~ $ docker volume create --name=test/
Error response from daemon: test/ includes invalid characters for a local volume name, only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
~ $ docker volume create --name=/test
/test
~ $ docker volume ls
DRIVER              VOLUME NAME
local               /test
```

Same applies to container names:
```
~ $ docker create --name=test/ ubuntu
Error response from daemon: Invalid container name (test/), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
~ $ docker create --name=/test ubuntu
a50d89a84103c17f2fd4e6ee6c...
~ $ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
a50d89a84103        ubuntu              "/bin/bash"         7 seconds ago       Created                                 test
```
My understanding (after a quick look at the history of that regular expression) is that it's due to the container name that is technically allowed to start with a `/`, which is added automatically if not provided (dcbd5e0:/daemon/daemon.go#L438).

It should be possible to update the regular expression to match what is advertised.

**Comment by thaJeztah** [comment]
Hm, I'll label this as a bug, because even though you can create such volume, docker won't use them, as it assumes volumes starting with a `/` to be a bind-mounted directory.

So,

```bash
docker volume create --name=/foo
docker run -v /foo:/bar ubuntu
```

Will actually use a bind-mounted volume, not the `/foo` named volume

I think this is the result of this regex, which prepends a `/` to be acceptable;
https://github.com/docker/docker/commit/d6d60287ee3a8a064340582d65c131181ae77127#diff-f23da1f8083fdc66ad62a3c2f9c03a16R9

I think there should be a separate regex for volume names.

For container names, I'm not sure, there's been some discussion about the `/` prefix, but I'm not sure what the best approach is there.

**Comment by thaJeztah** [comment]
ping @calavera wdyt?

**Comment by thaJeztah** [comment]
(added to the milestone for discussion, I think it should be an easy fix, but no obligation to solve this in the milestone, as it's probably a corner case)

**Comment by ColinHebert** [comment]
Oooh, I haven't tried it so far, but turns out you can't `docker volume rm` those volumes.
The container is fine though.

**Comment by jfrazelle** [comment]
I'm making a patch for this now

**Comment by thaJeztah** [comment]
This is now fixed, thanks again for reporting @ColinHebert, nice find!
