### ISSUE TITLE
Pass environment variables to container (like with --link)

### ISSUE THREAD

**Issue by curtiszimmerman** [docker/docker#19107]
Talking in IRC about the new networking that came with 1.9, and how it looks like it's going to replace the `--link` functionality, I thought it would be nice if there were some way to decouple the property of `--link` to pass environment variables to the linked container. Just as an example, `--env-from` was mentioned as a possibility. So what `--env-from` would do is just like it sounds, it would have available the environment variables of the specified container.

**Comment by thaJeztah** [comment]
For reference, the new approach is being discussed in https://github.com/docker/docker/issues/18699.

Is there a particular case you're using this for? And which environment-vars would you like to see copied? i.e. the "link" env-vars (e.g. `DB_PORT_5432_TCP_ADDR`) or other environment vars?

Reason we try to move away from those variables is that they are also a security risk, because a container connecting to another container will obtain environment variables that you may not want shared (database credentials), and adding them to each container is easy to achieve, for example, when using docker-compose

**Comment by curtiszimmerman** [comment]
Hi, thanks for that link. I should apologize for explaining somewhat poorly what I was thinking. I had in mind no particular use case, except that I was assisting someone in IRC to move many environment variables into a container from another, for which the "env" file wasn't the optimal solution. So for that particular situation, he was left using a bunch of `-e` CLI opts in his run command. That's what got me thinking about using `--link` as a hack to get environment variables into another container, and originally what got me thinking about a decoupled version of this feature. In particular, I agree with your suggestion that sharing environment variables as it is with `--link` is a security risk. Some part of the `--env-from` might include a list of environment variables somehow, so that you could select only a particular set, instead of the dump which now happens with `--link`.

**Comment by thaJeztah** [comment]
One thing I proposed in the past was using a convention, e.g. env-vars prefixed with `_` would not be shared; https://github.com/docker/docker/issues/5169#issuecomment-40281884

However, if docker-compose is not used, `--env-file` could be a good alternative

**Comment by LK4D4** [comment]
I'm closing this. Links now is not recommended way to connect containers.

**Comment by curtiszimmerman** [comment]
Ah, this feature idea is actually decoupled from the linking functionality. For this, I envisioned only being able to pass environment variables with `--env-from` but without any actual container linking. What I imagined would be a way merely to pass environment variables.

**Comment by LK4D4** [comment]
@curtiszimmerman Feel free to open new proposal with your vision of feature.
