### ISSUE TITLE
explicit bind-mounts for the container

### ISSUE THREAD

**Issue by ibukanov** [docker/docker#19120]
I have a PHP application that uses at least 3 locations in its file system to store various temporary files and configs. The paths are hardcoded and cannot be changed. As I would like to access those files from another container, currently the only options I have is to either create 3 volumes for each location or turn the locations into symlinks into directories and files under the common volume and expose only that. 

The first alternative in unattractive due to complexity and the need to be aware about a particular PHP application directory layout in the second container to look for mount points of volumes. The second is better but it still requires that symbolic links is maintained during software upgrade to make sure that those are not overwritten with files and directories from the software distribution.

What would be ideal if Docker had an option to specify an explicit bind mount between 2 directories in the container in addition to volume mounts. Then I could run the app like:
```
docker run ... -v /volume \
    --bind-mount=/volume/cache1:/opt/php-app/cache \
    --bind-mount=/volume/cache2:/opt/php-app/some-subcomponent/cache \
    --bind-mount=/volume/config-file.json:/opt/php-app/config-file.json ...
```

Here the bind-mounts are created after `/volume` is created and initialized with content and permissions from the image.

**Comment by cpuguy83** [comment]
I'm not sure... the `/volume` in `-v /volume` is _not_ on the host side, it's in the container.

As it is right now, volumes are created in lexicographic order, that is essentially shortest path first, so the longer the path, the later the create/mount.

**Comment by ibukanov** [comment]
@cpuguy83 In my use case I want to bind-mount precisely into container volume, not a host volume. For the host volumes I can effectively already do that, like in:
```
docker run ... \
  -v $(pwd)/foo:/foo 
  -v $(pwd)/foo/bar:/opt/php-app/some-dir 
  -v $(pwd)/foo/bar2.php:/opt/php-app/another-dir/some-file.php  
```
which makes `bar` and `bar2.php` in the `foo` directory on the host to be bind-mounted into arbitrary locations into the container. Then I can expose `foo` into another container and it will see files from both mount points in the first container. I can do that since I know the location of the host-volumes so nested bind-mounts are possible. With non-hosts volumes created by docker I have no such option. 

This is what the issue proposes to fix - an option to bind-mount into docker volumes. Note that mounting in lexicographical order is very fine with me as long as bind-mounts will be done after the docker volume is fully initialized according to the hierarchy in the image.

**Comment by mitchcapper** [comment]
I am sorry but I don't quite understand the full benefit of the additional commands?   you can already specifically specify where you want the mount to go ie:
docker run -v vol1:/mnt/whateverpath1 -v vol2:/mnt/whateverpath1/sub_dir image1
docker run -v vol1:/mnt/whateverpath2 -v vol2:/mnt/test image2


It sounds like your problem with that is the 'complexity' of having 3 volumes for the 3 different paths?   
It sounds like you could just use a shell script inside your container to accomplish the same without adding more commands to docker run (although your sym linking is probably a cleaner way to do so, a startup shell script that validates the correct sym links are there on startup might work well for your situation).

**Comment by ibukanov** [comment]
@mitchcapper The complexity comes when I need to expose those 3 volumes into another container. With `--volumes-from=` that container needs to deal with volumes mounted into paths specific to PHP-application when that second container should know nothing about. Ideally I want to get in the second container a single volume with sub-directories mounted into the first container.

Note that when using symlinks one do not need a startup script. Docker creates them automatically according to the structure in the image. The real drawback is that the structure of mount points is decided effectively when container is built and symlinks are created making the deployment less flexible in addition to the need to recreate the links after the software update.

**Comment by mitchcapper** [comment]
@ibukanov I think volumes from is somewhat on the way out, instead using the -v  on both containers is probably more recommended (its also more clear than --volumes-from).    The only thing it can't do is the different mount paths to a single volume set.

**Comment by LK4D4** [comment]
I think it's possible to solve that with `docker volume`. Implementing new logic in `docker run` would be hell :(

**Comment by iraklisg** [comment]
@ibukanov in https://github.com/moby/moby/issues/19120#issuecomment-169394358 you mention:

> Note that mounting in lexicographical order is very fine with me as long as bind-mounts will be done after the docker volume is fully initialized according to the hierarchy in the image.

Are you saying that, independenlty of the lexicographic order, bind mounts are always done after the volumes? Because i cannot find any reference on this subject :disappointed:

**Comment by ibukanov** [comment]
@iraklisg That was just a reference about a possible implementation with no implications how docker worked at that point.

**Comment by iraklisg** [comment]
ok @ibukanov thank you for your reply. What I am  trying to understand is what order the docker executes different types of mounts (i.e bind-mounts, volumes). From what I have understand, bind-mounts are performed in a lexicographic order (smallest path first). However, it seems that if we use a volume in conjuction with bind-mounts, the volume is mounted first and then the bind-mounts are executed in lexicographic order. Unfortunatelly, there is lack of information on this subject....

**Comment by cpuguy83** [comment]
@iraklisg All container mounts are sorted in lexicographic order.

**Comment by iraklisg** [comment]
@cpuguy83 yes, I have understand that (mostly because of your previous comments :stuck_out_tongue: )

I know that this is not the place for discusing this kind of questions  but, what I am really asking here is if volumes are mounted first (regardless the lexicographic order) and then the bind-mounts. The reason I am asking this is because I cannot find any references in the docker docs and because I noticed a strange behavior when I tried to use a volume in conjunction with bind-mounts. I have also posted a [SO](https://stackoverflow.com/questions/47795937/in-which-order-does-docker-executes-the-bind-mounts-volumes) question describing this bevavior

Again, I do appologize for making general discussion in github issues 

BR

**Comment by cpuguy83** [comment]
@iraklisg volumes are mounts the same as bind-mounts as far as the container runtime is concerned. So binds, volumes, tmpfs mounts, etc... are all lumped together and sorted.

**Comment by iraklisg** [comment]
@cpuguy83 Hmmm, I think (finally) I am starting to understand the process... Let me, please, put my question in another way.... 

In case of trying to run a container with both _bind-mounts_ and _volumes_ , for example:

`docker container run -v /app:/opt/app -v data:/opt/app/foo myRepo/myImage`

does the docker engine performs the following **two** steps ?:

1) Initially, it creates a new storage-space (i.e. `volume`) in the host filesystem (`data/`) for the container to persist files and then (since that newly created volume is _empty_) it copies the files from the container (whatever is inside `/opt/app/foo/*`) to the volume's storage location (`data/`)

2) Then, it performs all mounts (_binds, volumes, tmpfs mounts, etc... are all lumped together_) in lexicographic order (first mounts `/app` to `/opt/app` then `data` to `/opt/app/foo`)

**Comment by cpuguy83** [comment]
@iraklisg Yes.

**Comment by Silidrone** [comment]
Thanks for discussing this guys, it cleares up a lot of confusion. Though I have some case I want to add, take a look at this example:

Host filesystem:
**frontend**
|-- some stuff like src, public etc. BUT NO node_modules exists

Container filesystem **before** the compose is ran, so this is the state after the image build phase:
**frontend**
|-- **node_modules**
|-- some stuff like src, public etc. 

So basically this is my image:
FROM node:20.16.0

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

# COPY does not remove already existing files in the container. It just overwrites the files that are already there, and adds the new files.
COPY . .

EXPOSE 3000

CMD ["npm", "start"]

And I run this in the context of the frontend directory, so my compose is:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/usr/src/app
      - /usr/src/app/node_modules/
    environment:
      - CHOKIDAR_USEPOLLING=true
      
where "../frontend" is the aforementioned frontend with its filesystem layout. Now I understand what happens here. I understand that the original contents of the image (the node modules with the installed modules) will at the end be inside of the container, and that the node_modules of the container will in no way ever be bind-mounted to any host node_modules (if they exist). 

**The unexpected behavior here is that, after I `docker-compose up` an empty node_modules dir is created on the host**
The volume **DOES NOT** exist prior to running the container. Though the same behaviour can be observed even if it does.
And the node_modules **DOES NOT** exist in frontend/ on the host machine. 

Why does this happen? If we follow the process (taking into account that the volumes are mounted in a lexographical order):
1. The initialization happens for the new named volume `node_modules`, so whatever is on the path `/usr/src/app/node_modules` in the container image is now copied over to a new volume storage path on the host machine. At this point, the docker container /usr/src/app/node_modules also contains whatever was in the container image path, because nothing overrode it.
2. Because of the lexical order, the bind-mount happens first, so HERE, I would expect the bind mount to take the node_modules inside the container and map it to the host machine's frontend/node_modules (which didnt exist), effectively resulting in frontend/node_modules on the host machine **TO NOT BE EMPTY BUT HAVE THE INSTALLED MODULES THAT WERE INSTALLED IN THE BUILD PHASE**. 
3. The contents of the named node_module volume's storage from the host are now copied into the associated path in the container, which is /usr/src/node_modules, which is identical, so nothing would change.

If I got the above order correct, I don't see how an empty directory node_modules would be created on the host machine...

**Comment by thaJeztah** [comment]
-  `/usr/src/app` inside the container is a bind-mount of `../frontend` on the host (so `/usr/src/app` inside the container _IS_ `../frontend` on the host)
-  `/usr/src/app/node_modules/` inside the container has an anonymous volume mounted
    - docker creates an anonymous volume, and passes the mount specification to the OCI runtime (`runc`)
    - the OCI runtime must mount the anonymous volume to `/usr/src/app/node_modules/`, but mounting requires a mountpoint; if the path doesn't exist, a directory is created at  `/usr/src/app/node_modules/` to act as mountpoint
    - given that `/usr/src/app/node_modules/` is within `/usr/src/app`, which is (see first bullet) a bind-mount
    - so the `node_modules` directory (mountpoint) is created at `/usr/src/app/node_modules/` inside the container, which is `../frontend/node_modules` on the host
- the anonymous volume is mounted at that location, but within the container's mount namespace, thus only known inside the container; any files writen to  `/usr/src/app/node_modules/` inside the container and up in `<anonymous volume>`, not inside the mountpoint.
- any files writen to `../frontend/node_modules` on the host end up inside the directory acting as mountpoint, which is mounted over by the anonymous volume, so are not visible inside the container (unless the mount is unmounted).
