### ISSUE TITLE
cross compile for powerpc with gccgo

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#19134]
@brahmaroutu @duglin @clnperez @tianon @justincormack 

Hey all,

I think it is possible to cross compile for powerpc with gccgo so we wouldn't need to build on a seperate server.... I know some of you know my love for LDFLAGS, so I am going to try this out, but I thought I would include you all as you might know better than I if this is possible, we can use `gcc-4.4-powerpc-linux-gnu libc6-dev-powerpc-cross` I believe for cgo like we do mingw-gcc for windows compiling.

**Comment by justincormack** [comment]
Wrong powerpc I think you want `gcc-powerpc64le-linux-gnu` - the powerpc ones are 32 bit ppc, old ABI.

**Comment by jfrazelle** [comment]
oh nice!

**Comment by tianon** [comment]
Indeed, powerpc64le would be the correct one (GOARCH of ppc64le, dpkg arch
of ppc64el).  I'm really a fan of cross-compiling, but I don't think we
should use it as our only means of building these binaries -- if we're
officially releasing binaries for an architecture, we should prefer
arch-native compilation when possible.

I think where cross-compile would be awesome would be for making sure all
the arches we support really do still compile without having to have a
million new arch-specific CI workers (although having those would still be
good so we can verify correctness as well, ofc).

**Comment by jfrazelle** [comment]
yeah this would save us the trouble, we could build gccgo on every pr and cross compile for powerpc :) then when actually releasing we can build natively if you think its better :)

**Comment by jfrazelle** [comment]
that way we dont need a million power pc instances for prs

**Comment by tianon** [comment]
Yeah, given the hardware availability issues with ppc64le I think this
approach makes a ton of sense.  We should actually be able to cross-compile
ppc64le at least with Go directly (no gccgo required), and only use gcc for
the hacky cgo bits since ppc64le is officially supported in Go (which isn't
the case for s390x yet -- it's still gccgo-only).

**Comment by brahmaroutu** [comment]
@jfrazelle I have attempted this a while ago and I was told that the generation of the code is quite buggy according to the Linux on Power guys in IBM. ping @bpradipt 
My original build flags to build go across platforms is using similar approach to https://github.com/erikw/ewxb_gcc_cross-compiler_builder.git
changing the target to build on ppc64le

I still have to support s390x too. Sorry, I do not think this will work well.

**Comment by laboger** [comment]
I wouldn't say gccgo cross compilation was or is "buggy".  The problem is that you can't just build the gccgo compiler when doing a cross compile, you have to build all components of the toolchain that are needed for the target, including the cross libgo, libc, and bintuils.  That is included in the Advance Toolchain 9.0 right now and can be used to do cross gccgo compiles.  But I haven't tried to use it to build Docker yet, only some simple tests.

**Comment by clnperez** [comment]
Anything to prevent me from owning a million power vms. :smile: 

@jfrazelle - So, is the plan to just build (not run all the tests) with power right now for PRs?

@tianon, issues I've run across, e.g. https://github.com/opencontainers/runc/pull/437 indicate that we should still use gccgo and not go to do the compiling, so that was can catch weird little bugs like that. Otherwise we'd be hitting them later when we want to build the binary for distribution.

BTW, thanks @justincormack for that catch. Definitely powerpc != ppc64le.

**Comment by jfrazelle** [comment]
yes just to be sure we don't break compiling

**Comment by LK4D4** [comment]
There is no gccgo now and we have native compiler.
