### ISSUE TITLE
ISSUE: Can't use ADD when reading Dockerfile from STDIN from docker build (working as intended)

### ISSUE THREAD

**Issue by beetree** [docker/docker#19197]
If building an image from the current directory it builds correctly:

```
# pwd
/root/tmp
# ls
test.txt
# echo -e "FROM busybox\nADD . /root/tmp/\n" > Dockerfile; docker build --no-cache=true -t testimage .; docker run -it testimage ls /root/tmp
Sending build context to Docker daemon 4.096 kB
Step 1 : FROM busybox
 ---> ac6a7980c6c2
Step 2 : ADD . /root/tmp/
 ---> 5c384cc22f7d
Removing intermediate container 0af30a9ea706
Successfully built 5c384cc22f7d
Dockerfile  test.txt
```

However, if I do the same using STDIN to `docker build` I get:
```
# pwd
/root/tmp
# ls
test.txt
# echo -e "FROM busybox\nADD . /root/tmp/\n" | docker build --no-cache=true -t testimage -; docker run -it testimage ls /root/tmp
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM busybox
 ---> ac6a7980c6c2
Step 2 : ADD . /root/tmp/
 ---> 1688932a8c60
Removing intermediate container 58376b74073c
Successfully built 1688932a8c60
Dockerfile
```

It seems that when `docker build` reads from STDIN it creates a temporary Dockerfile in some Directory (where?) and the `ADD . /root/tmp/` is operating out of this temporary directory.

If this is working as intended, what's the best way of using `ADD` with `docker build` when using STDIN?

I realize this may seem like a really peripheral issue, and it probably is. Please mark it as low priority.

Thanks!

/b3

**Comment by duglin** [comment]
@beetree if you look at the usage for `docker build` you'll see that the last param is: `PATH | URL | -`  meaning you can either specify a location for your build context (dir) or it just reads the Dockerfile from stdin. In the stdin case because the build dir isn't specified it doesn't assume the current dir is what you wanted, it (as you noticed) assumes no dir at all which is why that temp dir you mentioned has just the Dockerfile.  Net, this is working as designed.

May I ask why you want to read the Dockerfile from stdin?  If I understood the bigger picture I might be able to offer up a solution.

**Comment by beetree** [comment]
@duglin Okay, that seems logical.

What I'm trying to do is to start a container from an image with a set of files added to the image before any processes (within the container) are started. The obvious way of doing this is to use volumes, but for two reasons volumes isn't an option:

1. I need the files to be deleteable within the container
2. I need the files (and their modifications) to be part of future docker exports of the container

Requirement #2 I guess could arguably be a design flaw. Why would I need to export the whole container when I could just read the mounted volumes from the host all-together? The reason behind this is that all the volumes may not exist, and if they do not exist they get initialized at container start. For example, imagine a container that runs a game server. During container start all game configurations are initialized and saved into files. These configurations can be modified during the containers lifetime and therefore needs to be made "stateful". However, at the time of the (first) container creation the contents of these configuration files are not known, hence they can't be mounted as (empty) volumes at container creation.

Not sure if this makes sense, and I'm most certainly poorly-designing this. That said, my current plan is to inject the files by creating a new image "FROM abc/xyz\nADD . .\n" and then do a `docker export` after which I will identify the "stateful" parts of the container filesystem and then reinject them next time the container is created (thereby retrieving the previous state).

/b3

**Comment by duglin** [comment]
@beetree ok so it sounds like in the end the reason you want to read the Dockerfile from stdin is because you don't want it to show up in the container after you do a `ADD. .`, right?  Easiest way to solve this is to create a `.dockerignore` file and put `Dockerfile` and `.dockerignore` in there - then both of them should be erased after the Dockerfile is parsed, but before any cmds from the Dockerfile are executed.  Would that do it for you?

**Comment by beetree** [comment]
@duglin 

Yeah, I'll probably end up doing something along the lines of `echo "FROM abc/xyz\nADD . .\n" > Dockerfile; echo "Dockerfile" > .dockerignore; docker build -t someimage .; rm .dockerignore; rm Dockerfile;`

Thanks for the help. I'll go ahead and close this ticket as it wasn't really an issue with Docker.

**Comment by Feuermurmel** [comment]
@beetree You can use `docker build -f - .` to read the Dockerfile from stdin while using the current directory as context.

**Comment by thaJeztah** [comment]
Correct, this was implemented in https://github.com/moby/moby/pull/31236, which is part of docker 17.05 and up. Also see https://github.com/moby/moby/issues/27393, which started the discussion again on this feature.
