### ISSUE TITLE
How to control the IP subnet used by docker_gwbridge

### ISSUE THREAD

**Issue by dvenza** [docker/docker#19298]
I looked in the documentation and set up a testbed to try and understand how the `docker_gwbridge` stuff works. Now I understand it, but there is a piece missing, especially in a multi-host setting.

I have my container on the overlay network with two interfaces, one private, one public.
* I can control the IP address space of the private one, by explicitly passing an IP subnet when I create the network.
* But the IP that actually matters to me, the one I can use to access the services run inside the container from outside, is taken from the `docker_gwbridge` bridge network, that uses an arbitrary IP range, potentially different across different docker engines.

Is there some option that I can pass to the docker daemon to tell it which IP subnet it should use for the `docker_gwbridge` network?

If I create by hand a `docker_gwbridge` network with the IP range I want, before creating any container, will it be picked up by docker?

I understand that I am supposed to use port forwarding, but let's say I have lots of "public" IP addresses and I don't want to pay the NAT performance penalty. What can I do?

**Comment by mavenugo** [comment]
> If I create by hand a docker_gwbridge network with the IP range I want, before creating any container, will it be picked up by docker?

Yes It will be picked up. But, please note that we take special precautions to this network when we create this network to be used for overlay network. docker_gwbridge network is shared across all the containers running across multiple overlay networks. Because of that, we configure ICC=false in the docker_gwbridge in order to prevent the containers connected to the docker_gwbridge to communicate with each other via this network. PTAL : https://github.com/docker/libnetwork/blob/master/default_gateway_linux.go#L15

If you have to create it manually it will be `docker network create --opts com.docker.network.bridge.enable_icc=false --subnet={your prefered subnet} docker_gwbridge`.

But please note that, though this will work in the current overlay driver implementation, there is no guarantee that we will continue to use `docker_gwbridge` as a way to provide external connectivity.

**Comment by dvenza** [comment]
Thank you for the clarification. I will keep using the docker0 bridge for now and keep an eye on how overlay networks will evolve in 1.10.

**Comment by igrcic** [comment]
Hi,

just a tiny fix, it should be --opt

`docker network create --opt com.docker.network.bridge.enable_icc=false --subnet=192.168.2.0/24 docker_gwbridge`

Additionally one can define` --internal` if no internet connectivity is required.

A question: will this network always persist on docker restarts? Can one save this somehow in docker daemon options?

Thank you,
Ivan
