### ISSUE TITLE
Add back protection against starting a container twice

### ISSUE THREAD

**Issue by tonistiigi** [docker/docker#19335]
This issue is to track the follow-up questions in #18736. Either we should revert it or add a `starting` state. `starting` state would also need some special handling - if `running` state is expected but `starting` is found the action shouldn't error but wait for the state to change.

#19330 also has relevant discussion.

@WeiZhang555 @ibuildthecloud @LK4D4 @cpuguy83

**Comment by calavera** [comment]
I vote to revert that PR.

**Comment by cpuguy83** [comment]
I like adding a `starting` state.
In the check on `ContainerStart` we can check `container.IsStarting()` first and hold until it's actually started (or failed to start), then we get to the `container.IsRunning()` check and go from there.

**Comment by tonistiigi** [comment]
@cpuguy83 What make this more complicated is that we have lots of other places that do ` container.IsRunning()` that is protected with this lock. With a naive change all these calls that previously waited for start to finish would now just error.

**Comment by calavera** [comment]
> I like adding a starting state.
> In the check on ContainerStart we can check container.IsStarting() first and hold until it's actually started (or failed to start), then we get to the container.IsRunning() check and go from there.

I think we should not make changes to the state lifecycle today. I rather release with a stable implementation. That PR addressed an issue that do NOT exist with our official exec drivers.

**Comment by cpuguy83** [comment]
Ok, makes sense. Let's revert.
We can look at specifically fixing issues with `ps` and locking as a separate item in 1.11, especially since that PR wasn't really fixing that anyway.

**Comment by cpuguy83** [comment]
Opened a revert PR: #19339

**Comment by WeiZhang555** [comment]
Revert is OK if we are eager to get a stable release.

I've done some work on adding a `Starting` state and thinks a lot.

First I think it's rational to separate a container's start process into two states: "starting" and "running", because the container's start process may take long time for maybe doing some volume mount, two states can reduce waiting time for getting running lock and reduce reaction time of docker ps(but not fix it completely). A "starting" state is also workable for stop user from starting container twice.

Second I'm still feeling worried about the blocking channel. Involve a blocking Golang channel in critical section is not a good idea, that means it has possibility that the lock will never be released.

However, @tonistiigi is also right,  adding "starting" state will need some painstaking work, because we need to handle `starting` state everywhere `running` state is handled. We need to decide whether we should wait the state change or exit with error or ignore it or let the code pass. It will take some time to cover all the parts with changes, reverting is easier comparing to adding `starting` state.

So it's OK to revert it if `docker ps` lock problem is solved because that my previous PR only improves that but not fixes it. Though I'm sad to see it's reverted :(

**Comment by WeiZhang555** [comment]
There's one more thing, just want to make sure you are OK with that.

```
type State struct {
    sync.Mutex
    // FIXME: Why do we have both paused and running if a
    // container cannot be paused and running at the same time?
    Running           bool
    Paused            bool
    Restarting        bool
    OOMKilled         bool
    RemovalInProgress bool // Not need for this to be persistent on disk.
    Dead              bool
    Pid               int
    ExitCode          int
    Error             string // contains last known error when starting the container
    StartedAt         time.Time
    FinishedAt        time.Time
    waitChan          chan struct{}
}
```

The container's state is a little bit of chaos, I am planning to change it to something like:

```
type ContainerState int64

const (
    stateRunning ContainerState = (1 << itoa)
    statePaused
    stateRestarting
    OOMKilled
    RemovalInProgress
    Dead
)

type State struct {
    sync.Mutex
    State      ContainerState
    Pid        int
    ExitCode   int
    Error      string // contains last known error when starting the container
    StartedAt  time.Time
    FinishedAt time.Time
    waitChan   chan struct{}
}
```

I feels this will make state more clear, because the container will go from one state to another and there's no need to keep so many boolean variants in one struct.

This will also take lots of work and impact a lot of places in Docker code, are you OK with this change? If you prefer not, I would keep it unchanged, or I would start this work to see if it's feasible.

**Comment by tonistiigi** [comment]
@WeiZhang555 I believe `State` is directly used in the `docker inspect` output and we have to keep API backwards compatibility there.

**Comment by WeiZhang555** [comment]
@tonistiigi That makes sense, then I wouldn't touch that part for keeping backward compatibility. :smile:
