### ISSUE TITLE
missing privilege separation directory /var/run/sshd

### ISSUE THREAD

**Issue by vklonghml** [docker/docker#19351]
Hi,all
Does anybody have ever such a problem when run a docker container without "/bin/bash"

here is my environment:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

the image i using is created from Dockerfile, it looks like that:
FROM scratch
ADD . /
ENV PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
RUN rm Dockerfile
CMD /usr/sbin/sshd -D

and i download a rootfs by using cmd "debootstrap --variant=minbase --include=openssh-server  --arch i386 trusty /mnt", and copy the Dockerfile into the /mnt, then use cmd "docker build -t mytrusty /mnt" to make a new image.
at last, when i run a docker container with cmd "docker run -it mytrustry", and came out a problem:
missing privilege separation directory /var/run/sshd; 

i have installed the sshd in the rootfs, how does that problem come out.
thanks!

**Comment by HackToday** [comment]
Is it possible to run docker run -d  ** related to make sure if your docker container running?
Or whether use use -d or not, it have same issue ?

**Comment by thaJeztah** [comment]
Sounds similar to https://bugs.launchpad.net/ubuntu/+source/openssh/+bug/45234 ?

**Comment by thaJeztah** [comment]
i.e., looks like you need a script to setup `/var/run/sshd` instead of calling sshd directly

**Comment by unclejack** [comment]
As @thaJeztah has stated above, this can be fixed quite easily by running a tiny script before launching sshd.

This isn't a Docker bug. It's just something related to a particular piece of software to be run in Docker.

Please keep in mind this issue tracker is dedicated to tracking bugs, proposals and pull requests to make changes to Docker; it's not a general support forum.

This kind of question and general support questions are more adequate for the following:
1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker channel on Freenode.
4) StackOverflow https://stackoverflow.com/questions/tagged/docker

I'm going to close this issue now because a solution has been provided. Please feel free to continue the discussion. There's no need to open a new issue on this topic.
