### ISSUE TITLE
1.10 network links does not behave exactly the same as legacy links

### ISSUE THREAD

**Issue by michaelsauter** [docker/docker#19403]
I just tried 1.10 to check out the new alias feature for networks.

With legacy links (written to /etc/hosts instead of using DNS) it was possible to do the following:

```
docker run --link foo:local.foo.com
```
Then this container could look up `foo` using `local.foo.com`. If I do the same using a network, it does not work:
```
docker run --net bar --link foo:local.foo.com
```

"Normal" aliases work however:
```
docker run --net bar --link foo:baz
```

Is this to be expected?

Relevant output from `docker info`:
```
Server Version: 1.10.0-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 566
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.2.0-23-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
```

**Comment by vdemeester** [comment]
@michaelsauter I'm pretty sure this is expected. Using `--link foo:local.foo.com` was never meant to work like that I guess. 

To achieve the same behavior, I think the best way would be to use `--add-host` (`--add-host=foo:local.foo.com`). But I guess it does not work with 1.10 because we check that it's an IP for `--add-host`..

@thaJeztah @mavenugo WDYT ?

**Comment by michaelsauter** [comment]
@vdemeester Thanks for the quick reply. Yea not sure this behaviour should be supported, but just wanted to ask since it was possible to do this and from what I gathered from the discussion around network links/aliases it sounded like they should bring back functionality that the legacy links supported. If it is not supported in 1.10, then maybe this should be noted somewhere as a difference between legacy links and network links.

I assume a working "solution" would be to assign the container a fixed IP (using the new `--ip` flag), then use `--add-host` as you mention. Not very pretty though.

**Comment by mavenugo** [comment]
@michaelsauter as @vdemeester pointed out, `--link` in user-defined networks are not designed to work like legacy `--link`. With DNS backing the name resolution, the name resolution behavior changes as well. the x.y.z notation will be used to namespacing the request.
But having said that, being an user-specified alias, we should do our best to resolve this (atleast as a best-effort). ping @sanimej.

**Comment by sanimej** [comment]
@michaelsauter This is the expected behavior for links on user defined networks because of the change to use DNS. The embedded DNS server can only resolve the names in the namespace of the networks to which a container is connected to. ie: ping foo is same as ping foo.net

For a fully qualified name local.foo.com, local has to be resolved in the domain foo.com. Since the docker embedded DNS server is not aware of this domain it will forward it to the external DNS server.

One way to achieve what you want is to have a DNS server for your domain, add the service names to it and configure that DNS server IP in other containers.

**Comment by michaelsauter** [comment]
@sanimej Okay, understood. Should
```
docker run --net bar --link foo:api.foo.bar
```
or
```
docker run --net bar --link foo:api.foo
```
work then? They don't seem to work either.

**Comment by sanimej** [comment]
@michaelsauter please try..

> docker run --net bar --link foo:api

**Comment by michaelsauter** [comment]
@sanimej Well that works as explained above. But then I can only access container `foo` as `api`. So far so good. But it would be handy to simulate subdomains with links. Assume I have an API accessible on `api.example.com`, and that the routing of this is tied to being on the subdomain `api`. Now if I could link the container `foo` as `api.foo` (or `api.foo.bar`), then I would not have to setup a DNS server just for this. It worked well using the legacy links, so my hope was it would continue to work with network links.

**Comment by sanimej** [comment]
@michaelsauter The intent of the --link alias is to give an alias for the container name and not for the domain. There was no explicit check before and because of the fact that /etc/hosts was used underneath it was still possible to do it. 

With the move to DNS based resolution the domain has a specific interpretation.  What you are looking for is a way to define an alternate domain for the containers. I am not sure if --link is the right way to do it. If this is a general use case we can look into providing an option to define your own domain for the containers.

**Comment by michaelsauter** [comment]
@sanimej Fair enough. Closing as my question has been answered. Maybe add a comment somewhere that lists the differences between legacy links and network links.

**Comment by sanimej** [comment]
@michaelsauter It was possible to have `.` not only in the alias name but in the container name and network name as well. Because of this I changed the name resolution logic (docker/docker #19573). Please try the latest master or the next RC image when its out. The use case you have will also work now.

**Comment by michaelsauter** [comment]
@sanimej That is awesome - thanks! I will try with the next RC.

**Comment by michaelsauter** [comment]
Just tried 1.10-rc2, works perfectly. Thank you very much!

**Comment by thaJeztah** [comment]
@michaelsauter cool, thanks for testing!
