### ISSUE TITLE
[1.10] Pulling with wrong credentials doesn't show prompt

### ISSUE THREAD

**Issue by tonistiigi** [docker/docker#19523]
`POST image/create` endpoints response previously got `200` on authentication error, in `v1.10` the response code is `500`. Error message is also different.

On the client side this means that error message is shown instead of showing prompt like in `1.9`.

If `500` remains the new response code then probably need versioning for the old clients. Also old daemons should still be supported.

Depending on #19522

**Comment by tonistiigi** [comment]
#19159 is probably the same issue. This isn't limited to private registries though.

**Comment by calavera** [comment]
> on authentication error, in v1.10 the response code is 500

we should really propagate the 401 from the registry in those cases, 500 is a very misleading response.

**Comment by aaronlehmann** [comment]
What should happen in a scenario where output is sent to the client before the auth issue happens, for example "pull all tags" returning a 401 for one of the tags?

**Comment by calavera** [comment]
> for example "pull all tags" returning a 401 for one of the tags?

this might be too deep in the :rabbit: hole, but why does the registry return information about a tag when we don't have access to pull it? it sounds like a security vulnerability tbh. The registry should only return information about things my credentials give me access to.

**Comment by calavera** [comment]
> "pull all tags"

this should always be "pull all tags this credentials give me access to".

**Comment by calavera** [comment]
but I guess we cannot change that behavior, right?

**Comment by aaronlehmann** [comment]
I don't believe what I'm describing can actually happen with our official registry, but I see all kinds of weird behavior with third-party registries, and I don't want the engine to be overly reliant on errors happening at specific points in the flow.

It also seems like a big constraint to not allow any output to be shown to the user before a possible authentication error. We can't even print informational messages about what we're attempting to do, because those would force a 200 status code in the daemon -> client communication.

Not a big deal for 1.10, but something to think about.

**Comment by calavera** [comment]
between returning a `200` or a `500` I prefer to return a `500`. At least it's not a success code, but we need to decide what to do with old clients, as @tonistiigi says.

**Comment by calavera** [comment]
For conversations with @aaronlehmann, it looks like the right approach is to return 401, rather than that 500. That would have the benefit of not requiring any backport logic, since old clients would get that status directly rather than getting the 200 and reading the response looking for it. I'm not completely sure where to change that response code though, does that come from distribution?

**Comment by aaronlehmann** [comment]
It doesn't come from distribution. I think the right place to set the response code is `postImagesCreate` in `api/server/router/local/image.go`.
