### ISSUE TITLE
How to access the Mysql database inside Docker container environment

### ISSUE THREAD

**Issue by thinhduckhoi** [docker/docker#19581]
So i created my own Docker image using Dockerfile featuring Centos6, LAMP and i deployed Wordpress successfully on my testing host.
In Dockerfile, here is a line related to Mysql Database.
UN service mysqld start && mysql -u root -e "CREATE DATABASE wordpress; GRANT ALL PRIVILEGES ON wordpress.* TO 'wpuser'@'localhost' IDENTIFIED BY 'wp123456'; FLUSH PRIVILEGES;"
The point is i don't know how to access to Mysql database, when i was running this command I could log into Docker environment.
sudo docker run -it image-name /bin/bash
But when i trying to log into mysql database with this command , it always failed with this error.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)

So do you guys know there is any way to connect to Mysql database in Docker environment???

**Comment by unclejack** [comment]
This is a support question, not a Docker bug.

Please keep in mind this issue tracker is dedicated to tracking bugs, proposals and pull requests to make changes to Docker. This is not a general support forum or a place to ask questions when one is getting started with Docker.

This kind of question and general support questions are more adequate for the following:
1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker channel on Freenode.
4) StackOverflow https://stackoverflow.com/questions/tagged/docker

Thank you for understanding.

I'm going to close this issue now because it's a question which can be answered by reading the documentation and by going over tutorials. Please feel free to continue the discussion. There's no need to open a new issue on this topic.
