### ISSUE TITLE
Debian 8 Jessie - docker-engine (1.9.1-0~jessie) - DOCKER_OPTS ignored

### ISSUE THREAD

**Issue by tmiklas** [docker/docker#19585]
I found that settings from `/etc/default/docker` file are ignored when service starts via `systemd`, making it really awkward to add/change parameters, for example where docker deamon listens for commands (required to enable clustering - default is `-H fd://`).

Currently the only option I found working is to manually edit the `docker.service` file, reload systemd and restart docker service for changes to take effect.

Version affected:

Package: docker-engine
Maintainer: Docker &lt;support@docker.com&gt;
Version: 1.9.1-0~jessie

**Comment by HackToday** [comment]
check if this applies your needs
https://docs.docker.com/engine/articles/systemd/

**Comment by thaJeztah** [comment]
Correct, systemd systems should be configured using "drop-in" files; note that you should **never** edit the service-file itself, because that may cause issues if you're upgrading an existing install, and there's an updated version of the service-file. Using drop-ins makes sure your changes are preserved, also when upgrading. See this section on the page that @HackToday mentioned to learn about using drop-in files; https://docs.docker.com/engine/articles/systemd/#custom-docker-daemon-options

I'm going to close this issue, because this works as expected, but feel free to comment here after I've closed this issue
