### ISSUE TITLE
Problem with running mongo image

### ISSUE THREAD

**Issue by meelosh94** [docker/docker#19582]
I need mongodb and nodejs for docker compose.
I follow the instructions from https://github.com/StefanScherer/docker-compose-nodejs-mongodb-example
But when i do docker-compose up, it says: exec format error, cannot start container <id of mongo container>
When I tried to run only mongo image, it stopped and said: waiting for connections on port 27017, and then crashed.
So that container doesn't work properly.
What should i do to fix that so i can use docker-compose?

**Comment by HackToday** [comment]
Which mongo image did you use ?  Is it official image ?
Did you check related container logs , from 
```
 waiting for connections on port 27017, and then crashed.
```

It seems something wrong with your image.

**Comment by meelosh94** [comment]
I used "docker pull mogno", it pulls latest version from dockerhub.
https://hub.docker.com/_/mongo/

And I want to compose it with "docker pull node" image, also from dockerhub.
https://hub.docker.com/_/node/

nodejs works fine, but mongo returns "waiting for connections on port 27017" and wont to create container, and because of that docker-compose doesn't work
Don't know what can we wrong with my mongo image.

**Comment by HackToday** [comment]
hi @meelosh94  suggest you try mongo directly, like `docker run ***`
if above work.

For you mentioned https://github.com/StefanScherer/docker-compose-nodejs-mongodb-example, I suppose if that example old or deprecated.  For compose question I think you could ask in docker-compose. WDYT?

**Comment by phemmer** [comment]
@meelosh94 can you provide the information @GordonTheTurtle asked for?

**Comment by unclejack** [comment]
This issue tracker is a bug tracker for Docker issues, new feature requests, proposals and pull requests to make changes to Docker.

This problem has been reported without the necessary information for us to debug and figure out if there's indeed an issue with Docker. However, you've mentioned you're using docker-compose. This issue tracker isn't the right place to ask for help with docker-compose.

This kind of question and general support questions are more adequate for the following:
1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker channel on Freenode.
4) StackOverflow https://stackoverflow.com/questions/tagged/docker

I'm going to close this issue now because it involves docker-compose and this question should be asked on the forums. Please feel free to continue the discussion. There's no need to open a new issue on this topic.
