### ISSUE TITLE
[1.10-rc1] vxlan device exists

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#19694]
Steps:

1. Launch Daemon configured with etcd backend (backend type probably doesn't matter)
2. Create network foo
3. Create container on network foo
4. Kill -9 daemon
5. Kill etcd
6. Start daemon
7. Start previously launched container (it fails as expected)
8. Start etcd
9. Start previoulsy launched container

```
$ docker start -ai a01eea86bfa2
Error response from daemon: subnet sandbox join failed for "10.0.0.0/24": error creating vxlan interface: file exists
```

**Comment by ibuildthecloud** [comment]
Oh wait, if I create any container after that on network `foo` it also fails in the same way.

**Comment by thaJeztah** [comment]
ping @mavenugo can you have a look at this?

**Comment by mavenugo** [comment]
Thanks @ibuildthecloud for the detailed reproduction steps. I couldn't reproduce it in ubuntu 14.04 (kernel < 3.16). This could be specific to kernel > 3.16.
I think the issue is seen due to the double negative case of ungraceful daemon shutdown and KVStore down. Docker daemon will attempt to cleanup stale resources (such as vxlan device) during daemon shutdown (via container cleanup). When the daemon is ungracefully brought down, such a cleanup is bypassed. Hence the daemon attempts to perform sandbox cleanup on bootup, if the KVStore is down, such an attempt will also fail.
We also attempt to perform the cleanup when the container comes up. But, it seems to not happen for kernels > 3.16.

@mrjana will be the best person to handle this.

**Comment by mrjana** [comment]
@mavenugo @ibuildthecloud I already pushed a PR docker/libnetwork#901 last night to fix this

**Comment by tiborvass** [comment]
@mrjana so should we expect another vendoring today?

**Comment by mrjana** [comment]
@tiborvass Yes
