### ISSUE TITLE
"Version-free" method to get container id inside container

### ISSUE THREAD

**Issue by viatcheslavmogilevsky** [docker/docker#19698]
Inspired by comments of this answer: http://stackoverflow.com/a/25729598

Problem: get container ID inside of this container
It would be nice use the same method across different docker server versions.

My current solution is:

```bash
cat /proc/self/cgroup | grep docker | grep -o -E '[0-9a-f]{64}' | head -n 1
```

I created this issue to find more "versionless" method

**Comment by HackToday** [comment]
Hi @viatcheslavmogilevsky  Not quite understand your needs. Do you want feature added in docker ?
Or just ask what related shells magic or linux magic can be used to get container ID ?

**Comment by viatcheslavmogilevsky** [comment]
@HackToday it's about shell magic to get container ID. If someone know solution better than proposed - I would be glad to see here.

**Comment by phemmer** [comment]
There are several proposals for this type of feature. See https://github.com/docker/docker/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+introspection

**Comment by thaJeztah** [comment]
@viatcheslavmogilevsky see the issues that @phemmer referred to for alternative proposals.

However, the issue tracker is not the best location for asking other uses to show there approach. Could you ask/discuss this question on one of the below;

1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker IRC channel on Freenode.

I'll close this issue here, but feel free to comment here after I've closed
