### ISSUE TITLE
Add redis logging driver

### ISSUE THREAD

**Issue by lami02** [docker/docker#19804]
A driver similar to the existing ones, that will forward the logs to a redis server and append them to a specified list. The list holds string representations of jsons. For more information about redis see: http://redis.io.

Specific log options will be:
* redis-address (required)
* redis-database (only necessary, if you have multiple databases on your redis server)
* redis-password (only necessary, if you have secured your redis server with a password)
* redis-key (the key to the list of logs, default key 'docker-logger')

With this new driver one can store logs in a highly available key-value store and process the logs further from there. For example one can easily use logstash to transport the logs to elastic and get a nice dashboard for your logs with the help of kibana.

The logs will contain:
* message (the log message)
* container (the container name)
* hostname
* tag (the container tag)
* attrs (a struct in which all defined envs and labels get stored)

**Comment by lami02** [comment]
#dibs

**Comment by lami02** [comment]
+kind/feature

**Comment by thaJeztah** [comment]
Closing this because the feature has been rejected (sorry @lami02!) see https://github.com/docker/docker/pull/20146.


Note that we have an open proposal to support external logging drivers as a plugin; if this is realized at some point, you can re-implement this as a plugin https://github.com/docker/docker/issues/18604
