### ISSUE TITLE
On RHEL/CentOS 7, version 1.10.0 results in systemd complaints about TasksMax

### ISSUE THREAD

**Issue by dandric-activevideo** [docker/docker#20036]
As noted in my comment on 1057783, on RHEL/CentOS 7, as of version 1.10.0, systemd starts complaining about the `docker.service` unit file:

   [/usr/lib/systemd/system/docker.service:14] Unknown lvalue 'TasksMax' in section 'Service'

This is because systemd appears to have introduced this setting in version 226, while RHEL/CentOS7 still have systemd 219.  Similarly, Debian 8 has systemd 215, so I assume the same error can appear there (I haven't tested that).

The above message appears when installing the official (I assume) RPMs from https://yum.dockerproject.org/repo/main/centos/7.

The solution is probably to maintain different systemd unit files for different distros.

**Comment by tiborvass** [comment]
Sorry I misunderstood the issue, I thought the daemon wouldn't even start. We'll fix it, but it's def not a p0.

**Comment by dandric-activevideo** [comment]
No, sorry about that; this is (I hope) only cosmetic.  Also, the original thread on [stackexchange](http://unix.stackexchange.com/questions/253903/creating-threads-fails-with-resource-temporarily-unavailable-with-4-3-kernel/255603#255603) says:

> It was introduced in systemd 228 and makes use of the cgroups pid subsystem, which was introduced in the linux kernel 4.3. A task limit of 512 is thus enabled in systemd if kernel 4.3 or newer is running.

If I read that correctly, there may be no limit at all, or a completely different limit, on at least RHEL/CentOS 7, since these have kernel 3.10.  And Debian 8 has kernel 3.16.

**Comment by mcmohd** [comment]
guys, is there any solution for this? I'm getting issue related to resources unavailable.

**Comment by cpuguy83** [comment]
@mcmohd What do you mean?

**Comment by wu0407** [comment]
@mcmohd   only delete the line of TasksMax in the /usr/lib/systemd/system/docker.service

**Comment by mcmohd** [comment]
Thanks wu0407, makes sense. Let me give a try.

**Comment by wu0407** [comment]
` [root@centos7-node4 ~]# systemctl status docker.service 
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2016-02-05 22:10:47 EST; 2h 34min ago
     Docs: https://docs.docker.com
 Main PID: 18694 (docker)
   CGroup: /system.slice/docker.service
           └─18694 /usr/bin/docker daemon -H fd://

 root@centos7-node4 ~]# cat /proc/18694/limits 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        unlimited            unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             1048576              1048576              processes 
Max open files            1048576              1048576              files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       15097                15097                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us  
`
I think Centos 7 don't have task limit

**Comment by centminmod** [comment]
indeed ran into this on CentOS 7.2 as well

**Comment by mkomarinski** [comment]
I can confirm it happens in Debian 8

**Comment by bobrik** [comment]
I bet you all forgot to do `systemctl daemon-reload`.

**Comment by mkomarinski** [comment]
Maybe...*opens new terminal window*

**Comment by mkocikowski** [comment]
Ubuntu 15.10 as well ; commenting out TasksMax and doing `systemctl daemon-reload` 'fixes'.

**Comment by bobrik** [comment]
@mkocikowski does it work with `daemon-reload` but without `TaskMax` removal? Ubuntu 15.10 has never systemd than Debian Jessie and it works on Debian Jessie out of the box.

**Comment by bobrik** [comment]
Just installed vanilla ubuntu 15.10 in a VM, no issues about `TaskMax`.

![image](https://cloud.githubusercontent.com/assets/89186/12955806/ade011aa-d01c-11e5-9a56-df3ce5bfd284.png)

@jfrazelle what is the reason to remove a sane default?

**Comment by dandric-activevideo** [comment]
@bobrik, the service will start, but if you use `systemctl status -l docker`, you will see:

    systemd[1]: [/lib/systemd/system/docker.service:14] Unknown lvalue 'TasksMax' in section 'Service'

This is because Ubuntu 15.10 comes with systemd 225, which does not yet implement the directive.

Maybe the addition of the directive can be made conditional at build time, depending on whether the systemd version is 226 or later.

**Comment by bobrik** [comment]
Okay, looks like somehow I missed the warning in logs. It seems that the first time it prevented docker from starting up.

I still think it should stay since it does not break existing things and makes newer systemd and kernel work out of the box.

**Comment by mkocikowski** [comment]
@bobrik right. the service starts, but with an error message. i have no opinion on keeping it / removing. just reporting.

**Comment by bobrik** [comment]
Okay, I see. https://twitter.com/frazelledazzell/status/697821784360484864

**Comment by jfrazelle** [comment]
Just because your version works doesn't mean they all do ;)

On Wednesday, February 17, 2016, Ivan Babrou <notifications@github.com>
wrote:

> Okay, I see. https://twitter.com/frazelledazzell/status/697821784360484864
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/20036#issuecomment-185575638>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
