### ISSUE TITLE
Flag provided but not defined: -d

### ISSUE THREAD

**Issue by dixon22ma** [docker/docker#20081]
Greetings.
After upgrading wing version 1.10 the -d flag is not recognized.

docker -d
flag provided but not defined: -d
See 'docker --help'.

**Comment by vdemeester** [comment]
Hi @dixon22ma,

It is *normal* that it is not here anymore. It has been deprecated since 1.8 and was target for removal for 1.10 (see https://docs.docker.com/engine/deprecated/#old-command-line-options). It has been replace by the subcommand `daemon` (see https://docs.docker.com/engine/reference/commandline/daemon/).

I'm gonna close this then :wink:.

**Comment by shanteadam** [comment]
When upgrading docker was it supposed to also upgrade the "service" script for docker? I am using docker 1.10.2 and the service script still looks like below causing flag provided but not defined errors.

`[Service]
ExecStart=/usr/bin/docker -d -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=amazonec2 
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
Environment=

[Install]
WantedBy=multi-user.target
`

**Comment by thaJeztah** [comment]
@shanteadam looks like you made modifications to the service-file (comparing it to https://github.com/docker/docker/blob/master/contrib/init/systemd/docker.service). I suspect that in that case, the file will not be updated.

If you want to provide custom settings in your service-file, don't make changes to `docker.service`, but use a drop-in file to override those settings; see https://docs.docker.com/engine/admin/systemd/#custom-docker-daemon-options

**Comment by shanteadam** [comment]
I didn't make any modifications actually. This machine was provisioned/created by a docker-machine command. It originally had docker 1.9 and then I "upgraded" to the newest version by following the instructions for 1.10 which said to use a different apt source. After upgrading the package using the new apt source the version was changed to 1.10.2 BUT the service was failing to start due to the flag -d not being changed in the service script. Since my original comment I have just reproduced this while upgrading another docker-machine instance in the same manner. 

> If you want to provide custom settings in your service-file, don't make changes to docker.service, but use a drop-in file to override those settings; see https://docs.docker.com/engine/admin/systemd/#custom-docker-daemon-options

I don't want to customize the file. I would like to use the "official" docker.service file for 1.10.2 but that doesn't seem to be changed automatically using apt-get to upgrade from 1.9 -> 1.10.2

**Comment by shanteadam** [comment]
I guess the question is if docker should support upgrading docker.service files created by older versions of docker-machine. If not, then this isn't a bug.

**Comment by thaJeztah** [comment]
@shanteadam hm interesting; I think I noticed in the past that the docker-machine provisioner updated the service-file and didn't use drop-ins.

Looks like docker machine still uses that https://github.com/docker/machine/blob/8094d6ce52d7a0634f430a6620b02d6114c672d6/libmachine/provision/systemd.go#L35-L53

perhaps better that it uses drop-ins as well

**Comment by shanteadam** [comment]
> Looks like docker machine still uses that https://github.com/docker/machine/blob/8094d6ce52d7a0634f430a6620b02d6114c672d6/libmachine/provision/systemd.go#L35-L53
> 
> perhaps better that it uses drop-ins as well

That seems like a sensible alternative. As long as us docker-machine users don't have to manage it by hand.

FYI, if anyone else hits this issue changing "-d" to "daemon" in the docker.service file will at least solve the problem and match the docker.service file created by the current version of docker-machine. However, @thaJeztah makes it sound like this issue could reappear if the flags change in future docker versions.
