### ISSUE TITLE
Orphaned Containers when Client Dead

### ISSUE THREAD

**Issue by cancan101** [docker/docker#20171]
If I run `docker run --rm -it ubuntu` and then I `kill -9` the `docker` client, it appears that the docker daemon is still running that container:
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
4d2c241534bf        ubuntu              "/bin/bash"         11 seconds ago      Up 11 seconds                           small_elion
```
Leaving a running container unexpectedly (i.e. I did not specify `-d`) "orphaned". Is there anyway to have the daemon detect when the client dies and to then cleanup the container?

List the steps to reproduce the issue:
1. `docker run --rm -it ubuntu`
2. `ps -ax | grep docker`
3. `kill -9 <pid>`

Describe the results you received:
* container still running

Describe the results you expected:
* container not running
```
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```
```
$ docker info
Containers: 85
Images: 398
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 568
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: dev
ID: HPPL:LRJJ:5GOJ:SFFO:WRTX:SSAY:3LAR:NUBU:CGJI:IFA3:LEUP:EY2N
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 20
 System Time: 2016-02-09T23:24:13.364136606Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: agrothberg
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Comment by AkihiroSuda** [comment]
`--rm` is implemented on the client side, that is why container keeps running even when the client is killed.
https://github.com/docker/docker/blob/da58ee42bb1d4e17c5b525d161f29ad8efc0569e/api/client/run.go#L224-L230

I can't come with up any easy solution to detect orphan containers.

## Proposal
Proposal: add `Attachers` to `/containers/(id)/json` for detection of orphan containers

### Example output
Terminal 1:
```
$ docker run -it --rm ubuntu
root@foobar:/# 
```

Terminal 2:
```
$ docker inspect foobar | jq .[0].State.Attachers
['127.0.0.1:4242']
$ kill -9 $TERMINAL1_DOCKER_CLIENT
$ docker inspect foobar | jq .[0].State.Attachers
[]
```

Maybe returning the number of the attachers is enough rather than returning all the `ip:port` list.

### Implementation Issue
For Go >= 1.6, I think we can use the new-designed `CloseNotifier` that supports `http.Hijack`.
But I'm not sure how we can easily detect closes for Go < 1.6.
I suggest using the `null` value for Go < 1.6.

https://github.com/docker/docker/blob/da58ee42bb1d4e17c5b525d161f29ad8efc0569e/daemon/attach.go#L41
https://github.com/golang/go/commit/99fb19194c03c618c0d8faa87b91ba419ae28ee3

If I can receive positive reactions to this proposal, I can work on this.

**Comment by thaJeztah** [comment]
@cancan101 @AkihiroSuda I think this is a duplicate, or related to https://github.com/docker/docker/issues/16575. I suggest to close this, and move the discussion to that issue

**Comment by AkihiroSuda** [comment]
I'm OK to close this, thanks!
PTAL @cancan101

**Comment by thaJeztah** [comment]
Let me go ahead and close this, but feel free to comment here after I've closed, @cancan101
