### ISSUE TITLE
docker machine connect to other host using generic driver can cause  the host docker client version change?

### ISSUE THREAD

**Issue by llitfkitfk** [docker/docker#20221]
$ systemctl restart docker

"An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.22/containers/json: read unix @->/var/run/docker.sock: read: connection reset by peer"

**Comment by llitfkitfk** [comment]
[root@mydevserver ~]# docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:34:50 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**Comment by llitfkitfk** [comment]
[root@mydevserver ~]# systemctl status docker
● docker.service
   Loaded: loaded (/etc/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Thu 2016-02-11 13:52:06 CST; 1min 48s ago
  Process: 25231 ExecStart=/usr/bin/docker -d --graph /mnt/docker -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver devicemapper --label provider=generic (code=exited, status=125)
 Main PID: 25231 (code=exited, status=125)

Feb 11 13:52:06 mydevserver systemd[1]: Started docker.service.
Feb 11 13:52:06 mydevserver systemd[1]: Starting docker.service...
Feb 11 13:52:06 mydevserver docker[25231]: flag provided but not defined: -d
Feb 11 13:52:06 mydevserver docker[25231]: See '/usr/bin/docker --help'.
Feb 11 13:52:06 mydevserver systemd[1]: docker.service: main process exited, code=exited, status=125/n/a
Feb 11 13:52:06 mydevserver systemd[1]: Unit docker.service entered failed state.
Feb 11 13:52:06 mydevserver systemd[1]: docker.service failed.
Feb 11 13:52:06 mydevserver systemd[1]: start request repeated too quickly for docker.service
Feb 11 13:52:06 mydevserver systemd[1]: Failed to start docker.service.
Feb 11 13:52:06 mydevserver systemd[1]: docker.service failed.

**Comment by llitfkitfk** [comment]
# docker info
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.22/info: read unix @->/var/run/docker.sock: read: connection reset by peer

**Comment by fabiocarneiro** [comment]
@llitfkitfk Why did u close? I'm having the same issue

**Comment by fuentecilla86** [comment]
same issue here!

**Comment by fuentecilla86** [comment]
if you try to run the daemon manually: 
sudo /usr/bin/docker daemon

And the error is:
"FATA[0000] Error starting daemon: Error initializing network controller: could not delete the default bridge network: network bridge has active endpoints "

The solution is: 
sudo rm -r /var/lib/docker/network

Start again docker daemon: 
sudo service docker start 

It worked for me. There was a problem with the bridge docker started.

**Comment by jdmarshall** [comment]
The docker guys have a habit of closing issues that are unresolved.  It's hands down my least favorite thing about Docker.  :/

**Comment by llitfkitfk** [comment]
@fabiocarneiro I reinstall the docker 1.10, need waiting a long time to migration for change the format of the old docker images.

**Comment by llitfkitfk** [comment]
@fuentecilla86 It's my bad, not docker. I use new docker toolbox on my mac, try to connect to the other  old version host of docker  using docker machine( generic driver)

**Comment by llitfkitfk** [comment]
but somehow, it was not successful try to connect to the server, and when I ssh to the server host, I got  the latest docker client version(I did not update the docker on the host).

**Comment by jdmarshall** [comment]
I could have sworn I had upgraded to 0.10 but I think maybe it didn't take.  Just installed 0.10.1 and everything seems to be working now.

**Comment by llitfkitfk** [comment]
I don't know why. It seems that docker machine use generic driver to connect the other host which can cause the server docker client version change?

**Comment by jdmarshall** [comment]
This seems like a version-version incompatibility that perhaps should see some attention in the next version(s).  

If the client is incapable of talking to the server we should get a warning or an outright error, rather than a failure to launch.  Either the client or the server should reject the transaction at the handshake, wouldn't you think?

**Comment by llitfkitfk** [comment]
agree👍

**Comment by llitfkitfk** [comment]
Why they change ’-d‘ to ‘daemon’ ![image](https://cloud.githubusercontent.com/assets/2404785/13042597/67e0c6ca-d3fc-11e5-8bef-219d8d41efa9.png)

**Comment by jdmarshall** [comment]
Seems I deleted the wrong comment.  I had this issue running docker-machine 0.5.6 against whatever DigitalOcean is running on their servers right now.  Problem cleared up with 0.6.0, so it seems that a breaking change snuck in without a guard in place.

**Comment by jdmarshall** [comment]
@llitfkitfk Oh is that what happened?  I was looking through syslog and didn't see a specific error other than 125.  

(and to answer your question, it's a 0.6 build, things are bound to break)

**Comment by llitfkitfk** [comment]
see output of 'systemctl status docker' above
Feb 11 13:52:06 mydevserver docker[25231]: flag provided but not defined: -d

**Comment by llitfkitfk** [comment]
@jdmarshall the comment u delete is just machine reply, not necessary. It's OK.

**Comment by vdemeester** [comment]
@jdmarshall @llitfkitfk yeah, the `-d` flag to start the daemon had been deprecated since 1.8 I believe — and has been replaced by the subcommand `daemon`. Machine did use `-d` up until the `0.6.0`, but it could have been using it on `0.5.x` to ease/smooth the transition… 

If you use the latest docker machine (0.6.0) it should be fine with any driver — if you use an older one, it won't be fine. We'll try our best to handle these transition better in the future, that's our bad :sweat_smile:.

> I don't know why. It seems that docker machine use generic driver to connect the other host which can cause the server docker client version change?

I don't think so. The daemon on the other host has been provisionned with `1.10` but it was using the old flag for some reason (probably because the docker-machine version was `0.5.x`).

**Comment by llitfkitfk** [comment]
@vdemeester Thanks!

**Comment by thaJeztah** [comment]
Is this resolved? Note that (if it isn't resolved)  his may be better reported in the docker-machine issue tracker (https://github.com/docker/machine/issues)

**Comment by vdemeester** [comment]
I do agree with @thaJeztah so I'll close it, feel free to discuss still if needed :wink:

**Comment by basnijholt** [comment]
I'm having the same issue, is there any proposed fix?

**Comment by vdemeester** [comment]
@basnijholt yes, you need to upgrade the version of `docker-machine` :wink:

**Comment by basnijholt** [comment]
Stupid question: how do I do that?

**Comment by j127** [comment]
I encountered this bug on Ubuntu 14.04 with Docker 1.12.0. None of the solutions above worked until I deleted `/var/lib/docker/` after purging docker-engine.

```
    $ sudo apt-get autoremove --purge docker-engine
     
    # Nothing worked until I added this step
    $ sudo rm -rfv /var/lib/docker
     
    # Reboot here
     
    $ sudo apt-get update
    $ sudo apt-get install docker-engine
```

**Comment by matejvelikonja** [comment]
@j127 thx for the tip, this solutions also worked in my case.

**Comment by entron** [comment]
@j127 Your solution does not work for me.

**Comment by j127** [comment]
@entron - If that doesn't work, I'm not sure how to fix it. I went through the entire thread, trying everything that people suggested until the error went away.

**Comment by caffeineaddiction** [comment]
It should be noted that OP's error also happens if you are running on a VPS that is using an old kernal

$ sudo /usr/bin/docker daemon
INFO[0000] libcontainerd: new containerd process, pid: 2042
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
FATA[0001] Your Linux kernel version 2.6.32-042stab116.2 is not supported for running docker. Please upgrade your kernel to 3.10.0 or newer.

**Comment by xwzyb** [comment]
I have the same problem with you . I solved it by delete the directory /var/lib/docker/devicemapper .Tell me if it helped you. Thank you.

**Comment by thuannvn** [comment]
@j127 works for me

**Comment by rzr** [comment]
reboot is optional

PRETTY_NAME="Ubuntu 14.04.5 LTS"

**Comment by arifch2009** [comment]
Remove the old docker and install new docker( Version:      1.13.1
 API version:  1.26)

`    $ sudo apt-get purge docker-engine


#Remove the old docker directory
    $ sudo rm -rf /var/lib/docker

    $ sudo apt-get update

# Install docker again
    $ sudo apt-get install docker-engine`

**Comment by thaJeztah** [comment]
For docker machine (and the local VirtualBox driver), the recommended way to upgrade is to do `docker-machine upgrade`. For other setups (e.g. on ubuntu), follow the regular upgrade procedures (which can be simply `sudo apt-get update && sudo apt-get install docker-engine`).

I'm locking the conversation on this issue so that it doesn't start to lead a life of its own;  if you have a bug to report, please open a new issue. 

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. If you want to get help with _running_ docker, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)
