### ISSUE TITLE
UX issue with orientation of 'Submit' and 'Back' buttons on Billing page

### ISSUE THREAD

**Issue by JackHampson** [docker/docker#20326]
Steps:
Visit 'Billing page' https://hub.docker.com/account/billing-plans/update/ to change payment information
Fill out all fields
Go to click action button on RHS (Right Hand Side) of screen, but hit 'Back' which sends me back to previous screen
Have to fill out all information again

Expected:
The Submit button is on the RHS

Observation
Submit button is on LHS

**Comment by thaJeztah** [comment]
Thanks for reporting @JackHampson. Unfortunately, Docker Hub is handled by a different team, and we cannot do anything about that in this repository.

I suggest to contact support@docker.com to open a ticket (which is for Docker Hub), or open an issue in https://github.com/docker/hub-feedback/issues.


I'm going to close this issue here, because of the reasons mentioned above, but thanks again for reporting. Feel free to comment here after I've close this issue :+1:

**Comment by JackHampson** [comment]
Thanks for pointing that out. I've raised the issue with them.

**Comment by thaJeztah** [comment]
Cool, thanks!
