### ISSUE TITLE
Keep track of --rm daemon side (container update) ?

### ISSUE THREAD

**Issue by vdemeester** [docker/docker#20334]
This is a *don't forget* issue related to #19116 and the `--rm` case. I'll quote @WeiZhang555 

---

Also today I may find another problem, if we run 
```
$ docker run --rm --restart=always busybox top
Conflicting options: --restart and --rm
```
So it forbid me from using `--restart` with `--rm`. Then what will happen if run 
```
$ docker run --rm busybox top
$ docker update --restart=always xxxx
```

I guess there will be something broken, I haven't checked it yet, later I will make a more detailed investigation.

---

The idea would be to *kinda* let know the daemon that the container is gonna be removed at some point and thus, disallow updating the restart policies. Not sure this is the right solution, but we need to think of it.

**Comment by tianon** [comment]
It's probably similar to what happens if you `docker rm -f` in a second terminal:
```console
$ docker run --rm --name test busybox top
...
$ # new terminal
$ docker rm -f test
...
$ # first terminal
Error deleting container: Error response from daemon: No such container: 54cf0f158b55a37d272a53f1890a0125d0dd38907e3ae86a626edafd50b47f42
Error: No such container: 54cf0f158b55a37d272a53f1890a0125d0dd38907e3ae86a626edafd50b47f42
```

So we're not really adding _more_ strange behavior, just highlighting even further that `--rm` is implemented client-side.  Maybe before doing the client-side delete, we should check the restart policy of the container, and only delete if it hasn't been updated in the meantime?  (since adding a restart policy is basically an explicit way of saying "I want this container to live on after death")

We see similar oddities with `docker restart`:
```console
$ docker run --rm --name test busybox top
... (starts running)
$ # new term
$ docker restart test
test
...
$ # first term
RACE CONDITION, but likely to see:
Error deleting container: Error response from daemon: Conflict, You cannot remove a running container. Stop the container before attempting removal or use -f
```

**Comment by vdemeester** [comment]
> Maybe before doing the client-side delete, we should check the restart policy of the container, and only delete if it hasn't been updated in the meantime? (since adding a restart policy is basically an explicit way of saying "I want this container to live on after death")

That's a good point/idea… didn't thought of that :stuck_out_tongue_closed_eyes:

**Comment by tianon** [comment]
Not sure whether we can change "docker restart" to jive with that too, but
maybe that's totally out of scope. :smile:

**Comment by WeiZhang555** [comment]
@vdemeester Thank you for help create this issue :smile: 

@tianon I like your idea, it makes sense and is easier to implement, I love it.  

I'll try to make a solution(probably based on @tianon 's suggestion) after  #19116 is merged.

**Comment by duglin** [comment]
Ultimately any client-side solution will be problematic - why not do it on the daemon side? Keep the `rm` flag in the state and based on the restartPolicy kill it when it stops?  For cases where the deamon is restarted, we already have a loop in place to kill old exec data we can reuse that to kill "left over" containers.

**Comment by WeiZhang555** [comment]
@duglin You're also right, I'm swinging...

Currently "--rm" is a client-side flag which caused lots of problems, maybe it's better to move it to daemon side, let daemon decides when to delete the container based on Restart Policy.

Client-side change may be hard to handle "--restart on-failure:3" because it's not aware of how many failures have happened and it shouldn't care that it's not client's work.

**Comment by duglin** [comment]
yes, and not only that but once the client hits control-C (or loses its connection) everything is all messed up - that's bad.

**Comment by thaJeztah** [comment]
@vdemeester is this now a dup of https://github.com/docker/docker/issues/16575? I saw that @AkihiroSuda proposed an approach here; https://github.com/docker/docker/issues/16575#issuecomment-182298779

**Comment by vdemeester** [comment]
@thaJeztah you are right, this seems kinda like a dup' of #16575 if we choose to handle that with daemon.

**Comment by WeiZhang555** [comment]
Since #19116 is already merged, I think it's time to consider how to handle this problem.
After these discussions above, I guess implement `run --rm` on the daemon side should be right approach. I've already read related discussion of #16575, that issue actually covers two part, one is `--rm` on daemon side and the other one is how to do garbage collection when client lost connection, and #16575 focus more on the latter one as I can see, so I think maybe we should go on discussion on `--rm` in this issue.

So here is the basic idea:
1. Implement `--rm` flag on the daemon side, adding a new flag named `Autoremove bool`(?) in `HostConfig`.
2. Allow `run --rm -d`, do NOT report conflicting error when calling `--rm` and `-d` any more.
3. If `--rm` is specified, restart policy can only be `no`. Forbid updating restart policy when `--rm` is set.
4. if container is started with `--rm` flag, `docker restart` will report error, because we'll meet same problem with restart policy, we can't decide whether the container should be restarted or removed  when it exits. As `--rm` often indicates a container to be temporary, this should be reasonable from my point of view.

What do you think? ping @vdemeester @tianon @duglin @thaJeztah @calavera

**Comment by AkihiroSuda** [comment]
@WeiZhang555 In your approach, there is no "garbage" issue because you detect the actual process exit rather than detecting TCP connection loss, right?
If so, I withdraw my proposal https://github.com/docker/docker/issues/16575#issuecomment-182298779, unless there is another need for `.[0].State.Attachers`.

**Comment by WeiZhang555** [comment]
@AkihiroSuda Yes, it will detect container's exit and remove it automatically on daemon side even client's TCP connection is lost.

**Comment by WeiZhang555** [comment]
What do you think of the design? ping @vdemeester @tianon @duglin @thaJeztah @calavera

**Comment by vdemeester** [comment]
@WeiZhang555 Sorry for the delay. I think your proposal makes sense, you can create a PR and we could discussed the design further more :wink:

**Comment by WeiZhang555** [comment]
@vdemeester OK, I'll start working on this, thank you for your response :laughing:

**Comment by duglin** [comment]
@WeiZhang555 sorry for the long wait... some commments:
1 - yup
2 - yup
3 - why do we need this restriction? I would prefer if we could make it so that we delete the container when the container stops and won't be restarted. This way if the host is rebooted we don't start to kill off containers if the restart policy is asking for the container to be started.  Likewise, I see no reason to not let them change the restart policy - all that matter is the current value of the policy when the container stops. It doesn't matter how often it changes before that point in time.
4 - same as 3.

**Comment by tianon** [comment]
What if we made "remove" a new restart policy?

**Comment by duglin** [comment]
that's an interesting idea.  I guess it depends on whether you want to have your container be restarted upon failure/host-reboot but also have it deleted upon "docker stop xxx".  Almost feels like two separate control knobs.

**Comment by WeiZhang555** [comment]
@duglin 
>3 - why do we need this restriction? I would prefer if we could make it so that we delete the container when the container stops and won't be restarted. This way if the host is rebooted we don't start to kill off containers if the restart policy is asking for the container to be started. Likewise, I see no reason to not let them change the restart policy - all that matter is the current value of the policy when the container stops. It doesn't matter how often it changes before that point in time.
>4 - same as 3.

This is just for avoid confusion, besides that, I feels "--rm" and "--restart" is kind of hostile to each other. From my point of view, "--rm" means "This container is temporary, please remove it after it finished, I won't need it any more", and "--restart(=always/on-failure/unless-stopped)" means "This container is executing some important job, make sure it's always running/serving, even after failure". So if user specifies "--rm" and "--restart" at the same time, can we say "--rm" should be handled before "--restart" or vise versa?

@tianon Hmm, this can be another choice, we can so many choices, I'm not sure which one is better

**Comment by WeiZhang555** [comment]
@tianon Hmm, this can be another choice, we can so many choices, I'm not sure which one is better

**Comment by duglin** [comment]
@WeiZhang555 I'm not sure I see the conflict between `--rm` and `--restart`.  To me `--restart` is about telling Docker when a container should be considered "done".   And `--rm` tells Docker what to do when that container reaches the "done" state. I don't see any overlap.

**Comment by WeiZhang555** [comment]
@duglin 
Ahh, sorry that I misread your comment! I thought you mean that we should respect `--rm` flag more than `--restart`, and automatically remove container regardless of the restart policy.

You are right! That sounds very reasonable and feasible.

Sorry for my poor English :cry:

**Comment by tianon** [comment]
@duglin the reason I suggested a restart policy is that I see restart polices as "what to do when this container _exits_/stops", which makes "remove" a perfect candidate :innocent:

**Comment by thaJeztah** [comment]
@tianon I see where you're coming from, but probably would've made more sense if the flag was called `--on-exit`. i.e. `--on-exit=do-nothing` `--on-exit=restart` `--on-exit=remove`

**Comment by duglin** [comment]
@tianon I understood what you were saying, but that means I can't have a restart policy of "unless-stopped" and "--rm=true".  Meaning, keep restarting it until I explicitly stop it, then go ahead and remove it.

**Comment by tianon** [comment]
Yeah, fair! :+1:
