### ISSUE TITLE
run --dns regression in 1.10 with user networks

### ISSUE THREAD

**Issue by jackstrain** [docker/docker#20338]
run --dns no longer works for user networks.

`docker network create test`
`docker run --dns=8.8.8.8 --net=test --rm ubuntu cat /etc/resolv.conf`

Prints:
nameserver 8.8.8.8 in 1.9
nameserver 127.x.x.x in current 1.10.1 (not sure about earlier versions)

Edit: This might just be how things are done now with the new dns based host resolution but I would just like to confirm. I need to prevent dns leaks in containers and without this option I will have to edit the resolv.conf every boot.

**Comment by thaJeztah** [comment]
The 127.0.0.11 DNS server is the embedded DNS used for discovering other containers in the same network (I.e., this allows you to `ping somecontainer`). All other DNS queries should be forwarded to the DNS server you specified.

Is there something in your use-case that no longer works in 1.10?

**Comment by mavenugo** [comment]
@jackstrain this is an expected behaviour. Please read the docs : https://docs.docker.com/engine/userguide/networking/configure-dns/ and https://docs.docker.com/engine/userguide/networking/dockernetworks/#docker-embedded-dns-server.

**Comment by jackstrain** [comment]
> Is there something in your use-case that no longer works in 1.10?

Yes I don't want to leak DNS requests on VPN containers.

I'm guessing the DNS Server at 127.0.0.11 uses the hosts network stack to resolve the dns queries that don't match other containers?

I'll remove the post tomorrow if noone has a good answer and this is really how things are supposed to be but atleast for my use case this is a regression.

**Comment by mavenugo** [comment]
@jackstrain 

> I'm guessing the DNS Server at 127.0.0.11 uses the hosts network stack to resolve the dns queries that don't match other containers?

That's correct. By `8.8.8.8` do you mean the globally reachable DNS server or is it a private DNS server for that container ? And since you are using bridge driver `docker network create test`, the container would have resolved to the globally reachable DNS server by default in 1.9, just like how it will behave in 1.10. Do you plumb the container differently ?

**Comment by sanimej** [comment]
@jackstrain 

> I'm guessing the DNS Server at 127.0.0.11 uses the hosts network stack to resolve the dns queries that don't match other containers?

Yes, its the current behavior. In your case how is the networking setup for VPN containers ? Are you using docker inbuilt driver (bridge or overlay) or a third-party plugin ?

**Comment by jackstrain** [comment]
@mavenugo 
> the container would have resolved to the globally reachable DNS server by default in 1.9, just like how it will behave in 1.10. Do you plumb the container differently ?

Sorry I don't know what this means but yes I used the standard bridge with `docker run --dns=customdns` and that would previously edit my resolv.conf and use my container's network stack for the resolves.

@sanimej 

> Are you using docker inbuilt driver (bridge or overlay) or a third-party plugin ?

I am using the bridge driver on a user created network. Basically one vpn container that gets NET_ADMIN caps for the firewalling/routing and then other containers just use it for container networking. If this sounds like a stupid way to do this I am open to ideas.

Thankyou for your time.

**Comment by mavenugo** [comment]
@jackstrain if you are using standard bridge driver, then the embedded DNS server must be able to forward the DNS request to your `customdns` that was run as a container. (even when the container's /etc/resolv.conf doesn't reflect that). But yes, the embedded DNS server will forward the DNS request from the host network stack. Will that cause a problem in your case ?
BTW, we have heard such request to use the container network stack instead of the host stack and we are evaluating the options.

**Comment by jackstrain** [comment]
Thankyou @mavenugo.

I will just replace resolv.conf on each container run for now and look forward the the request you mentioned.

I will mark the issue closed soon but I'm not sure if that stops people replying and I'm still hoping someone can tell me a way to prevent docker overwriting my /etc/resolve.conf even if it's a hack.
