### ISSUE TITLE
Decouple the CLIs

### ISSUE THREAD

**Issue by mlaventure** [docker/docker#20362]
As more and more projects make use of either the CLI of the daemon part of the Docker Engine, it now seems appropriate to break those responsibilities in two independent binaries, rather than relying strictly on compilation flags. Starting with Docker Engine 1.11, the binary will be split between `docker-daemon` (daemon-side, name to be confirmed) and `docker` (pure client-side code). This will allow for easier distribution of the client-side for multiple platforms (Mac, Windows, ...).

### Impacts

- Allows the daemon and the cli to evolve without affecting each other
- Reduce memory footprint of daemon
- Cleaner logic separation from a user point of view
- Will require having 2 binaries shipped within the distribution packaging
- No more one binary to rule them all

**Comment by duglin** [comment]
having `docker` and `dockerd` is probably the right thing to do, but I have to admit I'll be a little sad when it happens.

**Comment by LK4D4** [comment]
@duglin end of the single-binary age :( It was a time of joy and prosperity.

**Comment by HackToday** [comment]
Does that imply we would split docker repo into two parts ? docker-daemon and docker-client?

**Comment by icecrime** [comment]
@HackToday No repository split involved so far, as there is no obvious benefit here.

**Comment by WhisperingChaos** [comment]
In decoupling responsibilities from Docker Engine, was any consideration given to implementing secondary concerns, like CLI support, within containers?

One could refactor Docker Engine to provide only the core services needed to pull and run containers.  Thereafter, additional features, like CLI support, builder, Swarm, ... would simply be services running within their own containers.  In this scenario, docker would remain a single distribution binary with the following responsibilities:
* bootstrap Docker Engine to initialize and run its core services,
* and when called to process CLI requests simply forward them to the CLI container for execution.

Wouldn't Docker's own products benefit from the container paradigm?

**Comment by icecrime** [comment]
@WhisperingChaos This is pretty spot on, and something we are indeed considering :-) We'd like to base this off the current containerd integration work (#20662) which makes it possible to run containers without requiring daemon internals (e.g., graph).

**Comment by WhisperingChaos** [comment]
@icecrime 

Thanks for your reply and including #20662!  I'm happy this effort is well underway.

Along with others, I have been thinking about this implementation for a while now ([see post](https://groups.google.com/d/msg/docker-dev/mzpAga_XZ-Y/myMG1VCL8LsJ)) but the implementation is not as important as the following realization: the introduction of the container technology elevates the level of abstraction in which developers can both consume and deploy services.  Images, containers, and networks respectively replace the highly successful but more elemental abstractions of files, processes, and pipes, as these primitives are now encapsulated within these elevated ones.  That they are analogs of one another, just as the success that both enjoy isn't an accident, as they both capture, within their domains, the essential/minimal abstractions needed to compose viable services from interchangeable parts. 

Development teams should now focus on describing the implementation their designs using these elevated terms: Images, containers, and networks, instead of the low level primitive ones: file systems, processes, and pipes/sockets.  I'm confident the conversation will organically adopt these terms and I'll certainly push it along.

**Comment by HackToday** [comment]
hi @icecrime  Sorry I did not catch your above comments, I learned that containerd a daemon which just call runC(libcontainer), 

And you said that could run container without daemon internals (like graph)  Do you mean graph drivers ?

I did not find https://github.com/opencontainers/runc/tree/master/libcontainer container graph drivers, and I did not think it is part of libcontainer. Could you help explain ?

**Comment by thaJeztah** [comment]
Moving this to the 1.12.0 milestone, per https://github.com/docker/docker/pull/20639#issuecomment-197999255

**Comment by icecrime** [comment]
@HackToday I meant that even parts of the daemon could be run as containers on top of containerd. For example, the graphdrivers subsystem could be implemented as an independent tool.
