### ISSUE TITLE
--hostname does not properly validate the specified hostname

### ISSUE THREAD

**Issue by kohlerm** [docker/docker#20371]
---hostname does not check for the _ character which is not allowed in hostnames. 
See https://en.wikipedia.org/wiki/Hostname

This leads to hard to find issues, because a service inside the container might not work properly. 
I just ran into an issue with an old version of jboss that does validate the hostname, but only shows a relative generic error message. Something like "There might be an incorrect character or wrong port used"

The hostname specified should be validated. 
e.g --hostname bla_bla should lead to an error. 

$ docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:34:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:34:50 2016
 OS/Arch:      linux/amd64

$ docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 718
Server Version: 1.10.0
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.0-1.el7.elrepo.x86_64
Operating System: Red Hat Enterprise Linux Client 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.3 GiB
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by AndrewGuenther** [comment]
dibs

**Comment by AndrewGuenther** [comment]
I'm going to pick on @thaJeztah since he applied the networking label. I'm curious what your opinion is on where this should be applied. We could add a check to Docker ([`runconfig/opts/parse.go`](https://github.com/docker/docker/blob/master/runconfig/opts/parse.go)), libcontainer ([`libcontainer/configs/validate/config.go`](https://github.com/opencontainers/runc/blob/master/libcontainer/configs/validate/config.go)) or somewhere in libnetwork? Or all of the above. In the meantime, I'll at least submit a PR for adding it to `runconfig`.

Here is the regex I plan to use to validate the hostname. Its [RFC 1123](https://tools.ietf.org/html/rfc1123) compliant.

```
^(([[:alnum:]]|[[:alnum:]][[:alnum:]\-]*[[:alnum:]])\.)*([[:alnum:]]|[[:alnum:]][[:alnum:]\-]*[[:alnum:]])$
```

**Comment by thaJeztah** [comment]
There's also some prior discussions on validity of hostnames https://github.com/docker/docker/pull/8194#issuecomment-57379360, and https://github.com/docker/docker/pull/7787
