### ISSUE TITLE
Support multiple versions of the client protocol in the cli

### ISSUE THREAD

**Issue by ErikGrimes** [docker/docker#20405]
We have three environments, our development environment, our test environment, and our production environment.  We upgrade Docker in our development environments, then our test environments, and finally our production environment once we're sure that everything is working as intended.  However, upgrading Docker in our development environments makes the Docker cli unable to talk to our test and production environments (the client protocol is newer than the server protocol).  Currently we keep VM's around with the previous version of Docker installed, but this is cumbersome.  Ideally the Docker client would be backwards compatible with several of the previous versions of the Docker engine.

**Comment by thaJeztah** [comment]
Given that a newer client may support features that are not yet available in an older daemon, we cannot fully agree that it works, hence that error message.

However, as of docker 1.10, you can override the API version that is used by the client by setting the `DOCKER_API_VERSION ` environment variable. This allows you to use a client with an older daemon (basically, just for the situation you're describing). It doesn't come with warranty, so use at your own risk :smile:

See the pull-request; https://github.com/docker/docker/pull/15964

I'm going to close this issue, because we cannot guarantee *full* compatibility with an older daemon, but I think the `DOCKER_API_VERSION` should fix your use-case.

Feel free to comment / continue the discussion after I've closed this :+1:
