### ISSUE TITLE
docker 1.10 on Amazon Linux

### ISSUE THREAD

**Issue by Bekt** [docker/docker#20427]
Installing docker via `https://get.docker.com/` does not install the latest docker version (1.10). Specifically because of:

```
case "$lsb_dist" in
  amzn)
    (
    set -x
    $sh_c 'sleep 3; yum -y -q install docker'
    )
```

The latest version of docker in Amazon's package manager is 1.9.1.

```
[ec2-user@ip-x ~]$ yum info docker
Name        : docker
Arch        : x86_64
Version     : 1.9.1
Release     : 1.2.amzn1
Size        : 9.9 M
Repo        : amzn-updates/latest
```

Is there any way to install docker from a different repository on Amazon Linux? If so, the get.docker.com scripts should be updated as well.

**Comment by thaJeztah** [comment]
We currently don't build binaries for Amazon Linux, pending an official image from Amazon, to be able to build this. For reference, see https://github.com/docker/docker/pull/17283#issuecomment-163456402

So, unfortunately, at this moment you'll have to check with Amazon when there's an updated build available in their yum repository.

Once an official image is available for Amazon Linux, we can re-open https://github.com/docker/docker/pull/17283 so that we can provide builds for that distribution through our yum repository.

Thanks for suggesting; I'll close this issue for now, because this depends on Amazon, but feel free to continue the discussion here.

**Comment by nhoover** [comment]
+1 would really like to be able to upgrade to Docker 1.10 on my Amazon Linux instances. Need this fix https://github.com/docker/docker/pull/17877 

I'll put in a support ticket with AWS to see if they can get this going.
