### ISSUE TITLE
journald logging error when using Ubuntu 15.10

### ISSUE THREAD

**Issue by dmp1ce** [docker/docker#20497]
```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:41:30 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:41:30 2016
 OS/Arch:      linux/amd64
```
```
Containers: 11
 Running: 9
 Paused: 0
 Stopped: 2
Images: 183
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 219
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.8 MiB
Name: upgradeya
ID: BYQR:5LFW:YHLX:2DUG:AB27:IN3F:EPFT:JGEP:PKNU:MUN2:AHSK:XZK5
WARNING: No swap limit support
```

Vultr.com running Ubuntu 15.10.

1. Run container with journald logging driver
2. Run `docker logs` on the container using journald

The error is `Error running logs job: configured logging reader does not support reading`. The OS is Ubuntu 15.10. The error occurs whenever using the `journald` logging driver and then using `docker logs`. See #13707 and #20413.

Expected results is that the logs should be printed to the screen.

**Comment by thaJeztah** [comment]
ping @nalind :smile:

**Comment by nalind** [comment]
Given that the .pc file which we need to refer to in the `#cgo pkgconfig` directive differs between releases, there are at least two options:
* Duplicate the source file, with one copy using 'libsystemd' and the other using 'libsystemd-journal', and have make.sh set a build tag to one or the other depending on which one, if either, it finds.  Keeping the two otherwise in sync could get tiresome, but it would become unnecessary once releases with 'libsystemd-journal' fell off of the supported platform list.
* Have make.sh check for both, and depending on what it finds, create yet another .pc file (call it docker-libsystemd-journal.pc) in a directory in the source tree that lists what it found as a Requires:, set $PKG_CONFIG_PATH to point to the directory that contains the file, have read.go pull that in, and continue on as before.  The downside is that people building with 'go build' would also need to do the equivalent if they're using the 'journald' build tag.

I'm not super-fond of either plan, but if there's a preference, I can probably work up a patch.

**Comment by nalind** [comment]
Hmm, that first option looks like it can be done in a way that's less terrible than I originally thought.
