### ISSUE TITLE
User defined network requires a subnet when using --ip flag on docker run

### ISSUE THREAD

**Issue by robbrockbank** [docker/docker#20547]
I'm using a (libnetwork) network driver to handle networking and IPAM.  I've noticed that if you specify an IP address on the docker run command, it errors if you do not specify a subnet when creating the network.

```
$ docker run -tid --net net1 --name test --ip 192.168.100.122 busybox sh
27011decc0af611e9c060bfa2f3dbe0e1664af824c0c99764f1b25d86fecf635
docker: Error response from daemon: User specified IP address is supported only when connecting to networks with user configured subnets.
```

It seems overly restrictive to have to specify a subnet on the `docker network create` since my driver is taking care of all the networking and IPAM and the container is not connected to the docker bridge (the other end of the veth is dangling in the host ns).  I did see a comment related to this in issue #19418, but it didn't seem to cover the case of user defined networks.

I can include the JSON requests and responses from the network and IPAM driver if that would be useful.  Just let me know.

I've got a few questions:
-  Since I am using my own network plugin that handles IPAM and networking (and the container is not connected to the docker bridge), why is it necessary to specify a subnet when creating the network?
-  Can I work around this by specifying a subnet of 0.0.0.0/0 for my user-defined networks, or will that have disastrous consequences elsewhere (such as other containers that are using --net=bridge)?
-  Is it possible to just remove this restriction in docker for user defined networks?
-  Are there any plans to put in options on the docker run command that are passed to the network and ipam driver?

```
$ docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 20:39:58 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 20:39:58 2016
 OS/Arch:      linux/amd64

$ docker info
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 14
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 103
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host calico
Kernel Version: 3.19.0-15-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.86 GiB
Name: calicodev
ID: H2E7:VK52:6P4T:A2X5:ZZPQ:CAPE:63GT:F2JB:QSG6:UDTQ:6GWN:BF4T
Debug mode (server): true
 File Descriptors: 21
 Goroutines: 40
 System Time: 2016-02-20T11:34:22.387875756-08:00
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/bin/docker
 Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
Cluster store: etcd://127.0.0.1:2379

$ uname -a
Linux calicodev 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mavenugo** [comment]
@robbrockbank 

>  Since I am using my own network plugin that handles IPAM and networking (and the container is not connected to the docker bridge), why is it necessary to specify a subnet when creating the network?

There are 2 important reasons for this design.

1. If a container is assigned a static ip using `--ip`, it is expected that the container should be able to run even after a daemon restart. Daemon cannot assume or guarantee how an IPAM plugin is going to behave on a restart. If the IPAM driver that backs a network decides to use a different subnet, then the container will fail after the daemon restart. That impacts the UX badly.

2. Though your IPAM might be able to guarantee a stable subnet across reboots, docker also provides a modular way for operators to change the network and ipam plugins without the need to change the application. For example, developer can run a compose file (or) container just by specifying the network name and `--ip`. While the operator will decide which network or IPAM plugin to use based on the infrastructure that runs that particular application / container. This provides a mechanism to not bind the container to the infrastructure. Hence, the only way to guarantee a static `--ip` is by making sure the `docker network create` is done with the appropriate `--subnet`.

**Comment by robbrockbank** [comment]
HI @mavenugo 

Thanks for the details.

I'm not sure I follow what you mean though by tying the container to the underlying infrastructure.  Surely by specifying the --net option on the docker run command you're tying it to the infrastructure in that you are tying network and ipam management to the appropriate network and ipam driver.

Even considering points (1) and (2), it still seems that the necessity have the subnet specified on the network is more a property of the particular network and ipam drivers because your network driver can assign a different subnet on different runs.  For my particular use case, and with our drivers - we don't want to necessarily assign a subnet to network.

Given that this limitation does exist, and given that I'm using a separate ipam and network driver - will docker/libnetwork actually do anything with the subnet configuration, other than police the ip parameter and pass the information to the driver?  i.e. Is my particular workaround of specifying a full 0/0 subnet going to have any odd side-effects?

**Comment by aboch** [comment]
@robbrockbank 

Regarding 
>Can I work around this by specifying a subnet of 0.0.0.0/0 for my user-defined networks, or will that have disastrous consequences elsewhere (such as other containers that are using --net=bridge)?

AFAIK there should not be any side-effect, libnetwork is not doing any other check other than `ip belongs to the pool`.

**Comment by mavenugo** [comment]
@robbrockbank 
> I'm not sure I follow what you mean though by tying the container to the underlying infrastructure. Surely by specifying the --net option on the docker run command you're tying it to the infrastructure in that you are tying network and ipam management to the appropriate network and ipam driver.

Please consider this compose application -

```
$ cat docker-compose.yml
version: "2"

services:
  voting-app:
    image: docker/example-voting-app-voting-app
    ports:
      - "80"
    networks:
      - votenet
  result-app:
    image: docker/example-voting-app-result-app
    ports:
      - "80"
    networks:
      - votenet
  worker:
    image: docker/example-voting-app-worker
    networks:
      - votenet
  redis:
    image: redis
    networks:
      - votenet
  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - votenet
volumes:
  db-data:

networks:
  votenet:
```

for a dev `votenet` is a network created automatically by docker-compose and the dev doesnt care which driver it is using or which IPAM configs are being used. Infact, the above compose file will work as is and the default network driver `bridge` will be used and a subnet is automatically assigned.

Now, when an operator schedules the application say in staging... the op might add another override compose file, which extends the above application (or) create the above network independently before running the application.

```
$ cat docker-compose.override.yml
version : "2"

networks:
  votenet:
    driver: overlay
    ipam:
      config:
        - subnet: 70.28.0.0/16
          gateway: 70.28.5.254
```

In this example, the same application creates (or uses an existing network) with a different driver and different `subnet` configuration.

Hope that answers the reason how the `network` specified in the application/container is not tied to the infrastructure where it is executed.

Infact that is one of the reasons why we have `docker network` command isolated from `docker run` and not tie in the operator view of the infrastructure impact the container execution. Portability is one of the key requirement.

>  i.e. Is my particular workaround of specifying a full 0/0 subnet going to have any odd side-effects?

It is a clever workaround and is kinda equivalent to specifying multiple subnets in the `network create` which covers all the subnets. But libnetwork will fail with this error : `Error response from daemon: Pool overlaps with other one on this address space` because it is an overlapping address with existing default bridge `docker0` network. Hence you can infact create a network outside of the `docker0` subnet and that will take care of it.

**Comment by robbrockbank** [comment]
Hi @mavenugo 

I guess that specifies what you mean about infrastructure, but I'm not sure that it answers why the IP/subnet validation check is not the property of the network driver.  Sure it might be that most network drivers need to perform that validation and therefore building it into docker makes sense, but it is not the case that all network drivers have that requirement and so having that additional enforcement seems overly prescriptive given that there is no way to "opt out" of this checking.

**Comment by robbrockbank** [comment]
@mavenugo 

Regarding your point about the 0/0 subnet.  I have been able to create multiple networks using our driver that all have a 0/0 subnet which you inferred may not be possible.   Why is that?  It's good from my perspective because it allows me to do what I actually need to do given the subnet/IP restriction - but I'm nervous if you think that it shouldn't actually work.

**Comment by mavenugo** [comment]
@robbrockbank My comment was on default IPAM driver which will NOT allow overlapping subnet ranges across networks. By default, docker0 bridge is allocated a range from the global range (typically it is 172.17.0.0/16). When that happens, if any other network tries to allocate 0/0, it will fail because of the overlapping range.

If you are using your own IPAM driver & if you ignore this case, then yes, you may not hit this issue. But, if the containers using this IPAM plugin happens to overlap with that of the docker0 network range, it will result in forwarding issues and  you must be aware of it.

**Comment by mavenugo** [comment]
This issue can be closed.
