### ISSUE TITLE
 restart  container, the host is restarted 

### ISSUE THREAD

**Issue by houht** [docker/docker#20594]
I used to restart the container command, sometimes host automatically restart host。

command： docker restart container name

host version: Linux 2.6.32-431.el6.x86_64 

docker version: Docker version 1.7.1, build 786b29d/1.7.
docker info:

Containers: 11
Images: 200
Storage Driver: devicemapper
Pool Name: docker-253:0-2487440-pool
Pool Blocksize: 65.54 kB
Backing Filesystem: extfs
Data file: /dev/loop0
Metadata file: /dev/loop1
Data Space Used: 6.687 GB
Data Space Total: 107.4 GB
Data Space Available: 22.17 GB
Metadata Space Used: 10.08 MB
Metadata Space Total: 2.147 GB
Metadata Space Available: 2.137 GB
Udev Sync Supported: true
Deferred Removal Enabled: false
Data loop file: /var/lib/docker/devicemapper/devicemapper/data
Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 2.6.32-431.el6.x86_64
Operating System: 
CPUs: 4
Total Memory: 3.744 GiB
Name: localhost.localdomain
ID: REW4:5GRQ:TVHP:4B5A:MGXQ:4KVJ:PJOM:MXEU:PH3J:JXVQ:4EBT:MGDH

**Comment by HackToday** [comment]
It is one intersting question. Anything else in dmesg or docker logs ?

**Comment by thaJeztah** [comment]
This could well be an issue with RHEL6 and an outdated kernel. From the information provided, it looks like you're running an outdated version of RHEL6 and the kernel; see https://access.redhat.com/articles/3078. Always make sure your system is fully up to date, especially on RHEL/CentOS6.

Having said that, RHEL6/CentOS6 is no longer a supported platform for Docker because the kernel is too old. If possible, upgrade to RHEL 7.

I'm going to close this issue, because we no longer support this version of RHEL, but feel free to comment after I've closed
