### ISSUE TITLE
Improve/fix documentation on build-arg and caching

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#20612]
The documentation https://docs.docker.com/engine/reference/builder/#impact-on-build-caching explains that build-args only invalidate the cache for the first step in the Dockerfile that *uses* the build-arg.

Given that build-args are prepended to each `RUN` instruction, the cache is actually invalidated for each `RUN` instruction (the build-cache does not evaluate `RUN` commands to check if a build-arg is actually *used*).

The documentation should explain this more clearly.

I haven't checked yet if the build-cache actually evaluates `ENV` instructions to determine if the cache should be used or not, so this has to be checked before updating the documentation as well.

For more information/example/background, see https://github.com/docker/docker/issues/20136#issuecomment-187688636

**Comment by mikelinjie** [comment]
@thaJeztah, I have checked ENV,
As documentation written, in this example:
```
1 FROM ubuntu
2 ARG CONT_IMG_VER
3 ENV CONT_IMG_VER $CONT_IMG_VER
4 RUN echo $CONT_IMG_VER
```
cache miss occurs  on line 3 because the variable’s value in the ENV references the ARG variable,

and in this example:
```
1 FROM ubuntu
2 ARG CONT_IMG_VER
3 ENV CONT_IMG_VER hello
4 RUN echo $CONT_IMG_VER
```
cache miss does not occur, because ENV instruction will override an ARG of the same name,
so I agree that it appears to be working as designed, but documentation is a little misleading.

I make some additions the this part, and is this ok?

### Impact on build caching

`ARG` variables are not persisted into the built image as `ENV` variables are.
However, `ARG` variables do impact the build cache in similar ways. If a
Dockerfile defines an `ARG` variable whose value is different from a previous
build, then a "cache miss" occurs upon the first time it is possible to be used, not its declaration.
For example, consider these two Dockerfile:

```
1 FROM ubuntu
2 ARG CONT_IMG_VER
3 RUN echo $CONT_IMG_VER
```

```
1 FROM ubuntu
2 ARG CONT_IMG_VER
3 RUN echo hello
```
If you specify `--build-arg CONT_IMG_VER=<value>` on the command line, in both cases, the
specification on line 2 does not cause a cache miss; line 3 does cause a cache
miss. The definition on line 2 has no impact on the resulting image. The `RUN`
on line 3 executes a command and in doing so defines a set of environment
variables, maybe including `CONT_IMG_VER`. At that point, the `ARG` variable may
impact the resulting image, so a cache miss occurs.

Consider another example under the same command line:

```
1 FROM ubuntu
2 ARG CONT_IMG_VER
3 ENV CONT_IMG_VER $CONT_IMG_VER
4 RUN echo $CONT_IMG_VER
```
In this example, the cache miss occurs on line 3. The miss happens because
the variable's value in the `ENV` references the `ARG` variable and that
variable is changed through the command line. In this example, the `ENV`
command causes the image to include the value.

If an ENV instruction overrides an ARG instruction of the same name, like this Dockerfile:

```
1 FROM ubuntu
2 ARG CONT_IMG_VER
3 ENV CONT_IMG_VER hello
4 RUN echo $CONT_IMG_VER
```
There will be no cache miss on line 3.

**Comment by mikelinjie** [comment]
ping @thaJeztah  @proppy  Can you have have a look, and give some suggestions, I want to have PR.

**Comment by triccardi-systran** [comment]
I think the improved doc (from #21790 ) can be even more explicit for the following scenario: a `RUN` with no apparent use of the `ARG` environment variable.
In fact, any `RUN` will invalidate the cache if any `ARG` was previously declared.
This is pretty important: it happens all the time, the other examples are less common.

Suggestion: (additions in **bold**)
> Dockerfile defines an ARG variable whose value is different from a previous
build, then a "cache miss" occurs upon the first time it is possible to be used, not its declaration. **In particular, all `RUN` use the environment variables declared by previous `ARG`, thus always cause a cache miss if a previous `ARG` exists.**

**Comment by thaJeztah** [comment]
@triccardi-systran can you open a pull request with the improvements you think need to be added?

**Comment by triccardi-systran** [comment]
@thaJeztah Yes, I'll do that tomorrow.
