### ISSUE TITLE
Help me please!

### ISSUE THREAD

**Issue by mmoralesmc** [docker/docker#20632]
Hi, I'm new in Dockers... I'm following this tutoríal http://olatheander.blogspot.com.es/2014/07/dockerized-hello-world-web-app-using.html?m=1
but... When I run **docker build -t ubuntu-node-hello .** I have this error 

Error checking contexto: 'can't stat '/Users/mariamoralesmunoz/Library/Saved Application State/com.bitrock.appinstaller.savedState''.

And... If I run **sudo docker build -t ubuntu-node-hello .** I have this error... 

Post http:///var/run/docker.sock/v1.20/build?cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&t=mamoralesmc%2Fubuntu-node-hello&ulimits=null: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?

Can you help me please?? 

Thanks so much 

María

Output of `docker version`:

```
(paste your output here)
```

Output of `docker info`:

```
(paste your output here)
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
1.
2.
3.

Describe the results you received:

Describe the results you expected:

Provide additional info you think is important:

**Comment by thaJeztah** [comment]
Looks like you don't have the right environment variables set in your shell; try setting them using

    eval $(docker-machine env default)

You may also be interested in reading the getting started guide; https://docs.docker.com/mac/

and the user guide; https://docs.docker.com/engine/userguide/containers/dockerizing/


Please note that the GitHub issue tracker is *not* a generic support forum, but meant for reporting bugs and feature requests

This isn't a Docker bug, this is a question which is more appropriate for
1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker IRC channel on Freenode.
4) StackOverflow (https://stackoverflow.com)

1) and 2) should be better for longer conversations.

Since this isn't a bug, I'm going to close this now. Please feel free to comment.

**Comment by mmoralesmc** [comment]
docker versión:

Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64

docker info
Containers: 75
Images: 134
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 284
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: 4V23:BVAC:NCCW:JETN:WG2O:5XH7:HATP:HFZR:2F32:EWQP:3VOC:JVCI
Debug mode (server): true
File Descriptors: 11
Goroutines: 16
System Time: 2016-02-23T22:03:48.852812327Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: mmoraeles92
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
