### ISSUE TITLE
Random container IP

### ISSUE THREAD

**Issue by migorman** [docker/docker#20654]
Hi everyone,
 I'm docker newbie,i'm running mongoDB in a container and redisDB in an other container and i'm linking this tow databases to my nodeJS project wich is running in a third container.
 In order to connect to my databases i'm putting the IPs of my containers in my source code but everytime i'm restarting a container the IP is changing so i have to change it in my source code,How can i deal with this problem ?? 
Thanks in Advance :)

**Comment by thaJeztah** [comment]
You can access the other container using their container-name or the link-alias you provided. Please read this section about networking; https://docs.docker.com/engine/userguide/networking/dockernetworks/. The section about links; https://docs.docker.com/engine/userguide/networking/dockernetworks/#links

However, please keep in mind that GitHub isn't a general support forum. This is an issue tracker for Docker bugs, features and pull requests. Please take this into account when opening an issue.

This isn't a Docker bug, this is a question which is more appropriate for
1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker IRC channel on Freenode.
4) StackOverflow (https://stackoverflow.com)

1) and 2) should be better for longer conversations.

Since this isn't a bug, I'm going to close this now. Please feel free to comment.
