### ISSUE TITLE
Got 

### ISSUE THREAD

**Issue by IvanChen118** [docker/docker#20657]
Hi everybody, I downloaded docker installation package "Linux 64bit binary" from this website:
http://www.oschina.net/news/70887/docker-1-10-2-rc1

When I run ./docker daemon , I got below errors:

WARN[0000] Your Linux kernel version 2.6.32-358.el6.x86_64 can be unstable running docker. Please upgrade your kernel to 3.10.0. 
WARN[0000] devmapper: Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/daemon/#daemon-storage-driver-option 
WARN[0000] devmapper: Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section. 
WARN[0000] devmapper: Base device already exists and has filesystem ext4 on it. User specified filesystem  will be ignored. 
INFO[0000] [graphdriver] using prior storage driver "devicemapper" 
INFO[0000] Graph migration to content-addressability took 0.00 seconds 
INFO[0000] Firewalld running: false                     
ERRO[0000] could not get initial namespace: no such file or directory 
ERRO[0000] failed to set to initial namespace, readlink /proc/53113/task/53167/ns/net: no such file or directory, initns fd -1: function not implemented 
ERRO[0000] failed to set to initial namespace, readlink /proc/53113/task/53167/ns/net: no such file or directory, initns fd -1: function not implemented 
INFO[0000] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 
ERRO[0000] failed to set to initial namespace, readlink /proc/53113/task/53167/ns/net: no such file or directory, initns fd -1: function not implemented 
WARN[0000] Your kernel does not support cgroup memory limit: mountpoint for memory not found 
WARN[0000] mountpoint for cpu not found                 
WARN[0000] mountpoint for blkio not found               
WARN[0000] mountpoint for cpuset not found              
FATA[0000] Error starting daemon: Devices cgroup isn't mounted 

Could someone help me on this?Thanks very much!!!

**Comment by thaJeztah** [comment]
CentOS/RHEL 6, which use kernel 2.6 is no longer supported, and we no longer build RPM's for those systems. The static binaries you downloaded should **not** be used to run with the device mapper graph-driver, as they don't have Udev sync support, which **will** lead to data corruption. 

(note that 1.10.2-rc2 is outdated, 1.10.2 has been released: https://github.com/docker/docker/releases/tag/v1.10.2)


I'm closing this, because kernel 2.6 is not supported; if possible, upgrade to a newer system (e.g. RHEL/CentOS 7.x) and an up-to-date kernel.

Also note that GitHub is not a general support forum. This is an issue tracker for Docker bugs,
features and pull requests. Please take this into account when opening an issue, and use one of the following for questions:

1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker IRC channel on Freenode.
4) StackOverflow (https://stackoverflow.com)

1) and 2) should be better for longer conversations.

Since this isn't a bug, I'm going to close this now. Please feel free to comment.
