### ISSUE TITLE
How to define start order of containers when docker daemon is restared

### ISSUE THREAD

**Issue by jimmycmh** [docker/docker#20651]
I'm running volume driver as a container, and the driver container must be started befor other containers when docker daemon is restared.

container link provides some possibility, but still have obvious shortage.
1. container link is a legacy feature now in 1.10, and new net work model don't support link.
2. there are only two levels in link.

I'm proposing a "starting sequence" tag to container, and starts the containers by sequence.

Is it a good idea?

**Comment by thaJeztah** [comment]
Thanks for asking; we're currently in the process of designing / implementing a better plugin infrastructure, so that plugins can more easily be run in a container. For progress on this, please subscribe to this issue: https://github.com/docker/docker/issues/20363

I'll close this issue to keep the discussion in a single place, but feel free to comment here after I've closed
