### ISSUE TITLE
Enhancement: give friendly error message when non-image name passed to "docker save"

### ISSUE THREAD

**Issue by dbbernstein** [docker/docker#20709]
Output of `docker version`:

```
David@noe MINGW64 ~/extvol
$ docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64

David@noe MINGW64 ~/extvol
$
```

Output of `docker info`:

```
David@noe MINGW64 ~/extvol
$ docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 21
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 37
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.1.18-boot2docker
Operating System: Boot2Docker 1.10.2 (TCL 6.4.1); master : 611be10 - Mon Feb 22 22:47:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.1 MiB
Name: default
ID: 226R:TS6B:7ZBR:LRVK:UP2Y:HY6M:3L2N:XYK5:7QIH:4TIJ:AIO6:ULTN
Debug mode (server): true
 File Descriptors: 18
 Goroutines: 32
 System Time: 2016-02-25T22:45:17.889222018Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

David@noe MINGW64 ~/extvol
$
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

> Recent installation using docker-machine on Windows 10.

List the steps to reproduce the issue:

> 1. created data volume /var/lib/postgresql/data  in container based on debian:8.2 for use by known working image based on postgres:9.4.5
> 2. tried to run `docker save` on container with data volume

Describe the results you received:
```
David@noe MINGW64 ~/extvol
$ docker save data_vlpd > data_vlpd.tar
Error response from daemon: digest not found

David@noe MINGW64 ~/extvol
$ docker save -o data_vlpd.tar data_vlpd
Error response from daemon: digest not found

David@noe MINGW64 ~/extvol
$
```

Describe the results you expected:

> Friendly error message along lines of `"data_vlpd" is not an image`

Provide additional info you think is important:

```
Motivated by #20705 . Filed at suggestion of @thaJeztah
```

**Comment by HackToday** [comment]
#dibs

**Comment by HackToday** [comment]
I'd like to take a look at this. ping @thaJeztah

**Comment by thaJeztah** [comment]
Thanks @HackToday!

**Comment by HackToday** [comment]
hi @tonistiigi  I did some research and found that in 
https://github.com/docker/docker/commit/eeb2d4c1adbe4e00f9fbcdc70f9ac31997968e1d

it add related logic, and that would cause non-exist image have no digest error output.


But I tried to add logic in daemon.go to check if image exist or not first before do save operation, but it is not fix, because save image accept general repo without tag, so GetImage can not work.

It may need some change in your commit change before.  I did not quite understand complicated content-address image logic there. Maybe you are more familiar with that. Could you take a look at that ?

**Comment by tonistiigi** [comment]
@HackToday Repo without the tag means saving all tags for the image. The reason why there is so much logic there is the order of priority for different inputs. The order should be digest, digest prefix, repo:tag, repo, hex. For this specific error `ErrDigestNotFound` , it can only come if you search digest from imagestore and it cannot be found. So maybe just rewrite this specific error instead of trying to detect it before calling.

**Comment by HackToday** [comment]
hi @tonistiigi  

1) what do you think the error should be?  We should have  "Image can not be found" message, but I am not sure if `ErrDigestNotFound` here is right place to do changed with  "Image can not be found" message.

2) And also from `https://docs.docker.com/engine/reference/commandline/save/` I did not it said related format for ` digest, digest prefix, repo:tag, repo, hex` it just have repo and repo:tag

**Comment by HackToday** [comment]
ping @tonistiigi

**Comment by tonistiigi** [comment]
> 1) what do you think the error should be? We should have "Image can not be found" message, but I am not sure if ErrDigestNotFound here is right place to do changed with "Image can not be found" message.

`ErrDigestNotFound` should not come from anywhere else so should be safe to replace. I'm not sure if all cases will fail with this error though. This should happen if every other method fails and we are trying to match the input as a part of an image ID. You should not replace the original error. Just detect that if you the imagestore returns `ErrDigestNotFound` you instead show some nice error to the user.

 > 2) And also from https://docs.docker.com/engine/reference/commandline/save/ I did not it said related format for digest, digest prefix, repo:tag, repo, hex it just have repo and repo:tag

Image ID (+ partial) is also supported. The order is just a best effort to avoid collisions.
