### ISSUE TITLE
Size & VirtualSize missing from distribution manifest config JSON

### ISSUE THREAD

**Issue by mattrgreen** [docker/docker#20717]
Since 1.10 and the migration to store local images & layers by content addressable digests, any images pushed to a private registry will no longer have the Size or VirtualSize fields in either the v1Compatability array (manifest schema 2.1) or the separate config JSON (manifest schema 2.2).

Presumably this is because the Size/VirtualSize is now stored on disk in a "size" file locally, instead of in the JSON for each layer. Was the removal of these fields an intended regression?

**Comment by tonistiigi** [comment]
Yes, we use locally calculated size because in some cases the graphdrivers do not produce same results for that field(and because IDs are checksums of content we can't have changing fields in there). Also, if we would just use a number in the config there would be no way to validate the correctness of it.

**Comment by LK4D4** [comment]
@tonistiigi Do you think this should be closed?

**Comment by tonistiigi** [comment]
@LK4D4 Indeed
