### ISSUE TITLE
Should the file created by --cidfile be removed when the container dies?

### ISSUE THREAD

**Issue by JesusTinoco** [docker/docker#20766]
Output of `docker version`:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64
```

List the steps to reproduce the issue:

1. `docker run --rm --cidfile=/tmp/my-container.cid debian:jessie ls`
2. `cat /tmp/my-container.cid # The cid file persists once the container is removed`

Describe the results you received:

Using the `--cidfile` option in the `run` command, the file is still persisting once the container dies.

Describe the results you expected:

Should this file be removed when the container dies? Or is its persistence the correct behaviour?

**Comment by thaJeztah** [comment]
This is the correct behavior; the file is just a convenience to store the container-id, it's not a "pidfile", so it's not related to the process running in the container. 

Removing if when the container is removed also cannot be done, because the "client" and "daemon" may not be on the same host; the container may be removed from another client.

I'll close this, but feel free to comment after I've closed
