### ISSUE TITLE
Builder: create more unit-tests and improve coverage

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#20784]
Now that the builder is decoupled from other parts of the engine
(see https://github.com/docker/docker/issues/14298#issuecomment-185404706),
we want to make improvements to test-coverage of that package.

- Write more unit-tests
- Review existing integration-tests to check if they can be implemented as a unit-test instead

**Comment by tkopczynski** [comment]
@thaJeztah I would like to work on those tests if no one's already doing it.

Just one thing: how would like them to be submitted for the review? As one PR or several smaller ones? Or maybe I would open a single PR and mark it as a _work in progress_?

For me it would be better to submit portions of code because this will probably take a while to complete  and I would prefer to get code review response as soon as possible.

**Comment by vdemeester** [comment]
@tkopczynski ping me on irc, as I'm gonna work on it too :stuck_out_tongue_closed_eyes: 

> For me it would be better to submit portions of code because this will probably take a while to complete and I would prefer to get code review response as soon as possible.

Exactly. It's better to do a whole lot of small steps than one big that is too hard to review for maintainers :wink:

**Comment by thaJeztah** [comment]
@tkopczynski awesome that you want to help on this!

**Comment by thaJeztah** [comment]
I'll close this issue, as there's been a lot of improvements, but more is always welcome!
