### ISSUE TITLE
Why i can't use option -t when checking images

### ISSUE THREAD

**Issue by thinhduckhoi** [docker/docker#20808]
This is an article from docker homepage i just read today.
https://docs.docker.com/docker-cloud/tutorials/optimize-dockerfiles/
And you can see that they mentiond about the command "docker images -t" to see all of the layers.
But when i executed that command.
`[root@ip-10-0-7-48 docker]# docker images -t

flag provided but not defined: -t
See 'docker images --help'.`

I checked for all options and didn't see any -t option.
I'm running Docker version 1.10.2 on CentOS 7.

**Comment by thaJeztah** [comment]
Looks like that documentation is not up-to-date, because the `-t` (and `--tree`) flags have been deprecated a long time ago https://github.com/docker/docker/pull/5001, and have been removed in 

There's a proposal to bring it back in some form, but the change to content-addressable images in Docker 1.10 makes this not trivial, see https://github.com/docker/docker/issues/17366#issuecomment-169787909

You can, however, use the dockviz image to achieve the same; https://github.com/justone/dockviz. That image was created by the author that originally implemented the `-t` feature in docker

**Comment by HackToday** [comment]
@thaJeztah  I did not htink dockviz would support content-addressable images.

**Comment by thaJeztah** [comment]
If you're optimizing a specific image, perhaps `docker history`is a good or even better solution, for example;

```
docker history ubuntu
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
06ab2de020f4        11 weeks ago        /bin/sh -c #(nop) CMD ["/bin/bash"]             0 B
d5bdf8bb1e25        11 weeks ago        /bin/sh -c sed -i 's/^#\s*\(deb.*universe\)$/   1.895 kB
0c844eeeeea3        11 weeks ago        /bin/sh -c echo '#!/bin/sh' > /usr/sbin/polic   194.5 kB
179d14f5dee8        11 weeks ago        /bin/sh -c #(nop) ADD file:9b5ba3935021955492   187.7 MB
```

**Comment by thaJeztah** [comment]
@thinhduckhoi I've opened an internal ticket for the Docker Cloud docs team to address this, so I'll close the issue here. Thanks so much for reporting!

Feel free to comment here if you have more questions about this, then I'll try to answer

**Comment by justone** [comment]
dockviz is ever so slightly less useful now with content-addressable images.  The only effect on output is that incremental sizes are no different from cumulative sizes.  It's still very useful for seeing the parentage of an image.  It'd be great to have more information come over the API (#20451).

**Comment by justone** [comment]
FYI, with the [v0.4 release](https://github.com/justone/dockviz/releases/tag/v0.4), dockviz properly handles content-addressable images.

**Comment by thaJeztah** [comment]
Nice work @justone!
