### ISSUE TITLE
Label that hides containers from ps

### ISSUE THREAD

**Issue by Tebro** [docker/docker#20937]
Would like to see a way to hide system containers from "docker ps" (without "-a")

The same way that UCP and Swarm hides their system containers.

This would be good so that one can "hide" containers that handle infrastructure, such as overlay storage drivers and key-value stores that are used for networking etc.

**Comment by thaJeztah** [comment]
Hi @Tebro, thanks for suggesting. I think this is part of the plans for https://github.com/docker/docker/issues/20363, which is on the roadmap. However, feel free to comment/subscribe to that issue to keep track on progress.

I'll close this issue so that we can keep the discussion centralized, but leave a comment if you disagree :)

**Comment by richmondwang** [comment]
how is this done now?
