### ISSUE TITLE
How to disable embedded DNS in docker 1.10

### ISSUE THREAD

**Issue by skairali** [docker/docker#20941]
As of Docker 1.10, the docker daemon implements an embedded DNS server which provides built-in service discovery.  In our case we want to disable this Embedded DNS and use external DNS by default. Is there anyway I can disable embedded DNS  for all endpoints regardless of network driver type?

**Comment by skairali** [comment]
Right now its based on whether its User defined or not.  https://github.com/docker/docker/blob/master/container/container_unix.go#L315  Here I would say it would be beneficial if we can disable the embedded DNS by calling  libnetwork.CreateOptionDisableResolution()   based on some DOCKER OPTIONS we can configure.

**Comment by sanimej** [comment]
@skairali Embedded DNS server introduced in 1.10 replaces the /etc/hosts based name resolution in previous releases. Since it replaced an existing feature there is no knob to disable it. You can continue to pass your DNS server using the --dns option and it will be used if the embedded server can't resolve a name or doesn't support a query type. Refer to #19474
