### ISSUE TITLE
Docker daemon failed to start on Windows 10

### ISSUE THREAD

**Issue by williamn** [docker/docker#21144]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      windows/amd64
An error occurred trying to connect: Get http://127.0.0.1:2375/v1.22/version: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.
```

**Output of `docker info`:**

```
An error occurred trying to connect: Get http://127.0.0.1:2375/v1.22/info: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VirtualBox 5.0.16

**Steps to reproduce the issue:**
1. Install Docker using DockerToolbox-1.10.3.exe
2. Run `docker run hello-world` to test the installation
3. Restart the PC
4. Open Docker Quickstart Terminal

**Describe the results you received:**

Docker daemon failed to start.

**Describe the results you expected:**

Docker daemon succesfully started.

**Additional information you deem important (e.g. issue happens only occasionally):**

Output of `docker daemon`

```
time="2016-03-12T08:42:46.128656500+07:00" level=warning msg="/!\\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\\"
time="2016-03-12T08:42:46.132581900+07:00" level=error msg="Failed to load vmcompute.dll - error Failed to load vmcompute.dll: The specified module could not be found."
time="2016-03-12T08:42:46.133562800+07:00" level=fatal msg="Error starting daemon: Couldn't restore custom images: Failed to restore base images: Failed to load vmcompute.dll - error Failed to load vmcompute.dll: The specified module could not be found."
```

**Comment by thaJeztah** [comment]
I suspect the environment variables are not setup properly, because the IP address that's being used is 127.0.0.1, which isn't correct (the daemon runs in a Virtual Machine on Windows, not on the Windows host itself).

Have you tried setting the environment variables, using the instructions that `docker-machine env default` give you?

Please note that this is an issue with docker toolbox, not with the docker engine, so please open this issue in the docker toolbox issue tracker https://github.com/docker/toolbox/issues

I'll close this issue here, but hope that the hints above help you further. Feel free to comment after I've closed

**Comment by williamn** [comment]
@thaJeztah Thank  you for the explanation. I found out that my issue is somehow connected to docker/toolbox#153 so I think I will go there.

I just uninstall the Toolbox so I can't give you my `docker-machine env default`
