### ISSUE TITLE
Odd Behavior for 1.10.x Registry v1 Pushes

### ISSUE THREAD

**Issue by ekristen** [docker/docker#21147]
I know things changed with 1.10, but registry v1 is still supported, but using a registry v1 is painful now. Takes over 70 seconds before it attempts to push an image, then takes much longer per image then docker 1.9.1 and below.

**Output of `docker version`:**

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.6
 Git commit:   c3959b1
 Built:        Tue Feb 23 21:12:32 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 23
 Running: 0
 Paused: 0
 Stopped: 23
Images: 2222
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 2276
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-39-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.797 GiB
Name: random
ID: J5MX:3AOW:4ASK:PT4U:Z4JX:XZWF:VAKF:YBUI:TYMY:Z4KV:OX3R:SFJT
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 34
 System Time: 2016-03-11T23:21:28.202728025-05:00
 EventsListeners: 0
 Init SHA1: 14bbd54b64d2a737269118ce4f1613787e2d0ce8
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
Username: random
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Build an image
2. Push to a v1 registry

**Describe the results you received:**
All the layers go into **waiting immediately**

```
f14109b5884e: Waiting
bd389813facf: Waiting
0dbcdbf526ce: Waiting
187d53198f19: Waiting
6384a5c74e87: Waiting
3612bd767d5f: Waiting
dd72ba050b45: Waiting
309b7466071b: Waiting
4353bfbc20c0: Waiting
5f70bf18a086: Waiting
90f774439683: Waiting
dfd83ed44976: Waiting
217e6c75dcfc: Waiting
c0b5f9221fac: Waiting
```

Then the first 5 layers immediately go into **Retrying**

```
f14109b5884e: Retrying in 6 seconds
bd389813facf: Retrying in 6 seconds
0dbcdbf526ce: Retrying in 6 seconds
187d53198f19: Retrying in 6 seconds
6384a5c74e87: Retrying in 6 seconds
3612bd767d5f: Waiting
dd72ba050b45: Waiting
309b7466071b: Waiting
4353bfbc20c0: Waiting
5f70bf18a086: Waiting
90f774439683: Waiting
dfd83ed44976: Waiting
217e6c75dcfc: Waiting
c0b5f9221fac: Waiting
```

Then after about 5 retries (70+ seconds), docker starts pushing from the bottom up.

```
f14109b5884e: Waiting
bd389813facf: Waiting
0dbcdbf526ce: Waiting
187d53198f19: Waiting
6384a5c74e87: Waiting
3612bd767d5f: Waiting
dd72ba050b45: Waiting
309b7466071b: Waiting
4353bfbc20c0: Waiting
5f70bf18a086: Image successfully pushed
90f774439683: Pushing [==>                                                ] 10.31 MB/178 MB
dfd83ed44976: Image successfully pushed
217e6c75dcfc: Already exists
c0b5f9221fac: Already exists
```

It finally pushes.

**Describe the results you expected:**

Tough to say, with the change to content addressable layers and sha256 hashes, I'm not sure how much really changed in the registry pushing process, but since the v1 registry hasn't been deprecated, prior to 1.10.0 release it would sequentially go through the layers and identify the ones that were already pushed and push the new one, one at a time. 

It would also push immediately, none of this retry for 70+ seconds before doing anything.

**Comment by aaronlehmann** [comment]
Thanks for the report. This isn't normal behavior when pushing to a v1 registry. The Docker daemon starts by trying the v2 registry protocol, and it if it sees a HTTP error response that looks like it came from a v2 registry, it will keep trying with the v2 protocol instead of switching to the v1 protocol immediately. I think that's what is happening here - your v1 registry is being incorrectly detected as a v2 registry.

What registry software are you using? Is it Docker's `registry` v1 or a third party implementation?

Do you happen to know if the registry (or a proxy sitting in front of it) returns JSON in the body of HTTP error responses? That's the first thing that comes to mind which would explain the incorrect detection, though it's probably not the only explanation.

It would be helpful to see a daemon log in debug mode (`docker daemon -D`) and a registry log.

**Comment by ekristen** [comment]
I think it's very possible that it is detecting things incorrectly, this isn't the first time registry version detection has been a problem, IIRC.

I'm using docker's v1 registry, however I am using my own open source index implementation (which has worked flawlessly up until 1.10.x). https://github.com/ekristen/docker-index

It's very possible that my index is returning something that is causing incorrect detection.

Could you point me to where the detection code is?

In the mean time, when I get some time today (hopefully) I'll grab some debug logs for you.

**Comment by aaronlehmann** [comment]
@ekristen: Have a look at https://github.com/docker/docker/blob/v1.10.2/distribution/registry.go#L140

**Comment by ekristen** [comment]
That's the retry logic, what about the detection logic? I'm mobile right now I'll try and parse through the code, but if someone from the distribution team can explain or point me to how things are actually detected that would be useful. Thanks!

**Comment by aaronlehmann** [comment]
I think the retry logic is what matters here, because the problem you're seeing is unnecessary retries before it eventually switches to the v1 protocol. If you want to see the logic for whether the v1 protocol will be used at all, this is the relevant code: https://github.com/docker/docker/blob/v1.10.2/registry/registry.go#L212

**Comment by ekristen** [comment]
That makes sense. I wasn't looking at it from that perspective. I'll see if I can't throw it in debug and see what I can find. Thanks.

**Comment by ekristen** [comment]
The logs are not very helpful

```
time="2016-03-13T03:12:58.624389550Z" level=error msg="Upload failed, retrying: <nil>"
```

I think the problem is that the error is nil and that is unexpected.

**Comment by aaronlehmann** [comment]
I believe `<nil>` means that the errors slice is empty: https://github.com/docker/distribution/blob/master/registry/api/errcode/errors.go#L183

So most likely what's happening is that the client tries to parse an error response body as JSON, and ends up with an empty `errcode.Errors` slice.

One way to fix this would be to make `retryOnError` check for this case and return `xfer.DoNotRetry`. It seems like a reasonable thing to do, since if the remote host is returning something we interpret as an empty list of v2 errors, it's probably not a real v2 registry. Alternatively, perhaps this check belongs in the `docker/distribution` client library, and it should return `UnexpectedHTTPResponseError` if it doesn't decode any valid errors.

**Comment by ekristen** [comment]
Either option sounds good to me.

**Comment by ekristen** [comment]
@stevvooe thoughts on getting a fix for this? This is a pretty brutal experience right now.

**Comment by runcom** [comment]
will be fixed by https://github.com/docker/docker/issues/21283

**Comment by ekristen** [comment]
Sounds great @runcom thanks

**Comment by stevvooe** [comment]
@ekristen I think @aaronlehmann and @runcom have you covered. Sorry for the pain here. Let me know if you need anything else.
