### ISSUE TITLE
downgrade from 1.10 to 1.9 makes images go unnamed

### ISSUE THREAD

**Issue by jordimassaguerpla** [docker/docker#21208]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**

Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.4.2 gccgo (SUSE Linux) 5.2.1 20150721 [gcc-5-branch revision 226027]
 Git commit:   9e83765
 Built:        
 OS/Arch:      linux/ppc64le

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.4.2 gccgo (SUSE Linux) 5.2.1 20150721 [gcc-5-branch revision 226027]
 Git commit:   9e83765
 Built:        
 OS/Arch:      linux/ppc64le

**Output of `docker info`:**

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 1.10.3
Storage Driver: btrfs
 Build Version: Btrfs v4.1.2+20151002
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null bridge host
Kernel Version: 3.12.51-60.20-default
Operating System: SUSE Linux Enterprise Server 12 SP1
OSType: linux
Architecture: ppc64le
CPUs: 8
Total Memory: 3.711 GiB
Name: ps64vt1093
ID: BG5I:42OA:3WKA:6IFH:Z5RE:WTMJ:UVHF:YIVB:4QJ4:DOE6:FVEY:4WO5
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Install docker 1.9.1
2. pull any image
3. Install docker 1.10.3
4. Install docker 1.9.1
5. pull another image
6. Install docker 1.10.3
7. run "docker images"

**Describe the results you received:**

You'll see the image pulled on 5 has no name.

**Describe the results you expected:**

the image keeps its name

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
Yes, this is expected; docker 1.10 has a new content-addressable store, and migrates all images the first time docker is started after upgrading. Once upgraded, this process will no longer be performed, so the images you downloaded after downgrading to 1.9.1 are not migrated when 1.10.3 is started, and won't be visible. Read about the migration to content-addressable store in this wiki; https://github.com/docker/docker/wiki/Engine-v1.10.0-content-addressability-migration

Note that we have never supported downgrading to older versions, although with other versions downgrading may have been less problematic and "worked" in many cases.

I'll close this issue, because this is expected, but feel free to comment here after I've closed
