### ISSUE TITLE
Flaky test: TestRestartStoppedContainer

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#21211]
Looks like a flaky test on WindowsTP4 https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/2759/console.  Seen on https://github.com/docker/docker/pull/21196

```
DockerSuite.TestRestartRunningContainer	28.710s
02:53:45 
02:53:45 ----------------------------------------------------------------------
02:53:45 FAIL: docker_cli_restart_test.go:13: DockerSuite.TestRestartStoppedContainer
02:53:45 
02:53:45 docker_cli_restart_test.go:24:
02:53:45     c.Assert(out, checker.Equals, "foobar\nfoobar\n")
02:53:45 ... obtained string = "foobar\n"
02:53:45 ... expected string = "" +
02:53:45 ...     "foobar\n" +
02:53:45 ...     "foobar\n"
02:53:45 
02:53:45 
02:53:45 ----------------------------------------------------------------------
```

**Comment by yongtang** [comment]
The issue seems to be because of the out-of-order of `docker logs` command. Inside the test, a `docker restart` command is followed by a `docker logs` command. However, `docker restart` returns immediately so `docker logs` might have been finished even before the `echo foobar`.

It is not easy to repeat this issue but if the test code is changed into the following (by sleep 2 seconds before echo), then the issue will be repeated reliably:
```
func (s *DockerSuite) TestRestartStoppedContainer(c *check.C) {
	dockerCmd(c, "run", "--name=test", "busybox", "sh", "-c", "sleep 2 && echo foobar")
	cleanedContainerID, err := getIDByName("test")
	c.Assert(err, check.IsNil)

	out, _ := dockerCmd(c, "logs", cleanedContainerID)
	c.Assert(out, checker.Equals, "foobar\n")

	dockerCmd(c, "restart", cleanedContainerID)

	out, _ = dockerCmd(c, "logs", cleanedContainerID)
	c.Assert(out, checker.Equals, "foobar\nfoobar\n")
}
```

Let me see if I could find a way to wait for the finish of container before `docker logs`.

**Comment by yongtang** [comment]
#dibs
