### ISSUE TITLE
json-file logger doesn't close log file, preventing container from being removed.

### ISSUE THREAD

**Issue by swernli** [docker/docker#21231]
Output of `docker info`:
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.11.0-dev
Storage Driver: windowsfilter
 Windows:
Execution Driver:
 Name: Windows 1854
 Build: 1.11.0-dev 6c2f438
 Default Isolation: process
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat transparent null
Kernel Version: 10.0 14282 (14282.1003.amd64fre.rs1_onecore_container_hyp.160306-1800)
Operating System: Windows Server 2016 Technical Preview 5 Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 863.3 MiB
Name: WIN-JGURQ6E8MQ3
ID: GQWQ:BAWE:RZSG:MDYN:ONSQ:TX6N:P5AU:AX6P:BNKE:TTAR:PIG4:GE65
Docker Root Dir: C:\ProgramData\docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: -1
 Goroutines: 19
 System Time: 2016-03-15T15:17:46.5815892-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/

Output of `docker version`:
Client:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   6c2f438
 Built:        Tue Mar 15 13:55:08 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   6c2f438
 Built:        Tue Mar 15 13:55:08 2016
 OS/Arch:      windows/amd64

Steps to reproduce the issue:
1. docker run --name test <img> <command>
2. docker logs test
3. docker rm test

I would expect this to be able to remove the container, but instead it fails to remove the json log file.  It turns out that the file is never closed after the logs command completes.  If the daemon is restarted, the file can be deleted, but since the container configuration is already gone, the rm command will fail, meaning that the graphdriver storage gets leaked for that container.  I think the same bug exists on Linux, but there the open handle doesn't prevent deletion.

**Comment by jstarks** [comment]
This appears to be because we call container.StartLogger() in daemon/logs.go, but if the container stays running, then nothing ever closes the logger after we are done. I'm not certain what the right solution is... maybe we should ref count the use of loggers?

I think there's also a file leak in jsonfilelogs.followLogs() when there's a rotation, but this doesn't seem to be the cause of this particular problem.

**Comment by swernli** [comment]
I believe I've found the fix, so I'll submit a PR for this.

**Comment by mlmeyers** [comment]
It appears this issue has been reintroduced. I am encountering the same on both windows 10 creators update and server 2016 on a pretty consistent basis on multiple containers running the latest stable docker version. I am not running any AV and lock is held by the docker process.

unable to remove filesystem for a8dfea0f59f6602529e75c1fec6cbe68aca09e7ddec1032cdba360750e8c9a52: remove C:\ProgramData\docker\containers\a8dfea0f59f6602529e75c1fec6cbe68aca09e7ddec1032cdba360750e8c9a52\a8dfea0f59f6602529e75c1fec6cbe68aca09e7ddec1032cdba360750e8c9a52-json.log: The process cannot access the file because it is being used by another process.

Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.24)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:15:52 2017
  OS/Arch:      windows/amd64
  Experimental: true
