### ISSUE TITLE
Why to showed the BLOCK I/O has been no change?

### ISSUE THREAD

**Issue by lioncui** [docker/docker#21317]
```
docker stats fd49d51e1c82
CONTAINER           CPU %               MEM USAGE / LIMIT    MEM %               NET I/O             BLOCK I/O
fd49d51e1c82        0.00%               1.12 GB / 1.928 GB   58.12%              1.192 kB / 648 B    3.502 MB / 0 B
```
BLOCK I/O has been no change after long time.
Even if i use "dd" to write a 2G file.

**Comment by coolljt0725** [comment]
@lioncui  I think use a `oflag=direct` in your `dd` cli, you can find the statistic of blkio will update immediately. Because there is a `page cache` above the block device, in general, the `write` operation will write to the `cache` first, it's asynchronous, the `blk cgroup` only take effect on synchronous io for now.

I think this is not a docker issue, ping @thaJeztah  can we close this?

**Comment by lioncui** [comment]
@coolljt0725 thk your answer, i close this.
