### ISSUE TITLE
confused restart policy

### ISSUE THREAD

**Issue by ZYNCMA** [docker/docker#21359]
I have read the introduction on https://docs.docker.com/engine/reference/run/#restart-policies-restart, but I'm really confued about **on-failure, always and unless-stopped**. 
It seems that these restart policies work depending on the exit status of containers, but when I ran `docker stop` on a container and its exit staus became 137, none of those three restart policies restarted the container.
So what exit status actually means? If the restart policy doesn't work on `docker stop` or `docker kill` or anything else, can you detail more?
By the way, is there a way to **actually always restart** a container, even if it's stopped by `docker stop` or `docker kill`?

**Comment by thaJeztah** [comment]
If you manually stop a container (`docker stop foo`), docker won't restart that container until the daemon is restarted. Having a restart *does* restart the container in other situations. If you (for example) send a `kill` to the process that's running in the container, docker will automatically restart the container and increment the restart-count;

    docker run -d --restart=always --name foo nginx

Find the process and kill it;

    ps aux | grep nginx
    ....
    kill 28127

And see that the container's RestartCount is incremented;

    docker inspect --format "{{ .RestartCount }}" foo
    1


Hope this helps!


I'll close this issue, because the GitHub issue tracker is *not* a general support forum, but for reporting bugs and feature requests. For these kind of questions, it's better to use;

- forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow

Feel free to comment here after I've closed

**Comment by ZYNCMA** [comment]
@thaJeztah Thanks. I'm clear now. I think you can detail when the restart policy works on the website I mentioned above, that would help a lot.
