### ISSUE TITLE
Install Docker packages for non-root users to user home

### ISSUE THREAD

**Issue by kovacsa91** [docker/docker#21351]
I have access to Grid5000 and would like to use Docker containers on it. Tutorial says, that users should install the tools in the user's home and add the user's home to the PATH environment variable. I can't find any reference about this in the docker or docker-machine manual. How can I install it without using apt-get command? My user isn't in the sudoers group.

**Comment by HackToday** [comment]
The docker related command needs some commands to access system resource, like privileged used ways  I think it need some kinds of root right, like sudo.

do you mean you want user(who not in sudo  group) to install docker , and allow user to use that docker to access system resource ?  Not quite understand your needs here

**Comment by kovacsa91** [comment]
Yes, exactly that you think!

**Comment by thaJeztah** [comment]
The docker daemon needs to run as root, so you cannot install docker if you don't have root or sudo rights. Your best option is to contact someone at Grid5000 to ask what options they have, and if they have a way to install Docker.

I'm closing this issue, because there's not much we can do here to help, but feel free to comment after I've closed
