### ISSUE TITLE
[1.11-RC1] Occasional high container startup time due to boltdb

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#21453]
TL;DR; we have occasional extremely high container startup time (over 10s), that we know for sure is spent updating the boltdb on-disk database used by libnetwork at preStartHook time.

Networking team is already investigating; This issue is for tracking this issue.

**Comment by aboch** [comment]
To clarify, this is seen in hosted jenkins automated environment (at least on a 3.13 ubuntu/aufs machine), docker-in-docker setup.

**Comment by thaJeztah** [comment]
Just discussed this with @mavenugo; apparently this issue was already present in older versions of Docker, and nobody hit it. However, it became more apparent with the containerd integration in 1.11, which uses a timeout. We're only seeing this currently in CI, so changing to P2 for now (possibly P3)

**Comment by thaJeztah** [comment]
Sorry for the confusion; I thought it was something new in 1.11 :smile:

**Comment by mavenugo** [comment]
@thaJeztah The issue description and title are very generic and it will result in being a catch-all bug for any container startup time issues. We have already seen a few instances that it was incorrectly attributed to this issue as the root-cause.

Hence, can you pls add the exact scenario / use-case that this issue is seen in the description so that it is clear for anyone looking for similar issues.

As we discussed we are using boltdb from v1.9 and we haven't seen any such issues till now. As @aboch mentioned, based on his investigation, it is currently seen in a DinD setup on a CI environment. Is that your observation as well ? If not, it would be good to mention the scenario.

**Comment by icecrime** [comment]
@mavenugo True, so far we've only saw it on CI servers. However, I did measure it outside of DinD. Until we have a full explanation, this is a potential blocker for the release.

Please let us know:

1. If you feel this is unimportant because X, Y, or Z, and we'll take it from there.
2. If you agree this is a potential blocker and are making this a priority.

I'm considering this a potential blocker. I'm not forcing you to agree, but let me know so we can plan accordingly.

**Comment by mavenugo** [comment]
@icecrime can you please share the details on the measurement that you have outside of the CI DinD environment ? That would be of great help to characterize this problem. Regarding the priority of an issue, its really upto the maintainers and I have nothing to say there. Since you have measurements, it would be good to compare the results with 1.9, 1.10 releases to make sure if this is specific to 1.11 or an existing problem with boltdb that is observed now. If it is an existing problem, then considering it a release blocker is questionable. Regardless, @aboch is working on it and he may have more data to share.

**Comment by aboch** [comment]
The issue is about boltdb write operation taking long time, up to seconds. This is seen in while running docker IT. Note that commonly these calls take 2ms, and no more than 20ms. The problem happens rarely, very randomly unrelated to the size of the data being pushed to disk or to the IT test being executed.

So far I have been able to reproduce the issue only in dind, during IT execution.
I am testing docker with latest boltdb code, logging the boltb operations which take longer than a second.

I came out with a single docker IT test which execution hits the problem 50% of the time on a AMI (ubuntu 3.13) instance equal to the ones where the jenkins jobs are executed. 
But, running the full IT is still the most reliable way to hit the issue. Although, I ran the full IT on my ubuntu 4.2 around 10 times and have never seen the problem.

As the log shows (https://github.com/docker/docker/pull/21479#issuecomment-200981674), bottleneck is always in boltdb `fdatasync` function which simply executes the `syscall.Fdatasync`.

Outside dind, I tried to reproduce the issue several times (on the jenkins AMI and my machine) replicating what the IT test does and never encountered the problem.

At this point, with the info I have and posted above, I assume this is a dind specific issue.

**Comment by benbjohnson** [comment]
Bolt author here. Let me know if I can answer any questions or help troubleshoot the issue.

**Comment by aboch** [comment]
@benbjohnson Thanks a lot for offering !

At this time I have no ground for thinking it is a boltdb issue: The slow function is in the syscall go pkg.

But if you are aware of any non-canonical way of using boltdb which could cause the library not to work properly, please let us know. 

The docker component which is currently using boltdb is https://github.com/docker/libnetwork, accessing it via a (k,v) store abstraction layer at https://github.com/docker/libkv/tree/master/store/boltdb.

Thanks again !

**Comment by benbjohnson** [comment]
@aboch I don't see anything unusual about the usage. A long `fdatasync()` syscall seems like it would point to either a file system or disk issue.

I remember I worked on an ext3 FS a while back that would hang for half an hour on an `ftruncate()` call. We never could figure out what the heck was going on.

**Comment by aboch** [comment]
Thanks @benbjohnson for confirming. That helped to exclude other areas.

We were also suspecting it might have to do with the FS. For the record, the VM where the error is seen has a virtual ext4 device: `/dev/xvda1 on / type ext4 (rw,discard)`.

**Comment by mavenugo** [comment]
@benbjohnson what is your opinion on setting the `NoSync` flag to `true` for ext3 / ext4 FS ?

**Comment by benbjohnson** [comment]
@mavenugo It's not a safe operation since pages can be reordered when written and it can corrupt your database. It's really only meant to be used when bulk loading data.

**Comment by calavera** [comment]
we got bolt 1.2 in and libnetwork v0.7.0-rc.1. Hopefully we won't see this kind of issue again. But feel free to reopen.
