### ISSUE TITLE
[Build process] Error fetching deb

### ISSUE THREAD

**Issue by icecrime** [docker/docker#21512]
We are seeing a lot of apt related failures when building Docker, especially on CI:

```
07:19:41 E: Failed to fetch http://httpredir.debian.org/debian/pool/main/p/python3-defaults/python3-minimal_3.4.2-2_amd64.deb  Error reading from server. Remote end closed connection
```

I'm opening this to explore alternatives.

- One unsatisfactory earlier attempt was to move all 3rd party dependencies to a base image (#20665).
- Should we try some of the other solutions described [here](http://httpredir.debian.org/)? They will surely be inferior in some aspects, but maybe we should optimize for reliability here.

**Comment by kencochrane** [comment]
I'm not sure it is possible (couldn't find it with a quick search), but if we could have apt-get fail over to a backup mirror (if the one from httpredir fails) that might be slower, but more reliable then that seems like the better approach. 

Another idea is to install our own apt-cacher, so that we can can cache the packages we use close to us, and limit the impact of a bad mirror. see https://help.ubuntu.com/community/Apt-Cacher-Server for more details.

**Comment by thaJeztah** [comment]
https://docs.docker.com/engine/examples/apt-cacher-ng/

**Comment by jfrazelle** [comment]
yeah so its an apt problem, we could set a different mirror or like ken and @thaJeztah said

**Comment by icecrime** [comment]
I'm thinking maybe we can use a `--build-arg` to override the Debian mirror at build-time, so that:

- Our contributors around the world could continue benefiting from geo-aware `httpredir` as the default.
- Our CI servers could use a specific mirror depending on their location (which should be pretty much all US, except ARM in France).

What do you think?

**Comment by tianon** [comment]
Seems like an OK solution here.

For the general issue, I'm thinking it might be time to switch the Debian base images off httpredir since it appears to be in some sad period of mourning (this is the third independent report I've heard of issues like this, which is more serious than the usual `Hash Sum Mismatch`).  I've got high hopes for http://deb.debian.org, but it's currently stretch-only, and isn't supported by debootstrap (yet), so we'd have to hard-code `cdn-fastly.deb.debian.org` for now, and I'm not sure how well-supported that'll stay without an official announcement that it ought to be used on debian-devel-announce. :disappointed:
