### ISSUE TITLE
[1.11-RC2] Warnings when host does not have seccomp 2.3 installed

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#21533]
On distributions that have seccomp support enabled, but don't have libseccomp 2.3 installed, docker (runc) outputs warnings when a container is started;

```
docker run -it --rm centos:7
2016/03/25 21:51:33 Error resolving syscall name copy_file_range: could not resolve name to syscall - ignoring syscall.
2016/03/25 21:51:33 Error resolving syscall name mlock2: could not resolve name to syscall - ignoring syscall.
[root@ebec24e7b0ed /]#
```

This can be fixed by either upgrading libseccomp to 2.3, disabling the default profile using

    --security-opt seccomp=unconfined

(or probably by using a custom profile that doesn't contain the `copy_file_range` or `mlock2` syscalls)

**Comment by icecrime** [comment]
Ping @justincormack: I think we may revert to 2.2.3 (and remove some of your additions to the default profile accordingly).

**Comment by crosbymichael** [comment]
This is to remove the logs but seccomp 2.3 is not being released by distros causing a mismatch for compile/runtime.

https://github.com/opencontainers/runc/pull/691

**Comment by thaJeztah** [comment]
for reference, this relates to https://github.com/docker/docker/pull/21262 and https://github.com/docker/docker/pull/21123

**Comment by justincormack** [comment]
I will look at silencing the warnings as they are harmless. Otherwise it looks like its it just `copy_file_range` and `mlock2` which need to be removed, which is fine as they are likely not used yet, I don't think there is a need for reverting the static linked version to 2.3.0 or the other changes, as that would revert various other bug fixes (which are not giving warnings as the syscall names are not new).

**Comment by justincormack** [comment]
Out of interest which distros do have seccomp enabled? The centos 7 install I just tried doesn't, and nor does my Ubuntu one. Will try Debian jessie...

**Comment by thaJeztah** [comment]
@justincormack I had this issue on Ubuntu 15.10 and Fedora 23. Fedora (in DigitalOcean) had libseccomp 2.2.3 installed (didn't check if that was installed out of the box, or as a dependency for docker). It -did- have seccomp 2.3 available, so the problem was solved after upgrading.

Ubuntu 15.10 did not have seccomp 2.3 available

**Comment by justincormack** [comment]
Should be resolved by https://github.com/opencontainers/runc/pull/691

**Comment by justincormack** [comment]
Fedora 23 is indeed fixed by an update. Ubuntu is waiting for upstream Debian to fix...

**Comment by icecrime** [comment]
There's no reason for us to upgrade to seccomp 2.3 right now, and the lack of availability on the distros we support is a problem.

@justincormack Do you mind sending us a PR to revert to seccomp 2.2.3 for 1.11.0. I don't think we strictly need to modify Docker's default profile however, as the warnings will be silenced by runC anyway.

**Comment by crosbymichael** [comment]
The 2.3 milestone on the golang binaries is still open.  We should wait until the golang binaries are up to supporting this version before upgrading and make sure it has broad distro support. 

https://github.com/seccomp/libseccomp-golang/milestones/v2.3

**Comment by justincormack** [comment]
@icecrime the upgrade is only for the static linked build, and fixes various reported bugs. It does not affect the dynamic builds, which are linked against whatever the distro has (or nothing), we are not requiring linking to 2.3.0.

The distros are doing rolling upgrades to 2.3.0, as it is ABI compatible so we will be supporting a mix of people on 2.2.x and 2.3.x anyway.

The warnings referred to in this issue turned out to be happening for some people with eg 2.2.0 with 1.10.3 in #21557 , so nothing to do with the 2.3.0 changes.

@crosbymichael none of those issues affect docker. Some distros (eg fc23) are already on libseccomp 2.3.0 so we will be supporting it regardless.

So I don't see a rationale to revert...

**Comment by crosbymichael** [comment]
@justincormack fine but you are on bug duty if anything goes bad ;)

**Comment by justincormack** [comment]
;)

**Comment by icecrime** [comment]
Works for me then ;-)

Let's close this issue as soon as we update runC in docker/docker to include opencontainers/runc#691. Thanks!

**Comment by thaJeztah** [comment]
Opened a PR to bump runC https://github.com/docker/docker/issues/21629
