### ISSUE TITLE
Better way to access the Engine API from a container

### ISSUE THREAD

**Issue by errordeveloper** [docker/docker#21622]
Wouldn't it be nice if there existed an API access shim that one could use inside of a container without bind-mounting the socket and ensuring the client binary or libraries are compatible with the daemon you it happens to be talking to?

And, of course, it'd be critical to implement flexible access-control for what API calls are allowed.

One way to consider would be something as simple as:
```shell
docker run --with-api-access-shim run <any_image> sh -c \
  "echo ps | socat - UNIX-CONNECT:/.docker.sock"
docker run --with-api-access-shim run <any_image> sh -c \
  "echo exec foo ls -la | socat - UNIX-CONNECT:/.docker.sock"
```

For those who need more, a shim shared library could be provided, with bindings for different languages.

**Comment by programmerq** [comment]
What should the shim provide that you don't already get with the bind mount?

**Comment by amouat** [comment]
The problem with the bind mount is you have to install Docker inside the container. And then you suddenly have a versioning issue...

**Comment by thaJeztah** [comment]
You'd have a versioning issue with any software that uses the API, but only if the software inside the container is trying to use a newer API version than the daemon that is running

**Comment by titpetric** [comment]
I would note that perhaps the operative feature would be to introduce the "flexible access-control for what API calls are allowed". For example, I'd like to give some access to data which I can currently get only with "docker ps" and "docker inspect" to a container (/containers/json, /containers/{name}/json).

I apologize if such a feature is already in the works or duplicate, I did my research as best I could, and what I could find out is that only some Authentication mechanism is supported via certificates/CA, but I didn't sniff out any kind of ACL.

**Comment by thaJeztah** [comment]
There are still plans to one day have an introspection API https://github.com/docker/docker/issues/8427, with more fine-grained control over access. Such an API would be a less "hacky" solution than mounting the socket.

No target date / version for that though :smile:

**Comment by titpetric** [comment]
@thaJeztah Just as a curiosity, how would such an API differ from just allowing all GET requests to the API? It would give a read-only access to the host (perhaps swarm?), and not smaller units (like, defined networks - group of containers, or single-unit - self container).

**Comment by thaJeztah** [comment]
Still has to be discussed / designed. At least it should be easily consumable, and more targeted for use inside a container

**Comment by justincormack** [comment]
The client version issue is being looked into, to work out how the client can safely talk to other versions, see https://github.com/docker/docker/issues/25498

We do have auth plugins that control access, so you can restrict what can be done, but it is not very easy to set up, so it does not get much use (not sure there is a tracking issue but it is on my list).

Access to read only data such as labels and container names is being worked on in https://github.com/docker/docker/pull/26331

@errordeveloper not sure exactly what your requirements are - this issue is very vague. It really helps if your issue explains what you want to do not what mechanism you would to implement it. There are quite a few problems with general API access, so we have postponed this for now to work on #26331 which has no security concerns but obviously lets you control less. It would be better to rewrite this or open a new issue if any of the above is not suitable for whatever you want to do. (you around tomorrow was going to catch up with Milos in the evening we could discuss...).

**Comment by errordeveloper** [comment]
@justincormack I guess I might have gone a bit too far here... the basic requirement is about being able to claim API access and not having to assume socket path. But next comes the problem of having to have right client version, which I thought could be done with some simple plain text interface, but that was just me brainstorming a little bit.

**Comment by errordeveloper** [comment]
Re-opened as https://github.com/docker/docker/issues/27261.
