### ISSUE TITLE
API PUT archive file ownership root when container running as non-root.

### ISSUE THREAD

**Issue by BenHall** [docker/docker#21651]
We're having issues using the PUT /containers/(id)/archive endpoint due to file ownership permissions. When a container is running as a non-root user, the ownership is always reset back to root after uploading the file.

```
  > docker version                                                                         
Client:                                                                                    
 Version:      1.10.0                                                                      
 API version:  1.22                                                                        
 Go version:   go1.5.3                                                                     
 Git commit:   590d5108                                                                    
 Built:        Thu Feb  4 18:36:33 2016                                                    
 OS/Arch:      linux/amd64                                                                 

Server:                                                                                    
 Version:      1.10.0                                                                      
 API version:  1.22                                                                        
 Go version:   go1.5.3                                                                     
 Git commit:   590d5108-unsupported                                                        
 Built:        Fri Feb  5 02:32:52 2016                                                    
 OS/Arch:      linux/amd64  
```

Given an image with a directory owned by a different user

```
FROM ubuntu
RUN mkdir /opt/www-data && chown www-data:www-data /opt/www-data
docker build -t secure .
```

And a tar file owned by a non-root user

```
> touch test
> tar -zcvf test.tar.gz test

> ls -lha 
-rw-r--r-- 1 non-root non-root    0 Mar 30 10:19 test  
-rw-r--r-- 1 non-root non-root  114 Mar 30 10:19 test.tar.gz
```

When you launch the container as a non-root user

```
docker run -d -u www-data --name target secure sleep 100000
```

After uploading the tar, the file ownership permissions will be reset to root. The ownership should match either the original file or the user the container is being run as. 

```
curl -s -XPUT  -T test.tar.gz docker:2345/containers/target/archive?path=/opt/www-data
docker exec -it target bash

> /opt/www-data$ ls -lha
drwxr-xr-x 1 www-data www-data 4.0K Mar 30 10:24 .
drwxr-xr-x 1 root     root     4.0K Mar 30 10:22 ..
-rw-r--r-- 1 root     root        0 Mar 30 10:19 test 
```

**Comment by BenHall** [comment]
@thaJeztah I tested on 1.11 and I have the same behaviour.

```
Server:                                                                                    
 Version:      1.11.0-dev                                                                  
 API version:  1.23                                                                        
 Go version:   go1.5.3                                                                     
 Git commit:   79edcc5                                                                     
 Built:        Sat Feb 13 00:12:47 2016                                                    
 OS/Arch:      linux/amd64                                                                 
 Experimental: true
```

**Comment by thaJeztah** [comment]
ping @estesp I think you looked into similar issues recently, care to have a look?

**Comment by maloddon** [comment]
Got the exactly same problem here

```
Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64
```

**Comment by erikh** [comment]
Does anyone mind if I attack this? Is there someone working on it now?

**Comment by thaJeztah** [comment]
@erikh please go ahead :+1:

**Comment by erikh** [comment]
so if I understand this code correctly:

https://github.com/docker/docker/blob/master/daemon/archive.go#L260-L266
https://github.com/docker/docker/blob/master/pkg/archive/archive.go#L333-L348

the uid/gid is getting set in a few situations, but it's always set to the mapped UID of root.

I would really just like a "I know what I am doing mode" that lets me unpack a tarball with all the UID mismatches I want into a container.

However, even if I wanted to do that right now, this archive implementation is too coarse I think. It modifies every header post-hoc (by way of lchown) it seems? I don't think that'll work for a tarball with varying uid/gid information.

Please advise, thanks. I'd love to do this patch.

**Comment by erikh** [comment]
Can I get pointed in the right direction? Hopefully I'm not being a problem. I just really need this bug fixed.

**Comment by BenHall** [comment]
My workaround involves base64 encoding a file and using docker exec to decode/write to the container. It seems to be working well for me, but it's only a couple of files.

**Comment by erikh** [comment]
Ugh. Thanks for the idea, though.

**Comment by thaJeztah** [comment]
ping @duglin @estesp are you able to help?

**Comment by erikh** [comment]
I'll phrase my question another way: if I added a way to directly import the UID/GID information from the tarfile, what would be the disadvantage?

**Comment by erikh** [comment]
I really don't need help writing the code, just the assistance required to know what I need to do, if this is even a possibility.

I'm sorry to be such a pest but it would be really nice to fix this after what, 3 years of it being broken now?

**Comment by thaJeztah** [comment]
@erikh looks like I missed your previous ping. Given that this would be a breaking change, I suggest to add a query-parameter on the endpoint to enable this behavior. I'm not sure which parts of the CLI use this endpoint (should look), so for those, adding a flag would probably be best.

ping @duglin @estesp let me know if you have additional thoughts!

**Comment by estesp** [comment]
@thaJeztah I was just starting to look at this 5 minutes ago..good timing :) I'm a bit confused and want to do some quick research first; last I checked files inside the tar retained their original permissions, and we have tests on this. But, in general I fully agree that something is needed in this area as we have so many different threads of discussion on the same file ownership vs. "container user" topic.

**Comment by estesp** [comment]
Interesting, so `ADD sometar.tgz /` has different codepath/behavior than the `PUT` archive support. Maybe this is the same difference between `ADD` and `COPY`.

`ADD sometar.tgz` actually preserves ownership of the original tar. Which has some valuable behavior, but conflicted with initial implementation of userns as the user assumes copied in contents will match the shifted ID space.  I think the right fix for this path is for that hardcoded uid gid (from the link provided above) to be replaced with the shifting of IDs which is used elsewhere in the archive packages.

**Comment by erikh** [comment]
Awesome, this is very useful context/instruction. I'll see if I can go the last mile and try to put a patch together this weekend!

**Comment by erikh** [comment]
So, what I'm sending is just a basic tarball of the fs I'm copying; which is fine for `CopyToContainer` except for the perms. I'll send more data as I work on this.

Thanks again!

**Comment by erikh** [comment]
oh; what should we do when no UID exists on the system for these tar files? Should we just write the UID/GID as tar typically works, or would you like me to do something else?

**Comment by erikh** [comment]
@estesp this exhibits the exact behavior I want. Can you try it out? Just any copy operation with a UID that should be preserved will work.

https://github.com/docker/docker/compare/master...erikh:fix-copy?expand=1

I am surprised it's so small, which is why I'm asking you to look/try before I spend a ton of time on tests.

**Comment by erikh** [comment]
other issue which is potentially resolved by this: https://github.com/docker/docker/issues/21651

**Comment by estesp** [comment]
@erikh: one minor tweak to your patch--it really should be passing maps to the archiver so that the user namespace enabled case works properly. My error in the initial implementation was to bluntly pass root as a "chown" option rather than passing the full maps and letting the code already in the archiver do shifting (if necessary).  Without that, this code reverts to working for the non-user namespace case, but having files unmapped when user namespaces are enabled.

So, instead of asking the daemon for the root UID and GID, you should instead ask for the maps:
```
  uidMaps, gidMaps := daemon.GetUIDGIDMaps()
```
And then pass the maps as archiver options instead of the chown options:
```
    NoOverwriteDirNonDir: noOverwriteDirNonDir,
    UIDMaps: uidMaps,
    GIDMaps: gidMaps,
```

This should handle your use case as well as handling mapping in a more refined way than the blunt "chown to (possibly remapped) root"

**Comment by erikh** [comment]
Ok I'll try that tonight. Thanks.

**Comment by erikh** [comment]
@estesp changes + an initial test: https://github.com/docker/docker/compare/master...erikh:fix-copy?expand=1

is this ready to submit?

**Comment by thaJeztah** [comment]
> is this ready to submit?

Commit message could use a bit of TLC 😇

**Comment by erikh** [comment]
can you clarify?

**Comment by thaJeztah** [comment]
Oh, ignore me, looks like GitHub didn't propagate the text field when viewing; it usually takes the commit message, but perhaps not when multiple commits

**Comment by erikh** [comment]
yeah, it just uses the branch name when multiple commits exist.

**Comment by estesp** [comment]
@erikh looks like the right solution to me!

**Comment by erikh** [comment]
awesome. I'll put the PR together after work!

**Comment by mlilback** [comment]
Why was this issued closed? This issue deals with the archive endpoint of the rest api, but the fix that was made only applies to the CLI. 

I'm working around this by using a path that the container user owns so the files can still be removed even though they are owned by root.

**Comment by thaJeztah** [comment]
@mlilback the linked PR updates both the cli and the API, but it is part of the upcoming 17.06 release

**Comment by jankeromnes** [comment]
> but it is part of the upcoming 17.06 release

Thanks a lot for pointing this out! It's always hard to know which fixes are part of which versions. Now all I need to do is wait for 17.06 to come out and stabilize...

@erikh Thanks a lot for putting in so much effort and implementing this feature!

I have a quick question on how this new feature will work with Docker Remote API (I'm not sure this is the right place to ask, if not please point me in the right direction):

In a Node.js app, I use [tar-stream](https://www.npmjs.com/package/tar-stream#packing) to create a tar stream containing a file (`authorized_keys`), which I then pass to [dockerode](https://www.npmjs.com/package/dockerode)`.`[putArchive()](https://github.com/apocas/dockerode/blob/3d0df1bf0160777d2c7bc9efc37aab12fe53b6af/lib/container.js#L830) in order to extract the file into a container's `/home/user/.ssh` directory. In this container I have a user called `user`, but I have this github issue's exact problem: the extracted `authorized_keys` file belongs to `root:root` instead of `user:user`.

How will I be able to specify the expected ownership to the Docker Remote API? Apart from adding `copyUIDGID: true` to `dockerode.putArchive()`'s options,
- Is it enough to pass `{ uname: 'user', gname: 'user' }` to tar-stream's `pack.entry()` method?
- Do I need to also specify `{ uid: ?, gid: ? }` to tar-stream, and if so, how do I know the value of `user`'s `uid` in my container?

**Comment by andreamancuso** [comment]
Yep, this is still an issue for me as well.
