### ISSUE TITLE
docker push overwrites images on server

### ISSUE THREAD

**Issue by tadasv** [docker/docker#21744]
Hi,

I'm running distribution 2.x and I was wondering if there is a way to reject image pushes with tags that already exist on the server? I want to prevent people from overwriting images with the same tag. Assuming that tagging process is not controlled.

**Comment by thaJeztah** [comment]
I think this was discussed at some point, but I can't find the issue it was discussed in :smile:

**Comment by vdemeester** [comment]
I think this issue should be in distribution repository (probably?), but ping @stevvooe @aaronlehmann for insights 👼

**Comment by stevvooe** [comment]
@tadasv As @thaJeztah said, this has been discussed, although I cannot find the original issue.

Due to how tags work in practice, I am not sure we'd introduce such a feature without finer grain access controls, such those provided in DTR and other products. One example is `latest`. If you turn off updates for `latest`, a lot of workflows may break.

That said, there might be a simple feature based on config:

```
manifests:
  noupdate:
    - v\d+.\d+.\d+
```

The above would prevent updates of tags that have a semantic version. All other tags would be allowed to be updated.

That said, please follow @vdemeester's advice and take this over to docker/distribution.

**Comment by thaJeztah** [comment]
Let's close the issue here, but feel free to open an issue for discussion in https://github.com/docker/distribution/issues
