### ISSUE TITLE
Docker does not extract images in parallel

### ISSUE THREAD

**Issue by hsingh23** [docker/docker#21814]
Feature request

Description of problem:
Docker does not extract images in parallel

`docker version`:
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

`docker info`:
Containers: 23
 Running: 0
 Paused: 0
 Stopped: 23
Images: 15
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 303
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-30-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.945 GiB
Name: something-else
ID: 37YL:PW3M:M5GE:PSQ5:TMHR:QCFI:M64D:53RJ:2LOA:CLU2:BXUR:X2RG
WARNING: No swap limit support

`uname -a`:
Linux something-else 4.2.0-30-generic #36~14.04.1-Ubuntu SMP Fri Feb 26 18:49:23 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
physical

How reproducible:
very easy

Steps to Reproduce:
1. docker run some image you dont have
2. notice the images are extracted one by one. This could be Parallelized

Actual Results:
images are extracted one by one

Expected Results:
images are extracted in parallel

Additional info:
None

**Comment by thaJeztah** [comment]
Related discussion, but about compressing (for docker push); https://github.com/docker/docker/issues/21814, and https://github.com/docker/docker/pull/17674

also adding @unclejack and @aaronlehmann

**Comment by aaronlehmann** [comment]
Thanks for the feature request. Note that not all storage drivers would be able to support parallel extraction. Some are snapshotting filesystems where the first layer must be extracted and snapshotted before the next one can be applied.

**Comment by cpuguy83** [comment]
We also don't really want a `pull` operation consuming tons of CPU on a host with running containers.

**Comment by hsingh23** [comment]
What do you think of a parallel flag to specify how many packages to
extract at once, that knows if your storage driver supports parallel
extraction?


Peace

Harsh Singh

**Comment by thaJeztah** [comment]
@hsingh23 I think it's also important to check if parallel extraction actually speeds up things? A well-optimized single extract may already make full use of the available resources. Someone should create a proof-of-concept and provide benchmarks; then again, we should really be careful with this (re: @cpuguy83's concern above) and not create something where a single `docker pull very-large-image` can lead to potential denial-of-service

**Comment by unclejack** [comment]
This isn't going to happen for technical reasons. There's no room for debate here. AUFS would support this, but most of the other storage drivers wouldn't support this. This also requires having specific code to implement at least two different code paths: one with this parallel extraction and one without it.

An image is basically something like this graph A->B->C->D and most Docker storage drivers can't handle extracting any layers which depend on layers which haven't been extracted already.

Should you want to speed up `docker pull`, you most certainly want faster storage and faster network. Go itself will contribute to performance gains once Go 1.7 is out and we start using it.

I'm going to close this right now because any gains parallel extraction for specific drivers  aren't worth the complexity for the code, the effort needed to implement it and the effort needed to maintain this in the future.

**Comment by cristipp** [comment]
Naively, "extract" implies decompressing. While one needs to mount the layers in sequential order for the reasons @unclejack mentioned, it doesn't immediately follow that the layers must be also decompressed sequentially. Would it be possible to extract in parallel, and have only the mount operation sequential?

Use case: Pulling a 5GB image on a fresh 32 core VM in the cloud [GCE / GCR] takes 3 minutes, most of them spent "extracting". There is nothing else to do until the image is pulled, so we end up with 31 cores sitting idle. Note that the "download" part is actually quite snappy.

**Comment by aaronlehmann** [comment]
I doubt it would make sense in most cases. You'd have to decompress to temporary storage, then possibly copy the decompressed files on top of the previous layer when possible. It would be a lot of extra I/O load to allow some extra concurrency on decompression.

**Comment by cristipp** [comment]
For the use-case mentioned above, "create a big VM in the cloud, pull an image, run some containerized jobs, shut down the VM", there is nothing to do until one pulls the container image. A 32 core VM comes with 120GB of RAM, plenty of room to keep decompressed layers in RAM if I/O cost is a concern.

We could at least to benchmark the latency of downloading / extracting / mounting per layer. Possibly Docker already has some instrumentation along these lines, I wonder if someone could point towards the right documentation.

**Comment by sepiroth887** [comment]
While I see the reason for this choice I would want to note that on most cloud providers and in private datacenters the network speed will likely be high enough to result in a <1:1 ratio between download and extraction. From experience we are seeing downloads for ~1.5GB images to take ~8sec to download but another 35-40sec to extract (to an SSD to boot). 

The above example btw is on a 20 core machine with 112GB of RAM. Would need to pull iostats to check on disk, but we are not using NAS for this.... 

Is this a purely CPU + disk IO bottleneck or would for example compression changes make a difference? It would be great to be able to configure a sweet spot per deployment environment to trade off between network & CPU+Disk IO  @unclejack @aaronlehmann  thoughts?  (and this is likely more a feature for the docker registry/hub now that i think about it)

**Comment by thaJeztah** [comment]
Note that the next release will use `pigz` (parallel decompression) for layers; https://github.com/moby/moby/pull/35697

**Comment by berendo** [comment]
> While I see the reason for this choice I would want to note that on most cloud providers and in private datacenters the network speed will likely be high enough to result in a <1:1 ratio between download and extraction.

I agree wholeheartedly.

In private data centers, or even in public cloud services that provide their own container repositories (e.g. Google Cloud Platform), `docker pull`s of large images can _definitely_ be decompression-limited than network-limited. Even after the migration to `pigz`, which unlike `pbzip2` _cannot_ speed up decompression much, both continuous integration and deployment flows that start with cold image caches are _severely_ hampered by initial `docker pull` completion latencies.

While I understand that the _general_ target of containerization is lightweight containers, where image sizes should naturally be on the smaller end of the spectrum, many of the benefits still carry-over to some applications that inherently have very large container sizes (i.e. not due to inclusion of "data" in containers). The image/layer decompression performance issues go quite a ways back in GitHub issue history and seem to all eventually go cold...

Right now, as things stand, the layer compression is still "hard-coded" to use the internal/`pigz` implementation which makes it difficult to inject an external compression helper (e.g. `pbzip2`) for private/custom usage so that the pull path would be _forced_ to use a different decompression (other than `pigz`). And given that layers are decompressed serially, there's no way to take advantage of parallelism at that level, either.

**Comment by sabrehagen** [comment]
I don't know about y'all, but in `Docker 18.09.0, build 4d60db4` I'm seeing:

![extraction](https://user-images.githubusercontent.com/1094600/49623138-7eea9380-fa20-11e8-8508-8f8ca4d0d43e.gif)

**Comment by brannondorsey** [comment]
Sorry to raise this from the dead, but I too am getting sequential decompression of layers on `Docker (Moby) version 3.0.10+azure` on AKS. The host has `pigz` (and therefore `unpigz`) installed. What am I missing? Is there no way to extract downloaded layers in parallel?

**Comment by brannondorsey** [comment]
It seems like perhaps this is the reason: https://github.com/moby/moby/issues/37957#issuecomment-427550062

**Comment by cpuguy83** [comment]
Layers must be extracted in order.
It seems like it would be technically feasible to make the download manager smarter and know that it can extract certain layers while others are downloading... but it does not do this now.

I do not think we will be changing this any time soon.
If you want to improve this, I'd suggest working on it in containerd as we will be moving to containerd in the next major release (after the one we are just about to kick off).

**Comment by brannondorsey** [comment]
Sounds good, thanks for the quick response. Do you have any insight into whether this functionality is already supported in containerd or if it would require a contribution?

**Comment by cpuguy83** [comment]
It's definitely not supported today... and as I recall may actually worse than Docker is today in terms of parallelism across a pull.
