### ISSUE TITLE
Why docker volume driver create a default volume if volume does not exist?

### ISSUE THREAD

**Issue by jay-lau** [docker/docker#21829]
**Output of `docker version`:**
```
root@devstack007:~# docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64
 
Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@devstack007:~# docker info
Containers: 1
Images: 171
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 176
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 4
Total Memory: 3.743 GiB
Name: devstack007
ID: ML2V:ASNA:E7TH:QLKO:5ZEB:TF2Y:Q2O5:J4LW:EQ6X:ZTY2:7VIJ:XNPA
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. No Volume
root@devstack007:/home/gyliu# docker volume ls
DRIVER              VOLUME NAME
2. Create a container with a non-exist volume abc
root@devstack007:/home/gyliu# docker run -it -v abc:/tmp ubuntu:14.04 /bin/bash
root@9e09399b3627:/# 
3. Check volume again
root@devstack007:~# docker volume ls
DRIVER              VOLUME NAME
local               abc
root@devstack007:~# docker volume inspect abc
[
    {
        "Name": "abc",
        "Driver": "local",
        "Mountpoint": "/var/lib/docker/volumes/abc/_data"
    }
]

**Describe your question:**
My question is why does docker create a volume by default? What is the volume size of the default volume? How to handle the case if the create by default volume does not fit into customer docker volume requirement? 

Another question is that I saw that no one is cleaning up the volumes, so there will be some garbage volume left on the host, who will help clean them?

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
Looks like a duplicate of https://github.com/docker/docker/issues/16068, or at least closely related

>  What is the volume size of the default volume?

Volumes created through the default ("local") volume driver don't have a size limit; they're basically just directories created inside `/var/lib/docker/volumes`. If you want to put a size constraint on volumes, you need to use a volume-plugin that supports this. Some plugins can be [found in the documentation](https://docs.docker.com/engine/extend/plugins/#finding-a-plugin)

> Another question is that I saw that no one is cleaning up the volumes, so there will be some garbage volume left on the host, who will help clean them?

That is by design; volumes are designed to persist data, independent of the lifecycle of a container. For example, you store your database-data inside a volume, so that you can replace a container (stop it, and remove it), without loosing your data.

As of docker 1.9, docker has volume management functions (`docker volume ls`, `docker volume create`, `docker volume rm`) to manage volumes, and clean them up when they're no longer needed.

Docker cannot make that decision for you, as it doesn't know when your data is no longer needed.

**Comment by jay-lau** [comment]
Thanks @thaJeztah , but the problem is that if I was using a volume driver when run a docker container, if the volume does not exist, docker will also help to create a volume based on the volume driver for me, so what is the size of such kind of volumes with a driver? It would be great if you can show me the code for creating volume by default in docker.

**Comment by cpuguy83** [comment]
@jay-lau There is no "size", it's just whatever the specified driver provides by default (with no opts).
I agree I don't (generally) like the behavior, however it really needs to stay as is for compatibility reasons.

**Comment by jay-lau** [comment]
OK, I see. thanks @cpuguy83
