### ISSUE TITLE
Support for Git's Large File Storage?

### ISSUE THREAD

**Issue by rafaelsoaresbr** [docker/docker#21862]
Will the Docker Hub have support for git-lfs?
So we can create automated builds without worrying about the repository size (cache history).

**Comment by thaJeztah** [comment]
Hi @rafaelsoaresbr thanks for the suggestion; can you open this issue in the https://github.com/docker/hub-feedback/ issue tracker? This issue tracker is only for Docker itself, and Docker Hub is a different team, so nothing we can do about that here :smile:  You can also open a ticket through support@docker.com

I'll close this issue here, but feel free to comment here after I've closed (nice idea btw)

**Comment by rafaelsoaresbr** [comment]
Thanks for your quick reply! It looks like someone already requested this o(5 Dec 2015)
https://github.com/docker/hub-feedback/issues/500
