### ISSUE TITLE
[BUG]build image faild:Untar re-exec error: exit status 1: output: operation not supported

### ISSUE THREAD

**Issue by vklonghml** [docker/docker#22192]
**Output of `docker version`:**

```
(paste your output here)
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

**Steps to reproduce the issue:**

i want to build an ubuntu image(download from ubuntu website, version=15.04.img), using scratch method,
1.the content of Dockerfile is below:

```
FROM scratch
ADD . /
RUN mkdir /var/run/sshd
RUN rm Dockerfile
CMD [\"/usr/sbin/sshd\", \"-D\"]
```

2.execute command: `docker build -t ubuntu-15.04.0203 .`
3.then failed

**Describe the results you received:**

```
Step 1 : FROM scratch
 ---> 
Step 2 : ADD . /
Untar re-exec error: exit status 1: output: operation not supported
```

**Additional information you deem important (e.g. issue happens only occasionally):**

this problem like #14792, but not the same, he solved his problem by updating the docker version, however, my docker version is up to date. Beside, i can succeed finish the above procedure when i use ubuntu-14.04.img, does anybody know how to fix this problem, thanks.

@thaJeztah， @arthurlogilab

**Comment by vklonghml** [comment]
i found a solution for the above problem, when i mount the ubuntu15.04 qcow2 image file on a directory, if i directly build with the above Dockerfile under the  mounted directory, it failed with the above error, if i remove the bin directory, it will succeed.

**Comment by vklonghml** [comment]
i don't know if it is a bug or something, does anybody knows that?

**Comment by thaJeztah** [comment]
Is there a specific reason you're trying to build for own Ubuntu image, instead of using the official `ubuntu:15.04` image? Note that you probably have to do more than just adding that image, to get a functional image. See this repository, which is used to create the official images; https://github.com/tianon/docker-brew-ubuntu-core/blob/master/update.sh

**Comment by vklonghml** [comment]
@thaJeztah yes, i just want to keep the docker image directories as the same as the ubuntu image. I will check the procedures of creating a official image, thank you.

**Comment by thaJeztah** [comment]
@vklonghml I really recommend using the official images instead of trying to build your own Ubuntu base image. The official images are always kept up to date, so you don't have to maintain them yourself (but be aware that Ubuntu 15.04 is EOL, and will not get any updates from Ubuntu). So simply 

```
FROM ubuntu:15.04
....
```

Also note that if you use a `.dockerignore` file, you don't have to remove the Dockerfile inside your image (if you add it to the ignore-list).

If you're looking for a simple example to build an SSH image, have a look here; https://docs.docker.com/engine/examples/running_ssh_service/

**Comment by vklonghml** [comment]
@thaJeztah ok, thanks a lot.
