### ISSUE TITLE
Can't access docker images after reboot

### ISSUE THREAD

**Issue by onlineworld69** [docker/docker#22212]
I am using Ubuntu 15.10 as a server. I was very happy to access my docker images I installed via the web. However, after I reboot, I can't access them all. I reinstalled docker with the images and it happened again. I also tried to create an isolated_nw in [docker guide](https://docs.docker.com/engine/userguide/networking/dockernetworks/) and many other ways but can't make it work yet. Please help!

**Comment by thaJeztah** [comment]
please keep in mind that the GitHub issue tracker is not a general support forum, but for reporting bugs and reviewing PR's.

Since this is a support question for working with Docker, can you ask this question on;

- forums.docker.com
- in the #docker IRC channel
- on StackOverflow

But when asking, please provide some more information (e.g. What version of docker are you using? Are your containers running? (what does `docker ps` show?).

I'll close this issue because of the above, but feel free to comment after I closed

**Comment by onlineworld69** [comment]
I am sorry and thanks for making it clear to me.
