### ISSUE TITLE
Relative symlinks don't work with --device argument

### ISSUE THREAD

**Issue by ulope** [docker/docker#22271]
Support for `--device` following (absolute) symlinks was added in #20684 (fix for issue #13840)

However this doesn't work if the symlink's target is a relative path. Since udev (one of the main reasons for this feature IMO) only generates relative path symlinks this isn't very usable currently.

The problem is that https://github.com/yongtang/docker/blob/master/daemon/container_operations_unix.go#L314 blindly assumes that the symlink target is absolute.

Example:

```
$ ls -l /dev/ttyACM1
crw-rw---- 1 root dialout 166, 1 Apr 23 15:37 /dev/ttyACM1

$ ls -l /dev/somealias
lrwxrwxrwx 1 root root 7 Apr 23 15:37 /dev/somealias -> ttyACM1

$ docker run --rm -it --device /dev/somealias:/dev/something alpine /bin/bash
docker: Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device "/dev/somealias": lstat ttyACM1: no such file or directory.
```

**Comment by yongtang** [comment]
Thanks @ulope for finding this issue. I will create a fix shortly. #dibs

**Comment by yongtang** [comment]
@ulope @thaJeztah @timthelion Just created a pull request @22272 by replacing `os.Readlink` with `filepath.EvalSymlinks()`. Let me know if there are any issues.

**Comment by icecrime** [comment]
This is a P3 and won't be fixed in 1.11.1.

**Comment by asantos82** [comment]
Hi,
I have the same issue in 1.11.2. Waiting for the 1.12.0 for the fix

BR, André

**Comment by thaJeztah** [comment]
@asantos82 release candidates for 1.12 are available, so would be great if you could test if it resolves the issue for you

**Comment by asantos82** [comment]
Hi @thaJeztah I havte tested the `Docker version 1.12.0-rc3, build 91e29e8` and the relative symbolic links work OK. When starting docker I no longer get the message 

`docker: Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device "/dev/somealias": lstat device: no such file or directory.`

But i do not think that it is working 100% :(

When I pass the physical address of the device to the container and test udev rule inside container I get no error
`docker run -it -P --device=/dev/bus/usb/002/006:/dev/bus/usb/002/006 --link db_odoo:db_odoo --security-opt seccomp:unconfined bc1d868ce3c6 /bin/bash`

`root@b23bdfbacd42:/home/odoo/odoo#  udevadm test $(udevadm info -q path -n /dev/bus/usb/002/006) 2>&1`

```
<OUTPUT OMMITED>
read rules file: /etc/udev/rules.d/99-usb.rules
rules contain 24576 bytes tokens (2048 * 12 bytes), 11265 bytes strings
1833 strings (21771 bytes), 1202 de-duplicated (11138 bytes), 632 trie nodes used
IMPORT builtin 'usb_id' /lib/udev/rules.d/50-udev-default.rules:9
IMPORT builtin 'hwdb' /lib/udev/rules.d/50-udev-default.rules:9
MODE 0664 /lib/udev/rules.d/50-udev-default.rules:41
GROUP 1001 /etc/udev/rules.d/99-usb.rules:1
MODE 0660 /etc/udev/rules.d/99-usb.rules:1
GROUP 1001 /etc/udev/rules.d/99-usb.rules:2
MODE 0660 /etc/udev/rules.d/99-usb.rules:2
handling device node '/dev/bus/usb/002/006', devnum=c189:133, mode=0660, uid=0, gid=1001
set permissions /dev/bus/usb/002/006, 020660, uid=0, gid=1001
creating symlink '/dev/char/189:133' to '../bus/usb/002/006'
ACTION=add
BUSNUM=002
DEVNAME=/dev/bus/usb/002/006
DEVNUM=006
DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1
DEVTYPE=usb_device
DRIVER=usb
ID_BUS=usb
ID_MODEL=TM-T70
ID_MODEL_ENC=TM-T70
ID_MODEL_FROM_DATABASE=Receipt Printer M129C/TM-T70
ID_MODEL_ID=0202
ID_REVISION=0100
ID_SERIAL=EPSON_TM-T70_JECF153434
ID_SERIAL_SHORT=JECF153434
ID_USB_INTERFACES=:ffff02:
ID_VENDOR=EPSON
ID_VENDOR_ENC=EPSON
ID_VENDOR_FROM_DATABASE=Seiko Epson Corp.
ID_VENDOR_ID=04b8
MAJOR=189
MINOR=133
PRODUCT=4b8/202/100
SUBSYSTEM=usb
TYPE=0/0/0
USEC_INITIALIZED=6145890027
unload module index
Unloaded link configuration context.
```

But when I start the container with relative symbolic link to the dev, i get a error while testing udev rule stating that `can not stat() node '/dev/bus/usb/002/006' (No such file or directory)`

Below is the output:

`root@d36eded8453d:/home/odoo/odoo# udevadm test $(udevadm info -q path -n /dev/my_tmt70) 2>&1`

```
<OUTPUT OMMITED>
read rules file: /etc/udev/rules.d/99-usb.rules
rules contain 24576 bytes tokens (2048 * 12 bytes), 11265 bytes strings
1833 strings (21771 bytes), 1202 de-duplicated (11138 bytes), 632 trie nodes used
IMPORT builtin 'usb_id' /lib/udev/rules.d/50-udev-default.rules:9
IMPORT builtin 'hwdb' /lib/udev/rules.d/50-udev-default.rules:9
MODE 0664 /lib/udev/rules.d/50-udev-default.rules:41
GROUP 1001 /etc/udev/rules.d/99-usb.rules:1
MODE 0660 /etc/udev/rules.d/99-usb.rules:1
GROUP 1001 /etc/udev/rules.d/99-usb.rules:2
MODE 0660 /etc/udev/rules.d/99-usb.rules:2
handling device node '/dev/bus/usb/002/006', devnum=c189:133, mode=0660, uid=0, gid=1001
can not stat() node '/dev/bus/usb/002/006' (No such file or directory)
ACTION=add
BUSNUM=002
DEVNAME=/dev/bus/usb/002/006
DEVNUM=006
DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1
DEVTYPE=usb_device
DRIVER=usb
ID_BUS=usb
ID_MODEL=TM-T70
ID_MODEL_ENC=TM-T70
ID_MODEL_FROM_DATABASE=Receipt Printer M129C/TM-T70
ID_MODEL_ID=0202
ID_REVISION=0100
ID_SERIAL=EPSON_TM-T70_JECF153434
ID_SERIAL_SHORT=JECF153434
ID_USB_INTERFACES=:ffff02:
ID_VENDOR=EPSON
ID_VENDOR_ENC=EPSON
ID_VENDOR_FROM_DATABASE=Seiko Epson Corp.
ID_VENDOR_ID=04b8
MAJOR=189
MINOR=133
PRODUCT=4b8/202/100
SUBSYSTEM=usb
TYPE=0/0/0
USEC_INITIALIZED=6312704343
unload module index
Unloaded link configuration context.
```

**Comment by polarathene** [comment]
@thaJeztah I've also run into an issue, not sure how to confirm if it's related to Docker or the container/image running openHAB. I've used a udev rule to map a usb device to a symlink I want to use in the container, `Docker 1.12.0` now allows this instead of throwing an error as 1.11 did, however the symlink is not working correctly.

openSUSE Tumbleweed host with OBS repo [described here](https://docs.docker.com/engine/installation/linux/SUSE/) to use the latest Docker(`Docker version 1.12.0-dev, build d6d02f6` at present).

---

###udev rule: 

```
SUBSYSTEM=="tty", ACTION=="add", ATTRS{idVendor}=="0658", ATTRS{idProduct}=="0200", SYMLINK+="zwave"
```
---

###Startup and `ls -l /dev`
Container was created with `docker run` adding two devices, ideal situation is `/dev/zwave` only:

```
--device=/dev/ttyACM0 \
--device=/dev/zwave \
```

**host:**

```
ls -l /dev

crw-rw---- 1 root    dialout 166,   0 Jul 26 14:22 ttyACM0
lrwxrwxrwx 1 root    root           7 Jul 26 14:22 zwave -> ttyACM0
```

**[openHAB official docker image](https://github.com/openhab/openhab-docker):**

```
ls -l /dev

crw-rw---- 1 root dialout2 166,   0 Jul 26 17:43 ttyACM0
crw-rw---- 1 root dialout2 166,   0 Jul 26 17:39 zwave
```
---

You can see that it's appearing as the symlinked device, the `dialout2` group is ok as they both map to the same GID, the docker image supports the varying GID for hosts for Serial devices.

I am able to access the device just fine through the software when specifying `/dev/ttyACM0` as the serial device, when using `/dev/zwave` instead however I receive: `Serial Error: Port /dev/zwave does not exist`.

**Comment by polarathene** [comment]
I've yet to continue looking into this but I was able to get the device passed through using the udev rule with alpine/eudev-dev and node-red. So it's potentially an issue with the Java app openHAB or the debian/packages it's docker image is based on.

**Comment by swapnilnshelar** [comment]
I am still facing the above issue while using symlink with --device argument.

Docker version 17.04.0-ce, build 4845c56

This is how i launch the container.
sudo docker run -t -i   -h qvs-02 -v ~/qvs_data:/root/qvs_data --device=/dev/tegra2 qvs-docker:5000/qvs:1510_v904

This is how my udev rule is set on Ubuntu 12.04 LTS host.
SUBSYSTEM=="usb", ATTRS{idVendor}=="0955", ATTRS{idProduct}=="b43d", ATTRS{serial}=="0332516040229", SYMLINK+="tegra2"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0955", ATTRS{idProduct}=="7721",  ATTR{product}=="APX", ATTR{busnum}=="1", SYMLINK+="tegra2"

Symbolic link on host.
 ls -l /dev/tegra2
lrwxrwxrwx 1 root root 15 Jun  7 01:30 /dev/tegra2 -> bus/usb/002/017

Inside container i can see it, but it is not working.
root@qvs-02:/# ls -l /dev/tegra2
crw-rw-rw- 1 root audio 189, 144 Jun  7 01:44 /dev/tegra2

crw-rw-rw- 1 root audio 189, 144 Jun  7 01:44 /dev/tegra2
root@qvs-02:/# ^C
(failed reverse-i-search)`ude': ^C
root@qvs-02:/#  udevadm test $(udevadm info -q path -n /dev/tegra2)
calling: test
version 225
This program is for debugging only, it does not run any program
specified by a RUN key. It may show incorrect results, because
some values may be different, or not available at a simulation run.

=== trie on-disk ===
tool version:          225
file size:         6656240 bytes
header size             80 bytes
strings            1714624 bytes
nodes              4941536 bytes
Load module index
timestamp of '/etc/systemd/network' changed
timestamp of '/lib/systemd/network' changed
Parsed configuration file /lib/systemd/network/99-default.link
Parsed configuration file /lib/systemd/network/90-mac-for-usb.link
Created link configuration context.
timestamp of '/etc/udev/rules.d' changed
timestamp of '/lib/udev/rules.d' changed
Reading rules file: /lib/udev/rules.d/40-gnupg.rules
Reading rules file: /lib/udev/rules.d/40-vm-hotadd.rules
Reading rules file: /lib/udev/rules.d/50-bluetooth-hci-auto-poweron.rules
Reading rules file: /lib/udev/rules.d/50-firmware.rules
Reading rules file: /lib/udev/rules.d/50-udev-default.rules
Reading rules file: /lib/udev/rules.d/55-dm.rules
Reading rules file: /lib/udev/rules.d/60-block.rules
Reading rules file: /lib/udev/rules.d/60-cdrom_id.rules
Reading rules file: /lib/udev/rules.d/60-drm.rules
Reading rules file: /lib/udev/rules.d/60-evdev.rules
Reading rules file: /lib/udev/rules.d/60-persistent-alsa.rules
Reading rules file: /lib/udev/rules.d/60-persistent-input.rules
Reading rules file: /lib/udev/rules.d/60-persistent-storage-dm.rules
Reading rules file: /lib/udev/rules.d/60-persistent-storage-tape.rules
Reading rules file: /lib/udev/rules.d/60-persistent-storage.rules
Reading rules file: /lib/udev/rules.d/60-persistent-v4l.rules
Reading rules file: /lib/udev/rules.d/60-serial.rules
Reading rules file: /lib/udev/rules.d/61-persistent-storage-android.rules
Reading rules file: /lib/udev/rules.d/64-btrfs.rules
Reading rules file: /lib/udev/rules.d/70-mouse.rules
Reading rules file: /lib/udev/rules.d/70-power-switch.rules
Reading rules file: /lib/udev/rules.d/70-uaccess.rules
Reading rules file: /lib/udev/rules.d/71-power-switch-proliant.rules
Reading rules file: /lib/udev/rules.d/71-seat.rules
Reading rules file: /lib/udev/rules.d/73-idrac.rules
Reading rules file: /lib/udev/rules.d/73-seat-late.rules
Reading rules file: /lib/udev/rules.d/75-net-description.rules
Reading rules file: /lib/udev/rules.d/75-probe_mtd.rules
Reading rules file: /lib/udev/rules.d/78-graphics-card.rules
Reading rules file: /lib/udev/rules.d/78-sound-card.rules
Reading rules file: /lib/udev/rules.d/80-debian-compat.rules
Reading rules file: /lib/udev/rules.d/80-drivers.rules
Reading rules file: /lib/udev/rules.d/80-net-setup-link.rules
Reading rules file: /lib/udev/rules.d/80-networking.rules
Reading rules file: /lib/udev/rules.d/97-hid2hci.rules
Reading rules file: /lib/udev/rules.d/99-systemd.rules
rules contain 24576 bytes tokens (2048 * 12 bytes), 11056 bytes strings
1724 strings (20833 bytes), 1126 de-duplicated (10376 bytes), 599 trie nodes used
value '[dmi/id]sys_vendor' is 'Hewlett-Packard'
value '[dmi/id]sys_vendor' is 'Hewlett-Packard'
IMPORT builtin 'usb_id' /lib/udev/rules.d/50-udev-default.rules:13
IMPORT builtin 'hwdb' /lib/udev/rules.d/50-udev-default.rules:13
MODE 0664 /lib/udev/rules.d/50-udev-default.rules:41
handling device node '/dev/bus/usb/002/017', devnum=c189:144, mode=0664, uid=0, gid=0
**can not stat() node '/dev/bus/usb/002/017' (No such file or directory)**
created db file '/run/udev/data/c189:144' for '/devices/pci0000:00/0000:00:1d.7/usb2/2-2'
ACTION=add
BUSNUM=002
DEVNAME=/dev/bus/usb/002/017
DEVNUM=017
DEVPATH=/devices/pci0000:00/0000:00:1d.7/usb2/2-2
DEVTYPE=usb_device
DRIVER=usb
ID_BUS=usb
ID_MODEL=Tegra_Device
ID_MODEL_ENC=Tegra\x20Device
ID_MODEL_ID=b43d
ID_REVISION=ffff
ID_SERIAL=NVIDIA_gr8rFiV8US03C03C00_Tegra_Device_0332516040229
ID_SERIAL_SHORT=0332516040229
ID_USB_INTERFACES=:ffff00:ff4201:
ID_VENDOR=NVIDIA_gr8rFiV8US03C03C00
ID_VENDOR_ENC=NVIDIA\x20\x20\x20\x20gr8rFiV8US03C03C00
ID_VENDOR_FROM_DATABASE=NVidia Corp.
ID_VENDOR_ID=0955
MAJOR=189
MINOR=144
PRODUCT=955/b43d/ffff
SUBSYSTEM=usb
TYPE=0/0/0
USEC_INITIALIZED=11797401527
Unload module index
Unloaded link configuration context.
root@qvs-02:/#


Let me how to fix this issue, if it is already taken care in code.

**Comment by timthelion** [comment]
You have to install the proprietary so's from nvidia inside the 
container for nvidia stuff to work.

**Comment by swapnilnshelar** [comment]
Okay, but then how it works in the case when i pass the actual device to container instead of symlink, can you help answer this please.

**Comment by timthelion** [comment]
Did you bind the actual device to a new name, or did you leave it under 
the /dev/usb/... path?

**Comment by swapnilnshelar** [comment]
With below way if i start the container it works, but then if a android device is reboot the enumeration will change, so i way trying with symlink(--device=/dev/tegra2).

--device=/dev/bus/usb/002/017

**Comment by timthelion** [comment]
Does this work: --device=/dev/bus/usb/002/017:/dev/tegra2 ?

Using the symlink won't help. In case the device changes, AFAIK, you 
have no hope what-so-ever and you must use something other than Docker: 
https://github.com/moby/moby/issues/10637

**Comment by swapnilnshelar** [comment]
If we reboot the device or put into recovery or factory mode for flashing it will enumeration will change 
/dev/bus/usb/002/017 to /dev/bus/usb/002/018 something like this, so i was thinking to use symlink to over come this issue.
But as you said it wont be possible at this point of time with docker :(, any idea of getting this support added to docker in near future, any timeline.

thanks for your help.

**Comment by timthelion** [comment]
I'd love to know myself. It is one key feature for my project, 
subuser.org , which is missing.

One thing to know, however, is that the path to a device is IRELEVANT, 
what is important is the major/minor numbers. In order for a device to 
be used in a contaienr it must be

1) mknoded

2) cgroup allowed

3) (maybe) selinux allowed

4) (maybe) apparmour allowed

You can do all of these things manually if you want.
