### ISSUE TITLE
Containers stuck in "Removal In Progress"

### ISSUE THREAD

**Issue by csdbrcm** [docker/docker#22312]
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**
```
 docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 627
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 598
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-77-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.63 GiB
Name: rodan
ID: DXQA:RAVJ:ISZ4:JWKG:A4MO:2H73:D5A2:GQGZ:XTLO:WNAS:656L:2DFH
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical Dell Optiplex workstation.

**Steps to reproduce the issue:**
A couple of my containers are stuck in "Removal In Progress" state. Rebooting didn't help. Upgrading docker to 1.11 (it was 1.10 when the problem first happened) didn't help either.

**Describe the results you received:**
```
root@rodan:~# docker ps -a
CONTAINER ID        IMAGE                  COMMAND               CREATED             STATUS                PORTS               NAMES
1c33105ff0c9        csd/yocto_imx6-dev     "/usr/sbin/sshd -D"   9 days ago          Removal In Progress                       yocto_imx6-yimx2
d3102b431840        csd/yocto_x86_64-dev   "/usr/sbin/sshd -D"   5 weeks ago         Removal In Progress                       yocto_x86_64-yo2
root@rodan:~# docker rm 1c33105ff0c9 d3102b431840
1c33105ff0c9
d3102b431840
root@rodan:~# docker ps -a
CONTAINER ID        IMAGE                  COMMAND               CREATED             STATUS                PORTS               NAMES
1c33105ff0c9        csd/yocto_imx6-dev     "/usr/sbin/sshd -D"   9 days ago          Removal In Progress                       yocto_imx6-yimx2
d3102b431840        csd/yocto_x86_64-dev   "/usr/sbin/sshd -D"   5 weeks ago         Removal In Progress                       yocto_x86_64-yo2
root@rodan:~# docker rm --force 1c33105ff0c9 d3102b431840
1c33105ff0c9
d3102b431840
root@rodan:~# docker ps -a
CONTAINER ID        IMAGE                  COMMAND               CREATED             STATUS                PORTS               NAMES
1c33105ff0c9        csd/yocto_imx6-dev     "/usr/sbin/sshd -D"   9 days ago          Removal In Progress                       yocto_imx6-yimx2
d3102b431840        csd/yocto_x86_64-dev   "/usr/sbin/sshd -D"   5 weeks ago         Removal In Progress                       yocto_x86_64-yo2
root@rodan:~# sleep 10m;docker ps -a
CONTAINER ID        IMAGE                  COMMAND               CREATED             STATUS                PORTS               NAMES
1c33105ff0c9        csd/yocto_imx6-dev     "/usr/sbin/sshd -D"   9 days ago          Removal In Progress                       yocto_imx6-yimx2
d3102b431840        csd/yocto_x86_64-dev   "/usr/sbin/sshd -D"   5 weeks ago         Removal In Progress                       yocto_x86_64-yo2
```

The only thing I can attribute this behaviour to is that this machine was rebooted while the containers were running, and after the reboot I could not clean them up. But a number of other containers were running at the time that did get cleaned up properly, only these 2 didn't.

**Comment by mlaventure** [comment]
I opened a PR to fix what I think was the cause of this state.

In between your only solution until the next release would be to remove `/var/lib/docker` entirely or to manually edit the affected containers `config.v2.json` files (in `/var/lib/docker/containers/<containerd-id>/`) to set the `RemovalInProgress` to `false (**shutdown the daemon first to be safe**). Once updated, just restart the daemon and it should let you delete them.

**Comment by philwinder** [comment]
Manually deleting the container folder worked for me. See https://github.com/docker/docker/issues/10589#issuecomment-222468296.
Thanks @mlaventure!

**Comment by lukosan** [comment]
Hello, not sure if this is a related issue of requires a new bug report but we're experiencing an inability to stop or remove a running container.

```
# docker rm -f fe3972f6adfd
Error response from daemon: removal of container fe3972f6adfd is already in progress
# cat /var/lib/docker/containers/fe3972f6adfd3b5080c3f4650f9a77200134fb3e3e5435704a9517dede001079/config.v2.json
{"StreamConfig":{},"State":{"Running":true,"Paused":false,"Restarting":false,"OOMKilled":false,"RemovalInProgress":false,"Dead":false,"Pid":4548,"ExitCode":0,"Error":"","StartedAt":"2017-08-17T15:58:09.170073517Z","FinishedAt":"0001-01-01T00:00:00Z","Health":null},"ID":"fe3972f6adfd3b5080c3f4650f9a77200134fb3e3e5435704a9517dede001079","Created":"2017-08-17T15:58:07.223997642Z" ... <snip/>
```

As you can see the daemon reports that removal of the container is already in progress but the `RemovalInProgress` flag is set to `false` in the config.

```
# docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by karanp24** [comment]
I am facing this same issue in docker 17.09-ce , when I manually try to remove the container i get the folllowing error
Error response from daemon: unable to remove filesystem for 872a4f65532abd823760e8bdce43c614bc171570b8d6cf3264c3deb274cf01b5: remove /var/lib/docker/containers/872a4f65532abd823760e8bdce43c614bc171570b8d6cf3264c3deb274cf01b5/shm: device or resource busy
If the daemon is restarted then these exited/Removal In Progress containers disappear.As this is my production system I cant take chance of restarting daemon again and again. Any suggestions how can we overcome this behavior.

**Comment by pineking** [comment]
@karanp24 do you solve this problem?

**Comment by AaronDMarasco-VSI** [comment]
I just removed 9 that were stuck for 12 hours to 2 days with `docker ps -a | grep Removal | cut -f1 -d' ' | xargs -rt docker rm` - not the best / most robust, but they all went away without complaint this time. See also https://github.com/docker/for-linux/issues/124

**Comment by thaJeztah** [comment]
Older versions of docker (when using `docker rm -f`) would remove the container from the "store", even if docker failed to remove the container's filesystem. As a result, those containers (well, their rootfs) were orphaned, leaving no way to re-try removing them.

If you were able to remove the container at a later stage, it's possible the initial `docker rm` failed (e.g. due to mounts being in use by another process), but that problem resolved itself (the other process stopped using the mount), and removal now succeeded.

Removing such containers will automatically be re-tried when restarting the daemon, but manually cleaning up shouldn't be an issue 👍

**Comment by leonardobsjr** [comment]
Docker version 17.09.1-ce, build 19e2cf6, still having this problem. Is there any reliable way to remove them? @AaronDMarasco-VSI one-liner didn't solve it.

**Comment by ericyan** [comment]
@leonardobsjr We have to deal with this issue on a monthly basis (running `17.12.0-ce` here). Deleting container files manually works for us. The procedure is something like this:

```
sudo systemctl stop docker
sudo rm -rf /var/lib/docker/containers/<CONTAINER_ID>
sudo systemctl start docker
```

We are still looking for a fix more permanent than this workaround though.

**Comment by leonardobsjr** [comment]
@ericyan My problem with this kind of solution is having to stop the service. It's a PITA to restart all the containers for a single one.

**Comment by zcalusic** [comment]
Docker 17.12 still the same bug. Don't understand how it is closed, when obviously there are still issues?!

Tnx @ericyan for instructions on how to get rid of the container. Although, in my case I also had to add `umount /var/lib/docker/overlay2/<LONG ID>/merged` before rm -rf. After that, and restarting docker engine, the container is in "Dead" state instead of "Removal in Progress" and then i could `docker rm -f <ID>` and finally get rid of it.

Nasty bug...

**Comment by rebel24** [comment]
Also getting the same problem. I can't afford to restart all docker containers all the time to sort this... :/ Exactly the same problem i'm getting from @zcalusic

**Comment by zcalusic** [comment]
I've since downgraded all Docker engines to 17.03.2 in hope that this older version of Docker will have less bugs. And especially not this one, as it's really grave. 17.03 is recommended for Kubernetes deployments anyway, and after experiencing this (closed?) bug, I felt it was the right thing to do.

Maybe there's a reason why Kubernetes hasn't tested/approved any higher version of Docker?

**Comment by mlaventure** [comment]
Locking this issue. The root cause you guys are seeing is probably different than the original on. It's hard for maintainers to keep track of what is what when old issues are used that way.

For those affected, please open a new issue with the required details. If you have a way to reproduce it, it'd be most helpful to try and figure out what is going on. Just saying that you are also affected doesn't help if we can't figure out how you reached that state. If you can run the daemon in debug mode and provide the logs once the error occurs it may be extra help.

Feel free to ping me on the new created issue (and please reference that one for others to find it so we don't end up with duplicates issue). I'll try to find some time to look at it, but since it's not my main job anymore I can't warranty when, others maintainers may do so once they see a new issue (we often miss old issues especially if they are closed).
