### ISSUE TITLE
Remove `docker/` prefix from log messages tag

### ISSUE THREAD

**Issue by sempasha** [docker/docker#22358]
When I specify [logger tag](https://docs.docker.com/engine/admin/logging/log_tags/) for application running in docker container, I expect all messages of application will have exact same tag, but actually every message tag prefixed with `docker/`. And there is no way to remove this prefix from tag.

Launch application
```
docker run -d --log-driver=syslog --log-opt syslog-address=udp://172.16.155.205:514 --log-opt tag="hello-world" hello-world
```

Expected log messages
```
...
Apr 27 09:10:55 example.com hello-world[755]: Hello from Docker.
Apr 27 09:10:55 example.com hello-world[755]: This message shows that your installation appears to be working correctly.
Apr 27 09:10:55 example.com hello-world[755]: 
Apr 27 09:10:55 example.com hello-world[755]: To generate this message, Docker took the following steps:
...
```

Actual log messages
```
...
Apr 27 09:10:55 example.com docker/hello-world[755]: Hello from Docker.
Apr 27 09:10:55 example.com docker/hello-world[755]: This message shows that your installation appears to be working correctly.
Apr 27 09:10:55 example.com docker/hello-world[755]: 
Apr 27 09:10:55 example.com docker/hello-world[755]: To generate this message, Docker took the following steps:
...
```

**Comment by yongtang** [comment]
The prefix of `docker/` is located in:
https://github.com/docker/docker/blob/v1.11.0/daemon/logger/syslog/syslog.go#L102-L104
where `path.Base(os.Args[0])` is the file name of the docker daemon binary (`docker` or `dockerd` depending on the version of the docker).

If we want to allow unsetting the prefix of `docker/` in syslog messages without changing the behavior by default, it might be possible to introduce an additional field for template so that it is adjustable.

I could create a PR to open further discussion about how to best handle the above mentioned situation.

**Comment by sukrit007** [comment]
+1 for the fix

**Comment by yongtang** [comment]
@sempasha @sukrit007 The PR #22384 was created to address this issue. Please let me know if there are any issue.
