### ISSUE TITLE
System error: exec format error : Line endings

### ISSUE THREAD

**Issue by sylvainmouquet** [docker/docker#22469]
When i run a container with a entrypoint with a bad ending lines (windows) the container does not start. If i convert the ending lines to Unix, the container starts successfully

**Output of `docker version`:**
1.10.2

**Output of `docker info`:**
Containers: 17
 Running: 4
 Paused: 0
 Stopped: 13
Images: 9
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 437
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-23-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.636 GiB
Name: brazil-dev-docker
ID: Q372:2WCC:IAHA:XPAQ:2APS:IY2H:BPAA:5TBC:JTXG:ATQH:YMEW:4AB5
WARNING: No swap limit support

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create a docker project with an entrypoint with Windows ending lines
2.
3.

**Describe the results you received:**
docker run -it hello:latest locale
exec format error
docker: Error response from daemon: Cannot start container a1d00e1882e4860714c70b4782c91c4c6a98ff79bd08f0665d8bc47c8713a154: [9] System error: exec format error.

**Describe the results you expected:**
no errors

**Additional information you deem important (e.g. issue happens only occasionally):**
If i run 
 docker run -ti --entrypoint=/bin/bash brazil_postgresql_smartged -s
and run /docker-entrypoint.sh
/docker-entrypoint.sh: line 1: #!/bin/bash: No such file or directory

i install dos2unix  yum install -y dos2unix
i convert the file to unix format
dos2unix /docker-entrypoint.sh
dos2unix: converting file /docker-entrypoint.sh to Unix format ...

i run /docker-entrypoint.sh all is ok

i exit the image and i run the container with /docker-entrypoint.sh

docker exec -it 5443019622fc /docker-entrypoint.sh
start success

**Comment by thaJeztah** [comment]
Yes, this is expected, docker sends files to the daemon as-is, and a linux container won't accept shell files if they have the wrong line ending.

I don't think there's much we can do here; if you obtained that file from a git repository, you can configure git to force checking out those files with unix line-endings (see https://help.github.com/articles/dealing-with-line-endings/), and make sure your text-editor uses unit line endings as a default.

As mentioned, I don't think there's much we can do here, so I'll close this issue, but feel free to continue the discussion here after I closed

**Comment by sylvainmouquet** [comment]
The file is pushed with COPY and the repository is TFS
Perphaps a better error message could be displayed to the user

**Comment by thaJeztah** [comment]
This error is the error that Linux outputs (yes I agree they could've done a better job at that :smile:)

**Comment by Hronom** [comment]
Can `COPY` command automatically convert line endings to the proper one?

**Comment by Hronom** [comment]
Or at least flag that enables line ending fixing, this will be very helpful, because this is big trouble then you work under windows.

**Comment by Iakovenko-Oleksandr** [comment]
Totally agree with @Hronom, while working from under Windows, editing entrypoint is really annoying

**Comment by thaJeztah** [comment]
Automatic conversion is not something we will implement. Most editors allow you to set what line-endings to use for your files, and this situation is not any different from (e.g.) locally editing files on a Windows machine and uploading them to a Linux server. Docker cannot "assume" a file needs to be converted, as it doesn't know what the intent is (there are valid use cases where you would want to keep the line endings in a certain format).

**Comment by Hronom** [comment]
@thaJeztah I'm understand you and totally agree, the question is in adding some sugar:) from Docker side.

Now I'm thinking about command, for example `FIXLINEENDINGS`:
`FIXLINEENDINGS <path>`
`FIXLINEENDINGS ["<path>",... "<path>"]`

So new Dockerfile looks like:
```
FROM ubuntu:16.04

COPY /test-app/bin /test-app
FIXLINEENDINGS ["/test-app/wait-for-it.sh", "/test-app/docker-entrypoint.sh"]
RUN chmod u+x /test-app/wait-for-it.sh
RUN chmod u+x /test-app/docker-entrypoint.sh

WORKDIR /test-app

CMD ["./docker-entrypoint.sh"]
```

**Comment by thaJeztah** [comment]
That's really a slippery slope; where will it end? Wildcards? (`FIXLINEENDINGS /project/*.sh`) Fixing UTF-8 BOM headers that were added by an editor? (`REMOVEBOMHEADERS`), encoding issues (`SETENCODING UTF8 ["file1", "file2"]`). This will lead to highly inefficient images (each modification will lead to *another* copy of those files in the layered filesystem).

If your code is under version control, this is already possible, for example, for git: https://help.github.com/articles/dealing-with-line-endings/, and for SVN: http://stackoverflow.com/questions/10164132/how-to-adjust-svn-settings-to-convert-line-endlings-on-windows. For git, it's even possible [to mark a file as "executable"](http://stackoverflow.com/questions/21691202/how-to-create-file-execute-mode-permissions-in-git-on-windows), so that the `chmod u+x` can be omitted.

And if you don't use a version control system, [using `dos2unix` is still an option](https://chrisjean.com/convert-dos-formatted-files-to-unix-format-in-ubuntu-and-centos/) (but fixing at the source instead of fixing up in the Dockerfile is really the preferred way to handle this)
