### ISSUE TITLE
race conditions with restart policies and overlay networks in docker 1.11.0-1.11.1

### ISSUE THREAD

**Issue by vikstrous** [docker/docker#22486]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 102
 Running: 4
 Paused: 0
 Stopped: 98
Images: 2
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 209
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host overlay bridge null
Kernel Version: 3.13.0-74-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.676 GiB
Name: ip-172-31-33-160
ID: TZXF:QIZJ:QFMJ:VAJ2:C6VT:DOHB:H5JA:CKLG:37RZ:4XTR:FSA2:4UY7
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 33
 Goroutines: 83
 System Time: 2016-05-03T21:06:23.420006922Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster store: etcd://172.17.0.1:2050
Cluster advertise: 172.17.0.1:12376
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS Ubuntu 14.04 with `curl https://get.docker.com/ | sudo sh`

**Steps to reproduce the issue:**
1. Create ubuntu 14.04 vm on AWS
2. This is my cleaned up bash history:
```
curl https://get.docker.com | sudo sh
sudo docker run -d --name etcd -p 2050:2050 --restart always quay.io/coreos/etcd:v2.2.4 --advertise-client-urls http://172.17.0.1:2050 --listen-client-urls http://0.0.0.0:2050 --debug
sudo cat <<EOF | sudo tee /etc/docker/daemon.json
{       
        "debug": true,
        "cluster-advertise": "172.17.0.1:12376",
        "cluster-store": "etcd://172.17.0.1:2050"
}
EOF
sudo kill -HUP $(cat /run/docker.pid)
sudo docker network create -d overlay ol
for i in $(seq 0 10); do sudo docker run -d -t --net ol --restart always --name test$i alpine sh; done
sudo docker ps
sudo service docker restart
sudo docker ps
```
I ran it with 100 containers last time, but it should work with 10. If it doesn't, run more containers.

**Describe the results you received:**
Some of the containers failed to start with the following error:
```
$ docker inspect test18 | grep Error
            "Error": "network ol not found",
```
They were in a "stopped" state instead of a "restarting" state.

**Describe the results you expected:**
I expected the containers to start successfully

**Additional information you deem important (e.g. issue happens only occasionally):**
This seems to be a race condition during start up that happens only when using an etcd in a docker container on the same machine with overlay networking.

**Comment by vikstrous** [comment]
I should add sometimes when containers get into this state they can be started again cleanly, other times starting them causes the following error:
`service endpoint with name XXXX already exists`
I don't know yet why this is.

**Comment by mavenugo** [comment]
@vikstrous overlay network `ol` is stored in the `etcd` kv-store. Since the kv-store is run as a container as well and the docker restart doesnt guarantee that the `etcd` container comes up before other containers... all the containers that run in the overlay network (which depends on the etcd store) will fail to start. If we have some sort of privileged (or system) container concept, then the daemon can possibly bring such containers up before the dependent containers to address these issues.
The only workaround is to manually restart the container after the etcd container is up and running.

**Comment by mavenugo** [comment]
@vikstrous I dont know why you are hitting the second issue though. But the workaround is to use `docker network disconnect -f {network} {XXX}`

**Comment by vikstrous** [comment]
I've also seen another potentially related issue...

Sometimes when I restart docker with UCP running on it the overlay network doesn't come back up.
```
ubuntu@ip-172-31-34-92 ~> docker start test0
Error response from daemon: subnet sandbox join failed for "10.0.0.0/24": vxlan interface creation failed for subnet "10.0.0.0/24": failed to set link up: transport endpoint is not connected
Error: failed to start containers: test0
```

I can open a separate issue if it's unrelated to this one.

**Comment by mavenugo** [comment]
@vikstrous thanks pls do open a new issue. I have never seen this issue `failed to set link up: transport endpoint is not connected` in the past.

**Comment by mavenugo** [comment]
@vikstrous actually, the workaround of `docker network disconnect -f {network} {XXX}` for the second issue will work only if you execute it from another host (not from the host where the container with the name {XXX} present. But, if you wish to find a workaround for the second issue, it is a bit more involved..

`docker rename test1 testfoo`
`docker network disconnect -f dtr-ol test1`
`docker rename testfoo test1`
`docker network connect dtr-o1 test1`
`docker start test1`

More than a workaround, it is a trick to cheat the endpoint store to let go of the stale endpoint and let the daemon reuse it. We still need to figure out why the stale endpoint ends up in the etcd store. Since you are running in an environment where the etcd instances are running in multiple nodes, is it possible that the partition merge is recreating some states that we dont expect in the kv-store ? I just have wild guesses atm.

**Comment by vikstrous** [comment]
The workaround works. In this case I'm testing with a single etcd, so there's no partition or anything like that happening.

**Comment by mavenugo** [comment]
@vikstrous hmm... can I have access to the setup ?

**Comment by cpuguy83** [comment]
@vikstrous Could you test with #22561 ?
