### ISSUE TITLE
Set enviroment variables for existing container

### ISSUE THREAD

**Issue by AndreKR** [docker/docker#22490]
There should be a way to set environment variables for an existing container.

I see #15078 where a `docker update` command was implemented but you could not decide on whether to include environment variables or not and so apparently you didn't. (Aren't you guys making it too complicated?)

Of course they will only be available after a restart, but that's totally fine.

What is the alternative? Copy all transient files out from the container, look at `docker inspect`, re-assemble the command line that was used to run the container, remove the container (to free name and ports and such) and then restart it and copy the files back?

**Comment by AndreKR** [comment]
I just noticed... Kitematic can do it - so it seems to be a client limitation.

**Comment by thaJeztah** [comment]
Kitematic doesn't do that either; it creates a new container with the new environment-variables set, filesystem changes are lost.

There's a number of reasons why we haven't implemented this; environment variables are used in a lot of ways in images. Many images use the environment variables to initialize the container the first time it's run (for example, to initialize a database, set a password, etc). Restarting the container will not repeat those steps.

It's also a fundamental decision; containers should be ephemeral, and don't hold "state". Any data that should be persisted beyond a container's lifecycle should be stored outside of the container (in a volume). Basically, containers should be treated as "immutable". For example, don't update the software that's *in* the container, but replace the container with a newer version that contains the updated software. 

This is a key concept of Docker, and an important one; because of this, containers are "repeatable", i.e. if I run an image with the same arguments, I get the same result, anywhere. I can be confident that I ran the image on my local machine, do the same on a production machine, and have the same outcome. If I managed to make a container work by (manually) making changes to it, it's no longer repeatable and that defeats the purpose of Docker. Containers should be treated as "cattle", not "pets" - i.e., don't hold on to your containers.

Having said that, you -can- preserve filesystem changes in the container, by committing it as a new image;

```bash
$ docker run -it --name=foobar alpine sh
/ # echo foo > bar
/ # exit

$ docker commit foobar mynewimage
$ docker rm foobar

$ docker run -it --name=foobar mynewimage sh
/ # cat bar
foo
```

Committing the changes to a new image preserves the "repeatable" concept; running `mynewimage` will always result in the same outcome.

> look at docker inspect, re-assemble the command line that was used to run the container

I think this relates to the above; if you don't remember what was used to start a container, there's no chance to repeat it (how are you going to deploy the container in production, if you don't know what is needed to get it running?). If the options to start a container are non-trivial, either document it, or use a tool, like docker-compose (or a Makefile, see the Makefile in this repository; https://github.com/docker/docker/blob/master/Makefile)

**Comment by LK4D4** [comment]
I agree with @thaJeztah . Closing as inactive.

**Comment by willemavjc** [comment]
I know that many will not care but I personally do not _fully_ agree with @thaJeztah 

It might now be 2019 for an issue closed in 2016 but here are some scenarii that seem to have be forgotten past then:

Adding up at run time rather than while building up can be especially useful when you're testing different possibilities like choosing between `yarn` and `npm` or designing an app with a throwable compiling environment.
