### ISSUE TITLE
Add `named` volume ls filter

### ISSUE THREAD

**Issue by shane-axiom** [docker/docker#22515]
It would be very useful to support a `volume ls` filter to only show named volumes. I can hack around this by checking for volume names that aren't exactly 65 characters, but that's sketchy.

My main intent for this is to create scripts to automatically back up any named volumes, since they always contain data I want to keep around and non-named data volumes generally don't (in our case).

**Comment by thaJeztah** [comment]
Hm, I'm not entirely sure if this information is actually stored somewhere. Basically, an "unnamed" volume is also "named", only the name is generated.

We *do* have labels now on volumes, and there's a PR (https://github.com/docker/docker/pull/21567/files) to allow filtering on labels, so that would give you an option to specify a label (e.g. `backup=yes`) on those volumes that are important

**Comment by shane-axiom** [comment]
Ah, ok, if volume label filtering support gets merged that could be an acceptable workaround. Should I close this in favor of #21567, or leave open for now? If there actually is some sort of `named` flag on volumes that would be filterable that could be useful as well.

**Comment by thaJeztah** [comment]
I'm not sure if we persist that information, @cpuguy83 probably knows

**Comment by LK4D4** [comment]
Labels were merged  and we had the same conversation in another issue, it's hard to say which is named.
