### ISSUE TITLE
`docker kill` just like `docker-compose kill`

### ISSUE THREAD

**Issue by dtu-compute** [docker/docker#22530]
`docker kill` or perhaps `docker kill -f` should kill the container that was created by the `Dockerfile` in `.` just like how `docker-compose kill` works.

If there are only one container then `docker kill` or `docker kill -f` would kill that container regardless of above idea.

**Comment by justincormack** [comment]
Most people do not have the Dockerfile around when they run their containers, so I don't think this will work so well. You can just always create a compose file though to do this.

**Comment by phemmer** [comment]
There's also the problem that you can have multiple running docker containers using the same image (built from the referenced Dockerfile). Which one gets killed?

**Comment by thaJeztah** [comment]
There's no way to relate a Dockerfile to a container, or even to a specific image, because you "tag" the built image during build, e.g. `docker build -t myimagename .`.

Thanks for suggesting, but I'm going to close this issue, because this is not something we'll implement. If you need this, docker compose is the best solution.
