### ISSUE TITLE
Flaky test: TestEventsLimit failing on WindowsTP5

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#22601]
TestEventsLimit seen failing on this PR; https://github.com/docker/docker/pull/22588 (https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP5/1500/console)

```
2:52:07 ----------------------------------------------------------------------
12:52:07 FAIL: docker_cli_events_test.go:108: DockerSuite.TestEventsLimit
12:52:07 
12:52:07 docker_cli_events_test.go:129:
12:52:07     c.Assert(err, checker.IsNil, check.Commentf("%q failed with error", strings.Join(args, " ")))
12:52:07 ... value *errors.errorString = &errors.errorString{s:"exit status 127: D:\\CI\\CI-858ae79\\binary\\docker.exe: Error response from daemon: Container command 'C:/busybox/busybox.exe' not found or does not exist.\n"} ("exit status 127: D:\\CI\\CI-858ae79\\binary\\docker.exe: Error response from daemon: Container command 'C:/busybox/busybox.exe' not found or does not exist.\n")
12:52:07 ... "run --rm busybox true" failed with error
12:52:07 
```

**Comment by dnephin** [comment]
This is still failing on WindowsRS1 (https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/1866/console)

**Comment by thaJeztah** [comment]
ping @jhowardmsft ^^

**Comment by tiborvass** [comment]
Ping @swernli

**Comment by jhowardmsft** [comment]
I'm on vacation... :innocent:

**Comment by darrenstahlmsft** [comment]
I've seen this locally too. Appears to be in the platform. Attempting to get a better repro and file a local bug.

**Comment by cpuguy83** [comment]
Any news on this?

**Comment by darrenstahlmsft** [comment]
The issue appears to be that starting so many containers at once on the CI servers triggers a platform timeout. We're tracking an internal issue on this, as the timeout seems too aggressive, but in order to avoid this in CI, we can either limit the concurrency of the test, or impose concurrency limits on calls to the engine. I'm leaning towards limiting the concurrency of the test, I'll submit a PR soon.
