### ISSUE TITLE
Workflow for making new Dockerfiles?

### ISSUE THREAD

**Issue by johnstt** [docker/docker#22617]
Sorry if this is a repost. It's tricky to search for duplicates here and on the web because there are so many guides about **workflows which make use of Docker**, and so on.

**What I'm after is different:** is there an accepted workflow for creating Dockerfiles / images? Allow me to explain...

Putting together a Dockerfile for one of my projects typically involves lots of trial and error. 
Eventually, I end up with a file that works from scratch (overcomes all the weird caveats and dependency issues that might arise). By the time I am done, I have a huge stack of redundant images and containers which I have to delete manually. This seems to happen even if I use the options to delete intermediate images/containers - the leftover images and containers are _valid_ and distinct, they just fail at some late stage in the Dockerfile (installing a package, setting up permissions, running some application etc).

Is there a proper way to create something like a 'staging area' for Dockerfiles under construction, so I don't have to pick through these useless images/containers afterward? Am I missing something obvious?

**Comment by thaJeztah** [comment]
If you use the same name each time you build your image, then the previous build will automatically be "untagged", and become "dangling", e.g. `docker build -t myimage .` will build the image, and untag the previous version of `myimage`.

You can cleanup unused and untagged images by running;

    docker rmi $(docker images -aq --filter dangling=true)


I'll close this issue, because the issue tracker is not a general support forum, but for reporting bugs and feature requests, which this is not. For these kind of questions, please consider using;

- forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow


I'll close this issue because of the above, but hope this helps you further. Feel free to comment here afte I closed
