### ISSUE TITLE
Docker stop sync with replaced files

### ISSUE THREAD

**Issue by luan-cestari** [docker/docker#22627]
I saw this case on https://forums.docker.com/t/container-losing-volume-etc-hosts-when-file-is-edited/10038 and I tried out own my on. It seems that Docker is not aware when the volume is a single file and the whole file is replaced. I tried also with symlink but I also noticed another problem ( https://github.com/docker/docker/issues/13382 ). Is it possible and desired to docker to watch the changes over a file like this case?

**Comment by thaJeztah** [comment]
Yes, this is expected, and not something docker can account for; this is a limitation in the way `mount` works. Basically, when bind-mounting a file, mount keeps track of the *inode* of the mounted file. Some tools don't update a file, but write to a temp-file, and replace the existing file. The bind-mount is still using the inode of the original file though, which may have been deleted in the process.

We do have some mention of this in the documentation, but that refers to trying to edit a bind-mounted file from *inside* the container, which is the same problem actually, but with different effect;

https://docs.docker.com/engine/userguide/containers/dockervolumes/#mount-a-host-file-as-a-data-volume

> Note: Many tools used to edit files including vi and sed --in-place may result in an inode change. Since Docker v1.1.0, this will produce an error such as “sed: cannot rename ./sedKdJ9Dy: Device or resource busy”. In the case where you want to edit the mounted file, it is often easiest to instead mount the parent directory.

The solution is the same; if possible, put the file you want to mount in a directory, and mount the directory instead of a single file. In the example discussed in the linked forum post (bind-mounting `/etc/hosts`), this may not be possible. Perhaps not using the `--in-place` option would resolve it though.

Is there a reason you want to edit the `/etc/hosts` file for the container? If you want to add custom host entries to `/etc/hosts`, I'd recommend using the `--add-host` option on `docker run`, for example

```bash
docker run -t --rm --add-host foobar:192.168.1.5 alpine sh -c "cat /etc/hosts" 
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
192.168.1.5	foobar
172.17.0.4	f8bb57c2869d
```

**Comment by luan-cestari** [comment]
I see.Thank you for your prompt reply. As you mentioned in the issue https://github.com/docker/docker/issues/18246#issuecomment-159736981 , the solution for this case could also rely on using a volume plugin, right? 

Do you consider that Docker could have a this feature in the future (watch if an inode is removed and look up the new one in case of change)?

**Comment by thaJeztah** [comment]
Given that a volume plugin also provides a mount-point that is mounted in the container, I don't think a volume can easily resolve this issue, unless if would (for example), watch a file and sync those changes to the bind-mounted file to prevent the inode from changing.

> Do you consider that Docker could have a this feature in the future (watch if an inode is removed and look up the new one in case of change)?

I don't think  that'll happen, it would add a lot of complexity, if even possible; basically that would mean watching a file (by name?), unmount the old file, and mount a new file in a running container. There's a lot of moving parts in that process, and could easily lead to other issues.

I fully understand the issue here, and it would be great if this "just worked", but I think we should close this.

**Comment by cpuguy83** [comment]
Docker really can't dynamically update the mounts (anything is possible, just a matter of what's right).
I think the only way to really handle this is to either:
1. Patch vfs to support mounts to a file reference rather than an inode
2. Use a custom fs (such as a fuse based one) that tracks the reference rather than the inode.
