### ISSUE TITLE
docker can not work on ubuntu 16.04

### ISSUE THREAD

**Issue by YuleiXiao** [docker/docker#22647]
docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6.1
 Git commit:   20f81dd
 Built:        Wed, 20 Apr 2016 14:19:16 -0700
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

ps -ef|grep docker
root      7299     1  0 17:38 ?        00:00:00 /usr/bin/docker daemon -H fd://

Steps to reproduce the issue:
1. Install Docker via "apt install docker.io" on Ubuntu 16.04
2. Just run any docker command, docker will fail to start with the error:

**Comment by wenchma** [comment]
your user is running with the right permission ?

**Comment by thaJeztah** [comment]
can you try using `sudo docker version`?

Also note that you're installing a version of docker that is maintained and supported by Ubuntu, and not the official docker packages we provide. To install the official docker packages from this repository, follow the instructions here; https://docs.docker.com/engine/installation/linux/ubuntulinux/

**Comment by YuleiXiao** [comment]
@wenchma @thaJeztah it work well after I reboot my server but not work only restart docker service

**Comment by thaJeztah** [comment]
@YuleiXiao I'm not sure if the ubuntu packages also modify the user to be in the docker group, which requires you to log out and back in again; (we mention this in [our installer script](https://github.com/docker/docker/blob/996138bf8e6acde9a937755ef81459f7d7566fc9/hack/install.sh#L53-L58))

I'm going to close this issue, because I think it's resolved, and the package you installed is maintained by Ubuntu, so we cannot provide support for that.

Feel free to comment here after I closed 👍
