### ISSUE TITLE
I can push several private images which exceeds my quote limitation

### ISSUE THREAD

**Issue by StanleyShen** [docker/docker#22667]
Though the issue is related to hub.docker.com  but I think the feedback repo is not quite active.
So I put the issue here.

I can push several docker images but in fact I only have 1 private repository for my quote.

What I did just use "docker push" after "docker login"

**Comment by thaJeztah** [comment]
With multiple images, do you mean, create multiple private repositories, or push multiple images (i.e. multiple "tags") to the same, private repository? Note that *public* repositories are free, so you can create an unlimited amount of public repositories, only private repositories are paid for.

Basically, a repository is;

    hub.docker.com/r/yourusername/yourprivaterepo/


But you can create as many images/tags as you like;

```
yourusername/yourprivaterepo:latest
yourusername/yourprivaterepo:version1
yourusername/yourprivaterepo:1.0
yourusername/yourprivaterepo:beta
```

Hope this helps, but if you have additional questions, it's best to send an e-mail to support@docker.com; this repository is really about the docker open source software, and Docker Hub is managed by a different team.

**Comment by StanleyShen** [comment]
I agree, just didn't find a good place and I though it's managed by this team too.
I think my case is a big security issue, which means I can push unlimited private repositories even I only had one.
I sent email to email you provided.

**Comment by fauzanariffin** [comment]
Hi Stanley,

Yes, you can push different images as private repositories.
This settings can be change by going to https://hub.docker.com/account/settings/ and changing the **default visibility for your repositories**.

However, you **can't pull the images that are private** (even though you own them) since you are on a FREE tier.
You will need to upgrade to a PAID tier in order for you to pull them.

I hope that clear your doubts.
