### ISSUE TITLE
Docker Daemon 1.11 inside Netns + Overlay Network

### ISSUE THREAD

**Issue by HamidEDD** [docker/docker#22675]
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 27
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.16.0-49-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: openstack-cli
ID: Y6E5:SEXI:ENOH:YGNX:NZHM:BTS4:7DIR:HSVZ:X5JR:4HNZ:DZ6J:4YTG
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VM Ubuntu 14.04.4 LTS  under KVM

**Steps to reproduce the issue:**

```
echo >> start.sh << EOF
#!/bin/bash
ip link add eth0 type veth peer name veth_pub
ip link set dev eth0 up
ip link set dev lo up
ip link set dev veth_pub netns 1
ip addr add 20.20.20.1/24 brd + dev eth0
ip netns exec default ip link set dev veth_pub up  ## default is the netns id 1
ip netns exec default ip addr add 20.20.20.254/24 brd + dev veth_pub
ip route add default via 20.20.20.254
mkdir /var/run/docker_demo/
docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker_demo/docker.sock -D --exec-root=/var/run/docker_demo -G demo --pidfile=/var/run/docker_demo/docker.pid --userland-proxy=true --userns-remap=demo --dns=8.8.8.8 --cluster-store=consul://20.20.20.254:8500 --cluster-advertise=20.20.20.1:2376
EOF
```
1. unshare -n ./start.sh
2. docker -H tcp://20.20.20.1:2376 run -itd alpine sh
3. docker -H tcp://20.20.20.1:2376 network create -d overlay demo
4. docker -H tcp://20.20.20.1:2376 run -itd --name c1 --net=demo alpine sh

**Describe the results you received:**

- The Step 2 works correctly.
- at step 4, I get this error from Docker CLI : : 
docker: Error response from daemon: error creating external connectivity network: cannot restrict inter-container communication: please ensure that br_netfilter kernel module is loaded.

- From The Docker Daemon, I get : http://pastebin.com/rGkmxmfx

- I had already tried starting Docker Daemon with "--icc=true" param, but without success.

- The Overlay network works correctly when the daemon is launched outside the netns

Please, Any idea  ?

**Comment by HamidEDD** [comment]
Hello, 
Can someone tell me if there is a solution for this?

**Comment by sanimej** [comment]
@HamidEDD What is happening here is in the new network namespace created on unshare /proc/sys/net/bridge directory is not created. For a bridge creation with icc=false docker daemon tries to [check the booleans] (https://github.com/docker/libnetwork/blob/e5064dd5ac5dddc55b04036843addd7cd219257b/drivers/bridge/setup_bridgenetfiltering.go#L40) (bridge-nf-call-iptables etc.) in this directory and it fails. The error message is a bit misleading.

The reason it fails in step 4 for you is that when you create a container on a overlay network we try to create an interface on another bridge, docker_gwbridge, for external connectivity. icc is set to false by default on this bridge.

But this problem doesn't happen in the dind environment when I create a bridge with icc set to false. Its because the error is specifically [ignored] (https://github.com/docker/libnetwork/blob/e5064dd5ac5dddc55b04036843addd7cd219257b/drivers/bridge/setup_bridgenetfiltering.go#L36) in the dind case.

/proc/sys/net/bridge not getting created in a network namespace seems to be a kernel issue.

**Comment by mavenugo** [comment]
thanks @sanimej that make sense on why it works in dind :) (though it isnt actually working as expected).

@HamidEDD though am not proud of it... simpler workaround is to `touch /.dockerenv` and that will cheat the code and it will ignore the error just as in `dind` case.

**Comment by sanimej** [comment]
@mavenugo with dind I verified that containers on a network with icc=false can't talk to each other. So the booleans not being available inside a network ns doesn't affect at least this functionality.

**Comment by HamidEDD** [comment]
@mavenugo @sanimej  thanks for your help ! it works with `/.dockerenv`.
I also realized, that netowrk ns destroy the /proc/sys/net/bridge, but I have found no way to remount it.
Thanks again, I close the issue.
