### ISSUE TITLE
where is my docker.conf or docker

### ISSUE THREAD

**Issue by SweetPotatoGit** [docker/docker#22692]
i cant find it anywhere likely to be /etc/init/docker.conf, /etc/default/docker or /etc/default/docker.io,plearse help me,thank you!!!!!!

**Comment by cpuguy83** [comment]
Are you on a system with systemd? If so it would be `/lib/systemd/system/docker.service` most likely... but really shouldn't be editing these files directly.

If you would like to change settings, I'd recommend providing those settings in `/etc/docker/daemon.json`
For docs on this file, see: https://docs.docker.com/engine/reference/commandline/daemon/#daemon-configuration-file

Closing as this isn't really an issue.

**Comment by thaJeztah** [comment]
What distro are you running on? `/etc/default/docker` is only used for systems running upstart or sysvinit (e.g. ubuntu 14.04) . You can use a daemon configuration file (`/etc/docker/daemon.json`)

https://docs.docker.com/engine/reference/commandline/daemon/#daemon-configuration-file

Or for drop-in configuration files for systems using systemd;
https://docs.docker.com/engine/admin/systemd/#custom-docker-daemon-options


I'll close this issue, because the GitHub issue tracker if for reporting bugs and feature requests, not a general support forum. For questions, consider using;

- forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow

I'll close this because of the above, but I hope this helps, and feel free to comment after I closed
