### ISSUE TITLE
Request: gcplogs driver (and others) should support log level severity

### ISSUE THREAD

**Issue by hamx0r** [docker/docker#22736]
In the vein of #18480, any of the log drivers could accept a regular expression string as an argument to configure the driver to parse the log body (ie stdout) so that additional fields could be set for whatever log driver is bing used.  For Google Stackdriver Logging (aka Google Cloud Logging), the [driver](https://github.com/docker/docker/blob/master/daemon/logger/gcplogs/gcplogging.go) sets a `data` field which contains the full text of the log entry as a single string.  I suggest any of the following improvements:
1. Use the stream to establish a Severity level:  `stdout` means `info`, and `stderr` means `error`.  Even just 2 log levels would be a big help.
2. A regex string `--log-opt` could be used to set more [structured data here](https://developers.google.com/resources/api-libraries/documentation/logging/v2beta1/python/latest/logging_v2beta1.entries.html#write) which would end up in the `structPayload` part of the [log message in Google Stackdriver Logging, making it filterable](https://cloud.google.com/logging/docs/quickstart-sdk).
3. Similarly, a regexp string could break a log message into existing fields, like `severity`

Both regex ideas could be implemented using [named groups](https://github.com/google/re2/wiki/Syntax).

**Comment by henryw374** [comment]
a possible alternative it to tell gcplogs to parse log messages as json. then users can use a logging encoder to record timestamp, severity fields etc as required by google cloud logging.

**Comment by cpuguy83** [comment]
Definitely -1 to applying a regex to each log message.

**Comment by thaJeztah** [comment]
Agreed, applying a regex to each log message is going to seriously affect logging performance, which _will_ be an issue for high-volume logging. Performing the same search on Google's side may be an alternative (also I realize that's not ideal as well) https://cloud.google.com/logging/docs/view/advanced_filters

I don't think we should implement this in the core functionality of docker. Note that work is being done on supporting _external_ logging driver plugins. Once that's there, custom logging driver plugins can implement this, so that people that need this functionality, and know the implications, can install a custom driver; https://github.com/docker/docker/pull/28403

Some alternative proposals that don't involve regexing each message can be found here; https://github.com/docker/docker/issues/29604, and https://github.com/docker/docker/issues/25683, and possibly could allow adding more flexibility

I'm closing this issue because we won't implement this as suggested, but feel free to comment after I closed.

**Comment by henryw374** [comment]
More of what I'm suggesting then, have a way to stop the gcplog plugin wrapping the message as {"data" : <msg>}, ie `--raw` or some such, so users can log in json format and so set the correct severity etc.

**Comment by c0b** [comment]
so what's the best solution to have gcplogs severity levels so far?

**Comment by c0b** [comment]
so what's the best solution to have gcplogs severity levels so far?

**Comment by nikhilk** [comment]
Anyone know if whether is there an alternate gcp log driver that supports some customization?
