### ISSUE TITLE
Why remove container command is not defined

### ISSUE THREAD

**Issue by swan-go** [docker/docker#22779]
$ docker ps -a      
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                           PORTS               NAMES
96bbfe60adc9        dd64161e9554        "/bin/sh -c '/usr/bin"   2 hours ago         Exited (137) About an hour ago                       96bbfe60adc9_dockerapp_mysql_1

$ docker rm 96bbfe60adc9                                   
flag provided but not defined: -i
See 'docker rm --help'.

$ docker rm --help                                          
flag provided but not defined: -i
See 'docker rm --help'.

 docker version              
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64

**Comment by phemmer** [comment]
Sounds like you have an alias or something wrapping your `docker` command.
Can you provide the output of `command -V docker`?

**Comment by HackToday** [comment]
yes, looks like environment related

**Comment by thaJeztah** [comment]
I'll go ahead and close this, because this doesn't look like a bug in docker, but feel free to continue the discussion

**Comment by swan-go** [comment]
Only supported -v, not support  -V

$git:(master*) docker -V    
flag provided but not defined: -V
See 'docker --help'.

$git:(master*) docker -v 
Docker version 1.11.1, build 5604cbe

**Comment by phemmer** [comment]
Not `docker -V`, `command -V docker`

**Comment by penhauer-xiao** [comment]
May be  zsh can't support this,  but bash is ok

**Comment by penhauer-xiao** [comment]
Untill today,  docker version 1.12.3, it can't support zsh. :)  so this problem still exists.

**Comment by thaJeztah** [comment]
@penhauer-xiao docker works perfectly with zsh, but as @phemmer tried to explain above, it looks like there's an alias installed on your system. What is the output of `command -V docker` on your system? It should show something like;

```
command -V docker

docker is /usr/local/bin/docker
```

**Comment by penhauer-xiao** [comment]
@thaJeztah  Oh, Not docker -V,  like docker -v is ok;   but this issue is still exists, as following is my trace info:

$ docker -v
Docker version 1.12.3, build 6b644ec

$ docker ps  
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
5afb994baf78        anwar/redis:1.1     "/bin/sh -c 'supervis"   21 hours ago        Up About an hour    0.0.0.0:4379->6379/tcp   redis

$ docker rm 5afb994baf78  
unknown shorthand flag: 'i' in -i
See 'docker rm --help'.

$ docker rm --help   
unknown shorthand flag: 'i' in -i
See 'docker rm --help'.

**Comment by thaJeztah** [comment]
So, it looks like there's an alias set for `docker rm`, so each time you run `docker rm`, an alias that does (e.g.) `docker rm -i` is executed instead.

http://zsh.sourceforge.net/Intro/intro_8.html

**Comment by penhauer-xiao** [comment]
@thaJeztah 

I couldn't  config alias of docker,   My zsh config as following:

export UPDATE_ZSH_DAYS=30

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# export ZSH_THEME="xiong-chiamiov-plus"
export ZSH_THEME="anwar"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want disable red dots displayed while waiting for completion
# DISABLE_COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git autojump sudo last-working-dir docker docker-compose encode64 urltools  extract)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

#***********************************
export GOROOT="/mnt/shared/go"
export GOARCH="amd64"
export GOOS="linux"
export GOBIN="$GOROOT/bin"
export GOTOOLS=$GOROOT/pkg/tool/linux_amd64

export GOPATH="/mnt/shared/go-T"
export GOPKGBIN="$GOPATH/bin"
export PATH=$GOBIN:$GOPKGBIN:$GOTOOLS:$PATH
#***********************************

setopt INC_APPEND_HISTORY SHARE_HISTORY
setopt APPEND_HISTORY	# If this is set, zsh sessions will append their history list to the history file, rather than overwrite it.
unsetopt BG_NICE 			# Run all background jobs at a lower priority. This option is set by default.
setopt MENUCOMPLETE   # Very good to select option for commands,etc. ls -

# Set/unset  shell options
setopt   autoresume histignoredups pushdsilent 
setopt   autopushd pushdminus extendedglob rcquotes mailwarning
unsetopt bgnice autoparamslash

# Autoload zsh modules when they are referenced
zmodload -a zsh/stat stat
zmodload -a zsh/zpty zpty
zmodload -a zsh/zprof zprof
zmodload -ap zsh/mapfile mapfile

alias ll='ls -l --color=auto'
alias ls='ls --color=auto'
alias lla='ls -al --color=auto'
alias f=finger
alias -g cp='cp -i'
alias -g mv='mv -i'
alias -g rm='rm -i'
alias -g grep='grep --color=auto'
alias -g tmc='source $ZSH/themes/simple.zsh-theme'
alias -g tmn='tmux new -d -s'
alias -g tml='tmux ls'
alias -g tma='tmux attach -t'
alias -g tmk='tmux kill-session -t'
alias -g rtm='retmux '
alias -g py='bpython'
alias -g uterm='/usr/bin/rxvt-unicode'
alias -g mterm='/usr/local/bin/mlterm'
alias man="pinfo -m"
alias -g gt='gnome-terminal'
alias -g pcz='proxychains'
#alias go=colorgo

sudo-command-line() {
    [[ -z $BUFFER ]] && zle up-history
    [[ $BUFFER != sudo\ * ]] && BUFFER="sudo $BUFFER"
    zle end-of-line           
}
zle -N sudo-command-line

bindkey "\e\e" sudo-command-line
#}}}

setopt HIST_IGNORE_DUPS

zstyle ':completion:*:ping:*' hosts 192.168.128.1{38,} www.g.cn \
       192.168.{1,0}.1{{7..9},}
       
my_accounts=(
{r00t,root}@{192.168.1.1,192.168.0.1}
kardinal@linuxtoy.org
123@211.148.131.7
)
zstyle ':completion:*:my-accounts' users-hosts $my_accounts
#}}}

eval "`dircolors ~/.dircolors`"
ulimit -c unlimited

export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8

**Comment by penhauer-xiao** [comment]
Sorry, it really is an alias problem, this line:  alias -g rm='rm -i'  affect the docker

**Comment by penhauer-xiao** [comment]
Thanks @thaJeztah
