### ISSUE TITLE
How does docker imcomplement "docker start ID" command?

### ISSUE THREAD

**Issue by TheBeeMan** [docker/docker#22896]
I am a newcomer to docker, I just want to konw how did libcontainerd implement "docker start ID" command.I made a preliminary study on that, things below list what i understand about starting a container.
1. api/client  post /container/xx/start to docker daemon
2. daemon.ContainerStart
3. daemon call libcontainerd/client to start a container
4. libcontainerd.client call libcontainter.container  to start a container
5. libcontainter.container Post GRPC message to libcontainerd.remote 
6. However, libcontainerd.remote could not handle the event "start-container"

  so, the question is how libcontainerd to start a container and excute the user command, like "bin/bash" or "echo hello-world"

**Comment by thaJeztah** [comment]
This may be a question that's better asked on the docker-dev mailing list or in the docker-dev IRC channel (see https://github.com/docker/docker/blob/master/CONTRIBUTING.md#talking-to-other-docker-users-and-contributors). I'll close this issue, because the GitHub issue tracker is intended for tracking bugs, which this is not, but perhaps @mlaventure is able to answer this
