### ISSUE TITLE
systemd unit file ignores DOCKER_OPTS from /etc/default/systemd

### ISSUE THREAD

**Issue by mschirmacher** [docker/docker#22905]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:16:22 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:16:22 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 33
Server Version: 1.11.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.5.0-2-amd64
Operating System: Debian GNU/Linux stretch/sid
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.38 GiB
Name: lap-it-012
ID: KLFQ:LVWH:EOTZ:CNSE:FI5B:EHDD:J3US:BE3F:H3ZR:D5AU:2COI:VLIH
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
```
**Additional environment details (AWS, VirtualBox, physical, etc.):**

This bug affects especially the systemd unit filed provided by the official debian packages.
Probably the unit file is the same for other distributions, too, but i didn't check that.

**Steps to reproduce the issue:**
1. configure DEFAULT_OPTS in /etc/default/docker
2. systemctl restart docker

**Describe the results you received:**

The docker daemon is started with the very same default options.

**Describe the results you expected:**

The unit file should consider the DOCKER_OPTS like the sysvinit script does.

**Additional information you deem important (e.g. issue happens only occasionally):**

Please let me know if there is another way to configure default daemon options for the docker daemon when it is started by systemd

**Comment by thaJeztah** [comment]
The `/etc/default/docker` file is only used for upstart/sysvinit (see the comment at the top of that file: https://github.com/docker/docker/blob/master/contrib/init/sysvinit-debian/docker.default#L1-L8)

To configure daemon options;

- Use a daemon-configuration file; https://docs.docker.com/engine/reference/commandline/daemon/#daemon-configuration-file (this method works irregardless of the process manager in use)
- Use a systemd drop-in file to override options from the systemd unit file; https://docs.docker.com/engine/admin/systemd/#custom-docker-daemon-options

We discussed adding an EnvironmentFile to the systemd unit, but using such a file was not the recommended way to configure a systemd service. (drop-ins are). Unfortunately, some distros ship docker with a different systemd service file than the [unit file in the official packages](https://github.com/docker/docker/blob/master/contrib/init/systemd/docker.service), which can be confusing if you have such a package installed.

I'll close this issue, because this has been discussed in other issues, but I hope the above helps you further

**Comment by haizaar** [comment]
I'll just add here that on Ubuntu 16.04 with docker-engine 17.04.0\~ce-0~ubuntu-xenial, using DOCKER**D**_OPTS (again, note the trailing D in DOCKERD) makes the options to apply.

I can not figure out why is it working, even by grepping DOCKERD_OPTS in the whole file system; but it does work.
