### ISSUE TITLE
why HostConfig remove Deprecated 

### ISSUE THREAD

**Issue by davidstack** [docker/docker#22933]
I use the start API  to add a  new volume to a container after it was created. just add a binds info to the HostConfig parameter. it test ok.
At https://docs.docker.com/engine/deprecated/ ,I find HostConfig in the API of start container  will be removed,is there any other method to add volume after container created? thanks

**Comment by cpuguy83** [comment]
Definitely should not rely on this, and certainly not if HostConfig is already set.

**Comment by mlaventure** [comment]
Not related to #22563, he is trying to add a new volume entry (i.e. `-v` equivalent) not a new device :).

Otherwise, updating the container configuration post create has never been explicitly supported AFAIK; that'd explain why HostConfig in start was deprecated I guess (can't say I remember when that happened though)

**Comment by davidstack** [comment]
@cpuguy83  any other method to add a new volume to a created container?

**Comment by davidstack** [comment]
@thaJeztah @mlaventure   I want  to add a new volume to a created container. Now ,i use the HostConfig parameterin the Start API.(just stop the running container,start the container with the binds parameter in HostConfig)
      but i found the parameter will be removed.
does docker have the feature to add a new volume to a created container?

**Comment by davidstack** [comment]
https://github.com/docker/docker/pull/22570   docker1.12 has removed this feature,so i closed this issue.
