### ISSUE TITLE
Docker graylog splits up stacktraces

### ISSUE THREAD

**Issue by justechn** [docker/docker#22979]
I am just getting started with docker and graylog and I have run into a snag. Docker is splitting up stacktraces so that each line is a new log. This is not optimal, and makes viewing the entire stack trace impossible. 

I setup my docker container from the instructions found here https://www.graylog.org/blog/28-centralized-docker-container-logging-with-native-graylog-integration

Is there some step that I am missing?

here is an example of what I get in graylog
![image](https://cloud.githubusercontent.com/assets/1508662/15544726/f7127124-2256-11e6-8fb8-1945807ea3cb.png)

**Comment by thaJeztah** [comment]
Yes, this is the way logging works in Docker; log-entries are separated by newlines, because there's no way for Docker to "detect" if multiple lines should be treated as a "single" log-entry, or as multiple.

See the discussion on https://github.com/docker/docker/issues/22920 for some background / context.

Unfortunately, I'll have to close this issue, but possibly we can have more features (including this use case), if there's an option to add custom logging-plugins.

**Comment by justechn** [comment]
ok, thanks, it sounds like docker logging is not going to work for us. I will look for another solution.
