### ISSUE TITLE
docker daemon fail to start, there are no more loopback devices available

### ISSUE THREAD

**Issue by hanae2e** [docker/docker#23043]
**Output of `docker version`:**
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:
 OS/Arch:      linux/amd64
```
(paste your output here)
```
i062683@mo-93f7030d0:~> docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
i062683@mo-93f7030d0:~> sudo /usr/sbin/service docker status
docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled)
   Active: failed (Result: exit-code) since Fri 2016-05-27 04:53:45 UTC; 27min ago
     Docs: http://docs.docker.com
 Main PID: 57330 (code=exited, status=1/FAILURE)

May 27 04:53:45 mo-93f7030d0 docker[57330]: time="2016-05-27T04:53:45.324943484Z" level=error msg="There are no more loopback devices available."
May 27 04:53:45 mo-93f7030d0 docker[57330]: time="2016-05-27T04:53:45.325122040Z" level=error msg="[graphdriver] prior storage driver \"devicemapper\" failed: loopback mounting failed"
May 27 04:53:45 mo-93f7030d0 docker[57330]: time="2016-05-27T04:53:45.325181627Z" level=fatal msg="Error starting daemon: error initializing graphdriver: loopback mounting failed"

**Output of `docker info`:**

```Cannot connect to the Docker daemon. Is the docker daemon running on this host?
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.sudo rpm -ivh docker-1.9.1-62.3.x86_64.rpm
2.docker info
3.

**Describe the results you received:**

i062683@mo-93f7030d0:~> sudo docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
**Describe the results you expected:**

ld8529:~ # docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.2
 Git commit:   a34a1d5
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.2
 Git commit:   a34a1d5
 Built:
 OS/Arch:      linux/amd64
**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
http://www.projectatomic.io/blog/2015/06/notes-on-fedora-centos-and-docker-storage-drivers/

Basically, don't use loopback devices.
The default devmapper config does this for making it easy to get up and running, but is not meant for extended use.

**Comment by FlorianHeigl** [comment]
Seriously, this is just thoughtless.
If it errors out on start _due to_ the default configuration on major providers, then the advice should not be "don't use loopback devices"
You can try - for example - "we might need to have a fallback" or any other thing that makes the daemon at least able to start.
A default config might be suboptimal for longer use, but in the VERY LEAST, there's a missing dependency, a missing test, or a misleading message.
So there is room for improvement.

**Comment by cpuguy83** [comment]
@FlorianHeigl This *is* the fallback.
Docker warns you about not using loopback devices constantly.
"Falling back" to something else is not workable because you will lose all data.

This is using devicemapper. Devicemapper still needs a device, which unless you configure a device for it to use and tell Docker about it, it will use a loopback device. Modprobing will not help here, Docker is already using both these things you mentioned.

**Comment by unixbhaskar** [comment]
Heck...
`
bhaskar@ArchLinux_18:28:35_Mon Oct 24:~>sudo systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2016-10-24 18:28:06 IST; 39s ago
     Docs: https://docs.docker.com
  Process: 31641 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 31641 (code=exited, status=1/FAILURE)

Oct 24 18:28:04 ArchLinux systemd[1]: Starting Docker Application Container Engine...
Oct 24 18:28:05 ArchLinux dockerd[31641]: time="2016-10-24T18:28:05.786865081+05:30" level=info msg="libcontainerd: new containerd process, pid: 31665"
Oct 24 18:28:06 ArchLinux dockerd[31641]: time="2016-10-24T18:28:06.137942666+05:30" level=error msg="There are no more loopback devices available."
Oct 24 18:28:06 ArchLinux dockerd[31641]: time="2016-10-24T18:28:06.137984814+05:30" level=error msg="[graphdriver] prior storage driver \"devicemapper\" failed: loopbac
Oct 24 18:28:06 ArchLinux dockerd[31641]: time="2016-10-24T18:28:06.138039969+05:30" level=fatal msg="Error starting daemon: error initializing graphdriver: loopback att
Oct 24 18:28:06 ArchLinux systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Oct 24 18:28:06 ArchLinux systemd[1]: Failed to start Docker Application Container Engine.
Oct 24 18:28:06 ArchLinux systemd[1]: docker.service: Unit entered failed state.
Oct 24 18:28:06 ArchLinux systemd[1]: docker.service: Failed with result 'exit-code'.

`

**Comment by Strubbl** [comment]
@unixbhaskar same here. did you solve that problem? how?

**Comment by rubo77** [comment]
A reboot didn't help me. 

I tried this: https://stackoverflow.com/a/51801626/1069083

But still, now I got a new error:

```
Error opening loopback device: open /dev/loop0: no such device or address
[graphdriver] prior storage driver devicemapper failed: loopback attach failed

```

**Comment by rung2kf** [comment]
Thanks, @Strubbl!  I just updated to the latest patches for Ubuntu 18.04.1 before I installed docker-ce 18.06.1, so rebooted my machine did create the loop devices automatically (there was no /dev/loop* prior to the reboot).  @rubo77, if you're still having problem, maybe you should undo the changes from Stackoverflow then reboot your machine.

**Comment by rubo77** [comment]
I solved it: https://stackoverflow.com/a/57212150/1069083

I had to install the latest version 19.0.6 and use pygrub in the VM so the kernel kan be modified inside the VM
