### ISSUE TITLE
volume driver RO/RW option passed to the plugins

### ISSUE THREAD

**Issue by tsaridas** [docker/docker#23051]
**Output of `docker version`:**

```
docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
docker info
Containers: 79
 Running: 3
 Paused: 0
 Stopped: 76
Images: 55
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 328
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local rbd rbd2
 Network: bridge null host
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.1 LTS
```

**Describe the results you received:**
There is no option being returned by docker volume concerning mount mode ( ro/rw )

**Describe the results you expected:**
The option to be passed to the 

VolumeDriver.Get
VolumeDriver.List
VolumeDriver.Mount

requests made to docker.

**Comment by cpuguy83** [comment]
That is because docker handles this mode.

**Comment by tsaridas** [comment]
@cpuguy83 the plugin handles how the volume is provided and need to know what kind of locks are needed. In ceph's case there are different locks. Wouldn't know how the rest of the filesystem plugin work.

**Comment by cpuguy83** [comment]
@tsaridas The backing store doesn't matter here. This is a mount level option (done at container runtime, not at volume creation). This is handled when docker mounts the provided path into the container.

**Comment by tsaridas** [comment]
@cpuguy83 I do understand what you are saying. What I'm asking though is the plugin to be able to see this value ( ro/rw ) so it can take the necessary actions.

**Comment by thaJeztah** [comment]
@tsaridas the mount mode options are a *runtime* config, not a property of the *volume*, but the way it is *mounted*, so it doesn't make sense to pass this to the volume driver.

Take for example;

```bash
docker volume create --name myvolume

docker run -v myvolume:/foo:rw -dit alpine sh
docker run -v myvolume:/foo:ro -dit alpine sh
```

Both containers share the same volume, but the first one has it mounted read-write, whereas the second one has it mounted read-only.

If a volume driver supports options to (for example) create a read-only volume, then those options should be passed through the `--opt` flag on `volume create`, e.g.

    docker volume create --opt is-readonly=1 --name myreadonlyvolume


I'm going to close this issue, because this is not something we'll implement, but feel free to comment after I closed

**Comment by tsaridas** [comment]
hello @thaJeztah ,
are the options ( --opt ) passed to the volume plugins ? 
If yes this can solve my problem in ceph rbd,

ro volumes - shared lock 
rw volumes - exclusive locks

**Comment by thaJeztah** [comment]
@tsaridas yes, the `--opt` options are driver-specific, and are directly passed on to the plugin;
https://github.com/docker/docker/blob/v1.11.1/docs/reference/commandline/volume_create.md#driver-specific-options

> These options are passed directly to the volume driver. Options for different volume drivers may do different things (or nothing at all).

**Comment by flaviostutz** [comment]
Sorry reviving this old thread, but I have the same requirements as the author and by the reading of the comments it was not really solved.

Docker volume plugins passes the "opt" fields only on "Create(Volume)" callback which is called during volume creation. When mounting a volume, "opt" fields are not available on "Mount" callback.

I created a plugin to provide Docker Volumes using Ceph RBD Images. During "Create" volume phase, there is no need to know whatever the volume will be mounted as "readonly", but during "Mount", I need to know if it is meant to be mounted as readonly because I want only one mount to have "write" access (the other concurrent mounts need to be readonly).

Sample scenario:
  1. docker run -d --volume-driver=cepher --name first --volume myvolume:/foo1 somecontainer
  2. docker run -d --volume-driver=cepher --name second --volume myvolume:/foo2 someothercontainer:ro

On the first "run", the plugin will be called for "Create", I create the image on Ceph, then, the plugin is called for "Mount". I mount the volume with write access and make locks on Ceph cluster. All right. 

On the second "run", the plugin will be called for "Created". I reuse the same Ceph Image, and then the plugin is called for "Mount". During mount phase, I would need the information about it being "readonly" (:ro) so that I can make the correct arrangements to check for the write lock and allow it to mount only if it was mounted with the "readonly" option.

I suggest the driver "opts" to be passed during the "Mount" callback of the volume plugin. 

Any ideas?
