### ISSUE TITLE
docker daemon -s overlayfs, Failed to connect to containerd, 

### ISSUE THREAD

**Issue by hanae2e** [docker/docker#23077]
**Output of `docker version`:**
ld8529:~ # docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.1
 Git commit:   9e83765
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.1
 Git commit:   9e83765
 Built:
 OS/Arch:      linux/amd64
```
(paste your output here)
```

ld8529:~ # docker daemon -s overlayfs
FATA[0000] Failed to connect to containerd. Please make sure containerd is installed in your PATH or you have specificed the correct address. Got error: exec: "docker-containerd": executable file not found in $PATH

**Output of `docker info`:**
ld8529:~ # docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-254:6-2016-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop2
 Metadata file: /dev/loop3
 Data Space Used: 11.73 MB
 Data Space Total: 107.4 GB
 Data Space Available: 1.443 GB
 Metadata Space Used: 581.6 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 1.443 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.03.01 (2016-01-25)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.12.51-52.39-default
Operating System: SUSE Linux Enterprise Server 12
OSType: linux
Architecture: x86_64
CPUs: 64
Total Memory: 504.9 GiB
Name: ld8529
ID: FFSR:FEUL:IY2F:QPCA:6HPD:UBCH:FFVL:LNCT:EMWL:XESU:45LL:MOSP
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support

```
(paste your output here)
```
ld8529:~ # docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-254:6-2016-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop2
 Metadata file: /dev/loop3
 Data Space Used: 11.73 MB
 Data Space Total: 107.4 GB
 Data Space Available: 1.443 GB
 Metadata Space Used: 581.6 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 1.443 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.03.01 (2016-01-25)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.12.51-52.39-default
Operating System: SUSE Linux Enterprise Server 12
OSType: linux
Architecture: x86_64
CPUs: 64
Total Memory: 504.9 GiB
Name: ld8529
ID: FFSR:FEUL:IY2F:QPCA:6HPD:UBCH:FFVL:LNCT:EMWL:XESU:45LL:MOSP
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support

**Additional environment details (AWS, VirtualBox, physical, etc.):**

suse 12.1 enterprise

**Steps to reproduce the issue:**
1. systemctl stop docker
2. docker daemon -s overlayfs
3.

**Describe the results you received:**
ld8529:~ # echo $PATH
/sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/opt/MegaRAID/MegaCli:/opt/MegaRAID/storcli:/root/bin
ld8529:~ # whereis containerd
containerd: /usr/sbin/containerd

ld8529:~ # docker daemon -s overlayfs
FATA[0000] Failed to connect to containerd. Please make sure containerd is installed in your PATH or you have specificed the correct address. Got error: exec: "docker-containerd": executable file not found in $PATH

**Describe the results you expected:**
docker deamon run ok

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by HackToday** [comment]
it seems you have `devicemapper` enabled, while you want to use overlay ?

**Comment by hanae2e** [comment]
now the daemon cannot start correctly, because docker-containerd????

**Comment by HackToday** [comment]
you need to check if you have docker-containerd in your PATH, or it in other paths

**Comment by cpuguy83** [comment]
@hanae2e How did you install docker?
Docker is now comprised for 4 binaries, `docker`, `docker-contianerd`, `docker-runc`, and `docker-containerd-shim`

**Comment by thaJeztah** [comment]
@hanae2e you're running a version of docker that's packaged by SUSE, I happen to know that in those installs, `docker-containerd`, `docker-runc`, and `docker-containerd-shim` are explicitly excluded from `$PATH`, so manually starting docker probably won't work.

I suggest to report this use case in the SUSE issue tracker. I'll close this issue here, but feel free to comment after I closed

/cc @cyphar

**Comment by hanae2e** [comment]
this does install in SUSE, does anyone knows if there is a workaround to fix it????

**Comment by thaJeztah** [comment]
@hanae2e you can create a [`/etc/docker/daemon.json`](https://docs.docker.com/engine/reference/commandline/daemon/#daemon-configuration-file) configuration file containing;

```json
{"storage-driver":"overlay"}
```

Then start the daemon the regular way (`sudo systemctl start docker`). That should make the daemon use `overlay` instead of the default (`devicemapper`). Assuming the systemd unit file doesn't have the `devicemapper` driver explicitly set

**Comment by cyphar** [comment]
@hanae2e Where did you get this Docker package from? We haven't released Docker 1.11.1 to our customers yet. Can you please file a bug through the usual channels (since it appears you're using the Containers module).

/cc @flavio

**Comment by thaJeztah** [comment]
(OT) @cyphar are there plans to use `daemon.json` as well for configuration? Looking if we can standardize on configuration

**Comment by hanae2e** [comment]
ld8529:~ # docker daemon -s overlayfs --containerd /var/run/containerd/containerd.sock
ERRO[0000] Failed to GetDriver graph overlayfs /var/lib/docker
FATA[0000] Error starting daemon: error initializing graphdriver: driver not supported

![image](https://cloud.githubusercontent.com/assets/7993352/15627680/06399af0-251e-11e6-9a97-e671721cde6f.png)
![Uploading image.png…]()

**Comment by cyphar** [comment]
@thaJeztah Possibly. The reason we use `/etc/sysconfig/docker` is because every other SUSE package uses that scheme for configuration (for consistency and historical reasons). We might be able to move to using `daemon.json` -- but we'd have to find a way to generate that config from `/etc/sysconfig/docker` (because that's what our customers are used to using and our AutoYaST setup tools assume all user configuration exists in `/etc/sysconfig/docker`).

**Comment by thaJeztah** [comment]
@cyphar makes sense. If there's anything you need for that, let me know

**Comment by flavio** [comment]
> ld8529:~ # docker daemon -s overlayfs

@hanae2e: this is a typo: the name of the storage driver is `overlay`.

Note well: this is available on SLE12 SP1 forward. SLE12 GA had the `overlayfs` kernel module, which is the precursor of the `overlay` kernel code that has been merged into the upstream kernel. The `overlayfs` kernel module *cannot* be used with docker because the code is quite different from the `overlay` one.

Also do not install tumbleweed packages on top a SLE system. Docker is available inside of the containers module. See the [quickstart](https://www.suse.com/documentation/sles-12/dockerquick/data/dockerquick.html) docs or even the [official docker docs](https://docs.docker.com/engine/installation/linux/SUSE/).

Take a look at [this](https://build.opensuse.org/project/repositories/Virtualization:containers) project on the [Open Build Service](https://build.opensuse.org/) if you want to get experimental (and hence unsupported) builds of Docker for SLE. Just make sure to pick the right repository.

Finally, I would recommend you to go through the official SUSE support channels.

**Comment by Bharathkumarraju** [comment]
Hi Team,

I am getting below error...

root@uklpauedm25a[PRD][devops] # systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2017-10-09 14:31:26 UTC; 5min ago
     Docs: http://docs.docker.com
  Process: 51192 ExecStart=/usr/bin/dockerd-current --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current --default-runtime=docker-runc --authorization-plugin=rhel-push-plugin --exec-opt native.cgroupdriver=systemd --userland-proxy-path=/usr/libexec/docker/docker-proxy-current $OPTIONS $DOCKER_STORAGE_OPTIONS $DOCKER_NETWORK_OPTIONS $ADD_REGISTRY $BLOCK_REGISTRY $INSECURE_REGISTRY $REGISTRIES (code=exited, status=1/FAILURE)
 Main PID: 51192 (code=exited, status=1/FAILURE)

Oct 09 14:31:26 uklpauedm25a systemd[1]: Starting Docker Application Container Engine...
Oct 09 14:31:26 uklpauedm25a dockerd-current[51192]: time="2017-10-09T14:31:26.647222596Z" level=fatal msg="Failed to connect to containerd. Please make ...in $PATH"
Oct 09 14:31:26 uklpauedm25a systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Oct 09 14:31:26 uklpauedm25a systemd[1]: Failed to start Docker Application Container Engine.
Oct 09 14:31:26 uklpauedm25a systemd[1]: Unit docker.service entered failed state.
Oct 09 14:31:26 uklpauedm25a systemd[1]: docker.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
root@uklpauedm25a[PRD][devops] #


and my service script as below..

```
[Unit]
Description=Docker Application Container Engine
Documentation=http://docs.docker.com
After=network.target
Wants=docker-storage-setup.service
Requires=rhel-push-plugin.socket registries.service
Requires=docker-cleanup.timer

[Service]
Type=notify
NotifyAccess=all
EnvironmentFile=-/run/containers/registries.conf
EnvironmentFile=-/etc/sysconfig/docker
EnvironmentFile=-/etc/sysconfig/docker-storage
EnvironmentFile=-/etc/sysconfig/docker-network
Environment=GOTRACEBACK=crash
Environment=DOCKER_HTTP_HOST_COMPAT=1
Environment=PATH=/usr/libexec/docker:/usr/bin:/usr/sbin
ExecStart=/usr/bin/dockerd-current \
          --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current \
          --default-runtime=docker-runc \
          --authorization-plugin=rhel-push-plugin \
          --exec-opt native.cgroupdriver=systemd \
          --userland-proxy-path=/usr/libexec/docker/docker-proxy-current \
          $OPTIONS \
          $DOCKER_STORAGE_OPTIONS \
          $DOCKER_NETWORK_OPTIONS \
          $ADD_REGISTRY \
          $BLOCK_REGISTRY \
          $INSECURE_REGISTRY\
          $REGISTRIES
ExecReload=/bin/kill -s HUP $MAINPID
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
TimeoutStartSec=0
Restart=on-abnormal
MountFlags=slave
KillMode=process

[Install]
WantedBy=multi-user.target

```

**Comment by thaJeztah** [comment]
@Bharathkumarraju looks like you're running the Red Hat fork of Docker, which is not maintained here; issues with that fork should be reported in the Red Hat issue tracker

**Comment by Bharathkumarraju** [comment]
@thaJeztah  yeah it is like some basic stuff it is missing


[devops] # ls -lrth /usr/bin/doc*
-rwxr-xr-x 1 root root  29M Jul 20 04:07 /usr/bin/dockerd-current
-rwxr-xr-x 1 root root 6.6M Jul 20 04:07 /usr/bin/docker-ctr-current
-rwxr-xr-x 1 root root 1.8M Jul 20 04:07 /usr/bin/docker-containerd-shim-current
-rwxr-xr-x 1 root root 7.5M Jul 20 04:07 /usr/bin/docker-containerd-current
lrwxrwxrwx 1 root root   32 Oct  9 14:31 /usr/bin/docker-storage-setup -> /usr/bin/container-storage-setup
[devops] #

**Comment by Bharathkumarraju** [comment]
@thaJeztah  i am just wondering what went wrong here if anyone knows it would be great relief for me for the day

**Comment by thaJeztah** [comment]
@Bharathkumarraju can't tell; the `docker-storage-setup` utility is not part of the official packages, only in the Red Hat packages

**Comment by Bharathkumarraju** [comment]
okay @thaJeztah  thanks for the hint..let me debug more on this

**Comment by Bharathkumarraju** [comment]
@thaJeztah ... i found the issue it is like i tried to remove yum package of docker using yum remove docker   and then i listed all the files which contains docker so it listed below files too...

```
/dev/mapper/rootvg-docker--pool
/dev/mapper/rootvg-docker--pool_tdata
/dev/mapper/rootvg-docker--pool_tmeta
/dev/rootvg/docker-pool

```

so what i did is ... locate docker| awk '{print $NF}' | xargs rm -rf .... so i think it might corrupted the if i am not wrong...so when i tried to install  again with yum install docker...it is throwing the error as i mentioned above.....is there anyway  can you help me to fix this?

**Comment by Bharathkumarraju** [comment]
These are blocked i removed accidentally all files which locate docker displayed for me

```
[mapper] # ls -l /dev/mapper/rootvg-docker--pool /dev/mapper/rootvg-docker--pool_tdata  /dev/mapper/rootvg-docker--pool_tmeta /dev/rootvg/docker-pool
lrwxrwxrwx 1 root root 8 Oct  9 23:32 /dev/mapper/rootvg-docker--pool -> ../dm-17
lrwxrwxrwx 1 root root 8 Oct  9 23:32 /dev/mapper/rootvg-docker--pool_tdata -> ../dm-16
lrwxrwxrwx 1 root root 8 Oct  9 23:32 /dev/mapper/rootvg-docker--pool_tmeta -> ../dm-15
lrwxrwxrwx 1 root root 8 Oct  9 23:32 /dev/rootvg/docker-pool -> ../dm-17
[mapper] # ls -l ../dm-17
brw-rw---- 1 root disk 253, 17 Oct  9 23:32 ../dm-17
[mapper] # ls -l ../dm-16
brw-rw---- 1 root disk 253, 16 Oct  9 23:32 ../dm-16
[mapper] # ls -l ../dm-15
brw-rw---- 1 root disk 253, 15 Oct  9 23:32 ../dm-15
[mapper] #

```

**Comment by cyphar** [comment]
@Bharathkumarraju Please report issues in Red Hat packages to the Red Hat issue tracker (**especially** if you have a RHEL subscription). If you are using the CentOS packages, report it to the CentOS issue tracker. Ditto for Fedora.

Also this is a more-than-one-year-old issue that was related to SUSE packages, which was incorrectly reported here and was resolved with us directly. If you are using a distribution's packages please **always** report it to that distribution first, and if they find that it's an upstream issue then you (or they) can submit an upstream bug report.

**Comment by eisenwj** [comment]
Dear Team,
     Don't know if this thread is still on maintenance, But I got the same problem -- docker 17.12.1 ce on sles12.4 --If anyone can show me what's wrong. It will be appreciated.
    I extracted docker-17.12.1-ce.tgz from download.docker.com and move all to /usr/bin/docker, then I added "/usr/bin/docker" to PATH -- 
docker:/tmp/installer # printenv|grep PATH
...
PATH=/usr/bin/docker:/sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games
...

    When I ran "dockered" manually, it looks all right. And then I edited /etc/systemd/system/docker.service -- 
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network-online.target firewalld.service
Wants=network-online.target

[Service]
Type=notify
ExecStart=/usr/bin/docker/dockerd -H tcp://0.0.0.0:2375 -H unix://var/run/docker.sock
ExecReload=/bin/kill -s HUP $MAINPID
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
TimeoutStartSec=0
Delegate=yes
KillMode=process
Restart=on-failure
StartLimitBurst=3
StartLimitInterval=60s

[Install]
WantedBy=multi-user.target

   And the "systemctl start docker" failed to start docker as daemon. The "journalctl -xe" reported this error --
Jan 06 12:00:36 docker dockerd[8884]: time="2022-01-06T12:00:36.970600345-05:00" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'R
Jan 06 12:00:36 docker dockerd[8884]: Failed to connect to containerd: exec: "docker-containerd": executable file not found in $PATH
Jan 06 12:00:36 docker systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jan 06 12:00:36 docker systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed

    But actually -- the "docker-containerd" IS in the $PATH... and I even copied it to /usr/bin, but still failed with same error. I really don't know what's the problem. Please kind help. Thanks

Regards
Eisen

**Comment by cyphar** [comment]
@eisenwj 

> But I got the same problem -- docker 17.12.1 ce on sles12.4 --If anyone can show me what's wrong.

We (SUSE) do not support such an old Docker version (that version is *five years old*). In addition, you pulled it from docker.com rather than the SLES Container Module repositories, which is also unsupported. The issue has been fixed in SLES for many years now, please just use the latest version of Docker we provide there.
