### ISSUE TITLE
iTerm3 incompatibility

### ISSUE THREAD

**Issue by mkowsiak** [docker/docker#23094]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64
```

**Output of `docker info`:**

```
docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 14
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 11
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.8-boot2docker
Operating System: Boot2Docker 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:36:45 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: EB2W:BISD:NRCS:YYWN:JNXN:Z36B:VMCX:FHGP:5L2I:VPWQ:M4MJ:T7ZX
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 29
 System Time: 2016-05-29T17:51:33.700571884Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Start iTerm2 (Build 2.9.20160523) - a.k.a. iTerm3 beta
2. Start Docker Quickstart Terminal
3. Nothing happens
4. Start iTerm2 (old version)
5. Start Docker Quickstart Terminal
6. Docker starts OK

**Describe the results you received:**

Docker didn't start

**Describe the results you expected:**

I wanted Docker to start

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
Thanks for reporting! Note that the Docker QuickStart terminal is part of Docker Toolbox, which has its own repository and issue tracker. This issue is already tracker in https://github.com/docker/toolbox/issues/427 and https://github.com/docker/toolbox/issues/348.

Having said that, you may be interested in Docker for Mac beta, which does not need the QuickStart Terminal, and works out of the box in any terminal, including the latest iTerm.

Read about the beta in this blog post https://blog.docker.com/2016/03/docker-for-mac-windows-beta/, and you can register at https://beta.docker.com

I'll close this issue here, because this is already tracked in the Docker Toolbox issue tracker, but feel free to comment here after I closed
