### ISSUE TITLE
Cannot share data between a Docker container and host system using volumes

### ISSUE THREAD

**Issue by abenmess** [docker/docker#23119]
Hello,
I cannot share data using volumes.
Here are my test:
$ mkdir data1
$ echo "Docker volume share" > data1/file1
$ docker run --privileged=true -v $PWD/data1:/opt/data1 -it debian cat /opt/data1/file1
cat: /opt/data1/file1: No such file or directory

The expected result is : Docker volume share 

Here is my conf
$ docker info
Containers: 31
 Running: 0
 Paused: 0
 Stopped: 31
Images: 17
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 205
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.8-boot2docker
Operating System: Boot2Docker 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:36:45 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.955 GiB
Name: boot2docker
ID: 5YYQ:2R3R:5NON:3KFO:7SOP:M62H:7LE5:TH5E:5LTF:72FE:RY33:RQOA
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 33
 System Time: 2016-05-31T09:03:53.350475141Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/

Could you help please ?

**Comment by thaJeztah** [comment]
Can you give the output of `docker version` as well?

Which directory are you running this from? This most likely is because the directory you're running from is not inside the `/Users` (OS X) or `C:\Users` (Windows) directory.

Docker Toolbox / Boot2Docker only shares those directories with the VM that docker runs in, anything outside of those directories is not shared with the VM, which results in docker creating an empty directory inside the VM, and bind-mounting that inside the container. See this section in the boot2docker readme; https://github.com/boot2docker/boot2docker/#virtualbox-guest-additions

**Comment by abenmess** [comment]
I am on Debian GNU/Linux 8 (jessie) 64 bits
$ uname -r
  4.5.0-0.bpo.1-amd64
$ pwd
/home/abenmess/docker/tmp

thank you in advance for your help

**Comment by thaJeztah** [comment]
But your output shows that the daemon is running on boot2docker, so I suspect you have a Virtual Machine installed with docker running in it? Is it set up to share host directories with the VM through guest additions?

Also, is there a reason to install docker inside a VM, and not directly on the host (Debian Jessie is able to run docker directly, so you don't need a VM to run it in; and it would give you far better performance)

**Comment by abenmess** [comment]
I followed the instruction in the https://docs.docker.com/machine/get-started/ as follow:
$ docker-machine create --driver virtualbox default
$ docker-machine env default
Otherwise how create machine and start deamon without virtualbox ?

**Comment by thaJeztah** [comment]
You can simply install docker on your Debian host, using the instructions here; https://docs.docker.com/engine/installation/linux/debian/, or using the "easy install script";

    curl -fsSL https://get.docker.com | sh

Before doing so, I recommend unsetting the environment variables that docker-machine set, otherwise your docker client may still try to connect to the docker daemon running in the VM;

    eval $(docker-machine env --unset)

**Comment by abenmess** [comment]
Thank you Sebastiaan van Stijn,
I advanced in my testing, by cons I have to use sudo in the run on the docker, here are my commands:
# add my user to docker group
$ sudo usermod -aG docker $USER
# Start the docker daemon
$ sudo service docker start
# I need to use sudo in the following command to access to the shared data described below
$ sudo docker run --privileged=true -v $PWD/data1:/opt/data1 -it debian cat /opt/data1/file1
Docker volume share

When i try to run without sudo, i have the following:
$ docker run --privileged=true -v $PWD/data1:/opt/data1 -it debian cat /opt/data1/file1
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.

Do you have an idea how to connect a docker (runned without sudo and by a user member of docker group ) to a deamon runned by sudo please ?

**Comment by thaJeztah** [comment]
You probably have to log out and in again to make sure you are in the docker group (after changing the user with usermod)

**Comment by thaJeztah** [comment]
looks like this was resolved. closing
