### ISSUE TITLE
Dcoker content trust - image pulled without signature verfication

### ISSUE THREAD

**Issue by sburnwal** [docker/docker#23250]
I am using docker 1.11 that has content trust in-built but I want to see a working case for enforcing signature validation during docker pull. As I understand, notary service sends the image public key over https to the docker pull client. However, I want to see this trust in action that is claimed in the docs https://docs.docker.com/engine/security/trust/content_trust/ (under pull images section). I am trying out these 2 approaches (see steps to reproduce) but none of these seem to be checking the trust/signature.

**Output of `docker version`:**
```
[root@positron-9 sburnwal]# docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**
```
[root@positron-9 sburnwal]# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-253:0-67109718-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 45.77 GB
 Metadata Space Used: 581.6 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.671 GiB
Name: positron-9.cisco.com
ID: JGSG:3QP5:A3YS:7RIT:G2IV:NKWF:2CWC:QW74:MZUB:YMM3:UDLV:HXIW
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: radiatejava
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS 7 host os.

**Steps to reproduce the issue:**
1. I am doing docker push for an image to a public docker repository with DOCKER_CONTENT_TRUST=1 and it correctly asks to me setup the root and repository keys. So I would believe these are signed in the repository. However, when I do docker pull for these images, I am able to pull both with and without enabling content trust while doing the pull on another machine. Is this a valid case ? Shall I be able to pull signed images without enabling content trust on pulling side ?

2. Next, I do docker push for an image to public repo DOCKER_CONTENT_TRUST=0 (trust disabled) and it correctly pushes the image without creating any keys. On another host however, I am able to pull the images from the repository again both with and without enabling content trust. Is this valid ? If I did not push with trust, how come I am able to pull with trust ?

**Describe the results you received:**
Even though on docker pull side content trust is enabled, I am able to download unsigned images.

**Describe the results you expected:**
Docker pull must validate signature and fail is the docker image is not signed.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
ping @cyli could you have a look at this?

**Comment by cyli** [comment]
@sburnwal:

> I am doing docker push for an image to a public docker repository with DOCKER_CONTENT_TRUST=1 and it correctly asks to me setup the root and repository keys. So I would believe these are signed in the repository. However, when I do docker pull for these images, I am able to pull both with and without enabling content trust while doing the pull on another machine. Is this a valid case ? Shall I be able to pull signed images without enabling content trust on pulling side ?

Yes, you should be able to pull with or without content trust enabled.  The signed data is additional metadata that lives next to the image.  The image is always pushed to the registry, so you can still pull it whether or not you have trust enabled.   Here is a table for whether things are pullable.

|                                       | pullable with trust | pullable without trust |
|--------------------------------| ------------------------ | --------------------------- |
pushed signed image      | yes                       | yes                            |             
pushed unsigned image  | no*                       | yes                            |

* if the unsigned image differs from any previously pushed signed images

The "no*" brings us to your next question:

> Next, I do docker push for an image to public repo DOCKER_CONTENT_TRUST=0 (trust disabled) and it correctly pushes the image without creating any keys. On another host however, I am able to pull the images from the repository again both with and without enabling content trust. Is this valid ? If I did not push with trust, how come I am able to pull with trust ?

So you can definitely pull images from repository again, with and without enabling content trust, but you might get different content depending on whether content trust is enabled.  

To see if there's a bug, I think we'd need more information about you on exactly which `docker push` and `docker pull` commands you ran, as well as the output.  

Here are two cases in which case a pull would and should succeed:

1.  You pushed the same data without content trust as you did previously with content trust, and so when you pull you get the same content both times.

	If you do:
	```
	$ export DOCKER_CONTENT_TRUST=1
	$ docker tag alpine myname/myrepo:latest
	$ docker push myname/myrepo:latest
	.... <successfully signed>
	```

	And then from a different machine:
	```
	$ unset DOCKER_CONTENT_TRUST
	$ docker push myname/myrepo:latest
	.... <successfully pushed without signing>
	```

	Then when you do `docker pull myname/myrepo:latest`, it will successfully pull without content trust because (see above explanation), and it will successfully pull *with* content trust because the same content had already previously been signed.  

2.  You pushed different data without content trust as you did previously with content trust, and you can still pull with content trust but you get your original data back instead of your new data.

	If you do:
	```
	$ export DOCKER_CONTENT_TRUST=1
	$ docker tag alpine myname/myrepo:latest
	$ docker push myname/myrepo:latest
	.... <successfully signed>
	```

	And then from a different machine:
	```
	$ unset DOCKER_CONTENT_TRUST
	$ docker tag ubunut myname/myrepo:latest
	$ docker push myname/myrepo:latest
	.... <successfully pushed without signing>
	```

	Then when you do `docker pull myname/myrepo:latest`:

		- with content trust: you will successfully pull down the previous image (`alpine`), because that was the one that was signed in the first time you pushed
		- without content trusts: you will successfully pull down the latest image (`ubuntu`, because that was the last one pushed)

Here is an example cases where a pull should fail:

If you do:
```
$ unset DOCKER_CONTENT_TRUST
$ docker tag alpine myname/myrepo:latest
$ docker push myname/myrepo:latest
.... <successfully pushed without signing>
```

Then when you do 
```
$ export DOCKER_CONTENT_TRUST=1
$ docker pull myname/myrepo:latest
```

This pull should fail, because there was no signed data to begin with.  But pulling without content trust enabled will succeed.

**Comment by sburnwal** [comment]
OK thanks for the update. I can see that unsigned images are not pulled when content trust is enabled.
