### ISSUE TITLE
Force containers to use cgroup-parent defined by Docker Daemon

### ISSUE THREAD

**Issue by HamidEDD** [docker/docker#23262]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

```

**Steps to reproduce the issue:**
1. docker daemon --cgroup-parent=/example/demo -D ....
2. docker run --cgroup-parent=/ ....

**Describe the results you received:**
**Describe the results you expected:**

I would like to make docker API available to a group of user with limited resources.
So i create a Cgroup (demo) for Docker and configure Daemon to use --cgroup-parent=/example/demo. But users could easily change this value when creating a container (docker run --cgroup-parent = /), and the container will be created outside the cgroup demo.

Is there a way to remedy this problem and force all containers to start within the cgroup's Daemon ?

Thank you.

**Comment by thaJeztah** [comment]
Docker doesn't have this built in (I.e. there's no built in feature to disallow certain actions, or have different "type" of users), however, you could limit access to the `--cgroup-parent` flag for `docker run` / `docker create` through an authorization plugin. See https://docs.docker.com/engine/extend/plugins_authorization/, and https://docs.docker.com/engine/extend/plugins/#authorization-plugins.

I'll close this issue, because having more fine-grained access control to the API is on the roadmap, although there's no ETA yet
