### ISSUE TITLE
Docker Bootstrap is missing when reboot

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [docker/docker#23448]
use this guide http://kubernetes.io/docs/getting-started-guides/docker-multinode/master/ to create kubernetes master.
setup flannel overlay network instead of docker0.
but when reboot the server, it restores to docker0, all things can't work.

**Comment by thaJeztah** [comment]
I think this may be because the network runs in a container, so may not be up yet. The setup described in that article is working around the standard way that docker works, and is not really supported, or recommended; I suggest to ask for assistance at the people that wrote that article; I see a slack channel is mentioned to get support.

I'm going to close this issue here because of the above, but feel free to comment after I closed
