### ISSUE TITLE
Breaking change in hostname validation in docker 1.12

### ISSUE THREAD

**Issue by alena1108** [docker/docker#23729]
In Rancher we've been following docker-compose format for naming containers "stackName_serviceName_number" ("foo_bar_1"). With docker 1.12 change for hostname validation, the containers can no longer be started due to "Invalid hostname format". 

@thaJeztah commented on https://github.com/rancher/rancher/issues/5195:

>Could you open an issue in the Docker issue tracker as well, to discus this? Although validating the hostname may be a good thing, possibly it's too much of a breaking change

**Comment by thaJeztah** [comment]
Thanks!

ping @docker/core-engine-maintainers, not sure if we should change, but think its good to have at least a quick look

**Comment by ibuildthecloud** [comment]
I completely understand why this change was done.  At Rancher we discussed removing support for `_` but backed off because users got to used to that format as a result of `docker-compose`.  The problem here is that the API never validated, it was just the CLI.  API doesn't have a deprecation cycle like the CLI because of the API versioning.  From that perspective it seems that this stricter hostname validation should only apply to the Docker v1.24 API.

**Comment by thaJeztah** [comment]
agreed, we should fix that before 1.12GA; Darren, do you have time to do a PR, or perhaps @vdemeester?

**Comment by vdemeester** [comment]
ah good point @ibuildthecloud :angel: 
@thaJeztah on it :wink:
