### ISSUE TITLE
Built-in help for Docker Registry isn't consistent

### ISSUE THREAD

**Issue by pcgeek86** [docker/docker#23749]
1. The `docker tag` command refers to `IMAGE[:TAG]` as well as `[REGISTRYHOST/][USERNAME/]NAME[:TAG]`, which I understand are essentially the same thing. 

2. The `docker pull` command refers to images as `NAME[:TAG]`, but doesn't specify how to reference an image in an alternate registry, like the `docker tag` command does. However, it does reference a `@DIGEST`. I'm not sure what that means.

I'm not sure if there are any other inconsistencies, but can we make sure there's some consistency in how image references are handled across Docker sub-commands?

![image](https://cloud.githubusercontent.com/assets/466713/16180545/7cb4af7a-3645-11e6-844a-f96066b6f464.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by stevvooe** [comment]
We should probably remove mentions of `[REGISTRYHOST/][USERNAME/]NAME[:TAG]`. From a grammar perspective, `[REGISTRYHOST/][USERNAME/]NAME == IMAGE`. Albeit, the distinction of `USERNAME` is only true for hub or other registries that dictate a naming scheme. The only thing the docker engine may interpret is a possible registry host, which can be hard to encode in a simple format. We can include something about how the image name can be used to interpret a particular registry host.

The `@DIGEST` portion is for pull by digest, which has no place in tagging, since that is a property of the image itself. However, this can be used to push and pull specific version of images.

I wouldn't say any of these outputs are really inconsistent, as these commands have different behavior. I think that `docker tag` may need some cleanup, but there is nothing wildly incorrect.
