### ISSUE TITLE
[FEATURE] Environment variable check on mac installation having DOCKER_HOST set

### ISSUE THREAD

**Issue by ss89** [docker/docker#23860]
I was just installing Docker on my Mac and had some trouble connecting to the daemon.
(Everything is solved now)
It would be a great feature if the installer checked whether the DOCKER_HOST env variable is set to something that would make docker unable to connect to the new local docker environment - at least a notice would be great.

**Comment by thaJeztah** [comment]
I think this will be hard to do, because having an environment variable set could be a valid configuration (for example, I have docker for Mac installed locally, but sometimes connect to a remote daemon)

Anyway, can you post this issue in the Docker for Mac beta forums? Docker for Mac, is a separate project, and doesn't use this issue tracker

https://forums.docker.com/c/docker-for-mac
