### ISSUE TITLE
Docker for Mac: inability to update proxy settings imported from OSX

### ISSUE THREAD

**Issue by roovo** [docker/docker#24033]
OS Version: Yosemite 10.10.5 (14F1713)
App version: 1.12.0-rc2-beta16 (build: 9493)

**Output of `docker version`:**
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Fri Jun 17 22:09:20 2016
 OS/Arch:      linux/amd64
 Experimental: true

**Steps to reproduce the issue:**
If I change the proxy settings in OSX system preferences I would expect these to be picked up by docker for mac and propagated to newly started containers.  This should either happen automatically on change or (probably better) via some interaction with the Docker for Mac application - perhaps through restarting it via the preferences panel.

**Describe the results you expected:**
Once docker for Mac has loaded the settings from OSX there seems to be no way to change them.  Even quitting docker for mac and restarting the mac does not force an update.  This makes it very inconvenient if you work some of the time behind a corporate firewall and some of the time out in the real world.

**Additional information you deem important (e.g. issue happens only occasionally):**

It seems that the proxy settings are cached in the docker for mac application database at:

~/Library/Containers/com.docker.docker/Data/database

which is a git repository. If I edit the proxy settings in the files in the proxy directory in this database:

~/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/proxy

then commit the changes the docker app reloads itself and picks up the changes and propagates them into new containers.

This isn't particularly convenient - but it works ;)

**Comment by maxx** [comment]
It would be great to see this as an option in the preferences gui, similar to how firefox does it:

(  ) No proxy
(  ) Use system proxy settings
(  ) Manual proxy configuration:

**Comment by thaJeztah** [comment]
ping @FrenchBen perhaps you know if this is on the roadmap?

**Comment by justincormack** [comment]
It is on the roadmap to do proxying from the host not from inside the containers, but there is quite a bit of work to do to get this in place, so not sure exactly when it will ship.

**Comment by samoht** [comment]
We have implemented what @maxx suggested in the last released Beta. Please try it out! :-)

**Comment by roovo** [comment]
Looking good - I've just had a go and it looks like it'll work for me - I'm seeing the proxy settings propagated to containers and can change them using the preferences - just what I needed -> many thanks.  I'll give it a go from behind the corporate firewall next week and report back here if I find any issues.

**Comment by Xorelock** [comment]
hello, I am also having a similar issue with corporate proxy.

output of docker version:
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

I tried navigating to ~/Library/Containers/com.docker.docker/Data/database/ to enact the fix @roovo had mentioned, but here i find only .git subdirectory. Here git status declares a list of files (seems like all files) are deleted. Is this perhaps the result of being on the stable version?

After accidentally getting stuck with an invalid proxy configuration and unable to modify it after the first time i set it, i was able to apply correct configuration by 'Uninstall/Reset' => restore factory defaults, and then applying them in the reset environment. Since i'm just trying to set up a new workstation laptop this is ok, but this will become an issue pretty quick once i have data in there i might care about persisting.

Hopefully the solution makes it out of beta soon, or @samoht if that beta was rolled into 1.12.1 then maybe there are still some unresolved issues.

**Comment by thaJeztah** [comment]
@Xorelock actually, I think this is in the current version, see https://docs.docker.com/docker-for-mac/networking/#/httphttps-proxy-support. Can you try if that works for you?

**Comment by ijc25** [comment]
@Xorelock 
> I tried navigating to ~/Library/Containers/com.docker.docker/Data/database/ to enact the fix @roovo had mentioned, but here i find only .git subdirectory. Here git status declares a list of files (seems like all files) are deleted. Is this perhaps the result of being on the stable version?

With newer versions of D4M you need to start with `git checkout master` to get a working tree.

However if you are running latest stable or beta then you shouldn't need to do any of that since the UI _should_ work (some recent betas had bugs in this area, but those should be fixed in beta29). If you are still having issues setting the proxy from the UI with the latest version on whichever branch you are running on then it would be best to open a new issue in against docker/for-mac by using the Whale menu "DIagnose and Feedback" to upload a diagnostics bundle.

@thaJeztah I believe the original issue reported here in beta16 has been long fixed (https://github.com/docker/docker/issues/24033#issuecomment-236367050 seems to agree). I think we should close this and deal with new issues in newer stable/beta separately.

**Comment by justincormack** [comment]
Closing. If you have further issues with this, please open a new issue at https://github.com/docker/for-mac/issues with exact details about what you did and what exactly is not working.
