### ISSUE TITLE
Daemon flags for swarm join

### ISSUE THREAD

**Issue by aluzzardi** [docker/docker#24087]
The engine should probably have flags such as `--swarm-join`. This would help automation.

/cc @icecrime @tonistiigi @tiborvass @stevvooe

**Comment by thaJeztah** [comment]
Agreed, ran into this trying to set up a docker-in-docker swarm cluster through docker-compose

**Comment by tianon** [comment]
+1 -- I built https://github.com/tianon/docker-dind-cluster/blob/2b43e6efc1aba32086337427085a1d1434510db7/docker-compose.yml with Swarm + Docker 1.11, but it's really hacky and hard-coded to three nodes so that it works and creates a cluster reliably.

The only other option (both with old Swarm and new Swarm) that I can come up with is to have some kind of hacky script which runs `swarm join` _after_ the daemon has started up, which is really fragile (and if anything goes wrong, the daemon is still running without any good indication that something happened).

Ideally, there'd be some way to specify the "Swarm master" node and the "Swarm join" via a daemon flag, and then `docker-compose scale docker=N` could be used to scale the cluster up and down dynamically (which is a heavily over-simplified example, but I think one which maps to "real" Docker instances just as well as it does for DinD).

**Comment by thaJeztah** [comment]
Closing for now, per https://github.com/docker/docker/pull/24770#issuecomment-248325444, but I'll open a new issue for tracking improvements for automated setup of a Swarm in general.

**Comment by thaJeztah** [comment]
opened https://github.com/docker/docker/issues/26743
