### ISSUE TITLE
Pass swarm task information as environment variables into each task

### ISSUE THREAD

**Issue by F21** [docker/docker#24110]
I am interested in running HDFS using swarm. One of the requirements of HDFS is a Zookeeper ensemble. To operate a Zookeeper ensemble, each Zookeeper should have a unique ID, starting from 1 and ending in 255.

While it is possible to coordinate the ids using something like consul or etcd, it would be much simpler for swarm to pass in task information as environment variables into each task. For example:

- `SWARM_TASK_ID`
- `SWARM_SERVICE_NAME`
- ...

These variables can then be used by the containers to simplify orchestration.

**Comment by yongtang** [comment]
I think this one is similiar to #23843?

**Comment by yongtang** [comment]
I can work on this issue, will create a pull request shortly. #dibs

**Comment by cpuguy83** [comment]
@yongtang I wouldn't work on this yet.
This is similar to the debate in adding the container ID to the container env.

**Comment by yongtang** [comment]
@cpuguy83 Thanks. I didn't know the discussion about container ID in container before. 

I will just un #dibs for now.

**Comment by AkihiroSuda** [comment]
@yongtang yes, my proposal  #23843 seems related, although  #23843 is the proposal for jobs rather than services.

@cpuguy83 Please share the issue tickets about adding the container ID to the container env?

**Comment by cpuguy83** [comment]
@AkihiroSuda I've looked, it's there I know... but github...

**Comment by thaJeztah** [comment]
I think you mean these;

https://github.com/docker/docker/issues/3506, https://github.com/docker/docker/pull/6481, and https://github.com/docker/docker/pull/7685

**Comment by AkihiroSuda** [comment]
@thaJeztah Thank you for the information.

Alternative idea for the original proposal https://github.com/docker/docker/issues/24110#issue-162893018

#### For `SWARM_TASK_ID`:
Considering the debate about the container ID env var, I think it is better to have a generalized approach rather than just having `SWARM_TASK_ID`  (as in `docker run -e FOO=BAR` instead of just having the container ID env var)

So I suggest implementing #23843
```
$ # I feel `--scatter` is better than `--per-completion-env`
$ docker service create --replicas 3 \
     --per-completion-env=ZKID=$(seq 1 3) \
     zookeeper
```

#### For `SWARM_SERVICE_NAME`:
I think we can just use `-e` (already implemented). No new feature needed.

```
$ docker service create --name foo -e SWARM_SERVICE_NAME=foo zookeeper
```

**Comment by stevvooe** [comment]
Task IDs are unique to the running task, so probably not useful here.

Considering that we don't have `CONTAINER_ID`, I don't see this happening.

I'll comment on #23843, but a better approach might be to support some sort of contextual templating across parameters. For example:

```
docker service create -e ZKID={{.Task.Slot}}
```

This would provide a lot more power and would require an awkwardly named flag.

**Comment by mcassaniti** [comment]
Adding #24113 to the list as well

**Comment by AkihiroSuda** [comment]
@stevvooe 
I think that approach is hard to implement because [`Task`](https://godoc.org/github.com/docker/engine-api/types/swarm#Task) is not determined at the time when [`ServiceCreate`](https://godoc.org/github.com/docker/engine-api/client#Client.ServiceCreate) is called.

I'm planning to open PR with another approach like this (using FUSE):
```
$ docker service create --inspection-fs /sys/docker .
$ docker exec -it foo cat /sys/docker/swarm/task/json
(task json goes here)
$ docker exec -it foo cat /sys/docker/container/json
(container json goes here as well)
```

WDYT?

Note: there had been similar discussion in https://botbot.me/freenode/docker-dev/2014-07-16/?msg=18090155&page=1 (for https://github.com/docker/docker/pull/6481)
```
vbatts
  SvenDowideit: though, having a /sys or /proc type access for inside containers would be interesting
SvenDowideit
  yeah, thats where i was pondering lately too
vbatts
  but imagine that would look hacky
  because some would need to be r/o, some could allow writes
  ick
SvenDowideit
  echo "inspect container" > /sys/docker/socket
vbatts
  SvenDowideit: curious
  or rather `cat /sys/docker/inspect`
  but still
SvenDowideit
  even nicer :)
...
```
cc @vbatts @SvenDowideit

**Comment by AkihiroSuda** [comment]
opened PR https://github.com/docker/docker/pull/24893

**Comment by stevvooe** [comment]
Thanks for the awesome POC. #24893 is a cool PR and we'll take a hard look at it. 

> I think that approach is hard to implement because Task is not determined at the time when ServiceCreate is called.

The evaluation of parameters can be delayed until execution time. In fact, this is required, since the context doesn't exist until then.

In general, an introspection API is an interesting idea but there are a number of considerations:

- A fuse based API creates runtime requirements, requiring a fuse server to be up that wouldn't required by other solutions, such as templating or static files. What if the fuse server goes down?
- Could it just be a readonly file system with static data?
- Is json the best format? It might be better to have the values directly accessible through the filesystem. Integrating with bash would be much easier if one doesn't have to parse json.
- Is it worth the extra coupling if all we need is an orchestrator assigned identifier?
- Is this only for static data?
- Do we make our applications less portable by having this? (obviously not, with the hdfs case)

I think if we take the time to develop a common context struct, then evaluate these solutions in the context of the... er.. context struct, it will make it a lot more clear which solution works. I'd start with something like this:

```go
type RuntimeContext struct {
  ContainerID string
  TaskID string
  ServiceID string
  NodeID string
  ClusterID string
}
```

Then, do we break this down hierarchically?

```go
type RuntimeContext struct {
  Container struct {
    Name string
    Labels map[string]string
    ID string
  }

  Task struct {
    ID string
    Name string
    Labels map[string]string
  } 

  Service struct {
    ID string
    Name string
    Labels map[string]string
  }

  Node struct {
    ID string
    Name string
    Labels map[string]string
    Hostname string // do we really want to expose this?

    Engine struct { /* ... */ } // information about the engine
  }

  Cluster struct {
    ID string
    Name string
  }
}
```

This context can then be mapped to several possible solutions:

- file system mappings
- env variable mappings
- template mappings

Put differently, the steps to design this are the following:

- Define the data structure which we'd like to inject into the container
- Decide the level of coupling we'd like applications to have with said data structure
- Evaluate the options of projecting that data structure into a container

**Comment by AkihiroSuda** [comment]
@stevvooe

Thank you a lot for the comment,

> A fuse based API creates runtime requirements, requiring a fuse server to be up that wouldn't required by other solutions, such as templating or static files. What if the fuse server goes down?

Actually I don't like the FUSE server as well :sweat: , so I'm considering removing the server and just mount a real filesystem, and put JSON files to the filesystem periodically (per N seconds specified by a config).

@justincormack also expressed his concern about FUSE because it is not available in non-Linux (I think he means Windows. Actually there is [dokany](https://github.com/dokan-dev/dokany), but it needs a kernel mode driver) https://github.com/docker/docker/pull/24893#issuecomment-234361695

> Could it just be a readonly file system with static data?

It's read-only, but should not be considered static. 
For example, `/dev/docker/container/json` can have dynamically-updated label values (https://github.com/docker/docker/issues/21721, https://github.com/docker/docker/pull/18958) in future releases.
Such dynamic data cannot be supported by the `-e ZKID={{.Task.Slot}}` approach.


> Is json the best format? It might be better to have the values directly accessible through the filesystem. Integrating with bash would be much easier if one doesn't have to parse json.

Makes a sense :smile:

> Is it worth the extra coupling if all we need is an orchestrator assigned identifier?

You mean using `RuntimeContext` rather than directly using `engine-api/types`?
I'm :+1: for it.

> Is this only for static data?

No

> Do we make our applications less portable by having this? (obviously not, with the hdfs case)

I don't think it makes apps less portable.

**Comment by stevvooe** [comment]
> Such dynamic data cannot be supported by the -e ZKID={{.Task.Slot}} approach.

Untrue. You just make a new container.

> I don't think it makes apps less portable.

It does. Apps that integrate directly with some disk layout will be tied to that version of the data layout. If all you need is some particular value for an application, it is much more portable to populate an application defined env variable with a value from the context than to integrate with an introspection API.

**Comment by mcassaniti** [comment]
This is my first exposure to the Docker development community and it's great to see the pace and quick responses from people. I personally agree that longer term it would be ideal to implement a file system approach with one file per key. I would suggest a read-only bind mounted file system where Docker holds some form of local per-container directory, and updates the contents. This means that the bind mount is read-only with respect to the container, but not Docker. I assume that the Docker engine can receive an event whenever the labels, name or other meta-data change for a container or a container's service while it is live. I would think that the event notifications could be added if this sort of event information isn't available already. Since Docker is updating the FS, the container should be able to use inotify when the Docker engine makes changes.

The argument against portability when using an FS containing this information is an interesting one. In my mind it is similar to the EC2 cloud-init process available for VMs. In this case the data is available via an FS rather than a URL. If the FS implementation was created in Docker somewhat as a PoC and then standardised with [OCI](http://opencontainers.org) would it then be a portability problem? I would suggest not using /dev/docker but rather something like /dev/container-env. If you're worried about versioning, cloud-init had this problem as well. It seems to be easy enough to work around.

My thoughts are a tree like:
  * /dev/container-env
  * /dev/container-env/_API-ver_
  * /dev/container-env/_API-ver_/engine (essentially docker --version)
  * /dev/container-env/_API-ver_/stack (directory won't exist if this container wasn't run under a service/swarm/stack)
  * /dev/container-env/_API-ver_/stack/name
  * /dev/container-env/_API-ver_/stack/id
  * /dev/container-env/_API-ver_/stack/labels
  * /dev/container-env/_API-ver_/stack/labels/_label1_
  * /dev/container-env/_API-ver_/container/name
  * /dev/container-env/_API-ver_/container/id
  * /dev/container-env/_API-ver_/container/task-id (Empty if not part of a service/swarm/stack. Contains the number after the service name e.g.: If conatiner name is _service_.1.xxxxxxx, the value in this file will be 1)
  * /dev/container-env/_API-ver_/container/labels
  * /dev/container-env/_API-ver_/container/labels/_label1_

**Comment by AkihiroSuda** [comment]
@stevvooe


>> Such dynamic data cannot be supported by the -e ZKID={{.Task.Slot}} approach.

> Untrue. You just make a new container.

In my understanding https://github.com/docker/docker/issues/21721 will support adding a label to a running container, rather than making a new container.

>> I don't think it makes apps less portable.

> It does. Apps that integrate directly with some disk layout will be tied to that version of the data layout. If all you need is some particular value for an application, it is much more portable to populate an application defined env variable with a value from the context than to integrate with an introspection API.

@mcassaniti 's proposal (`API-ver`) can improve portability.

**Comment by AkihiroSuda** [comment]
@mcassaniti

:+1: for one-file-per-key and read-only bind mount.

But I think the information are Docker-specific and out of scope of OCI.

**Comment by AkihiroSuda** [comment]
Comparison table for several approaches in https://github.com/docker/docker/pull/24893#issuecomment-234919630
(Can we move the discussion to #24893? )

**Comment by mgoelzer** [comment]
Closing because we won't be creating any environment variables by default.  But https://github.com/docker/swarmkit/pull/1650 will allow you to do this yourself.
