### ISSUE TITLE
`docker swarm inspect` and `docker info` inconsistencies

### ISSUE THREAD

**Issue by aluzzardi** [docker/docker#24148]
Both `docker info` and `docker swarm inspect` display information regarding the swarm.

They do so in a different way.

There are also other inconsistencies in `swarm inspect` (#23689, #24122).

/cc @stevvooe @aanand @dnephin @tonistiigi

**Comment by tiborvass** [comment]
I suggest we replace `swarm inspect` with `swarm info` because it does not expect an argument.
It should be pretty by default, and maybe add `--json` flag, although I would prefer not having it for 1.12 and adding it to both `swarm info` and `info` in a later release.

This means that `--pretty` could remain on `node inspect` and `service inspect`, even though i would expect `--pretty` be added in a later release to `volume inspect` and `network inspect` and `inspect`.

**Comment by tiborvass** [comment]
We could also add this information to `docker info` and remove `swarm inspect` altogether to stay future proof (in the case there will be multiple swarms to inspect).

**Comment by minzhang28** [comment]
Voting for removing `swarm inspect` as :
- It's not following the conventions as docker inspect, docker-machine inspect
- It's only showing the current swam info

**Comment by tiborvass** [comment]
We decided to remove `swarm inspect` altogether and just add swarm-specific information to `docker info`. We need to find a way of merging the existing swarm information in docker info, with the one in `swarm inspect` currently.

Any takers?

**Comment by vdemeester** [comment]
@tiborvass I can take a look at it tomorrow morning :angel: :fr:

**Comment by aluzzardi** [comment]
SGTM
