### ISSUE TITLE
`docker inspect <task>` is inconsistent

### ISSUE THREAD

**Issue by aluzzardi** [docker/docker#24150]
1.12 adds `docker inspect` support for tasks (along with the already included support for containers and images).

This is inconsistent.

Either we allow `inspect` to inspect all Docker objects (services, networks, ...) or we remove support for tasks in `docker inspect`.

It is essential for tasks to be inspected in order to make the swarm operable. Therefore, if we remove support in `docker inspect`, we have to find a new home.

/cc @dnephin @aanand @tiborvass

**Comment by dnephin** [comment]
`docker service inspect TASK`

**Comment by aluzzardi** [comment]
See also: https://github.com/docker/docker/pull/23614

**Comment by vdemeester** [comment]
As commented on #23614, I do agree that either we make `docker inspect` taking all "object" that can be inspected or we *kinda* deprecate it (and thus removing tasks from it, keeping image and container for backward compatibiliy).

And I'm definitely leaning forward make them all separate (i.e. `docker node inspect`, `docker volume inspect`, in the future `docker image inspect`, …). On Tasks I wonder though : `docker task inspect` ? I feel like `docker service inspect TASK` is a little bit confusing – what is the difference with `docker service inspect SERVICE` then ?.

**Comment by tiborvass** [comment]
I'm closing this since we have no choice because we don't want to introduce a new task command, but we do need a way to get information about a task to get the container ID, and we decided not to make the container ID be equal to the task ID.

**Comment by jatin665** [comment]
You can inspect a task for service by setting the experimental mode to true.

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

You can enable the experimental mode by using the command:
` vim /etc/docker/daemon.json`

Then add the following in the json :
```
{ 
    "experimental": true 
}
```

After saving the file restart the docker:
`systemctl restart docker.service`

You can then be able to inspect the task.

**Comment by thaJeztah** [comment]
@jatin665 docker swarm services is no longer experimental, so there should not be a need to enable experimental mode for this

**Comment by thernstig** [comment]
@tiborvass or @thaJeztah Could you explain why this was closed? It is confusing. And does not follow Docker's "new" way of grouping commands.

Documentation suggests that most/all commands are being moved to the top level "Management Commands" i.e. `docker container`, `docker service`, `docker image` etc.

If you want to check the logs of a task, you have to issue:
`docker service logs <TASK-ID>`

But the same command is (naturall) used to check service logs:
`docker service logs <SERVICE-ID or SERVICE-NAME>`

Now, since checking tasks in various ways is put under the `docker service` level, why can one not inspect a task under here? **Especially** since `docker inspect` (and all top-level commands) are not recommended anymore.
