### ISSUE TITLE
`docker service tasks` doesn't feel right 

### ISSUE THREAD

**Issue by aluzzardi** [docker/docker#24152]
It's the only command where users are confronted with the concept of tasks directly.

We used to have `docker service ps` and I think I preferred that UX.

There's still time to change - thoughts?

/cc @nathanleclaire @aanand @dnephin @icecrime @vieux

**Comment by dnephin** [comment]
I like `tasks`, it's short for `ls-tasks`, which we could add as an alias.

`ps` is misleading. It implies you're looking at containers, which is confusing. `docker ps` should also be renamed to `docker container ls` for consistency with other objects, so we shouldn't add more `ps` commands.

**Comment by jhorwit2** [comment]
While we are on the subject of that command :).

I'm not sure the reasoning, but it would be nice if the ID for a task was the container id. Then `ps` would make sense and it would be easy to connect service tasks to running containers. Since container IDs are already unique it cleans up the name (no uid at the end of a task name) and keeps a common id between the two. 

Also, `DESIRED STATE` isn't very clear to me at least. I'd think desired state would always be running? Not sure why it went to accepted after a stop either. 

```
$ docker service tasks test
ID                         NAME    SERVICE  IMAGE  LAST STATE             DESIRED STATE  NODE
bfeobguo2zezsfitqj1lea6se  test.1  test     nginx  Running About an hour  Running        moby

$ docker stop 44e495afc593
44e495afc593

$ docker service tasks test
ID                         NAME    SERVICE  IMAGE  LAST STATE          DESIRED STATE  NODE
9vuo55d3k4zysl8mp3lhao7zs  test.1  test     nginx  Accepted 2 seconds  Accepted       moby

$ docker service tasks test
ID                         NAME    SERVICE  IMAGE  LAST STATE         DESIRED STATE  NODE
9vuo55d3k4zysl8mp3lhao7zs  test.1  test     nginx  Running 7 seconds  Running        moby
```

**Comment by shykes** [comment]
The confusing part is not the name of the command, it's the fact that users have to deal with tasks, which have different IDs than containers.

If you want to use `ps` then you would have to lookup containers internally amd show that. Tasks would only be shown to advanced users.

**Comment by jhorwit2** [comment]
I agree. The complexity of tasks seems pretty unneeded for just deploying app containers. Ive found explaining the service -> task -> container concept to people to be a bit confusing since a task is basically a container but not really. You can view tasks but that doesnt help you know the containers without another step. It seems containers are a second class citizen in the new service service/task setup (weird to say bc containers are tasks but you have less power compared to docker run in some regards).

I definitely think what tasks and the scheduler can offer is pretty cool but definitely seems for advanced use cases.

**Comment by dnephin** [comment]
The distinction between a task and a container is important. Tasks are visible from any engine that is a swarm mode manager. Containers are only visible from the single engine that is running the container. If you make tasks look like containers you end up in a weird situation where you're told about a "container" `abc`, but if you try to run any container command on them (`docker rm abc`, `docker stop abc`, etc), it just fails saying "no such container", because the container is actually on a different engine.

**Comment by jhorwit2** [comment]
That brings up a really good point thats tracked in another ticket. Lets say i have a task acting bad and it needs a restart. Now i have to find the task, find the container and the node its on then run the docker command on that node to stop the task so the scheduler will make another one. 

If ids converged between tasks and containers you could the use metadata in the id (first byte or something says the type) to know this docker command request is a task then send the command to the appropriate node after looking it up. This works for nonswarm also bc the metadata will say its not a task so it will execute on the current host. Then as a user i dont even care about the distinction between tasks and containers.

**Comment by dnephin** [comment]
> Lets say i have a task acting bad and it needs a restart

The idea is that you shouldn't ever need to do that. The orchestration should know that it's not working and kill the task for you. With the right healthchecks and proper resource limits on the service you shouldn't ever need to kill the task directly.

> send the [container] command to the appropriate node after looking it up

I don't think that's currently possible, and I believe it would be a significant change.

**Comment by jhorwit2** [comment]
Correct me if im wrong but if a task fails a healthcheck its only going to be taken out of the pool of tasks to get requests. What if my task gets in a bad state and eats up 100% cpu because of a infinite loop? Bad health check wont do anything there. 

Yea i wasnt sure the required change for that one. Just an idea.

**Comment by aluzzardi** [comment]
Related to #24241

`service ps` would make much more sense at that point. Only advanced users would need to know about tasks.

**Comment by tiborvass** [comment]
@aluzzardi could we have the list of tasks in `service inspect` ?

**Comment by stevvooe** [comment]
@tiborvass This is basic functionality. It should be `docker service ps`.

I'm going to put together a proposal tomorrow.

**Comment by stevvooe** [comment]
I went to go make a change here to `docker service ps` and found we also have the equally incorrect commands of `docker node tasks` and `docker stack tasks`. I am not sure how we got this so wrong.

There seems to be a fundamental misunderstanding of the concept of tasks in the UX/UI design. These need to be replaced with a top-level `docker tasks` command to meet these use cases.

**Comment by mrvrbabu** [comment]
Hi, 
I have a service 'webby' which gets listed when I run 'docker service ls'. 
But I dont get to see the tasks when I run 'docker service task webby'. 
Anything that I am missing ? 

--snip--

[root@manager1 ~]# docker service ls 
ID            NAME   REPLICAS  IMAGE                               COMMAND
9tkmo740fzeq  webby  5/5       nigelpoulton/pluralsight-docker-ci  
[root@manager1 ~]# docker service task webby

Usage:	docker service COMMAND

Manage Docker services

Options:
      --help   Print usage

Commands:
  create      Create a new service
  inspect     Display detailed information on one or more services
  ps          List the tasks of a service
  ls          List services
  rm          Remove one or more services
  scale       Scale one or multiple services
  update      Update a service

Run 'docker service COMMAND --help' for more information on a command.
[root@manager1 ~]# 

--snip--

**Comment by mrvrbabu** [comment]
I believe the replacement command for 'docker service task webby' is 'docker service ps webby' which is almost working in the similar fashion.
