### ISSUE TITLE
Include Docker Compose in the official PPA

### ISSUE THREAD

**Issue by alexanderadam** [docker/docker#24210]
First of all, Docker has an [official Ubuntu repository / PPA](https://docs.docker.com/engine/installation/linux/ubuntulinux/#DocumentationText) which is great! :+1: 
And compose is a part of Docker, which is great too.

However, compose seems not to be available via the repository which means that Docker can be updated together with all other system components whereas the upgrade mechanism for Docker Compose is installing yet another package manager (pip) and remembering updating compose separately or, even worse, download the script manually.

Not to say that this way [the documented / recommended way](https://docs.docker.com/compose/install/) is mention anything about checking content / hashsums and lead will to outdated Docker Compose installations (it still states you should install version 1.6.2).

So it would be wonderful if the Repository would contain the official Docker tools which includes Compose too.

**Comment by thaJeztah** [comment]
There's an issue tracking this in the docker compose issue tracker https://github.com/docker/compose/issues/2235 (I see you already commented on that); I agree that it would be good to have packages for docker compose as well, but first of all, docker compose should have tooling in place to actually build deb/rpm packages, and may require some changes in the tooling for updating the apt and yum.dockerproject.org repositories.

I'm closing this issue for now, because this requires docker compose to build deb and yum packages first (https://github.com/docker/compose/issues/2235)

**Comment by franklinyu** [comment]
Excuse me but what's the tooling required, now that Debian [has already been distributing it by deb](https://packages.debian.org/stretch/docker-compose)?

**Comment by thaJeztah** [comment]
The deb package you're linking to is built by debian, and (as you can see) not updated to a current version.

 The tooling I referred to, is that the docker compose project/team needs to have a build system in place to build packages for all distros and platforms, which  is currently not the case 

Please continue the discussion on the issue I linked to (https://github.com/docker/compose/issues/2235) because docker compose is maintained in that repository, not here

**Comment by alexanderadam** [comment]
This point has to be mentioned here as you answered here as well:

> The tooling I referred to, is that the docker compose project/team needs to have a build system in place to build packages for all distros and platforms, which is currently not the case

But docker/moby itself is distributed as well in these distributions so I guess there is some kind of toolchain already?
And there are packages for all [distributions docker provides repositories for](https://pkgs.org/download/docker-compose).

So for me (disclaimer: I have _absolutely no_ idea how your current tooling for packaging the docker packages work) it sounds that everything seems to be available _somewhere_. Just not integrated in the docker/moby repositories.

**Comment by thaJeztah** [comment]
> But docker/moby itself is distributed as well in these distributions so I guess there is some kind of toolchain already?

Same applies to those ("docker") packages; they are built/packaged by downstream distributions. While convenient to use those for installing Docker (or Docker Compose), in many cases those packages are not kept up-to-date, sometimes are severely modified (for example, the CentOS, Fedora and Red Hat packages are a _fork_ of docker, and behave completely different than a vanilla docker install).

As you can see in that list, the version of docker compose shipped in those repositories varies greatly; some are almost three year old versions.

Anyway, please continue in the other issue, because the Docker Compose maintainers are not watching this repository, so any comment left here won't reach the right people.

I'm locking the conversation here to prevent the discussions from diverging
