### ISSUE TITLE
Worker is able to join twice

### ISSUE THREAD

**Issue by mgoelzer** [docker/docker#24228]
#### Summary

In a two-node cluster, I am getting into a state where the one worker node is erroneously reported as having joined the cluster twice:

```
ubuntu@ip-192-168-33-10:~$ docker node ls
ID                           HOSTNAME          MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
6jjvdt26ht5goi1eqdl0vbmb7    ip-192-168-33-20  Accepted    Ready   Active        
7xj4w5iwl54m7uxd5clqizrlr    ip-192-168-33-20  Accepted    Ready   Active        
b1ggr9f8pce1yy6qe4v56rp8w *  ip-192-168-33-10  Accepted    Ready   Active        Leader
```

#### How to reproduce

(1)  Start with a single node at 192.168.33.10 and do `docker swarm init`

(2)  From second node at 192.168.33.20 do:

```
docker swarm join --listen-addr 192.168.33.20:2377 192.168.33.10:2377
Error response from daemon: Timeout was reached before node was joined. Attempt to join the cluster will continue in the background. Use "docker info" command to see the current Swarm status of your node.
```

(3)  The above failure was because of my firewall rules.  After opening up the necessary ports, I did a `leave`:

```
ubuntu@ip-192-168-33-20:~$ docker swarm join --listen-addr 192.168.33.20:2377 192.168.33.10:2377
Error response from daemon: This node is already part of a Swarm cluster. Use "docker swarm leave" to leave this cluster and join another one.
ubuntu@ip-192-168-33-20:~$ docker swarm leave
Node left the swarm.
```

and then repeated the original command:

```
ubuntu@ip-192-168-33-20:~$ docker swarm join --listen-addr 192.168.33.20:2377 192.168.33.10:2377
This node joined a Swarm as a worker.
```

(4)  Back on the manager, I see this:

```
ubuntu@ip-192-168-33-10:~$ docker node ls
ID                           HOSTNAME          MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
6jjvdt26ht5goi1eqdl0vbmb7    ip-192-168-33-20  Accepted    Ready   Active        
7xj4w5iwl54m7uxd5clqizrlr    ip-192-168-33-20  Accepted    Ready   Active        
b1ggr9f8pce1yy6qe4v56rp8w *  ip-192-168-33-10  Accepted    Ready   Active        Leader
```

#### version information

Distro is Ubuntu 15.10

```
$ docker version
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   691bbea
 Built:        Fri Jul  1 17:24:51 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   691bbea
 Built:        Fri Jul  1 17:24:51 2016
 OS/Arch:      linux/amd64

$ uname -a
Linux ip-192-168-33-20 4.2.0-41-generic #48-Ubuntu SMP Fri Jun 24 11:28:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment]
@mgoelzer I think this is a duplicate of https://github.com/docker/docker/issues/24088, could you have a look?

**Comment by mgoelzer** [comment]
@thaJeztah  Partly, yes, it appears so.  

But note how the node thought it was part of a Swarm after step (2) even though it failed to join.  (Is that our intended behavior?)  This part seems different from #24088.

**Comment by thaJeztah** [comment]
let me make this a P1, so that we don't forget to investigate if it's the same issue or different

**Comment by tonistiigi** [comment]
Could not reproduce with specifying wrong manager address. What were the firewall rules that were wrong and were they resolved before `swarm leave` was invoked? Network issues are not considered fatal and as the error message says it will continue to retry. But if it doesn't succeed before `swarm leave` there should not be an additional row.

**Comment by mgoelzer** [comment]
Let's keep it P2 for now.  If I can't repro and no one else reports this, we can close.

**Comment by abronan** [comment]
I can't reproduce this one either. I really do think it is a duplicate of #24088 looking at the reproduce steps, so let's move the discussion there instead.

Tonis explained why the node thought it was part of the Swarm as it was still trying to reach a Manager. In a sense it is similar to the scenario of joining as a Manager, we optimistically assume our role is `Manager` until we effectively reach another Manager and the node is registered into the raft memberlist. Here the node assumes it is part of a Swarm until it can reach the Manager. The duplicate entry is most likely a result of the misconfigured firewall rules, and the join went through while the response was blocked.

Doing a `docker swarm leave` solves the problem as the node falls back into standalone docker mode. The proper additional step in this case is to also issue a `docker node rm <node-ID>` to cleanly remove the entry in the store.

Additionally the output on step `4` is correct but because it was done right after the `docker swarm leave` and `docker swarm join`, the node was still listed as `Ready`. After some time though, it should detect the node as `Down`. Current step for that use case is to remove the duplicate entry (the node marked as `Down`) with `docker node rm`.

**Comment by mgoelzer** [comment]
Thank you @abronan .  Agree that it should be closed.  Appreciate your studying it.
