### ISSUE TITLE
Cannot build rpm for Fedora 24

### ISSUE THREAD

**Issue by tiborvass** [docker/docker#24235]
**Steps to reproduce the issue:**
1. `docker build -t docker .`
2. `docker run -it --privileged -v $(pwd)/bundles:/go/src/github.com/docker/docker/bundles -e DOCKER_BUILD_PKGS=fedora-24 -e DOCKER_GRAPHDRIVER=aufs docker hack/make.sh binary build-rpm`

**Describe the results you received:**
A built rpm in bundles/

**Describe the results you expected:**
At step:
```
RUN rpmbuild -ba \
        --define '_gitcommit 4949c95' \
        --define '_release 0.3.rc3' \
        --define '_version 1.12.0' \
        --define '_origversion 1.12.0-rc3' \
        docker-engine.spec
```
the following error:
```
error: line 89: Invalid version (epoch must be unsigned integer): %{epoch}:1.12.0-0.3.rc3.fc24: Requires(pre): docker-engine-selinux >= %{epoch}:1.12.0-0.3.rc3.fc24
```

Related to #23896

**Comment by runcom** [comment]
just a note, so, I don't know why `%{epoch}` is there because it's not a commonly used field and it's rarely used (it's used for downgrading packages already shipped into stable but other than that it's not to be *ever* used). Most likely, you won't never release a broken docker-engine-selinux and then downgrade it afaict.

I'm going to remove that epoch tag from the comparison and see how it goes

**Comment by runcom** [comment]
other than that I think I'll go and figure out why `%{epoch}` seems undefined (hence negative probably) - the removal of `%{epoch}` can be just used as a stop-gap for now I guess

**Comment by thaJeztah** [comment]
Was added in https://github.com/docker/docker/commit/df6d92837029411bd06c4541c08c20127ce8327e

**Comment by runcom** [comment]
Right, but you usually ship docker-engine and docker-engine-selinux at the same time and unless you're going to downgrade docker-engine-selinux in between 2 releases that tag isn't needed
