### ISSUE TITLE
Containers created by a Service should have their IDs set to the Task ID

### ISSUE THREAD

**Issue by aluzzardi** [docker/docker#24241]
This would make the UX much better.

/cc @stevvooe @dnephin @tonistiigi @shykes

**Comment by stevvooe** [comment]
The only issue with this is if we want to use tasks to re-exec in a particular container. Imagine that we no longer want to recreate a container every time, but just want to re-dispatch a task to reuse a context.

**Comment by dnephin** [comment]
I think this would make it difficult to inspect the task. Since we only have task inspect under `docker inspect`, if they try to inspect they may end up with the container output, or the task output, depending on which host they run the inspect.

**Comment by thaJeztah** [comment]
That's where the `--type` flag is for on `docker inspect`, but I agree it's awkward

**Comment by dnephin** [comment]
`inspect` was just an example, here's a better one (which assumes #24152 since this proposal was referenced as an supportive argument for that proposal):

```
$ docker ps

$ docker service ps
abcd123  nodeA...
abcd124  nodeB ...

$ docker inspect abcd123
# Shows the task

$ ssh nodeA inspect abcd123
# Shows the container

$ docker stop abcd123
Error: response from daemon: No such container: abcd123
```

User: 
* why does `docker service ps` show me docker "containers" that `docker ps` doesn't show?
* why do I get different output for `docker inspect` from different nodes on the same swarm?
* why can't I stop this container that I see in `docker service ps` ?

Tasks are an important detail, we can't hide them or it gets super confusing.

**Comment by tiborvass** [comment]
@dnephin so what are you suggesting?

**Comment by dnephin** [comment]
I'm suggesting we close this issue as wont-fix and don't make any changes. tasks and containers are separate objects, I think we make the UX worse by sharing an ID and partially conflating the two.

**Comment by icecrime** [comment]
I think I'm with @dnephin here: different objects, different ID sets.

**Comment by thaJeztah** [comment]
I'm ok with closing this then, but happy to get feedback from @aluzzardi

**Comment by icecrime** [comment]
I'm closing, but please @aluzzardi ping us if you strongly disagree :wink:
