### ISSUE TITLE
service create --mount documentation

### ISSUE THREAD

**Issue by jamespedwards42** [docker/docker#24277]
I have been unable to find any documentation or examples for the mount configuration option on the [docker service create](https://docs.docker.com/engine/reference/commandline/service_create/) command.  How do you express the source, target, driver and driver plugin specific options?

**Comment by tpbowden** [comment]
After reading the source I think it works like this. There might be other options too :
```
docker service create --mount target=<container file/directory>,source=<host file/directory>,type=<bind or mount>
```

**Comment by jamespedwards42** [comment]
@tpbowden What do you think about for the nested [VolumeOptions](https://github.com/docker/docker/blob/master/vendor/src/github.com/docker/engine-api/types/swarm/container.go#L36)? I'm trying to figure how to configure a [volume plugin](https://docs.docker.com/engine/extend/plugins/#/volume-plugins), e.g. VolumeOptions.driver=[gce](https://github.com/mcuadros/gce-docker),VolumeOptions.opts.SizeGb=100GB.

**Comment by stevvooe** [comment]
`--mount type=volume,target=<container file/directory>,source=<host file/directory>,volume-driver=<driver>,volume-opts=<k0>=<v0>,volume-opts=<k1>=<v1>`

**Comment by stevvooe** [comment]
There will be better documentation for this in the coming days.

**Comment by josear** [comment]
We are trying to mount nfs volumes but it's not working. This is the command we're using (well, one of them):

docker service create --name aName --mount type=volume,target=/insideContainer,volume-driver=local,volume-driver-opt=type=nfs,volume-driver-opt=device=nfs-server:/nfsServer redis

Any suggestion?

Btw, @stevvooe documented "volume-opts" but according to source code its "volume-driver-opt".

**Comment by DSTOLF** [comment]
Guys, I'm pretty new to docker and I'm building a test swarm with 1.12. I decided to use the RC because it seems to me it would be more productive to start with swarm mode integrated in the engine, instead of learning swarm standalone just to see it discontinued.

So, here's my test:
```
[dstolf@VINDOC701 docker]$ docker node ls
ID                           HOSTNAME                    MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
01h8iq4kxdlibdw9mdx394jd0 *  VINDOC701.dev1.stelo.local  Accepted    Ready   Active        Leader
510vgjvdvq9kk5ufpzb44p7iu    VINDOC703.dev1.stelo.local  Accepted    Ready   Active        
7oq0krop57wfebcgsr8t8bk4t    VINDOC702.dev1.stelo.local  Accepted    Ready   Active   
```

At VINDOC701, the manager, I try to start a service like this
`docker service create --replicas 1 --mount target=/data,source=/data,type=volume,writable=true --name teste alpine env\>/data/teste`

It keeps trying to run the service on all nodes indefenetely and I get the following error on :
`Jul  6 17:28:10 VINDOC702 dockerd: time="2016-07-06T17:28:10.244549274-05:00" level=error msg="Create container failed with error: oci runtime error: exec: \"env>/data/teste\": stat env>/data/teste: no such file or directory"`

Am I doing something wrong?? Or is it really a bug?

**Comment by DSTOLF** [comment]
Needless to say, /data exists on all nodes. Since it's just a POC, I have created a NFS share on the manager node and mounted it on the workers' node:
```

[root@VINDOC701 data]# df -kh /data
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda2       99G  1,3G   92G   2% /

[root@VINDOC702 ~]# df -kh /data
Filesystem         Size  Used Avail Use% Mounted on
10.150.9.14:/data   99G  1,3G   92G   2% /data

[root@VINDOC703 ~]# df -kh /data
Filesystem         Size  Used Avail Use% Mounted on
10.150.9.14:/data   99G  1,3G   92G   2% /data
```

**Comment by DSTOLF** [comment]
`type=bind` gives the same error, also.

**Comment by stevvooe** [comment]
@josear "volume-driver-opt" is correct. Thanks!!

Looks like you are expecting the `volume-driver-opt` parameters to be converted directly to mount parameters. Could you file a separate issue and cc me? It looks like there is a bug or gap in support.

@DSTOLF Look at the command you are trying to run. `env\>/data/teste` doesn't look like a valid command.

This issue is about documentation. Please file a separate issue, rather than hijacking others.

**Comment by DSTOLF** [comment]
@stevvooe Thanks, you are correct... I was trying to figure out if the problem I'm facing was with --mount or --env.

By using the command "touch teste", it worked and now I think the problem is with the environment variables.

Thanks.

**Comment by stevvooe** [comment]
@DSTOLF Great! If you have more problems, don't be afraid to file an issue!

**Comment by tiborvass** [comment]
@DSTOLF I consider `volume-driver-opt` being a bug. It should be `volume-opt`.

**Comment by stevvooe** [comment]
@tiborvass I was editing the comment for you...

**Comment by mastermindg** [comment]
It's been over a month and I don't see anything on docker service create. Maybe docker should think about opening up the docs to comments like PHP. The documentation there is so rich because of the wide community support.

**Comment by Illydth** [comment]
I hate to pile on, but I'd like to add my "me too" onto this.  The published docks give 0 reference to mounting volumes, linking containers or otherwise setting up something basic like a web proxy in front of web code in front of a database container.

I realize this is brand spanking new out the gate, but if I can't even create a basic service connection between a couple containers with persistent data in a semi-documented way, there's no way I can sell using this to any of my teams.

Which is a crying shame because this new swarm mode looks like it might just be the next greatest thing since sliced bread...or docker itself.

**Comment by cpuguy83** [comment]
@mastermindg docs are all available in this repo at `docs/` following the same basic url structure as the docs themselves, all in markdown.

**Comment by sfsmithcha** [comment]
@Illydth , @mastermindg ,

Thank you for your feedback. I'm working as quickly as possible to get usable documentation onto the docs site.

Please see https://docs.docker.com/engine/swarm/services/ for the current docs on `docker service create` including the syntax for using mounts with services.

There's a PR in progress for service discovery (which is how you'll network containers). https://github.com/docker/docker/pull/25420

There is a lot of content in the works. I'll try to move an example like you've suggested web proxy w/ a database backend to the top of the list.

**Comment by Illydth** [comment]
@sfsmithcha This may be the wrong place for this comment but on that page under the "add an overlay network" the first command creates a "my-network" while the second command seems to indicate the service will connect to a "my-multi-host-network" which doesn't seem to exist since the prior network was called just "my-network"?  I haven't tested this yet but was curious as to the name difference between the two commands.

**Comment by sfsmithcha** [comment]
Good catch, @Illydth , Normally you can file a separate docs issue so as not to conflate multiple issues. However, this was a quick fix, so I created a pr: https://github.com/docker/docker/pull/25506

**Comment by garthk** [comment]
I'm inching closer to an NFS mount, @josear:

```
docker service create \
  --mount type=volume,src=registrydata,volume-driver=local,dst=/data,volume-opt=type=nfs,volume-opt=o=addr=192.168.1.1,volume-opt=device=/data/registry \
  --name registry \
  --env STORAGE_PATH=/data \
  registry:2
```

The command succeeds, but the service fails. `docker.log` reveals:

```
time="2016-08-18T10:50:49.055888916+10:00" level=error msg="fatal task error" error="create registrydata: invalid option key: \"addr\"" module=taskmanager task.id=apzerxws454cqmxoa5kz3yuui 
```

**Comment by stevvooe** [comment]
@garthk You need to use the nfs server as the device:

```
--mount type=volume,src=registrydata,volume-driver=local,dst=/data,volume-opt=type=nfs,volume-opt=device=192.168.1.1:/your/nfs/path
```

The above will create the volume, if not created already, and mount it in the container  at `/data`.

If you've already mounted the nfs path on the target host, you don't need to specify the volume options. Just bind mount the directory:

```
--mount type=bind,src=/data/registry,dst=/data
```

**Comment by cpuguy83** [comment]
@stevvooe The kernel will not read the server address from device. The mount command actually translates `mount -t nfs 1.2.3.4:/foo /bar` into `mount -t nfs -o addr=1.2.3.4 :/foo /bar`
Which means a fairly unwieldy volume opt for us: `volume-opt=device=:/foo,volume-opt=o=addr=1.2.3.4`

Considering making a dedicated nfs driver built-in... but perhaps we don't want such a driver to be only a client.

**Comment by mgoelzer** [comment]
@sfsmithcha I think we should include in our docs some kind of an NFS recipe based on what @stevvooe and @cpuguy83 are writing above.  Let me know if I can help with this.

**Comment by stevvooe** [comment]
@cpuguy83 

> The mount command actually translates mount -t nfs 1.2.3.4:/foo /bar into mount -t nfs -o addr=1.2.3.4 :/foo /bar
Which means a fairly unwieldy volume opt for us: volume-opt=device=:/foo,volume-opt=o=addr=1.2.3.4

I scoured manpages yesterday and could find absolutely no mention of the `addr` option. Every example I found included the address in the device. Is this documented _anywhere_?

**Comment by cpuguy83** [comment]
@stevvooe I used strace to find out what it was doing. Could not find any docs.

**Comment by garthk** [comment]
Docker team, full props for technical ability, *and* I think you need to add "documented" to your definition of "done". It's a bit rude to claim credit for shipping it if nobody can use it. Also, strikes me we're tripping over corner cases you haven't taken into account. Someone testing your docs might well have found these *before* release.

**Comment by joonas-fi** [comment]
+1'ing just doesn't cut it, so here's my two cents:

I somehow understand that changing terminology and syntax from `-v` to `--mount` is justified in the longer run (hope you're going to be consistent by having a plan to change this also in `$ docker run ...`), but this shouldn't have been shipped unless it was documented properly. For crying out loud the CLI `--help` and online docs did not give me a damn clue.

There's something horribly wrong if I need to browse the issue database to find the correct syntax. Even in the other issue's (#23833) comments where this was mentioned got the syntax wrong (`type=bind,source=/path,dest=/path`) - was the syntax changed again or is this way too damn hard because nobody knows how to use the damn widget because the documentation is non-existent..

I respect the game-changing work your team is doing but I fully agree with @garthk's argument:

> you need to add "documented" to your definition of ‘done’. It's a bit rude to claim credit for shipping it if nobody can use it.

**Comment by Vanuan** [comment]
Here's a helpful blog post http://www.kendrickcoleman.com/index.php/Tech-Blog/how-to-use-volume-drivers-and-storage-with-new-docker-service-command.html

**Comment by cpuguy83** [comment]
@joonas-fi Thanks for pointing it out. You're right this should already be in the docs. Docs have definitely been a sore spot in terms of keeping them up to date, and even more so with the number of UX changes during the pre-release phase for 1.12. Definitely something to work towards to be better at.

Thanks @Vanuan for linking the post!

**Comment by frimdo** [comment]
Hi - I am here to ask for help, maybe it is issue, maybe I am doing something wrong. I am able to mount GlusterFS volume by creating container
```
docker run --name gluster --hostname=gluster -d --privileged=true --network=host gluster/gluster-centos 
```
And than mounting it by 
```
docker exec -it gluster mount -t glusterfs 81.2.252.144:/test /test
```
What I am failing to achieve is to mount the volume right into docker service using `--mount` flag. I tryed
```
docker service create \
  --mount type=volume,\
source=gluster_volume,\
volume-opt=type=gluster,\
volume-opt=device=:/test,volume-opt=o=addr=81.2.252.144,\
target=/test \
   gluster/gluster-centos
```
and 
```
docker service create \
  --mount type=volume,\
src=gluster_volume,\
volume-driver=local,\
dst=/test,\
volume-opt=type=gluster,\
volume-opt=device=81.2.252.144:/test \
  --name gluster-mounter \
   gluster/gluster-centos
```
and many similar commands.

**Comment by cpuguy83** [comment]
@frimodo this is not the right place to get support.
Please hop on #docker on IRC, forums.docker.com, or the docker community slack. Feel free to ping me on those.

**Comment by dhiraj-hadkar** [comment]
Hi all,
I am trying to redirect nodejs app logs from one container to another using service create command.
On host this is possible, but is it possible that say my logs are written in /myapp/logs/myaa.log in container 1 and i want it to be redirected to container 2 /containerlogger/ folder.


[root@manager ~]# docker info
Containers: 74
 Running: 1
 Paused: 0
 Stopped: 73
Images: 42
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-251:1-369099008-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 10.61 GB
 Data Space Total: 107.4 GB
 Data Space Available: 38.08 GB
 Metadata Space Used: 14.9 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.133 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: active
 NodeID: 3wod0p18btb30qxaqrsncmijz
 Is Manager: true
 ClusterID: 4d9ax6f3xpodnjkngtl3w2p0s
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.16.100.xxx
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.1.12-37.6.3.el7uek.x86_64
Operating System: Oracle Linux Server 7.2
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.583 GiB
Name: manager
ID: H6QT:BUG5:FLFV:NRZI:KGNQ:ZVL6:DUGQ:TERC:HUS6:ZV44:QMAK:T7CD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: dhirajh12
Registry: https://index.docker.io/v1/
Insecure Registries:
 172.16.100.xxx:5000
 127.0.0.0/8
 
 
 
 
 [root@manager ~]# docker version
 Client:
  Version:      1.12.1
  API version:  1.24
  Go version:   go1.6.3
  Git commit:   23cf638
  Built:
  OS/Arch:      linux/amd64
 
 Server:
  Version:      1.12.1
  API version:  1.24
  Go version:   go1.6.3
  Git commit:   23cf638
  Built:
  OS/Arch:      linux/amd64
 [root@manager ~]#

**Comment by thaJeztah** [comment]
@dhiraj-hadkar please don't use closed issues for support questions; the GitHub issue tracker is for tracking bugs and feature requests, and is not intended as a general support forum. Consider using;

- forums.docker.com
- the #docker IRC channel
- StackOverflow

**Comment by robertofabrizi** [comment]
@stevvooe Doing that only mounts the NFS on the master of the swarm nodes. Even if worker nodes have the nfs mounted, it's not inside the containers distributed on those.

**Comment by stevvooe** [comment]
@robertofabrizi Doing what? This issue is a year old, closed and there are a ton of comments. It is impossible to tell what you are talking about.

As far services go, you can dispatch a mount via a service to any node in the cluster, so these shouldn't be restricted to the managers.

Note that some of these comments were made before the feature even went GA, so the syntax have changed since. If there are bugs in the documentation, it is most helpful to file the bugs in the documentation project where we can get it correct, if there are still problems.
