### ISSUE TITLE
How to install docker engine without yum & apt-get 

### ISSUE THREAD

**Issue by balamsg** [docker/docker#24324]
Hi,
I am a newbie in this docker environment.So, can somebody tell me how to install docker without yum in RHEL 7.1 . Not able to get much info abt this in the google search. I have downloaded "docker-engine-1.10.0-1.el7.centos.x86_64.rpm" and "docker-engine-selinux-1.10.0-1.el7.centos.noarch.rpm" but still it says

warning: docker-engine-1.10.0-1.el7.centos.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 2c52609d: NOKEY
error: Failed dependencies:
libdevmapper.so.1.02(DM_1_02_97)(64bit) is needed by docker-engine-1.10.0-1.el7.centos.x86_64
libsystemd.so.0()(64bit) is needed by docker-engine-1.10.0-1.el7.centos.x86_64
libsystemd.so.0(LIBSYSTEMD_209)(64bit) is needed by docker-engine-1.10.0-1.el7.centos.x86_64

**Comment by justincormack** [comment]
You should be able to find the RPMs that contain those libraries from your RHEL repository and install them first. Otherwise you can download static binaries of docker see https://docs.docker.com/engine/installation/binaries/ but these do not have devicemapper support, which is the normal storage driver for RHEL systems.

**Comment by balamsg** [comment]
Thanks a lot justincormack !!
