### ISSUE TITLE
Ability to expose a name of a port

### ISSUE THREAD

**Issue by scottbessler** [docker/docker#2435]
With the new linking functionality I can see a desire to name a port when dealing with a container that exposes multiple ports, e.g. one for cassandra:

```
# gossip
EXPOSE 7000
# thrift
EXPOSE 9160
# jmx
EXPOSE 7199
```

If another container links to a running cassandra container it will currently have to hardcode these 3 ports in a config file / startup script. 

It would be useful if one could name/alias these exposed port+proto pairs to enable some useful link env variables (coupled with #2431 ):

In the Dockerfile:
```
EXPOSE 7000 gossip
EXPOSE 9160 thrift
EXPOSE 7199 jmx
```

In the client container
```
# DB is the link alias specified on container creation, gossip is the port alias from above dockerfile
DB_PORT_GOSSIP=tcp://172.17.0.2:7000
DB_PORT_GOSSIP_IP=172.17.0.2
DB_PORT_GOSSIP_PORT=7000
DB_PORT_GOSSIP_PROTO=tcp
```

Does this sound like something worth doing?

**Comment by cpuguy83** [comment]
Definitely better than port numbers in the env vars, but also env vars are really bad for this sort of thing anyway since once a container (or a process) is started, you can't change it's env except from in the process itself, which makes it bad for discovery.

In general I find the port numbers in the linked env vars to be useless because you must know already what ports you are connecting to to find out the port, and docker never changes these ports, they are exactly what is exposed by the image, which should always be the default port since each container gets it's own network stack.
I suppose naming these would mean you don't have to know what port the other one is listening on, just that you need to connect to a gossip port (for example).

Still, service discovery via env vars has turned out to be not so great.

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
