### ISSUE TITLE
[1.12] docker doesn't cleanup "faulty" service containers

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#24394]
When spinning up a service that fails to start, or exits within 10 seconds (so is considered not "up"), docker keeps spinning up new containers, without cleaning up failed containers, eventually leading to the node running out of resources.

To reproduce;

```
docker service create --name faulty --replicas 3 alpine sh
```

Then watch as the number of stopped containers keeps increasing:

```
watch docker ps -a
```

**Comment by tiborvass** [comment]
Related to https://github.com/docker/docker/issues/23704 and #23706

**Comment by stevvooe** [comment]
Tried this as of rc3. It looks the behavior is somewhat mitigated through the task history limit.

Create a bad service:

```console
$ docker service create --name redis ressteve
```

After a bit, we see we have several tasks:

```console
$ docker service tasks redis -a | wc -l                                                                                                                                                                                                                       
      11
```

This will stay stable at 10 tasks, since the default task history limit is 10 and we have one replica. If we don't like this limit, we can change it

```console
$ docker swarm update --task-history-limit 5                                                                                                                                                                                                                   
Swarm updated.
```

After a bit, we see the list has been truncated to 5 entries:

```console
$ docker service tasks redis -a | wc -l
       6
```

I also tried this with the following, to ensure this works for bad containers:

```console
$ docker service create alpine sh
```

Using docker ps, we see that we hold at 5 containers:

```
$ docker ps -a | grep angry | wc -l
       5
```

I changed the title, as this is not actually DOS.

This all works do to something called a "task assignment set" and the amount of history we keep for failed tasks. While new containers may be created after each failure, the total number is limited by the number of replicas per service times the task history limit. For example, if we scale to 10 replicas, we can see there are 5 (task history limit) * 10 replicas containers:

```console
$ docker service scale angry_volhard=10
angry_volhard scaled to 10
$ docker ps -a | grep angry | wc -l
      50
```

The main reason to have this level of control is to enable debugging a container. In cases where failures are very quick, this history limit will result in a situation where a target container may disappear, but it still allows some window.

Admittedly, I think swarmkit could probably backoff to reduce the rate at which new containers are created as failures are encountered.

**Comment by thaJeztah** [comment]
Thanks @stevvooe looks like it's not that big of an issue then; I just recalled the conversation we had earlier while talking with @tiborvass and did a quick test before opening this issue. Let me make this a "P3", as I don't think this should be a show-stopper (but something we may want to improve on)

**Comment by stevvooe** [comment]
@thaJeztah We should document the above to demonstrate this behavior. cc @sfsmithcha 

Note that I did find a removal bug in this process. After generating these examples and removing the service, I still have the following:

```
$ docker ps -a -f name=angry
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
c4683915c083        alpine:latest       "sh"                20 hours ago        Created                                 angry_volhard.8.158923tb8caod0qe8l29393un
eb063366c99a        alpine:latest       "sh"                20 hours ago        Created                                 angry_volhard.4.cd1jwcz7m8tbj0o4tuhpkj89w
4b17aa0280d5        alpine:latest       "sh"                20 hours ago        Created                                 angry_volhard.6.dxm3enk1xqvnz77kni8f4lpfo
```

I am pretty sure this is unrelated to your original complaint, but I need to track this down, nonetheless.

**Comment by stevvooe** [comment]
@thaJeztah Are we still seeing this?

I think there is a tertiary error causing removal to fail but I haven't seen the log message in the wild. We need to focus on separating these by root cause.

If we are still seeing this around code freeze, we'll have to add a task reaper to swarmkit but that is a nuclear option and will hide bugs.

**Comment by thaJeztah** [comment]
I think it works correctly;

```bash
docker service create --name faulty nginx:alpine sh
```

This climbs up to +/- 16 old containers, but that seems to be just because it cannot remove old containers fast enough.

Fixing the service makes the amount of containers go back to 5 (1 running, and 4 old tasks);

```bash
docker service update --args "nginx -g 'daemon off;'" faulty
```

```
CONTAINER ID        IMAGE                                                                           COMMAND                  CREATED             STATUS                      PORTS               NAMES
b06788fb0d4e        nginx@sha256:5c6be3514a00db611371806c5aeb510dfd285a4b8261c6e5c3323387e396b66b   "nginx -g 'daemon ..."   30 seconds ago      Up 27 seconds               80/tcp, 443/tcp     faulty.1.d2oyympb32dbba22q4cfjsbit
19fb783c3c46        nginx@sha256:5c6be3514a00db611371806c5aeb510dfd285a4b8261c6e5c3323387e396b66b   "sh"                     36 seconds ago      Exited (0) 29 seconds ago                       faulty.1.9cyqj59cbef4xtsn3w4dbbsol
ef61d6a529d4        nginx@sha256:5c6be3514a00db611371806c5aeb510dfd285a4b8261c6e5c3323387e396b66b   "sh"                     42 seconds ago      Exited (0) 36 seconds ago                       faulty.1.j1454pjtc06bjkxhcqxgj3b46
62970591e5da        nginx@sha256:5c6be3514a00db611371806c5aeb510dfd285a4b8261c6e5c3323387e396b66b   "sh"                     48 seconds ago      Exited (0) 42 seconds ago                       faulty.1.1crpq72i9yxggltzoavd7oydz
467c640169ab        nginx@sha256:5c6be3514a00db611371806c5aeb510dfd285a4b8261c6e5c3323387e396b66b   "sh"                     55 seconds ago      Exited (0) 48 seconds ago                       faulty.1.lu27u18z8adquddoooga35fhm
```


One thing I tried, is to use the new `--update-max-failure-ratio` option, however this does not work for _creating_ a service. I wonder if we should consider doing that, I'll open a new issue for that.
