### ISSUE TITLE
ingress-sbox not always created

### ISSUE THREAD

**Issue by mgoelzer** [docker/docker#24400]
ingress-sbox not always created  @mavenugo 

Environment:
```
Red Hat Enterprise Linux Server release 7.2 (Maipo)
[root@node2 ~]# uname -a
Linux node2 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 9 10:09:10 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mavenugo** [comment]
@mgoelzer @tiborvass I could reproduce this problem with a specific reproduction steps

```
sudo docker swarm init
sudo docker service create --name=sw5 --replicas=3 -p 5000:5000  xxx yyy
sudo docker swarm leave --force
sudo docker swarm init
sudo docker network inspect ingress
```

Workaround : restart daemon

**Comment by mavenugo** [comment]
@mrjana when a manager is forcefully stopped and inited, swarmkit  creates the `ingress` network automatically. But `SetupIngress` fails while trying to delete the existing `ingress` network due to existing endpoints (as the tasks created via `service create` is not cleaned up).
wdyt ?

**Comment by mavenugo** [comment]
@tiborvass @tonistiigi @mgoelzer  this issue ultimately caused by the fact that when a manager is forced to leave the swarm, it fails to cleanup the service & hence the tasks/containers that is backing the service. That makes the `ingress` network to continue servicing the running tasks. When the swarm is created again (this time with the new ingress network), it is unable to cleanup the existing network, which causes this issue.

I think the correct fix is to cleanup the services/tasks when the user leaves the swarm. WDYT ?

**Comment by tiborvass** [comment]
Your conclusion makes sense to me but i'm not the man

**Comment by tonistiigi** [comment]
@mavenugo When we leave swarm we are removing all containers. There is no cleanup of service/task but I'm not sure what you mean by that.

**Comment by mavenugo** [comment]
@tonistiigi thanks for the confirmation. I just figured that out myself. I also found the root-cause of the stale endpoint issue. fix coming up.
