### ISSUE TITLE
[1.12] cgroup: systemd-cgroup support is broken

### ISSUE THREAD

**Issue by mrunalp** [docker/docker#24424]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   6167a9a
 Built:        Thu Jul  7 10:39:27 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   6167a9a
 Built:        Thu Jul  7 10:39:27 2016
 OS/Arch:      linux/amd64
```

**Steps to reproduce the issue:**
1. Start docker daemon with --exec-opt native.cgroupdriver=systemd
```
[root@dhcp-16-129 docker]# ./bundles/1.12.0-dev/dynbinary-daemon/dockerd --selinux-enabled --exec-opt native.cgroupdriver=systemd
```

2.  Start a container and look at the process's cgroup
```
[root@dhcp-16-129 testroot]# /root/gosrc/src/github.com/docker/docker/bundles/1.12.0-dev/dynbinary-client/docker run -it --rm busybox sh
/ # 
/ # cat /proc/self/cgroup 
11:freezer:/system.slice:docker:902ff1717ddcf52f19bce1334537724d67e78fdfd3be7e3a4c34ed7d6dccee63
10:perf_event:/system.slice:docker:902ff1717ddcf52f19bce1334537724d67e78fdfd3be7e3a4c34ed7d6dccee63
9:memory:/system.slice:docker:902ff1717ddcf52f19bce1334537724d67e78fdfd3be7e3a4c34ed7d6dccee63
8:hugetlb:/system.slice:docker:902ff1717ddcf52f19bce1334537724d67e78fdfd3be7e3a4c34ed7d6dccee63
7:pids:/user.slice/user-1000.slice/session-2.scope/system.slice:docker:902ff1717ddcf52f19bce1334537724d67e78fdfd3be7e3a4c34ed7d6dccee63
6:devices:/user.slice/system.slice:docker:902ff1717ddcf52f19bce1334537724d67e78fdfd3be7e3a4c34ed7d6dccee63
5:net_cls,net_prio:/system.slice:docker:902ff1717ddcf52f19bce1334537724d67e78fdfd3be7e3a4c34ed7d6dccee63
4:blkio:/system.slice:docker:902ff1717ddcf52f19bce1334537724d67e78fdfd3be7e3a4c34ed7d6dccee63
3:cpuset:/system.slice:docker:902ff1717ddcf52f19bce1334537724d67e78fdfd3be7e3a4c34ed7d6dccee63
2:cpu,cpuacct:/system.slice:docker:902ff1717ddcf52f19bce1334537724d67e78fdfd3be7e3a4c34ed7d6dccee63
1:name=systemd:/user.slice/user-1000.slice/session-2.scope/system.slice:docker:902ff1717ddcf52f19bce1334537724d67e78fdfd3be7e3a4c34ed7d6dccee63
/ # 
```

The output should have the form
```

6:devices:/system.slice/docker-902ff1717ddcf52f19bce1334537724d67e78fdfd3be7e3a4c34ed7d6dccee63.scope

```

**Comment by runcom** [comment]
This is happening with 1.12-rc3 as well. Adding this to the 1.12 milestone tentatively.

**Comment by mrunalp** [comment]
https://github.com/docker/containerd/pull/247 in containerd broke this.

**Comment by mrunalp** [comment]
This can be fixed in docker by setting setting runtimeArgs correctly when --exec-opt native.cgroupdriver is set to systemd.

**Comment by mlaventure** [comment]
This should have been taken care of by https://github.com/docker/docker/blob/master/cmd/dockerd/daemon_unix.go#L71

At least when using the stock runtime.

For additional runtime, this would have to be specified manually as a runtimeArgs.

Would have to check why it's not working as intended.

**Comment by runcom** [comment]
@mlaventure the problem is that on container start, even if containerd has been started with `--systemd-cgroup=true`, in https://github.com/docker/docker/blob/master/daemon/start_linux.go#L19 you'll retrieve the default runtime which is `docker-runc` (which has been set into https://github.com/docker/docker/blob/master/daemon/daemon_unix.go#L520) but no systemd option is passed then.
So, when you make a call to libcontainerd you send:
```
runtime: "docker-runc"
runtimeArgs: []
```
and then when you hit https://github.com/docker/containerd/blob/master/supervisor/create.go#L31 you override the default runtimeArgs (with --systemd-cgroup=true) with none

**Comment by runcom** [comment]
@mlaventure this is tricky to fix, because containerd can't assume `docker-runc` is the default and the PR I made https://github.com/docker/containerd/pull/285 isn't ok because we override the runtimeArgs no matter what runtime is and that's not correct. Not sure, probably we should save the default runtimeArgs somewhere along with the runtime itself.

**Comment by runcom** [comment]
Figured it out, opened https://github.com/docker/docker/issues/24450
