### ISSUE TITLE
[proposal] 'docker con' command

### ISSUE THREAD

**Issue by nathanleclaire** [docker/docker#24429]
`docker ps` could be replaced by `docker container`, but `docker container` is a lot to type.  `docker con` command would be nice and terse, plus it's poetic.

**Comment by thaJeztah** [comment]
If `docker container` will be implemented, `docker ps` will most likely kept as an alias, I don't think we should add more aliases, better keep that as an excercise for the user.

I'll close this for now, because we don't have an `docker container` command (yet), but track this in https://github.com/docker/docker/issues/8829

**Comment by nathanleclaire** [comment]
👍 😁
