### ISSUE TITLE
Add support for raspbian in install.sh

### ISSUE THREAD

**Issue by icecrime** [docker/docker#24561]
We have all the necessary scripts upstream to finally officially distribute deb package for raspbian, however the exact distro isn't yet supported in [`install.sh`](https://github.com/docker/docker/blob/778b38cbf1f03d54ef86ba79882af45d653e71b0/hack/install.sh#L272-L280).

Adding this to 1.12.0 milestone so we can start distributing this package.

Cc @DieterReuter @mlaventure @tiborvass!

**Comment by thaJeztah** [comment]
I think the release script also needs to be modified, as `arm` debs are not built by default

**Comment by mlaventure** [comment]
The script only build for the arch it is currently running on.

if run on a arm machine, it will build the debs for arms (ubuntu, debian, raspbian).

**Comment by thaJeztah** [comment]
ah, makes sense

**Comment by DieterReuter** [comment]
I'll dig into the necessary changes later this day and will open a PR. Should not be do complicated to add the official Raspbian/jessie version. We already tested to install the ARM .deb package and it works quite nicely with the standard kernel settings.

**Comment by cpuguy83** [comment]
@DieterReuter Any news?

**Comment by DieterReuter** [comment]
@cpuguy83 what a great timing! 

I just had a deeper look into the changes we need to apply to support the standard Raspbian and HypriotOS for all the available Raspberry Pi models. Both OS are based upon Raspbian/Jessie and therefore we can use exactly the same built Debian packages for the docker-engine.

In order to test the changes we should have at least two different versions of the Debian packages uploaded into the "testing" branch of the APT repo. This is necessary to test the update/upgrade as well as the install procedures. As we already had generated all the 1.12 RC's on our Jenkins build server, we can use these Debian packages here:
* [raspbian-jessie/docker-engine 1.12.0-rc4](https://jenkins.hypriot.com/job/armhf-docker/17/) - [Download .deb package](https://jenkins.hypriot.com/job/armhf-docker/17/artifact/bundles/latest/build-deb/raspbian-jessie/docker-engine_1.12.0%7Erc4-0%7Ejessie_armhf.deb)
* [raspbian-jessie/docker-engine 1.12.0-rc3](https://jenkins.hypriot.com/job/armhf-docker/15/) - [Download .deb package](https://jenkins.hypriot.com/job/armhf-docker/15/artifact/bundles/latest/build-deb/raspbian-jessie/docker-engine_1.12.0%7Erc3-0%7Ejessie_armhf.deb)
* [raspbian-jessie/docker-engine 1.12.0-rc2](https://jenkins.hypriot.com/job/armhf-docker/9/) - [Download .deb package](https://jenkins.hypriot.com/job/armhf-docker/9/artifact/bundles/latest/build-deb/raspbian-jessie/docker-engine_1.12.0%7Erc2-0%7Ejessie_armhf.deb)

Who can help to upload the .deb packages into 'https://apt.dockerproject.org/repo/dists/raspbian-jessie/testing/binary-armhf/', so we can live test the install and update?

**Comment by alexellis** [comment]
@DieterReuter I'm happy to help with testing. I have plenty of Pi 2/3 and Zero boards.

**Comment by thaJeztah** [comment]
Looks like changes to the install script were made, so I'll close this one, but ping me if additional changes are needed, and I'll reopen :smile:
