### ISSUE TITLE
Docker Cloud not creating a node cluster using new UI

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker#24762]
Trying to create a Docker Cloud Node Cluster with the values as shown in attachment.

Clicking on Create just shows a spinning wheel for a second and then comes back to the same screen. No new instances are created in EC2.

<img width="1128" alt="screen shot 2016-07-18 at 12 19 18 pm" src="https://cloud.githubusercontent.com/assets/113947/16923874/24749344-4ce2-11e6-8881-7233caa56d7c.png">

Going to the classic UI shows the following error `No billing info for user arungupta. Please enter your credit card details`. Fixing this error allowed to create the node cluster using UI.

**Comment by thaJeztah** [comment]
ping @fermayo PTAL

**Comment by sushanthmangalore** [comment]
Hi,

So is the billing info essential to create a node cluster even with the Docker Cloud default plan?

Thanks,
Sushanth

**Comment by thaJeztah** [comment]
@sushanthmangalore perhaps you can send an e-mail to support@docker.com for that question; this repository is strictly for the open source engine, not for Docker Cloud.

@arun-gupta I'll close this issue here, but you can discuss on https://forums.docker.com/c/docker-cloud (or probably send an e-mail to support@docker.com).
