### ISSUE TITLE
Why is Docker load command not secure?

### ISSUE THREAD

**Issue by innocentme1** [docker/docker#24779]
https://docs.docker.com/engine/security/security/ says"   -  it should be noted that ‘docker load’ is a mechanism for backup and restore and is not currently considered a secure mechanism for loading images" but it does not provide any reason why it is not secure. Can anyone help me understanding that?

**Comment by tonistiigi** [comment]
Since docker v1.10 internals of`docker load` command are much improved. I'd feel comfortable with removing this scary warning.

@aaronlehmann @thaJeztah

**Comment by aaronlehmann** [comment]
Let's remove it.

**Comment by innocentme1** [comment]
@tonistiigi can u direct me to the improvements of docker load command?

**Comment by tonistiigi** [comment]
@innocentme1 https://github.com/docker/docker/pull/17924

**Comment by innocentme1** [comment]
@tonistiigi Thanks but I am little confused on how this (Adding content addressable layers) is related to the docker load security issues question I am asking. One thought is that (one guy from slack gave me this answer when I asked same question) docker load is not secure because it does do any content verification like Notary..Anything else? 

If you mean to remove this comment, so is docker load secure now? (I know nothing is 100% secure but it seems to be secure for now? does it address this content validation issue? etc.)

**Comment by tonistiigi** [comment]
@innocentme1 That comment in the docs refers to the old(this comment was added in v1.5) `docker load` implementation where the data in the tar was considered more trustworthy than the images downloaded by `docker pull` and it didn't go through much validation. Since content-addressability both load and pull use the same methods for storing images, everything is addressed by the checksums of the data so collisions can't happen if images from load and pull are not exactly the same.

Notary is different and provides secure naming. Meaning if you pull something called "someuser/foo" you know that the bytes you get are the bytes that "someuser" created.

If you download a random tarball from internet, `docker load` it and it creates an image called "ubuntu" you can't trust that this ubuntu is the same official ubuntu that you get from doing `docker pull`. What you can trust is that this loaded image did not overwrite any of your existing images and if you do `docker pull ubuntu` with notary it can verify the existing data without repulling it.

**Comment by tangzhankun** [comment]
@tonistiigi , I don't quite understand that when one <code>docker load</code> an arbitrary tarball from the internet with a tag name "ubuntu:14.04", why won't it overwrite existing official ubuntu:14.04.

As far as I know, one can tag a centos image with the name, for instance "ubuntu:14.04". And docker save it to a tarball. Then if another host <code>docker load</code> this tarball, this command would force to replace existing ubuntu:14.04 by default. This would cause other users confused when "docker run ubuntu14.04" which is apparently unsecure.

How can I avoid this tag name conflict? It seems adding an option <code>--override</code> to <code>docker load</code> and make it won't replace existing image others are using by default seems more reasonable to me. Thoughts?

**Comment by tonistiigi** [comment]
@tangzhankun This was mostly answered in https://github.com/docker/docker/pull/24782#issuecomment-234646754 . Load creating tags is the same process as user running `docker tag` or `docker build -t`. If you want to make sure the image is up-to-date you should use docker content trust or repull if repo doesn't have trust signatures.

**Comment by tangzhankun** [comment]
@tonistiigi , thanks for the info. I guess there is no way to ensure a tarball can be trusted, right? Then the <code>docker load</code> is not responsible for this.
