### ISSUE TITLE
docker service changes routing table

### ISSUE THREAD

**Issue by vhp1360** [docker/docker#24796]
I encountered a deal problem:<br/>
I have *fedora24* as host and installed *centos7 minimal* as guest on *KVM*.<br/>
installed *docker* in guest, there is one NIC by ens3 name with 192.168.122.120 address<br/>
I can ssh to guest from host before *start docker service*.
in this step when i run `route -n` in guest,i would have 
>Kernel IP routing table
>Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
>0.0.0.0         192.110.133.1   0.0.0.0         UG    100    0        0 ens3
>192.168.122.0   0.0.0.0         255.255.255.0   U     100    0        0 ens3<br/>

now when i run `service docker start` in guest, i will lost ssh to guest by *ssh: connect to host 192.168.122.120 port 22: No route to host* and when i check rout table in guest machine, i faced
>Kernel IP routing table
>Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
>0.0.0.0         192.110.133.1   0.0.0.0         UG    100    0        0 ens3
>172.17.0.0      0.0.0.0         255.255.255.0   U     0      0        0 ens3
>192.168.122.0   0.0.0.0         255.255.255.0   U     0      0        0 br-c2a15a4ad6d2
>192.168.122.0   0.0.0.0         255.255.255.0   U     100    0        0 ens3<br/>

does know any one a logic reasonable?how can i solve it?

**Comment by cpuguy83** [comment]
ping @mavenugo

**Comment by vhp1360** [comment]
could you please let me know the status? shall i wait for new version?

**Comment by mavenugo** [comment]
@vhp1360 docker daemon doesnt touch the host routing table directly. But the output clearly indicates that there are some `docker networks` being created resulting in this :

```
172.17.0.0 0.0.0.0 255.255.255.0 U 0 0 0 ens3
192.168.122.0 0.0.0.0 255.255.255.0 U 0 0 0 br-c2a15a4ad6d2
```

Can you please check if you have previously created `docker networks` ?
Its always recommended to use the `--subnet` while creating docker network so that it will not conflict with your existing physical subnets causing routing failures.

Pls remove the networks that are conflicting using `docker network rm` (or) stop the deamon, remove the /var/lib/docker/network directory and restart docker daemon.

**Comment by vhp1360** [comment]
@mavenugo thanks, but i could not got you about "docker daemon doesnt touch the host routing table directly", because my routing table change when i run docker.
regarding "Can you please check if you have previously created docker networks" the result is _docker: 'networks' is not a docker command._ ans as i do not know how to create network, i sure did not do that :-),
any way, my problem solved with your solution but i could understood the reason, many thanks and very sorry for late

**Comment by mavenugo** [comment]
@vhp1360 thanks for getting back. it is `docker network` command. 
Since the workaround that I suggested worked for you and since you didnt create this explicitly, I think the network was created automatically by other applications such as docker-compose or DTR, etc...

I will close the issue now. Pls feel free to comment.
