### ISSUE TITLE
1.12.0-rc4: how to set registry_mirror (windows hyper-v)

### ISSUE THREAD

**Issue by eromoe** [docker/docker#24794]
https://docs.docker.com/engine/admin/registry_mirror/
This doc is empty, it says `The original content was deprecated. `  

Below doc 1.6 not work
https://docs.docker.com/v1.6/articles/registry_mirror/

I am using newest windows hyper-v docker. And I am in China, I have to set a mirror to get docker work(due to the dammit GFW)

**Comment by thaJeztah** [comment]
If you're running Docker for Windows, have a look at this section https://docs.docker.com/docker-for-windows/#/docker-daemon as well

However, our GitHub issue tracker is for tracking bugs and feature requests, not a general support forum, please use forums.docker.com, the #docker IRC channel, or StackOverflow

I'll close this issue, because this is a support question, but feel free to comment after I closed
