### ISSUE TITLE
[1.12] docker service scale should have "--registry-auth" flag

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#24894]
As brought up by @Stehsegler (thanks!) in https://github.com/docker/docker/issues/24891#issuecomment-234232186, `docker service scale` does not have a `--registry-auth` flag, making it not possible to scale a service if it uses an image from a private repository.

We should add this flag.

**Comment by aaronlehmann** [comment]
I think this is based on a misunderstanding of `--registry-auth`. The flag isn't needed to do an operation like scaling. It's only needed to put in place or update the credentials.

So I think `docker service scale` *shouldn't* have a `--registry-auth` flag, because the purpose of the command is only to scale. If you want to update the credentials, you should use `docker service update`.

**Comment by thaJeztah** [comment]
closing per the discussion here, and https://github.com/docker/docker/issues/24891#issuecomment-234338480

Thanks @aaronlehmann
