### ISSUE TITLE
review docs for consistent usage and capitalization of "swarm", "swarm mode"

### ISSUE THREAD

**Issue by sfsmithcha** [docker/docker#24905]
need to review docs for consistent usage of "swarm" and "swarm mode"

"swarm" is not a proper noun. It should not be capitalized except when it comes at the beginning of the sentence.

The same is true of many of the concepts for "swarm mode:"
worker node, manager node, etc.

**Comment by aaronlehmann** [comment]
Thanks for opening the PR.

#24823 should address this in the actual CLI and the CLI reference docs. The API docs and user guide still need to be updated.

One possible exception is "Docker Swarm". I have left this as a proper noun since I think it is referring to Swarm as a product, not the concept of a swarm.

**Comment by sfsmithcha** [comment]
You are right : "Docker Swarm" refers the product that is not swarm mode inside of Docker Engine. There may be some ambiguous references.
