### ISSUE TITLE
Basic Auth for ETCD Discovery

### ISSUE THREAD

**Issue by DerekTBrown** [docker/docker#25093]
I know you can use TLS Auth, but can you use Basic Authentication when doing ETCD Discovery?

**Comment by thaJeztah** [comment]
this looks to be a question for "Swarm" (not "swarm mode", which is new in Docker 1.12); the Swarm issue tracker may be better for this https://github.com/docker/swarm/issues

However, since this is a support question, not a bug; it's probably best to ask this on the forums;
forums.docker.com, or the #docker or #docker-swarm IRC channel

I'm closing this issue here, because this is not a bug, and not related to the docker engine
