### ISSUE TITLE
docker pull should replace tag

### ISSUE THREAD

**Issue by tinganho** [docker/docker#25132]
As I understand Docker. It pulls a tag with `docker pull <image>` and then if there exists an existing tag it untags it, but keeps the old image?

Why untag it and keep the image? I propose deleting it. Or at least let us have an option to specify how many old tags to keep.

My disk is always overbloated with docker images nowadays.

**Comment by thaJeztah** [comment]
The old image is still kept, because it may be in use by a (running) container, or (depending on the version of docker you're using), act as a parent image for other images.

We'll be looking into improvements for data-management (e.g. purging unused images, etc), and there's an issue to track that here; https://github.com/docker/docker/issues/22871

I'll close this issue as we already track this in https://github.com/docker/docker/issues/22871, so please subscribe to that issue to keep up to speed 👍

**Comment by tinganho** [comment]
>The old image is still kept, because it may be in use by a (running) container, or (depending on the version of docker you're using), act as a parent image for other images.

Just a question, does it get deleted if it isn't used by a running container or acts as a parent? Because every time I delete untagged ones. There is just loads of images that dissapears.

This is my docker version:
```
$ docker --version
Docker version 1.10.2, build c3959b1
```

**Comment by thaJeztah** [comment]
No, currently, I don't think it's automatically cleaned up, but I think un-referenced layers are - @tonistiigi should know more about that (I remember asking him once); we'll look at that as well while working on the linked issue

**Comment by tonistiigi** [comment]
Only command that can remove existing images/layers is `docker rmi`. Layers are not referenced by tags but by images, so pulling doesn't remove any layer references.
