### ISSUE TITLE
kitematic.exe: remember preference for virtualbox

### ISSUE THREAD

**Issue by mcandre** [docker/docker#25247]
In Kitematic, please remember my preference for hypervisor. The built-in one in Docker Toolbox always fails on my machine, so it's annoying to have to constantly remind Kitematic to use the VirtualBox hypervisor every time.

* Docker Toolbox 1.11.2
* Windows 10 Professional x86_64

**Comment by icecrime** [comment]
Cc @mchiang0610!

**Comment by mchiang0610** [comment]
@mcandre Thanks. Noted for this feature on the Kitematic repo. ( @icecrime mind closing this issue so it doesn't stay in docker/docker?) 

@mcandre Curious on why you're not using Docker for Windows and is instead using Docker Toolbox since you are on Windows 10 Professional? 

Thanks,
Michael Chiang

**Comment by icecrime** [comment]
Closing, thank you Michael ;-)
