### ISSUE TITLE
Was tarsum_version discarded?

### ISSUE THREAD

**Issue by ZYNCMA** [docker/docker#25284]
When I pulled an images from registry v2 using docker 1.5, I got `Error from V2 registry: unable to wrap image blob reader with TarSum: tarsum label string should be of the form: {tarsum_version}+{hash_name}`. 
After digging into the functionality of tarsum, I found that `tarsum_version` seemed to be discarded in docker 1.11. It only took effect when pushing image to registry v1 and was sent to registry v1 as file _checksum (by the way, when I checked the _checksum file of registry v1, `tarsum_version` wasn't there). It has nothing to do with registry v2. But I did remember I had seen `tarsum_version` in the manifest file before using registry v2 api. 
My question is, since when and why was `tarsum_version` discarded? If it is not, how can I get it?

**Comment by thaJeztah** [comment]
isnt this related to https://blog.docker.com/2015/10/docker-hub-deprecation-1-5/ ?

**Comment by ZYNCMA** [comment]
No. I know registry v2 doesn't support docker 1.5 and earlier. I'm asking about the tarsum_version.
I do remember I saw blobsums containing tarsum_version (something like tarsum+sha256:67db4a8ef11598d13fcbd3d4cc01ab82b2c30216e07a05454b42e96d35ab2ac6) before via `GET /v2/{image_name}/manifests/{tag}`. But when I tried it yesterday, it didn't return the tarsum_version. So I read the source codes of docker 1.11 and distribution to see what happened, and I found that tarsum_version seemed deprecated.
I want to know whether I'm right or not. If yes, why is it deprecated? If no, how can I get a digest or blobsum containing the tarsum_version?

**Comment by ZYNCMA** [comment]
By the way, may I ask how you make docker 1.5 able to pull images from Docker Hub based on registry v2? What did you do to Docker Hub? When I pulled images from registry v2 using docker 1.5, I got `Error from V2 registry: unable to wrap image blob reader with TarSum: tarsum label string should be of the form: {tarsum_version}+{hash_name}`.

**Comment by thaJeztah** [comment]
ping @aaronlehmann @stevvooe do you know about the tarsum_version?

**Comment by dmcgowan** [comment]
Tarsum currently has 2 versions (see https://github.com/docker/docker/blob/master/pkg/tarsum/versioning.go) and the valid values for `tarsum_version` are `tarsum` and `tarsum.v1`. The v2 registry does not support tarsum and any prior support was experimental has been removed. Older docker clients had support for pulling tarsum content but were unable to push content. Because tarsum requires processing the data prior to verification and the potential for exploits during that pre-verification computation, it was removed as a method for pulling and verification. It still exists in the code for local cache addressing only, but it not used in any v2 registry interactions.

To use the v2 registry, you must upgrade to at least docker 1.6, when private v2 registry support was added. Support for the v2 registry in prior versions of Docker is considered experimental and not supported.

**Comment by ZYNCMA** [comment]
Got that. Thank you @dmcgowan  @thaJeztah  !

**Comment by thaJeztah** [comment]
You're welcome!
