### ISSUE TITLE
Debian package doesn't hook CA certificate updates

### ISSUE THREAD

**Issue by duncan-bayne** [docker/docker#25429]
**Output of `docker version`:**

```
Docker version 1.10.3, build 20f81dd
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 5
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 112
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.0-21-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.41 GiB
Name: duncan-e550
ID: IPYR:6U3S:ZLW6:ZCQF:RS4U:WG3S:K7OO:DPSN:4SB4:B3FC:UTZT:ZWJX
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on Linux Mint 18 Sarah (Cinnamon, 64-bit).

**Steps to reproduce the issue:**
1. Install Docker with: `sudo apt-get install -y docker.io && usermod -aG docker $(whoami)`.
2. Add a custom CA certificate to the system, and run `sudo dpkg-reconfigure ca-certificates`.
3. Attempt to pull a Docker image from a repository with a certificate signed by the custom CA certificate. 

**Describe the results you received:**

I expected the Docker image to pull successfully.

**Describe the results you expected:**

The Docker image failed to pull, with the following errors:

```
v2 ping attempt failed with error: Get https://my-domain/v2/: x509: certificate signed by unknown authority
v1 ping attempt failed with error: Get https://my-domain/v1/_ping: x509: certificate signed by unknown authority
```

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue was fixed by restarting the Docker daemon with `sudo service docker restart`.

I _believe_ the correct fix is for the .deb package to install a hook script in:

`/etc/ca-certificates/update.d`

... that restarts the Docker daemon when new CA certificates are installed.

If you can confirm that this fix is desirable, I'll raise a PR to fix this issue that way.  I'm concerned that there's a good reason that you're not already hooking CA certificate updates, though.

**Comment by thaJeztah** [comment]
The `docker.io` package is maintained by Debian, but I assume the packages at apt.dockerproject.org have the same issue.

I can assume that the reason here is that (in a default configuration), restarting the daemon also brings down all containers (or restarts them), which may well be unwanted. I wonder if the certificates can be reloaded without *restarting* the daemon (e.g. via a `SIGHUP`), in which case doing this would be a better option.

Ping @tianon @paultag any ideas?

**Comment by thaJeztah** [comment]
also /cc @mlaventure @kencochrane

**Comment by tianon** [comment]
I'm personally wary of any solution that involves restarting the admin's Docker daemon for them when they didn't explicitly request it, especially given the concern @thaJeztah raised regarding that restarting all containers by default (and thus causing potential downtime and frustration).

I believe the Go package responsible for loading these is `crypto/x509` (https://golang.org/src/crypto/x509/root_linux.go), but I'm not sure if there's a way for us to have it reload them (since I'm not sure where/how they're getting loaded explicitly or implicitly or where they're being stored/cached once they are).  I think figuring that out would help inform whether there's anything we can/should do at the packaging level (more than just adding pointers informing folks that they'll have to restart their daemon to pick up new or changed certs).

**Comment by thaJeztah** [comment]
Thanks for looking @tianon 

Calling @dmcgowan, who may know more about the crypto package (I hope :smile:)

**Comment by duncan-bayne** [comment]
Ah - I'd assumed they were using packages built via the .deb packaging code in the docker repo.  My bad.

I guess the question still stands, though ... what's the right thing to do, restart or SIGHUP?  Sounds like SIGHUP.

**Comment by dmcgowan** [comment]
The Go package does not allow for reloading the system certificates, it is protected with a `sync.Once` (see https://golang.org/src/crypto/x509/root.go). 

Restarting the daemon has always been the expected solution after updating system certificates. I would not be supportive of any solution which tried to do this automatically on just one system since it would then be inconsistent with other systems.

> restarting the daemon also brings down all containers (or restarts them)

If we get to a point where this is not true by default then restarting may make more sense. As is I agree with @thaJeztah and @tianon

**Comment by thaJeztah** [comment]
Thanks for looking @dmcgowan. Based on the above, I don't think there's much we can do (currently) to improve this. I'll close this issue because of that, but happy to revisit if other options are possible in future

**Comment by mlaventure** [comment]
Note: from `1.12.0` if the `live-restore` daemon flag is sets, restarting the daemon **WILL NOT** brings down all the containers.

**Comment by dmcgowan** [comment]
@mlaventure have you seen any packagers enabling `live-restore` by default? And would you suggest it?

**Comment by tianon** [comment]
Until it's enabled by default in Docker itself, I'd strongly encourage
packagers to avoid enabling it (and leave that choice to the users).

Doesn't enabling it still mess with Docker networks in some way?

**Comment by mlaventure** [comment]
@dmcgowan I haven't seen it no, but users are free to do so. I personally enabled it on my machine after the upgrade.

@tianon The assumption (and it should be somewhere in the docs too) is that the daemon configuration cannot be changed between restart for `live-restore` to work. So no changes to network, I guess that may cover CA updates too.
