### ISSUE TITLE
NoCredentialProviders error with awslogs logging driver

### ISSUE THREAD

**Issue by tlvince** [docker/docker#25468]
**Output of `docker version`:**

```
Docker version 1.12.0, build 8eab29e
```

**Output of `docker info`:**

```
Containers: 7570
 Running: 3
 Paused: 0
 Stopped: 7567
Images: 11
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15171
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.2.0-41-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.858 GiB
Name: example
ID: XBFR:JJ2K:4H3E:EXG7:6FRF:WYXK:GF4A:UJNV:OCVO:YYHG:PQJH:2IXO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=amazonec2
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

docker-machine initialised EC2 (Ubuntu) instance

**Steps to reproduce the issue:**

1. Create an IAM user and set `/root/.aws/credentials` (per [docs](https://docs.docker.com/engine/admin/logging/awslogs/#/credentials) and [example.ini](https://github.com/docker/docker/blob/3f970819bb4231375f7821aa54670fd59e384f4d/vendor/src/github.com/aws/aws-sdk-go/aws/credentials/example.ini))

2. Start a container using the awslogs driver

    ```
docker run \
  --log-driver awslogs \
  --log-opt awslogs-region=eu-west-1 \
  --log-opt awslogs-group=example \
  --log-opt awslogs-stream=example \
 hello-world
    ```

**Describe the results you received:**

```
ERROR: for hello-world  Cannot start hello-world: b'Failed to initialize logging driver: NoCredentialProviders: no valid providers in chain. Deprecated. \n\
tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors'
```

**Additional information you deem important (e.g. issue happens only occasionally):**

What I've tried (via #19392 and #16551):

* Exporting AWS_ACCESS_KEY_ID (etc.) in `/etc/default/docker`
* Creating a `~/.aws/credentials` file (for both root and ubuntu)
* Passing them in at runtime via a .env file

**Comment by thaJeztah** [comment]
ping @samuelkarp could you have a look?

**Comment by samuelkarp** [comment]
Hi @tlvince,

If you're running on EC2, the easiest way to provide credentials to the Docker daemon is by using an [EC2 instance profile](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html) with an appropriate IAM role.

However, if you were not running on EC2, you should still be able to provide credentials to the Docker daemon.  It looks like you're running Ubuntu 15.10, which I believe uses systemd as its init system.  I am less familiar with systemd, but I suspect some of the confusion here relates to differences between how systemd functions and a more traditional init system.

For `/root/.aws/credentials` to work, the `HOME` environment variable must be set for the user running the Docker daemon.  I'm suspecting in your case that no `HOME` environment variable is set (the [systemd documentation](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#%24USER) seems to imply that `HOME` is only set if `User=` is specified in the unit file).  As an alternative here, you can use the `AWS_SHARED_CREDENTIALS_FILE` environment variable ([since Docker 1.10](https://github.com/docker/docker/issues/19392#issuecomment-173040949)) to specify the location of the shared credentials file.

For environment variables to work (including the `AWS_SHARED_CREDENTIALS_FILE` environment variable) they must be specified when the daemon is launched.  In systemd, I do not believe environemnt variables defined in `/etc/default/docker` are picked up; rather you'll need to define them in the unit file for Docker.

@thaJeztah, I think you're more familiar with systemd than I am; can you let me know if my assumptions here are correct?

@tlvince, please let me know if you continue to run into problems.

Thanks,
Sam

**Comment by tlvince** [comment]
@samuelkarp thanks for the well thought through and patient response. Setting environment variables in the systemd service file (`/etc/systemd/system/docker.service` in Ubuntu) worked for me.

I'm not sure if further resolution is needed here besides perhaps adding this as a note to the [awslogs docs](https://docs.docker.com/engine/admin/logging/awslogs/#/credentials); feel free to close this issue. Cheers!

**Comment by thaJeztah** [comment]
@tlvince it's best to not edit the systemd unit file directly; doing so causes issues if a future update of docker includes changes in the unit file (apt/yum/dnf in that case will not replace the unit file with the updated version, because local modifications were found).

To add custom options to a unit file, you can use an override (drop-in) file; you can find how to do so in this part of the documentation; https://docs.docker.com/engine/admin/systemd/#/custom-docker-daemon-options

I see that these credentials cannot be passed through daemon options, otherwise you could configure them in a `daemon.json` configuration file; the advantage of that would be that the configuration could be set, independent of the type of process manager in use (systemd/upstart) (as explained in https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-configuration-file), perhaps that would be a nice addition?

**Comment by thaJeztah** [comment]
I'll close this issue, because it doesn't appear to be a bug, but feel free to continue the discussion or if you think improvements should be made to the documentation

**Comment by samuelkarp** [comment]
@tlvince Glad I could help!  If you have suggestions on how to improve the docs I'm definitely interested. :smile:

**Comment by ottumm** [comment]
How do I set environment variables for the Docker daemon when using Docker for Mac?

**Comment by thaJeztah** [comment]
@ottumm I think there's still being worked on including that in the UX; since that's specific to Docker for Mac, which has its own issue tracker could you check if an existing issue exists, or otherwise open one? https://github.com/docker/for-mac/issues
