### ISSUE TITLE
users bypass docker userns restriction

### ISSUE THREAD

**Issue by HamidEDD** [docker/docker#25492]
When docker engine runs inside a usernamspace (with the --userns-remap=default option), a simple user could bypass this restriction using :
``` 
- docker run -itd --name c1 --userns=host ubuntu bash
```
The container then is launched as root.

Normally, (--userns=host) option should not be available, exactly like (--net=host), when docker-engine is running in usernamspace mode.

Another thing that I found very strange, is when I use the ubuntu or alpine images 
the container is created as root while the container with cirros image is created as "dockremap" user.

**Output of `docker version`:**

Both versions are affected
```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:40:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:40:59 2016
 OS/Arch:      linux/amd64

--------------------
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- VM Ubuntu 16.04 and Debian Jessie

**Steps to reproduce the issue:**
1. docker daemon -H fd:/// --userns-remap=default
2. docker run -itd --name c1 --userns=host ubuntu bash 
3. docker run -itd --name c2 --userns=host alpine sh
4. docker run -itd --name c3 --userns=host cirros sh
5. ps faux | grep "docker-containerd-shim" -A 1 | grep -v "grep"

**Describe the results you received:**

The containers c1 and c2 are created as root, while c3 is created as "dockremap" user

**Describe the results you expected:**

All containers should be created inside dockermap userns.

**Additional information you deem important (e.g. issue happens only occasionally):**
```
- docker run -itd --name test --userns=host --net=host cirros sh 
```
doesn't fail, and allow user to create container with **net=host** inside dockermap userns !!

**Comment by cpuguy83** [comment]
Wouldn't `--userns=host` be the usernamespace of the docker daemon?

**Comment by HamidEDD** [comment]
@cpuguy83 normally it should be. But in my case, only containers with cirros images are created inside  userns of docker daemon.

**Comment by justincormack** [comment]
The behaviour of `--userns=host` bypassing the user namespace setting is intentional, judging from the commit. Accessing the Docker socket without any authorization plugin does give privileges, despite user namespaces.

Will take a look at why the containers are inconsistent though.

**Comment by estesp** [comment]
`--userns=host` as @justincormack mentioned was explicitly added so that `--privileged` mode is available for admin-type operations when the daemon is enabled with user namespaces; so yes, it was intentional, and userns == host was the method by which we decided to make it explicit that you were "turning off" user namespaces by using the host (most likely not in a user namespace).

The cirros issue is quite strange--the gid is correct, but the effective uid is remaining as the remapped root ID; I will look into this (unless @justincormack already has a handle on it) :)

**Comment by justincormack** [comment]
@estesp did you look into this (I havent yet)?

**Comment by estesp** [comment]
@justincormack sorry--lost track of it. Was confused until I found this in the cirros image:
```
/bin $ ls -l busybox
-rwsr-xr-x    1 165536   165536      728528 May  7  2015 busybox
```

Because we are running the daemon in userns mode, the filesystem of the image has been remapped via `chown` to the higher uid/gid range already. Now since the "sh" and other binaries are just symlinked to a setuid busybox, even though the process is started as real (host) root, it's euid becomes 165536 because of the setuid binary. It is definitely not running within a userns (looking at `/proc/self/uid_map` clearly shows it is not), but appears to be running as the "remapped root" because of this busybox binary.  To me this is an image problem, as there isn't much we can do with a setuid binary, other than hope in a further phase of user namespace support the lower filesystem won't have to be "chowned" to the remapped range (although how setuid binaries will operate in that environment is TBD.. but at least `--userns=host` mode would be clearer).

**Comment by justincormack** [comment]
Ah. I don't recommend people use `setuid` myself, especially for busybox, as that gives you unnecessary privileges. Adding capabilities is much better. For userns it is an extra problem I guess, more reasons to avoid.

I am going to close this as it appears to be just confusing not a bug, but feel free to continue the conversation.
