### ISSUE TITLE
Perform Health Check externally?

### ISSUE THREAD

**Issue by veerendra2** [docker/docker#25525]
Hello,
In the healthcheck, we plan to run an external command that can initiate test on container and uses the result for success or failure of health check. During the rolling update with HEALTHCHECK command, how can I get the new instance IP or ID to initiate my test?

Is there any external command for HEALTHCHECK to perform "tests"(An Shell code located outside of container) on the container if the performance is bad, it roll-back to previous version? (I have checked  [here](https://github.com/docker/docker/issues/23962), but the "tests"(Shell script) will copy into the image i.e. inside of the container)

**Comment by justincormack** [comment]
The `HEALTHCHECK` is intended for internal testing only. If you want to run external checks you will have to run as an additional service that controls your main service I think.

**Comment by veerendra2** [comment]
Thanks for reply! Can you share your idea with some details, that would be helpful

**Comment by thaJeztah** [comment]
please keep in mind that the GitHub issue tracker is not a generic support forum; the issue tracker is for tracking bugs and feature requests (https://forums.docker.com, the #docker IRC channel or StackOverflow are more suitable for other types of discussions).

I'll close this issue for housekeeping, because this is not a bug, but feel free to continue the discussion here

**Comment by teohhanhui** [comment]
I think this is a feature request. Currently implementing a `HEALTHCHECK` requires that we dirty the container with otherwise unnecessary tools in some cases (see docker-library/php#366 for example where the `cgi-fcgi` binary needs to be installed for doing healthcheck on PHP `fpm`). If there could be an option for an external healthcheck, it'd allow the image to be clean again.
