### ISSUE TITLE
Feature Request:  Add the ability to specify ports on deploy

### ISSUE THREAD

**Issue by joshgarnett** [docker/docker#25594]
The DAB spec states that the port exposed on the host cannot be specified in the file, which makes sense as I may want to deploy the app to a different set of ports.  That said, it would be very useful when running docker deploy, to be able to specify the port mapping.  Right now it is automatic and requires an explicit update of the service to expose the desired port.

**Comment by dnephin** [comment]
Yes, we absolutely need some way to be able to specify these non-portable options at deploy time, without requiring a bunch of `service update` commands post-deploy.

I don't think they will ever be part of the DAB, because we want to keep it portable, but I think a separate config for non-portable options might work.

**Comment by dnephin** [comment]
Going to close this since we have #26748 to track the larger issue.
