### ISSUE TITLE
A bug in implements of loading image for docker v1.12.0

### ISSUE THREAD

**Issue by ywk253100** [docker/docker#25654]
These seems a bug in implements of loading image in line 239 of [load.go](https://github.com/docker/docker/blob/v1.12.0/image/tarexport/load.go)(v1.12.0).
```
repositoriesFile, err := os.Open(repositoriesPath)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		return repositoriesFile.Close()
	}
	defer repositoriesFile.Close()
```
If repositoriesFile doesn't exist, it will go to "return reposigoriesFile.Close()". Since it does not exist, why we close it? And the close will cause an "invalid argument" error.

Besides, does the new version of docker support loading layers? In version 1.8.2, I can load a middle layer if its parents have existed in docker, but now docker seems not support it anymore. According to the implements of v1.12.0, docker does not look up layer's parent in file system first but just check if it exits in the tarball file.

**Comment by thaJeztah** [comment]
I think that's a bug indeed, but has been there since 1.10.0 (see https://github.com/docker/docker/blob/v1.10.0/image/tarexport/load.go#L164-L171)

Are you interested in opening a pull request?

> Besides, does the new version of docker support loading layers? In version 1.8.2, I can load a middle layer if its parents have existed in docker, but now docker seems not support it anymore. According to the implements of v1.12.0, docker does not look up layer's parent in file system first but just check if it exits in the tarball file.

That's due to the content-addressable store; since 1.10, the way layers are "collected" for an image changed. In older versions, the "parent" image chain is walked to collect the image-layers for the image. Since docker 1.10, each image contains a list of image-layers that compose the image; the "parent" chain is no longer used for that, which also means that pulling an image will no longer pull parent images.

**Comment by ywk253100** [comment]
Sorry for the late reply  and I will open a pull request later to fix the bug.

**Comment by allencloud** [comment]
@ywk253100 
I think in load.go, there are two places have the same problem. 
```
repositoriesFile, err := os.Open(repositoriesPath)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		return repositoriesFile.Close()
	}
```
Wish it could be fixed soon.

**Comment by tonistiigi** [comment]
> Besides, does the new version of docker support loading layers? In version 1.8.2, I can load a middle layer if its parents have existed in docker, but now docker seems not support it anymore.

You can't load layers individually but you don't have to have all the layers in tar if docker already has them https://github.com/docker/docker/pull/18727
