### ISSUE TITLE
[feature request]  Run command on health check - ok and health check - bad

### ISSUE THREAD

**Issue by krasi-georgiev** [docker/docker#25674]
We run a HA web server(2 servers in LB setup) and another external monitoring server.

The external IP on both servers is added as an A record to the DNS (Cloudflare)
If the external monitoring server detects a problem with one of the server it uses the Cloudflare API to disable the DNS records for this server so no clients are sent to this bad server.
This is how it looks like:

![Schema](https://raw.githubusercontent.com/prioactiveinvestors/fmServer/master/schema.png)

Now with the new Docker health check and swarm mode it would be really cool if we could implement all this without relying on a external health check service.

I am thinking something that will extend the idea for the container health check and maybe allow adding commands on a container or node failure. 

It will run some curl command that will adjust the external DNS in our case.

**Comment by talex5** [comment]
The built-in healthcheck only tells you that the container is healthy, but not that it is reachable from outside, so you probably want to keep your existing external check. Combining the two will help to tell you why the service isn't working: if it is unreachable externally but Docker says it is healthy then you know the problem is the network connection to the container.

**Comment by vipconsult** [comment]
Yes fair point the external check will be a better criteria, but I still think it would be cool to be able to run commands when the container check validates or fails.

**Comment by krasi-georgiev** [comment]
I realised that I can actually run the commands inside the healthcheck script itself.
