### ISSUE TITLE
Push Serialized On Low Bandwith

### ISSUE THREAD

**Issue by jpaugh** [docker/docker#25679]
It's [awesome](#150) that [push](#18498) is now parallel; however, could we have an option to push layers in serial, also? It need not be the default.

Uploads are not always blazingly fast; I typically get 3-5 Mb/s when working from home. Serializing in this scenario would be more stable.

### Use case

If I'm uploading 3 images (50MB, 210 MB, 111 MB), and I manage to upload 250 MB before the connection drops, I could have completed the upload of any one of the layers; but with that bandwidth spread across all of them, I might not get *any* of them to upload successfully.

**Comment by thaJeztah** [comment]
This is already implemented in docker 1.12, which allows you to set the maximum number of concurrent up/downloads; see https://github.com/docker/docker/pull/22445

You can set this either through a flag on the daemon, or (more convenient), through a daemon configuration file; https://docs.docker.com/engine/reference/commandline/dockerd/#/linux-configuration-file

Using a daemon configuration file allows you to change this setting without restarting the daemon; 
https://docs.docker.com/engine/reference/commandline/dockerd/#/configuration-reloading

I'll close this issue, because this is already implemented, but feel free to continue the discussion :+1:

**Comment by jpaugh** [comment]
Ah! I forgot, I'm not using the latest. Thank you!

**Comment by abawany** [comment]
Any idea how this works on OSX? There appears to be no `dockerd` on there and trying to modify ~/.dockercfg results in a `invalid file` error. I would like to limit the number of concurrent uploads.

**Comment by notpeter** [comment]
@abawany 18 months too late, but you can configure this under Docker->Preferences, Daemon->Advanced.
```
{
	"max-concurrent-downloads": 3,
	"max-concurrent-uploads": 5
}
```
See: [dockerd daemon configuration file docs](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file)

**Comment by abawany** [comment]
Thanks @notpeter - I updated my config. My workaround in the meantime had been to build on our cloud machines instead of locally to avoid my bandwidth limitations.
