### ISSUE TITLE
[feature request] Routing preference based on lowest latency.

### ISSUE THREAD

**Issue by krasi-georgiev** [docker/docker#25688]
It would be cool if we can set a preference for the  load balancing  to to send requests to the nearest container (lowest latency)

We run a standard nginx and mysql website so if we run more than one mysql spread on different nodes it would be great performance increase if we make the nginx container send requests to the mysql which is local on the same node.

**Comment by FlorinAsavoaie** [comment]
This sounds like an expected feature in high traffic deployments, from 2 perspectives:

1. When one service connects to a mesh network endpoint, it connects to the IP of a random node (since you connect to ONE of them). This generates traffic between the node running the calling service and the node we are connecting to. Can't we find a solution in which we are always directed to the mesh network endpoint running on the same node as the calling service?
2. If the service being called is on a different node than the one we ended up calling via the mesh network endpoint, we end up generating traffic to even one more node, through one that doesn't host either the calling service or the service being called.

Example:
Service X running on host A
Service Y running on host B
Random host C

Service X wants to connect to service Y through the ingress network (say they run in different overlay networks for security purposes or whatever). It has the IPs of hosts A, B, and C as endpoints. Luckily, ends up on C. C decides that it doesn't have the service Y that is being called, B does. As such, all traffic goes through C, with no reason whatsoever.

As such, I'd say that this "lowest latency" thing should be on both sides:

1. When directing connections TO the mesh network from inside the containers, I'm not sure how this is supposed to work. Maybe provide something like the possibility to automatically expose the mesh/ingress IP of the host running the container as a DNS name for the containers running in that host?
2. When directing connections received by an ingress/mesh network endpoint to the service. I would guess this should be something like a flag, since the current behavior might still be wanted in some cases as it would spread the workload better in many scenarios. I propose this one formulated in a different way in #28105, but would achieve kind of the same thing.

**Comment by FlorinAsavoaie** [comment]
An explanation for the close, please?

**Comment by krasi-georgiev** [comment]
5 months without any comments 
with no interest I don't think it will get implemented.
