### ISSUE TITLE
Windows 10 Pro Shared File access-  password won't work even after removing $

### ISSUE THREAD

**Issue by scargill** [docker/docker#25695]
I've changed my Windows login password after reading that Docker can't handle certain symbols - still no joy - simple CANNOT login to initiate volume sharing therefore cannot user Docker.

**Comment by thaJeztah** [comment]
Thanks for reporting, @scargill. A dedicated issue tracker for Docker for Windows was opened recently; since this is specific to Docker for Windows, could you report your issue there? I looks like there's already an open issue that you can subscribe to; https://github.com/docker/for-win/issues/35

I'll close this issue here, but thanks again for reporting, and feel free to comment after I closed
