### ISSUE TITLE
Changing container network

### ISSUE THREAD

**Issue by sburnwal** [docker/docker#25724]
I created some containers in a custom network using the 'docker create -net ...' command. However I need to change the network of my containers now. Is there a way to change the network of container(s) ?

**Comment by thaJeztah** [comment]
Yes, you can `docker network disconnect`, then `docker network connect` to connect to the other network. See https://docs.docker.com/engine/reference/commandline/network_connect/,  and the networking user guide; https://docs.docker.com/engine/userguide/networking/

I'll close this issue, because the GitHub issue tracker is not a support forum, but for tracking bugs and feature requests, but feel free to continue the discussion after I closed

**Comment by sburnwal** [comment]
Thank you for the quick response! Will try out the suggestion.
