### ISSUE TITLE
selinux spec: warning on installing docker-engine-selinux

### ISSUE THREAD

**Issue by coolljt0725** [docker/docker#25741]
Build rpm packages using spec in `hack/make/.build-rpm`,
the `docker-engine-selinux` rpm installing will show a warning
````
warning: docker-engine-selinux-1.11.2-1.el7.centos.noarch.rpm: Header V4 RSA/SHA                                         512 Signature, key ID 2c52609d: NOKEY
restorecon:  lstat(/var/lib/docker) failed:  No such file or directory
warning: %post(docker-engine-selinux-1.11.2-1.el7.centos.noarch) scriptlet failed, exit status 255
````
Download the rpm from https://yum.dockerproject.org/repo/main/centos/7/Packages/
and it has the same problem.
Is this warning should be ignored and how to avoid this warning ?
ping @rhatdan

**Comment by rhatdan** [comment]
Looks like it could be ignored.  You are installing docker-engine-selinux before installing docker-engine, so /var/lib/docker has not been created.  Should look for this in the post install script of docker-selinux.

Since you are installing docker second, it should set the label during the transaction.

**Comment by coolljt0725** [comment]
@rhatdan  thank you

**Comment by hqhq** [comment]
@coolljt0725 Would there be any warnings if you touch `/var/lib/docker` before installing docker-engine-selinux?

**Comment by coolljt0725** [comment]
@hqhq  If we create `/var/lib/docker` before installing docker-engine-selinux, there is no warnings any more
