### ISSUE TITLE
Allow user to set predefined token when swarm init

### ISSUE THREAD

**Issue by fphilippon** [docker/docker#25752]
Hello,

Following #24430, having the ability to set our own token when initializing a swarm could be a great help in order to automatize creation of swarms using some configuration management tools like Chef & cie.

We could have a sub-command "set" under the docker swarm join-token option.

Do you think we could have this for the upcoming releases?

Thanks.

**Comment by justincormack** [comment]
There has been no change in the discussion in #24430, where the ability to generate your own token was intentionally removed, so this is not going to be changed.

We are aware that it makes cluster setup more difficult in some situations, but it should not be impossible to do with the generated tokens. Feel free to discuss how to do that here or open another issue, but I will close this as it is not due to change.

**Comment by websitesca** [comment]
+1

**Comment by adamkdean** [comment]
It's sad to see the ability to provide predefined tokens has been removed to save users from themselves. It's like removing knives from a kitchen because you may cut yourself if you use them wrong. Now we have no knives and can't cut anything.

**Comment by qli-aa** [comment]
+1

**Comment by igorgatis** [comment]
Please, at least provide us with an example of how to make cluster automation in this case. A terraform or ansible example would be really appreciated.
