### ISSUE TITLE
service update "--mount-add" fails with "duplicate mount point"

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#25772]
Updating a service to replace a volume with a different volume fails with "duplicate mount point"

To reproduce:

``` bash
$ docker service create --name=foo --mount type=volume,source=volume1,target=/foo nginx:alpine
foo

$docker service update --mount-add type=volume,source=volume2,target=/foo foo
foo
```

Then see tasks failing:

``` bash
$ docker service ps foo

ID                         NAME             IMAGE         NODE          DESIRED STATE  CURRENT STATE            ERROR
0c7uelw2fk0qkeneww14g553m  foo.1      nginx:alpine  7e44720a5b2a  Ready          Rejected 1 second ago    "Duplicate mount point '/foo"
ckhrp1iq2rh5ehabqxw5992e2   \_ foo.1  nginx:alpine  7e44720a5b2a  Shutdown       Rejected 6 seconds ago   "Duplicate mount point '/foo"
38ycpjw10baw0lyfr7sjuhnul   \_ foo.1  nginx:alpine  7e44720a5b2a  Shutdown       Rejected 11 seconds ago  "Duplicate mount point '/foo"
1mz8x3nwhj3hrxtjlbtbic9y3   \_ foo.1  nginx:alpine  7e44720a5b2a  Shutdown       Rejected 16 seconds ago  "Duplicate mount point '/foo"
0k3oycgrzzurzoi8pvjg6teg0   \_ foo.1  nginx:alpine  7e44720a5b2a  Shutdown       Rejected 20 seconds ago  "Duplicate mount point '/foo"
```

``` bash
$ docker inspect 0c7uelw2fk0qkeneww14g553m
...
"Status": {
    "Timestamp": "2016-08-16T21:09:40.972455571Z",
    "State": "rejected",
    "Message": "preparing",
    "Err": "Duplicate mount point '/foo'",
    "ContainerStatus": {}
},
...
```

Tested on current master, https://github.com/docker/docker/commit/641e1564cfeb3f94f68f3c43a353df10331afecf

**Comment by kunalkushwaha** [comment]
Error is raised due to duplicate mount entries for same target at [daemon/volumes.go#L133](https://github.com/docker/docker/blob/480d7b310b2b063621eb260aff34e34171694ae3/daemon/volumes.go#L133)

But the actual problem is , while updating the mount point, mount point should be replaced, instead of blindly appending the mount list at [api/client/service/update.go#360](https://github.com/docker/docker/blob/master/api/client/service/update.go#L360).
- It should be checked, if target is same, then update the entry instead of appending it.

If solution sounds okay, I can make a PR.

**Comment by thaJeztah** [comment]
That'd be awesome, @kunalkushwaha

**Comment by stevvooe** [comment]
@kamigerami This fix needs to happen on the swarmkit side.

**Comment by kunalkushwaha** [comment]
@stevvooe Do you mean also need to fixed in swarmkit for [swarmctl](https://github.com/docker/swarmkit/blob/master/cmd/swarmctl/service/flagparser/volume.go#L27) ?

**Comment by stevvooe** [comment]
@kunalkushwaha SwarmKit validates the mounts. These _must_ be checked by the manager in the Control API. None of this can be client side.

**Comment by kunalkushwaha** [comment]
@stevvooe  Control API, seems to be validating and checking the specs for errors. But they are not modifying the specs.

But this issues is at new specs creation from docker cli arguments, so fix at cli is better place. I think a validation function for mounts similar to https://github.com/docker/swarmkit/blob/master/manager/controlapi/service.go#L188, could be added for mounts. 
Or
modifying specs, in case same targets for mounts are found in spec make will right approach? I fear modifying specs in swarmkit may introduce some unexpected behavior in long term.

With ref to https://github.com/docker/docker/pull/25974#issuecomment-243020325 
/cc @tonistiigi

**Comment by stevvooe** [comment]
@kunalkushwaha Uh, validate that the mounts are unique on the target side and reject it. You _cannot_ safely do this on the client-side.

The client side can validate that it is not sending bad data and show an error message, but this fix belongs on the server.

There should be no modification of specs on the swarmkit side. I'm not sure where I told you to do that.

**Comment by kunalkushwaha** [comment]
>validate that the mounts are unique on the target side and reject it. You cannot safely do this on the client-side.

@stevvooe I got your point :)
But the validation part  already exist at server side and as update command creates duplicate  mount points for same mount target ,  it fails the request [ daemon/volumes.go#L133](https://github.com/docker/docker/blob/480d7b310b2b063621eb260aff34e34171694ae3/daemon/volumes.go#L133)

> The client side can validate that it is not sending bad data and show an error message, but this fix belongs on the server.

My fix is to build the update request properly. i.e. instead of appending volume, replace existing mount point with new mount details. 
The test function also only validates, if list is of mount points is created/modified properly or not.

I am still little confused, if you really mean to perform these modification at server side.

**Comment by stevvooe** [comment]
@kunalkushwaha I am not suggesting any modifications on the server side. I am suggesting that these are validated properly in the swarmkit controlapi. The referenced daemon code is much too late in the process to correctly validate this.

**Comment by kunalkushwaha** [comment]
@stevvooe understood :). Will make a PR in swarmkit for validation.

**Comment by stevvooe** [comment]
@kunalkushwaha Thanks! Let me know if you need any help!

**Comment by xiaods** [comment]
this issue is PR done. close wait for merged the patch.

**Comment by srikalyan** [comment]
This issue should be closed as I can confirm that docker 1.12.2 has fixed the problem.

**Comment by thaJeztah** [comment]
@srikalyan I don't think it's fixed on 1.12.2; check the output of `docker service ps foo` and see that tasks are failing.

**Comment by srikalyan** [comment]
@thaJeztah Sorry for the false alarm seems like it does not work. Just too excited I guess :p

**Comment by thaJeztah** [comment]
@srikalyan I didn't check on "master" yet, possibly it's fixed already (depends on if the SwarmKit changes were brought in in this repository)
