### ISSUE TITLE
docker.io/wordpress image does not allow wordpress plugin uploads

### ISSUE THREAD

**Issue by Chaz6** [docker/docker#25840]
I followed the guide at https://docs.docker.com/compose/wordpress/ to set up wordpress in docker, however when I try to upload a (paid-for) wordpress plugin, it shows the following message:-

The uploaded file exceeds the upload_max_filesize directive in php.ini.

The size of the plug-in file is 2.2M.

**Comment by dsifford** [comment]
> The uploaded file exceeds the upload_max_filesize directive in php.ini.

Have you tried changing the `upload_max_filesize` directive in your `php.ini` file? Or, an even easier solution, `docker cp` the folder directly into the wordpress container do circumvent using the built-in uploader?

**Comment by thaJeztah** [comment]
Official images ship with a _default_ configuration, and need to be configured for your use case (usually by extending the image, or for frequently used configuration changes, sometimes through environment variables). 

However, this looks to be an issue with the official images, and there's a separate issue tracker for that; https://github.com/docker-library/wordpress/issues

I hope the information above helps you further, but if you think improvements need to be made, please open an issue in the issue tracker I linked

I'll close this issue here

**Comment by Chaz6** [comment]
Thanks @thaJeztah, I did try to find some official support page for the docker images but I did not come across the page you mentioned.

@dsifford I could not find any information how to set this in a docker image. I looked at the issues page linked, and it seems there is support for being able to specify this limit using an environment variable.

**Comment by dsifford** [comment]
@Chaz6 check out [this repo](https://github.com/visiblevc/wordpress-starter)

**Comment by patmccormick** [comment]
Wordpress starter repo has the same, time-killing bug.  I wish there weren't so many posts that don't work - including everything posted here.

**Comment by dsifford** [comment]
@patmccormick it’s not a bug. All you need to do is increase the `post_max_filesize`directive in your `php.ini` file. This is a common issue in a lot of 3rd party themes and plugins. So common, in fact, that some hosting providers bump the `post_max_filesize` directive above the default from the start.

**Comment by patmccormick** [comment]
I've done that and it doesn't change the value that PHP uses. It stays at 2mb.  Also tried a separate user.ini in attach volume - no change. Still 2mb.  I can't find a syntax for adding an environment variable for it in the WP container either. I agree that it's common, but those themes and plugins are being installed in other environments. None of them can be uploaded to a 2mb limited Docker container.

**Comment by dsifford** [comment]
You need to reload the configuration by restarting apache after you make any changes.

**Comment by thaJeztah** [comment]
The official images on Docker Hub use the default configuration as specified by upstream projects. For example, the [default value for `upload_max_filesize` in PHP is 2M](http://php.net/manual/en/ini.core.php#ini.sect.file-uploads) (also see the [sample configuration files](https://github.com/php/php-src/blob/4a6f83fe6f1663b47434c4799c47a31e3b304ae5/php.ini-production#L822-L824), and [source](https://github.com/php/php-src/blob/d92a701a3bb99fe8dbaa341589c2fc1e5010a6b8/main/main.c#L601-L602)).


From [the PHP documentation](http://php.net/manual/en/ini.core.php#ini.post-max-size):

> post_max_size integer
> Sets max size of post data allowed. This setting also affects file upload. To upload large files, this value must be larger than upload_max_filesize. Generally speaking, memory_limit should be larger than post_max_size. 

A standard PHP installation (and the official images on Docker Hub) doesn't come with a php.ini file; you'll have to add one with the configuration that fits your requirements. You can find some discussion on this topic here; https://github.com/docker-library/php/issues/163, https://github.com/docker-library/php/issues/182, https://github.com/docker-library/php/issues/311, and for the WordPress image: https://github.com/docker-library/wordpress/issues/10

The use of these images varies widely, and while for _your_ use-case, an unlimited upload may be desirable, for others it may not be. If you read the quote from the PHP documentation above, you'll also see that upload size relates to memory use as well, which can easily be misused for a DOS attack.

A common use of containers is to run them "immutable"; for WordPress this may be that the container is run with a read-only filesystem. This allows you to know _exactly_ what runs in production and prevents security issues due to people being able to make modifications to the code.

As mentioned in my earlier comment; https://github.com/moby/moby/issues/25840#issuecomment-240894231; This is an issue with the official images, not the source code that's maintained in this repository, and there's a separate issue tracker for that; https://github.com/docker-library/wordpress/issues

If you think improvements need to be made, please open an issue in the issue tracker I linked. If you have specific requirements for your use-case; extending the official images (`FROM wordpress`) and making changes that are needed for your situation may be what you're looking for.
