### ISSUE TITLE
FEATURE REQUEST: Don't pass volumes defined in Dockerfile but not provied in docker run command line to volume driver

### ISSUE THREAD

**Issue by liubin** [docker/docker#25875]
Docker 1.12

## Now action:

I have VOLUME instruction in Dockerfile:

```
VOLUME ["/var/lib/mysql", "/var/lib/postgres"]
```

And run Docker with self-developed volume driver:

```
docker run -v my-vol:/var/lib/mysql --volume-driver=my-driver img cmd
```

This will failed because I have not a volume for `/var/lib/postgres`.

## Reason

By `-v my-vol:/var/lib/mysql` only for one volume, Docker will **_aslo_** pass the other volume `/var/lib/postgres` to volume driver(use an auto generated volume-name like `06dda0d5dd1c2108ae0f0b6d0769c020d789d31953ec68afd8940ef42e8d7c7b` that used by `local` drvier).

## Action Expected

I think, pass only `my-vol:/var/lib/mysql` to volume driver, and the other(`/var/lib/postgres`) not specified by `docker run` command line should be processed by Docker` local` driver but not passed to custom volume driver.

**Comment by cpuguy83** [comment]
This makes for incredibly confusing behavior.
I think we just have some major shortcomings in the available syntax for expressing volumes. We will be most likely bringing in the "--mount" flag from `docker service create` to `docker run` which is much more expressive.

**Comment by thaJeztah** [comment]
We actually changed this at some point in https://github.com/docker/docker/pull/19175, but that would be a breaking change, so that was reverted in https://github.com/docker/docker/pull/19190. _However_, there's an open pull-request to implement the `--mount` flag for `docker run` (see https://github.com/docker/docker/pull/26825), which would allow you to specify a driver _per volume_, similar to what's possible on services https://github.com/docker/docker/blob/master/docs/reference/commandline/service_create.md#add-bind-mounts-or-volumes

I'll close this issue, but feel free to comment
