### ISSUE TITLE
Enhancement - friendly message for: client is newer than server

### ISSUE THREAD

**Issue by alexellis** [docker/docker#26141]
I got the following message today and I've seen it many times before: "Error response from daemon: client is newer than server. I know that there is a workaround which maybe should come with a disclaimer about how far back it can go in the form of `ENV DOCKER_API_VERSION`.

On the #general slack channel we were chatting with @vdemeester about improving the UX around the error message. I thought this change may have been suggested before and rejected but didn't find it in the issue search history. Hope I am not treading on anyone's toes with this suggestion or going over a moot point. 

Actual:

```
$ docker ps
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
```

Expected:
```
$ docker ps
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
Note: client API version can be set via DOCKER_API_VERSION environmental variable
```

I'd expect the change to be relatively straight-forward (but I could be wrong). If the change is approved and not too hard too complex I'd like to get dibs on the go changes.

![](https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTz_iIxYHOFFz0ZumWGLfFVji1NsodTRazJGzVMuPpvtftTv1-F)

**Comment by cpuguy83** [comment]
Honestly, this env var was created for dev purposes and we really didn't want it to escape that since there is no guarantee that the client will be able to handle the response from the daemon or provide the expected results to the user.

We are working on (finally) getting rid of this version requirement and have the client itself be backwards-compat with the daemon... where as right now only the daemon is backwards compatible. See #25498

**Comment by icecrime** [comment]
Agreed with @cpuguy83, this environment variable is pretty much a lie, but doesn't do anything to cope with versions discrepancies. We're working on it, hopefully we'll have a solid answer by 1.13.0!

I'm closing this one, but please track #25498.
