### ISSUE TITLE
Convert unit tests to use gocheck

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#26175]
Right now the integration tests are using gocheck for having things in suites but we also have unit tests that use the stdlib's `testing` package.  

We need to change all the unit tests to use gochecks suites and not use the stdlibs testing package.

Some of the unit test files are:

https://github.com/docker/docker/blob/master/daemon/daemon_linux_test.go
https://github.com/docker/docker/blob/master/daemon/daemon_test.go
https://github.com/docker/docker/blob/master/daemon/daemon_unix_test.go

etc...

**Comment by michelvocks** [comment]
#dibs

**Comment by vdemeester** [comment]
@crosbymichael I wonder why using `gocheck` instead of the stdlib `testing` would benefit :sweat_smile:  (I tend to like and stick to `testing` for unit tests as it's simple)

**Comment by crosbymichael** [comment]
@vdemeester because we are going to have it output xunit support so that jenkins can parse it and every test will do the same

**Comment by crosbymichael** [comment]
@michelvocks thanks!

**Comment by vdemeester** [comment]
@crosbymichael hum ok sounds fair (but still, https://github.com/tebeka/go2xunit makes it that we can do it with testing).
@michelvocks thanks 👼 the PR is a bit huge (and thus hard to review) — we might want to do smaller ones I think 😝

**Comment by stevvooe** [comment]
Why do we consider `gocheck` to be "better" than the stdlib? I can't count the hours wasted due to the use of "clever" unit testing frameworks. The worst part is that contributors now need to learn Go and whatever framework is used for testing.

If we are simply looking for xunit output, there is https://github.com/tebeka/go2xunit.

With Go 1.7 [subtests](https://golang.org/pkg/testing/#hdr-Subtests_and_Sub_benchmarks) and `TestMain`, frameworks that subdivide individual tests are much less beneficial.

I have written about this before, but the problems stem from examples like the redefinition of a [`nil` check to include if the interface value is `nil`](https://github.com/go-check/check/blob/v1/checkers.go#L117). If you are testing what [`x == nil` will do, this is incorrect](https://play.golang.org/p/1gq91ynJe7). This is just the tip of the iceberg. Equivalence is another area where things can get problematic.

Also, note that use of such frameworks may prevent us from running tests in parallel (at least, I don't see the option in gocheck).

**Comment by aaronlehmann** [comment]
I'm also skeptical of the benefits of porting the unit tests to go-check.

I'm not averse to testing frameworks in general, but I don't particularly like go-check. I find the `Assert` method confusing even after working with go-check for a long time (it involves expressing logic by building up an argument list to a function). And it also deviates from the standard `testing` package so there's a nonstandard way to choose which tests to run, and it's difficult to call code that's written using the `testing` package or run tests in parallel.

I think `github.com/stretchr/testify/assert` does a better job with these things, but I don't see a compelling reason to port the unit tests to it either.

**Comment by tonistiigi** [comment]
Closing as #26393 was not accepted.
