### ISSUE TITLE
How does it work? Docker overlay? gwbridge?

### ISSUE THREAD

**Issue by wyxgit** [docker/docker#26194]
Two docker hosts, etcd as kvs. Etcd is healthy.

```
docker network create --driver overlay --subnet 10.60.1.0/24 overlaynet
```

The normal way to add a container to an overlay network does not work. The problem is the network connectivity to overlay...

```
docker run -it --name debianTEST --net overlaynet  debian bash
```

In this case the container is attached to two networks by default (gwbridge and overlay):

```
root@773d1c2594e0:/# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
574: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether 02:42:0a:3c:01:03 brd ff:ff:ff:ff:ff:ff
    inet 10.60.1.3/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:aff:fe3c:103/64 scope link 
       valid_lft forever preferred_lft forever
576: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:12:00:05 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.5/16 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe12:5/64 scope link 
       valid_lft forever preferred_lft forever
```

I would like to ping a container on another host connected to the overlaynet also:

```
root@773d1c2594e0:/# ping 10.60.1.8
```
......no answer.

Why?
I checked, no special iptables rule has been added after creating the overlay net.

**Comment by gittycat** [comment]
Post your `docker info` and `docker version`. It's not clear whether you're using swarm mode or legacy swarm, amongst other info.

**Comment by thaJeztah** [comment]
I'm closing this issue, because there's not enough information here. 

More information about overlay networking with an external k/v store (https://docs.docker.com/engine/userguide/networking/get-started-overlay/#/overlay-networking-with-an-external-key-value-store) or in Swarm mode (https://docs.docker.com/engine/userguide/networking/get-started-overlay/#/overlay-networking-and-swarm-mode) can be used in the documentation.

Always make sure that the required ports for overlay networking are open between hosts; https://docs.docker.com/engine/swarm/swarm-tutorial/#/open-ports-between-the-hosts
