### ISSUE TITLE
Manually kill docker-containerd-shim during daemon down make the container can't be stoped after daemon restart 

### ISSUE THREAD

**Issue by coolljt0725** [docker/docker#26374]
**Output of `docker version`:**

```
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.6.3
 Git commit:   a8f79e5
 Built:        Wed Sep  7 04:30:12 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.6.3
 Git commit:   a8f79e5
 Built:        Wed Sep  7 04:30:12 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Steps to reproduce the issue:**
1. start docker daemon with `--live-restore` flag and run a container
````
$ docker run -tid busybox
e826c7cdbbb10d55d881e416196c8e70873c39189f6e7d46224038364a1ed86d

````
2. shutdown the docker daemon and kill the docker-containerd-shim
````
[lei@fedora image]$ ps aux | grep e826c7cdbbb10d55d881e416196c8e70873c39189f6e7d46224038364a1ed86d
root     25765  0.0  0.0 334768  3556 ?        Sl   10:16   0:00 docker-containerd-shim e826c7cdbbb10d55d881e416196c8e70873c39189f6e7d46224038364a1ed86d /var/run/docker/libcontainerd e826c7cdbbb10d55d881e416196c8e70873c39189f6e7d46224038364a1ed86d docker-runc
lei      25852  0.0  0.0 118928  2308 pts/15   S+   10:16   0:00 grep --color=auto e826c7cdbbb10d55d881e416196c8e70873c39189f6e7d46224038364a1ed86d
[lei@fedora image]$ sudo kill -9 25765
[sudo] password for lei:

````
3. restart docker daemon and the container still exist in `docker ps`, but we can't kill it
````
[lei@fedora image]$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS               NAMES
e826c7cdbbb1        busybox             "sh"                About a minute ago   Up About a minute                       tiny_elion
[lei@fedora image]$ docker kill e826c7cdbbb1
e826c7cdbbb1
[lei@fedora image]$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS               NAMES
e826c7cdbbb1        busybox             "sh"                About a minute ago   Up About a minute                       tiny_elion

````
and during docker kill the daemon log is 
````
DEBU[0028] Sending kill signal 9 to container e826c7cdbbb10d55d881e416196c8e70873c39189f6e7d46224038364a1ed86d
WARN[0028] container kill failed because of 'container not found' or 'no such process': Cannot kill container e826c7cdbbb10d55d881e416196c8e70873c39189f6e7d46224038364a1ed86d: rpc error: code = 2 desc = no such process
INFO[0038] Container e826c7cdbbb1 failed to exit within 10 seconds of kill - trying direct SIGKILL
DEBU[0038] Cannot kill process (pid=25780) with signal 9: no such process.

````

**Describe the results you expected:**

The container should not be seen as running
**Additional information you deem important (e.g. issue happens only occasionally):**

ping @mlaventure  will https://github.com/docker/containerd/pull/311 fix this?

**Comment by mlaventure** [comment]
@coolljt0725 I doubt it, since in that case there will be no subreaper so the child will be handed back to the init process.

I'll try it. If it doesn't work, I'll try to update the loadprocess to take this scenario in account.

**Comment by ravilr** [comment]
@mlaventure  is this fixed?
Server Version:      1.12.0
running into same issue on node reboot. docker daemon has live-restore turned on. On node reboot, daemon fails to recover containers (which is expected), but `docker ps` lists all the previously running containers (before the reboot) as running.  trying to kill them fails with the same error as in this issue:

Sep 14 06:48:13 s6 systemd[1]: Starting Docker Application Container Engine...
Sep 14 06:48:16 s6 dockerd[2416]: time="2016-09-14T06:48:16.238564101Z" level=error msg="containerd: notify OOM events" error="open /proc/1352/cgroup: no such file or directory"
Sep 14 06:48:16 s6 dockerd[2416]: time="2016-09-14T06:48:16.268387865Z" level=error msg="containerd: notify OOM events" error="open /proc/41870/cgroup: no such file or directory"

Sep 14 06:48:25 s6 dockerd[2416]: time="2016-09-14T06:48:25.555124496Z" level=error msg="Failed to restore f7d500974b1dbf13d86f5bea598ec237d151a075f1d06a3ad12cfc8d8a2
f9068 with containerd: rpc error: code = 13 desc = get all pids for container: exit status 1: \"open /run/run/f7d500974b1dbf13d86f5bea598ec237d151a075f1d06a3ad12cfc8d8a2f9068/state.json: no such file or directory\\n\""
Sep 14 06:48:25 s6 dockerd[2416]: time="2016-09-14T06:48:25.566350382Z" level=error msg="Failed to restore c572eb593cd05b56900add271825735d3b300274a297380de83f6df6fa0
1280e with containerd: rpc error: code = 13 desc = get all pids for container: exit status 1: \"open /run/runc/c572eb593cd05b56900add271825735d3b300274a297380de83f6df6fa01280e/state.json: no such file or directory\\n\""

Sep 14 06:48:40 s6 dockerd[2416]: time="2016-09-14T06:48:40.019490876Z" level=warning msg="container kill failed because of 'container not found' or 'no such process': Cannot kill container 231cb5578523517bf8a6c8ad6a1fce367c643214d04f650adb9b3e68f59f8c71: rpc error: code = 2 desc = no such process"
Sep 14 06:48:40 s6 dockerd[2416]: time="2016-09-14T06:48:40.019575344Z" level=warning msg="container kill failed because of 'container not found' or 'no such process': Cannot kill container bf5b2b4410e55b7ef46d7dd6fbc0967bab7c0a1e676f270d6e15f6f97c111a6d: rpc error: code = 2 desc = no such process"

**Comment by coolljt0725** [comment]
@ravilr  https://github.com/docker/containerd/pull/313 should have fixed this issue, but I haven't tested it. :)
@mlaventure From what I know, the fix for such issues is on the containerd  side. On the docker daemon side, Should we also make the container to non-running if we get `no such process` from containerd if we try to kill/stop a container which show in docker ps?

**Comment by mlaventure** [comment]
@coolljt0725 that's probably a good idea yes, do you want to make the PR for it? :)

has for the fix, it's not working properly for this case, I'll include the fix with docker/containerd#317

**Comment by coolljt0725** [comment]
@mlaventure  sorry for late response, had to a 3-day vacation for the mid-autumn festival holiday :)

after digging this deeper, I think a better fix on the daemon side is to make the fake running containers(
show in docker ps but the container is not actually running) to non-running state on daemon starting.
On daemon starting, if the `container .IsRunning`  is true, then make sure the container is actually running.
WDYT?

**Comment by mlaventure** [comment]
@coolljt0725 once `containerd` is fixed the daemon should correctly receive the `exit` event for it.

But in order to be future proof, on restart if the `Restore` call for the container fails (see [here](https://github.com/docker/docker/blob/master/daemon/daemon.go#L192)), we should probably remove it from the running state indeed. Maybe mark it as `Dead`? Or maybe a new state to be more explicit (e.g. `Unavailable`)

cc @tonistiigi

**Comment by tonistiigi** [comment]
@mlaventure In case containerd can't report correct data about a container, docker will set the container as exited even if there is no exit event. They will just get `exitcode=1`.

**Comment by mlaventure** [comment]
@tonistiigi at the moment the container is left in the running state in the case where the container is not found by `containerd` (see [here](https://github.com/docker/docker/blob/master/libcontainerd/client_linux.go#L530) and [here](https://github.com/docker/docker/blob/master/libcontainerd/client_linux.go#L563))

**Comment by coolljt0725** [comment]
@tonistiigi  
>In case containerd can't report correct data about a container, docker will set the container as exited even if there is no exit event. They will just get exitcode=1

I don't find the code where get this done, maybe I miss something

**Comment by tonistiigi** [comment]
@coolljt0725 I was referring to the place where containerd doesn't know about the container and responds "container not found" https://github.com/docker/docker/blob/master/libcontainerd/client_linux.go#L546-L555

**Comment by ravilr** [comment]
@mlaventure are your fixes going to be included in next docker release 1.12.2 ? Thanks.

**Comment by mlaventure** [comment]
@ravilr they are, could you try the rc to see if it works for you?

**Comment by ravilr** [comment]
@mlaventure i did a quick test with 1.12.2. After node reboot, the previously running containers before the reboot, doesn't show up in `docker ps` output now. Thanks.

**Comment by coolljt0725** [comment]
@ravilr  Thank your for your test. 
@mlaventure  I have tested, my issue are also fixed.  
closing
