### ISSUE TITLE
docker-compose with swarm mode

### ISSUE THREAD

**Issue by omipandey** [docker/docker#26370]
**Output of `docker version`:*1.12*
[root@msedgewin10 swarm]# docker-compose exec  manager docker swarm init --listen-addr 172.16.100.203:2377
rpc error: code = 2 desc = oci runtime error: exec failed: exec: "docker": executable file not found in $PATH

**Output of `docker info`:**
[root@msedgewin10 swarm]# docker info
Containers: 5
 Running: 2
 Paused: 0
 Stopped: 3
Images: 56
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-251:1-2232182-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.965 GB
 Data Space Total: 107.4 GB
 Data Space Available: 5.368 GB
 Metadata Space Used: 4.018 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.1.12-37.6.3.el7uek.x86_64
Operating System: Oracle Linux Server 7.2
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 987.3 MiB
Name: msedgewin10
ID: EGUE:UP7T:6D5W:P4VY:POOZ:ZM6S:7JKT:TLFT:BBRA:2BYE:XM2J:ZOGP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 172.16.100.55:5000
 127.0.0.0/8

```
**Additional environment details (AWS, VirtualBox, physical, etc.):**



**Steps to reproduce the issue:**
1. docker-compose build 
2.docker-compose up
3.docker-compose exec  manager docker swarm init --listen-addr x.x.x.x:2377

**Describe the results you received:**
docker-compose up is working properly.i got the containers running.
there are two services inside docker-compose.yml file .1.manager 2.worker 
i am trying to start swarm with docker-compose 
i am following this video .here is the link ..     ---- https://www.youtube.com/watch?v=tlEurzT-KDQ
**Describe the results you expected:**
swarm mode should start after the last command .

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
`docker-compose` does not work with swarm mode.

`docker-compose exec` is meant for running a command in an existing compose service (this is akin to `docker exec <container>`), not for executing arbitrary commands.
The error message you are seeing is because it's trying to exec `docker` in a service container called `manager` and it's not finding it.

You can export your compose services to a DAB file which can then be imported into docker with `docker deploy` (experimental build only). Not all compose options are supported with this method.

**Comment by omipandey** [comment]
okay .but can you please take a look in that video link --- https://www.youtube.com/watch?v=tlEurzT-KDQ
i don't know how but i think the guy is using docker-compose with swarm mode in docker 1.12

**Comment by cpuguy83** [comment]
He's using docker-in-docker via compose and using compose to execute commands in those docker daemon containers.

**Comment by omipandey** [comment]
but i have also i defined docker-compose.yml in which i have defined manager as a service .
so by calling "docker-compose exec manager " .it should work.but it's not .

**Comment by cpuguy83** [comment]
@omipandey What images are you building? The person in the video is using the `docker:dind` image specifically because these have docker built-in, and actually run docker.

For help figuring all this out, please use forums.docker.com or #docker on IRC.
The issue tracker isn't really a great place to offer support.

**Comment by jpalanco** [comment]
Is it possible to run compose over standard swarm instead of swarm mode? In my case my instances are not able to virtualise, so I have no chance to use docker-machine and it seems almost all the documentation refers to docker-machine.

As far as I understood I need to setup 1 or more instances of swarm, at least 1 instance of consul (or etcd) and as many worker nodes as I want.

I run consul like this:
docker run -d -p 10.0.0.8:8500:8500 --name=consul progrium/consul -server -bootstrap

Then I modify /lib/systemd/system/docker.service to launch docker like this for the swarm master:

ExecStart=/usr/bin/dockerd -H tcp://10.0.0.1:2375 -H unix:///var/run/docker.sock

In my 2 nodes I execute this, to join the cluster:

docker run -d swarm join --advertise=10.0.0.4:2375 consul://10.0.0.8:8500
docker run -d swarm join --advertise=10.0.0.5:2375 consul://10.0.0.8:8500

I go to any of the nodes and I setup the docker host as the master:
export DOCKER_HOST=tcp://10.0.0.1:4000

When I execute docker info, I see the 2 nodes joined to the cluster.

But when I want to execute "docker-compose up -d" I receive a message that the overlay network cannot be created in a worker node, if I go to the master to execute. If I 

As fas as I know 1.12 is backward compatible, so it should work.

I just want to use old swarm, I tried to launch the workers like this:

/usr/bin/dockerd -H tcp://10.0.0.4:2375 -H unix:///var/run/docker.sock --cluster-store=consul://10.0.0.8:8500 --cluster-advertise=tun0:2375

And I get this weird message:

FATA[0002] Error creating cluster component: --cluster-store and --cluster-advertise daemon configurations are incompatible with swarm mode 

I just dont want swarm mode, why I get this message?

Regards
