### ISSUE TITLE
Missing docker/notary/tuf/store package for docker/api/client/trust.go

### ISSUE THREAD

**Issue by nylon22** [docker/docker#26420]
**Output of `docker version`:**

```
github master branch
```

**Output of `docker info`:**

```
n/a
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

go 1.6.2

**Steps to reproduce the issue:**

1. go get github.com/docker/notary/tuf/store

**Describe the results you received:**

cannot find package "github.com/docker/notary/tuf/store"

**Describe the results you expected:**

Should be able to go get "github.com/docker/notary/tuf/store" 

**Additional information you deem important (e.g. issue happens only occasionally):**

docker/api/client/trust.go imports docker/notary/tuf/store package here: https://github.com/docker/docker/blob/master/api/client/trust.go#L39

**Comment by cyli** [comment]
I don't think `go get github.com/docker/notary/tuf/store` will work in this case, because that tries to look up the package in the latest version of notary, and that package has since been removed/refactored.

The docker project has vendored an [older version of notary (0.3)](https://github.com/docker/docker/blob/master/hack/vendor.sh#L103), which does have the package:  https://github.com/docker/docker/tree/master/vendor/src/github.com/docker/notary/tuf/store

You might want to check out that particular version of notary manually, either using git or `go get github.com/docker/notary`, then go to `$GOPATH/github.com/docker/notary` and `git checkout v0.3.0`
