### ISSUE TITLE
Proposal: --fixed-cidr for macvlan driver

### ISSUE THREAD

**Issue by npcode** [docker/docker#26474]
`--fixed-cidr` and `--fixed-cidr-v6` restricts the range of IPs to allocate for containers but seems to work only with bridge network.

It would be very useful if docker administrator can restrict the range of IPs for macvlan network by the options. I want to prevent that users create macvlan networks with inappropriate subnets and/or ip ranges.

**Comment by aboch** [comment]
The `--fixed-cidr` and `--fixed-cidr-v6` daemon options only take effect on the default network (which happens to be the `bridge` network).
Given the default network cannot be created via the `docker network` command and it is automatically created by the daemon, its parameters are configurable only via daemon level options.

For any other user-defined network which will be created via `docker network` command, user would use the `--subnet` and `--ip-range`. This is by design.

**Comment by LK4D4** [comment]
@aboch Thanks for an explanation. @npcode I hope answer is ok for you. Thanks!
