### ISSUE TITLE
Can't override ONBUILD build-arg

### ISSUE THREAD

**Issue by rawkode** [docker/docker#26533]
I have a Dockerfile:

```Dockerfile
FROM centos:6.7
...
ARG APP_NAME
ONBUILD COPY ./example /app/${APP_NAME}
...
```

and it is extended by another:
```Dockerfile
FROM parent
```

which I build with `docker build -t tag --build-arg APP_NAME=myapp .`

Unfortunately I can't defer the binding of the build argument

**Comment by duglin** [comment]
I think we need to run the ONBUILD sub-command thru the env var substitution logic - but only for certain sub-commands (e.g. RUN doesn't get processed).

**Comment by rawkode** [comment]
Is this relatively trivial? My Go knowledge is pretty solid, but I've not jumped into docker/docker too much.

**Comment by duglin** [comment]
@rawkode yup - I think it should be a good one for a docker newbie.

**Comment by duglin** [comment]
@rawkode actually I think I was mistaken. I'm not sure we can support this at all.  Hold off for a sec, let me do more investigation...

**Comment by duglin** [comment]
ok we can support this today but its kind of funky - but does make sense if you understand the total flow.

First, ONBUILD commands are run before ALL other Dockerfile commands, right after the FROM is processed.  This means that any `--build-arg`s put on the `docker build` command line will not impact the ONBUILD stuff because any ARG in the second Dockerfile won't be seen until after the ONBUILDs.    Also, note that ARGs from Dockerfile 1 will not known/transferred to Dockerfile 2.

(On a side note, this is one of the negative side-effects of forcing people to unnecessarily define these env vars at all via  a ARG cmd, but I'll defer that rant for later :-)  )

So, how do we fix this? Do this in your first Dockerfile:
```
FROM centos:6.7
...
ONBUILD ARG APP_NAME
ONBUILD COPY ./example /app/${APP_NAME}
...
```

This will insert a `ARG APP_NAME` into the 2nd Dockerfile during the ONBUILD processing and give you what you want.

btw - we do already run the ONBUILD cmds thru the env var substitution - so no code change should be needed.

**Comment by rawkode** [comment]
Thanks @duglin - adopting the funk and changing ARG` to `ONBUILD ARG` works as suggested :+1

**Comment by cheevo** [comment]
Excellent !Thanks .. Works for me by adding as u suggest the "ONBUILD ARG APP_NAME" tried a lot of permutations before reading your solution .

**Comment by francardoso93** [comment]
This thread helped me a lot. Just adding a quick info about this subject:
You might want to place default ARG values at Dockerfile 2 that will be used at Dockerfile 1. If that's the case, just add them before the "FROM" clause at Dockerfile2.

```
FROM centos:6.7
...
ONBUILD ARG APP_NAME
ONBUILD COPY ./example /app/${APP_NAME}
...
```

```
ARG APP_NAME='DefaultAppName'
FROM parent
...
```
