### ISSUE TITLE
How to create named volume with swarm mode on specific node?

### ISSUE THREAD

**Issue by vingrad** [docker/docker#26730]
How to create named volume with swarm mode on specific node?

Is there are any alternative to constraint 'node==worker1' ?

**Comment by thaJeztah** [comment]
Named volumes are created on the node where a service's task is scheduled, and you specify its definition using the `--mount` syntax (see https://github.com/docker/docker/blob/master/docs/reference/commandline/service_create.md#add-bind-mounts-or-volumes)

Constraints are also defined on the service; see https://github.com/docker/docker/blob/master/docs/reference/commandline/service_create.md#specify-service-constraints---constraint

I'll close this issue, because it's a question, not a bug (so better suitable for forums.docker.com), but feel free to continue the discussion
