### ISSUE TITLE
Service creation API documentation is incorrect

### ISSUE THREAD

**Issue by deviantony** [docker/docker#26807]
The actual documentation for the creation of a service using the Docker API is incorrect for the port publishing section (at https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/create-a-service)

The **Example request** specifies the following:

```json
POST /services/create HTTP/1.1
Content-Type: application/json

{
  ...
  "EndpointSpec": {
    "Ports": [
      {
        "Protocol": "tcp",
        "PublishedPort": 8080,
        "TargetPort": 80
      }
    ]
  },
 ...
}
```

This is totally correct, but the **JSON parameters** shows the following:

```
* Endpoint – Properties that can be configured to access and load balance a service.
  * Spec –
    * Mode – The mode of resolution to use for internal load balancing between tasks (vip or dnsrr).
    * Ports – Exposed ports that this service is accessible on from the outside, in the form of: "Ports": { "<port>/<tcp|udp>: {}" }
```

This is totally incorrect and can lead to confusion.

**Comment by thaJeztah** [comment]
Thanks for reporting @deviantony. This was also reported here: https://github.com/docker/docker/issues/23597#issuecomment-243324631, and was fixed by https://github.com/docker/docker/pull/26634, which should go out in an update to the online documentation soon.

I'll close this issue because this is fixed, but thanks again for reporting, and feel free to comment after I closed
