### ISSUE TITLE
docker tag via remote API to private registry returns "invalid reference format"

### ISSUE THREAD

**Issue by adityats** [docker/docker#26810]
---
## BUG REPORT INFORMATION

Briefly describe the problem you are having in a few paragraphs.
docker tagging works with CLI, i.e. "docker tag image-name 10.160.0.161:5000/se:sometag". When done programmatically, tagging the image fails with "invalid reference format"

**Steps to reproduce the issue:**
Image tagging with private repo with ":" in its value (private repos are required to be named with ":" separation between the hostname and the port)

**Describe the results you received:**
Image tag for a private repo fails with "{"message":"invalid reference format"}"

**Describe the results you expected:**
Image tag to succeed

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens always. However when I drop ":" from the private repo name, things work as expected.

**Output of `docker version`:**
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**

 Running: 0
 Paused: 0
 Stopped: 0
Images: 15
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-8:3-2235511-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.422 GB
 Data Space Total: 107.4 GB
 Data Space Available: 88.93 GB
 Metadata Space Used: 1.573 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-47-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67 GiB
Name: 10-160-1-101
ID: ANVT:6RLY:3SQY:WNT2:VPEL:JHDL:RC5B:UAFI:E4MW:YFW6:MJ4X:WPAS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: IPv4 forwarding is disabled
Insecure Registries:
 10.160.0.161:5000
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualMachine on VMWare running Ubuntu 14.04 (kernel : 3.19.0-47-generic x86_64)

**Comment by cpuguy83** [comment]
Can you provide more details? What does your API request look like?

**Comment by adityats** [comment]
docker tag 3da7766027e0 10.160.0.161:5000/ase:version-str, works

echo -e "POST /images/3da7766027e0/tag?repo=10.160.0.161:5000/ase&force=1&tag=version-str", threw an error

**Comment by cpuguy83** [comment]
@adityats If you put the daemon in debug mode, it will spit out the post form data as json. Might help to compare.

**Comment by pilgrim2go** [comment]
I got the same issue when tag ECR image.

```
docker.errors.APIError: 500 Server Error: Internal Server Error for url: https://192.168.99.100:2376/v1.24/images/sha256:32fed92ebc8116491bda87b2b0f9b92ba33e79c0e0fe785455dd279541abcdb6/tag?repo=two&tag=xxxxx.dkr.ecr.ap-southeast-1.amazonaws.com%2Fmyorg%2Ftest%3Alatest&force=1 ("invalid tag format")
```

**Comment by thaJeztah** [comment]
@pilgrim2go you nee do use `latest` as tag, and `xxxxx.dkr.ecr.ap-southeast-1.amazonaws.com/myorg/test` as repo-name;

```
https://192.168.99.100:2376/v1.24/images/busybox/tag?repo=xxxxx.dkr.ecr.ap-southeast-1.amazonaws.com%2Fmyorg%2Ftest&tag=latest
```

You can see these requests when putting the daemon in debug mode, and then check the logs

@adityats running

```
docker tag busybox 10.160.0.161:5000/ase:version-str
```

Performs this API call;

```
DEBU[0260] Calling POST /v1.24/images/busybox/tag?repo=10.160.0.161%3A5000%2Fase&tag=version-str
```

I'll close this issue because I don't think there's a bug here, but feel free to comment if you think there's something that needs to be fixed

**Comment by justinzyw** [comment]
@thaJeztah , I have exactly the same problem. The **BUG REPORT INFORMATION** that @adityats added discribed the problem accurately. The problem seems to do with "**:**" in query Parameters **repo** of the **tag** API call. The CLI works fine but **API** does NOT. 

In my case:

CLI command `docker tag ubuntu:latest myregistry:5000/ubuntu:latest` worked **fine**. Note that the CLI command contains ":" is there.

However, the same function through an API call `http://localhost:2375/images/ubuntu:latest/tag?repo=myregistry:5000/ubuntu&tag=latest` triggered the "invalid reference format" **error**.

Tried to remove the port info in the API call (as well as the ":") and `http://localhost:2375/images/ubuntu:latest/tag?repo=myregistry/ubuntu&tag=latest` worked **fine**.

Also tried to retain the port info and replace the ":" with "%3A" in the API Call and `http://localhost:2375/images/ubuntu:latest/tag?repo=myregistry%3A5000/ubuntu&tag=latest` threw the "invalid reference format" error.

I can not say for sure that this is an issue. Please help me to understand this.

**Comment by justinzyw** [comment]
@thaJeztah I removed my previous comment as I realized I was wrong on the conclusion that the problem lays in ":". It was actually the "_" which troubled me.

`sudo docker tag appname my_repo:5000/repo/appname` does not work as it contains a "_".
`sudo docker tag appname myrepo:5000/repo/appname` works fine.

**Comment by thaJeztah** [comment]
@justinzyw looks like the first part is an invalid hostname (underscores are not allowed in there), so docker sees `my_repo` as image name, and `5000/repo/appname` as tag name

**Comment by justinzyw** [comment]
@thaJeztah  thanks for your clarification!
