### ISSUE TITLE
Signed images

### ISSUE THREAD

**Issue by shykes** [docker/docker#2700]
Docker should support signing images after building them. This allows for a "chain of trust" where the content and origin of an image can be verified cryptographically regardless of how the image was distributed.

**Comment by stevvooe** [comment]
cc @endophage @diogomonica @NathanMcCauley

**Comment by cyphar** [comment]
GPG would work if we have a set of keys registered to accounts. Then you have to verify that the signature was signed by one of those keys. GPG has solved this problem already, I'm not sure why we don't just leverage it. The purpose of the WOT is not to provide authority for someone to sign something, it is to provide assurance that the key's owner is who the sender says it is. This is not really relevant in the Docker registry model, because we already have a central authority on "who's who". Revocation and other such things are going to be a pain though, but I can't really think of any nice way of pushing revocation lists to clients.

**Comment by dreamcat4** [comment]
@cyphar The solution was recently announced and demo'ed at dockercon 2015... the new 'notary' tool / library. You can see it in action during the dockercon 2015 keynote video.

https://github.com/docker/notary

**Comment by stevvooe** [comment]
@cyphar 

> This is not really relevant in the Docker registry model, because we already have a central authority on "who's who". Revocation and other such things are going to be a pain though, but I can't really think of any nice way of pushing revocation lists to clients.

This is a strong assumption. Can you always trust the registry? Should you have to?

**Comment by dstufft** [comment]
If you can trust the registry, then just use TLS.

**Comment by ewindisch** [comment]
A proposal to introduce https://github.com/docker/notary integration is in the works and should be linked to this issue once available.

**Comment by cyphar** [comment]
@stevvooe Well. Is there another way of giving authority to certain people? You can't have your cake and eat it. If you want to make sure that some random person doesn't sign bad images and send them to people then you need to have a central authority (that you then must trust) which will give you the list of people who own certain projects. The other option is for people to manually import keys they trust into their keyring -- and then the onus is on the user to make sure they *actually* trust the person whose key they are importing.

I prefer the latter, because it's how GPG is meant to work, but the issue is that you now need to be doubly sure that the person who signed it (and obviously has set `MAINTAINER` to reference them) is a person you trust to sign that particular image. Having a central authority fixes that problem, but then you need to trust the authority.

I guess you could argue that using WOT to map a key to a project or account *might* work (you get people to sign statements that say "this project belongs to this key -- this statement will expire on this date"), but that relies on people not randomly signing others as being owners of things. And it also relies on an active community to do so.

**Comment by cyphar** [comment]
Ultimately, I don't think that using the WoT model makes sense for Docker. We are a monolithic binary that manages containers that pulls images from a single registry. Nothing about this model seems to be a good fit for a distributed trust system like the WoT.

**Comment by stevvooe** [comment]
@cyphar I'd recommend you check out https://github.com/docker/notary. These issues are being considered in detail within that project.

While there will be an central authority, we want to decouple that authority from the registry. This makes sure the registry serves bits while something else takes care of the trust aspect. The two services have much different scaling and security requirements so decoupling them has many benefits.

**Comment by andrewwebber** [comment]
As a keep observer of this thread what makes the following systemd unit approach stupid. 
Is this thread mainly about making the whole approach unified by the docker cli or much more than that.

```bash
[Service]
TimeoutSec=0
ExecStartPre=-/usr/bin/sh -c "source /etc/profile.d/etcdctl.sh && /usr/bin/wget -nv -N -P /opt $(etcdctl --no-sync get /services/pkg)/couchbase.container.tar.gz"
ExecStartPre=-/usr/bin/sh -c "source /etc/profile.d/etcdctl.sh && /usr/bin/wget -N -P /opt $(etcdctl --no-sync get /services/pkg)/couchbase.container.tar.gz.sig"
ExecStartPre=/usr/bin/gpg --verify --trusted-key 1FATBOY12345678 /opt/couchbase.container.tar.gz.sig
ExecStartPre=/usr/bin/docker load -i /opt/couchbase.container.tar.gz
ExecStartPre=-/usr/bin/mkdir /home/core/couchbase
ExecStartPre=/usr/bin/chown 999:999 /home/core/couchbase
ExecStartPre=-/usr/bin/docker kill couchbase
ExecStartPre=-/usr/bin/docker rm -f couchbase
ExecStart=-/usr/bin/sh -c 'source /etc/profile.d/etcdctl.sh && /usr/bin/docker run --name couchbase --net="host" -v /home/core/couchbase:/opt/couchbase/var -e ETCDCTL_PEERS=http://10.10.2.2:4001 --ulimit nofile=40960:40960 --ulimit core=100000000:100000000 --ulimit memlock=100000000:100000000 andrewwebber/couchbase'
ExecStop=/usr/bin/docker kill --signal=SIGTERM couchbase
Restart=always
RestartSec=20
```

**Comment by stevvooe** [comment]
@andrewwebber I am not an expert on the attacker model, but the [TUF](http://theupdateframework.com/) documentation can elaborate on the problems a simple GPG approach.

The approach in that unit file is not "stupid". It just doesn't handle key distribution, trusted naming and secure updating.

**Comment by endophage** [comment]
@andrewwebber The biggest problem with using simple GPG signing is that once a piece of content has been signed, that signature is valid for as long as the key is valid. In the context of containers (or any software) it behooves us to be able to revoke the validity of a signature in the case that a major vulnerability is found, thus preventing any further installations and enabling people already holding a copy to detect they should upgrade.

TUF handles this via the signed targets list (removing a target from this list and resigning indicates the target is no longer valid) and its layered freshness guarantees (validity period of signatures is independent of key validity).

**Comment by NathanMcCauley** [comment]
We've put together a proposal to have Docker use The Update Framework as implemented by [notary](github.com/docker/notary). Please take a look at the [design document](https://docs.google.com/document/d/1Xn9kuhICOFj_P37ZWng8LeR_32NAj4Ytm42XAVWuTHw/edit?usp=sharing). Comments welcome!

**Comment by bfirsh** [comment]
Boom.

http://blog.docker.com/2015/08/content-trust-docker-1-8/

**Comment by cyphar** [comment]
:+1::shipit:
