### ISSUE TITLE
Accessing swarm using API

### ISSUE THREAD

**Issue by kumarsarath588** [docker/docker#27009]
Hi Guys,

Earlier when i am using swarm with containers i used to create certificates from CA and used to access swarm API like this:

export DOCKER_HOST=tcp://<DOCKER_IP>:2376
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH=/root/.docker

Now in docker 1.12  swarm mode, it generates its own certs and places in /var/lib/docker/swarm/certificates

So now how can i run swarm command from remote client or from my mac.

**Comment by thaJeztah** [comment]
There's two things being mixed up here. In "swarm" (not swarm _mode_), Swarm "wraps" the regular Docker remote API, and to talk to the swarm (instead of an individual daemon), the Docker Client has to connect to that API.

Swarm (https://docs.docker.com/swarm/) can still be used today (in docker 1.12 and up), and will function the same way as before.

If you're using Swarm _mode_ (i.e., using the new "services" features) in Docker 1.12, no additional installation is required, only swarm mode has to be enabled. Documentation for Swarm mode can be found here; https://docs.docker.com/engine/swarm/

In Swarm mode, the Docker client connects to the remote API of a manager. To allow remote connections over https (instead of only through `/var/run/docker.sock`, the daemon has to be configured for this; https://docs.docker.com/engine/reference/commandline/dockerd/#bind-docker-to-another-host-port-or-a-unix-socket, and protected with TLS https://docs.docker.com/engine/security/https/. This is also the same as in older versions of Docker.

> Now in docker 1.12 swarm mode, it generates its own certs and places in /var/lib/docker/swarm/certificates

This is where you got confused; these certificates are used by the manager nodes in the swarm to communicate with each other. This is an "internal" API, and you cannot connect to that API yourself. 

Does this answer your question?

**Comment by kumarsarath588** [comment]
Hey thanks for the quick response.

Got clear idea now.

**Comment by thaJeztah** [comment]
You're welcome; let me close this issue, but feel free to continue the conversation
