### ISSUE TITLE
docs: improve device mapper configuration instructions

### ISSUE THREAD

**Issue by bgrissin** [docker/docker#27020]
https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#/for-a-direct-lvm-mode-configuration

This doc informs users to push all images to a remote registry and then informs to rm -f /var/lib/docker, thus removing everything including certs that may be stored under this directory tree.  For good reasons, we instruct users to change from the default devicemapper loopback configuration that we recommended in early releases, of which they maybe running UCP on those nodes.   Deleting the certs in /var/lib/docker/discovery_certs creates a far more complex recovery scenario than just copying the certs back after the lvm changes have been completed.  This is the error received when you try to start up the docker daemon after following the doc instructions on a UCP node.

Initializing discovery with TLS
Error starting daemon: discovery initialization failed (Could not read CA certificate \ "/var/lib/docker/discovery_certs/ca.pem\" open /var/lib/docker/discovery_certs/ca.pem: no such file or directory

Can additional steps be written into the referenced doc perhaps such as copy the /var/lib/docker directory to /tmp to enable the recovery of items such as certs, etc in order to  keep from  placing users into extensive recovery scenarios.  thnx

**Comment by thaJeztah** [comment]
Good points. With "Swarm mode" in 1.12, I also wonder if there's other directories that should be kept around in case the machine is part of a Swarm.

Since this part of the documentation will be moved to unified docs repository (https://github.com/docker/docker.github.io), and the docs team being very busy on the migration, could you reopen this issue there? I don't think it's realistic to have this change in before the migration.

**Comment by bgrissin** [comment]
sure thing, will do.   thnx @thaJeztah

**Comment by thaJeztah** [comment]
Let me close the issue here, thanks @bgrissin!

**Comment by bgrissin** [comment]
https://github.com/docker/docker.github.io/issues/19
