### ISSUE TITLE
The container internal business log

### ISSUE THREAD

**Issue by yqguodataman** [docker/docker#27052]
I would like to know how to handle docker container internal business log file，Is there a way through the driver configuration log output?

**Comment by Vanuan** [comment]
From my experience, it's best to redirect logging to standard output.
If you're already writing logs to a file, you can prepend your docker command with:

 `tail -f /path/to/log & ; `

Only after that, you can use various docker log drivers:

https://docs.docker.com/engine/admin/logging/overview/

**Comment by thaJeztah** [comment]
Correct; the docker logging drivers collect the output of `stdout` and `stderr`. If your application is able to log to those; that's the way to go.

However, if your application expects to be writing to a _file_, you can redirect to `stdout` / `stderr` by creating a symlink. For example; here's what the official NGINX image does;

https://github.com/nginxinc/docker-nginx/blob/0dd9ef6a337474293b5e36c95a85da99b11e1a0a/mainline/jessie/Dockerfile#L21-L23:

```Dockerfile
# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log
```

I'll close this issue, because I _think_ your question is answered, but feel free to continue the conversation
