### ISSUE TITLE
Docs: Copying of built binaries in dev container needs change in binary name 

### ISSUE THREAD

**Issue by sn-narang** [docker/docker#27055]
In (https://docs.docker.com/opensource/project/set-up-dev-env/)
---> Task 2. Start a development container
---> Step 7. Copy the binary to the container’s /usr/bin directory.

root@a8b2885ab900:/go/src/github.com/docker/docker# cp bundles/1.12.0-dev/binary-client/docker* /usr/bin
root@a8b2885ab900:/go/src/github.com/docker/docker# cp bundles/1.12.0-dev/binary-daemon/docker* /usr/bin

The source path of this copy command is incorrect. The directories created as part of the build artifacts are bundles/1.13.0-dev. (Not 1.12.0 as above)

So the command(s) should be:

root@a8b2885ab900:/go/src/github.com/docker/docker# cp bundles/1.13.0-dev/binary-client/docker* /usr/bin

AND 

root@a8b2885ab900:/go/src/github.com/docker/docker# cp bundles/1.13.0-dev/binary-daemon/docker* /usr/bin

**Comment by sn-narang** [comment]
#dibs

**Comment by thaJeztah** [comment]
@sn-narang the source file for that document is currently in https://github.com/docker/opensource/blob/master/docs/project/set-up-dev-env.md, _however_ we're in the process of moving those docs to a unified repository; https://github.com/docker/docker.github.io/blob/master/opensource/project/set-up-dev-env.md

This is currently in progress, so you may have to wait until next week before opening a pull request there.

Also; I think the step can be made even easier; our makefile now has a `make install` target, which automatically copies all the binaries to the right location; that makes it even easier to use, and there's no need to update the documentation with each release. Perhaps you can use that in your pull request.

I'll close this issue here, because this part of the documentation is not in this repository, but I look very much forward to your pull request in the https://github.com/docker/docker.github.io/ repository; feel free to "ping" me there once your pull request is opened!
