### ISSUE TITLE
Unable to create containers.I am getting error " Error response from daemon: network myapp not found" here myapp is name of the network. Command i am using " sudo docker  run -itd --name=web --network=myapp nginx". 

### ISSUE THREAD

**Issue by abhayranjan7** [docker/docker#27058]
sudo docker network ls:

```
abhay@abhay-pc:~$ sudo docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
060d80d6ac2d        bridge              bridge              local
07b5241e19a7        docker_gwbridge     bridge              local
dba5297ceefd        host                host                local
2gs6seyiwrz2        ingress             overlay             swarm
3irubggsfbpy        myapp               overlay             swarm
8cb2f8da6e99        none                null                local
```
sudo docker network inspect myapp:

```
abhay@abhay-pc:~$ sudo docker network inspect myapp
[
    {
        "Name": "myapp",
        "Id": "3irubggsfbpyzmmctt21q7tkl",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Containers": null,
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "257"
        },
        "Labels": null
    }
]
```

Output of `docker version`:

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

```
Output of `docker info`:

```
Containers: 6
 Running: 1
 Paused: 0
 Stopped: 5
Images: 2
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 33
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: active
 NodeID: e3yfvwh1zmsbf5w0vhsv4h87x
 Is Manager: true
 ClusterID: 17s3wxf8qhflln3zfl10h98en
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.17.75.66
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.2.0-42-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797 GiB
Name: abhay-pc
ID: OHOV:HD2Q:OXWS:R52P:HPOS:2Y7G:WJHP:L3SV:LIZK:EDA4:E3XF:DOYD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.): I am on ubuntu server OS

**Comment by daviddyball** [comment]
You can't attach to a network managed by swarm via a non-swarm container. You must use `docker service create --network=myapp` in order to attach to it.

**Comment by thaJeztah** [comment]
In docker 1.12, "Swarm" scoped networks (see the "SCOPE" column) cannot be used for `docker run`, only for services. 

Allowing `docker run` to use swarm-scoped networks is being tracked by https://github.com/docker/docker/issues/23901, and is already implemented on "master" through https://github.com/docker/docker/pull/25962, which will be in the upcoming 1.13 release.


The error message is confusing indeed, as this message should be shown instead; https://github.com/docker/docker/blob/v1.12.2-rc1/daemon/container_operations.go#L330-L332. The bug here looks to be that (if a Swarm-scoped network is not in _use_ on the node) the network cannot be found (around this code https://github.com/docker/docker/blob/v1.12.2-rc1/daemon/container_operations.go#L351-L354).

I'll open a separate issue for that.

I'll close this issue, but thanks for reporting

**Comment by abhayranjan7** [comment]
But official docs are creating containers by "docker run " command.

**Comment by thaJeztah** [comment]
You can use `docker run` without issue, but not with a swarm-scoped network.

For example;

```
docker network create my-network
349b80d672d1ff579d61a673959e0923b6d6b8ce83b032c001641360f8e5d577

docker network ls

NETWORK ID          NAME                   DRIVER              SCOPE
a0fae0abd843        bridge                 bridge              local
a597265888b1        docker_gwbridge        bridge              local
0d73b5c2c8bc        host                   host                local
24iv7j69gen8        ingress                overlay             swarm
1lr6ktlm1k8c        my-multihost-network   overlay             swarm
349b80d672d1        my-network             bridge              local
4c4ebfd8f8f3        none                   null                local
```

Note that "my-network" is using the `bridge` driver, and has `local` scope, whereas `my-multihost-network` uses the  "overlay" driver, and is "swarm" scoped.

I can use the `my-network` network for `docker run`;

```
docker run -dit --network my-network busybox

c59af932f29ea86cc1d2fe365723e460e23f41526c55d107aba72005bab0375e
```

But using the `my-multihost-network` fails:

```
docker run -dit --network my-multihost-network busybox

docker: Error response from daemon: swarm-scoped network (my-multihost-network) is not compatible with `docker create` or `docker run`. This network can only be used by a docker service.
```

I _can_ use it for services;

```
docker service create --name my-service --network my-multihost-network nginx:alpine

816znuh7xgsyhliiz69lkou9q
```

**Comment by abhayranjan7** [comment]
Thanks for the explanation. I have understand that  docker run will not work in swarm mode but official docs are using "$ docker run -itd --name=web --network=my-net --env="constraint:node==mhs-demo0" nginx" to create containers. So can you explain what it is?.

**Comment by thaJeztah** [comment]
Looks like that example comes from "Swarm" (https://docs.docker.com/swarm/), not "swarm mode" (https://docs.docker.com/engine/swarm/) - the naming is confusing.

Swarm uses an external k/v store to create overlay networks, and uses `docker run` to deploy individual containers in the swarm. You can still use Swarm with docker 1.12, but if this is a new setup, I'd recommend to have a look at Swarm _mode_, which is where most active development currently takes place.

Swarm _mode_ is new in docker 1.12, and uses a whole different concept (no external k/v store needed for overlay networking, and you deploy _services_ instead of managing individual containers).

You can find a introduction to swarm mode in the documentation as well;
https://docs.docker.com/engine/swarm/swarm-tutorial/

**Comment by abhayranjan7** [comment]
Then i am also following the steps which talks about swarm not swarm mode. I am implementing same steps given in "https://docs.docker.com/engine/userguide/networking/get-started-overlay/". The moment i am creating containers i am getting this error. I don't know where i am going wrong.

**Comment by thaJeztah** [comment]
That page shows the two different approaches for creating overlay networking;

1. overlay networking in swarm mode (https://docs.docker.com/engine/userguide/networking/get-started-overlay/#/overlay-networking-and-swarm-mode)
2. overlay networking in "swarm", using an external k/v store (https://docs.docker.com/engine/userguide/networking/get-started-overlay/#/overlay-networking-with-an-external-key-value-store)

The first one (1.) can only be used for `docker service` commands, whereas the second one (2.) can used for "swarm", however, you need to make sure your daemon is not running with swarm mode enabled, otherwise the internal store is used.

**Comment by abhayranjan7** [comment]
Can you tell how can i stop docker daemon from running in swarm mode.

**Comment by abhayranjan7** [comment]
Ok i think i have to delete that node and try again.

**Comment by thaJeztah** [comment]
https://docs.docker.com/engine/reference/commandline/swarm_leave/ (and slightly related https://docs.docker.com/engine/reference/commandline/node_demote/)

**Comment by thaJeztah** [comment]
But you can probably also stop the daemon, and remove the `/var/lib/docker/swarm` directory 😇

**Comment by abhayranjan7** [comment]
@thaJeztah For creating docker host i am using command "docker-machine create -d virtualbox --swarm --swarm-discovery="consul://$(docker-machine ip consul-machine):8500" --engine-opt="cluster-store=consul://$(docker-machine ip consul-machine):8500" --engine-opt="cluster-advertise=eth1:2376" swarm-node-01". Here in cluster-advertise i am passing eth1 but when i am doing ifconfig i can't see any eth1. So is it going to cause any error.

**Comment by abhayranjan7** [comment]
Now i am getting error Error response from daemon: error getting pools config from store during init: store for address space GlobalDefault not found" when i am creating overlay network.
