### ISSUE TITLE
Container Failed to join swarm overlay network

### ISSUE THREAD

**Issue by kumarsarath588** [docker/docker#27064]
#Error: `docker: Error response from daemon: Could not attach to network my_net: rpc error: code = 7 desc = network my_net not manually attachable.` 
--------------------------------------------------------------------
`docker version`
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1-cs1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   e7f4338
 Built:
 OS/Arch:      linux/amd64

-------------------------------------------------------------------
`docker node ls`
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
1ws2qr1a00g2ye779bv5l3g57    centos7   Ready   Active
5sacbfgd15p62k4807gvwsisc *  centos7   Ready   Active        Leader
f2rmgh9bt9ra2qf92vx66gwyc    centos7   Ready   Active

-------------------------------------------------------------------
`docker network create  --subnet 192.168.200.0/24 -d overlay my_net`
75o1hdmvpjby5kpdgos84heow

-------------------------------------------------------------------
`docker run -d --network ingress busybox ping docker.com`
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
8ddc19f16526: Pull complete
Digest: sha256:a59906e33509d14c036c8678d687bd4eec81ed7c4b8ce907b888c607f6a1e0e6
Status: Downloaded newer image for busybox:latest
d13ac2bea679682a34ed02c77a3c204ae73abe1b8b769d1461f05c1d7e84ef1c
docker: Error response from daemon: Could not attach to network ingress: rpc error: code = 7 desc = network ingress not manually attachable.

It works if i use with `docker service` commands, but our application uses old way.

Please Help

**Comment by daviddyball** [comment]
You can't attach to a swarm managed network when not running the container via `docker service`.

**Comment by thaJeztah** [comment]
Correct, in docker 1.12 with swarm mode enabled, "Swarm" scoped networks (see the "SCOPE" column) cannot be used for `docker run`, only for services. 

Allowing `docker run` to use swarm-scoped networks is being tracked by https://github.com/docker/docker/issues/23901, and is already implemented on "master" through https://github.com/docker/docker/pull/25962, which will be in the upcoming 1.13 release.

Even then, you should _not_ manually attach to the ingress network; the ingress network is automatically used if you're publishing a port (also see https://github.com/docker/docker/issues/25396)

If you don't want to use swarm-mode (services), you should not enable it. If you want to use multi-host / overlay networking; you can still setup overlay networking with an external k/v store as before 1.12 (see https://docs.docker.com/engine/userguide/networking/get-started-overlay/#/overlay-networking-with-an-external-key-value-store)

I'll close this issue, because this is already fixed on master and will be addressed in 1.13 but thanks for reporting. Feel free to continue the conversation here 👍

**Comment by afolarin** [comment]
@thaJeztah  Still seeing this in Docker version 1.13.0-rc4, build 88862e7

> docker run --network=83p2j8lx396z --rm confluentinc/cp-zookeeper:3.1.1 /bin/bash
> docker: Error response from daemon: Could not attach to network radar-cns-stack_zookeeper: rpc error: code = 7 desc = network radar-cns-stack_zookeeper not manually attachable.

**Comment by thaJeztah** [comment]
@afolarin did you create the network with the `--attachable` option? (see https://github.com/docker/docker/blob/v1.13.0-rc6/docs/reference/commandline/network_create.md)

**Comment by afolarin** [comment]
@thaJeztah yup that was it. Thanks!

**Comment by kenzhaoyihui** [comment]
docker version: 17.11.0-ce

```
[root@dhcp-8-111 ~]# docker network create -d overlay ov_net1 --attachable 
z2ymv4v579kwn0v4y1psz62t1
[root@dhcp-8-111 ~]# docker run -itd --name ov1 --network ov_net1  yzhao/fedora /bin/bash
6fdd6ddf7537caa71a9c6cab98df8b9af34ce79d30b0ea6020314609fe411847
docker: Error response from daemon: attaching to network failed, make sure your network options are correct and check manager logs: context deadline exceeded.
[root@dhcp-8-111 ~]# 
```
Could you help me?

**Comment by raymondzhaoy** [comment]
@kenzhaoyihui      I have the same issue too
