### ISSUE TITLE
Windows containers can't access UNC paths available to the host

### ISSUE THREAD

**Issue by douglaswaights** [docker/docker#27100]
Hi,

I'm using Docker for Windows 1.12.2-rc1-beta27.1 on Windows 10 anniversary addition (latest bits at the time of writing) and trying to access UNC paths available to the host inside Server Core or Nano Server containers but not getting anywhere.

I would like to have all UNC paths that are available to the host also available to the Windows containers.

I also can't mount UNC paths as volumes.

https://forums.docker.com/t/how-to-access-a-mapped-network-folder-or-unc-path-inside-a-windows-container/22861

Thanks
Doug

**Comment by friism** [comment]
cc @jhowardmsft

**Comment by jhowardmsft** [comment]
No, I don't think this works in the platform. Must be a local drive for a volume. You can net use from inside the container though.

**Comment by douglaswaights** [comment]
ok thanks for the prompt response!

Doug

**Comment by mikecurrancs** [comment]
I am using gluster to create a volume -- sharing it as an mount to all my windows boxes so that the external configuration for each container can pop up on any swarm node -- but I need to mount the speicific configuration volume to the specific container 

I can net use the mount to the gluster server successfully. However, I cannot then create a junction to where it actually belongs, because it is not considered a local drive.  Is this brushed aside because of a windows limitation or just an unconsidered of use of docker?
