### ISSUE TITLE
Can't unmount partition until docker service is stopped.

### ISSUE THREAD

**Issue by masavini** [docker/docker#27138]
Hi,
I'm getting out of space on my SSD, so I copied /etc/docker to an external drive and linked /etc/docker to its mount point.

Docker service start fine on boot and I can start container once the external drive is mounted.
I can't, however, unmount the external drive without manually stopping the docker service (even if no container is running), which is pretty annoying...

Any hint?

**Comment by cpuguy83** [comment]
Not sure where `/etc/docker` is coming from since docker uses (by default), `/var/lib/docker`.
But certainly if a service is running and is using a mounted drive you should not be able to unmount it until said service is stopped.
Not sure what else you are looking for here?

Closing since this is a non-issue.
