### ISSUE TITLE
Local images with the same name as a library image should not take precedence

### ISSUE THREAD

**Issue by darrenstahlmsft** [docker/docker#27132]
**Description**
When a local image has the same name as a library image, the local image is used, even if the full library image name is specified. On Windows, this creates the situation where `docker run library/busybox` works, but `docker pull library/busybox` fails.

**Steps to reproduce the issue:**
1. Create a local image named `hello-world`
2. `docker run library/hello-world` (or `docker.io/library/hello-world`, etc.)

**Describe the results you received:**
The local image `hello-world` is run.

**Describe the results you expected:**
The library `hello-world` image should run and give the standard hello-world message.

**Output of `docker version`:**
Not relevant, as the issue occurs on Windows daemons as far back as 1.12, I don't currently have a Linux daemon to test, but based on code inspection, I expect it to occur there as well.

**Additional details**
This is being intentionally stripped in https://github.com/docker/docker/blob/master/reference/reference.go#L192, but I don't think that this behaviour is correct. I think that it should resolve the image in the hub before stripping the name, and this should fail if the library image cannot be pulled (such as on Windows, attempting to pull the linux based library images).

Note that `docker pull hello-world` does correctly find the library image, even if a local image of the same name exists. Also note that this issue occurs in Dockerfiles as well.

**Comment by justincormack** [comment]
This does seem weird, yes.

**Comment by tonistiigi** [comment]
Although somewhat confusing, I think this is the correct behavior. All these references are identical. `docker build -t tonistiigi/foo . && docker push docker.io/tonistiigi/foo`  `docker build -t docker.io/tonistiigi/foo . && docker push tonistiigi/foo`

>  On Windows, this creates the situation where docker run library/busybox works, but docker pull library/busybox fails.

If I understand this correctly then this is because `docker pull busybox` also fails so the addition of  `library` doesn't change anything here.

**Comment by darrenstahlmsft** [comment]
Correct, `docker pull busybox` fails. My example isn't the best way to illustrate the issue. The issue I think boils down to the special treatment of `library/...`. Here's another example that I find is weird, and potentially a bug:

I have a local image called busybox
```
PS C:\Users\Administrator> docker images
REPOSITORY                                    TAG                 IMAGE ID            CREATED             SIZE
busybox                                       latest              7c53f09466f1        4 days ago          7.43 GB
```
```
docker run busybox
```
works as expected and runs the local image

```
docker run library/busybox
```
runs the local image, even though there does exist an image called `library/busybox` on the hub that is not the same as the local image.

```
docker run microsoft/busybox
```
fails to find an image `microsoft/busybox` locally and attempts to pull from the hub. No such image exists, so it fails.


It seems to me that the special handling of `library/...` images causes a mismatch of behaviour between two commands that I would expect to both either fail to find an image, or both find the local image and run it.

**Comment by tonistiigi** [comment]
@darrenstahlmsft Yes, `library` and `docker.io` are special for default username and host. If user doesn't know about them it can be confusing. It's a feature to mix these references in a way I showed in my previous comment. If you pull `library/busybox` you never get `library/busybox` but just `busybox` because `library/*` is special. There is no way for an user to ever create a reference with `library/*` or `docker.io/*`, they are reserved for automatic prefixes. If you want to trust remote refs over local refs you can turn on content trust, that will make `run library/busybox` fail for you.

**Comment by darrenstahlmsft** [comment]
@tonistiigi Ok, if this is expected behaviour, then that's fine. It just seemed odd, and I was expecting it to fail (we even have a CI test that validates it doesn't fail on Windows, which I think was accidentally enabled in the first large batch). I'll stop running the test on Windows.
