### ISSUE TITLE
Make ingress network a special routing only network

### ISSUE THREAD

**Issue by mrjana** [docker/docker#27147]
When docker creates a swarm cluster a special overlay network called `ingress` network is created to properly route external requests outside the cluster to services which are publishing ports. This network exists to serve one purpose only, to facilitate routing such requests. Even though it shows up in network listings it should not be used as a normal network to discover services which are attached to them or facilitate internal load balancing between these services. To block such unintentional behavior the following needs to happen:
* Disable service discovery in `ingress` network
* Block services explicitly trying to attach to `ingress` network
* Allow only access to published ports when traffic is coming to any container via `ingress` network

**Comment by doxxx** [comment]
This sounds it would resolve #24637 but I can't say for certain without testing it.

**Comment by jtyberg** [comment]
IMHO, if the ingress network truly is intended to be special purpose, and it is conflicting with expected behavior of user-defined overlay networks (see #24637), then imposing the above restrictions to avoid these conflicts makes sense to me.  

As a user, I would not think to explicitly attach to the ingress network, nor would I expect it to magically route things for me if I don't properly setup my own overlay network.  The current situation is much worse, in that I **do** setup my overlay network, but things aren't working as expected.

I already compartmentalize the ingress network as the cool feature that allows me to publish any service on a port Swarm-wide, and allows me to hit it from any machine in the swarm.  If the restrictions don't break this, I'm happy.

**Comment by rogaha** [comment]
Agreed! Are we going to prompt a message to the `end-user`if he tries to the join the `ingress`  network (https://github.com/docker/docker/issues/25396)?

**Comment by mavenugo** [comment]
Changing the  priority to p1 based on discussion with @mrjana

**Comment by lbguilherme** [comment]
I believe this has been fixed by #27180 already.

**Comment by sanimej** [comment]
@lbguilherme #27180 brings the fix to 1.12 branch. its not in docker master yet.

**Comment by mrjana** [comment]
Fixed by #26954

**Comment by g0t4** [comment]
Could we get this info into the docs? Or is it somewhere already?
