### ISSUE TITLE
Docker 1.13 on Windows no /var/run/docker.sock

### ISSUE THREAD

**Issue by dajester2013** [docker/docker#27222]
**Description**

I am needing to launch a docker container that has access to the docker daemon in order to launch other docker containers.  Previously this was done by mounting the docker.sock as a volume.  However, this does not work on Docker 1.13-dev and Windows 10 Enterprise.

**Steps to reproduce the issue:**
1. Install docker 1.13 on windows pro/enterprise as referenced at msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10
2. Attempt to run Eclipse Che:  `docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che start`

**Describe the results you received:**

Recieved an error stating that \var\run\docker.sock... is an invalid volume specification.

**Describe the results you expected:**

Che container starts normally.

**Additional information you deem important (e.g. issue happens only occasionally):**

This works as expected on docker 1.12 on Windows 10.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   febf53d
 Built:        Fri Oct  7 17:30:22 2016

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   febf53d
 Built:        Fri Oct  7 17:30:22 2016
```

**Output of `docker info`:**

```
Containers 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.13.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.206.amd64fre.rs1_release.160915-0644)
Operating System: Windows 10 Enterprise
OSType: Windows
Architecture: x86_64
CPUs: 8
Total Memory: 7.956
Name: ---------
ID: ------------
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.1/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Comment by friism** [comment]
This is a difference between Windows containers and Linux containers. When you set up according to the MSDN guide, you set up the windows-native Docker daemon. `eclipse/che` is not a Docker Windows container image (I think), and you cannot volume mount `docker.sock` into a Windows Docker container because the socket doesn't exist on Windows (there's currently no good way to make the Docker Engine control API available inside a Windows container).

I suspect what you're looking for is just Docker for Windows on your Windows 10 machine and using Linux Docker containers: https://docs.docker.com/docker-for-windows/

**Comment by dajester2013** [comment]
You know, I had not tried launching any other linux docker containers - 'image operating system "linux" cannot be used on this platform."

Thanks, I will revert for now.
