### ISSUE TITLE
Get logs from service in Docker Swarm mode

### ISSUE THREAD

**Issue by nlsun** [docker/docker#27396]
It doesn't seem like there is a way to get the logs from a container running in a service, or even to get the containers running in the service?

**Comment by thaJeztah** [comment]
You can get logs for individual container, but only from the node they're running on (see https://github.com/docker/docker/issues/23710)

Work is in progress to improve this, and to support logs for services (see https://github.com/docker/docker/issues/24812)

I'll close this issue because we're tracking this through https://github.com/docker/docker/issues/24812, but thanks for reporting
