### ISSUE TITLE
Containers in internal networks do not expose ports even if explicitly made to do so

### ISSUE THREAD

**Issue by TimurKiyivinski** [docker/docker#27441]
**Description**
Docker containers created inside an internal network are not able to access each other's ports but are able to ping each other. The requirement is to have containers be able to communicate with each other without internet access.

**Steps to reproduce the issue:**

Steps are adapted from https://stackoverflow.com/questions/34834913/how-to-access-ports-in-docker-custom-bridge-networks to replicate the scenario at work. The output of `docker {version,info}` is from work PC although this is tested and fails on my personal laptop as well.

1. `docker network create --internal test`
2. `docker run --net test --expose 4200 --name weba -d node sh -c 'npm install http-server -g && mkdir -p /public && echo "welcome to weba" > /public/index.html && http-server -a 0.0.0.0 -p 4200'`
3. `docker run --net test --expose 4200 --name webb -d node sh -c 'npm install http-server -g && mkdir -p /public && echo "welcome to webb" > /public/index.html && http-server -a 0.0.0.0 -p 4200'`
4. `docker exec -it webb sh -c 'curl http://weba:4200'`

**Describe the results you received:**
The output of number 4 is: `curl: (7) Failed to connect to weba port 4200: Connection refused`
Running `docker exec -it webb sh -c 'ping weba'` works normally.
Containers are also not able to access external internet as expected too.

**Describe the results you expected:**
From reading the docs here, https://docs.docker.com/engine/userguide/networking/ , I understand that links should not work but exposing them should still work? This has been testing using exported and published ports.

**Additional information you deem important (e.g. issue happens only occasionally):**
The containers are able to communicate perfectly well when using host network without having to use `--expose` or `-p`. Running `docker ps` does reveal that no ports are being exposed from the container as expected.

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   bb80604
 Built:        Sun Oct 16 13:09:44 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   bb80604
 Built:        Sun Oct 16 13:09:44 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 32
Server Version: 1.12.2
Storage Driver: devicemapper
 Pool Name: docker-8:2-30015863-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 10.72 GB
 Data Space Total: 107.4 GB
 Data Space Available: 96.65 GB
 Metadata Space Used: 10.85 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.137 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135 (2016-09-26)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.7.6-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.709 GiB
Name: tkiyui
ID: YCP6:Z6Y4:KWXP:HGXL:LBYU:BWEJ:OITY:3KVD:IDS6:L3FT:V2OJ:7M2D
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by sanimej** [comment]
@TimurKiyivinski Within a network the containers' ports are reachable without port expose or publish. This is true for internal networks as well. Here is a quick example. In your case can you check if the http-server is indeed listening on 4200. 

```
# docker run -d --net test --name web jwilder/whoami
0b54cf8466634532ce28206124d96e38af49b9dd879e6a284ae17388bb15be49

# docker run -d --net test --name client sanimej/ubuntu bash -c "sleep infinity"
e2945a5a3caedb404fe04cdfd357c505fb95dfc064bbd23e6392fc4668d86c25

# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
e2945a5a3cae        sanimej/ubuntu      "bash -c 'sleep infin"   1 seconds ago       Up 1 seconds                            client
0b54cf846663        jwilder/whoami      "/app/http"              41 seconds ago      Up 41 seconds 
                          web
# docker exec client curl "http://web:8000"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    17  100    17    0     0   2831      0 --:--:-- --:--:-- --:--:--  3400
I'm 0b54cf846663
#
```

**Comment by TimurKiyivinski** [comment]
Thanks for the example, it's helped me realize the problem is odder than I initially realized. The example provided may be flawed as the npm packages would not work inside an internal network. My apologies. The scenario is as so: There is a MariaDB instance that needs to be initialized and started before the application starts as part of some internal testing. To delay the startup of the application until the database is initialized, there is an intermediate container that runs netcat that polls the database until it is started. All of this is tested and works fine using the host network but not with the internal network.
```
docker run -d --net test --name db -e ... corp/db
```
However in the intermediate container, `ping` works but `nc` and `nmap` indicate that all ports are closed.
```
docker run -d --net test --name inter --link db:db corp/inter
```
By simply removing `--net test`, all appears to work well and the containers are able to communicate. What options do I have debugging this issue?

**Comment by sanimej** [comment]
@TimurKiyivinski ping would work because it doesn't depend on the application. What I suspect happening is that database app tries to reach an external address and when that fails doesn't open the port. To narrow it down you can run the database app in the default bridge network or host mode and capture the packets to check what the db app is doing.

Since this doesn't seem to be an issue with `internal` mode of docker network I will close this issue. But if you have other questions feel free to continue the discussion here.

**Comment by TimurKiyivinski** [comment]
Finally back at the office to continue testing. This is the default MariaDB image with an additional database SQL placed in `/docker-entrypoint-initdb.d/` and it works on host or non `--internal` networks. Even in an internal network, I am able to run `docker exec -it db mysql -u root -p` to confirm that the database is indeed up. 
## testing with 2 MariaDB instances
I have now tried using 2 MariaDB instances, one the default image and the same issue seems to occur. They both can ping each other but neither seem to be able to connect to each other's db instance.
## testing netcat with Alpine
To further verify that ports are not forwarding or being blocked, I've tried having nc listen on one Alpine instance while the other tries to connect. Let's say I have an instance `n1` and `n2`.
In `n1` I run `nc -l -p 3333` whereas in `n2` I run `nc n1 3333`. Everything I type into `n2` and press enter echoes out in `n1` if I use a non-internal network but I again tells me `no route to host` in an internal network.

I'm no Linux networking genius so perhaps some guidance on what commands to run to check things would be appreciated. Thanks a bunch

**Comment by TimurKiyivinski** [comment]
The issue appears to be cause by firewalld. It worked on my personal computers that didn't use firewalld. Seems to be solved by switching to iptables, which is **not** of course an optimal solution.

**Comment by thaJeztah** [comment]
Did you start the docker service _after_ the firewalld service? Firewalld is known to ignore rules set by docker, and wipe them

**Comment by TimurKiyivinski** [comment]
Just tested starting Docker after firewalld, the DOCKER chain exists in iptables but containers are still not able to access each other's ports in an internal network.

**Comment by tiangolo** [comment]
I will cross-post my solution for a similar problem that I posted here: https://github.com/docker/docker/issues/16137#issuecomment-271615192 as it seems it could also be relevant in this issue.

I'm sorry if any of you consider it "spam", but as it is a possible solution I think it's best to share it.

---

**Note**: How I fixed it is a section below.

I was having issues with `firewalld` and Docker, specifically with Rancher v1.2 in CentOS 7.

Rancher needs a container to be able to communicate to the host via it's external (possibly local) IP address.

It was a requirement to have `firewalld` enabled and working.

## Environment

**OS**: `CentOS Linux release 7.3.1611 (Core)`

**Kernel** updated manually using "elrepo" to be able to use Overlay2 (`devicemapper` gave us several problems), although I don't think the kernel or the back end store is related to the problem: `4.9.0-1.el7.elrepo.x86_64`

**Docker**: 

```
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 29
Server Version: 1.12.5
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.9.0-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 56
Total Memory: 125.7 GiB
Name: node19
ID: 3SC3:MCMU:PYSL:IBPE:4LPY:OYAG:RUUF:QMQ7:JWDS:5VRI:V7IS:KUYC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
[root@node19 cerebro]# uname -r
4.9.0-1.el7.elrepo.x86_64
[root@node19 cerebro]# docker info
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 29
Server Version: 1.12.5
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.9.0-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 56
Total Memory: 125.7 GiB
Name: node19
ID: 3SC3:MCMU:PYSL:IBPE:4LPY:OYAG:RUUF:QMQ7:JWDS:5VRI:V7IS:KUYC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**`firewalld` is enabled**: 

```
systemctl status firewalld.service
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: active (running) since jue 2017-01-05 18:04:12 COT; 4 days ago
     Docs: man:firewalld(1)
 Main PID: 24584 (firewalld)
   Memory: 46.5M
   CGroup: /system.slice/firewalld.service
           └─24584 /usr/bin/python -Es /usr/sbin/firewalld --nofork --nopid

ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -D PREROUTING' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -D OUTPUT' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -X DOCKER' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -X DOCKER-ISOLATION' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -n -L DOCKER' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C DOCKER-ISOLATION -j RETURN' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C DOCKER -i docker0 -j RETURN' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -D FORWARD -i docker0 -o docker0 -j DROP' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8' failed:
```

...but those errors in `firewalld` are expected as pointed out in: https://github.com/docker/docker/issues/16137#issuecomment-269398488


## The problem

`firewalld` uses `iptables` and IPtables rules under the hood, but the way it "works" is with different "zones", with different levels of access (as I understand, different sets of `iptables` rules for each "zone").

The `docker0` network interface is not assigned to any zone, so, some of its communications are blocked.

In my case, running the Rancher "agent" (a Docker container) with `firewalld` active gives errors about not being able to connect to the Rancher server (via it's external IP, in where the Rancher server, another container, is listening to). But with `firewalld` inactive, it works normally.

To make it worse, in all the systems I have tested (bare metal and Linode VPS) the `docker0` interface's `firewalld` zone cannot be modified using `firewalld` commands, because it is "controlled" by the "NetworkManager".

## The fix

* Check the `firewalld` "zone" asigned to the Docker interface:

```bash
firewall-cmd --get-zone-of-interface=docker0
```

* If it says "no zone", you need to add it to the `trusted` zone

```bash
firewall-cmd --permanent --zone=trusted --change-interface=docker0
```

* If the previous command returns a message like:

```
The interface is under control of NetworkManager, setting zone to 'trusted'.
success
```

...it means that `firewalld` cannot control the zone of the interface (even if it says "success").

You can check that the zone was not assigned by running again:

```bash
firewall-cmd --get-zone-of-interface=docker0
```

* If that's the case, you need to use the "NetworkManager" and restart the `docker0` interface, so first stop the `docker` daemon:

```bash
systemctl stop docker
```

* Now use the "NetworkManager" command line interface to set the zone of the `docker0` interface to `trusted`:

```bash
nmcli connection modify docker0 connection.zone trusted
```

* Now turn the `docker0` interface off:

```bash
ifdown docker0
```

* And turn it on again:

```bash
ifup docker0
```

* And check that the `firewalld` zone assigned to the interface `docker0` is "trusted":

```bash
firewall-cmd --get-zone-of-interface=docker0
```
...now it should return `trusted` instead of `no zone`

* Now you can start Docker again:

```bash
systemctl start docker
```

* Check if the problem you had was solved

## References

http://unix.stackexchange.com/a/225845/90829

[Introduction to FirewallD on CentOS - Linode](https://www.linode.com/docs/security/firewalls/introduction-to-firewalld-on-centos)

[RedHat forums (in the comments is mentioned the `nmcli`)](https://access.redhat.com/discussions/1455033)

[RedHat docs for `nmcli`](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/sec-Using_the_NetworkManager_Command_Line_Tool_nmcli.html)
