### ISSUE TITLE
group-rm, group-add doesn't make sense on `docker service create`

### ISSUE THREAD

**Issue by stevvooe** [docker/docker#27646]
https://github.com/docker/docker/pull/25317 added support for specifying groups. It added `--group-rm` and `--group-add`. While these make sense for update, adding and removing groups should simply be a static list, best done with `--group` to specify the list of supplementary groups.

We'll need to fix this before 1.13.

cc @lilybguo @thaJeztah

**Comment by lilybguo** [comment]
#dibs

**Comment by thaJeztah** [comment]
@stevvooe you suggest to remove these from `docker service update` or renaming the flag on `docker service create` to `--group` ?

IIRC, there was discussion about that, because `--group`, combined with `--user` may lead to the expectation that the process is started as `<user>:<group>`, which it is _not_.

**Comment by stevvooe** [comment]
@thaJeztah `docker service create` should have `--group` and `docker service update` should have `rm/add`. `rm/add` makes no sense for create, since there was no previously existing group set.

> IIRC, there was discussion about that, because --group, combined with --user may lead to the expectation that the process is started as <user>:<group>, which it is not.

Yes, but we adopted that confusion by making these the same. We'll have to cover this with documentation.

**Comment by crosbymichael** [comment]
This has been merged.
