### ISSUE TITLE
build randomly fails on Docker Hub

### ISSUE THREAD

**Issue by vincentfretin** [docker/docker#27652]
I don't know if this is the right place for this, but it has been weeks I have random error on Docker Hub when my image is built. I think there is an issue with one of your servers on Docker Hub.
The error is:
```
Build failed: stat /var/lib/docker/overlay/69f1f175072ed86541772b28e3cdcced919a1d09d42808981b69bbc29b3ac498/merged/start: no such file or directory
```

All the Error line you see at 
https://hub.docker.com/r/ecreall/novaideo/builds/
is the same issue.

**Comment by j3k0** [comment]
+1 same error here, with many different repositories. It has to be a known issue.

**Comment by thaJeztah** [comment]
I think there's active work on this, and this may be related to https://github.com/docker/docker/pull/27609. However issues for Docker Hub in general should be reported either through support@docker.com or https://github.com/docker/hub-feedback/issues. I'll close this issue here, because this issue tracker is for the docker open source project, but feel free to comment after

**Comment by vincentfretin** [comment]
Thanks for the link to hub-feedback repo. Is there a link somewhere on Docker Hub that links to it that I missed?

There is a similar issue here: https://github.com/docker/hub-feedback/issues/844

**Comment by thaJeztah** [comment]
Not sure there's a link to that - IIRC, that repo/issue tracker was started during a redesign of Docker Hub, but kept alive for general feedback.
