### ISSUE TITLE
Deadlock after many create/rm container operations

### ISSUE THREAD

**Issue by tonistiigi** [docker/docker#27761]
Dockerd and containerd stacktrace https://gist.github.com/tonistiigi/df8028687858f2f11f0016ac336f8185

`docker ps` blocked in https://gist.github.com/tonistiigi/df8028687858f2f11f0016ac336f8185#file-docker-stacktrace-L4440-L4442

On first look, it seems to be blocked on start waiting on containerd grpc. For example https://gist.github.com/tonistiigi/df8028687858f2f11f0016ac336f8185#file-docker-stacktrace-L4131-L4147 It has already taken container lock but is not releasing it.

Traces are from https://github.com/docker/docker/commits/32b541e44385206772b30b2a6f241a7c809aa62f

@mlaventure @crosbymichael

**Comment by stevvooe** [comment]
Looks like the error channel went down. ContainerD is blocking in the following places:

https://github.com/docker/containerd/blob/master/api/grpc/server/server_linux.go#L54
https://github.com/docker/containerd/blob/master/api/grpc/server/server.go#L66
https://github.com/docker/containerd/blob/master/api/grpc/server/server.go#L156

**Comment by mlaventure** [comment]
`containerd` is stuck because of an `AddProcess` call [here](https://gist.github.com/tonistiigi/df8028687858f2f11f0016ac336f8185#file-containerd-stacktrace-L143).

It's stuck in an infinite loop because [`isAlive`](https://github.com/docker/containerd/blob/52ef1ceb4b660c42cf4ea9013180a5663968d4c7/runtime/container.go#L667) keeps returning `true`, which would mean the `containerd-shim` process associated with the exec is still running somehow.

There's 2 scenarios to hit this code path:
 1. The pid file wasn't created
 2. The conversion from `string` to `int` of the pid failed

@tonistiigi is the machine where it occurred still there? Or can you reproduce it somehow?

**Comment by mlaventure** [comment]
Also, this should have hit the timeout [here](https://github.com/docker/containerd/blob/52ef1ceb4b660c42cf4ea9013180a5663968d4c7/runtime/container.go#L659) and unfrozen the `containerd` loop. Not sure why this didn't happen.

**Comment by tonistiigi** [comment]
> is the machine where it occurred still there? Or can you reproduce it somehow?

cc @dongluochen

**Comment by dongluochen** [comment]
Yes the machine in this state is still there. We can look at it tomorrow morning.

**Comment by crosbymichael** [comment]
What version is this being tested on?

**Comment by mlaventure** [comment]
@crosbymichael https://github.com/docker/docker/commits/32b541e44385206772b30b2a6f241a7c809aa62f

**Comment by crosbymichael** [comment]
Is there a way to reproduce this? I guess try to run alot of execs and see if it happens?

**Comment by dongluochen** [comment]
This happened after `docker service test scale=20`. 

```
ubuntu@ip-172-19-241-144:~$ docker version
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   77f4c30
 Built:        Wed Oct 26 00:31:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   77f4c30
 Built:        Wed Oct 26 00:31:10 2016
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by tonistiigi** [comment]
I believe the execs were caused by a healthcheck in the service that was scaled.
