### ISSUE TITLE
RFE: docker inspect "RunCmd" to help recreate similar containers

### ISSUE THREAD

**Issue by VojtechVitek** [docker/docker#27786]
When running containers manually, I often need to know what `docker run` command was originally used to spin up the container.

For example, when I need to attach more volumes to the container, I need to `docker stop` and `docker rm` the container and `docker run` it again (since `docker update` can't handle volume changes yet). Now, what was the original `docker run` sequence I used before?

It would be useful if `docker inspect` was able to help me out:

```bash
$ docker inspect --format='{{.RunCmd}}' postgres
docker run -d --restart=always -p 5432:5432 -v /home/user/postgres:/var/lib/postgresql/data --log-opt max-size=500m --log-opt max-file=10 --memory-swappiness=10 --memory=1G --name=postgres postgres:9.6
```

so I could grab this string and re-use it to create new container.

**Comment by milindchawre** [comment]
#dibs

**Comment by thaJeztah** [comment]
This was proposed a few times, but rejected, see for example and info how to achieve this, https://github.com/docker/docker/issues/4480, https://github.com/docker/docker/issues/13302, https://github.com/docker/docker/issues/9150, https://github.com/docker/docker/issues/9924 https://github.com/docker/docker/issues/9007, https://github.com/docker/docker/issues/11460, https://github.com/docker/docker/issues/15614

Easiest way to achieve this is to use [docker compose](https://www.docker.com/products/docker-compose), or simply a shell-script to start your container. Note that the new services (swarm mode) functionality in docker 1.12 and up, allow you to update a service and add new volumes to an existing service (as it will recreate the containers backing the service)

I'll close this issue because of the above, but feel free to comment after

**Comment by VojtechVitek** [comment]
@thaJeztah oh, sorry for the duplicate. Strangely, I couldn't find the other issues. Seems like this functionality is in high demand then!

> Easiest way to achieve this is to use docker compose, or simply a shell-script to start your container. 

This RFE is not about reproducible deployments (docker-compose.yml, Swarm, Kubernetes or anything else) - it is about inspecting running container for user's convenience on localhost, ie. when testing set of docker images for the first time.

Quoting @cpuguy83 from the other issue:

> The Docker CLI is an API client. You can use the output of docker inspect to re-construct an equivalent docker run.

This is a good point. However, CLI is meant to help users work fast. So, why not to introduce this feature in the `docker inspect` itself, since CLI knows all the values anyway?

There is a good Unix precedent in `ps ax` command that lets you show and re-construct running processes. However, `docker ps` shows only what's inside of the container.

**Comment by sergw** [comment]
Alternatively solution to use https://github.com/nexdrew/rekcod
