### ISSUE TITLE
Error:response from deamon: page not found. when use docker-1.10.0-dev checkpoint function 

### ISSUE THREAD

**Issue by xiaozhazi** [docker/docker#27853]
**Description**

When I use the docker-1.10.0-dev to checkpoint a container , it shows that Error: response from daemon: page not found.
I try to change docker-1.9.0-dev, the error occurs again.
the docker-1.10.0-dev is the pre-release.

**Steps to reproduce the issue:**
1.sudo docker run -d --name looper --security-opt seccomp:unconfined busybox /bin/sh -c 'i=0;while true; do echo $i; i=$(expr $i +1);sleep 1;done'
2. sudo docker ps
3. sudo docker logs looper 
they all execute correctly.
4. sudo docker checkpoint busybox 
This step cannot execute ,shows errors.

**Describe the results you received:**
![image](https://cloud.githubusercontent.com/assets/4612045/19800956/b5ca86a8-9d2f-11e6-82a5-b2671908fa98.png)

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```
![image](https://cloud.githubusercontent.com/assets/4612045/19800997/e11d83b4-9d2f-11e6-8e5d-5093bd45b2c6.png)

**Output of `docker info`:**

```
(paste your output here)
```
![image](https://cloud.githubusercontent.com/assets/4612045/19801013/f49607a4-9d2f-11e6-8557-87eef7e16e46.png)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by justincormack** [comment]
Can you use a client that is the same version as the server to test this please? Why are you using a pre release 1.10?

**Comment by thaJeztah** [comment]
The checkpoint/restore feature you're using is from an experimental build from this repository; https://github.com/boucher/docker/releases/tag/v1.10_2-16-16-experimental

This was never released, and only used as a way to test this functionality. The API side of checkpoint/restore is merged into this repository now, and will be an experimental feature in docker 1.13 (see https://github.com/docker/docker/pull/22049)

I'll close this issue, because this is not a supported feature, and not an official build, but feel free to continue the conversation

**Comment by xiaozhazi** [comment]
Thank you for your answer. Because I want to test the docker C/R function, and I have seen some document see this function will add in docker 1.12. But 1.12 didn't include yet, so I tried to use the non-official build. Looking forward to see the experimental feature in docker 1.13.
