### ISSUE TITLE
overwrite registry  image

### ISSUE THREAD

**Issue by hamidasgarian** [docker/docker#27945]
ls there any way to overwrite pushed image in the local docker registry?

i have a image named local-registry:5000/mysql with size 635 MB
docker push local-registry:5000/mysql

then i build the image local-registry:5000/mysql with smaller size and push it.
docker push local-registry:5000/mysql

i expected pervious image replaced with new smaller image and release more disk in my registry.

can anyone help me?

**Comment by thaJeztah** [comment]
The registry never removes old images, because you can still reference them through their digest (https://docs.docker.com/engine/reference/commandline/pull/#/pull-an-image-by-digest-immutable-identifier). Also, image layers can be shared between images, and the registry does not purge these layers automatically.

Also see https://github.com/docker/distribution/issues/422, https://github.com/docker/distribution/issues/1844, https://github.com/docker/distribution/issues/1052

I'll close this issue here because this is related to the registry, not docker (engine), but I hope the above information answers your question
