### ISSUE TITLE
`docker service ls` does not truncate command

### ISSUE THREAD

**Issue by dongluochen** [docker/docker#27994]
**Description**

`docker service ls` outputs full text of COMMAND by default. It impacts readability when COMMAND is long.

**Describe the results you received:**

```
dchen@vm2:~/$ docker service ls
ID            NAME                 REPLICAS  IMAGE                      COMMAND
lfsyu3jnfi64  test                 1/1       dongluochen/simpleweb:0.5  simpleweb -e xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
```

**Describe the results you expected:**

Truncate output of command.

**Additional information you deem important (e.g. issue happens only occasionally):**

Good to follow `docker ps` and provide `--no-trunc` option.

**Comment by tealtail** [comment]
If it's alright, I'd like to call #dibs on this one :)

**Comment by tealtail** [comment]
I've pushed my initial work up to my fork here https://github.com/tealtail/docker/commit/5148744fb490b2e98245e70fb9b31406881af521, but I'm new to Go and fumbling a bit in passing the `opts` down through `PrintNotQuiet` and into `printTable` where it's needed. 

Since `PrintNotQuiet` is used by `docker stack services` I'm leery of adding extra params. 

I'll be looking for a solution, but if anyone knows I'd appreciate the boost

**Comment by aaronlehmann** [comment]
I'd suggest just removing `COMMAND`. It don't think it's important enough to show here. And its presence does seriously impact readability.
