### ISSUE TITLE
Windows `docker stats` CLI shows linux headers when no containers are running

### ISSUE THREAD

**Issue by jhowardmsft** [docker/docker#28005]
Opening an issue to track this so it's not forgotten about.

On master currently.  Follow on from https://github.com/docker/docker/pull/27759 and previously https://github.com/docker/docker/pull/24987. Title says it all...

**Comment by ripcurld00d** [comment]
Ummm, sounds interesting.
[that code line](https://github.com/docker/docker/blob/master/cli/command/container/stats.go#L199) should tell the CLI to use the windows header.
I wonder why it doesn't work.

**Comment by yongtang** [comment]
@jhowardmsft @ripcurld0 The issue is located:
https://github.com/docker/docker/blob/v1.13.0/cli/command/formatter/formatter.go#L74-L78

In case there is no container, a header will be faked. However, OSType is associated with individual container stats so the value is not passed in.

I created a PR #30749 with unit tests, think it should fix the issue.

I don't have a Windows setup yet but will get it done to test it either today or tomorrow.
