### ISSUE TITLE
Can't rmi an image after running a Hyper-V container from it, and directory leaked.

### ISSUE THREAD

**Issue by jhowardmsft** [docker/docker#28087]
On master

@swernli @darrenstahlmsft @jstarks 

The "rename on delete" PR has broken the ability to docker rmi images. See repro below:

```
PS C:\baseimages> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
PS C:\baseimages> docker load -i .\nanoserver.tar
Loaded image: microsoft/nanoserver:10.0.14393.321
Loaded image: microsoft/nanoserver:latest
PS C:\baseimages> docker run --rm --isolation=hyperv microsoft/nanoserver powershell echo hello
hello
PS C:\baseimages> docker images
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
microsoft/nanoserver   10.0.14393.321      22738ff49c6d        4 weeks ago         686 MB
microsoft/nanoserver   latest              22738ff49c6d        4 weeks ago         686 MB
PS C:\baseimages> docker rmi microsoft/nanoserver
Untagged: microsoft/nanoserver:latest
PS C:\baseimages> docker rmi 22738
Error response from daemon: rename C:\a\b\c\windowsfilter\c600d489c09f07aeb05b55ad2c8db12fd0051d28409073eda4bbdcde67397ea3 C:\a\b\c\windowsfilter\c600d489c09f07aeb05b55ad2c8db12fd0051d28409073eda4bbdcde67397ea3-removing: Access is denied.
PS C:\baseimages> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
PS C:\baseimages> docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
PS C:\baseimages> get-computeprocess


Id                : 82788C08-FCC9-4610-AF8B-3A84F97E74DC
Type              : Container
Isolation         : HyperV
IsTemplate        : True
RuntimeId         : 82788c08-fcc9-4610-af8b-3a84f97e74dc
RuntimeTemplateId :
RuntimeImagePath  : C:\a\b\c\windowsfilter\c600d489c09f07aeb05b55ad2c8db12fd0051d28409073eda4bbdcde67397ea3\UtilityVM
Owner             :



PS C:\baseimages> get-computeprocess | stop-computeprocess

Confirm
Are you sure you want to stop the compute process with ID '82788C08-FCC9-4610-AF8B-3A84F97E74DC'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A
PS C:\baseimages> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
PS C:\baseimages> cd C:\a\b\c\windowsfilter\
PS C:\a\b\c\windowsfilter> dir


    Directory: C:\a\b\c\windowsfilter


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        11/4/2016   6:25 PM                c600d489c09f07aeb05b55ad2c8db12fd0051d28409073eda4bbdcde67397ea3


PS C:\a\b\c\windowsfilter> cd .\c600d489c09f07aeb05b55ad2c8db12fd0051d28409073eda4bbdcde67397ea3\
PS C:\a\b\c\windowsfilter\c600d489c09f07aeb05b55ad2c8db12fd0051d28409073eda4bbdcde67397ea3> dir


    Directory: C:\a\b\c\windowsfilter\c600d489c09f07aeb05b55ad2c8db12fd0051d28409073eda4bbdcde67397ea3


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        10/5/2016   5:04 PM                Files
d-----        11/4/2016   6:25 PM                Hives
d-----        11/4/2016   6:25 PM                UtilityVM
-a----        11/4/2016   6:25 PM          16384 bcd.bak
-a----        11/4/2016   6:25 PM          12288 bcd.log.bak
-a----        11/4/2016   6:25 PM              0 bcd.log1.bak
-a----        11/4/2016   6:25 PM              0 bcd.log2.bak
-a----        11/4/2016   6:25 PM       42991616 blank-base.vhdx
-a----        11/4/2016   6:25 PM        4194304 blank.vhdx
-a----        11/4/2016   6:25 PM              4 layerchain.json


PS C:\a\b\c\windowsfilter\c600d489c09f07aeb05b55ad2c8db12fd0051d28409073eda4bbdcde67397ea3> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
PS C:\a\b\c\windowsfilter\c600d489c09f07aeb05b55ad2c8db12fd0051d28409073eda4bbdcde67397ea3> docker images -a
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
PS C:\a\b\c\windowsfilter\c600d489c09f07aeb05b55ad2c8db12fd0051d28409073eda4bbdcde67397ea3>
```

**Comment by darrenstahlmsft** [comment]
Why does a failed to remove the layer from the store? That seems like the real problem to me. What did it do before that change?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by swernli** [comment]
Several things going on here... TL;DR is that this is not a bug in the PR, it is a separate pre-existing issue with deleting base images when template Utility VMs are still running.

1) the reason it failed to delete is because you ran a hyper-v container, which started a template utility VM, which is using files in the folder.  Before the rename PR, I suspect this would've failed too, just with a different error message (likely "File in use").  We don't have a way to know during delete that we should shut down templates, so this will always fail until there is one.  You should not see this problem if you use only process isolation containers.  The real fix likely involves docker on Windows having an extra step in base layer deletion where it identifies any running template worker processes associated with that base layer and terminating them before trying to rename and delete the actual folder.

2) @darrenstahlmsft, the issue of entries being removed from the image store even if the delete fails is a flaw in docker itself, and has been around since forever.  The rename PR was actually an attempt to circumvent this problem.  When the delete happens, docker first removes entries from the image store, so the image is gone.  Then it tries to delete the layers, but if that fails, it does not delete them from the layer store.  So `docker images` won't show the image, but the layer store still holds some (possibly partially deleted) layers.  If the same image is imported later, the layer store says it already has the corresponding layers and ends up reusing the layers that were partially deleted.  By doing a rename first, we ensure that if the delete fails then at least the layer is not in a folder where it could be incorrectly reused by the layer store, and if the rename fails then we bail out before any partial deletion of the layer takes place so that if/when it gets reused the whole layer is still present.  So the PR is functioning as expected and giving us a slightly better failure case than what we had before.

**Comment by darrenstahlmsft** [comment]
Oh, I was reading this on my phone and thought that the running container was the created container, not the template utility VM. That makes a lot more sense. I'll take a look at this and see what we can do.
