### ISSUE TITLE
Rename docker run "--cpus" to "--limit-cpu"

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#28095]
Per the discussion on https://github.com/docker/docker/pull/27958#issuecomment-258598258, I think we should rename this flag, to keep consistency. Opening a new issue to track the discussion on this

ping @crosbymichael @tiborvass @yongtang @albers

**Comment by albers** [comment]
@thaJeztah I guess you mean `docker {run,create} --cpus` here?

**Comment by thaJeztah** [comment]
@albers oh, darn yes. Erm, AFK now so can't edit @tiborvass perhaps you can?

**Comment by yongtang** [comment]
I personally don't have a preference either way. Though I noticed that we have `--limit-memory` in services as well, but don't have `--limit-memory` in `docker run`. 
Wondering if that could be a concern?

#dibs

**Comment by thaJeztah** [comment]
@yongtang we may consider adding `--limit-memory` to `docker run`

**Comment by crosbymichael** [comment]
I talked to @stevvooe and @aluzzardi again about this today to make sure I was on the same page.

We are not going to change docker run to have --limit-cpu.  Services have the limit prefix because there is a distinction between a limit and a reservation.

What we are open to doing is adding `--cpus` and `--memory` to the services command as an alias for `--limit-cpus` and `--limit-memory` as they are straightforward and easy to use as flags if we think we need this type of consistency.  

We also want to modify swarm to pass NanoCpus to Docker Engine now that we have this supported so that we only do the quota and period calculation in the Engine.

**Comment by thaJeztah** [comment]
Thanks for the extra info @crosbymichael (and sorry for the back & forth @yongtang) your suggestion sounds good to me; want me to open an issue for it?

**Comment by crosbymichael** [comment]
@thaJeztah i just said NO, we are not going to add `--limit-` options to docker run if that is the suggestion you are talking about. That includes memory.

**Comment by thaJeztah** [comment]
@crosbymichael meant;

> What we are open to doing is adding --cpus and --memory to the services command as an alias for --limit-cpus and --limit-memory as they are straightforward and easy to use as flags if we think we need this type of consistency.

**Comment by crosbymichael** [comment]
Ok, the bold of the github username made it look like you where replying to him not me.  sry.  

Its fine if u want to open issues for both the flags on service as an alias and a swarmkit change to populate nanocpus to the docker api.

**Comment by linusguan** [comment]
@crosbymichael can you point me to the distinction between a limit and a reservation you mentioned? I am trying to understand the difference but the docs did not say anything about it. Thanks!
