### ISSUE TITLE
`login` and `push` make inconsistent result

### ISSUE THREAD

**Issue by fsword** [docker/docker#28225]
I use a private registry under my network, and `login` will get success.
```
/ # docker login proxy
Username: admin
Password: 
Login Succeeded
```

But, when I push a image to the private registry, it might use `docker.io` here and failed. 
```
/ # docker push proxy/library/hello:v1
The push refers to a repository [docker.io/proxy/library/hello]
6a8475e90792: Preparing 
a02596fdd012: Preparing 
unauthorized: authentication required
```

Why does the docker daemon cannot use the `proxy` host?

**Comment by thaJeztah** [comment]
It distinguishes between a "host" and a "repository" by checking if there's a `.` in the first component, so for example `proxy.local` would work.

**Comment by fsword** [comment]
Thank you for the comment. I want to read the source on it, could you help me to show the file path of git repo?

**Comment by fsword** [comment]
This design is so strange to me. Why we cannot use `slash` to checking it? 
eg:

```
proxy/library/hello - proxy for host, library for namespace, hello for image
library/hello - there is just one slash here, so no host is specified
```

**Comment by thaJeztah** [comment]
> Why we cannot use slash to checking it? 

Because the standard also allows `foobar.com/repository` as reference.

> want to read the source on it, could you help me to show the file path of git repo?

The "leading" definition for this is in the docker/distribution repo; https://github.com/docker/distribution/blob/master/reference/reference.go

But there are some different implementations in use, and there's work in progress to unify them; https://github.com/docker/distribution/pull/1778

As a workaround, you can include the port in the hostname, i.e. `proxy:5000/library/hello:v1`, which is handled as a host

/cc @stevvooe, who knows a lot more about the standard than I do

**Comment by fsword** [comment]
Thank you. It's very helpful
