### ISSUE TITLE
Docker network create doesn't inherit the MTU set in the Docker deamon

### ISSUE THREAD

**Issue by garthy** [docker/docker#28314]
**Docker network create doesn't inherit the MTU set in the Docker deamon**

The Docker deamon dockerd on some of our hosts has the mtu set to 1450 using the flag "--mtu=1450".
When a network is created using "docker network create <name>" the mtu for the bridge is set at 1500.
It would make sense for the network to use the mtu setting specified as   

**Steps to reproduce the issue:**
1. run docker with a custom mtu "dockerd --mtu=1450"
```
/usr/bin/dockerd --mtu=1400 --debug=true -H unix:///var/run/docker.sock
```
2. docker create a network  called test
```
docker network create test
8fbf416d37582ee1f0352625cb0cdff786e3516d10b8540e5bac458bebf53d95
```
3. list the networks
```
docker network ls
NETWORK ID          NAME                     DRIVER              SCOPE
e9c21cb405c9        bridge                   bridge              local               
bd0f75218012        host                     host                local               
3d81c322c790        none                     null                local               
8fbf416d3758        test                     bridge              local
```
4. ip link show | grep 8fbf416d3758
```
543: br-8fbf416d3758: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN 
```

**Describe the results you received:**

I expected the network created to honour the MTU set at the daemon level

**Describe the results you expected:**

Any networks created the MTU is set to 1500 

**Additional information you deem important (e.g. issue happens only occasionally):**

I am aware that I can set the MTU manually. This means I need to have knowledge about the docker I'm running on. I just want to be unaware of the underlying hardware and network configuration

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   19fddc2
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   19fddc2
 Built:        
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
docker info
Containers: 15
 Running: 7
 Paused: 0
 Stopped: 8
Images: 37
Server Version: 1.12.2
Storage Driver: btrfs
 Build Version: Btrfs v4.2.2
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.1.12-61.1.17.el6uek.x86_64
Operating System: Oracle Linux Server 6.7
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.858 GiB
Name: **********.novalocal
ID: P5PR:YBOT:SLNB:IPES:KTV6:GO26:6UU3:FUWC:UKU5:TFY6:P2VI:Z3MP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 59
 Goroutines: 87
 System Time: 2016-11-11T12:03:02.740206819-05:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Openstack, physical mix

**Comment by aboch** [comment]
Yes it does not inherit, because the daemon network options, like `--mtu`, `--fixed-cidr`, ... are only for the default automatically created bridge network `bridge`. They are not default options for all networks.

**Comment by mhaji** [comment]
@aboch What's the reason they're not the default option for networks created on a daemon which has the `--mtu` network option?

**Comment by aboch** [comment]
Because those options existed long before user could create networks, and their semantic was associated to the then only existing `docker0` bridge.
Once the `docker network create` feature was added, the semantic of those options was not modified, they still only affect the default `bridge` network.

Yours is a feature request, but in my opinion it would be very confusing that (some of) those options represent both the user chosen values for the `bridge` network as well the default values for newly user created networks.

Also that this will be true only for `--mtu` and `--dns...` options, while it is not (it does not make sense) for `--b`, `--bip`, `--fixed-cidr`, `--fixed-cidr-v6`, `--default-gateway`, `--default-gateway-v6` which are either strictly bridge specific or cannot be used by more than one network.

Also, if `--ipv6` becomes a default value and say user sets it to true, how would user create a pure ipv4 network after that ?

It would also not be possible to set a default for any network but still control the value for the default `bridge` network.

While this may make sense for your use case around the host mtu, I am not sure a common solution can be achieved by simply changing the semantic of `--mtu` flag. It seems to me yet a new flag would be needed to control the defaults.

**Comment by aboch** [comment]
Closing as responded.
