### ISSUE TITLE
Exposing types.Container directly on template options

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#28339]
Right now the api type `types.Container` is exposed directly on the `docker ps` formatter.
I think this is a mistake as these fields were not available before, and API types are subject to change over time (and that's ok because of API versioning), meanwhile the CLI interfaces must remain constant (or relatively constant).

Having `types.Container` directly available on the formatter users can assume this is a stable interface.
Namespacing under another field (".ContainerDetails", or some other much cleverer name) it is probably ok, but still likely way overkill for the CLI list format.

There's just too many ways things can conflict and cause problems down the road.

**Comment by yongtang** [comment]
It seems that the only purpose of `preProcessor` in `docker ps` is to capture if `.Size` is used in the template (so that we could set `opts.size = true`). I think we could ignore any field encountered other than `.Size` at the pre-processing stage. If there are unknown fields, it will be captured later anyway. Maybe we could use a `map[string]bool` instead?

**Comment by yongtang** [comment]
@cpuguy83 Add a PR #28347 to remove `types.Container` from `preProcessor` and redefined `preProcessor` as `map[string]bool`. Please take a look.

**Comment by maffiemouw** [comment]
git@github.com:docker/docker.git
@

- [ ]

**Comment by cpuguy83** [comment]
Ah, I see it's not as bad as I thought since we're only embedding in the preprocessor.
