### ISSUE TITLE
Docker fails to respond to commands (cannot find the file specified)

### ISSUE THREAD

**Issue by disintegrating** [docker/docker#28395]
Docker (quickstart terminal) does not respond to commands and fails with the message "An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json: open //./pipe/docker_engine: The system cannot find the file specified."

I have tried regenerating the certs, but it does not help.

This happens most often after I do a restart of my PC, not consistently, maybe 5 times out of 10. The only thing that fixes it is a full uninstall and reinstall. 

Edited to add: When this problem occurs, starting up the docker terminal, does not prompt me for user id and password like it usually does. 

**Output of `docker version`:**
$ docker version
Client:
 Version:      1.12.3-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bad4d12
 Built:        Tue Oct 25 08:07:33 2016
 OS/Arch:      windows/amd64
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version: open //./pipe/docker_engine: The system cannot find the file specified.

**Output of `docker info`:**
$ docker info
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info: open //./pipe/docker_engine: The system cannot find the file specified.

$ docker ps
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v
1.24/containers/json: open //./pipe/docker_engine: The system cannot find the fi
le specified.

$ docker-machine env
Error checking TLS connection: Error checking and/or regenerating the certs: The
re was an error validating certificates for host "192.168.99.100:2376": tls: oversized record received with length 29298
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.

$ docker-machine regenerate-certs
Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): y
Regenerating TLS certificates
Waiting for SSH to be available...
Detecting the provisioner...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...

$ docker ps
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v
1.24/containers/json: open //./pipe/docker_engine: The system cannot find the file specified.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Using Docker Quickstart Terminal (1.12.3-RC1) on Windows with NDIS 5 adapter, Oracle VM VirtualBox

**Comment by thaJeztah** [comment]
If no `DOCKER_HOST` environment variable is set, the client will try to use the default "named pipe" connection on windows (`//./pipe/docker_engine`). However, that pipe is only available if you're running "Native Windows" containers on a Windows 2010 or Windows Server 2016 host.

Since you are running docker toolbox (docker running inside a VirtualBox VM), you need to set the `DOCKER_HOST` environment variable when opening the shell.

This _should_ be done using the instructions that `docker-machine env` gives you, but in this case I see there's an error with the machine. Possibly some configuration files got out of sync because you tried to re-generate the certificates.

I'm going to close this issue here, because this issue is not related to the "docker engine" (this repository), but related to docker machine / docker toolbox, so if the above doesn't help you, feel free to open a new issue there; https://github.com/docker/toolbox

**Comment by megamindbrian** [comment]
I am getting this error on a fresh install.  I can't remember what I did to fix it.  It works on a different computer with no DOCKER_HOST.
