### ISSUE TITLE
document error

### ISSUE THREAD

**Issue by Usualme** [docker/docker#28398]
There are some errors in document just write `--name` as `-name`, in [Container naming chapter](https://blog.docker.com/2013/10/docker-0-6-5-links-container-naming-advanced-port-redirects-host-integration/).

I feel much puzzled at this point that why it didn't work since I type the right command like the document said. So, fix it as soon as possible in case others occur the same situation again.

**Comment by thaJeztah** [comment]
That link is not to the documentation, but a blog post from 2013 (for docker 0.6.5), in docker 0.6.5 it was still `-name` but that changed later https://github.com/docker/docker/blob/v1.12.3/docs/deprecated.md#old-command-line-options

I'll close this issue, because the blog is not part of this repository,  but I'll ask the team managing the blog if they can add a warning to those old blog posts
