### ISSUE TITLE
how to build 32 bit image in 64bit machine?

### ISSUE THREAD

**Issue by psraju** [docker/docker#28425]
**Description**

I am using 32bit/ubuntu as base image. when I try to build the image, architecture is showing x86_64. But the image is able to download i686 packages.
Run time we can change the arch using linux32. Is there any possibility to change the arch at build time?

**Steps to reproduce the issue:**
1. Add RUN arch to Dockerfile
2. build the docker

**Describe the results you received:**
x86_64

**Describe the results you expected:**
i686

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 274
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 243
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-96-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.465 GiB
Name: ubuntu_host
ID: OOTZ:NDXU:NVIB:4UGL:WNFB:KFNL:TRSA:GLNP:5K2W:2SG2:SUFK:RGHF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by unclejack** [comment]
The right way to have an x86 image is to build on top of an x86 image. The some-image in `FROM some-image` needs to be an x86 (32 bit) based image in order to produce an x86 (32 bit) image during the build.

Please keep in mind this issue tracker isn't meant to be used for general support questions. This issue tracker is meant to be used to track bugs, feature requests and pull requests to make code changes.

Those who need help when they learn how to use Docker (or other questions related to how to use Docker) should sign up and post here: https://forums.docker.com/

I'll close this issue now as the question has been answered and this isn't a bug. Please feel free to ask any questions on this issue. There's no need to open a new issue.

**Comment by psraju** [comment]
I tried docker experimental image i386/ubuntu:xenial-20160105. It seems like experimental image is also having some issue with the architecture. Architecture state is not changing while building x86 image on x86_64 host.

If i use linux32 utility before each command i am getting the expected results.
ex: ```RUN linux32 arch```, it is showing i686. is this the only way to get architecture as i686 in 64bit machine?

**Comment by justincormack** [comment]
Yes, for build each layer is independent so you might need linux32 on each
