### ISSUE TITLE
Is there a pre-start hook I can config when swarm cluster change the node position of a service?

### ISSUE THREAD

**Issue by ghostplant** [docker/docker#28570]
Is there a pre-start hook I can config when swarm cluster change the node position of a service?

Assume there are three swam node A, B, C and service X is current running on A;

when A crash, swarm automatically restarts X on either B or C, and I want to catch this change and prepare some environment configuration before X is to start on B (or C), such as layer quota limit, pre-mount, etc.

**Comment by thaJeztah** [comment]
No, there currently isn't. You can listen for "container" events on each node, but that probably won't help with this (there is an issue for "swarm mode events" in the swarm kit repository)

Also this issue may be related; https://github.com/docker/docker/issues/23880

I'll close this issue, because the question is answered, but feel free to write a more complete proposal / feature request with more details.
