### ISSUE TITLE
Embedded DNS is case-sensitive

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#28689]
Discovered this while discussing accepted characters for containers with @mstanleyjones;

```
docker network create foo
docker run -d --name FOO --net foo nginx:alpine
docker run -d --name foo --net foo nginx:alpine

docker run -it --rm --net foo alpine sh
/ # ping foo
PING foo (172.18.0.3): 56 data bytes
64 bytes from 172.18.0.3: seq=0 ttl=64 time=0.113 ms
64 bytes from 172.18.0.3: seq=1 ttl=64 time=0.099 ms
^C
--- foo ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.099/0.106/0.113 ms
/ # ping FOO
PING FOO (172.18.0.2): 56 data bytes
64 bytes from 172.18.0.2: seq=0 ttl=64 time=0.136 ms
64 bytes from 172.18.0.2: seq=1 ttl=64 time=0.096 ms
/ # ping fOo
ping: bad address 'fOo'
```

If looks like the embedded DNS is case sensitive, so resolving container IP addresses doesn't work if the wrong case is used. Also two containers on the same network can have the same name (but different case), which _should_ be a conflict, but currently isn't.

/cc @mavenugo

**Comment by sanimej** [comment]
@thaJeztah Though the standard DNS expects the names to be case insensitive the schema for embedded DNS is different, its based on container names. If the container names are case sensitive we have to keep it the same for resolution through embedded DNS. 

Are you suggesting that we make the container names case insensitive ? It probably makes sense, but I don't know if it was a conscious decision to have the names case sensitive.

**Comment by thaJeztah** [comment]
@sanimej t.b.h., I don't know what's best here; I see the conflict between container-names and DNS names; perhaps we should make container names case-insensitive, or indeed make it a conflict if they join the same network.

I wonder if the current situation leads to unexpected results (e.g. software that tries to resolve the IP address of a container, but is not able to).

Alternative could be to treat the containers case-insensitive for DNS (and use round-robin?)

**Comment by justincormack** [comment]
@sanimej I think this could cause all sorts of issues if you provide something that says it is a DNS server but does not match the specification for DNS, eg clients may be cacheing results or normalising or whatever.

I think we should switch container names to being DNS names. Perhaps we could start be recommending they are lower case? We could say if they are not they may cause unexpected behaviour.

cc @stevvooe

**Comment by sanimej** [comment]
@justincormack Embedded DNS server has to work with the schema that we have for naming containers, which is case sensitive today. Its not a limitation of the embedded server itself. But I don't know if it can cause any serious issues because for any queries outside the docker domain we forward the query as is. So the upstream server will treat the name in a case insensitive way. Can you give a specific example of what problem this can cause ?

Having said that, we should definitely move to a standard DNS naming scheme for swarm services/tasks. Its in the plans for 1.14

**Comment by sanimej** [comment]
@justincormack If the clients do normalizing of the mixed case names then yes, that can be an issue. We can make a recommendation to use lower case names. Some who have hit this issue do just that https://github.com/docker/docker/issues/21169

**Comment by thaJeztah** [comment]
Oh! @sanimej just reminded me that we already had an issue tracking this, that I forgot about (yup, it happens :blush:), closing as dup of https://github.com/docker/docker/issues/21169, please continue the discussion there

**Comment by stevvooe** [comment]
I know we said we're moving this to #21169, but want to characterize this problem before moving discussion there.

Before we discuss anything about case sensitivity, we need to understand the behavior during collisions. What is the expected behavior if two containers, on different daemons have the same name? We have seen similar problems, as discussed #28260, but the approach with DNS collisions seems to be to completely ignore them. As in that issue, the fundamental problem is exporting a locally validated value and expecting it to work without problems, case sensitive or not. In this case, we are exporting a container name from a local entity, while the other issue exports a low entropy random id.

As for case sensitivity, we really need to follow DNS rules to get this working right. In practice, DNS is actually quite relaxed. We should probably just follow this theme:

1. For non-colliding names, let's just return the case insensitive match.
2. For colliding names, favor the one that matches case.
3. For full collision, return both records pseudo-randomly.

To work correctly in such a relaxed schema, we need to balance this with visibility into collisions. There needs to be some way to query libnetwork and understanding which entries may collide, allowing users to make naming decisions base on impact.

By making this observable, we can provide mitigation to these problems without restricting container naming.
