### ISSUE TITLE
stop container show "containerd: deleting container                error=exit status 1" in daemon log

### ISSUE THREAD

**Issue by coolljt0725** [docker/docker#28821]
**Description**
stop a container, there will be a *Error* log in the daemon log.
`````
$ docker run -ti busybox
/ # exit
$
`````
````
DEBU[0013] containerd: process exited                    id=92e9e72c80007c38135cd9a15fc14d07a1547ad7566e2d30ca8109372cdc4b65 pid=init status=0 systemPid=32534
ERRO[0013] containerd: deleting container                error=exit status 1: "container 92e9e72c80007c38135cd9a15fc14d07a1547ad7566e2d30ca8109372cdc4b65 does not exist\none or more of the container deletions failed\n"
DEBU[0013] libcontainerd: received containerd event: &types.Event{Type:"exit", Id:"92e9e72c80007c38135cd9a15fc14d07a1547ad7566e2d30ca8109372cdc4b65", Status:0x0, Pid:"init", Timestamp:(*timestamp.Timestamp)(0xc420dab850)}

````

**Steps to reproduce the issue:**
1. start a container
2. stop a container
3. check the daemon log

**Describe the results you received:**
There is a error log in daemon log say `containerd: deleting container                error=exit status 1: "container 92e9e72c80007c38135cd9a15fc14d07a1547ad7566e2d30ca8109372cdc4b65 does not exist\none or more of the container deletions failed\n"`

**Describe the results you expected:**
There should be no error log if the container stop normally

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   03ba9a4
 Built:        Fri Nov 25 03:23:12 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.14.0-dev
 API version:         1.26
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          03ba9a4
 Built:               Fri Nov 25 03:23:12 2016
 OS/Arch:             linux/amd64
 Experimental:        false

```

**Output of `docker info`:**

```
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 4
Server Version: 1.14.0-dev
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: r1keowap3efura5ce9s0n3450
 Is Manager: true
 ClusterID: prthuhirjmtd28v0spdkq7fv9
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.175.125.216
 Manager Addresses:
  10.175.125.216:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: a6e649f5835b7ebf354a73ff3a80f3223e3cb5de (expected: 51371867a01c467f08af739783b8beafc154c4d7)
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.3.0
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 3.859 GiB
Name: centos
ID: OHKU:Z55T:2FD6:U7OF:BPAP:V7WE:JVLN:RJIK:SUR4:PE5E:PJCQ:B3QW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 31
 Goroutines: 126
 System Time: 2016-11-24T22:28:43.236602291-05:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
ping @mlaventure

**Comment by coolljt0725** [comment]
This also happen in `1.13.0-rc2`, so add 1.13 milestone 
@thaJeztah

**Comment by thaJeztah** [comment]
Confirmed, seeing this as well (running master in container);

```
DEBU[70200] Calling GET /_ping
DEBU[70200] Calling POST /v1.26/containers/create
DEBU[70200] form data: {"AttachStderr":true,"AttachStdin":true,"AttachStdout":true,"Cmd":null,"Domainname":"","Entrypoint":null,"Env":[],"HostConfig":{"AutoRemove":false,"Binds":null,"BlkioDeviceReadBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceWriteIOps":null,"BlkioWeight":0,"BlkioWeightDevice":null,"CapAdd":null,"CapDrop":null,"Cgroup":"","CgroupParent":"","ConsoleSize":[0,0],"ContainerIDFile":"","CpuCount":0,"CpuPercent":0,"CpuPeriod":0,"CpuQuota":0,"CpuRealtimePeriod":0,"CpuRealtimeRuntime":0,"CpuShares":0,"CpusetCpus":"","CpusetMems":"","Devices":[],"DiskQuota":0,"Dns":[],"DnsOptions":[],"DnsSearch":[],"ExtraHosts":null,"GroupAdd":null,"IOMaximumBandwidth":0,"IOMaximumIOps":0,"IpcMode":"","Isolation":"","KernelMemory":0,"Links":null,"LogConfig":{"Config":{},"Type":""},"Memory":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":-1,"NanoCpus":0,"NetworkMode":"default","OomKillDisable":false,"OomScoreAdj":0,"PidMode":"","PidsLimit":0,"PortBindings":{},"Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"RestartPolicy":{"MaximumRetryCount":0,"Name":"no"},"SecurityOpt":null,"ShmSize":0,"UTSMode":"","Ulimits":null,"UsernsMode":"","VolumeDriver":"","VolumesFrom":null},"Hostname":"","Image":"busybox","Labels":{},"NetworkingConfig":{"EndpointsConfig":{}},"OnBuild":null,"OpenStdin":true,"StdinOnce":true,"Tty":true,"User":"","Volumes":{},"WorkingDir":""}
DEBU[70200] container mounted via layerStore: /var/lib/docker/aufs/mnt/9c4522e98aab54137deaf7d88dfa2c8825d8bffb8ed89658b7106578ab820575
DEBU[70200] Calling POST /v1.26/containers/01ac07cda154b920089ea14b3683d446796bac7b6c418a072a8173fe3f67486d/attach?stderr=1&stdin=1&stdout=1&stream=1
DEBU[70200] attach: stdin: begin
DEBU[70200] attach: stdout: begin
DEBU[70200] attach: stderr: begin
DEBU[70200] Calling POST /v1.26/containers/01ac07cda154b920089ea14b3683d446796bac7b6c418a072a8173fe3f67486d/start
DEBU[70200] container mounted via layerStore: /var/lib/docker/aufs/mnt/9c4522e98aab54137deaf7d88dfa2c8825d8bffb8ed89658b7106578ab820575
DEBU[70200] Assigning addresses for endpoint sharp_wozniak's interface on network bridge
DEBU[70200] RequestAddress(LocalDefault/172.18.0.0/16, <nil>, map[])
DEBU[70200] Calling GET /v1.26/events?filters=%7B%22container%22%3A%7B%2201ac07cda154b920089ea14b3683d446796bac7b6c418a072a8173fe3f67486d%22%3Atrue%7D%2C%22type%22%3A%7B%22container%22%3Atrue%7D%7D
DEBU[70200] Assigning addresses for endpoint sharp_wozniak's interface on network bridge
DEBU[70200] Programming external connectivity on endpoint sharp_wozniak (b8ad5512ba606e1dc43f6feced02191588f022a7f8ea06e3112b64a2f5283e1d)
DEBU[70201] sandbox set key processing took 132.994184ms for container 01ac07cda154b920089ea14b3683d446796bac7b6c418a072a8173fe3f67486d
DEBU[70201] libcontainerd: received containerd event: &types.Event{Type:"start-container", Id:"01ac07cda154b920089ea14b3683d446796bac7b6c418a072a8173fe3f67486d", Status:0x0, Pid:"", Timestamp:(*timestamp.Timestamp)(0xc4212f7a90)}
DEBU[70201] libcontainerd: event unhandled: type:"start-container" id:"01ac07cda154b920089ea14b3683d446796bac7b6c418a072a8173fe3f67486d" timestamp:<seconds:1480076388 nanos:837024845 >
DEBU[70201] Calling POST /v1.26/containers/01ac07cda154b920089ea14b3683d446796bac7b6c418a072a8173fe3f67486d/resize?h=46&w=208
DEBU[70210] containerd: process exited                    id=01ac07cda154b920089ea14b3683d446796bac7b6c418a072a8173fe3f67486d pid=init status=0 systemPid=24680
ERRO[70210] containerd: deleting container                error=exit status 1: "container 01ac07cda154b920089ea14b3683d446796bac7b6c418a072a8173fe3f67486d does not exist\none or more of the container deletions failed\n"
DEBU[70210] libcontainerd: received containerd event: &types.Event{Type:"exit", Id:"01ac07cda154b920089ea14b3683d446796bac7b6c418a072a8173fe3f67486d", Status:0x0, Pid:"init", Timestamp:(*timestamp.Timestamp)(0xc421397dd0)}
DEBU[70210] attach: stdout: end
DEBU[70210] attach: stdin: end
DEBU[70210] attach: stderr: end
DEBU[70210] Closing buffered stdin pipe
DEBU[70210] Revoking external connectivity on endpoint sharp_wozniak (b8ad5512ba606e1dc43f6feced02191588f022a7f8ea06e3112b64a2f5283e1d)
DEBU[70210] Client context cancelled, stop sending events
WARN[70210] failed to close stdin: rpc error: code = 2 desc = containerd: container not found
DEBU[70210] Releasing addresses for endpoint sharp_wozniak's interface on network bridge
DEBU[70210] ReleaseAddress(LocalDefault/172.18.0.0/16, 172.18.0.3)
```

**Comment by thaJeztah** [comment]
ping @mlaventure PTAL

**Comment by thaJeztah** [comment]
Oh, I see you opened a PR already; https://github.com/docker/containerd/pull/357

**Comment by dm0-** [comment]
Probably related:  If I run `docker run --rm busybox uname -a` with 1.12.4, there is about a 50/50 chance that dockerd will log a warning `failed to close stdin: rpc error: code = 2 desc = containerd: container not found`.  The change currently at docker/containerd#357 does not fix this.

**Comment by coolljt0725** [comment]
@dm0-  Does https://github.com/docker/docker/pull/28854 fix your issue?

**Comment by dm0-** [comment]
@coolljt0725 Thanks.  The commits don't apply, but I was able to backport it, and it seems to work so far.

**Comment by thaJeztah** [comment]
opened https://github.com/docker/docker/pull/30226 to bump containerd version

**Comment by duglin** [comment]
@coolljt0725 did you ever figure out why delete() was being called in the first place? It seems odd that w/o the --rm flag on "docker run" that containerd would even try to delete the container at all.

**Comment by mlaventure** [comment]
@duglin `delete()` on `containerd` actually calls `runc delete <containerd-id>` to clean up the runc state. The container as seen by `docker` still exist in a stopped state

**Comment by duglin** [comment]
ah right, I forgot about that split - thanks

**Comment by AlexShu88** [comment]
@thaJeztah , after running sudo docker service update --force --update-delay 120s,  

error logs as below, is this caused because the  Docker daemon shuts down faster than the containers are cleaned (probably because of the container's ignoring signals or something)
can i resolve this issue  to change the daemon's shutdown-timeout in the Docker daemon configuration file. The default is 10s or something,  can I change it to 60s to avoid  these issues anymore?


https://github.com/docker/for-linux/issues/1148

bvs-dmg101_messages.20210215.log:6698:2021-02-15T16:39:30+09:00	vm.bvs-dmg101.messages	{"message":"Feb 15 16:39:30 bvs-dmg101 dockerd: time=\"2021-02-15T16:39:30.980641647+09:00\" level=error msg=\"c011ed50e27af1c2d00cd0935c94b84dff4659851ba409f0b4da87dd6565515e cleanup: failed to delete container from containerd: no such container\""}
bvs-dmg101_messages.20210215.log:8445:2021-02-15T16:56:28+09:00	vm.bvs-dmg101.messages	{"message":"Feb 15 16:56:28 bvs-dmg101 dockerd: time=\"2021-02-15T16:56:28.641683869+09:00\" level=error msg=\"6356cde7d5543b846e35bb6868b15295d4ee88c8e1d150ab70fb467246b71c7f cleanup: failed to delete container from containerd: no such container\""}
bvs-dmg101_messages.20210215.log:8966:2021-02-15T17:01:24+09:00	vm.bvs-dmg101.messages	{"message":"Feb 15 17:01:24 bvs-dmg101 dockerd: time=\"2021-02-15T17:01:24.968721694+09:00\" level=error msg=\"2b3dded5ba1bcd3958d9b39b711ea06f1f5b649839a54708d97e6923354eab03 cleanup: failed to delete container from containerd: no such container\""}
bvs-dmg101_messages.20210215.log:10247:2021-02-15T17:12:17+09:00	vm.bvs-dmg101.messages	{"message":"Feb 15 17:12:17 bvs-dmg101 dockerd: time=\"2021-02-15T17:12:17.447506570+09:00\" level=error msg=\"2cce5b75d389afd72d417a629f9d4b54a42900b5070ea8a116826c0a36e7af71 cleanup: failed to delete container from containerd: no such container\""}
bvs-dmg101_messages.20210215.log:10882:2021-02-15T17:16:49+09:00	vm.bvs-dmg101.messages	{"message":"Feb 15 17:16:49 bvs-dmg101 dockerd: time=\"2021-02-15T17:16:49.263524802+09:00\" level=error msg=\"7470ac8d8deead252164f59618c59445e6d2cbae0e1930a4be3fd9bf9eb734aa cleanup: failed to delete container from containerd: no such container\""}
bvs-dmg103_messages.20210215.log:8727:2021-02-15T16:42:00+09:00	vm.bvs-dmg103.messages	{"message":"Feb 15 16:42:00 bvs-dmg103 dockerd: time=\"2021-02-15T16:42:00.597461570+09:00\" level=error msg=\"354368df9408b7f4e0997089ee32490dd7cac6bbb29ec0e8082746ddb11b5a5a cleanup: failed to delete container from containerd: no such container\""}
bvs-dmg103_messages.20210215.log:10464:2021-02-15T16:58:57+09:00	vm.bvs-dmg103.messages	{"message":"Feb 15 16:58:57 bvs-dmg103 dockerd: time=\"2021-02-15T16:58:57.665240899+09:00\" level=error msg=\"dee2f58f797ddbf9b4cc05a201836915a02e0d7d084587f2e1b7a1dc270116ff cleanup: failed to delete container from containerd: no such container\""}
bvs-dmg103_messages.20210215.log:12541:2021-02-15T17:14:33+09:00	vm.bvs-dmg103.messages	{"message":"Feb 15 17:14:33 bvs-dmg103 dockerd: time=\"2021-02-15T17:14:33.199061243+09:00\" level=error msg=\"05936cb1b5961629e8c752cc2ed6a3f8cb7547b7998f3271e5686bcaa8dbb076 cleanup: failed to delete container from containerd: no such container\""}
bvs-dmg103_messages.20210215.log:13297:2021-02-15T17:19:40+09:00	vm.bvs-dmg103.messages	{"message":"Feb 15 17:19:40 bvs-dmg103 dockerd: time=\"2021-02-15T17:19:40.464146524+09:00\" level=error msg=\"46578120a0bb3837bffdda96eca8d7fc74b988ff7309bbb2789ea335ca1708fa cleanup: failed to delete container from containerd: no such container\""}

**Comment by snowsky** [comment]
Recently I also run into the similar issue as @AlexShu88 mentioned. The version of Ubuntu docker snap is 20.10.6 916 on latest/beta channel.
