### ISSUE TITLE
docker stack deploy should have a single file option

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#28960]
`docker stack deploy` now has `--compose-file` and `--bundle-file`, which are mutually exclusive.

Since a bundle file is JSON and a compose file is YAML it should be trivial to automatically detect the file format (a bundle file will begin with `{`, possibly followed by whitespace, and a bundle file will not).

I think it would be much simpler to only have a single option, possibly `-f` for consistency with other tools.

**Comment by AkihiroSuda** [comment]
It would be even better if we can set `docker-compose.yml` as the default value of `-f`

**Comment by yongtang** [comment]
Added a PR #28998 for this issue. It seem that in 1.12.3 the flag was still `--file` so probably no need for deprecation if the PR is accepted before 1.13.0 release.

**Comment by dnephin** [comment]
I think it's better to be explicit about what you're providing. JSON is valid yaml, so someone could generate a yaml file that is interpreted as json, but is not a valid dab.

Also `--bundle` is experimental. We should not be adding dab file support to a non-experimental flag, because we may still want to remove it.

We don't need a `-f`, we have a `-c` for the `--compose-file` option.

**Comment by AkihiroSuda** [comment]
@dnephin @aaronlehmann 

WDYT about this alternative idea?

* `--file`: only supports the compose YAML
* `--file-experimental`: supports both compose YAML and DAB JSON. The flag will be removed when we remove or promote DAB.

**Comment by dnephin** [comment]
I think the current flags are more appropriate, both in name and functionality.

**Comment by AkihiroSuda** [comment]
https://github.com/docker/docker/pull/28998 is closed, is this issue closable as well?
@thaJeztah @aaronlehmann @dnephin

**Comment by thaJeztah** [comment]
Lets close for now, we can reconsider in future
