### ISSUE TITLE
Ability to Rebalance/Redistribute containers across nodes in docker swarm.

### ISSUE THREAD

**Issue by FarhadF** [docker/docker#28989]
Hi guys,

I was wondering if there is a feature for redistributing better to say rebalancing containers on swarm nodes.
The scenario is: my containers are all on a single node after other nodes failed, now they are back online and I need to redistribute/rebalance them across the nodes. I can drain the node but it will cause an empty node.

Docker Version:
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:39:14 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:39:14 2016
 OS/Arch:      linux/amd64
```

Regards,
Farhad

**Comment by thaJeztah** [comment]
Looks like this is a duplicate of https://github.com/docker/docker/issues/24103, which contains some information why this is not implemented. If you want to force rebalancing, using `docker service update --force <service>` in 1.13, or `docker service update ...` to change a property (e.g., add an env-var or label` should work.

I'm closing this because this is a duplicate, please continue the discussion on the linked issue
