### ISSUE TITLE
'docker build' on FreeBSD fails to access DNS to download packages

### ISSUE THREAD

**Issue by yurivict** [docker/docker#28995]
I am trying to build the container with Dockerfile on FreeBSD 11:
```
FROM lexaguskov/freebsd:latest
RUN ASSUME_ALWAYS_YES=yes pkg install pkg
RUN pkg install kodi
CMD ["/usr/local/bin/kodi"]
```
It fails:
```
 ---> Running in 308c4f4714bc
pkg: Error fetching http://pkg.FreeBSD.org/freebsd:10:x86:64/latest/Latest/pkg.txz: No address recordBootstrapping pkg from pkg+http://pkg.FreeBSD.org/freebsd:10:x86:64/latest, please wait...
```

Same when I add the argument ```--dns=8.8.8.8``` to the daemon command line.

Installed from the port sysutils/docker-freebsd.

(I never had it running, the first time I am trying.)

**Comment by justincormack** [comment]
Unfortunately this was an unofficial port that was never upstreamed so
can't help you here.

Hopefully there will be an upstream port soon. I don't know where the
source for that is.

On 30 Nov 2016 17:58, "yurivict" <notifications@github.com> wrote:

I am trying to build the container with Dockerfile on FreeBSD 11:

FROM lexaguskov/freebsd:latest
RUN ASSUME_ALWAYS_YES=yes pkg install pkg
RUN pkg install kodi
CMD ["/usr/local/bin/kodi"]

It fails:

 ---> Running in 308c4f4714bc
pkg: Error fetching
http://pkg.FreeBSD.org/freebsd:10:x86:64/latest/Latest/pkg.txz: No
address recordBootstrapping pkg from
pkg+http://pkg.FreeBSD.org/freebsd:10:x86:64/latest, please wait...

Same when I add the argument --dns=8.8.8.8 to the daemon command line.

Installed from the port sysutils/docker-freebsd.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/docker/docker/issues/28995>, or mute the thread

**Comment by yurivict** [comment]
The port takestye source from here: https://github.com/kvasdopil/docker

**Comment by yurivict** [comment]
I looked at the current master, it is very different from the old FreeBSD port. It fails to compile in the network code due to the missing docker/libnetwork/ns/init_freebsd.go, etc.

There are "freebsd" clauses under +build, which means that somebody made an effort to build on the FreeBSD.

Is there any chance Docker port to FreeBSD will be completed and supported? It looks like it should take only a few hours for somebody familiar with how Docker handles networking. It looks like linux netlnik is used (github.com/vishvananda/netlink) which should be replaced with something on FreeBSD.

**Comment by justincormack** [comment]
We support a FreeBSD client, but there are many things broken on the server
side.

What is needed is a version of the Linux runc that works with jails. The
ZFS parts for the storage driver are already supported.

I am planning to clean up the obvious errors if no one else does, but
definitely looking for contributors.

**Comment by justincormack** [comment]
Its definitely more than a few hours work. The Solaris port is in the process of being merged, which should help a bit. If anyone is interesting in working on it do let me know.

**Comment by thaJeztah** [comment]
Yes, the changes from @kvasdopil were merged into this repository, but it's not complete

I'll close this issue, because FreeBSD is not currently supported, but feel free to continue the conversation

**Comment by yurivict** [comment]
One related thought I have is about the use of Netlink. Netlink is linux-specific, yet it is referred to in many places like daemon_unix.go and encryption.go. This makes Docker linux-specific. You should either move all Netlink-related code into xxx_linux.go modules and define a generic network interface not mentioning Netlink, or use some standard protocol instead, like Unix sockets. Is there an effort or plan to address Netlink?

**Comment by thaJeztah** [comment]
@yurivict if someone wants to take on maintenance / work on a FreeBSD build, we can consider, but it's not a priority currently.

**Comment by xorander00** [comment]
I'm willing to work on this a bit, but not sure when I'll be able to get to it.  I have a handful of applications that are pretty Docker-specific, and as such they're running within VMs right now.  It's a pain in the neck.

I'll start looking through the sources and history this weekend, but what are the primary technical focus points for porting?  Netlink has been mentioned, but what else?

**Comment by yurivict** [comment]
Netlink causes the compilation failure. Since Solaris port is in progress (?), this may have been solved there. (Solaris also doesn't have Netlink.)

runc not working on FreeBSD was also mentioned.

Other than this, it needs to be built and tested to see what the next issues are if any. Previous versions ran on FreeBSD, and those patches were merged upstream (see comments above).
