### ISSUE TITLE
Gliderlabs/registrator:v6 always get new container with HostIP: 0.0.0.0

### ISSUE THREAD

**Issue by phuthinh2202** [docker/docker#29107]
I built docker swarm follow the link: http://www.nachum234.com/virtualization/docker/install-docker-swarm-with-consul-consul-template-registrator-and-haproxy/ 
I use "docker-compose -H :<port-docker-swarm> up -d" to create a new container on docker worker. But registrator:v6 on this docker worker always regis with consul-server that HostIPaddress: 0.0.0.0:<host-port>.

**Comment by thaJeztah** [comment]
It looks like you're trying to run "classic" swarm (https://docs.docker.com/swarm/), not swarm _mode_, which was added in docker 1.12 (https://docs.docker.com/engine/swarm/)

Bugs in "classic" swarm should be reported in the issue tracker for that project; https://github.com/docker/swarm/issues

However, this looks like a support question, and the GitHub issue tracker isn't really intended for that. I suggest either asking the author of that tutorial; http://www.nachum234.com/virtualization/docker/install-docker-swarm-with-consul-consul-template-registrator-and-haproxy/

Or discussing on the docker user forums; https://forums.docker.com or the community Slack channel https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/

I'll close this issue because of the above, but feel free to comment after I closed
