### ISSUE TITLE
FEATURE REQUEST: Allow full semver spec as valid image tags

### ISSUE THREAD

**Issue by tniswong** [docker/docker#29189]
Source: [http://semver.org/spec/v2.0.0.html#spec-item-10](http://semver.org/spec/v2.0.0.html#spec-item-10)

> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

Currently, the inclusion of a plus sign (+), as denoted for build metadata, is rejected as an invalid tag. I would have hoped that the full spec of semver be considered valid for use as a docker tag.

**Comment by justincormack** [comment]
cc @stevvooe

**Comment by stevvooe** [comment]
Here are the duplicates:

https://github.com/docker/distribution/pull/1202
https://github.com/docker/distribution/issues/1201
https://github.com/docker/docker/issues/27269
https://github.com/docker/docker/issues/18168

First, let's take a peak at this clause:

> Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence.

If we read that carefully, it means that two things built that have different metadata are the same thing. Put differently, it means that the data after the `+` means nothing. Two images with the same version and different build metadata should be functionally equivalent, meaning only one should be active in a registry at anytime. However, you are free to use this metadata as you want, and may disagree with the implications of this clause, as it is somewhat vague.

The main issue with the `+` character, as I have said in the past, is that it is ambiguously encoded in urls, which are heavily used through docker and satellite build systems. Introducing it may cause untold errors and incompatibilities.

In the past, the due diligence required to introduce `+` to tags was laid out here:

https://github.com/docker/distribution/pull/1202#issuecomment-160761964

That criteria applies today.

Unfortunately, we don't have the resources or bandwidth to address all those items. Since docker is an open source project, you're perfectly welcome to take on that work. I'd recommend starting with a road map issue, enumerating those steps and then follow them.

The other option is to not rely on `+` in image tags.

**Comment by thaJeztah** [comment]
I'll go ahead and close this issue; let's keep https://github.com/docker/distribution/pull/1202 for tracking this, so that the discussion doesn't diverge, but thanks for opening this feature request
