### ISSUE TITLE
service created with global mode on specified node in swarm mode

### ISSUE THREAD

**Issue by ziqingzhu** [docker/docker#29384]
**Description**

I have 3 nodes in swarm mode,such as 
node1
node2
node3
I want run only one task on node1 and node2, but not on node3
if i create the service with replicated mode and set 2 sacle, it maybe run  two tasks on node1 or node2(i set some constraints)
if create the service with global mode, it will run one task on each node, but i don't want it run on node3

**Describe the results you expected:**
Could global mode run in specified node or can I get my expect result by other way?

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64
```

**Comment by thaJeztah** [comment]
you can set a constraint, e.g. `--constraint 'node.hostname != node2'`, see https://docs.docker.com/engine/reference/commandline/service_create/#/specify-service-constraints---constraint

There was an issue with constraints, combined with `mode=global`, but I think it's fixed in the latest 1.12 release (but i may be mistaken, and it could be in 1.13)

I'll close this issue, because the github issue tracker is for reporting bugs and feature requests; for other topics, consider using;

- https://forums.docker.com
- the docker community slack channel (https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- StackOverflow

but feel free to continue the discussion
