### ISSUE TITLE
Unusual ownership behavior of bind-mounted volumes

### ISSUE THREAD

**Issue by Risto-Stevcev** [docker/docker#29409]
**Steps to reproduce the issue:**
1. Create a Dockerfile
2. In the Dockerfile, include: `FROM node:6`
2. In the Dockerfile, include a new user and switch to that user like so:
```
RUN useradd -m -s /bin/bash pureuser
WORKDIR /home/pureuser
USER pureuser
```
3. Build the image and run your container:
`docker run --rm -itv $(pwd):/home/pureuser/src imagename bash`

**Describe the results you received:**
Note that the volume will be mounted but the owner of the folder will be `node` instead of `pureuser`, which effectively breaks the functionality because `pureuser` doesn't have superuser privileges.

**Describe the results you expected:**
The owner should really be `pueruser`, since that's the user that is logged in when you run the container. Using `--user pureuser` doesn't change anything in this regard.

This also affects composability of containers, because all of my `purescript` containers on Docker hub used to work fine with the above command until the nodejs docker team decided to include a `node` user in all of the containers to hotfix some issue a month or so ago.

**Comment by Risto-Stevcev** [comment]
```
$ docker --version
Docker version 1.12.3, build 6b644ec
```

**Comment by thaJeztah** [comment]
When bind-mounting a directory (or files) from the host, those files are mounted as-is in the container; docker does not change permissions on those files, because doing so would change those permissions on the host (consider bind mounting `-v /home/users/myname/:/somewhere` resulting in your home directory permissions being changed to a different user 😱)

You _can_ change the permissions of those files on the host, before bind-mounting them in the container so that they match the `uid:gid` of the user inside the container; see my answer on stack overflow on this subject; http://stackoverflow.com/a/29251160/1811501

Note that there _are_ situations where files may be bind-mounted with different permissions inside the container;

- when using boot2docker / virtualbox, files and directories are always owned by `uid:gid`  `1000:1000` due to limitations of virtualbox guest additions
- when using docker for mac, permissions are "ignored", so that _any_ process in the container sees them as if they are owned by that user.

This is not something that can be fixed currently, but may be possible in future, depending on certain features being implemented in the Linux kernel.

I'm going to close this issue for that reason, but feel free to comment after I closed

**Comment by Risto-Stevcev** [comment]
@thaJeztah I think there might be a misunderstanding on what is the issue here. I'll try to clarify:

- I have a purescript project with a number of files. On my host machine (no docker involved), the owner of these files and folders is `risto:risto`, like this:
```
$ ls -alF
...
-rw-r--r--   1 risto risto   310 Dec 14 12:00 package.json
drwxr-xr-x   2 risto risto  4096 Oct 23 02:27 .pulp-cache/
drwxr-xr-x   3 risto risto  4096 Nov 30 10:20 src/
...
```

- I run `docker run --rm -itv $(pwd):/home/pureuser/src gyeh/purescript:0.10.1 bash` as usual to work on my project
- Docker mounts `/home/pureuser/src` and it has this ownership inside the container:
```
$ pwd
/home/pureuser
$ ls -alF
...
drwxr-xr-x 8 pureuser pureuser 4096 Dec 14 11:01 src/
...
$ ls -alF src/
drwxr-xr-x   2 pureuser pureuser  4096 Oct 23 00:27 .pulp-cache/
-rw-r--r--   1 pureuser pureuser   310 Dec 14 11:00 package.json
drwxr-xr-x   3 pureuser pureuser  4096 Nov 30 09:20 src/
```
So obviously docker does change the ownership of the files inside the container (but not on the host machine). This is how I set it up and expect the container to work.
- About a month or so ago, the container my `gyeh/purescript` containers are based off of, `node:6`, was updated to include a `node` user. This conflicts with the `pureuser` user I created in the container. Now when I run the same command, this is what happens:
```
$ pwd
/home/pureuser
$ ls -alF
...
drwxr-xr-x 8 node node 4096 Dec 14 11:01 src/
...
$ ls -alF src/
drwxr-xr-x   2 node     node      4096 Oct 23 00:27 .pulp-cache/
-rw-r--r--   1 node     node       310 Dec 14 11:00 package.json
drwxr-xr-x   3 node     node      4096 Nov 30 09:20 src/
```
Obviously it's ownership of the folder is now `node` instead of `pureuser`. This is unintuitive and not very composable, because I based my container off of `node:6`, but the actual logged in user is `pureuser`. Shouldn't it be `pureuser:pureuser` instead of `node:node`?

I can modify the Dockerfiles I've hosted to get this working, but so far I haven't found any solution that works besides giving up and basing things off of the base container's `node` user, which could change again without warning and break my containers again.

- For some reference, see the last comments on this [issue](https://github.com/nodejs/docker-node/pull/263) and this [issue](https://github.com/nodejs/docker-node/issues/289). But this is really a limitation/bug of docker and not this specific container, since this can happen easily with any base container.

I'm running Linux if that's helpful info.

**Comment by thaJeztah** [comment]
I think the issue here is that the `node:node` or `pureuser:pureuser` names are simply a presentation of the numeric `uid:gid` values mapped to a name (from `/etc/passwd` inside the container).

Previously, the node image did not have a user added, so the first user that was added (`pureuser`) got `uid:gid` `X:Y`.

Now that the node image itself already adds a user, _that_ user (`node`) gets `uid:gid` `X:Y`, and the next user that's being added (`pureuser`) gets `X+1:Y+1`. Because of this, files with the _same_ `uid:gid` would previously show `pureuser` to be the owner, but now `node`.

You can see this happening if you run the following;

```
docker run -it --rm node:6 sh -c 'useradd -m -s /bin/bash pureuser && tail -n 2 /etc/passwd'

node:x:1000:1000::/home/node:/bin/bash
pureuser:x:1001:1001::/home/pureuser:/bin/bash
```

What does `ls -n` show (i.e., show the _numeric_ id's instead of the id's mapped to a name)? And what does `cat /etc/passwd` show?

**Comment by Risto-Stevcev** [comment]
Ah yeah, you're right. `ls -n` is showing `1000:1000`, which is the same `uid:gid` as `risto:risto` on the host machine. Since now `node` has `uid:gid` of `1000:1000` instead of `pureuser`, which is `1001:1001`, then it shows the owner as `node`. I see the issue now with making the current implementation more flexible.

**Comment by thaJeztah** [comment]
fwiw, if there's no reason to have _two_ users in your images, it may be worth switching your app to assume it's running as `node`; you can then remove the `adduser` line, and basically run the same as before.

**Comment by Risto-Stevcev** [comment]
Yeah that would be one solution, but it makes composing containers more frustrating. The nodejs team that wrote that container might decide to fix the new issue by removing that user again, for example, which would again spontaneously break my containers if they were pulled from docker hub after the change. I would also need to update docs on each change like this and I have no control over it.

Maybe there should be a version attribute just like libraries but for containers, so you can do something like `node:6:v1.0` or `node:6:commit_hash`, so that base containers don't spontaneously change without the author's knowledge. Afaict there's no way to tell if base containers have changed, or to freeze the base container to a particular version.
