### ISSUE TITLE
docker pull error

### ISSUE THREAD

**Issue by russellgao** [docker/docker#29438]
I docker pull a image, I docker login first and return Login Succeeded,but then I use docker  pull ,return 
WARNING: Error loading config file:/home/dnet/.docker/config.json - EOF
Pulling repository xxxxx
unauthorized: authentication required
that all I wirte in python script
and finally I docker pull in bash,it works successful, why? can any ideas have?

**Comment by thaJeztah** [comment]
please keep in mind that the GitHub issue tracker is for tracking bugs and feature requests, and not a general support forum; since this is a support question for _running_ docker, could you use one of the following?;

- https://forums.docker.com
- the docker community slack channel https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/
- StackOverflow

I'll close this issue here because of the above, but hope this helps you further

**Comment by russellgao** [comment]
sorry ,I use above  and follew with interes feature requests,thanks !
