### ISSUE TITLE
Failed to start docker daemon on linux kernel 4.9.0-0

### ISSUE THREAD

**Issue by rakshazi** [docker/docker#29488]
**Description**
Failed to start docker daemon on linux kernel 4.9.0-0

**Steps to reproduce the issue:**
1. Install linux kernel 4.9.0-0
2. Try to start docker daemon via systemd service unit

**Describe the results you received:**
Log from `journalctl -xe`:

```
-- Subject: Начинается запуск юнита docker.service
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Начат процесс запуска юнита docker.service.
дек 16 20:21:59 notebook dockerd[6603]: time="2016-12-16T20:21:59.872935615+02:00" level=info msg="libcontainerd: new containerd process, pid: 6621"
дек 16 20:22:00 notebook dockerd[6603]: time="2016-12-16T20:22:00.890205679+02:00" level=error msg="[graphdriver] prior storage driver \"aufs\" failed: driver not supported"
дек 16 20:22:00 notebook dockerd[6603]: time="2016-12-16T20:22:00.890427835+02:00" level=fatal msg="Error starting daemon: error initializing graphdriver: driver not supported"
дек 16 20:22:00 notebook systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
дек 16 20:22:00 notebook systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Ошибка юнита docker.service
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Произошел сбой юнита docker.service.
-- 
-- Результат: failed.
```
**Describe the results you expected:**
Docker daemon must start 

**Additional information you deem important (e.g. issue happens only occasionally):**
`lsb_release -a`:

```
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	16.10
Codename:	Fringilla
```

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.7.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 19:42:59 2016
 OS/Arch:      linux/amd64
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version: read unix @->/var/run/docker.sock: read: connection reset by peer
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical

**Comment by thaJeztah** [comment]
This is the problem here;

    [graphdriver] prior storage driver \"aufs\" failed: driver not supported

The `aufs` storage driver depends on the `linux-image-extra` packages being installed; those packages are tied to the kernel version, so should be upgraded as well after upgrading the kernel.

IIRC, Manjaro linux is based on Arch, which is known to be distributing "bleeding edge" packages, and because of that is known to break things regularly. For this reason, we don't have official packages for that distribution.

To resolve this; check if aufs is available for that kernel version, or select a different storage driver. When selecting a different storage driver, you may want to do a "factory reset" and remove your `/var/lib/docker` directory; doing so will remove all your images and containers.

For kernel 4 and up, the `overlay2` (or `overlay`) diver may be a good choice, but this depends on your use case (see https://docs.docker.com/engine/userguide/storagedriver/selectadriver/)

I'm going to close this issue, because this is not a platform for which we ship packages, and this looks not to be a bug in docker, but feel free to comment after I closed.

**Comment by jbtrystram** [comment]
Hi,

I just upgraded to kernel 4.9 on Ubuntu 16.10 and get the same error. looks like aufs is not shipped with the 4.9 ubuntu kernel

**Comment by thaJeztah** [comment]
aufs has never been _part_ of the kernel, and always has been an optional package (see my comment above); depending on the distribution, the `linux-image-extra` may provide that driver. However, only the kernel version that _ships_ by the distro is officially supported to run docker on; sometimes distro kernel versions have specific back ports for your distribution.

As mentioned above; on kernel 4 and up, `overlay2` (or `overlay` on older 4.x kernels) is a good choice instead

**Comment by abpostelnicu** [comment]
I thinks this solves the issue: https://stackoverflow.com/questions/37110291/how-to-enable-aufs-on-debian
