### ISSUE TITLE
what is the equivalent option for "--privileged" in Docker Swarm 1.12?

### ISSUE THREAD

**Issue by chenghsiang** [docker/docker#29503]
Pre Docker 1.12, I can launch a container with "--privileged" option, so that "mycontainer" can do NAT.
      docker run -itd **--privileged** --net mynetwork --name mycontainer ubuntu /bin/bash
In Docker Swarm 1.12, what is the equivalent option so that I can create a container on a specific overlay network with "--privieged" option?

**Comment by thaJeztah** [comment]
there currently isn't, and most likely `--privileged` won't be added, but more fine grained "security profiles". This is currently tracked in https://github.com/docker/docker/issues/24862

i'll close this issue, because this is already being tracked, you can follow progress by subscribing to the issue i linked

**Comment by Dev26112001** [comment]
docker run -it --name container2 --privilaged --volumes-from container1 ubuntu /bin/bash
While I am  trying to execute the above command, I am getting the error shown below:-
unknown flag: --privilaged
See 'docker run --help'.

Please help me resolve this issue asap.

**Comment by thaJeztah** [comment]
Did you try running `docker run --help` ? Looks like you made a typo and typed `--privilaged` in stead of `--privileged`

**Comment by Dev26112001** [comment]
Yeah , Thank you Sir.
I realized it later that I made that mistake.
