### ISSUE TITLE
I want to run docker in special indepent directory ?

### ISSUE THREAD

**Issue by timchenxiaoyu** [docker/docker#29518]
I want to run docker in special indepent directory ? for example docker run --dir 
 How to solve this?

**Comment by thaJeztah** [comment]
Please keep in mind that the GitHub issue tracker is not a general support forum, but for reporting bugs and feature requests. For questions about _using_ docker, consider using;

- https://forums.docker.com
- the community slack channel (https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- StackOverflow

Could you try one of those instead? It may be worth adding a bit more information about what you're trying to do when you're posting there, as it's not very clear from your current question 

I'll close this issue here
