### ISSUE TITLE
docker-compose.yml restart:always does not restart dependent services

### ISSUE THREAD

**Issue by tomekit** [docker/docker#29514]
I've got 2 services, one of them `stock_app` and the other `grafana_graphite`.
`stock_app` is dependent on `grafana_graphite`.
`stock_app` should start at boot.

When I restart the host, the `stock_app` service starts, but dependent service `grafana_graphite` is not started.

**Steps to reproduce the issue:**
1. Define 2 services, let's call them A and B
2. Add dependency, so the service A depends on service B using `depends_on`
3. Add `restart: always` to service A
4. Restart docker host

**Describe the results you received:**
`stock_app` service running

**Describe the results you expected:**
Both `stock_app` and `grafana_graphite` service running

**Additional information you deem important (e.g. issue happens only occasionally):**
When `orphaned` service runs without its dependency, when you remove the `restart: always` from the root service and run the: `docker-compose up -d` I got:
```
Starting grafana
Recreating event_stock_app_1
ERROR: for stock_app  Driver devicemapper failed to remove root filesystem c3643219d54f38026315c463fa983427724c0669fa9f686f111a68b7a5146611: Device is Busy
```

I've removed both services and tried  `docker-compose up -d` once again, got:
```
Creating grafana
Recreating c3643219d54f_event_stock_app_1

ERROR: for stock_app  open /var/lib/docker/containers/c3643219d54f38026315c463fa983427724c0669fa9f686f111a68b7a5146611/.tmp-config.v2.json129467283: no such file or directory
```

**Output of `docker version`:**

```
:~$ docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:37:28 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:37:28 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**
```
:~$ docker info
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 59
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: docker-8:1-1208136-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.412 GB
 Data Space Total: 107.4 GB
 Data Space Available: 14.14 GB
 Metadata Space Used: 6.353 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.35-1-pve
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.937 GiB
Name: ks370359
ID: UAO7:ITPD:XCU4:YARN:UAXW:ZVPY:S2BW:ZXJF:XZLK:3BEZ:QC2M:6GCA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Dedicated OVH server

**Comment by thaJeztah** [comment]
docker-compose does not _monitor_ the containers it starts; setting `depends_on` is only used to determine the order in which the containers are started / created when doing `docker-compose up`. 

Likewise, the `depends_on` is only known by docker-compose, and not a feature that the docker engine is aware of, so when restarting the docker daemon, so it will not take startup order into account.

Note that in general, it's recommended to make your containers resilient against failures of containers/services it depends on, and not only when starting up. A service can be unavailable at any point in time (e.g. when upgrading, or due to network failures); your applications should have mechanisms to cope with that, for example, by starting a retry loop until a connection can be established.

w.r.t the devicemapper failures; there's many possible reasons for this, and the `.tmp-config2...` error may be due to an unclean shutdown.

Based on the above, I don't see a bug at hand here, so i'll close this issue, feel free to comment if I misunderstood, or overlooked something
