### ISSUE TITLE
1.13-rc4 changed `--port` back to `-p`

### ISSUE THREAD

**Issue by ChristianKniep** [docker/docker#29592]
**Description**

When updating to 1.13-r4 the cli is back to the `-p` notation to publish ports

**Steps to reproduce the issue:**
1. Download 1.13-rc3/-rc4
2. check the help for both

**Describe the results you received:**

```
tmp # ./docker-1.13-rc3/docker service create --help |grep -i publish
      --port port                        Publish a port
tmp # ./docker-1.13-rc4/docker service create --help |grep -i publish
  -p, --publish port                     Publish a port as a node port
tmp #
```

**Describe the results you expected:**

Both should use `--port` to allow host mode

**Output of `docker version`:**

```
$ ./docker-1.13-rc3/docker version
Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      linux/amd64
$ ./docker-1.13-rc4/docker version
Client:
 Version:      1.13.0-rc4
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Sat Dec 17 01:34:17 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

nothing to do with the server...

**Comment by thaJeztah** [comment]
The `-p` and `--publish` ports were only hidden in rc3/rc4. After various discussions, it was decided to unify the long ("csv") and short `"-p 8080:80"` syntaxes in the `--publish` / `-p` flags. See some background in this issue; https://github.com/docker/docker/issues/28527

We won't be adding `--port` for 1.13-GA, and `--publish` should be used going forward. Apologies for this change during the RC cycles, but we wanted to have it settled before GA.

I'll close this issue because of the above, but feel free to comment after

**Comment by ChristianKniep** [comment]
@thaJeztah Thanks for clear this up. But how do I change the publishing mode now to `host`?

**Comment by thaJeztah** [comment]
@ChristianKniep same as you did with `--port`, just change it to `--publish`, e.g.;

```
docker service create \
  --publish mode=host,target=80,published=8080,protocol=tcp \
  --name web \
  nginx:alpine
```

**Comment by ChristianKniep** [comment]
Ah, ok... Thanks a lot and keep up the great work. Nice holidays...

**Comment by thaJeztah** [comment]
You're welcome! Same to you, and thanks so much for testing the RC's (including these bumps) 👍
