### ISSUE TITLE
FEATURE REQUEST Use EnvironmentFile=-/etc/default/docker in systemd service

### ISSUE THREAD

**Issue by simonellefsen** [docker/docker#29652]
**Description**

Could we please add/modify the systemd unit file to include a default environment file so you have the option to persist startup/daemon options on upgrades. Something like:

```
EnvironmentFile=-/etc/default/docker
ExecStart=/usr/bin/dockerd -H fd:// $DOCKER_OPTS

```

**Comment by thaJeztah** [comment]
This has come up quite a few times before, e.g. #12134, #13415, #7220, and especially https://github.com/docker/docker/pull/5141#issuecomment-40940481, #3307, and #3627.

You are correct, the systemd unit file should never be modified, as doing so will in some cases actually _prevent_ it from being updated if a newer version is available.

Using an `EnvironmentFile` this is not the correct approach for this. If you want to configure your daemon through systemd; use "drop-in" files to override settings in the main systemd unit file, as is described in the [official systemd specs](https://www.freedesktop.org/wiki/Software/systemd/FrequentlyAskedQuestions/)

The systemd section of the documentation shows you how to create and use drop-in files;
https://docs.docker.com/engine/admin/systemd/#custom-docker-daemon-options, and even shows how to add this option without modifying the main unit file.

**However**, the easiest way to configure custom daemon options is by using a `daemon.json` configuration file; https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-configuration-file

The `/etc/docker/daemon.json` file doesn't exist by default, but if you create one, docker will automatically read it; it has some benefits over using systemd drop-in files (or `/etc/default/docker` on systems using "upstart");

- the `daemon.json` file is loaded irregardless of the init system that is used, so it will work both for systems running systemd, upstart, sysvinit
- the configuration even works when manually running the daemon 
- various settings can be reloaded _without restarting the daemon_ (see [configuration reloading](https://docs.docker.com/engine/reference/commandline/dockerd/#/configuration-reloading)), for example, to temporarily enable debugging mode, or (in docker 1.13 and up), to add a new local registry to the list of "insecure registries" .

I'm going to close this issue, because this won't be implemented, but I hope the above will help you further. Also feel free to continue the conversation

**Comment by simonellefsen** [comment]
Thanks, tried the drop-in version and only add the change I wanted, but then it failed with

`
systemd[1]: ERR docker.service: Service has more than one ExecStart= setting, which is only allowed for Type=oneshot services. Refusing.
`

so I guess I will go for the /etc/docker/daemon.json option then.

**Comment by thaJeztah** [comment]
```
systemd[1]: ERR docker.service: Service has more than one ExecStart= setting, which is only allowed for Type=oneshot services. Refusing.
```

Is probably because in systemd, you first have to _reset_ the ExecStart, and then add the new one; like is shown in the examples;

```
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd --bip=172.17.42.1/16
```

The first ExecStart;

```
ExecStart=
```

Is not a "typo"; it is to _reset_ the `ExecStart` before setting the next one.
