### ISSUE TITLE
[1.13.x] same container port published twice prevent service to run

### ISSUE THREAD

**Issue by vdemeester** [docker/docker#29730]
This might be a known issue but I really think it's a weird one to have. If I publish the same container port on 2 ingress port, the service does not return any error and will never be scheduled — and it's really hard to know why without looking at the daemon logs.

```bash
$ docker service create --name never --publish 5000:80 --publish 5001:80 nginx:alpine
tjbepmsn4nvwevu2xuijfg6k9
$ docker service ls
ID            NAME   MODE        REPLICAS  IMAGE
tjbepmsn4nvw  never  replicated  0/1       nginx:alpine
$ docker service ps never
ID            NAME     IMAGE         NODE  DESIRED STATE  CURRENT STATE      ERROR  PORTS
qem9gxvaldy9  never.1  nginx:alpine        Running        New 2 minutes ago 
# Extract from the logs
ERRO[1550] task allocation failure                       error="service tjbepmsn4nvwevu2xuijfg6k9 to which this task qem9gxvaldy9bpbdtzhn6ornr belongs has pending alloc
ations"
ERRO[1550] task allocation failure                       error="service tjbepmsn4nvwevu2xuijfg6k9 to which this task qem9gxvaldy9bpbdtzhn6ornr belongs has pending alloc
ations"
```

Note that this is entirely possible using `docker run` : 

```
$ docker run -d --publish 5000:80 --publish 5001:80 nginx:alpine
# […]
d8381762d8a1
```

/cc @aaronlehmann @thaJeztah @stevvooe @mavenugo @icecrime @cpuguy83

**Comment by yongtang** [comment]
The issue is confirmed and the reason is located:
https://github.com/docker/docker/blob/v1.13.0-rc4/vendor/github.com/docker/swarmkit/manager/allocator/networkallocator/portallocator.go#L76-L85

In the current implementation, `getPortConfigKey` is used for both allocated ports and configured (may or may not be allocated) ports. However, `getPortConfigKey` will not take into consideration the `PublishedPort` field, which actually could be different for different allocated ports.

The case presented, `--publish 5000:80 --publish 5001:80`, is an example of multiple allocated ports mapped to the same `getPortConfigKey`.

However, we can't simply add the field of `PublishedPort` to `getPortConfigKey`, because `getPortConfigKey` will be used in configured (may or may not be allocated) ports as well.

For configured (may or may not be allocated) ports, the field of `PublishedPort` could be `0` to indicate a dynamic allocated port. If `PublishedPort` is used for `getPortConfigKey`, then we can't compare allocated ports with configured ports.

I think one solution is to have a map of `portKey:portNum:portState` stored, instead of the current `portKey:portState`. But I will need to take a closer look to make sure it is not impacting the current behavior.

**Comment by yongtang** [comment]
Added a PR https://github.com/docker/swarmkit/pull/1835 in SwarmKit to address this issue.
