### ISSUE TITLE
Docker on windows needs a lot more work

### ISSUE THREAD

**Issue by fresheneesz** [docker/docker#29814]
Docker is basically unusable on windows. 

A. The Docker installer just tells me it can't be installed and that I have to go get docker-toolbox instead. Why doesn't it just install docker-toolbox for me?
B. I had to install cygwin to get the Docker Quickstart console working
C. I also had to modify the start.sh file to get the Docker Quickstart working (a pain in the ass on windows)
D. Running the same Dockerfile via windows produces errors when running it on a mac doesn't
E. Running certain things (like npm install) causes bizare problems like "new state of nil is invalid"

What's going on here? Is anyone actually using this on windows? The sheer number of issues don't make me want to keep playing with docker.

**Comment by thaJeztah** [comment]
> The Docker installer just tells me it can't be installed and that I have to go get docker-toolbox instead. Why doesn't it just install docker-toolbox for me?

Because those are separate products. Instead of just producing an error that it cannot be installed, the team decided to add a more helpful message, and give a possible solution (i.e., install Docker Toolbox). System requirements can be found in the documentation for Docker for Windows; https://docs.docker.com/docker-for-windows/#/what-to-know-before-you-install

> B. I had to install cygwin to get the Docker Quickstart console working
> C. I also had to modify the start.sh file to get the Docker Quickstart working (a pain in the ass on windows)

Please report exactly _what_ you ran into and _what_ you had to modify in the Docker Toolbox issue tracker; https://github.com/docker/toolbox/issues. Installation should work out of the box

> D. Running the same Dockerfile via windows produces errors when running it on a mac doesn't

Be sure to check the Docker Toolbox [troubleshooting section](https://docs.docker.com/toolbox/faqs/troubleshoot/). Without knowing what kind of issues you ran into, it's not possible to provide help on this matter.

> E. Running certain things (like npm install) causes bizare problems like "new state of nil is invalid"

I think this error will be fixed in docker 1.13 (see https://github.com/docker/docker/issues/21323).

>  Is anyone actually using this on windows? The sheer number of issues don't make me want to keep playing with docker.

Yes, it's used by many. There are limitations to Docker Toolbox, which is the reason for ["Docker for Windows"](https://docs.docker.com/docker-for-windows/) to have been developed. Docker for Windows relies on certain features that are only available in Windows 10 Pro, Enterprise and Education, so for that reason, Docker Toolbox still exists.


I'm going to close this issue, because I don't think there's anything actionable here; please open separate issues with more details, where needed.
