### ISSUE TITLE
Device Mapper 'Unknown device' in deleted devicemapper store. 

### ISSUE THREAD

**Issue by petewilcock** [docker/docker#29914]
Client/version 1.12.3 on CentOS7:

I have a docker installation that has had its devicemapper dir accidentally deleted (don't ask) so there's nothing in `/var/lib/docker/devicemapper/mnt` 

Trying to run any container I get a message long the lines of:

```
[$term] docker run hello-world
docker: Error response from daemon: devmapper: Unknown device 01741771982e86c203c8039f52a04cb40bfdebf3c7cf866f3993d0d23ff17cb5.
```

I'm not sure how to restore docker to working order by recreating the devicemapper devices for my images correctly. Can anyone advise?

**Comment by thaJeztah** [comment]
@petewilcock we try to keep the GitHub issue tracker for reporting bugs and feature requests, not for questions on _running_ docker. Could you ask this question on;

- https://forums.docker.com
- the docker community slack channel (https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)

I'll close this issue here, but feel free to comment after I closed

**Comment by petewilcock** [comment]
@thaJeztah Happy to frame this as a feature request relating to my original query. Docker doesn't realise or evaluate when the devicemapper storage is absent and doesn't appear to have a mechanism to refresh it. Unless I'm wrong (please correct me), this could be classed as either a bug or feature request depending on your perspective.
