### ISSUE TITLE
Dockerfile $Path not working properly for Windows containers

### ISSUE THREAD

**Issue by toenuff** [docker/docker#30033]
Docker version 1.13.0-rc5, build 43cc971

I'm trying to do the following in a Dockerfile:

```
ENV PATH $PATH;c:\\somepath
```

I've tried it with lowercase and with $Path which is how Windows normally uses the name.  It is not setting it properly.  It treats $PATH as an empty string and leaves me the c:\somepath part without the existing path preppended.

For testing, you can use the following dockerfile:
```
FROM microsoft\windowsservercore
ENV PATH $PATH;c:\\somepath
echo %PATH%
```

I have a workaround with this, but it's not ideal:
```
RUN powershell -command "[Environment]::SetEnvironmentVariable('Path', $env:Path + ';C:\app\winss', [EnvironmentVariableTarget]::Machine)"
```

**Comment by thaJeztah** [comment]
Yes, this is a known limitation due to the way environment variables on Windows differ from those on Linux; for Linux, docker sets a default `$PATH` environment variable during `docker build`, and allow you to work with that.

On Windows this default cannot be set, and the only way to "get" the current value of `$PATH` is to start a container and query it's value.

There's an open PR to implement this; https://github.com/docker/docker/pull/29048

We're already tracking this issue through https://github.com/docker/docker/issues/22017, so I'll close this one, but you can subscribe to the issues I linked to keep informed on updates
