### ISSUE TITLE
swarm rejoin causes overlay network to become a "local" network

### ISSUE THREAD

**Issue by vikstrous** [docker/docker#30084]
**Description**

Leaving and joining a swarm while running a container on an attachable network turns the overlay network into a local network.

**Steps to reproduce the issue:**
```
docker swarm init --listen-addr 0.0.0.0 --advertise-addr 127.0.0.1
docker network create -d overlay --attachable overlaytest
# network scope is swarm
docker run -d --net overlaytest alpine sleep 1000000
docker swarm leave --force
# network scope is still swarm
docker swarm init --listen-addr 0.0.0.0 --advertise-addr 127.0.0.1
# network scope is local
```

**Describe the results you received:**
network is a "local" overlay network

**Describe the results you expected:**
Network doesn't exist, is a real overlay network or container is killed. Basically anything else other than what's happening because this behaviour is very confusing.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.4
 Git commit:   bf6eb85
 Built:        Tue Dec 27 22:23:51 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   bf6eb85
 Built:        Tue Dec 27 22:23:51 2016
 OS/Arch:      linux/amd64
 Experimental: false
```
This has always been this way though. I've seen it on 1.12-cs

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 600
Server Version: 1.14.0-dev
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: nhk9xeap351ngic91qdyco86j
 Is Manager: true
 ClusterID: tt3gmr7nh94mhxe8uqasoo4hc
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 127.0.0.1
 Manager Addresses:
  127.0.0.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.12
Operating System: NixOS 17.03.git.1c50bdd (Gorilla)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.53 GiB
Name: thisisfine
ID: 4XB6:RAOL:2UT7:W3TT:JBSR:ILHC:LREA:HUVU:5U7V:TI7E:WUT2:WQTS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 64
 Goroutines: 182
 System Time: 2017-01-11T17:42:25.480179518-08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Experimental: false
Insecure Registries:
 172.17.0.1
 172.17.0.1:3001
 172.17.0.1:443
 172.17.0.1:444
 172.17.0.1:445
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by yongtang** [comment]
I can reproduce the behavior for the most recent master.

The issue is that, when `docker swarm leave --force` is called, the created network `overlaytest` still exists for the daemon. Now when `docker network inspect` is called, the following:
https://github.com/docker/docker/blob/58738cdee327f5de481dcf7d3d377374cbb5f13a/api/server/router/network/network_routes.go#L180-L186
will return `Scope = swarm` even the network `overlaytest` does not belong to newly created swarm cluster (because `info.Dynamic()` is true so scope is `swarm` nevertheless).

Then after `docker swarm init` is called again, the network `overlaytest` does not belong to newly created swarm cluster.

This time when  `docker network inspect` is called, the following:
https://github.com/docker/docker/blob/58738cdee327f5de481dcf7d3d377374cbb5f13a/api/server/router/network/network_routes.go#L180-L186
will return `Scope = local` because `n.cluster.GetNetwork(nw.Name())` returns nothing.

I could see there is inconsistency here and we need to address it. However, I am not sure what would be the expected behavior when `docker swarm leave --force` is called. Should we delete the `overlaytest`, or "downgrade" `overlaytest` to local (currently `overlaytest`'s scope still `swarm` after swarm leave)?

/cc @mavenugo @aboch @aaronlehmann

**Comment by aboch** [comment]
Thanks @yongtang I was actually looking at the issue just now, and was wondering what the behavior should be.

At the moment, I think that on swarm leave docker needs to remove any `managed` network, also the one having non-managed containers attached.
So, I was thinking it should detect that, detach those non-managed containers and then remove the network.

**Comment by mavenugo** [comment]
@aboch I think that is a reasonable thing to do given that the node is forcefully yanked out of the cluster. The workaround is actually simple and the user who is running unmanaged container must make sure the containers are removed or disconnected from this network before leaving the swarm.

**Comment by aboch** [comment]
Thanks @madhu. 
@yongtang Let me know if you are already working on this, otherwise I can take it. Thanks.

**Comment by yongtang** [comment]
Thanks @aboch I am not very familiar with this part of the swarm/network so it may take me some time before I could get the issue fixed. It would be great if you can take a look for the fix.
