### ISSUE TITLE
Docker service on Windows left in memory after the crash

### ISSUE THREAD

**Issue by artisticcheese** [docker/docker#30155]
**Description**
Docker service on Windows for some reason fails to start when images are moved off to E drive via daemon.json containing `{  "graph": "e:\\images"  }`. Once failed to start leaves dockerd.exe still running in memory preventing any further attempts to start or fix the issue due to file locks on metadata.db.lock
**Steps to reproduce the issue:**
1. Have daemon.json contain `{  "graph": "e:\\images"  }`
2. Try to launch service via start-service docker
3.

**Describe the results you received:**
```
PS C:\Users\Administrator> start-service docker
start-service : Failed to start service 'docker (Docker)'.
At line:1 char:1
+ start-service docker
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand
```

**Describe the results you expected:**
Dockerd.exe left in memory 
```
PS C:\Users\Administrator> get-process dockerd

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    361      18    15852      29040       0.31   4480   0 dockerd
```
**Additional information you deem important (e.g. issue happens only occasionally):**
After deleting 2 lock files and killed remnant process service starts untill next reboot where entire thing happens again
**Output of `docker version`:**

```
PS C:\Users\Administrator> docker version
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
PS C:\Users\Administrator> docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.693.amd64fre.rs1_release.161220-1747)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 2.494 GiB
Name: CONTAINERHOST3
ID: I7XH:JPRK:MWNL:HQID:QAEL:DLRD:TMF5:7BOF:RR53:Z7A4:W5U7:OKEB
Docker Root Dir: E:\images
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows 2016 fully patched, Virtual

**Comment by artisticcheese** [comment]
Issue was with ServiceFabric service stopping docker service and spawning it's own process instead.

**Comment by sg1970** [comment]
@artisticcheese I have a similar issue with docker v1.13.1-cs . The docker service exits immediately after I deploy a SF Application that is deploying a native container.  The thing is it works beautifully on a different Server 2016 VM. Iam trying to get this working : https://loekd.blogspot.com/2017/01/running-windows-containers-on-azure.html

Did you find out why the docker service was being stopped by SF ?

Thanks!

**Comment by artisticcheese** [comment]
SF stops it and respawns it's own process with -H:1375 flag which makes daemon listen on TCP instead of netpipes port so I would assume it can be easily accessed by nodes on other networks or something. So just stop docker daemon at let SF manage it.

**Comment by sg1970** [comment]
@artisticcheese thanks for your response ..... but SF is not behaving in the same manner on a personal VM which  is not behind a corporate proxy unlike the one where Docker service stops.  I would think that my personal VM is working correctly behavior as Iam able to see that there are 3 containers running on my target VM by logging in thru rdp and querying thru docker ps and I can also simultaneously access the containers WebServices thru the SF endpoint port that is dynamically assigned.

Also in my case (on the corporate VM behind proxy ) SF is not successful in starting the container so I end up with no container mgmt tool once I hit the publish button as Docker is stopped and SF was un-successful in its attempt to run the container.  It appears in your case SF was successful in starting the containernafter it stopped docker. Right ?

 Any thoughts ?

**Comment by artisticcheese** [comment]
You still can work with docker on SF container launched docker daemon. You just need to add following environment value

```
PS C:\Windows\system32> dir Env:\docker_host

Name                           Value
----                           -----
docker_host                    tcp://localhost:2375
```

**Comment by sg1970** [comment]
@artisticcheese  I have that  env var set already. The error that you posted in the OP is what i get (even with the env variable set to tcp://localhost:2375 ).

**Comment by artisticcheese** [comment]
Set docker server on SF host to disabled.

**Comment by sg1970** [comment]
@artisticcheese  

Same error (SF Failed to deploy) ... this is the error I get on the SF Explorer. 

---------	
Error event: SourceId='System.FM', Property='State'.
Partition is below target replica or instance count.
fabric:/MyContainerService/MyContainerService -1 1 aa9eb532-c81f-432c-b62d-282b387913ff
  IB vm2 Up 131320812583374071
  IB vm1 Up 131320812583374072
  IB vm0 Up 131320812583374073
  (Showing 3 out of 3 replicas. Total available replicas: 0.)

-------

And If I try to run docker ps from command prompt i get : 

C:\Program Files\Docker>docker ps
error during connect: Get http://localhost:2375/v1.26/containers/json: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.

C:\Program Files\Docker>set | find /i "Docker"
DOCKER_HOST=tcp://localhost:2375 

Thanks for trying to help me with this.

**Comment by artisticcheese** [comment]
Not sure, this seems to be issue with SF not docker per se. Try to ask at SF forums.

**Comment by PatrickLang** [comment]
SF issues are tracked here: https://github.com/Azure/service-fabric-issues

**Comment by mani-ramaswamy** [comment]
Please open an issue in the SF forum above and link to this... can you also give us the output  of  docker -H localhost:2375 ps -a

**Comment by sg1970** [comment]
@PatrickLang @mani-ramaswamy thx I will ... sorry for the delay ... in the meanwhile here is the output of the docker -H localhost:2375 ps -a . ( BTW the Docker-engine service is disabled )

-------With localhost -------

C:\Program Files\Docker>docker -H localhost:2375 ps -a
error during connect: Get http://localhost:2375/v1.26/containers/json?all=1: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.

----- With 127.0.0.1 instead of localhost -------

C:\Program Files\Docker>docker -H 127.0.0.1:2375 ps -a
error during connect: Get http://127.0.0.1:2375/v1.26/containers/json?all=1: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.
