### ISSUE TITLE
How to get the server IP Address from a docker container which is running a Java application.

### ISSUE THREAD

**Issue by YashdeepSharma** [docker/docker#30372]
**Description**
I am running a java application inside a docker container and application needs to be deployed on a server. Application needs to access the IP_ADDRESS of the server from Java Code, since, it is running inside a container, it get the IP_ADDRESS as docker host IP.  

**Steps to reproduce the issue:**
1. I Used InetAddress to access the hostIP.
2. I got 172.x.x.x
3. Instead of 10.100.x.x

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by dnephin** [comment]
You could use `--net=host` to share the host network stack, which should give you the host IP address.

Or you could pass in the host IP address using an environment variable: `docker run -e HOST_IP_ADDR=...`

**Comment by thaJeztah** [comment]
Getting the IP address at which your service is accessible is really dependent on your situation / setup. For example;

- When running in the cloud, it's possible that the IP address of the machine is only accessible through an external load balancer.
- When running docker in a Virtual Machine, the situation is similar; the IP address of the Virtual Machine may not be accessible from your network.

The docker daemon does not have that information, so cannot provide it to the container. For this reason, `docker swarm init` also has an `--advertise-addr` option, which lets the user specify the IP-address at which the daemon can be reached.

I'm going to close this issue, because I think the question is answered.  Please keep in mind that the GitHub issue tracker is not intended as a general support forum, but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

Feel free to continue the conversation after I closed this issue 👍
