### ISSUE TITLE
1.12.3: Docker daemon hangs after some time

### ISSUE THREAD

**Issue by louis-paul** [docker/docker#30437]
We use Docker as a part of our Kubernetes setup. We see on a regular basis Docker daemons hanging after they have been active in the cluster for some time. There is no way to start, kill or list containers, but `docker version` works. Restarting Docker fixes the issue temporarily, and we have implemented a daemon monitoring script that does just that (in some rare cases the daemon will be unrecoverable and will keep hanging even after a restart).

I have included a stacktrace from an affected daemon at the end of this issue. If needed I could spin up a few machines with our Docker monitoring disabled to capture more info.

**Steps to reproduce the issue:**
1. Add a node to our Kubernetes cluster
2. Wait an indeterminate amount of time

**Additional information you deem important (e.g. issue happens only occasionally):**

From my limited understanding of the stacktrace, this looks like #27566 (see goroutines 15 and 25).

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   34a2ead
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   34a2ead
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 63
 Running: 32
 Paused: 0
 Stopped: 31
Images: 38
Server Version: 1.12.3
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 4.7.3-coreos-r2
Operating System: Container Linux by CoreOS 1235.6.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.679 GiB
Name: ip-10-0-0-106.ec2.internal
ID: I35V:TMFI:6TXT:RJNC:GPQA:MDXO:U772:FLPK:UGBT:JYUY:QLQF:U2C7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

(this is from a node that has not yet encountered this issue)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker is managed by Kubernetes 1.4.6 on CoreOS Stable (1235.6.0) AWS VMs.

**Stacktrace**:

This is from an affected daemon: [docker-stack1.txt](https://github.com/docker/docker/files/729206/docker-stack1.txt)

**Comment by cpuguy83** [comment]
Thanks for reporting.
This is already fixed.
There are two issues:

1.  The container lock is needlessly being taken here: https://github.com/docker/docker/blob/v1.12.3/daemon/monitor.go#L62
2. A race waiting for exec stdio streams to close caues this to hang https://github.com/docker/docker/blob/v1.12.3/daemon/monitor.go#L68

Because of "2", "1" is stuck in a locked state, which prevents most of the management commands from running.

Please upgrade to 1.12.6 which has a number of bug fixes, including fixes for these issues, as well as for CVE-2016-9962.

Closing since this is already resolved.
Again thank you for reporting 🙇 

Feel free to comment if you have any questions/concerns.

**Comment by louis-paul** [comment]
Thank you, I'll wait until 1.12.6 reaches the CoreOS beta channel and report back if there's something wrong.
