### ISSUE TITLE
docker stack deploy not compatible with Publish mode=host

### ISSUE THREAD

**Issue by WTFKr0** [docker/docker#30447]
**Description**

docker stack deploy from compose file not compatible with Publish mode=host (bypass ingress network)

**Steps to reproduce the issue:**
cat docker-compose.yml
```
version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "mode=host,target=80,published=9005"
```
docker stack deploy --compose-file docker-compose.yml test

**Describe the results you received:**
Invalid containerPort: mode=host,target=80,published=9005

**Describe the results you expected:**
I would like this create service like : 
```
docker service create --name test_nginx --publish "mode=host,target=80,published=9005" nginx
```

**Output of `docker version`:**
```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**
```
Containers: 43
 Running: 27
 Paused: 0
 Stopped: 16
Images: 258
Server Version: 1.13.0
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: ******
 Is Manager: true
 ClusterID: *****
 Managers: ***
 Nodes: ****
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: ****
 Manager Addresses:
  *****:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.2.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: ***
Total Memory: *** GiB
Name: *****
ID: *****
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 storage-driver=overlay2
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Thanx for reading

**Comment by thaJeztah** [comment]
ping @dnephin I _think_ this is a duplicate, but I couldn't find it quickly :smile:

**Comment by dnephin** [comment]
I think you pinged me on this issue before, ya, but it was in a comment in a long thread. Let's keep this issue, it has a better description of the feature request.

**Comment by jazoom** [comment]
Can confirm, this is important.

**Comment by jazoom** [comment]
I don't know if you want a whole separate issue for this, but it seems there's also no equivalent for --with-registry-auth.

**Comment by jazoom** [comment]
Also can't see support for this: --memory-swappiness=0

**Comment by thaJeztah** [comment]
@jazoom the `--with-registry-auth` is a flag you set during `docker stack deploy`. It's not a "property" of a service, but a flag that specifies that the auth-information passed on to the service during deploy. This is not something that should be set in the docker-compose file, but a deliberate action of the person deploying the stack.

> Also can't see support for this: `--memory-swappiness=0`

`--memory-swappiness` is currently not supported for services (possibly it can be set through the API, so that `--compose-file` can set it).

Could you open a separate issue for supporting it on services in general? Adding such options _may_ require additional discussion, as the _intent_ is to have "portable" options for constraints, where possible (which is the reason for `--limit-cpu` and `--limit-memory` to be added for services instead of all low-level options).

Once you have opened that issue, I'll link it to https://github.com/docker/docker/issues/25303, which is tracking flags/options that are present on `docker run`, but not on `docker service create`

> **note** I just noticed that https://github.com/docker/compose/pull/3542 added support for `mem_swappiness` in docker-compose, but for some reason it seems to be not documented in the [docker-compose file reference](https://docs.docker.com/compose/compose-file/#/cpushares-cpuquota-cpuset-domainname-hostname-ipc-macaddress-memlimit-memswaplimit-oomscoreadj-privileged-readonly-restart-shmsize-stdinopen-tty-user-workingdir), I'll have a look what happened there

**Comment by jazoom** [comment]
The reference says it was deprecated in version 3. I was wondering why it was called --memory-swappiness=0 in some places and mem_swappiness in others. I thought the latter was just for compose but I guess services don't have it at all now.

Thanks for clearing up --with-registry-auth. I guess it wasn't clear to me where it belonged since that flag was with the others in my service creation.

It's getting pretty confusing with 3 different ways of doing everything (run, service create, compose).

**Comment by jazoom** [comment]
By the way, it'd be great to get that swap setting back so we can disable it for things like Elasticsearch without disabling it for every other image on the host.

**Comment by yongtang** [comment]
I think the issue could be addressed by using `opts.PortOpt.Set()` directly from `convertEndpointSpec()`. Created a PR #30476 for it.

**Comment by dnephin** [comment]
Related to #29193. By supporting the long form of the syntax we can support `mode=host`
