### ISSUE TITLE
Proposal: Dockerfile add BIND_CONTEXT

### ISSUE THREAD

**Issue by amluto** [docker/docker#3056]
Currently I have mostly-useless commands in my Dockerfile like
    ADD stuff /docker_setup
    RUN /docker_setup/install.sh && rm -rf /docker_setup

This is ugly.  Can we have:
    BIND_CONTEXT /docker_context
    RUN /docker_context/stuff/install.sh

I'm not picky about the syntax.  I want to have docker build do what docker run -v does, but during the build process.

**Comment by dagelf** [comment]
This proposal as stated here has two problems. 

1) It creates unnecessary extra work. If I already have the stuff I need for my build in, say, /var/apt/cache - and I want it to be available during my (OFFLINE!) build, at /var/apt/cache inside the container, then this requires a bunch of extra and generally unnecessary steps, involving symlinking or bind-mounting inside my host and inside my container. 

2) The word "CONTEXT" is not unambiguous as to the use case. What would people needing this search for, and which one of the many contexts does the word context refer to? Does docker need yet another unintuitive verb? ... They would search  for "BIND" or "MOUNT" or "LOCAL" or "TEMP" or "OFFLINE" or... just maybe... "BUILDCONTEXTBINDMOUNT"  :-p

Let's recap the use case: You're offline, or in a secure environment, or you want secrets in your build that need not remain in your image. You want a command that will only be run on a certain "home" host, and will not cause an error on another, but you don't want people to hack together various solutions to something that can easily be solved.

I've read all the text in all the linked tickets and the only potential criticism comes from @tianon who is concerned with the cache (https://github.com/docker/docker/pull/5369) - I've not looked into how and what docker caches, but the logical counter to that is that nothing that is bind-mounted into the build-context, will end up in the final image, or necessarily changing the final image, and as such should not affect the cache, unless something in there results in different files being generated- or copied to/in the build - which it should not in most instances.  

If I have a local copy of all the .deb files I'll need, I can just BINDMOUNT /var/cache/apt/distfiles:/var/cache/apt/distfiles and my stupid docker won't have to download 500MB of data from the other side of the planet everytime I try to generate an image locally. 

If I have a directory with a generic key, and a config file for a database to pull into my image, but I also have a secure/development key and a local database thats much faster, then I'd like to be able for local build to use my local stuff, by just overloading the directory with the configs. If it's not there, the image will still build, but it will use the generic/globally available resources. 

Yes there's a security issue: A docker pull and run can read your local filesystem, which we don't want. Especially since a lot of people run docker as root. Simple: ignore all these commands, unless a special command line switch is given. And display a warning.

But thats the point, you want these commands ignored, unless you're in a home environment. The main purpose of these commands is to work on rapidly creating and fine tuning images, in an offline environment if you want.

**Comment by dagelf** [comment]
I challenge any of the docker developers/maintainers to try and work with docker in an offline or poor-connectity environment, and see what irks you and what solutions you come up to deal with it...

**Comment by a-ba** [comment]
> I've not looked into how and what docker caches, but the logical counter to that is that nothing that is bind-mounted into the build-context, will end up in the final image, or necessarily changing the final image, and as such should not affect the cache

I think you may be confused about intent of BINDCONTEXT (caching data was no the goal)


The main purpose is to bind files so that they can be processed in the subsequent RUN commands and **the result ends up in the image**.

Typically you mount your sources with BINDCONTEXT and issue a RUN to build the binaries. The binaries depend on the content of sources so you want them to be properly fingerprinted. Plus everything happens exclusively on server-side, so you are guaranteed to have no user-induced side effects.

The criticism from @tianon was not aimed at this proposal but at a comment from someone who suggested to bind the context implicitly at every build. 

Caching data for subsequent builds is a very valuable objective, but I would largely favour methods that are free of any uncontrolled side effect (eg. #4962 #9553) 


Regarding the word 'context' I think the meaning is pretty clear in docker's builder:
```sh
	$ curl -s http://docs.docker.com/reference/builder/| grep -oi context |wc -l
	27
```
(anyway I would not mind having a better name)

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.

**Comment by ibukanov** [comment]
To implement something like this does not require any extension to Dockerfile syntax. The build content could be made available over HTTP at some predefined address where it could be picked up by a curl or similar during RUN command.

**Comment by dagelf** [comment]
Goes without saying that there are numerous "hacky" workarounds, but all of
them require you to either modify the guest, poison DNS, or run a special
Web server.

Which is why I don't get why the docker maintainers don't get it - doing
things like this is already possible, so why not just streamline /
standardize it and save everyone a lot of pain?

What if you can't or don't want to modify the guest for aesthetic reasons.
Ie. You want to use the unmodified distribution of an OS, but you want it
to be able to use your local offline data cache or ssh keys if they are
available, to speed up your build?

I've since gotten gigabit Internet, so this hasn't been a need, else I
would've fixed it myself... but I still pity anyone who tries to use docker
offline or in the 3rd world where data costs $200/Gb. Very egalitarian.

To implement something like this does not require any extension to
Dockerfile syntax. The build content could be made available over HTTP at
some predefined address where it could be picked up by a curl or similar
during RUN command.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/docker/docker/issues/3056#issuecomment-213832893>

**Comment by amluto** [comment]
To make this 100% clear: this feature request was *never* about any sort of caching.  It was to improve the situation when I have contents (code, scripts, configuration, big tarballs, whatever) in the Dockerfile context directory and I want scripts in the Dockerfile to be able to access it without manually ADDing every file.

**Comment by duglin** [comment]
I think it would be easier to just make the build context available via some well-known mount point in the build containers - like /_bc   or /_docker_bc  then you could run/copy/whatever files directly from there w/o them being in the image.  I even had some prototype code for this as part of a different piece of work.  What I like about this is that it doesn't require a change to the Dockerfile and you can just any normal shell commands to access it - no need for http stuff.

**Comment by dagelf** [comment]
Certainly... or you could kill two birds with one stone and achieve so much
more with the same amount of effort.

Once again, for me first prize is to be able to use unmodified guests. Say
you want the startup of some service in your guest to run differently for
whatever reason - simple just overload the relevant file or path.

If you make it a fixed path, you're enforcing something on a lot of people.
If it's configurable, docker is friendlier as it can adapt to things that
are already in place.

**Comment by ibukanov** [comment]
My use case is to run a compiler or preprocessor during Docker build. When one use COPY or ADD before the RUN the source ends up in the image bringing unnecessary bloat. That cannot be removed as COPY and RUN belong to different image layers so doing rm during the build does not remove the files from the image.

One possible workaround for that is to expose the source over HTTP so one can use curl or similar to get it during RUN before executing the compiler. Another one is to use a staged build when one first build image with the compiler, then run it to compile the sources and then build the final image from the results. These are non-standard and require tools beyond the docker.

**Comment by a-ba** [comment]
To give some feedback about this issue (as the author of #5369), i have used this feature since v0.11 and i still rely a lot on it to reduce the size of my images. But i stopped maintaining #5369 after v1.7 and developed a simpler patch (named tmp-volume).

This [new patch](https://github.com/a-ba/docker/tree/tmp-volume) mounts /tmp from a temporary directory during the whole build. Everything that lands in /tmp is dropped when the build is complete and it is actually never committed into any layer. Compared to BINDCONTEXT, it is much less intrusive in the code, and it can be used to include only a part of the context. For those interested, it is up do date with v1.10.3. 

 

@duglin: note that setting up a permanent mount point like /_bc or /_docker_bc would do more harm than good in practice because it prevents caching the intermediate stages of the build (changing a single bit anywhere in the context would invalidate the whole cache). The whole point about BINDCONTEXT is that it works like COPY (including fingerprinting of the content) except that the content is stored outside the image.

For builds including a compilation (@ibukanov case), though i used  BINDCONTEXT a lot in the beginning, I now prefer building a separate image for the compiler for two reasons : (1.) I don't want the compiler in the final image (2.) some tools (e.g maven) implement their own cache to speed up successive builds but their cache is useless when run inside a dockerfile. To facilitate these multi-stage builds I developed a separate command [docker-rundev](https://github.com/a-ba/docker-utils#docker-rundev).

**Comment by thaJeztah** [comment]
This feature is now available in the experimental Dockerfile syntax; see the [Dockerfile frontend experimental syntaxes](https://github.com/moby/buildkit/blob/b3e4cdf0d8ef6367c2dd9497548cca75e453dbf8/frontend/dockerfile/docs/experimental.md)

Create a "build context" to work with; this would normally be your source files :smile:

```bash
mkdir my-context && cd my-context
echo this is a file in my context > file1.txt
mkdir subdir
echo this is a file in subdir > subdir/file2.txt
```

Make sure buildkit is enabled:

```bash
export DOCKER_BUILDKIT=1
```

You can use files from the bind-mounted context with the `--mount` option. These files are accessible during build, but are not copied to the image, so it's a great way to (e.g.) build source-code without the source code _itself_ ending up in the image.

This example bind-mounts the whole build-context. Note that `src=/` is relative to the root of your build-context, not an absolute path on your host. In this example, we're copying a file from the bind-mounted context to a file named `foo.txt` at the root of the container. This is obviously not a very useful thing to do (`COPY file1.txt /foo.txt` would've done the same), but it's just an example; this step could've been a `make && make install`.

```bash
docker build -t example -f- . <<EOF
# syntax=docker/dockerfile:1.0-experimental
FROM busybox
RUN --mount=src=/,target=/foo cp /foo/file1.txt /foo.txt
EOF
```

Running the image you can see that the "build artefacts" (`foo.txt`) is in the image:

```bash
docker run --rm example cat /foo.txt
this is a file in my context
```

But the source files are not;

```bash
docker run --rm example cat /foo/file1.txt
cat: can't open '/foo/file1.txt': No such file or directory
```

Note that the build-context is still sent to the daemon, so when you're bind-context, files are mounted from a _copy_ of your local files that resides on the daemon's host.

Instead of bind-mounting your whole build-context, you can also mount just a subdirectory. BuildKit is smart enough to only send what's needed, so bind-mounting just what you need can improve build speed;

```bash
docker build -t example2 -f- . <<EOF
# syntax=docker/dockerfile:1.0-experimental
FROM busybox
RUN --mount=src=/subdir,target=/foo cp /foo/file2.txt /foo2.txt
EOF
```

And you can verify it worked;

```bash
docker run --rm example2 cat /foo2.txt
this is a file in subdir
```

By default, binds are read-only, but you can mount writable. _However_, changes are not persisted (this is by design), so the second `RUN` in this Dockerfile will fail

```bash
docker build -t example3 -f- . <<EOF
# syntax=docker/dockerfile:1.0-experimental
FROM busybox

RUN --mount=src=/,target=/writable,rw echo new file > /writable/new-file.txt
RUN --mount=src=/,target=/writable,rw cat /writable/new-file.txt
EOF
```

```bash
...
=> [2/3] RUN --mount=src=/,target=/writable,rw echo new file > /writable/new-file.txt                                                     2.6s
 => ERROR [3/3] RUN --mount=src=/,target=/writable,rw cat /writable/new-file.txt                                                           2.7s
------
 > [3/3] RUN --mount=src=/,target=/writable,rw cat /writable/new-file.txt:
#11 2.088 cat: can't open '/writable/new-file.txt': No such file or directory
------
rpc error: code = Unknown desc = executor failed running [/bin/sh -c cat /writable/new-file.txt]: exit code: 1
```
