### ISSUE TITLE
Since Centos upgrade to docker 1.12.5 systemd[1]: Scope libcontainer-XXXXX-systemd-test-default-dependencies.scope has no PIDs. Refusing.

### ISSUE THREAD

**Issue by LordFPL** [docker/docker#30628]
**Description**
Since a Centos 7 upgrade, docker have been upgraded from docker-1.10.3-59.el7.centos.x86_64 to docker-1.12.5-14.el7.centos.x86_64.
All is "working"... except many logs in journalctl : 
```
févr. 01 11:31:18 xxxx.xxx.xx systemd[1]: Scope libcontainer-27883-systemd-test-default-dependencies.scope has no PIDs. Refusing.
févr. 01 11:31:18 xxxx.xxx.xx systemd[1]: Scope libcontainer-27883-systemd-test-default-dependencies.scope has no PIDs. Refusing.
```

**Steps to reproduce the issue:**
1. Install docker on centos 7 with default systemd service, launch it
2. Run a container (container=$(docker run -d centos:7 sleep 120))
3. Execute commands inside it (docker exec -it $container ls)
4. Look at logs
```
févr. 01 11:14:43 xxxx.xxx.xx systemd[1]: Scope libcontainer-26411-systemd-test-default-dependencies.scope has no PIDs. Refusing.
févr. 01 11:14:43 xxxx.xxx.xx systemd[1]: Scope libcontainer-26411-systemd-test-default-dependencies.scope has no PIDs. Refusing.
févr. 01 11:14:43 xxxx.xxx.xx systemd[1]: Scope libcontainer-26417-systemd-test-default-dependencies.scope has no PIDs. Refusing.
févr. 01 11:14:43 xxxx.xxx.xx systemd[1]: Scope libcontainer-26417-systemd-test-default-dependencies.scope has no PIDs. Refusing.
févr. 01 11:14:44 xxxx.xxx.xx systemd[1]: Scope libcontainer-26423-systemd-test-default-dependencies.scope has no PIDs. Refusing.
févr. 01 11:14:44 xxxx.xxx.xx systemd[1]: Scope libcontainer-26423-systemd-test-default-dependencies.scope has no PIDs. Refusing.
févr. 01 11:14:44 xxxx.xxx.xx systemd[1]: Scope libcontainer-26429-systemd-test-default-dependencies.scope has no PIDs. Refusing.
févr. 01 11:14:44 xxxx.xxx.xx systemd[1]: Scope libcontainer-26429-systemd-test-default-dependencies.scope has no PIDs. Refusing.
févr. 01 11:14:45 xxxx.xxx.xx systemd[1]: Scope libcontainer-26436-systemd-test-default-dependencies.scope has no PIDs. Refusing.
```

**Output of `docker version`:**

```
# docker version
Client:
 Version:         1.12.5
 API version:     1.24
 Package version: docker-common-1.12.5-14.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      047e51b/1.12.5
 Built:           Mon Jan 23 15:35:13 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.5
 API version:     1.24
 Package version: docker-common-1.12.5-14.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      047e51b/1.12.5
 Built:           Mon Jan 23 15:35:13 2017
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 151
Server Version: 1.12.5
Storage Driver: btrfs
 Build Version: Btrfs v4.4.1
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 32
Total Memory: 251.8 GiB
Name: xxxxxxx
ID: M5TL:ZZKU:3NIG:YS22:RVFM:7J3G:I4PM:C2PL:362N:F5BB:YOTD:L542
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://xxxxxx
Insecure Registries:
 127.0.0.0/8
Registries: xxxxxxx (secure), docker.io (secure)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Only solution found : 
```
systemctl stop docker
sed '/native.cgroupdriver=systemd/d' /usr/lib/systemd/system/docker.service > /etc/systemd/system/docker.service
systemctl daemon-reload
systemctl start docker
```

**Comment by thaJeztah** [comment]
Looks like you're running the Red Hat fork of Docker, which contain a lot of modifications; can you try installling the official version of docker and see if you're still having this issue?
https://docs.docker.com/engine/installation/linux/centos/

**Comment by LordFPL** [comment]
Hello, sorry for long answer.
I have installed official version (1.13.1), and it's work... except if i add "--exec-opt native.cgroupdriver=systemd" : 
```
févr. 23 13:10:11 xxxx  systemd[1]: Scope libcontainer-4484-systemd-test-default-dependencies.scope has no PIDs. Refusing.
févr. 23 13:10:11 xxxx  systemd[1]: Scope libcontainer-4484-systemd-test-default-dependencies.scope has no PIDs. Refusing.
févr. 23 13:10:11 xxxx  systemd[1]: Created slice libcontainer_4484_systemd_test_default.slice.
févr. 23 13:10:11 xxxx  systemd[1]: Starting libcontainer_4484_systemd_test_default.slice.
févr. 23 13:10:11 xxxx  systemd[1]: Removed slice libcontainer_4484_systemd_test_default.slice.
févr. 23 13:10:11 xxxx  systemd[1]: Stopping libcontainer_4484_systemd_test_default.slice.
```

Problem is with "Cgroup Driver: systemd"... i try with 1.12.5 : same but with only 2 lines as from my initial message.
As officiel docker package don't add "--exec-opt native.cgroupdriver=systemd", i consider my workaround ok... but i think there is some update to do with this driver.

**Comment by thaJeztah** [comment]
Thanks for that info. I know we switched to `cgroupfs` as the default driver, because there were various issues with the systemd cgroups (incomplete, breaking changes with systemd updates, incompatibilities between systemd versions). It's improving, but for now we default to `cgroupfs` as it's much more stable.

I don't know about _these_ particular issues though; perhaps @mlaventure knows more.

**Comment by panuhorsmalahti** [comment]
I'm also seeing this with RHEL's 1.12.5 docker.

**Comment by tompaulsen2002** [comment]
Also with Docker v1.12.6 on Centos 7

**Comment by pawankkamboj** [comment]
Also with 1.12.6 on centos with default systemd driver

**Comment by mlaventure** [comment]
This is not a bug, it's `runC` testing if starting transient units is supported by `systemd`

**Comment by sixijun** [comment]
while large number of units are created/removed for a period of time like 5 months, sd_bus->cookie will overflow and dbus org.freedesktop.systemd1 will be no response at all because systemd cannot seal dbus1 type of messages.

this issue impact Kubernetes cluster nodes for a long while and it's not easy to reproduce. when issue occurs, the node cannot create new container. wen can only reboot the system, or reexec systemd.

we should figure out some why to re-code the UseSystemd function or it's caller, so far the systemd will get like hundreds of message from runc even if we run a docker exec command. the test will overflow sd_bus->cookie sooner or later.

int bus_message_seal(sd_bus_message *m, uint64_t cookie, usec_t timeout) {
struct bus_body_part *part;
...
if (cookie > 0xffffffffULL &&
!BUS_MESSAGE_IS_GVARIANT(m))
return -ENOTSUP;

bus_message_seal (m=0x55cbc5a75790, cookie=4294967731, timeout=25000000) at src/libsystemd/sd-bus/bus-message.c:2924
2924 int bus_message_seal(sd_bus_message *m, uint64_t cookie, usec_t timeout) {

(gdb) info registers
rax 0x55cbc5a75790 94333682800528
rbx 0x55cbc5b5eba0 94333683755936
rcx 0x1000001b2 4294967730
rdx 0x17d7840 25000000
**_rsi 0x1000001b3 4294967731 cookie rdi 0x55cbc5a75790 94333682800528 sd_bus_**
rbp 0x0 0x0
rsp 0x7ffd80ae0268 0x7ffd80ae0268
r8 0x55cbc5a6ef50 94333682773840
r9 0x55cbc5abed00 94333683100928
r10 0x4 4
r11 0x55cbc5a75938 94333682800952
r12 0x0 0
r13 0x7ffd80ae0320 140726762341152
r14 0x7ffd80ae0300 140726762341120
r15 0x55cbc3ffcfc8 94333655044040
rip 0x55cbc3f54d40 0x55cbc3f54d40 <bus_message_seal>
eflags 0x202 [ IF ]
cs 0x33 51
ss 0x2b 43
ds 0x0 0
es 0x0 0
fs 0x0 0
gs 0x0 0
