### ISSUE TITLE
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

### ISSUE THREAD

**Issue by Suncatcher** [docker/docker#30631]
**Description**

I cannot use Docker on my brand-new AWS instance, where it was installed out-of-the-box.

**Steps to reproduce the issue:**
1. Trying to start docker via `sudo service docker start`. This steps returns OK.
2. running `docker info` returns **Cannot connect to the Docker daemon. Is the docker daemon running on this host?**
3. running any other Docker command returns the same

**Describe the results you received:**
`Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

**Describe the results you expected:**
Successful execution of commands

**Additional information you deem important (e.g. issue happens only occasionally):**
Full log from [/var/log/docker](http://pastebin.com/BgEkrD4Q) 

**Output of `docker version`:**
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Fri Jan  6 22:16:21 2017
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host

**Output of `docker info`:**

`Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS t2.micro AMI Linux 2016.09e

**Comment by gianarb** [comment]
Hello @Suncatcher thanks for your report. The useful part seems
```
time="2017-02-01T10:25:47.369865738Z" level=fatal msg="Error starting daemon: error initializing graphdriver: devicemapper: Non existing device docker-docker--pool"
```
And it can be a duplicated of this one https://github.com/docker/docker/issues/21304

**Comment by cpuguy83** [comment]
It looks like there is some configuration sitting on this host which is incorrect.
Specifically it seems to be telling docker to use a thin pool that does not exist, and based on the name I'd say it's pulling from a var that is empty(?).

Closing since this doesn't look like a Docker issue, but feel free to discuss here (or community slack may be better!).
Thanks!

**Comment by Suncatcher** [comment]
> And it can be a duplicated of this one #21304

This solution didn't help. Running with `-tpool` gave similar output:
```
docker group found. gid: 497
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock)
INFO[0000] libcontainerd: new containerd process, pid: 3554
DEBU[0000] libcontainerd: containerd connection state change: TRANSIENT_FAILURE
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
DEBU[0000] containerd: read past events                  count=0
DEBU[0000] containerd: supervisor running                cpus=1 memory=995 runtime=docker-runc runtimeArgs=[] stateDir=/var/run/docker/libcontainerd/containerd
DEBU[0000] containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock
DEBU[0001] Using default logging driver json-file
DEBU[0001] Golang's threads limit set to 7020
DEBU[0001] [graphdriver] trying provided driver "devicemapper"
DEBU[0001] devicemapper: driver version is 4.34.0
DEBU[0001] devmapper: Deferred removal support enabled.
DEBU[0001] devmapper: Generated prefix: docker-202:1-263196
DEBU[0001] devmapper: Checking for existence of the pool docker-202:1-263196-pool
DEBU[0001] devmapper: Pool doesn't exist. Creating it.
DEBU[0001] Cleaning up old mountid : start.
FATA[0001] Error starting daemon: error initializing graphdriver: open /dev/mapper/docker-pool0-tpool: no such file or directory
```

> this doesn't look like a Docker issue
And what is it look like? I am total newbie in Docker so any suggestions are appreciated.
Thanks.

**Comment by cpuguy83** [comment]
@Suncatcher It's a configuration issue. You've told docker to use `/dev/mapper/docker-pool0-tpool` but this does not seem to exist.
Did you setup the devicemapper thinpool?

**Comment by cpuguy83** [comment]
Here's the setup instructions https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#/configure-direct-lvm-mode-for-production

**Comment by Suncatcher** [comment]
Going through this guide I cannot do the first step.
**pvcreate /dev/xvdf** gives me
`Can't open /dev/xvda1 exclusively.  Mounted filesystem?
`

**Comment by cpuguy83** [comment]
@Suncatcher you need to specify your own block device here.

**Comment by Suncatcher** [comment]
I specified it (`xvda1` in my case). Maybe my device is not block?
This is what I get from df -h:
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1      7,8G  750M  7,0G  10% /
devtmpfs        488M   92K  488M   1% /dev
tmpfs           498M     0  498M   0% /dev/shm
```

**Comment by propercoil** [comment]
having the same issue on AWS:
```
docker version

Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Fri Jan  6 22:16:21 2017
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Comment by Suncatcher** [comment]
As [I was told](https://github.com/docker/docker/issues/30726#issuecomment-277553059) it's better to switch to another distro, however it's weird. In official AWS help [there are](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html) clear instruction how to install Docker and **it should** work out of the box.
Smth is wrong with Amazon AMI, however it's dead frost so submit smth to Amazon. No luck.

**Comment by thaJeztah** [comment]
ping @samuelkarp looks like there's two people running into this issue ^^

**Comment by Suncatcher** [comment]
Switching to Ubuntu solved the thing and Docker was installed like a charm. 
However you should definitely contact Amazon (as they have no real customer service) in order they stopped to release such a crap (I'm about AMI linux).

**Comment by samuelkarp** [comment]
@thaJeztah Thanks for pinging me.

@Suncatcher @propercoil Amazon Linux does not come configured to use direct-lvm by default and will instead use loop-lvm.  However, the Amazon ECS-optimized AMI does come with a script ([docker-storage-setup](https://github.com/projectatomic/docker-storage-setup)) that configures the instance to use direct-lvm on first boot on the `/dev/xvdcz` device (a second EBS volume); the thin pool does end up named `docker-docker-pool` so I assume that you are using the ECS-optimized AMI instead of just standard Amazon Linux.  You can find details of this in the [ECS documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html#ecs-ami-storage-config).

AWS offers [support plans](https://aws.amazon.com/premiumsupport/) that can help if you ever run into issues using any AWS product or service.

If you need help with Amazon Linux specifically, you can post on the [Amazon Linux forum](https://forums.aws.amazon.com/forum.jspa?forumID=228).  If you need help with ECS specifically, you can post on the [ECS forum](https://forums.aws.amazon.com/forum.jspa?forumID=187) or on the [ECS agent GitHub repo](https://github.com/aws/amazon-ecs-agent).

**Comment by Suncatcher** [comment]
@samueldg , thanks for clarification. However, you should update your documentation about configuring Docker on Amazon ECS Linux and add links to corresponding pages and scripts. AWS is one of the most popular cloud platforms and such questions will be raised more and more in future.

**Comment by samueldg** [comment]
@Suncatcher I think you meant @samuelkarp

**Comment by Suncatcher** [comment]
@samueldg , exactly! Sorry.

**Comment by johnreytanquinco** [comment]
Encountered the same problem but fixed running the command in sudo.
