### ISSUE TITLE
Document what --memory-swap=0 means

### ISSUE THREAD

**Issue by jamshid** [docker/docker#30716]
The 1.13.0 docs do not describe the effect of using `--memory-swap=0`. The default is `-1` which means unlimited. Does `0` mean no swap will be allowed, or do I have to set `--memory` and `--memory-swap` to the same value to accomplish that?

https://docs.docker.com/engine/admin/resource_constraints/#/memory-swap-details

**Comment by thaJeztah** [comment]
Can you report this in the documentation issue tracker, because that's where this document is maintained; you can use the ["request docs changes"](https://github.com/docker/docker.github.io/issues/new?title=Feedback%20for:%20engine/admin/resource_constraints.md&assignee=mstanleyjones&body=File:%20[engine/admin/resource_constraints.md](https://docs.docker.com/engine/admin/resource_constraints/)) link on that page 

I'll close the issue here, but feel free to continue the conversation
