### ISSUE TITLE
Improve troubleshooting UX for V2 plugins

### ISSUE THREAD

**Issue by bboreham** [docker/docker#30761]
Extracted from #30024:

> It seems really difficult to debug a v2 plugin - no `docker logs` or anything like that.

There is, unless I missed it, no way in the UI for the user/sysadmin to see whether the process is crashing and restarting, no way to look inside the container, no way to do anything beyond install it and list its name via the docker command.

You can drop down to `containerd` to find the ID, `exec` inside it and so forth, but this is somewhat ugly and undocumented.

**Comment by cpuguy83** [comment]
Agreed. Might be nice to take advantage of runc's ability to "exec" a non-running container.
But even then it can be pretty painful if there's no tooling in the plugin image.
Most of mine are just static binaries, so instead of entering the mount ns I have to mess around in `/proc`.

We probably need to look at the use case here and provide something that a user might be expected to run vs a plugin developer.

**Comment by anusha-ragunathan** [comment]
Added debug docs. Reopen if there's more that you are looking for.
