### ISSUE TITLE
When running interactive container, the tty initialization is too long

### ISSUE THREAD

**Issue by Soulou** [docker/docker#30785]
```
└> docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.7.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 19:42:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.7.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 19:42:59 2016
 OS/Arch:      linux/amd64
```

Explanation for the bugs are here: https://github.com/influxdata/influxdb/issues/7354

Basically when a container is started with the flags `-it`, it starts with a stty with

* `cols = 0`
* `rows = 0`

A few millisecond later, these values are intialized by docker, but still, there is a periode where the value is 0.

Is there a way to avoid this delay to happen?

Thanks.

**Comment by vincentwoo** [comment]
(related to my request in https://github.com/docker/docker/issues/10341)

**Comment by fntlnz** [comment]
@Soulou I know that's a workaround but using `stty rows` and `stty columns` before your command might do the trick. However having a "parameter" like @vincentwoo asked would be a better solution.

I'm closing this since there's not built-in solution to achieve this and we already have an issue #10341 to address this.
