### ISSUE TITLE
Proposal: Reduce Service create options

### ISSUE THREAD

**Issue by ehazlett** [docker/docker#30797]
As I've been working through https://github.com/docker/docker/issues/25303 it seems we are trying to bring container run options directly across.  This is OK for some things (i.e. `name`) but seems less than ideal for the rest.  I'm not a big fan of dozens of flags as this quickly gets out of control when using it in a production setting.  

My proposal is to actually reduce the existing options we have for `service create` and push those to the stack definition.  In a "real" world setting it's hard to remember all of the necessary flags for a service (let alone a container) and we should take advantage of stacks.

For example, I propose we reduce the options of service create to the following:

```
Create a new service

Options:
      --help                             Print usage
  -l, --label list                       Service labels (default [])
      --mode string                      Service mode (replicated or global) (default "replicated")
      --name string                      Service name
      --replicas uint                    Number of tasks
  -t, --tty                              Allocate a pseudo-TTY
      --update-delay duration            Delay between updates (ns|us|ms|s|m|h) (default 0s)
      --update-parallelism uint          Maximum number of tasks updated simultaneously (0 to update all at once) (default 1)
```

I think this makes it easy to explore Services with something simple like `docker service create --mode global nginx` but doesn't degrade the user experience by overwhelming the user with dozens of flags.  For comparison, `docker run` has 95 flags and I don't think we should just port these across to services.

**Comment by aaronlehmann** [comment]
I agree that `service create` has a lot of flags but I'm skeptical about deprecating most of them.

For better or worse, the CLI options are part of a workflow people are familiar with. It would be disruptive to tell people they need to switch over to compose files as part of an upgrade (even if that's a few versions away).

And even if we steer people towards compose files, I think it's handy to be able to change parameters with a single `docker service update` command. Eventually it would be great to have a way to diff the running service configuration against a compose file. We had this at the beginning of swarmkit when we had a compose-like yaml format for declaring services.

If we did decide to pare down the set of flags, I can think of a few other things that might be important enough to keep:

- `--constraint`
- `--env`
- `--publish`
- `--network`
- `--with-registry-auth`

We might end up with a set so large that deprecating the others doesn't simplify things much.

I'm more on board with limiting new flag additions and supporting new features through compose files. But there is something to be said for feature parity between the CLI and compose files.

**Comment by ehazlett** [comment]
Fair enough although I'm skeptical about the actual usage when we get into hundreds of flags.  IMO specifying defined options in a config as opposed to trying to remember every flag and value on the CLI is more inline with what actual operators do.

**Comment by aaronlehmann** [comment]
I like the idea of moving in a direction where instead of defining a flag for every tunable item, we somehow allowed individual fields from the compose grammar to be specified on the command line. But I'm not sure exactly what this would look like. We'd need to specify the path to a key in a different way from the actual YAML file, because multiline strings with nested indentation aren't command-line friendly. This might butcher the format so much that it's not really worth doing.

In case the above was confusing, I'm thinking of something like:

```
docker service update --set /services/web/image=busybox myservice
```

**Comment by thaJeztah** [comment]
So, yes, basically, we were discussing if _every_ option we have on `docker run` is _portable_ enough for `docker service`, and _widely_ used. For example, there's a lot of resource-constraints that are supported on `docker run` that _may_ make sense for a very limited target audience, but completely unused by most users. Many of those are 1-on-1 translations of a cgroup. People using those options would be familiar with those cgroups, so I'm almost tempted to say; have a `--cgroup` option that allows you to set/custom any cgroup for the container; leaving the responsibility to the user.

Ideally, most options for services should be portable, so that irregardless of the node a task ends on, I am sure my options are supported. For example, the `--limit-cpu` and `--limit-memory` options were designed to be an "abstract", "portable" way to set these constraints (and not a 1-on-1 translation to the cgroups/limits that are used).

Similarly, options, such as;

```
      --device-read-bps throttled-device      Limit read rate (bytes per second) from a device (default [])
      --device-read-iops throttled-device     Limit read rate (IO per second) from a device (default [])
      --device-write-bps throttled-device     Limit write rate (bytes per second) to a device (default [])
      --device-write-iops throttled-device    Limit write rate (IO per second) to a device (default [])
```

Could possibly be "abstracted" similarly

**Comment by thaJeztah** [comment]
> This is OK for some things (i.e. `name`) but seems less than ideal for the rest

Actually, there's some things related to that as well; for example, `--name` sets the name of the _service_; names of individual _tasks_ are based on that, but there are some use cases for templating that (e.g. `--container-name='task{{.TaskID}}.{{.ServiceName}}'`)

**Comment by cirocosta** [comment]
Hey, sorry if I just didn't understand but, what is the result of this discussion? Are there any discussions going on about whether the flags from the epic (https://github.com/moby/moby/issues/25303) should be added or not? 

I mean, should contributors hold on and not make PRs for those flags until something like this proposal lands or is it desireable that the community contribute the implementation of these flags? 🤔 

Thx!
