### ISSUE TITLE
docker sshd cpu 100%

### ISSUE THREAD

**Issue by zebozhuang** [docker/docker#30808]
I am suprised that sshd comsumes 100% CPU of my server.
![screenshot from 2017-02-08 11-14-39](https://cloud.githubusercontent.com/assets/1593533/22722176/409c47c4-edf0-11e6-8dc4-fbade95fadb1.png)
Now I can not login my docker, even I can not run docker kill, docker stop and docker images commands. They are blocked.

**Comment by thaJeztah** [comment]
Can you explain how this relates to docker? `sshd` is software installed on your machine, and not installed by `docker`

**Comment by zebozhuang** [comment]
@thaJeztah I have never met such a situation before, sshd can run 100% cpu in my machine. I run sshd as  deamon in my docker so that it can keep running after  I logout docker.

**Comment by zebozhuang** [comment]
@thaJeztah  Two weeks ago, it was normal. But It was stuck when I came back. And other command docker images, docker kill, and docker stop can not be run because they are blocked when I try to stop
my docker.

**Comment by thaJeztah** [comment]
> I run sshd as deamon in my docker so that it can keep running after I logout docker.

Is it running in a container or on the host? We really need more information, because just "sshd uses a lot of CPU", at least;

- what platform / distro are you  running docker on
- what version of docker do you have installed
- how is that `sshd` running; is it in a container or on the host
- steps to reproduce, perhaps log files?

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

**Comment by zebozhuang** [comment]
@thaJeztah It is running on a container.
1. The docker is running on ubuntu.

> root@iZ2321o1tjkZ:~# uname -a
Linux iZ2321o1tjkZ 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

2. version of docker:

> root@iZ2321o1tjkZ:~# docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64
Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64

3. sshd is running on docker, I can not run docker ps now. but the last CMD is as following:
 

> CMD ["/root/run.sh"]
 run.sh
 #!/bin/bash 
 /usr/sbin/sshd -D
~                       
4.This is how I run the docker:
docker run -d -p 19701:22 -p 3306-3308:3306-3308 -it

**Comment by thaJeztah** [comment]
Couple of things I notice;

- You're publishing a number of other ports; is something else running in that container, and, are you sure nothing is connected to that `sshd` possibly causing this issue?
- Docker 1.12.3 is not an up to date version of docker; many bugfixes have gone into 1.12.4,.5 and .6, including a security fix for RunC; did you install docker from the ubuntu repository, or using the official binaries from the apt.dockerproject.org repo?
- Make sure your kernel is up to date; 3.13.0-32 is an outdated kernel; there has been issues with older kernels that could result in processes hanging (see https://github.com/docker/docker/issues/18180#issuecomment-193708192)

**Comment by zebozhuang** [comment]
@thaJeztah OK, thanks.

**Comment by thaJeztah** [comment]
good to hear it's resolved!
