### ISSUE TITLE
[REGRESSION] connection reset by peer when attaching stdin AND stderr at run

### ISSUE THREAD

**Issue by runcom** [docker/docker#30816]
**Description**

echo'ing something while attaching stdin AND stderr at docker run isn't working anymore. Works fine if you use just stdin or just stderr instead.

**Steps to reproduce the issue:**
1. `echo true | docker run -a stdin -a stderr --tty=false fedora bash`
2. `echo true | docker run -a stdin -a stderr fedora bash`
3.

**Describe the results you received:**
```sh
$ echo true | docker run -a stdin -a stderr fedora bash
read unix @->/var/run/docker.sock: read: connection reset by peer
```

**Describe the results you expected:**

just exit == 0

**Additional information you deem important (e.g. issue happens only occasionally):**

if you revert this https://github.com/docker/docker/pull/30446 - everything works ok again.

**Output of `docker version`:**

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   41650df
 Built:        Wed Feb  8 09:46:12 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   41650df
 Built:        Wed Feb  8 09:46:12 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 51
Server Version: 1.14.0-dev
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: cc oci runc
Default Runtime: oci
Init Binary: docker-init
containerd version: 78fb8f45890a601e0fd9051cf9f9f74923e950fd
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.9.7-201.fc25.x86_64
Operating System: Fedora 25 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.44GiB
Name: runcom.usersys.redhat.com
ID: 62I5:E7N5:VHP3:HEWA:7I2L:JLUR:JQV7:SDPV:GYHS:LFYI:QBIH:KRRV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 24
 System Time: 2017-02-08T10:00:49.513415092+01:00
 EventsListeners: 0
Username: runcom
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

everywhere

**Comment by runcom** [comment]
ping @cpuguy83 @LK4D4

**Comment by jim-minter** [comment]
I believe that applying https://github.com/jim-minter/docker/commit/1aa000451ced8c0c4034e667a33efb1cc9833fc9 would resolve this.

However, I'm not really convinced that applying that patch is the answer.

Background: the client gets the `connection reset by peer` error because the daemon closed the unix socket without reading data that was waiting for it (the daemon) in its socket buffer.

Regardless of #30446, `echo foo | docker run -a stdin ...` did not and does not actually forward the text "foo" to the container process.  It was always necessary to specify `-i` (which itself implies `-a stdin`).  FWIW, I can't see the circumstances under which setting `-a stdin` without `-i` and piping in data, is a valid thing for a client to do.

Before #30446, behaviour in this case was that a "buffered stdin pipe" (search daemon/attach.go for that text) would happen to read at least some data from the client socket if available, even though it would not then send it on to the container in this case.  Hence no ECONNRESET error.

Current behaviour, after #30446: no data is read, and the client gets the error, which is designed to indicate to them that the data they sent never got as far as the container.  This is not necessarily a bad thing, IMO.

So: applying the patch indicated above would return to the previous functionality, but I think it's not great functionality.

I think some/all of the following would be better:
- don't apply my additional patch
- warn on/disallow `-a stdin` without `-i`
- ideally, remove the "buffered stdin pipe" functionality - I haven't fully looked into it, but I have no idea why it's even there.

What do others think?

**Comment by runcom** [comment]
ping @cpuguy83

**Comment by cpuguy83** [comment]
argh, I have no idea why we have `-a stdin` and `-i`... will need some time to look through this.
At the very least we should present a better error than conn reset.

**Comment by cevich** [comment]
> Current behaviour, after #30446: no data is read, and the client gets the error, which is designed to indicate to them that the data they sent never got as far as the container. This is not necessarily a bad thing, IMO.

OTOH, almost no other command behaves like that.  The right thing to do IMHO is not regress on these behaviors for compatibility sake at the least, and also don't do weird things without a really good reason (and consistency across all sub-commands)

e.g.
```
# echo foobar | docker info; echo $?
...
0

# echo "foobar" | docker ps; echo $?
...
0

$ echo foobar | ls -la; echo $?
...
0

$ echo foobar | ps -ef; echo $?
...
0

$ echo foobar | touch foobar; echo $?
0

echo foobar | iptables --help; echo $?
...
0
```
