### ISSUE TITLE
Error when removing stack

### ISSUE THREAD

**Issue by joelchen** [docker/docker#30853]
**Description**

Error when removing stack when left with 1 node.

**Steps to reproduce the issue:**
1. Initialize Docker Swarm from one node
2. Join master node from another node as manager
3. `docker stack deploy -c docker-compose.yml stack` on master node
4. `docker swarm leave --force` on 2nd node
5. `docker stack rm stack` on master node

**Describe the results you received:**
```
$ docker stack rm stack
Removing service stack_project-web-sit
Failed to remove service e2bbnn0wuyy4pwdzz7i299muf: Error response from daemon: rpc error: code = 4 desc = context deadline exceededRemoving service project_redis
Failed to remove service tlrzxf6v905xwtmxdqej4oofx: Error response from daemon: rpc error: code = 4 desc = context deadline exceededRemoving service project_caddy
Failed to remove service z4qwgq2iqqp0v0zyvnfvfiwur: Error response from daemon: rpc error: code = 4 desc = context deadline exceededRemoving network project_default
Failed to remove network iyv9ej2b3olp4lykr3q9qa0sv: Error response from daemon: rpc error: code = 4 desc = context deadline exceededFailed to remove some resources
```

**Describe the results you expected:**
```
$ docker stack rm stack
Removing service project_caddy
Removing service project_redis
Removing network project_default
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Attempting to remove 2nd node that had left via step 4 above on the master node also results in same error:
```
$ docker node rm rbsqkisilhcrq2f5fn0d7al9p
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded
```

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 35
 Running: 0
 Paused: 0
 Stopped: 35
Images: 12
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 121
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: gvqvt20ff1cpvq2tonlb7l92q
 Is Manager: true
 ClusterID: xd92cbileld0mieqx8qb8pf05
 Managers: 2
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.16.112
 Manager Addresses:
  172.31.16.112:2377
  172.31.7.169:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952 GiB
Name: ip-172-31-16-112
ID: SWAH:VWD3:HGAX:NKEB:MKVC:LK7B:BPQ2:S6X5:DA6J:QPXD:Y3AN:XAQV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: khamoud
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Nodes are AWS t2.small instances.

**Comment by thaJeztah** [comment]
This is expected; you have a 2-manager setup; in swarm mode,  changes to the swarm can only be performed if a majority of the managers have "acknowledged" the change. For two managers, that means more than 50% of the managers so _two_ managers.

A manager by itself cannot "decide" to _remove_ itself from the swam; `docker swarm leave` "disconnects" the node, but doesn't _remove_ the manager from the list of manager (doing so, requires _two_ managers to acknowledge that change).

Because lf this, from the perspective of the remaining manager;

- there are _two_ managers in the swarm (which can also be seen in the output of `docker info`
- one manager is "missing"; it does not respond, so it must be down
- no changes can be made to the swarm (including starting, stopping services, and demoting nodes)

The "context deadline exceeded" means that the manager awaits confirmation from the other manager(s) in the swarm, but no response was received.

To _remove_ a master from your swarm;

1. _Demote_ the node from a manger (`docker node demote xxyyzz`
2. Once demoted, remove the node from the swarm (`docker swarm leave` from the node you want to remove 

I'll close this issue because this not a bug but feel free to continue the conversation
