### ISSUE TITLE
Cannot run container with -m or -c

### ISSUE THREAD

**Issue by Vuiz** [docker/docker#30932]
Container runs without -m or -c (or --memory/--cpushares) but when run with, this error is given.

```
docker run webodm_webapp --memory="58g"
container_linux.go:247: starting container process caused "exec: \"--memory=58g\": executable file not found in $PATH"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"--memory=58g\": executable file not found in $PATH".
ERRO[0000] error getting events from daemon: net/http: request canceled

```

**Comment by lbguilherme** [comment]
Shouldn't it be `docker run --memory="58g" webodm_webapp`?

**Comment by thaJeztah** [comment]
Yes, docker options go _before_ the name of the image to run; if you pass them _after_ they're used as the _command_ to run _inside_ the container. Given that there's no `--memory` command/binary in the container; that will fail.

I'm going ahead and close this issue, because there's no bug here, but feel free to ask after I closed
