### ISSUE TITLE
Debian package - remove SysVinit configuration because it's not used

### ISSUE THREAD

**Issue by sbwoodside** [docker/docker#30936]
Debian by default uses SysVinit. That's what Debian users are used to. They can use other init systems if needed.

The docker-engine package includes SysVinit scripts such as `/etc/init.d/docker` which lead me to think that I could edit the config file `/etc/default/docker`. That doesn't work because docker is NOT using SysVinit on Debian, it's using `systemd`.

There is an issue with lots of comments from debian users confused by this: https://github.com/docker/docker/issues/9889#issuecomment-109766580

**Steps to reproduce the issue:**
1. Install docker on Debian Jessie using instructions here: https://docs.docker.com/engine/installation/linux/debian/#/install-using-the-repository
2. Try to edit /etc/default/docker
3. It doesn't have any effect
4. Add a file `/etc/systemd/system/docker.service.d/docker.conf` and put config in there
5. I.e. follow instructions here: https://docs.docker.com/engine/admin/#/configuring-docker-1 (by the way that doc needs to be updated to also say that it is used for Debian as well (and probably Ubuntu)

**Describe the results you received:**

Configuration failed to do anything.

**Describe the results you expected:**

Configuration does something.

**Comment by ijc25** [comment]
> Debian by default uses SysVinit. That's what Debian users are used to. They can use other init systems if needed.

Debian Jessie uses systemd by default, but as you say you can switch e.g. to sysvinit with `apt-get install sysvinit-core`.

Note that the selection of initsystem is host wide and that they are mutually exclusive i.e. a host cannot have some daemons using systemd and some using sysvinit (although this is somewhat blurry because systemd has some compatibility shims for sysv init scripts).

> That doesn't work because docker is NOT using SysVinit on Debian, it's using systemd.

It would be more accurate to say that docker uses whichever init system the host is configured with and yours is using systemd. If you had switched your system to sysvinit then editing `/etc/default/docker` would be correct.

Removing the sysvinit scripts would break the docker-engine package for anyone who has explicitly switched to sysvinit (or who has upgraded from older versions of Debian where that was the default without transitioning). The situation wrt systemd vs sysvinit configuration should perhaps be documented more clearly (perhaps including a suitable comment header in each file would help), but I don't think the sysvinit scripts should be removed.

**Comment by cpuguy83** [comment]
Agreed, we cannot remove the sysvinit script.
Note that the best method for configuring docker is via `/etc/docker/daemon.json`, which is distro/init agnostic.

https://docs.docker.com/engine/reference/commandline/dockerd/#/linux-configuration-file

Thanks!

**Comment by sbwoodside** [comment]
Thanks @ijc25.

@cpuguy83 Regarding `/etc/docker/daemon.json` it looks great but the [Configure and run Docker on various distributions](https://docs.docker.com/engine/admin/) page doesn't mention it.
