### ISSUE TITLE
Docker: Error response- error creating aufs mount to /var/lib/docker

### ISSUE THREAD

**Issue by jshiao** [docker/docker#31149]
I just started to use Ubuntu USB and docker. 
I got this message when I run docker hello-world. I don't know what to do. 

docker run hello-world
docker: Error response from daemon: error creating aufs mount to /var/lib/docker/aufs/mnt/8df7ace1555ac05d4f738bcdbb1324c130e6cb2e23a01dac1f54cdc431ec4735-init: invalid argument.
See 'docker run --help'.

If possible, please provide method for me to understand the problem. Thanks!

**Comment by cpuguy83** [comment]
@jshiao Most likely the underlying filesystem is not supported for aufs. You probably will need to use use the `vfs` driver unless you attach another device formatted with xfs or ext.

Note that the `vfs` storage driver is going to be quite slow and does not support copy-on-write like the other drivers do, so everything is copied up all the time.

**Comment by danielfsilva88** [comment]
Sorry to ask in this closed topic, but i wish to know how to change the underlying filesystem like it was cited.

I had the same issue of @jshiao with a debian stretch (4.9.0-4-amd64) live usb, and it was "corrected" with vfs storage driver, however, due to lack of space in usb, i wish to set an overlay2 storage-driver with an extfs backing filesystem (my issue was with an aufs/overlayfs pair). 

Ps: i also didn't understand how i had an aufs SD in a kernel 4.9 (if someone could explain that too i will be very thankful).
