### ISSUE TITLE
Centos dockerd broken from after 1.12.3

### ISSUE THREAD

**Issue by javadan** [docker/docker#31184]
**Description**

After 1.12.3 on Centos, (i.e. docker-engine-1.12.3-1.el7.centos), the docker daemon stopped working.  

This was the previously working config in 1.12.3:
ExecStart=/usr/bin/dockerd -H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375 --insecure-registry 10.20.2.1:5000

When run on later versions, processes start up in the background, but all docker commands result in the "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" error.

**Steps to reproduce the issue:**
1. systemctl stop docker

2. yum update docker-engine

3. (update wipes out my config, 
so add back in the parameters in /usr/lib/systemd/system/docker.service and /lib/systemd/system/docker.service because I'm not sure which one is correct)

4. systemctl daemon-reload

5. systemctl start docker

**Describe the results you received:**

service docker status shows it is running, but all docker commands result in:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Temporary workaround:**

ps -ef | grep "docker"
kill -9 everything.
Run /usr/bin/dockerd  --insecure-registry 10.20.2.1:5000 &
and leave out the docker.sock stuff

Or, downgrade to 1.12.3

**Comment by thaJeztah** [comment]
> (update wipes out my config,
so add back in the parameters in /usr/lib/systemd/system/docker.service and /lib/systemd/system/docker.service because I'm not sure which one is correct)

Updating should keep the systemd unit file untouched if you modified it, but note that you should _never_ directly modify the systemd unit file, and use a drop-in file instead (see https://docs.docker.com/engine/admin/systemd/#/custom-docker-daemon-options)

> service docker status shows it is running

Did you verify if the daemon (`dockerd`) process was running? If it is, do the daemon logs show any errors?

`Cannot connect to the Docker daemon` can also show if you don't have _permissions_ to access the `docker.sock`. What happens if you use `sudo`? (e.g. `sudo docker version`)?

**Comment by javadan** [comment]
Ok, there's no /etc/systemd/system/docker.service.d directory on my CentOS.  From what I can tell from your link, I would add this to a conf file in that dir, instead of editing the /usr/... or /lib/... file:
**[Service]
ExecStart=/usr/bin/dockerd -H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375 --insecure-registry 10.20.2.1:5000**



I'm root so there's no permission errors.



If I do ps -ef
I see there is a daemon running, after **systemctl start docker**


[root@dkr02 /]# ps -ef | grep docker
root      1224     1  0 17:23 ?        00:00:00 /usr/bin/dockerd -H tcp://0.0.0.0:2375 --insecure-registry 10.20.2.1:5000
All the docker-containerd-shim and docker-proxy's are running too.
After a while, it appears all programs are running.


[root@dkr02 /]# systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: **active** (running) since Mon 2017-02-20 17:23:19 SAST; 4min 26s ago
     Docs: https://docs.docker.com
 Main PID: 1224 (dockerd)
   Memory: 110.6M
   CGroup: /system.slice/docker.service
           ├─1224 /usr/bin/dockerd -H tcp://0.0.0.0:2375 --insecure-registry 10.20.2.1:5000
           (and so on)


But all docker commands show 
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by javadan** [comment]
Solved it... added -H unix:///var/run/docker.sock to ExecStart  :P

**Comment by GajovskiMaxime** [comment]
Can You explain Javadan ? I dunno what is ExecStart :x

**Comment by javadan** [comment]
@GajovskiMaxime - So, when you start up docker daemon, you sometimes have a bunch of options you want to set, so there's this mechanism called systemd, which you run with systemctl, which is just what the UNIX service passes it's commands to. So, **service docker start**.... will call **systemctl start docker**... and then it will look in a config file to work out what to do. The ExecStart line has the command to call to start up the daemon.

But apparently I've been doing it wrong by editing the docker.service file. There's some .conf drop-in file I'm supposed to use instead.

That's about all I know about it though.

**Comment by javadan** [comment]
Epilogue:

I upgraded another machine to 1.13.1.  I added the .conf file, and it was picked up.  Like in the docs, I needed a blank ExecStart= before my real ExecStart= or it complains.

Then it didn't start up after the upgrade.

Error in the logs was:
can't create unix socket /var/run/docker.sock: is a directory

I ran:
 rmdir  /var/run/docker.sock

systemctl daemon-reload
systemctl start docker

and it started up OK.

So I think there probably still is a bug in there somewhere, because I shouldn't have to do all this in order to upgrade to the latest docker.  But at least it was a quick fix.

**Comment by thaJeztah** [comment]
> can't create unix socket /var/run/docker.sock: is a directory

What I suspect is that you have a container running that's bind-mounting `/var/run/docker.sock` into the container. For historical reasons, docker automatically creates the host-path for bind-mounts if the path does not exist on the host; for example;


```
docker run -dit -v /foo/bar:/baz busybox
```

Automatically creates a directory named `/foo/bar` on the host if no such directory exists. Key here is that the docker does not know if you intended to bind-mount a _directory_ named `/foo/bar` or a _file_ named `/foo/bar`.

When starting docker, there is a race condition between the daemon starting, and the API being "up"; at that point `/var/run/docker.sock` is not yet present, but the container is started. As a result, the daemon creates a _directory_ named `/var/run/docker.sock`, and bind-mounts it into the container.

The moment the API is started, it fails, because it tries to create a socket at `/var/run/docker.sock`, but finds a directory at that path.

FWIW, we once deprecated the auto-creation of host-paths, but it was a breaking change for some users, and had to revert that change.
