### ISSUE TITLE
Docker Systemd service (docker.service) doesn't import variables from /etc/default/docker

### ISSUE THREAD

**Issue by fike** [docker/docker#31200]
Any change of /etc/default/docker isn't export to docker systemd service (docker.service). Mainly, DOCKER_OPTS variable. Probably, this is happen because  **docker.service** doesn't have **EnvironmentFile** parameter. 

This is fixed changing ExecStart to add $DOCKER_OPTS in the end of line and one line before add **_EnvironmentFile=/etc/default/docker_**. Therefore, these parameters would look like this:

[...]
EnvironmentFile=/etc/default/docker
ExecStart=/usr/bin/dockerd -H fd:// $DOCKER_OPTS
[...]

The environment is below
```
$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:34 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:34 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
$docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.9.0-0.bpo.1-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 996.3 MiB
Name: node1
ID: 3ESS:IQD7:EYQD:77TS:DNUL:6E54:Y4TD:E6JO:LGKA:UCP5:SKOD:NMQU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

```
$ uname -a
Linux node1 4.9.0-0.bpo.1-amd64 #1 SMP Debian 4.9.2-2~bpo8+1 (2017-01-26) x86_64 GNU/Linux
```

```
cat /etc/debian_version
8.7
```

**Comment by thaJeztah** [comment]
The `/etc/default/docker` file is only used for upstart/sysvinit (see the comment at the top of that file: https://github.com/docker/docker/blob/v1.13.1/contrib/init/sysvinit-debian/docker.default#L1-L8)

To configure daemon options;
- Use a daemon-configuration file; https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file (this method works irregardless of the process manager in use)
- Use a systemd drop-in file to override options from the systemd unit file; https://docs.docker.com/engine/admin/systemd/#custom-docker-daemon-options

We discussed adding an EnvironmentFile to the systemd unit, but using such a file was not the recommended way to configure a systemd service. (drop-ins are). Unfortunately, some distros ship docker with a different systemd service file than the [unit file in the official packages](https://github.com/docker/docker/blob/v1.13.1/contrib/init/systemd/docker.service), which can be confusing if you have such a package installed.

I'll close this issue, because this has been discussed in other issues (see https://github.com/docker/docker/issues/29652#issuecomment-268759359), but I hope the above helps you further

**Comment by fike** [comment]
Ouch! My apologies for didn't see documentation and #29652 before. I agree but perhaps there is an exception for .deb package provide for Docker. In the .deb could provide a file to import variables from _/etc/default/docker_ and become centralized any change, such as systemd, upstart or sysvinit. 

@thaJeztah, do you think is possible to add a file (/etc/systemd/system/docker.service.d/environment.conf) for .deb packages provide for Docker or this will keep unreasonable?
