### ISSUE TITLE
Documentation on Docker Status Webhooks

### ISSUE THREAD

**Issue by stefankraus-wf** [docker/docker#31296]
**Description**

As a Docker User, I want to know the format of the incoming webhooks from status.docker.com so that I can properly parse the data. This can be in the form of a JSON schema that is linked from the [status page](status.docker.com) or is otherwise searchable in the Docker [documentation](docs.docker.com).

**Steps to reproduce the issue:**
1. Visit the [status page](status.docker.com) and look for an example Webhook
2. Visit the [documentation](docs.docker.com) page and search for an example Webhook.

**Describe the results you received:**
I could not find documentation on the format of the webhooks on the status page or the docker documentation page.

**Describe the results you expected:**
An example of a webhook payload that may be received or a JSON schema exists in the documentation or can be found on the status page. It should show the different fields that will be returned and sample values that they could hold. For enum-like fields, for example `{'status':` 'good' | 'not so good' | 'bad'}`, the possible values should be listed.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

N/A

**Output of `docker info`:**

N/A

**Additional environment details (AWS, VirtualBox, physical, etc.):**
N/A

**Comment by thaJeztah** [comment]
Hi! Thanks for asking; this would probably a question for support@docker.com, as this is managed by Docker. Inc., not the open source project that's in this repository.

As far as I know, status.docker.com is using https://status.io, which may have some information

I'll close this issue here for housekeeping, as it's not really related to the source code in this repository, but feel free to continue the conversation
