### ISSUE TITLE
Implementing cassandra on dockerize.

### ISSUE THREAD

**Issue by phanirajl** [docker/docker#31335]
Hi,
I Want to run  DSE Container as a service using Docker Swarm .So i should be using service same as my hostname

1)When i use service name in cassandra.yaml on below properties 
   Seeds:
   listen_address:
   rpc_address:
   a)can a DSE container do a Gossiping.
   b)How do i support rack/datacenter	for dockerized nodes.

2)If i run multiple containers on a single machine how do they function.
Can anyone help me on this.

**Comment by thaJeztah** [comment]
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to comment after I closed.
