### ISSUE TITLE
Failed to run ./hack/make.sh

### ISSUE THREAD

**Issue by windowsair** [docker/docker#31367]
---> Making bundle: validate-dco (in bundles/1.9.1/validate-dco)
These commits do not have a proper 'Signed-off-by:' marker:
 - cd72306db2ec3b4760e646cb5a69b45cbb56a239
 - 2144c126d943b49e7f3ec3b9335b6cec78b07a9c
 - 929716bf23d18afc7bc7d9a68ed30a81933c7a67
 - d62c40b96d7d80e93742c79b41409359865b51c0
 - 29bd994aef36058da504ffe07e3eaa3f15879212
 - c9c088f86338ce08dca3e2239d8c7addf15e4d13

Please amend each commit to include a properly formatted DCO marker.

Visit the following URL for information about the Docker DCO:
 https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by ripcurld0** [comment]
I think you forgot to add your sign-off inside the commit.
Try to run the following command inside the docker directory (where the source code is):
`git commit -s --amend`

Read more here: https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work (as the error message suggests)

**Comment by windowsair** [comment]
Thanks.
But it seems can only modify the latest commit, and the error is commit history

**Comment by ripcurld0** [comment]
Does this help?
https://gist.github.com/kwk/d70f20d17b18c4f3296d

**Comment by thaJeztah** [comment]
Alternatively, you can do an interactive rebase (for example, `git rebase -i upstream/v1.9.1`) and mark each commit as `edit`. You can then sign-off and amend each commit (`github commit -s --amend --no-edit`).

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Comment by windowsair** [comment]
OK.It works.I am deeply sorry for your inconvenience caused by me.

**Comment by thaJeztah** [comment]
No worries, I was just closing for housekeeping :smile:
