### ISSUE TITLE
Wait for service update completed

### ISSUE THREAD

**Issue by WTFKr0** [docker/docker#31387]
**Description**

Add a way to wait for service update result
I think this is useful for Continous Deployment tools
Today we have to query service api to get the "UpdateStatus" info waiting for result

**Steps to reproduce the issue:**
1. docker service update --image myimage:version my_service

**Describe the results you received:**
my_service (code 0) in a second

**Describe the results you expected:**
With a new flag, wait for end of update and return status of update or RC like 
0 : completed
1 : paused
2: rolledback

**Comment by fntlnz** [comment]
@WTFKr0  If you need a quick way to obtain the status using the cli you can still inspect the service's `UpdateStatus`

```
✔ 15:57:46 ~ $ docker service inspect -f "{{.UpdateStatus.State}}" att841yyzi1x
completed
```

**Comment by thaJeztah** [comment]
There's a proposal currently being worked on to add "Swarm" events; see https://github.com/docker/swarmkit/issues/491, which may be useful for your use case. In addition, there's a pull request that allows the CLI to switch to _synchronous_ instead of _asynchronous_; https://github.com/docker/docker/pull/31144

**Comment by WTFKr0** [comment]
OK thanx, we can close that since this PR is OK for my needs : #31144
I follow that

**Comment by thaJeztah** [comment]
Great! Thanks for opening this issue 👍, and if you have feedback on the proposed changes in https://github.com/docker/docker/pull/31144, feel free to comment there
