### ISSUE TITLE
can create container with an option stop with dockerd while global live-restore is enabled

### ISSUE THREAD

**Issue by okletswin** [docker/docker#31403]
Hi, when I enabled --live-restore=true for dockerd, some special container can't work as well.
for example, the container has a volume /var/run/docker.sock, when dockerd restarted and recreated docker.sock file, the file in container exists, but is not same as the servers, so execute 'docker version' report docker daemon is not running.

**Comment by thaJeztah** [comment]
I think that may be expected, as bind-mounting the socket probably keeps the old inode. Can you try if bind-mounting `/var/run` instead works?

**Comment by okletswin** [comment]
@thaJeztah yes, I tried mount the /var/run directory and restart dockerd, the container works well.
The future of file-binding keep an old inode can be modify? or provide a parameter for control

**Comment by thaJeztah** [comment]
No changing this behavior would not be possible, because it's the way mounts work on Linux. Here's some information about inodes https://www.ibm.com/developerworks/aix/library/au-speakingunix14/.


I'll close this issue, because this is a known limitation of bind-mounting individual files, but feel free to continue the conversation after I closed
