### ISSUE TITLE
how can i export an docker volume to a zip or tar file

### ISSUE THREAD

**Issue by godcong** [docker/docker#31417]
I have not found any way in the documentation from official website

if have how to inport the volume?

**Comment by thaJeztah** [comment]
There's no built-in command for exporting/importing data into volumes. You can attach the volume to a container, and use the container to export/import data. For example, if your volume is named `foobar`;


If the daemon is running locally, you can bind-mount a local directory and copy the files from the volume to the bind-mounted directory

```bash
$ mkdir -p backup
$ docker run --rm -v foobar:/volume -v `pwd`/backup:/backup busybox sh -c 'cp -r /volume /backup'
```

For a remote daemon, you can "tar" the volume and send it to `stdout`;

```bash
$ docker run --rm -v foobar:/volume busybox sh -c 'tar -cOzf - /volume' > volume-export.tgz
```

Also see https://github.com/docker/docker/issues/18718

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Comment by godcong** [comment]
3q~

**Comment by thaJeztah** [comment]
YW!

**Comment by ice7mayu** [comment]
Use mount and bind-mount at the same time for a single container. Thanks!

**Comment by megamayoy** [comment]
@ice7mayu Could you please guide me on how to do both volumes and bing-mounts at the same time if I'm using docker-compose?

**Comment by minecraftchest1** [comment]
> There's no built-in command for exporting/importing data into volumes. You can attach the volume to a container, and use the container to export/import data. For example, if your volume is named `foobar`;
> 
> If the daemon is running locally, you can bind-mount a local directory and copy the files from the volume to the bind-mounted directory
> 
> ```shell
> $ mkdir -p backup
> $ docker run --rm -v foobar:/volume -v `pwd`/backup:/backup busybox sh -c 'cp -r /volume /backup'
> ```
> 
> For a remote daemon, you can "tar" the volume and send it to `stdout`;
> 
> ```shell
> $ docker run --rm -v foobar:/volume busybox sh -c 'tar -cOzf - /volume' > volume-export.tgz
> ```
> 
> Also see #18718
> 
> Please keep in mind that the GitHub issue tracker is not intended as a general support forum, but for reporting bugs and feature requests. For other type of questions, consider using one of;
> 
>     * https://forums.docker.com
> 
>     * the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
> 
>     * [StackOverflow](https://stackoverflow.com)
> 
> 
> I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

Wrong solution. Is this can be done, build it into `docker volume export`
