### ISSUE TITLE
Docker swarm secrets should be available as environment variables

### ISSUE THREAD

**Issue by cecchisandrone** [docker/docker#31422]
Hello,

I'm trying to migrate an application organized with Docker compose and environment variables and I was wondering how to change it to use secrets introduced in Docker 1.13. The main problem I see is that secrets are available as files and thus all the images that need environment variables (e.g. mysql) should be rebuilt with a proper wrapper script that reads these files and put their values in env vars. Do you plan to do this automatically in future Docker releases or am I not seeing the true solution to this issue?

**Comment by thaJeztah** [comment]
No, secrets will not automatically be exposed as environment variables; the design of the secrets feature _deliberately_ doesn't use environment variables, because environment variables are insecure, because they can easily leak (they can appear in logging/debugging output, and other processes are able to get access to them).

It's possible to use adapt your images to using file-based secrets though; for example, the official MySQL image has been updated to make use of the secrets in Swarm mode; https://github.com/docker-library/mysql/commit/4dd33136c4739667a223d39b6f829beb27b235cf#diff-10359b5dc7c35d252f89912170617e1e

I'll close this issue for house keeping, and I think your question is answered, but feel free to continue the conversation

**Comment by cecchisandrone** [comment]
Thanks for the answer, I just wanted to be sure if it's something foreseen for future Docker releases or not.

**Comment by thaJeztah** [comment]
You're welcome!
