### ISSUE TITLE
docker mount : the ability to mount a volume in a running container

### ISSUE THREAD

**Issue by brmzkw** [docker/docker#31452]
This is a feature request. 

#### Current status

It is only possible to specify the docker volumes/host files/host directories to mount into a container at creation time, with `docker run` or `docker create`.

#### Suggestion

The new `docker mount` command accepts three arguments:

* the container name
* a source path (a docker volume name or an absolute path of the host's filesystem
* a destination path (where to mount the source)

#### Usecase example

You have your development container, let's say a PostgreSQL container, started with `docker run --rm postgres`. You want to execute a script into it. Unfortunately, the script is on the host's filesystem.

Your options:

* stop the container and restart it with `docker run --rm -v /path/to/script:/script postgres`
* copy the script: `docker cp /path/to/script container_name:/script` and redo the copy everytime the script changes on the host
* or, thanks to `docker mount`, run `docker mount /path/to/script container_name:/script`

#### Thoughts

After a short discussion on IRC, `docker mount` could be seen as something breaking a container's immutability/"ephemerality", but:

- `docker cp` achieves the same result, it's just not as efficient
- Specifying a volume at container creation achieves the same result, but it's not extensible (you can't add/remove volumes dynamically) and requires to restart the container anyway.

**Comment by cpuguy83** [comment]
I'm not sure this is possible without breaking the container's mount isolation.

If there were a pre-defined path in the container fs that could be setup as a slave-mount where new mounts would be injected to it may work, but this will also be racey and could generally cause lots of problems.

In general I'd be -1 on doing something like this.
Mounts can be really tricky and is a huge pain point right now in general.

**Comment by nschoe** [comment]
I'm with @cpuguy83 on this one.
Usually, when people come ask this on IRC, I answer that it's not possible, that they have to destroy the container and mount the volume / host's directory on their new `docker run` command.

I _always_ add that this should not be a problem since containers should be ephemeral.

And regarding this feature, I feel like this is the kind of feature that will make this "containers should be ephemeral" claim weaker, because "what the hell bother think about how I should use Volumes if I can plug it a new one when I see fit". :/

(_that being said, I am not a docker developer_)

**Comment by thaJeztah** [comment]
I'm -1 as well; we've discussed this a couple of times in the past and while it looks like a neat feature, there's a lot of ways this can go horribly wrong, which is not a risk we're willing to take. Recreating the container to update the volume is really the best way forward for this.

I'll go ahead and close this issue, but thanks for suggesting, and feel free to continue the conversation.

**Comment by WolfgangFahl** [comment]
I think this issue should not be closed. There is a need to be able to mount additional volumes at runtime and IMHO there should be a way to fulfill this need. See e.g. https://www.bountysource.com/issues/33154966-mount-cifs-within-a-container and https://stackoverflow.com/questions/27989751/mount-smb-cifs-share-within-a-docker-container and https://github.com/moby/moby/issues/22197

Currently the work-around --cap-add SYS_ADMIN --cap-add DAC_READ_SEARCH is awkward because it doesn't have a natural option name like --allow-mounts and you still need to install cifs-utils

**Comment by cpuguy83** [comment]
"-v /foo:/bar:rslave" and then do the mount on the host in "/foo.

**Comment by cpuguy83** [comment]
This is the only way this can be accomplished.

**Comment by gyger** [comment]
I have one example were I do not see another solution.

A nginx container is started containing the code of the web service. It is based on php and fastcgi. Now a second container is used for php-fpm, but it needs the volumes from the nginx container, and the nginx container needs to connect to php-fpm to start, otherwise nginx will shutdown again.
This circular dependency makes it hard to design a system where mounts can not be added after startup.

**Comment by thaJeztah** [comment]
@gyger you can use a named volume that you share between those containers ("dummy" instructions below, just to illustrate);

```
$ docker volume create myvolume

$ docker run -v myvolume:/some/path php-fastcgi:latest
```

Use `:nocopy` on the nginx container, as you don't want data to be copied from that container to the volume (may even be mounted `ro` (read-only)

```
$ docker run -v myvolume:/some/path:nocopy nginx
```

Optionally, add a restart-policy to the nginx container to make it restart on failure (e.g. if php-fpm is not started yet)

**Comment by shuaichang** [comment]
> "-v /foo:/bar:rslave" and then do the mount on the host in "/foo.

@cpuguy83 your solution works like a charm. That's exactly what I need to change content of a container dir but not re-creating/starting a container, thanks!

**Comment by sachja** [comment]
Can someone explain the solution above. 
What command should have the "-v /foo:/bar:rslave" argument?

**Comment by shuaichang** [comment]
@sachja docker run -v /foo:/bar:rslave {image}

**Comment by sto6** [comment]
> "-v /foo:/bar:rslave" and then do the mount on the host in "/foo.

"/foo" has to be a unique/dedicated dir for each container instance; else same image if spawned as more than one container on same host are affected in unison.
Is there some trick to nicely exploit host-side per-container name-spaces for /foo?
