### ISSUE TITLE
Total mess with docker packaging on Gentoo

### ISSUE THREAD

**Issue by UralZima** [docker/docker#31609]
Hello. I use official docker overlay. I have unmasked docker, containerd, runc and docker-runc packages.
All was fine, once I updated docker and it deleted runc and installed docker-runc. 
On latest update, it want runc back and results in package block.
containerd-0.2.5 depends on runc, 0.2.5-r1 depends on docker-runc.
docker 17.03.0 depends on runc.
Ok I downgraded containerd to resolve block, now docker container fails to start with 
oci runtime error: flag provided but not defined: -console

I read on github issues, that docker is not compatible with runc anymore, but still depend on it.
I resolved it by modifying ebuild and replace runc with docker-runc on DEPEND section. 

Please fix docker ebuild to depend on docker-runc

**Comment by thaJeztah** [comment]
Thanks for reporting @UralZima. The Gentoo overlay is not an package that is maintained by the docker project, but by volunteers on the Gentoo project; can you report this issue there? @tianon (who's also a maintainer here) may be able to help. Unfortunately we cannot help you here, because that package / overlay is not maintained here.

w.r.t;

> I read on github issues, that docker is not compatible with runc anymore

That's not the case; there is no stable release yet for RunC (it hasn't yet reached 1.0), and docker currently uses fork of the 0.2 branch. This will change once RunC reaches 1.0 and the specs are stable.


I'll close this issue here, because of the above, but feel free to continue the conversation

**Comment by UralZima** [comment]
Thanks. Now I opened the issue in right place: https://github.com/tianon/docker-overlay/issues/69
