### ISSUE TITLE
bind /var/lib/docker:/var/lib/docker on dind:17.03-dind cause dockerd starting failed

### ISSUE THREAD

**Issue by sfwn** [docker/docker#31600]
**Description**

I run `docker build & docker push` inside dind:17.03-dind container. 
For speeding up the build process, I have to use build cache. So I want to bind `/var/lib/docker:/var/lib/docker` on this dind container. But it cause the dockerd inside dind container starting failed.

**Steps to reproduce the issue:**
1. The command I used is:
`docker run --privileged -ti -v /var/lib/docker:/var/lib/docker docker:17.03-dind`

**Describe the results you received:**
```
Unable to find image 'docker:17.03-dind' locally
17.03-dind: Pulling from library/docker
627beaf3eaaf: Already exists
1ed492db3a66: Already exists
d33053c322ce: Pull complete
8c4c8fa6a6a9: Pull complete
abbcefd2b80d: Pull complete
969bfae120ca: Pull complete
c33fc9cdbc00: Pull complete
68c7cb5693c8: Pull complete
Digest: sha256:b9a649480ac1002af3150d708a5a989d56a1e6b1321fff7b10e42b25c7def60b
Status: Downloaded newer image for docker:17.03-dind
WARN[0000] [!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]
INFO[0000] libcontainerd: new containerd process, pid: 16
Error starting daemon: error while opening volume store metadata database: timeout
```

**Describe the results you expected:**
The docker daemon starts successful and the cache which `docker build` makes will be stored and next `docker build` command will automatically use there build cache.

**Additional information you deem important (e.g. issue happens only occasionally):**
1. OS: centos 7.1611

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:54:03 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:54:03 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.03.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.7 MiB
Name: localhost.localdomain
ID: O6QR:FUAC:LAZ3:M3JM:VL3J:A2K2:CSDS:7A5T:2SO3:T5GG:45SD:W6TG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 0.0.0.0/0
 127.0.0.0/8
Registry Mirrors:
 https://ktm7bvr4.mirror.aliyuncs.com
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
My host is inside VirtualBox through vagrant.

**Comment by thaJeztah** [comment]
Sharing `/var/lib/docker` between multiple daemons is not supported, and generally asking for trouble (including data corruption). A daemon should have exclusive access to the `/var/lib/docker`. You may want to read this blog post about this; https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

If you only have a _single_ dind active at a time, you can consider;

- using a named volume for the cache; (`docker run --privileged -ti -v docker-data:/var/lib/docker docker:17.03-dind`)
- using a different host-path for the dind container (`docker run --privileged -ti -v /var/lib/docker-dind:/var/lib/docker docker:17.03-dind`)


You may also be interested in the `--cache-from` option introduced in docker 1.13; https://github.com/docker/docker/pull/26839

I'm going to close this issue, because sharing `/var/lib/docker` between daemons is not a supported scenario, and is known to cause issues. Feel free to continue the conversation after I closed the issue
