### ISSUE TITLE
no tar, sudo available on SLC6 -

### ISSUE THREAD

**Issue by farrukhazfar** [docker/docker#31769]
Dear Folks,

I have installed a CERN SLC6 - and I don't seem to have tar, or sudo commands - I cannot invoke them I get a "command not found" message -

I am a newbie, sorry if this is a dumb question

Farrukh
 

**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Docker is software you _install_ on your Linux distro; If you have questions about using Linux, this is not the right place to ask; perhaps check if there's a support forum http://linux.web.cern.ch/linux/

I'll close this issue, because this is not a docker issue, but feel free to comment after I closed
