### ISSUE TITLE
`docker node ps` does not check for swarm node

### ISSUE THREAD

**Issue by albers** [docker/docker#31879]
If you issue swarm commands on a non-swarm node, you get an error indicating that the command can only be issued on a swarm manager. Example:

```bash
$ docker node ls
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
```
This is not true for `docker node ps`:
```bash
$ docker node ps
ID                  NAME                IMAGE               NODE                DESIRED STATE       CURRENT STATE       ERROR               PORTS
Error: No such node:
```

**Comment by thaJeztah** [comment]
I think this will be fixed by https://github.com/docker/docker/pull/31513

**Comment by thaJeztah** [comment]
oh, actually, probably not, let me check again

**Comment by albers** [comment]
#31912 solves a similar problem.
@AkihiroSuda maybe you are interested in this issue as well?

**Comment by aluzzardi** [comment]
/cc @tonistiigi @aaronlehmann 

We're probably not doing the membership check in `ps`?

**Comment by aaronlehmann** [comment]
It's happening because the argument to `docker node ps` defaults to `"self"` if none is given. The first thing `docker node ps` does is try to resolve `"self"` to an ID using the `/info` endpoint. If there's no node ID, it just gets an empty string. This causes it to request `/nodes/`, which is not a valid endpoint. It gets a 404 error, and treats this as "node not found".

I'll submit a PR to add proper validation to the `"self"` replacement. It should check that the node is a manager, and also check that the ID is not blank.

**Comment by albers** [comment]
Thanks @aaronlehmann. Verified, works.
