### ISSUE TITLE
Oracle DB upgrade from 11g to 12c failed with PRVF-7565 error

### ISSUE THREAD

**Issue by SivarajaReddy** [docker/docker#32036]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

I am trying to upgrade DB from 11g to 12C on docker container but it failed with the error:
PRVF-7565 : Could not perform the runlevel verification check on
and I observed that I the command who -r is not working as expected.
I am not getting any output while executing who -r, due to which upgrade failed at pre-req verfication.

Can any one please check and help here? if u have faced this issue on dockers.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by AkihiroSuda** [comment]
Since this question is specific to Oracle and does not seem to an issue of Docker, I'm closing this issue.

You should be able to get Oracle 12 image from https://github.com/oracle/docker-images/tree/master/OracleDatabase, but if you have specific reason to rather upgrade existing Oracle 11 image to Oracle 12, I suggest asking the question to the author of your Docker image.
