### ISSUE TITLE
[Proposal] Create a new plugin type for API profiling

### ISSUE THREAD

**Issue by rogaha** [docker/docker#32133]
**Description**

As a developer and sysadmin, I would like to have a plugin that allows me to collect stats of API usage and profiling. Currently we have tree types of plugins:
 - `authz`
 - `Network`
 - `Volume`

The `authz` plugin gives us all the information we need in order to develop such a plugin, however it doesn't meet usability requirements: ability to `enable/disable` it remotely using the `docker plugin's API` as the `authz` plugin cannot be `enabled` remotely due to security reasons (an attacker could easily take over the `daemon`). Therefore, I propose that we create a different plugin `type` that only listens to the `request/response` between `clients & daemon`:

**Plugin should implement**
```
type Plugin interface {
	ProfilingReq(Request) Response
	ProfilingRes(Request) Response
}
```

**Requirements:**
 - `enable/disable` the plugin remotely (ideally it should be applied to the `swarm` cluster as a whole)

/cc @anusha-ragunathan @riyazdf @justincormack

**Comment by cpuguy83** [comment]
I think this particular use-case should be provided by the prometheus metrics.

**Comment by rogaha** [comment]
@cpuguy83 the `prometheus` metrics doesn't give us the `client / daemon` perspective. and having a plugin allows us to `install/un-install` it very easily across the whole cluster at once (`coming soon`) by using the `docker plugin's API`.

**Comment by thaJeztah** [comment]
Would that be more in line with https://github.com/docker/swarmkit/pull/1940 ?

**Comment by thaJeztah** [comment]
I understand; the question is, is it a long-term use case if other options are implemented (once it's implemented, it needs to be maintained "forever"), so trying to look at possible options that would cover the use-case, before tying down to a solution. It's still possible we end up with the proposed solution, but all options should be looked at before making that decision.

**Comment by rogaha** [comment]
yep, totally. I'm with you. I'm open to suggestions, but it seems that maintaining this `plugin` type seems to be reasonable as it's doesn't require much code to be implemented.

**Comment by justincormack** [comment]
I think as it is basically a cut down `authz` plugin without the ability to refuse events, its probably little work to maintain, and little code generally.

**Comment by anusha-ragunathan** [comment]
In the authz approach: 
1. sysadmins/operators would setup the daemon to use the `authz` plugin. This sets up the ability to read/write/modify the http request/response between client and daemon.
2. users cannot control daemon's usage of the plugin, other than disable it. Even for disable, the authz plugin can reject the request.

The `Profiling` plugin seems to be a read-only version of the authz plugin. i.e ability to read the http request/response between the client and daemon. So instead of having a new type of plugin, we can have a sub-class of an authz plugin for `read-only` modes. This becomes a profiler, although calling this an `authz` plugin would be a misnomer.

**Comment by anusha-ragunathan** [comment]
`however it doesn't meet usability requirements: ability to enable/disable it remotely using the docker plugin's API as the authz plugin cannot be enabled remotely due to security reasons (an attacker could easily take over the daemon).`

The other option to implement this would be to say that `enable` will work on-the-fly, but only in read-only mode. This will prevent client from hijacking the HTTP requests/responses. 

daemon startup -> rwm HTTP req/resp
plugin disable -> convert from rwm -> ro, but plugin continues running
plugin enable -> plugin runs in ro mode.
Plugin runs in ro mode until daemon restart.

**Comment by rogaha** [comment]
> In the authz approach:

>sysadmins/operators would setup the daemon to use the authz plugin. This sets up the ability to read/write/modify the http request/response between client and daemon.
users cannot control daemon's usage of the plugin, other than disable/remove it. Even for these cases, the authz plugin can reject the request.
>The Profiling plugin seems to be a read-only version of the authz plugin. i.e ability to read the http request/response between the client and daemon. So instead of having a new type of plugin, we can have a sub-class of an authz plugin for read-only modes. This becomes a profiler, although calling this an authz plugin would be a misnomer.

you are right, that's exactly it. So, to avoid confusion with `read-only` `authz plugin` do you think that having another `plugin` type is acceptable?  it would be act as a `read-only` `authz plugin`.

**Comment by rogaha** [comment]
>The other option to implement this would be to say that enable will work on-the-fly, but only in read-only mode. This will prevent client from hijacking the HTTP requests/responses.

>daemon startup -> rwm HTTP req/resp
plugin disable -> convert from rwm -> ro, but plugin continues running
plugin enable -> plugin runs in ro mode.
Plugin runs in ro mode until daemon restart.

@anusha-ragunathan so, in this case the `plugin disable` won't stop the `plugin` container?

**Comment by anusha-ragunathan** [comment]
@rogaha : Yes, it would not stop the plugin. Instead it would put it in ro mode.

**Comment by anusha-ragunathan** [comment]
Giving this more thought, it looks like having a separate `Profiling` plugin would be cleaner. Ping @docker/core-maintainers for thoughts.

**Comment by friism** [comment]
Another nice aspect of a separate plugin type is that plugins of the new kind could possible be sent events asynchronously, and further, that Docker could complete api calls even if the profiling plugin is not responding for whatever reason. This would remove profiling plugins from the performance and uptime-critical path.

**Comment by cpuguy83** [comment]
I don't think a plugin of this nature should receive request/response data.
We can provide further instrumentation of the daemon using the existing prometheus metrics.

Another service can come along and scrape the metrics from there. Now how can we containerize such a service?
Maybe a special plugin type that just gets the metrics socket mounted in.
This is similar in nature to the same issue of providing a way to mount the docker socket without having to actually specify something like `-v /var/run/docker.sock:/var/run/docker.sock` since this assumes that there is a unix socket at /var/run/docker.sock and that the inode for the socket never changes.

**Comment by rogaha** [comment]
I'm closing this in favor of the `prometheus` metrics exposed by the `/metrics` endpoint. Thanks @cpuguy83 @crosbymichael @anusha-ragunathan for your guidance!
