### ISSUE TITLE
[Flakey test] DockerRegistryAuthTokenSuite.TestPushMisconfiguredTokenServiceResponseError

### ISSUE THREAD

**Issue by vdemeester** [docker/docker#32159]
https://jenkins.dockerproject.org/job/Docker%20Master%20(arm)/5003/console

```
18:08:54 FAIL: docker_cli_push_test.go:608: DockerRegistryAuthTokenSuite.TestPushMisconfiguredTokenServiceResponseError
18:08:54 
18:08:54 docker_cli_push_test.go:616:
18:08:54     c.Assert(out, checker.Contains, "Retrying")
18:08:54 ... obtained string = "" +
18:08:54 ...     "The push refers to a repository [127.0.0.1:5000/busybox]\n" +
18:08:54 ...     "5f70bf18a086: Preparing\n" +
18:08:54 ...     "076f5601cfb4: Preparing\n" +
18:08:54 ...     "toomanyrequests: out of tokens\n"
18:08:54 ... substring string = "Retrying"
```

**Comment by tophj-ibm** [comment]
I see the issue. By the time the upload goroutine in push happens, the server has already retried it's x amount of times and is now just throwing the given test response (toomanyrequests: out of tokens in this case). Because this response is a do not retry response, it doesn't retry, hence the check for "Retry" fails.

 I don't think testing for a retry needs to happen in this test anyway, none of the other tests in the suite do it, and I imagine there is a much less racy / more efficient test for that anyway. I can open a PR changing the behavior

**Comment by tophj-ibm** [comment]
so I am actually mistaken, the original point of the test is to test for retries, and the error it is throwing is just a non-retry error, so we just need a less racy way of bringing up a temporarily unavailable registry, let me rework what I've done.

**Comment by tophj-ibm** [comment]
I'm seeing two different GET requests on the failing ones, do any of you know where / why dockercli is getting added?

&{GET /?scope=repository%3Abusybox%3Apush%2Cpull&service=registry  

vs

&{GET /?scope=repository%3Abusybox%3Apush%2Cpull&scope=repository%3Adockercli%2Fbusybox%3Apull&service=registry

**Comment by vdemeester** [comment]
@tophj-ibm ohh interesting 😓 no reald idea but that can give us some inputs, I'll try to take a look tomorrow 👼

**Comment by thaJeztah** [comment]
Should be resolved by https://github.com/docker/docker/pull/32285
