### ISSUE TITLE
BUG : Unable to start the VM in docker toolbox 

### ISSUE THREAD

**Issue by nehalbhanushali** [docker/docker#32396]
**Description**

![image](https://cloud.githubusercontent.com/assets/17151758/24741485/1d90321c-1a74-11e7-8e6d-e18891c0fc7b.png)

**Steps to reproduce the issue:**
1. Install Docker toolbox on Windows Home Edition
2. Open quickstart terminal

**Describe the results you received:**
```
Error creating machine: Error in driver during machine creation: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm default --type headless failed:
VBoxManage.exe: error: The virtual machine 'default' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\Users\nehal\.docker\machine\machines\default\default\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

Looks like something went wrong in step ´Checking if machine default exists´... Press any key to continue...
```

**Describe the results you expected:**
Machine start

**Additional information you deem important (e.g. issue happens only occasionally):**
Was working fine until a week back

**Comment by thaJeztah** [comment]
Can you report this in the Docker Toolbox issue tracker? https://github.com/docker/toolbox/issues

It may be worth checking the `VBoxHardening.log` log file that the error message refers to first (or include it in your bug report). Also when reporting, please include the versions of Docker Toolbox and VirtualBox that you have installed

I'll close the issue here, because this issue cannot be resolved in this repository, but feel free to continue the conversation
