### ISSUE TITLE
[Question] Docker documentation offline?

### ISSUE THREAD

**Issue by reijin90** [docker/docker#32598]
Hi!

I wonder where I can find a PDF or other version of the current Docker documentation. I was unable to find it via Google and the official docs page. Probably I'm overlooking sth.?

Thanks for your help!

**Comment by thaJeztah** [comment]
No, there's no version of the documentation for offline use (PDF, or epub), however, the docs are published as docker images, which you can download and run on your local machine. Also see https://github.com/docker/docker/issues/19237, and https://github.com/docker/docker.github.io/issues/289

I'll close this issue, because I think the question is answered, but feel free to continue the conversation

**Comment by sfreemire** [comment]
Which Docker images contain the Docker documentation!!

**Comment by tkoeck** [comment]
Are there epub and/or mobi formats? Having it on a docker image is fine but sometimes someone wants to read it on an ebook reader ...

**Comment by thaJeztah** [comment]
No, no other formats are published, so you'd have to convert it through other means
