### ISSUE TITLE
Add bridge data to API info

### ISSUE THREAD

**Issue by windowsrefund** [docker/docker#3909]
Since I can't seem to figure out how to add this support, here's the idea:

It would be great if the /info endpoint would include any data related to the following:

  * BridgeIface
  * BridgeIP
  * BridgeNetwork
  * BridgeNetmask

Given the fact that both BridgeIface and BridgeIP are represented in config.go, I figure this is doable. From there, I'd assume the remaining attributes could be determined and published.

**Comment by achanda** [comment]
The codebase has churned a lot since this conversation. I was trying to get the bridge by using `job.Getenv("BridgeIface")` and `daemon.Config().BridgeIface`. Both of those seem to return the value set as a parameter to the docker daemon. I am pretty new to Docker (and golang), am I missing something here?

**Comment by cpuguy83** [comment]
Closing since this is now available via the API (since 1.9).
`docker network inspect bridge`
