### ISSUE TITLE
Allow images to be pulled by ID

### ISSUE THREAD

**Issue by titanous** [docker/docker#4106]
In Flynn artifacts (such as container images) are completely immutable. This means that we need a way to consistently pull the *exact* same image every time. The solution is to allow images to be referenced by ID directly (I don't care if the name is required).

@creack mentioned in IRC that this feature might have been removed at some point.

**Comment by ejholmes** [comment]
+1

**Comment by tianon** [comment]
The registry currently supports this, but it is limited to a namespace that the ID has been known to exist within previously.  For example, downloading `ef872312fe1bbc5e05aae626791a47ee9b032efa8f3bda39cc0be7b56bfe59b9` in the context of `hello-world` is possible, but not in the context of `debian` (since it's an old `:latest` tag of `hello-world`, but has never been pushed to `debian`).

**Comment by termie** [comment]
+1

**Comment by vbatts** [comment]
all, please see #11109 for an implementation that can satisfy this.

**Comment by jfrazelle** [comment]
closing as https://github.com/docker/docker/pull/11109 is merged and will be in 1.6!
