### ISSUE TITLE
docker run -e VAR='$APT_PORT_3142_TCP_ADDR` not expanded

### ISSUE THREAD

**Issue by SvenDowideit** [docker/docker#4136]
I want to set my apt-cacher proxy automatically to a --linked container

```
docker run -rm -t -i -e 'http_proxy=http://$APT_PORT_3142_TCP_ADDR:${APT_PORT_3142_TCP_PORT}/' --link apt-cacher-run:apt debian bash
```

but at this point, everything is escaped.

is there an internal docker --link way to crack this egg?

**Comment by jfrazelle** [comment]
@SvenDowideit i take it this is still an issue?

**Comment by duglin** [comment]
PR #12344 should solve this one

**Comment by duglin** [comment]
(sorry for the long comment and showing you the 'interesting' progress of this)

I actually do have a fix for this but I don't think we can merge the code changes - but I'd like to hear what others think.

Most of this is pretty much along the lines of what @tianon mentioned earlier.

When we get the env vars from a `docker run` command we stick them into the container and *then* later on we add the "link" env vars right before we actually start the container.  Changing the order in which this happens isn't too bad, and in fact, that's what I did.  And it works just fine after I then also do the $... substitutions.

However, there's a problem. From my testing, it appears that the -e vars are saved within any image that is created from that container, while the "link" env vars are not.  Not saving the "link" ones makes sense.  But my code changes will also *not* save the `docker run` -e vars too because they may need to have the "link" env vars values to work properly.  And this would be a breaking change, which is why I don't think we can accept this code change.

One variant of my code did a little bit of both. It saved the -e vars in the container (and therefore any resulting image) but didn't do the env var substitutions until right before any new container was started, and after the LINK vars were set.  Sounds promising.  It even worked when new containers from that image were run with new -e vars, they were merged appropriately.  

However, there's a problem - again.  These -e vars are not really in the image, yet.  By that I mean, if someone created a Dockerfile using that image in the FROM, and then used ENV to change those previously defined -e vars it would look like it worked, but then any new container created from that new image would have those same (original) -e vars processed again and added to the new container - thus overriding anything done within the Dockerfile.  This is because the -e vars are pulled out into a new field and treated as 'special' and always processed right before a new container is started.  I did try to remove the vars from the -e list as they were mentioned in the ENV cmds, but things got really messy when I tried that due to how we merge config data - so I stopped.  The hole I as digging here started to really scare me beyond my comfort level at this point.

Anyway, the net of this is that I don't think we can support this w/o potentially breaking something or making some changes that will probably feel like hacks.

But, what do other people think?  @erikh @tiborvass

**Comment by tiborvass** [comment]
@duglin wauh! That's really nice that you tried so hard! I think you analyzed perfectly the situation.

However, I think @SvenDowideit's issue can be easily solved by:

Dockerfile:
```
FROM ubuntu:14.04
# ...
ENTRYPOINT ["/wrapper.sh"]
```

wrapper.sh:
```
#!/bin/sh
export http_proxy=http://$APT_PORT_3142_TCP_ADDR:${APT_PORT_3142_TCP_PORT}/
exec "$@"
```

I feel like the usecase is very narrow and can be circumvented like explained above, so I'd vote for closing this issue.

**Comment by duglin** [comment]
@tiborvass yep - I think that would probably do it for him.  I was just hoping to provide a native solution but given the way things are currently design I don't think its possible.

**Comment by tiborvass** [comment]
ok thanks for looking into it though @duglin ! I'm gonna close this to make us feel somewhat better about our open issues # :)
