### ISSUE TITLE
document docker logs

### ISSUE THREAD

**Issue by schmichael** [docker/docker#4934]
While `docker logs` is extremely useful for inspecting containers, [the documentation gives no hints as to how it should be handled operationally](http://docs.docker.io/en/latest/reference/commandline/cli/#logs).

Outstanding questions include:

* Where are logs stored (or are they an inmemory ring buffer like dmesg)?
* If they are stored, how are they rotated so they don't grow without bound?
* Is it a best practice for daemons running in containers to *not* using `std{out,err}` for logging (and instead use the host's syslog, a log file in a mounted voulme, a remote daemon, etc.)?

As per guidelines for contribution:

```
Client version: 0.9.1
Go version (client): go1.2.1
Git commit (client): 3600720
Server version: 0.9.1
Git commit (server): 3600720
Go version (server): go1.2.1
Last stable version: 0.9.1

Containers: 3
Images: 47
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 57
Execution Driver: native-0.1
Kernel Version: 3.11.0-18-generic
WARNING: No swap limit support
```

I tried searching existing issues for duplicates, but logging is a very difficult thing to search on. Please feel free to close if this is a dupe.

**Comment by jfrazelle** [comment]
@SvenDowideit has the documetation around this been updated

**Comment by unclejack** [comment]
I'm going to change the title of this issue to make it a docs only change. Logs have been improved already: there are 2 logging drivers now: none and jsonfilelog (the default). There's one more logging driver in the pipeline: https://github.com/docker/docker/pull/11485

**Comment by wlan0** [comment]
@unclejack  There's also a 'Syslog' logging driver

**Comment by Blaisorblade** [comment]
Current docs are at https://docs.docker.com/reference/run/#logging-drivers-log-driver and https://docs.docker.com/reference/logging/overview/. But the latter doesn't actually say how to configure the daemon — one has to guess that the same driver-specific options also work for the daemon. There's some info at https://docs.docker.com/reference/commandline/daemon/ and/or in ma docker, but it is insufficient.

In particular, I guess I'll use, by default, something like `--log-opt max-size=2m --log-opt max-file=10` to enable auto-rotation every 2 MB. I did that by changing `/etc/default/docker` so that it reads:
```
DOCKER_OPTS="--log-opt max-size=2m --log-opt max-file=10"
```

**Comment by cpuguy83** [comment]
Docs are up to date as far as I can see.
They show how to configure the daemon, as well as per container.

Closing as I believe this is taken care of.
Thanks!
