### ISSUE TITLE
Propagate http_proxy env var to builds

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#4962]
I'm just opening this issue from the discussion in #1852.  The original issue was fixed but this is a secondary discussion about the need for this env var to be available from the host in builds so that the containers can access the internet.  

From the build POV we don't want to commit this because it really makes things non-portable but maybe we can find a good solution for everyone.

**Comment by mikehaertl** [comment]
Should this topic be changed to "Support build time env vars" maybe? I really second this. 

Here's my use case:

I want to build a base image for the Yii2 framework. The `Dockerfile` therefore has a `composer install` command which will fetch several composer packages from github. Unfortunately this will hit github's rate limiter very soon, so that instead of dist packages, composer will fall back to much larger source packe installation. This could easily be fixed, if I could pass a github oauth2 token for composer to the build process. Of course, I don't want this token to become part of the image.

**Comment by duglin** [comment]
@crosbymichael you ok if we close this and keep the conversation going in #9176 ?

**Comment by danday74** [comment]
We are doing ...

ENV http_proxy http://9.9.9.9:9999
ENV https_proxy http://9.9.9.9:9999

and at end of dockerfile ...

RUN unset http_proxy
RUN unset https_proxy

This, for now (until docker introduces build env vars), allows the proxy vars to be used for build without publicly exposing them

**Comment by jrandall** [comment]
This issue recently came up in GNU guix, which also uses a form of containerisation during the build process. The solution there was to create a core configuration option called `leaked_env_vars` (https://www.gnu.org/software/guix/manual/html_node/Derivations.html#index-derivation-1) which defines a list of environment variables that are injected into the build environment from the outer environment. I'd be supportive of a similar option for docker (the "outer environment" could be that of the docker daemon or of the `docker build` client, whichever is easier).

**Comment by jrandall** [comment]
@danday74 that works for sharing the image but not the `Dockerfile` itself (and critically, not for building a `Dockerfile` from elsewhere that doesn't include proxy vars that match your environment).

**Comment by thaJeztah** [comment]
Duplicated by https://github.com/docker/docker/issues/14634?

**Comment by thaJeztah** [comment]
There's now a new issue created covering this so I'll close this issue.

For those participating / following this, please continue the discussion in https://github.com/docker/docker/issues/14634
