### ISSUE TITLE
envvars which are enherited from a linked container can cause a security issue

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#5169]
Many times we use env vars to do things like give credentials for db access, etc.
Right now a container which links to other containers is pulling in the env from the linked container, thus exposing these credentials to containers that shouldn't really have them.

**Comment by jfrazelle** [comment]
@duglin +1 docs

**Comment by duglin** [comment]
PR: https://github.com/docker/docker/pull/11172

**Comment by jamercee** [comment]
I just rediscovered this issue, which caused me to open a new PR https://github.com/docker/docker/issues/11284.  My issue was closed with a link to this PR, but I can't quite understand where this stands?  I saw some reference to links v2 solving this in 1.4, but we're running 1.4 and the issue still seems present. Also, I see some discussion about the docs being updated to describe this behaviour -- but for the life of me I can't see where it's mention.

**Comment by duglin** [comment]
@jamercee docs have been updated in git but they may not be updated on the docker.com website yet.

**Comment by jamercee** [comment]
Got it (about the docs).

Any feedback on where the issue (if leaking environment from source -> target) stands? If it's documented, is it now a feature? <grin>

**Comment by jfrazelle** [comment]
That can be discussed with security@docker.com

**Comment by xeor** [comment]
I totally agree with @jamercee. The problem is still there, and it is still a security issue (see earlier discussion about cases).

**Comment by jlj** [comment]
I agree with @jamercee and @xeor about this.

Although the doc now clearly includes a warning about env variables being propagated to linked containers, this still looks like a real security problem to me, because many images, including official images pass secret information though env variables, and there still doesn't seem to be a good way to pass a private variable to a container at runtime.

This can be illustrated by a very simple php / mysql application using a database container,using the official `mariadb` image, linked with a php container based on the official `php` image.

The result is simply that any php program has access to the mysql root password via the env variables:
![phpinfo](https://cloud.githubusercontent.com/assets/1850262/9672037/7ab2099e-5297-11e5-9068-dbb821865fdd.png)

And really, this is not desirable!

Ok, this could be considered as a bug of the `mariadb` image and I will also enter it as such...  
But my real feeling is that it looks more like a general docker issue.

**Comment by pushshift** [comment]
What's the current workaround for this?  Having some entrypoint script that destroys the sensitive ENV variables once the containers are linked?  My vote is for making this a critical security issue because, as @jlj eloquently demonstrated, sensitive ENV variables are easily accessible once they propagate to the linked containers.   

I'd also think it would make sense to make it CLI option when running / linking containers to allow propagation of ENV variables (with the default being no propagation).  

Thanks.

**Comment by thaJeztah** [comment]
@pushshift you can use the new networking feature and put containers together in a network. In this network, you can reach other containers by their *name*. "Aliases" currently aren't supported, but is being worked on for 1.10. See https://docs.docker.com/engine/userguide/networking/dockernetworks/

**Comment by pushshift** [comment]
@thaJeztah Thank you.  Sounds good.  Appreciate the advice.

**Comment by mkonakan** [comment]
@pushshift or @thaJeztah Can you guys please explain how would networking
prevent this issue of environment variables passing via linking of containers?

**Comment by thaJeztah** [comment]
@mkonakan the "legacy linking" registered a fixed 1-on-1 "link" between specific container instances. Part of that system was to setup environment variables containing information about the linked container, and sharing the environment variables of the container.

The new networking doesn't use fixed links, but a more dynamic design. Part of that design is to use an embedded DNS server for discovery of linked containers, instead of environment variables.

**Comment by mkonakan** [comment]
@thaJeztah  Thank you so much. https://docs.docker.com/engine/userguide/networking/work-with-networks/#linking-containers-in-user-defined-networks - This link solved my question and hence deleted my comment. Sorry. 

Also, so there are no further plans of implementing secure way of passing env variables as suggested above ? (dont pass private..pass only public, dont pass the ones started with _ etc) Only way one need to use is to do use this networking feature or use vault , keywhiz etc kind of solutions. Did I get it right?

**Comment by thaJeztah** [comment]
@mkonakan yes; sharing/not sharing by "convention" (prefix with `_` etc) is too risky, because for some images you may not have control over how env-vars should be named. Using keywhiz etc is definitely a good thing to do. If you *do* want to use environment variables for configuration / secrets, it's easy to set them on just the containers that need to have access; for example, using an `--env-file`, or even easier when using docker-compose.

**Comment by mkonakan** [comment]
Got it. Thank you :)
