### ISSUE TITLE
privileged containers get unintentionally constrained by apparmor

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#5490]
For normal containers docker will put the container in the docker-default profile.  For privileged containers, no profile is applied and the process is unconfined.  Since the container is unconfined, the child processes are subject to getting a profile from the host auto applied base on the binaries path.  

To see this happen, on ubuntu, install tcpdump and apparmor on the host.  Then install tcpdump in a privileged container.  tcpdump in the privileged container will not run.

It seems the correct fix would be to create a "docker-unconfined" profile that is applied to privileged containers.  The profile would not actually restrict anything, but allow all.  The only purpose of using this profile is to prevent the host from auto applying profiles to container processes.

**Comment by jfrazelle** [comment]
@ibuildthecloud is this still an issue, did we end up fixing the profile?

**Comment by Jamlee** [comment]
@ibuildthecloud @jfrazelle   could we solve this issue on release 1.6?

**Comment by ewindisch** [comment]
I've put together a change for this, although I need to test it before submitting the PR:
 https://github.com/ewindisch/docker/commit/d45be4e65288f2978dfedd4a940f3debe128fd35

**Comment by ewindisch** [comment]
#dibs

**Comment by bprodoehl** [comment]
@ewindisch any progress on testing your change for this?  I'm a bit stuck trying to get NetworkManager to run in a u14.04 container on a u14.04 host due to this problem, so I'm trying out your change right now.  I'll let you know how it goes.

**Comment by bprodoehl** [comment]
The patches from @ewindisch don't seem quite right anymore, and I'm out of sync on where AppArmor things are moving.  I did manage to get around my problem by applying his one-line change to have privileged containers use the "docker-unconfined" profile, rather than "unconfined", and then I put this profile in /etc/apparmor.d/docker-unconfined:

```
#include <tunables/global>


profile docker-unconfined flags=(attach_disconnected,mediate_deleted) {
  #include <abstractions/base>
  network,
  capability,
  file,
  umount,
}
```

I don't know all the implications, but that's what finally worked for me last night.

**Comment by ewindisch** [comment]
@bprodoehl thank you for confirming that this solves the problem. We have a series of apparmor related changes, of which this is closer to the bottom. Once we merge those, I'll officially propose this fix.

**Comment by bprodoehl** [comment]
@ewindisch great, thanks!

**Comment by imehrdad2012** [comment]
@bprodoehl  Can you please provide more details on your solution? I got stuck with the same problem, but I am not expert to immediately know how to modify similar to you.

Thanks

**Comment by bprodoehl** [comment]
@imehrdad2012 the easiest way around it is to relocate the affected binaries in the container. Is that an option for you? Otherwise, you'll have to compile and install your own docker binary. I can post more detail on what I did, but if you can just relocate tcpdump or whatever isn't working in your container, that's a pretty easy fix.
