### ISSUE TITLE
Cannot destroy container XXX: Driver devicemapper failed to remove root filesystem 

### ISSUE THREAD

**Issue by The-Judge** [docker/docker#5771]
Hi everyone,

I'm facing the problem, that I cannot remove a container anymore. I asked for help in IRC and shykes_ asked me to ping creack and unclejack for it.

I created a container like this:

1. `docker run -i -t -v /var/www/docker1:/var/www:rw centos:centos6 bash`
2. Installed several packages like PHP and HTTPd using that shell
3. Created an Image from it: `docker commit -a "Name" -m "First try with apache2" 4aa4c1e47ad6 derjudge/centos6_apache2`

When I try to delete the new Image (derjudge/centos6_apache2), this works ok.
When I try to delete the container, it fails:

```
judge ~ # docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
busybox             latest              2d8e5b282c81        2 weeks ago         2.489 MB
centos              centos6             0b443ba03958        3 weeks ago         297.6 MB
centos              latest              0b443ba03958        3 weeks ago         297.6 MB
centos              6.4                 539c0211cd76        13 months ago       300.6 MB
judge ~ # docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                        PORTS               NAMES
4aa4c1e47ad6        centos:centos6      bash                About an hour ago   Exited (127) 48 minutes ago                       goofy_meitner      
judge ~ # docker rm 4aa4c1e47ad6
Error: Cannot destroy container 4aa4c1e47ad6: Driver devicemapper failed to remove root filesystem 4aa4c1e47ad69662d71b5214e0b08331b95b9b2eca05fc1d876a118b49204f55: Error running removeDevice
2014/05/13 11:15:57 Error: failed to remove one or more containers
judge ~ #
```

shykes said he hit that, too and therefore mentioned this should get added on the bugathon list for 1.0.

**Comment by jfrazelle** [comment]
ping @vbatts is this a dup

**Comment by vbatts** [comment]
This is a dup of #4036 
The "device or resource busy" (`EBUSY`) can occur when a container was started, and during that time another service has unshared from the host's mount namespace (`CLONE_NEWNS`). The reason we see this in devicemapper, is because a device is set up and mounted for the container, but despite being unmounted for a stopped/dead container, the other pid with unshared mount ns on the host has a reference to the mount and the set up device. Therefore the kernel sees the device as busy, and will not let the device be removed (the call to `docker rm ...` attempts this).
