### ISSUE TITLE
ADD doesn't untar when the tarball has xattrs

### ISSUE THREAD

**Issue by murdegern** [docker/docker#6353]
Sorry if I'm being daft, but I think I really hit a bug here (or mis-documentation). My Dockerfile is as follows:

FROM scratch
ADD rootfs.tar /
MAINTAINER Torsten Luettgert <snip@snap>

and „docker build -t sl6x_64_base .“ makes me an image with the tarfile as-is in the fs root.
The same happens if I gzip, bzip2, or xz it or write „ADD ./rootfs.tar“ (or .tar.gz, or .tar.bz2, or .tar.xz).

Environment:
Docker version 1.0.0-dev, build 4cf40c9 on Scientific Linux 6x (current),
I compiled using git clone -- make build -- make binary.
Then I replaced the system docker from docker-io-0.11.1-4.el6.x86_64.rpm with the built static one; then I recompiled it with itself (and again, for good measure).

uname -a:
Linux schilf.schiller106 3.14.6 #1 SMP Tue Jun 10 11:30:23 CEST 2014 x86_64 x86_64 x86_64 GNU/Linux

docker version:
Client version: 1.0.0-dev
Client API version: 1.12
Go version (client): go1.2.1
Git commit (client): 4cf40c9
Server version: 1.0.0-dev
Server API version: 1.12
Go version (server): go1.2.1
Git commit (server): 4cf40c9

docker info:
Containers: 3
Images: 31
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 37
Execution Driver: lxc-1.0.3
Kernel Version: 3.14.6

Regards,
Torsten

**Comment by jfrazelle** [comment]
ping @vbatts @unclejack status?

**Comment by calavera** [comment]
It looks like this issue is fixed. I've tested that rootfs in my local docker and I was able to build the image. This is a screenshot of the output:

![1 tmp xattrs zsh 2015-04-23 12-01-38](https://cloud.githubusercontent.com/assets/1050/7305193/f0a3a036-e9b0-11e4-8d12-47ac4118a0a7.png)

I've also noticed that there is a test to validate this behavior:

https://github.com/docker/docker/commit/c4fe5dad1deb45ecde460d7627523dbf032dc205#diff-b4fec8b21e8e85ba7e0537147798eaedR323

I'm closing this issue as fixed. Please, feel free to reopen if the problem persist with a modern version of Docker.
