### ISSUE TITLE
Using `sudo` in Docker docs prevents command tab complete

### ISSUE THREAD

**Issue by mchelen** [docker/docker#6754]
There are good reasons to use `sudo` instead of running as `root` however when using `sudo` in the Docker docs it prevents all commands from allowing auto completion.

**Comment by jfrazelle** [comment]
closing i dont think this is an issue anymore but let me know if you are still seeing it, also i will not the user that is tab completing needs to be part of the docker group

**Comment by nealmcb** [comment]
As I understand it, adding a user to the docker group still effectively gives them read-write access to the entire filesystem of the the machine, and is thus as dangerous as giving them no-password sudo access.  Thus many installations don't add users to the docker group, but still want auto-complete.  I'm guessing that @tianon gets auto-completion because of being in the docker group, and despite the unnecessary addition of "sudo" to the front of commands.  I certainly don't get any auto-completion on image and container names.  So as I suggested in November, having some sort of way of leaking just container and image names to users would still be very helpful.

**Comment by tianon** [comment]
@jfrazelle maybe a note in the "Known Issues" section of the docs?

**Comment by bentocin** [comment]
For some distros (e.g. Ubuntu) tab complete works OOTB for `sudo`. However, I am running Manjaro Linux and also experienced that tab complete would work just fine without `sudo` but not with `sudo`. The following got me working solution for both situations, with and without `sudo`. 

Disclaimer: Solution only tested for `bash` and no other shell.

1. Make sure `bash-completion` is installed. For me this meant I would find the file `/usr/share/bash-completion/bash_completion` which gets sourced in my `~/.bashrc`. Other distros might put this file somewhere else, e.g. `/etc/bash_completion`. With Arch distros it can be installed with `pacman -S bash-completion`.
2. Make sure `bash-completion` is not overwritten for `sudo` in your `~/.bashrc` file with `complete -cf sudo`, which sets tab complete for sudo to commands and filenames and not using `bash-completion`.
3. Put the docker completion files (docker, docker-compose, docker-machine) into the folder for bash-completion, e.g. `/usr/share/bash-completion/completions` which might also be dependent on the distro.

After I did this, I was able to get the expected result:
```bash
sudo docker ver<TAB>

# resolves to
sudo docker version

sudo docker-compose do<TAB>

# resolves to
sudo docker-compose down
```

**Comment by just-pthai-it** [comment]
I face the same issue.
I use "docker compose -f <docker-compose-file> up " to specific docker-compose file. If I log as non-root user and use sudo before the command, it will not allow auto completing file like when I run command as root.
