### ISSUE TITLE
Squash build dependencies

### ISSUE THREAD

**Issue by shykes** [docker/docker#6906]
The current implementation of “docker commit” and “docker build” makes it difficult to strip images of their build dependencies. This causes 2 problems:

* Many images are unnecessarily bloated.
* To avoid the bloat, some developers avoid using “docker build”, creating unnecessary fragmentation.

**Comment by TomasTomecek** [comment]
Any updates?

**Comment by stain** [comment]
What about just having a multi-line `RUN-MANY` mean the equivalent of the awkward `&& \` chaining pattern? 

```
RUN-MANY
  apt-get update
  apt-get install wget unzip build-essentials
  wget http://example.com/source.zip
  mkdir /tmp/src
  cd /tmp/src
  unzip source.zip
  # CRAZY - comments allowed in the middle!
  make install
  apt-get remove --purge wget unzip mvn
  apt-get --purge autoclean
  rm -rf /tmp/*
END
```

This would give a lean image, but also make it easier to copy-paste in any existing install-scripts without having to search-replace in `RUN ` on every line.

**Comment by phemmer** [comment]
@stain As you mentioned, you can already accomplish the same thing with a simple `&&` shell operator. What this issue is about is doing things which aren't possible at all (not just inconvenient). Such as merging multiple dockerfile commands into a single image/layer (`ADD` and `RUN` as 1 layer instead of 2), and squashing to free space from the composite image due to deleted files (file is added in one layer, deleted in another, the composite image still has the file in it, increasing the size).

**Comment by thaJeztah** [comment]
@phemmer to give some context; @stain's original Dockerfile used a `COPY` to add the source. I suggested a build-container or curl/wget workaround and pointed to existing issues on the issue tracker wrt getting rid of large intermediate layers.

**Comment by stain** [comment]
But isn't there something wrong when most of the Dockerfile commands can't
be used in a production image because they generate enormous intermediate
images that nobody else will ever need?

The tiny difference between ADD and COPY does not help.

The COMMIT should be a better solution then my RUN-MANY, as it would allow
you to do COPY and so on without worrying about waste, and just do multiple
RUN in a naive way.

In one project I have a github repository which somehow is 600 MB when
checked out. Ideally I would like to host the Dockerfile right there, so
the image on the hub would track updates to the github code.

Then I would  just COPY . /src and do the build within the Docker image
(installing about 40 MB of binaries) and then clean up before a COMMIT.

currently I need to have a massive && which in the end does all the cleanup
like deleting /tmp and deleting all the library files needed for
compilation. Obviously testing this takes forever as it always does
everything.

Moving from Dockerfile style during development to mega-RUN-&&  style takes
considerable effort, as one has to do so much more housekeeping like
installing wget and unzip, keep track of the temporary files downloaded (or
use pipes if tar.gz), and clean everything up afterwards.

During such a sequence not a single Dockerfile command can be used as it
would make it pointless to clean up.

Flattening layers should be straight forward as its just set difference
(after all it is done at runtime by the container). you can set the
boundary to each Dockerfile, so you can't flatten outside layers.

**Comment by aigarius** [comment]
@stain you are also confusing this with #332 , please read my comments above for a clarification.

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
