### ISSUE TITLE
Proposal: abstract layer ID and image(json) ID

### ISSUE THREAD

**Issue by vbatts** [docker/docker#6959]
spec for abstracting layer ID (created by tarsum to have a deterministic ID) and the image ID (which is the json metadata, which references a particular layer ID)

Initially, a deterministic image ID will not be directly possible, as the usual TarSum calculation includes the contents of the image's json metadata, which itself includes the image's ID.

Once the file system layer has a deterministic ID, generated with a fixed-time hash (the TarSum), but not including that json metadata, then it will be possible to deduplicate layers that are exactly the same. This may happen often, as the primary differences will be in the json metadata (this could happen in a RUN, but also for MAINTAINER, ENV, PORT, ENTRYPOINT, CMD and VOLUMES).
Therefore multiple images(json) could reference the same layer IDs.

The next step of the image(json) ID, for it to be deterministic, the ID must not be inside the json itself. Perhaps since it is already in a directory path of ./<hash>/json, then the ID is inferred from its path, and verifiable by checksuming the json with the layer ID that it references.

**Comment by stevvooe** [comment]
@vbatts Is this still relevant? We still need to decouple image ID from the layer ID, but I am not sure if this proposal is still on the happy path.

**Comment by vbatts** [comment]
fair. this is really about content addressability. I'm fine with closing this issue as we're on the path already

**Comment by stevvooe** [comment]
@vbatts The separation is still an open issue in the engine and one of the blockers for proper v2 support. The specific problem is [`github.com/docker/docker/graph.(*Graph).Register`](http://godoc.org/github.com/docker/docker/graph#Graph.Register):

```
func (graph *Graph) Register(img *image.Image, layerData archive.ArchiveReader) (err error)
```

Effectively, this means we have to write layers and some image at the same time. This is fairly uncomfortable. Ideally, we'd like to be able write the layer data at a separate time and then merge or link them when both are resolved.

We'll file another PR/proposal along these lines when the timing is right. I'll probably reference this at that time but let's leave closed for now, since it doesn't go into the proper detail.

**Comment by vbatts** [comment]
sounds good.
