### ISSUE TITLE
Docker gets killed by SIGPIPE

### ISSUE THREAD

**Issue by vincentbernat** [docker/docker#7087]
Hi!

From time to time, docker running on my host is getting killed by SIGPIPE. I am running it through systemd:

```
docker.io.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.io.service; enabled)
   Active: inactive (dead) since jeu. 2014-07-17 19:33:03 CEST; 34s ago
     Docs: http://docs.docker.io
 Main PID: 29636 (code=killed, signal=PIPE)

juil. 16 00:03:34 neo docker[29636]: [466c6525] -job images() = OK (0)
juil. 16 00:03:34 neo docker[29636]: 2014/07/16 00:03:34 GET /v1.12/containers/json
juil. 16 00:03:34 neo docker[29636]: [466c6525] +job containers()
juil. 16 00:03:34 neo docker[29636]: [466c6525] -job containers() = OK (0)
juil. 16 08:48:50 neo docker[29636]: 2014/07/16 08:48:50 GET /v1.12/images/json
juil. 16 08:48:50 neo docker[29636]: [466c6525] +job images()
juil. 16 08:48:51 neo docker[29636]: [466c6525] -job images() = OK (0)
juil. 16 08:48:51 neo docker[29636]: 2014/07/16 08:48:51 GET /v1.12/containers/json
juil. 16 08:48:51 neo docker[29636]: [466c6525] +job containers()
juil. 16 08:48:51 neo docker[29636]: [466c6525] -job containers() = OK (0)
```

This is a very old problem that I had in early versions. I never investigated it but since it is still here, I am opening this bug report. Usually, no containers are running.

However, note that I am using 1.0.0 (from Debian unstable). 1.1.0 is not packaged yet. I have already [reported the problem to Debian][1] but got no answer yet.

[1]: https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=docker.io;dist=unstable

**Comment by jfrazelle** [comment]
If this is a problem with the debian or ubuntu builds please file those with their bug tracker 

I am not able to reproduce to latest docker version

**Comment by stefwalter** [comment]
I've seen this issue on Fedora 21 with docker-io-1.5.0-1.fc21.x86_64

It doesn't seem to be Debian or Ubuntu specific. And yes:

```
$ systemctl show docker.service | grep PIPE
IgnoreSIGPIPE=yes
```

**Comment by stefwalter** [comment]
The status of the docker service seems to show that it just died somewhere without leaving a coherent message:

```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled)
   Active: inactive (dead) since Do 2015-03-05 16:45:55 UTC; 31s ago
     Docs: http://docs.docker.com
 Main PID: 25138 (code=killed, signal=PIPE)

Mär 05 16:41:55 stefw-node-1 docker[25138]: time="2015-03-05T16:41:55Z" level="info" msg="-job version() = OK (0)"
Mär 05 16:41:59 stefw-node-1 docker[25138]: time="2015-03-05T16:41:59Z" level="info" msg="GET /containers/json?all=1"
Mär 05 16:41:59 stefw-node-1 docker[25138]: time="2015-03-05T16:41:59Z" level="info" msg="+job containers()"
Mär 05 16:41:59 stefw-node-1 docker[25138]: time="2015-03-05T16:41:59Z" level="info" msg="-job containers() = OK (0)"
Mär 05 16:42:00 stefw-node-1 docker[25138]: time="2015-03-05T16:42:00Z" level="info" msg="GET /containers/json"
Mär 05 16:42:00 stefw-node-1 docker[25138]: time="2015-03-05T16:42:00Z" level="info" msg="+job containers()"
Mär 05 16:42:00 stefw-node-1 docker[25138]: time="2015-03-05T16:42:00Z" level="info" msg="-job containers() = OK (0)"
Mär 05 16:42:06 stefw-node-1 docker[25138]: time="2015-03-05T16:42:05Z" level="info" msg="GET /version"
Mär 05 16:42:06 stefw-node-1 docker[25138]: time="2015-03-05T16:42:05Z" level="info" msg="+job version()"
Mär 05 16:42:06 stefw-node-1 docker[25138]: time="2015-03-05T16:42:06Z" level="info" msg="-job version() = OK (0)"
```

**Comment by jimmidyson** [comment]
I have exactly the same issue as @stefwalter on Fedora 21 so agree it seems like a cross-distro issue.

@jfrazelle - could we re-open this issue please?

**Comment by LK4D4** [comment]
Any go program will die if it will try to write to same broken pipe ten times :) I wonder where this pipe is.

**Comment by sahus5** [comment]
I am also seeing this in many of my nodes in the cluster running docker 1.4.1 on SLES12
# service docker status
docker.service - Docker
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled)
   Active: inactive (dead) since Wed 2015-04-22 23:04:39 UTC; 22h ago
 Main PID: 64423 (code=killed, signal=PIPE)

Apr 22 23:00:10 murray-mustard docker[64423]: time="2015-04-22T23:00:07Z" level="info" msg="+job top(d9e419a69bac, )"
Apr 22 23:01:19 murray-mustard docker[64423]: time="2015-04-22T23:01:19Z" level="info" msg="GET /version"
Apr 22 23:01:19 murray-mustard docker[64423]: time="2015-04-22T23:01:19Z" level="info" msg="+job version()"
Apr 22 23:01:19 murray-mustard docker[64423]: time="2015-04-22T23:01:19Z" level="info" msg="-job version() = OK (0)"
Apr 22 23:02:27 murray-mustard docker[64423]: time="2015-04-22T23:02:27Z" level="info" msg="GET /containers/json?limit=0&all=1&since=&before=&size=0"
Apr 22 23:02:27 murray-mustard docker[64423]: time="2015-04-22T23:02:27Z" level="info" msg="+job containers()"
Apr 22 23:02:28 murray-mustard docker[64423]: time="2015-04-22T23:02:27Z" level="info" msg="-job containers() = OK (0)"
Apr 22 23:02:28 murray-mustard docker[64423]: time="2015-04-22T23:02:27Z" level="info" msg="GET /containers/d9e419a69bacb4de5e740da5b2750132b3bd00873247926aaff8db3d8534d432/json"
Apr 22 23:02:28 murray-mustard docker[64423]: time="2015-04-22T23:02:27Z" level="info" msg="+job container_inspect(d9e419a69bacb4de5e740da5b2750132b3bd00873247926aaff8db3d8534d432)"
Apr 22 23:02:28 murray-mustard docker[64423]: time="2015-04-22T23:02:27Z" level="info" msg="-job container_inspect(d9e419a69bacb4de5e740da5b2750132b3bd00873247926aaff8db3d8534d432) = OK (0)"
 # systemctl show docker.io.service | grep SIGPIPE
IgnoreSIGPIPE=yes

**Comment by jimmidyson** [comment]
Still seeing this with docker-io-1.6.0-2.git3eac457.fc21.x86_64 on Fedora 21.

```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled)
   Active: inactive (dead) since Tue 2015-05-05 21:19:24 UTC; 11h ago
     Docs: http://docs.docker.com
  Process: 783 ExecStart=/usr/bin/docker -d $OPTIONS $DOCKER_STORAGE_OPTIONS $DOCKER_NETWORK_OPTIONS $INSECURE_REGISTRY (code=killed, signal=PIPE)
 Main PID: 783 (code=killed, signal=PIPE)

May 05 21:18:19 jimmi-docker-2.osop.rhcloud.com docker[783]: time="2015-05-05T21:18:19Z" level=info msg="+job containers()"
May 05 21:18:19 jimmi-docker-2.osop.rhcloud.com docker[783]: time="2015-05-05T21:18:19Z" level=info msg="-job containers() = OK (0)"
May 05 21:18:19 jimmi-docker-2.osop.rhcloud.com docker[783]: time="2015-05-05T21:18:19Z" level=info msg="GET /containers/json"
May 05 21:18:19 jimmi-docker-2.osop.rhcloud.com docker[783]: time="2015-05-05T21:18:19Z" level=info msg="+job containers()"
May 05 21:18:19 jimmi-docker-2.osop.rhcloud.com docker[783]: time="2015-05-05T21:18:19Z" level=info msg="-job containers() = OK (0)"
May 05 21:18:19 jimmi-docker-2.osop.rhcloud.com docker[783]: time="2015-05-05T21:18:19Z" level=info msg="GET /containers/json"
May 05 21:18:19 jimmi-docker-2.osop.rhcloud.com docker[783]: time="2015-05-05T21:18:19Z" level=info msg="+job containers()"
May 05 21:18:19 jimmi-docker-2.osop.rhcloud.com docker[783]: time="2015-05-05T21:18:19Z" level=info msg="-job containers() = OK (0)"
May 05 21:18:19 jimmi-docker-2.osop.rhcloud.com docker[783]: time="2015-05-05T21:18:19Z" level=info msg="GET /containers/json"
May 05 21:19:24 jimmi-docker-2.osop.rhcloud.com docker[783]: time="2015-05-05T21:18:19Z" level=info msg="+job containers()"
```

**Comment by paulmenzel** [comment]
@jfrazelle, please reopen this issue as your reasoning for closing it has been proven to be incorrect.

**Comment by kbrwn** [comment]
I was able to reproduce this issue on CoreOS (766.4.0 and 815.0.0) and Ubuntu 15.04. With docker 1.7.1 and docker 1.8.2. Strace of the docker daemon reveals a SIGPIPE failure when the systemd-journald.service is killed. 

https://gist.github.com/kbrwn/2b9849e0e5a9823d6618

Seems like it must be related to this golang issue: https://github.com/golang/go/issues/11845

**Comment by the-nw1-group** [comment]
I'm seeing this also on Centos 7.2, since upgrading docker to 1.10.3. I couldn't find anything in the logs, and systemctl status docker shows:

```
[xyz@vm-nds-bld02 ~]$ systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─tls.conf
   Active: inactive (dead) since Wed 2016-03-23 09:28:08 GMT; 17min ago
     Docs: https://docs.docker.com
  Process: 17265 ExecStart=/usr/bin/docker daemon -D --tls=true --tlsverify=true --tlscacert=/etc/docker/ca.pem --tlscert=/etc/docker/server-cert.pem --tlskey=/etc/docker/server-key.pem -H=0.0.0.0:2376 (code=killed, signal=PIPE)
 Main PID: 17265 (code=killed, signal=PIPE)

Mar 23 07:27:31 vm-nds-bld02 docker[17265]: time="2016-03-23T07:27:31.903992478Z" level=debug msg="Lookup for ndspublicengagement_ui_0.0.547_autotest.: IP 172.18.0.2"
Mar 23 07:27:32 vm-nds-bld02 docker[17265]: time="2016-03-23T07:27:32.523597013Z" level=debug msg="Querying ext dns udp:10.102.16.75 for ndspublicengagement_ui_0.0.547_autotest.[28]"
Mar 23 07:27:32 vm-nds-bld02 docker[17265]: time="2016-03-23T07:27:32.523846584Z" level=debug msg="To resolve: ndspublicengagement_ui_0.0.547_autotest in "
Mar 23 07:27:32 vm-nds-bld02 docker[17265]: time="2016-03-23T07:27:32.523945911Z" level=debug msg="Lookup for ndspublicengagement_ui_0.0.547_autotest.: IP 172.18.0.2"
Mar 23 07:27:34 vm-nds-bld02 docker[17265]: time="2016-03-23T07:27:34.349977031Z" level=debug msg="Querying ext dns udp:10.102.16.75 for ndspublicengagement_ui_0.0.547_autotest.[28]"
Mar 23 07:27:34 vm-nds-bld02 docker[17265]: time="2016-03-23T07:27:34.350164918Z" level=debug msg="To resolve: ndspublicengagement_ui_0.0.547_autotest in "
Mar 23 07:27:34 vm-nds-bld02 docker[17265]: time="2016-03-23T07:27:34.350245256Z" level=debug msg="Lookup for ndspublicengagement_ui_0.0.547_autotest.: IP 172.18.0.2"
Mar 23 07:27:35 vm-nds-bld02 docker[17265]: time="2016-03-23T07:27:35.176180876Z" level=debug msg="Querying ext dns udp:10.102.16.75 for ndspublicengagement_ui_0.0.547_autotest.[28]"
Mar 23 07:27:35 vm-nds-bld02 docker[17265]: time="2016-03-23T07:27:35.176257669Z" level=debug msg="To resolve: ndspublicengagement_ui_0.0.547_autotest in "
Mar 23 07:27:35 vm-nds-bld02 docker[17265]: time="2016-03-23T07:27:35.176344040Z" level=debug msg="Lookup for ndspublicengagement_ui_0.0.547_autotest.: IP 172.18.0.2"
```
uname -a output:

```
Linux vm-nds-bld02 3.10.0-327.4.5.el7.x86_64 #1 SMP Mon Jan 25 22:07:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by martynd** [comment]
I know this comment is regarding k8s not docker, but the similarities between how it appears in the service status along with the go issue, I thought perhaps there is relevant overlap

K8s v1.3.6 on Cent7.1 
`● kube-apiserver.service - Kubernetes API Server
 Main PID: 10815 (code=killed, signal=PIPE)`

It also had ignore SIGPIPE set.

The reason for my instance at least was the OOMkiller:
[2927539.378591] Out of memory: Kill process 18298 (kube-apiserver) score 209 or sacrifice child
[2927539.379046] Killed process 18298 (kube-apiserver) total-vm:7145416kB, anon-rss:7050004kB, file-rss:0kB

Since i didnt see any system logs here, just the service or docker logs I thought I would throw it out there given the similar manner of manifestation and similar lack of anything

**Comment by elouanKeryell-Even** [comment]
I'm using docker 1.12 and I'm not witnessing this issue: I manually stopped journald, and docker didn't crash.
