### ISSUE TITLE
Proposal: Nested builds

### ISSUE THREAD

**Issue by shykes** [docker/docker#7115]
Some images require not just one base image, but the contents of multiple base images to be combined as part of the build process. A common example is an image with an elaborate build environment (base image #1), but a minimal runtime environment (base image #2) on top of which is added the binary output of the build (typically a very small set of binaries and libraries, or even a single static binary). See for example ["create lightweight containers with buildroot"](http://blog.docker.com/2013/06/create-light-weight-docker-containers-buildroot/) and ["create the smallest possible container"](http://blog.xebia.com/2014/07/04/create-the-smallest-possible-docker-container/)
## 1. New Dockerfile keywords: IN and PUBLISH

`IN` defines a scope in which a subset of a Dockerfile can be executed. The scope is like a new build, nested within the primary build. It is anchored in a directory of the primary build. For example:

`PUBLISH` changes the path of the filesystem tree to use as the root of the image at the end of the build. The default value is `/` (eg. "publish the entire filesystem tree"). If it is set to eg. `/foo/bar`, then the contents of `/foo/bar` is published as the root filesystem of the image. All filesystem contents outside of that directory are discarded at the end of the build.

```
FROM ubuntu

RUN apt-get install build-essentials
ADD . /src
RUN cd /src && make

IN /var/build {
    FROM busybox
    EXPOSE 80
    ENTRYPOINT /usr/local/bin/app
}

RUN cp /src/build/app /var/build/usr/local/bin/app

PUBLISH /var/build
```
### Behavior of RUN

When executing a `RUN` command in an inner build, the runtime uses the inner build directory as the sandbox to execute the command. So for example: `IN /foo { touch /hello.txt }` will create /foo/hello.txt.
### Behavior of ADD

When executing `ADD` in an inner build, the original source context does not change. In other words, `ADD . /dest` will always result in the same content being copied, regardless of where in the Dockerfile it is invoked. Note: the _destination_ of the `ADD` will change in a nested build, since the destination path is scoped to the current inner build.
### The outer build can access the inner build

Note that filesystem changes caused by the inner build are visible from the outer build. For example, `/usr/local/bin` was created by `FROM busybox` and is therefore accessible to the final RUN command in the build.
### Behavior of PUBLISH

Also note that `PUBLISH /var/build` causes the result of the inner build (the busybox image) to be published. Everything else (including the outer Ubuntu-based build environment) is discarded and not included in the image.

**Comment by TomasTomecek** [comment]
What's a status of this?

**Comment by s3ththompson** [comment]
Are you still driving this @shykes?

**Comment by ibuildthecloud** [comment]
The next time I have some free hacking time I'm going to implement this.  I'm really sick of my really fat docker images and trying to do hacks to make small ones.

**Comment by jfrazelle** [comment]
Talk to @tibor because he's hacking on this too :)

**Comment by ibuildthecloud** [comment]
@tibor any branch I can look at?

**Comment by ibuildthecloud** [comment]
@jfrazelle wait, is that @tibor or @tiborvass ?

**Comment by jfrazelle** [comment]
@tiborvass my bad

**Comment by tiborvass** [comment]
@ibuildthecloud there's this branch (not mine) which is pretty cool, it should solve your current immediate problems: #8021

What I'm currently doing is thinking about all the design implications of various proposals and trying to sketch something out that has an answer to many of the different use-cases. I will share a proposal in the coming weeks after 1.6 :)

Feel free to talk to me about it on IRC (preferably next week).

**Comment by Sirupsen** [comment]
@tiborvass really interested in this work as well. Looking forward to the proposal.

**Comment by muayyad-alsadi** [comment]
I find `IN ... PUBLISH ...` to be redundant compared to my proposal #15271 
which look like this `SWITCH_ROOT <other_image> <new_root> ...`
where `other_image` can be scratch or busybox
and `new_root` is the directory to be copied from the previous process before the reset (which typically would be the target/destination of the previous build processes)

since #13171 is merged (we can `cp` between containers), the process would be `cp <new_root>` from the build container to some local/host  tmp then dump and start over with the other_image (scratch or busybox in the example) as if it's a new Dockerfile with new `FROM` the only thing that is supposed to be inherited is the maintainer.

in python zen they "say flat is better than nested". there is no need for two instruction that marks two positions.

**Comment by alunduil** [comment]
+1 for @muayyad-alsadi 's idea.  It's far better to have a single transition point than a checkpoint/release unless there are other use cases that I missed while skimming this issue.

**Comment by muayyad-alsadi** [comment]
@alunduil  @jlhawn the only use case (I can think of) that my proposal won't cover is having a common code base the takes forever to build then we want to extract more than one image from the same codebase. think of it as libreoffice package, you build one package that takes hours to build then you get multiple sub-packages like write and impress ..etc.

a real world example would be having both server and client coming from same source package and you want to build an image for the server and another one for the client.

I do have a idea. My vision to Dockerfile is like Spec-file in RPM world, just like dockerfile but instead of building container images, it builds a binary package. RPM has the feature of subpackages it's syntax is like this
```
Name: foobar
%files server
# foobar-server goes here
%files client
# foobar-client goes here
%files -n python-foobar
# python-foobar goes here (not foobar-python-foobar)
```

So we need to build sub-images that is auto-prefixed with the tag like those
we have only one build root and multiple published images 

```
# the same tag passed to docker build
SWITCH_ROOT <other_image> <new_root> ...
# add -<tag-suffix> to the tag up to :
SWITCH_ROOT_N_PUBLISH <tag-suffix> <other_image> <new_root> ...
```

for example `docker build -t foobar:2.5` would result in `foobar:2.5`, `foobar-monitor:2.5` and `foobar-client:2.5`. I have concerns about having a syntax for a full tag because one building image for `eggs`  would end with image for `spam`

**Comment by alunduil** [comment]
I'm very biased (my opinion is that spec is a horrendous format and shouldn't be emulated).  I personally don't need or want the publish multiple images from one build but I do see the utility of it.  I really like the idea of two commands (one for just doing a shear and one for shear with multiple images).  This lets me keep my Dockerfile nice and simple while accomplishing the goal (out of published image builds) while having the flexibility to  do more if need be.

**Comment by jimmycuadra** [comment]
Any updates on this? Not being able to easily separate the build environment from the final image is one of the biggest pain points in Docker for me.

**Comment by jakirkham** [comment]
Also, would be really interested in seeing something like this or some variant. From my understanding, it would be very helpful for testing a layer without including artifacts from testing in the final tagged commit.

**Comment by netroby** [comment]
+1 , would like this feature. really useful.

**Comment by sleaze** [comment]
+1 for docker multiple inheritance functionality

**Comment by kolis** [comment]
:+1:

**Comment by ionelmc** [comment]
Does this https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax mean this proposal won't be implemented any time soon? (if ever)

**Comment by srikanthNutigattu** [comment]
The proposal need to split so that each can be discussed and closed independently.

**Comment by mercuriete** [comment]
:+1: 
Another use case...
Maven image to build java artifacts (jar)
then put this artifacts inside a smaller runtime image (java jre)

**Comment by hiroshi** [comment]
Hi, I'm working on [a small tool](https://github.com/hiroshi/cb). It can build small docker image with multiple steps. Some may feel it useful.

**Comment by graingert** [comment]
have a look at https://github.com/6si/shipwright

**Comment by fletcher91** [comment]
Since we're posting utilities, I've built one to [build minimal Golang images](https://github.com/fletcher91/docker-go) in two steps based on the scratch image

**Comment by xenoterracide** [comment]
I think multiple inheritance is a bad idea, see diamond problem, but composable traits a good one, I wrote on the multiple inheritance ticket how I think it could be accomplished safely syntactically.

that said glancing at this or the issue that I'm interested in is a syntactic sugar around temporary build layers for multiple && commands

for example this nasty piece of code
```
# oracle hackery that lies to it for it's bad installer
RUN mv /usr/bin/free /usr/bin/free.bak \
    && printf "#!/bin/sh\necho Swap - - 2048" > /usr/bin/free \
    && chmod +x /usr/bin/free \
    && mv /sbin/sysctl /sbin/sysctl.bak \
    && printf "#!/bin/sh" > /sbin/sysctl \
    && chmod +x /sbin/sysctl \
    && rpm --install /tmp/oracle-xe-$VERSION-1.0.x86_64.rpm \
    && rm /tmp/oracle-xe-$VERSION-1.0.x86_64.rpm* \
    && mv /usr/bin/free.bak /usr/bin/free \
    && mv /sbin/sysctl.bak /sbin/sysctl
```

the rpm command is actually expensive and takes a while when doing build, so if if something fails after it (while developing the image) I have to do the whole thing again. What'd be nice is a way to denote layers that are to be flattened, in the final build.

```
RUN mv ... 
FLT curl
FLT tar 
FLT rm tar
```

or something like that, where if say the tar failed (because I typoed the path) I wouldn't necessarily have to run the curl again, while developing the file. In the final image these would just look like one layer.

**Comment by AkihiroSuda** [comment]
Given that we have multistage build now, can we update the status of this "roadmap" issue?
cc @tonistiigi 
https://github.com/docker/docker/pull/32063 https://github.com/docker/docker/pull/31257

**Comment by tonistiigi** [comment]
Thanks for the ping @AkihiroSuda . Let's close this as #32063 that addresses this problem is merged.

**Comment by mercuriete** [comment]
thanks you very much
@tonistiigi 
I was waiting for this sooo long
:+1:
