### ISSUE TITLE
TLS must support CRLs

### ISSUE THREAD

**Issue by huslage** [docker/docker#7128]
There is currently no way to revoke a client certificate via the standard CRL mechanism. If you lose control of a client key, you must re-key your entire environment. This is untenable in even small environments and leads to trust and management issues in large ones.

**Comment by jfrazelle** [comment]
closing as this is the same as https://github.com/docker/docker/issues/6817 and we are trying to cleanup and merge things

**Comment by jbalonso** [comment]
I'm not convinced that this issue is the same as #6817. #6817 is more concerned with usability and the burdens of PKI management. I think can get around that concern with an appropriate application of puppet. This issue, however, is concerned with the fact that missing CRL support is a specific deficiency.
