### ISSUE TITLE
Freeze on Arch Linux on DigitalOcean

### ISSUE THREAD

**Issue by stuartpb** [docker/docker#7395]
Repro steps:

- Create a new Arch Linux droplet.
- Update it appropriately, heeding the advice from [here][1] and [here][2]:

[1]: https://www.archlinux.org/news/binaries-move-to-usrbin-requiring-update-intervention/
[2]: https://www.archlinux.org/news/deprecation-of-etcsysctlconf/

```
# pacman -Syu --ignore filesystem,bash
# pacman -S bash
# pacman -Su
# mv /etc/sysctl.conf.pacsave /etc/sysctl.d/99-sysctl.conf
```

- Install the dependencies for the plushu app ecosystem, then install plushu itself:

```
# pacman -S git docker nginx dnsutils
# systemctl enable docker nginx
# systemctl start docker nginx
# bash <(curl meta.sh/setup/plushu)
```

- Copy credentials to the plushu user and install the app ecosystem:

```
# cat .ssh/authorized_keys > ~plushu/.ssh/authorized_keys
# plushu plugins:install dokku
```

- Comment out the image removal in the buildstep plugin.
```
# sed -i 's/^docker rmi/#\0/' ~plushu/plugins/buildstep/hooks/build
```

- From a development machine, try pushing an app (I've been hitting the issue with https://github.com/stuart/meta.sh) and wait until you see:

```
remote: -----> Discovering process types
remote:        Procfile declares types -> web
```

At this point, every terminal on the server will be frozen until the droplet is hard-reset via the dashboard.

**Comment by jfrazelle** [comment]
is this still an issue?

**Comment by brauner** [comment]
Still an issue with `systemd-218` and `kernel-3.18.3`.

**Comment by jfrazelle** [comment]
@brauner is that with docker 1.5

**Comment by unclejack** [comment]
@LK4D4 Is this still relevant?

**Comment by thaJeztah** [comment]
closing because this went stale, but feel free to comment if this is still an issue

**Comment by tej24** [comment]
I am facing this issue again :  /usr/sbin/systemd-sysv-convert: line 62: /var/lib/systemd/sysv-convert/database: No such file or directory

with following software versions :  systemctl --version
systemd 219

docker --version 
Docker version 1.12.1, build 23cf638

kernel : 
Linux suotblrbld038g.hpeswlab.net 3.10.0-229.el7.x86_64 . Do help

**Comment by thaJeztah** [comment]
@tej24 I don't see how your case relates to this issue;

```
/usr/sbin/systemd-sysv-convert: line 62: /var/lib/systemd/sysv-convert/database: No such file or directory
```

That error originates from this script; https://build.opensuse.org/package/view_file/Base:System/systemd/systemd-sysv-convert, which is not part of the Docker packages.

Also be aware, that Docker 1.12.1 has reached end of life a long time ago.

If you run into issues on a current version of Docker, and suspect it's a bug, please open a new issue instead, and provide the information that's requested in the issue template.

I'm locking the conversation on this issue, because it's very old, and any issue you encounter likely isn't related to the original issue reported here.
