### ISSUE TITLE
Proposal: Expose an environment variable for port bindings inside the container

### ISSUE THREAD

**Issue by capoferro** [docker/docker#7421]
Our applications register themselves with service discovery upon startup. Currently, we have to statically define the port bindings on `docker run` via `-p 1234:45000` and then provide the port via an environment variable (`-e HOST_PORT:45000`) so the app can correctly register itself correctly.

It would be helpful to have that environment variable exposed inside the container automatically to indicate which port docker has selected for our container so we can rely on docker port allocation instead of having to rewrite port allocation as part of a tool external to docker.

It's likely that a container binds to many ports, so the envvars exposed should follow a scheme similar to how container link envvars are generated. In the above example (`-p 1234:45000`), the env var generated would be something like `HOST_PORT_1234`.

**Comment by flaviostutz** [comment]
+1
I really need this for registering container services on etcd from inside the container!
For example, if I have a bunch of NodeJS containers serving my Application (with elastic resizing) and I have a bunch of NGinx containers on its front balancing requests, I would like to have NGinx instances to lookup at etcd for available NodeJS containers (along with IP:port) so that NGinx instances could automatically reconfigure themselves for added/removed NodeJS containers during operations.

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/3778

**Comment by junneyang** [comment]
+1

**Comment by junneyang** [comment]
no solution for such a long time, really disappointed
