### ISSUE TITLE
Is there any Official roadmap for docker 32 bit containers on 32-bit H/W? Please suggest

### ISSUE THREAD

**Issue by newtonkishore** [docker/docker#7513]

**Comment by ggrandes** [comment]
+1 to i386 and ARM (like raspberry & banana pi); where a hypervisor is too heavy.

**Comment by dashohoxha** [comment]
@ggrandes All the 32bit projects (https://github.com/docker-32bit) have a script `build-image.sh` which builds the image for the i386 arch. If you want to build images for ARM you can fork them and make some minor changes (find **i386** and replace it with **arm**, find **32bit** and replace it with **ARM** or something similar).
Maybe you could also improve the scripts so that they take the architecture as a parameter.

**Comment by calavera** [comment]
Hi,

as expressed in #611, this is something that Docker is not going to officially pursue, at least for now. It's great that there is someone in the community leading this effort. Please refer to those repos if you need help or have feedback about it.

I'm closing this issue. Thanks again for letting us know about your use case.

**Comment by techtonik** [comment]
LXD worked for me better as a replacement for 32-bit Docker - https://github.com/lxc/lxd
