### ISSUE TITLE
Vim highlighting is not simple to install

### ISSUE THREAD

**Issue by grahamc** [docker/docker#7525]
Pathogen and Vundle etc expect the vim extensions to be at the root of the repository. I'd propose creating a `docker/docker-vim-syntax` repository or something for containing vim highlighting utilities.

**Comment by greg0ire** [comment]
How about creating [a subtree split repo](https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/) ?

**Comment by sobrinho** [comment]
I'm in favor of creating a new repo like docker/docker-vim because I don't want to clone the entire docker repository just to grab the plugin.

Keeping this repository on the main repository do not makes sense IMO because it would lead us to pull all unrelated changes from docker itself if we are just looking for updates on the plugin.

A 50/50 solution would be a [subtree split repo](https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/) like @greg0ire suggested.

That way everything would be kept at the main repository and for who want just to clone the plugin itself would be able using the second repository.

Although I see a dedicated repository a better choice since it would allow people related to vim to improve the plugin without all the noise that docker itself makes on the main repository like pull requests and issues.

Makes sense?

**Comment by hassan-k** [comment]
:+1: with @greg0ire and @sobrinho 

cloning the dntire docker repo just for vim syntax is a pain

**Comment by tianon** [comment]
I've just created https://github.com/tianon/vim-docker which is running in
a Jenkins job to do a "git filter-branch --prune-empty
--subdirectory-filter" on Docker's repo so that it always has the latest
changes. :+1:
