### ISSUE TITLE
Daemon fails to start, emits "invalid argument" message

### ISSUE THREAD

**Issue by sbward** [docker/docker#7585]
Environment:
```
$ uname -a
Linux ip-10-5-152-136 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

$ sudo docker version
Client version: 1.1.2
Client API version: 1.13
Go version (client): go1.2.1
Git commit (client): d84a070
2014/08/14 19:44:15 Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
```

Trying to start Docker:
```
$ sudo docker -d -D
2014/08/14 19:45:07 docker daemon: 1.1.2 d84a070; execdriver: native; graphdriver:
[cecc9e7f] +job serveapi(unix:///var/run/docker.sock)
[cecc9e7f] +job initserver()
[cecc9e7f.initserver()] Creating server
2014/08/14 19:45:07 Listening for HTTP on unix (/var/run/docker.sock)
[debug] server.go:1137 Registering GET, /images/search
[debug] server.go:1137 Registering GET, /images/{name:.*}/get
[debug] server.go:1137 Registering GET, /containers/{name:.*}/logs
[debug] server.go:1137 Registering GET, /_ping
[debug] server.go:1137 Registering GET, /version
[debug] server.go:1137 Registering GET, /images/json
[debug] server.go:1137 Registering GET, /images/{name:.*}/history
[debug] server.go:1137 Registering GET, /images/{name:.*}/json
[debug] server.go:1137 Registering GET, /containers/ps
[debug] server.go:1137 Registering GET, /containers/{name:.*}/changes
[debug] server.go:1137 Registering GET, /containers/{name:.*}/attach/ws
[debug] server.go:1137 Registering GET, /info
[debug] server.go:1137 Registering GET, /containers/json
[debug] server.go:1137 Registering GET, /containers/{name:.*}/json
[debug] server.go:1137 Registering GET, /containers/{name:.*}/top
[debug] server.go:1137 Registering GET, /events
[debug] server.go:1137 Registering GET, /images/viz
[debug] server.go:1137 Registering GET, /containers/{name:.*}/export
[debug] server.go:1137 Registering POST, /auth
[debug] server.go:1137 Registering POST, /containers/create
[debug] server.go:1137 Registering POST, /containers/{name:.*}/pause
[debug] server.go:1137 Registering POST, /containers/{name:.*}/unpause
[debug] server.go:1137 Registering POST, /containers/{name:.*}/restart
[debug] server.go:1137 Registering POST, /images/create
[debug] server.go:1137 Registering POST, /images/{name:.*}/tag
[debug] server.go:1137 Registering POST, /containers/{name:.*}/wait
[debug] server.go:1137 Registering POST, /containers/{name:.*}/resize
[debug] server.go:1137 Registering POST, /containers/{name:.*}/attach
[debug] server.go:1137 Registering POST, /build
[debug] server.go:1137 Registering POST, /images/{name:.*}/push
[debug] server.go:1137 Registering POST, /containers/{name:.*}/kill
[debug] server.go:1137 Registering POST, /containers/{name:.*}/start
[debug] server.go:1137 Registering POST, /containers/{name:.*}/copy
[debug] server.go:1137 Registering POST, /commit
[debug] server.go:1137 Registering POST, /images/load
[debug] server.go:1137 Registering POST, /containers/{name:.*}/stop
[debug] server.go:1137 Registering DELETE, /containers/{name:.*}
[debug] server.go:1137 Registering DELETE, /images/{name:.*}
[debug] server.go:1137 Registering OPTIONS,
[debug] server.go:1227 docker group found. gid: 111
[debug] deviceset.go:552 Generated prefix: docker-202:16-2752542
[debug] deviceset.go:555 Checking for existence of the pool 'docker-202:16-2752542-pool'
invalid argument
[cecc9e7f] -job initserver() = ERR (1)
2014/08/14 19:45:07 invalid argument
```

strace:
```
$ sudo strace -o docker.log docker -d -D
```
[**strace output gist**](https://gist.github.com/sbward/ddb509379f16a852fd2c)

In strace I see [these lines](https://gist.github.com/sbward/ddb509379f16a852fd2c#file-docker-log-L784-L785) which appear to be the source of the "invalid argument" message:
```
mount("", "/mnt/image/docker/devicemapper", "none", MS_PRIVATE, NULL) = -1 EINVAL (Invalid argument)
write(2, "invalid argument\n", 17)      = 17
```

Other relevant info:
- `/var/lib/docker` is a symlink to an ext4 mounted filesystem (AWS EBS), specifically `/mnt/image/docker` as you can see in the strace

**Comment by nagliyvred** [comment]
I have the same problem, but on Google compute engine instance. Happens consistently with btrfs volume.
docker just does not pull any images:
```
core4 docker # docker pull ubuntu
Pulling repository ubuntu
8eaa4ff06b53: Download complete 
511136ea3c5a: Download complete 
3b363fd9d7da: Download complete 
607c5d1cca71: Download complete 
f62feddc05dc: Download complete 
2015/01/13 09:39:22 open /var/lib/docker/repositories-btrfs: no such file or directory
```
and when I stop the service, I am getting the 
```
core4 docker # docker -d -D 
2015/01/13 09:39:59 docker daemon: 1.3.3 5dc1c5a; execdriver: native; graphdriver: 
[713c64ee] +job serveapi(unix:///var/run/docker.sock)
2015/01/13 09:39:59 invalid argument
```
Problem disappears when I run docker with -g in a different directory. However, this is very annoying since, I am running a cluster and every restart/new node is having this problem, until I manually intervene...

**Comment by discordianfish** [comment]
I just ran into the same problem on a PV instance-store ec2 instance with custom build AMI.
As @vbatts notes this is because docker mounts the dir as MS_PRIVATE which somehow fails:

    [pid  2524] mount("", "/mnt/aufs", "none", MS_PRIVATE, NULL) = -1 EINVAL (Invalid argument)

/mnt is ext3 formatted /dev/xvda2. After a reboot, docker starts again. This already happened on the first start of Docker, so no stale mounts etc around. I haven't seen that issue on any other AMI, so it seems like it's specific to that.

The AMI isn't special, it's a ubuntu 14.04 created by debootstrap with linux-virtual kernel package.

**Comment by kenbreeman** [comment]
Checking /proc/mounts I found old mount points for devicemapper. If you're mounting EBS or local storage while docker is running and docker isn't able to restart cleanly, then old mounts get stuck. Rebooting fixed the issue on instances where this happened.

Shutting down docker before mounting EBS or local storage prevented this from happening entirely.

**Comment by cpuguy83** [comment]
It looks like the only actionable item here may be to improve this error message so as to give a clue to the admin what may be wrong.
It may be possible to automatically unmount whatever might be there, but that may be dangerous.

**Comment by discordianfish** [comment]
So this happens on HVM instances as well. It seems that this was caused by upstart trying to start docker which failed because the TLS key was missing. Those rapid restarts seem to bring the system into that state. I've checked /proc/mounts and also saw a old mount point but aufs in my case.
I assume Docker somehow mounts aufs/, then errors out because of the missing tls key and doesn't clean up / unmount properly. Next time it starts, it fails to (re)mount with 'invalid argument'.
I couldn't reproduce this on my laptop, so it might be still specific to the environment but after making sure I start Docker only after the tls key was written, things look good now.

**Comment by cpuguy83** [comment]
@fish Thanks for the extra info!
I think (hope) this all maybe related to the daemon not cleanly shutting down under certain circumstances, hence the dangling mounts.
See #11211 to at least address when that is the cause of the issue.

Would be great if some people can test this.
