### ISSUE TITLE
Proposal: Add SSH transport protocol

### ISSUE THREAD

**Issue by zedtux** [docker/docker#7650]
As I have already describe in the [docker-registry repository issue #531](https://github.com/docker/docker-registry/issues/531) I'd like to authenticate users with their SSH keys like is doing Git today.

This sounds really natural as Docker is already using the commits like in Git.

Pushing with Docker, using SSH, would then looks like the following:

    docker push docker@docker.zedroot.org:zedtux/my-docker-image

This needs to have a SSH key management in order order to add/update/remove them and then docker push should accept this new protocol.

**Comment by calavera** [comment]
Closing this issue. Thanks for reaching out, but it's not among our goals right now to tackle this.

**Comment by foxx** [comment]
I've gotta say, classifying this as not being an important goal is a pretty damning statement of your security priorities.

**Comment by akomm** [comment]
This is actually something very important. We got real world examples, some of which were mentioned here, why it is so. And the answer is a one-liner & close? Since when is a "not out goal right now" a close reason at all? Tag is if you think its low priority. Weird close-policies tend to generate assumption about reason behind them.

**Comment by theasp** [comment]
You can tunnel access to the registry over SSH without any change to docker.  The following will connect to a remote machine, and create a tunnel back to `localhost:5000` that you can pull over:
```
ssh other-docker-node -R 5000:127.0.0.1:5000 docker pull localhost:5000/your/image
```

You can use `-L` to make a tunnel you can access locally, as long as it's running.:
```
ssh other-docker-node -L 5000:127.0.0.1:5000  -v -D
```

**Comment by akomm** [comment]
@theasp Thank you, but I'm already doing it that way. 

It is not the same as transporting & communicating via SSH. While you already authenticate using key you also need to authenticate to docker's own system, because there is only an authorization, but no authentication plugin support / API. From HTTP point of view this makes sense, because to safely authenticate on application level, you first need a secure connection. Then why do authentication on application level, when you can do so in one step while ensuring the secured connection?

The thing is just - and because we have live examples of why I skip the explanation - ssh can simplify the usage of docker and reduce a lot of overhead, make it more lightweight. See an example of gitolite. It is a nice example of plain custom shell and key authentication which enables you to manage and authorize operations on repository for different user (via authorized keys & shell init command bound to those keys) using one non-sudo/adm local OS user. 

I understand that based on the current transport implementation of docker, SSH would make a lot of implication and changes needed. And that is why I understand that it can not be provided with a single  "snap". I just don't understand why this feature request is closed. It is still relevant - maybe not today, but tomorrow.

**Comment by justincormack** [comment]
I don't think having this issue open or closed makes much difference, as the issue for registry support for ssh is still open, and for this use case of ssh that would have to be implemented first. If that gets done then we can reopen this. There are other potential uses for ssh with docker, but this issue is not requesting those, so it is dependent on registry support.

**Comment by akomm** [comment]
@justincormack the registry projects references back to this project with the argument, that it simply relies on the transport of docker.

**Comment by xanview** [comment]
+1

**Comment by cfriedt** [comment]
+1

**Comment by zedtux** [comment]
I actually don't see the point of closing it, keeping it on open means it is on the radar (even if you don't consider it important ... :flushed:).

What is the cost of keeping it open? People having visibility on it can vote, is that a problem?
