### ISSUE TITLE
Proposal: SLINK instruction for Dockerfile

### ISSUE THREAD

**Issue by cmfatih** [docker/docker#7654]
Some files in images are environment specific. Even some files are only required while building process. A symbolic link feature would be nice when we don't want to ADD/COPY files. Basically it is like `docker run -v ` but for files and during building process. Here are some examples;

```
FROM ...
MAINTAINER ...

SLINK .npmrc ~/.npmrc
SLINK id_rsa ~/.ssh/id_rsa
SLINK ssh_config ~/.ssh/config

RUN git clone private-repo-url    // no prompt due SLINK ~/.ssh/*
RUN npm login                     // no prompt due SLINK .npmrc
RUN npm install private-module
RUN ...
```

`docker build -t="my-awesome-app" .` // Successfully build in box 1

`docker run my-awesome-app /bin/cat ~/.npmrc" .` // File not found in box 2

**Comment by WhisperingChaos** [comment]
This is a good idea, as long as the symbolic link:
+ remains within the initial build context or extended build context - intermediate state (path/files) derived from the original build context 
+ and writes to anywhere within the symbolically linked location cause the build to fail.

It can be used for secrets, and to improve the speed of the build by averting unnecessary physical copying.

There's currently an issue regarding [ONBUILD triggers](https://docs.docker.com/reference/builder/#onbuild), as these are immediately executed when FROM is run, before the first Docker file command after the FROM.  Therefore, the SLINK command would not be available to these ONBUILD trigger statements.  There is a proposal: #8240 to permit their interception, however, given the usefulness of this feature which would encourage its frequent application,  interception would probably become the norm instead of the exception, something that should be avoided.

I too originally thought you were accessing files outside the build context and put together a similar idea found here: #12072 to create a "Local Build Context" a build context specific to the needs of FROM statement and its associated Dockerfile commands that supports ONBUILD triggers without requiring interception.  I'll include a reference to this Proposal and detail the differences between them.

Although I'm sure it can be solved, can you explain how SLINK would trip the image cache especially in a deep directory structure?  Thanks.

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
