### ISSUE TITLE
Proposal: Add --plugin flag instead of manually bind-mounting socket

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#7841]
Basically, a docker plugin is essentially this:

docker run -d -v /var/run/docker.sock:/var/run/docker.sock cpuguy83/something_crazy
And if you want to share that with people, in the instructions we are telling them to do the same thing, but not everyone necessarily uses the unix socket, and even if they do it may not be in this location.

In addition, for such a common pattern this is pretty silly.

Instead I propose that we can automatically bind mount a socket if requested using --plugin from the CLI.

docker run -d --plugin cpuguy83/something_crazy
This would have a default path for placing the socket in the container, but could potentially be customizable.

**Comment by crosbymichael** [comment]
I don't like this at all right now.  We have a flag for manually bind mounting files.  Explicit is better than implicit and we don't want to define a flag right now that sets the tone for future features.  What if two months down the road plugins are not containers that bind mount in the socket?  We are screwed because we have a flag like this.  

Lets not make any changes like this until we have requirements for what a plugin is.  If you want the socket mounted just use `-v`.  There is no reason to abstract this away.
