### ISSUE TITLE
fork/exec /var/lib/docker/init/dockerinit-1.2.0

### ISSUE THREAD

**Issue by zyndiecate** [docker/docker#7863]
hey there … I am on 423.0.0 alpha and just want to start a container … I get `fork/exec /var/lib/docker/init/dockerinit-1.2.0: no such file or directory` … somebody knows about that? thanks

```bash
$ docker run -ti ubuntu /bin/bash
Unable to find image 'ubuntu' locally
Pulling repository ubuntu
c4ff7513909d: Download complete
511136ea3c5a: Download complete
1c9383292a8f: Download complete
9942dd43ff21: Download complete
d92c3c92fa73: Download complete
0ea0d582fd90: Download complete
cc58e55aa5a5: Download complete
2014/09/03 13:55:06 Error response from daemon: Cannot start container bf1ac9b018005bbc7f619ed1ea2982b44dc491141d6aa670dbbf0e8967eaef4f: fork/exec /var/lib/docker/init/dockerinit-1.2.0: no such file or directory
```

**Comment by unclejack** [comment]
This issue was filed against an old version of Docker and I haven't seen this error at all on any of the systems I've been testing on (Ubuntu, Debian, Fedora, CentOS).

I'm going to close this issue now. Please feel free to comment on this issue if you happen to run into this again. Please make sure to provide the full output of `docker info`, `docker version` and `uname -a`.
