### ISSUE TITLE
--dns and--dns-search should behave as expected when using --net=host

### ISSUE THREAD

**Issue by lexinator** [docker/docker#7936]
now that /etc/resolv.conf is changeable when using --net=host, command options --dns-search and --dns should behave as expected.

**Comment by jfrazelle** [comment]
ping @estesp resolv.conf :)

**Comment by estesp** [comment]
Yes, it's possible now given `resolv.conf` with `--net=host` is a copy of the host bind-mounted into the container.  The open design questions for command-line options + `--net=host` are:
 - do you merge in the servers from command line or append them?
 - Appending them may make them useless (glibc resolver only will use first 2 or maybe 3?)
 - do you add search domains or merge them with existing?

white-belt is fine.. I can help someone with the implementation if necessary

**Comment by superseb** [comment]
#dibs

**Comment by superseb** [comment]
Okay, so a lot has happened. For now, this is the current state:
```
$ docker run --dns=4.4.4.4 --net=host -t -i centos:centos6 sh
docker: Conflicting options: --net=host can't be used with --dns. This configuration is invalid.. See 'docker run --help'.
```
```
$ docker run --dns-search=example.com -t -i --net=host centos:centos6 sh
sh-4.1# cat /etc/resolv.conf 
nameserver 10.0.2.3
```
@estesp Do we need to discuss this design? Why not use the same logic already present? Or am I missing something here?

**Comment by estesp** [comment]
Right now as you can see, for `--dns` we are showing a conflict, and for `--dns-search` we are not reporting an issue, but we also aren't adding it to the container's DNS config either.  So, given it doesn't **have** to conflict anymore (because resolv.conf is changeable in the container), the steps to a PR that can be reviewed (design first, then code, as it changes current behavior):
 1. Remove the conflicting option on `--dns` and `--net=host`
 2. Modify the resolv.conf creation code to not preclude handling dns and dns-search command line options when  `--net=host` is set
 3. Add tests for `--net=host` + dns options and validate resulting `/etc/resolv.conf` in the container
 4. Finally, we should consider whether we need any "warn" output that the user has specified net host, but is modifying settings to deviate from host network config (adding resolvers, changing search config)

If the design is rejected to allow the behavior change, then we have to at least make the conflicting options consistent and make `--dns-search` also conflict with `--net=host`

Let me know if you have any questions about any of the above, or catch any of us on irc on #docker-dev if you need help.

**Comment by sprohaska** [comment]
I found it confusing that Docker seems to remove `nameserver 127.0.0.1` from `resolv.conf` even in `--net=host` mode. Removing it makes sense for the other `--net` modes.  But for `--net=host`, it does not make sense to me, because the container is able to reach the host's 127.0.0.1.

**Comment by thaJeztah** [comment]
@sprohaska could you give the current 1.10 release candidate a try? Using 127.0.0.1 as DNS should now be possible in 1.10, see https://github.com/docker/docker/issues/15819

**Comment by alexlovescoding** [comment]
#dibs

**Comment by cpuguy83** [comment]
This is resolved.
Thanks!
