### ISSUE TITLE
USER in Dockerfile doesn't inherit their own environment

### ISSUE THREAD

**Issue by rgbkrk** [docker/docker#7961]
If a user is created and used for the launching process, their environment variables don't get set in the way `su -` would:

```
22:26:31 rgbkrk@metallic ~/user_example$ sudo docker build -t userdemo .
Sending build context to Docker daemon  2.56 kB
Sending build context to Docker daemon
Step 0 : FROM ubuntu:14.04
 ---> 826544226fdc
Step 1 : RUN useradd -m -s /bin/bash steve
 ---> Running in 1f69672d61de
 ---> 8851c00a531c
Removing intermediate container 1f69672d61de
Step 2 : USER steve
 ---> Running in 53e69ed6a84e
 ---> 611f77883000
Removing intermediate container 53e69ed6a84e
Step 3 : CMD ["/bin/bash"]
 ---> Running in 1f4a4760c313
 ---> 915ae9a8d061
Removing intermediate container 1f4a4760c313
Successfully built 915ae9a8d061
22:26:35 rgbkrk@metallic ~/user_example$ sudo docker run -it userdemo
steve@07f10823a54c:/$ env
HOSTNAME=07f10823a54c
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
SHLVL=1
HOME=/
_=/usr/bin/env
steve@07f10823a54c:/$ whoami
steve
```

Ref: https://github.com/ipython/docker-notebook/issues/12

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.

**Comment by rgbkrk** [comment]
Well that's a good ROADMAP to read Jess, thanks!

On the other hand, this was an issue about the current implementation of the `USER` keyword. :confused: 

Looking forward to the builder being more extensible - that sounds fun and you all design great APIs. :tada:

**Comment by Buddikawidu** [comment]
Hi all, 

could you  help me out, The issue is i need to have main docker file , all the projects that creates that needed to inherit that main docker file, example main docker file contents below 

FROM microsoft/aspnetcore:1.1
ARG source
WORKDIR /app
EXPOSE 80
COPY ${source:-obj/Docker/publish} .
ENTRYPOINT ["dotnet", "DockerSampleInherit.dll"]

child project docker file contains only the 

RUN dir c:\

when project get run you needed to get main docker file content as well , the question is how can i add these reference in to child docker file,
