### ISSUE TITLE
Allow mounting directories from other image

### ISSUE THREAD

**Issue by mitar** [docker/docker#8305]
I would like to run a container and mount into the container a directory from another image. Instead of volume which would create an empty directory, I would like to mount the files are already in the other image.

**Comment by thaJeztah** [comment]
@mitar is this still an issue with you? Exposing data that's in an image via volumes and sharing that with another container works for me;

```bash

# Build an image with "data" inside
cat << EOF > ./Dockerfile
FROM debian:latest
RUN mkdir /data && echo "HELLO WORLD!" > /data/hello-world.txt
CMD cat /data/hello-world.txt
EOF

docker build -t imagewithdata .

# Run/create the data-container and expose the 
# data-directory as "volume"
docker run --name ihavedata -v /data imagewithdata

# Use the volume inside another container
docker run --rm --volumes-from=ihavedata --name iusedata debian cat /data/hello-world.txt

# Cleanup :)
docker rm -v ihavedata
docker rmi imagewithdata:latest
rm Dockerfile

```

**Comment by mitar** [comment]
Oh, this is because I am not mounting an outside directory into the container as a data, but just exposing a directory as a data? Interesting.

**Comment by thaJeztah** [comment]
@mitar correct (if I understand your question correctly); when specifying a "volume", and the container has files on that location, docker will copy the files to the volume.

Here, docker will create a volume and copy everything that's in "/data" inside the container to the volume;

    docker run -v /data something

However, when using a "bind-mount" (i.e., specify a directory on the *host* to use as a volume), docker will not do that, but use the files that are present in the "host" directory  as content for the volume.

In this example, al files that are present in `/some/path/on/the/host` are mounted in the `/data` directory in the container. Everything that is in the `/data` directory in the container is still there, but not visible, because it's "masked" by the mounted directory:

    docker run -v /some/path/on/the/host:/data something


I hope this answers your question. If you have more questions, please check the #docker IRC channel, there are lots of people there to help you further.

**Comment by mitar** [comment]
That perfectly explained things. I was used to bind-mount volumes so I did not know about this second behavior. Thanks.
