### ISSUE TITLE
Proposal: docker rmi --rm-containers to auto remove containers for image

### ISSUE THREAD

**Issue by tywkeene** [docker/docker#8585]
Hi everyone,
When I try to delete an image that still has containers using it, I get this:

`Error response from daemon: Conflict, cannot delete f4c521651b8e because the container 01578dc0561d is using it, use -f to force`

The current behavior of removing each container by hand, then removing the image in question is rather tedious, and, if I am not mistaken, using the `-f` option would leave these containers hanging.

I propose a command line option to force the stopping and removal of all containers when trying to remove an image, basically deleting the whole 'world', so to speak. (Unless I am sorely mistaken and there already exists such a feature)

i.e `docker rmi --rm-containers [image id]`

Which would go through and stop/delete all containers holding this image from being deleted.

I don't have much go experience but I'd like to take this chance to at least try and help get this implemented if anyone would like the help.

Thanks for the input,
Cheers.

**Comment by thaJeztah** [comment]
Giving this some more thought, I don't think we should implement this; removing random containers when removing an image is not logical; if you want to remove all images and containers, first remove the containers, then remove dangling images (or all images), e.g.

```bash
docker rm -fv $(docker ps -aq)
docker rmi $(docker images -aq --filter dangling=true)
```

Note that we will be working on improving data management (removing unused images, containers, volumes), which is tracked by https://github.com/docker/docker/issues/22871

I'll close this issue, because this is not the right solution, but thanks for suggesting, and subscribe to the linked issue to stay informed on updates :+1:

**Comment by rixed** [comment]
Do I understand probably that instead of removing "random" containers you suggest removing all of them with `docker rm -fv $(docker ps -aq)` ?

**Comment by thaJeztah** [comment]
@rixed agreed my example is still "random"; main point is that removing containers because they use an image will be a sliding slope; there's other resources that would come next; secrets, volumes, networks, configs, etc.
