### ISSUE TITLE
deny "attach" to container

### ISSUE THREAD

**Issue by andrea-spoldi** [docker/docker#8820]
Hi, 
this one is more a feature request I think, but probably it's already possibile in some other ways.

Let's say I have a container w/out ssh access, and I want to prevent also "docker attach <container-id>" to it, so that no one can access my code.

Is this possibile ? 
Thank you

AS

**Comment by unclejack** [comment]
This isn't something to be implemented right now. It'll be possible to do various things like this when support for ACLs is added. However, even then, if the particular individual has access to the host, they've got access to everything - they can dump memory, they can copy files and can do pretty much what they want.

I'm going to close this issue now since it's not something to be addressed right now and the future ACLs will most likely cover this, and much more.
