### ISSUE TITLE
Tracker: support building with gccgo

### ISSUE THREAD

**Issue by mwhudson** [docker/docker#9207]
Docker does not currently build with gccgo, which is a problem if you are interested in docker on platforms that are not currently supported by the native/'gc' toolchain. 

One sticking point is the use of the native toolchain's linker's -X flag, which gccgo has no equivalent for.

Otherwise, it's mostly just about adding bundles that invoke the go tool with -compiler gccgo etc.

**Comment by vbatts** [comment]
@hqhq This tracker is less about any specific issue, but intended to be a place to review overall progress on the goal of having first support for gccgo with docker. This will take work from the gccgo community and within the docker project too.

**Comment by duglin** [comment]
While we continue to work on getting gcc-go and cross-compilation to work, I was wondering what people thought about native compiles?  One of the issues we're running into is that some people are not comfortable is the reliability of cross-compilations and would really prefer if (at least some) of the official Docker binaries were built natively on the target platform.  What do people think about modifying the Docker CI pipeline so that it allows for native builds to be done for whichever platforms we decide should use that mechanism rather than cross compilation ?

@vbatts if you think this is off-topic let me know and I'll take it elsewhere, but I think even for native compiles we'll still need gcc-go support so it seemed related

**Comment by brahmaroutu** [comment]
@unclejack  We have successful native compilation on ppc64 platform and would like to know what is required to add this platform to Docker CI pipeline to build the binaries. I am willing to work on any modifications/customizations required to the CI pipeline.

**Comment by unclejack** [comment]
@brahmaroutu Do you have a branch I can look at?

**Comment by brahmaroutu** [comment]
Yes, Please check this out. https://github.com/brahmaroutu/docker/tree/gccgo_power I also have private branches for platform specific busybox image, etc. But first I would like to add the gccgo compile step to project/make/binary

**Comment by brahmaroutu** [comment]
The above PR is one for the following steps I would like to introduce.
1. enable gccgo into the build
2. build gccgo natively as a image on the platform. Following url has a way to build gccgo-image with gccgo tools for go1.3.3 https://github.com/brahmaroutu/power_docker/tree/master/gccgo-image
I am updating it for go1.4
3. customize the docker file to handle multiple paths so that appropriate tools are installed to trigger the build.
4. May require base image like busybox to be built on the platform.

**Comment by brahmaroutu** [comment]
For quick test on x86 I have a experimental branch https://github.com/brahmaroutu/docker/compare/gccgo_x86 that builds docker binary along with gccgo and gccgo tools using project/gccgo-image/Dockerfile.

**Comment by inatatsu** [comment]
GCCGO ignores a "constructor" C-function in a subdirectory. `docker exec` fails due to this problem since `init()` in [nsenter.go](https://github.com/docker/docker/blob/master/vendor/src/github.com/docker/libcontainer/namespaces/nsenter/nsenter.go) is not linked. [A workaround](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65134) is suggested on GCC Bugzilla.

**Comment by vbatts** [comment]
```
vbatts@noyee ~/src/docker/libcontainer/nsenter (vbatts-gccgo_constructor) $ go build -compiler gccgo
vbatts@noyee ~/src/docker/libcontainer/nsenter (vbatts-gccgo_constructor) $ sudo go test -compiler gccgo
PASS
ok      _/home/vbatts/src/docker/libcontainer/nsenter   0.302s
```

**Comment by inatatsu** [comment]
@vbatts Great! Thanks.

**Comment by inph** [comment]
The removing -X flag patch https://github.com/docker/docker/commit/6871b9b16afe46e7566ac2937246b4a64be97269 breaks building the dynbinary due to the removal of INITPATH from `project/make/dynbinary` and ld being unable to find libs.

Adding the following to `project/make/dynbinary`: 
`export LDFLAGS_STATIC_DOCKER="-X $DOCKER_PKG/dockerversion.INITPATH \"$DOCKER_INITPATH\""`

Fixes the dynbinary build on gc.

**Comment by rhatdan** [comment]
I confirm adding the export line on Fedora fixes our problem.

**Comment by tianon** [comment]
With https://github.com/docker/docker/pull/10951, the `dynbinary` problem should be fixed.

**Comment by inatatsu** [comment]
A static binary built with GCCGO has to dynamically link GLIBC to avoid [potential segmentation fault at DNS lookup](https://sourceware.org/bugzilla/show_bug.cgi?id=10652), since [GCCGO cannot enable the "netgo" build tag](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=63731#c28).

**Comment by inatatsu** [comment]
#12181 is to resolve [the issue](https://github.com/docker/docker/issues/9207#issuecomment-77994720) of `netgo`.

**Comment by brahmaroutu** [comment]
Hi Tatsushi,
    Thanks Tatsushi. I have already tested this based on Lynn's
recommendation. Only reason I am holding off is to make sure that this code
is in fact in the main gccgo branch. I see the code review on Lynn's patch
got a LGTM does that mean that we have the netgo library patch accepted?
Are we ready to push code changes to Docker code?
regards,
Srini

**Comment by laboger** [comment]
If you pull the latest source from gcc trunk, this change is there.

**Comment by brahmaroutu** [comment]
thanks, I will try it today.

**Comment by icecrime** [comment]
This is fixed, as we have been building with gccgo as part of our CI jobs for several months now. Thanks all!
