### ISSUE TITLE
can not replace a old image with a new one

### ISSUE THREAD

**Issue by gansteed** [docker/docker#9276]
after I update a image, those containers depend on old images can not move to new images. I think docker should have this feature, because container is build on image, it's just a layer.  so I wonder can I replace the old image with a new one and do not need rebuild the container?

**Comment by unclejack** [comment]
@gansteed This question has been asked and answered on this issue tracker before. This can't be done easily because there's no easy way to reconcile changes done in the base image with the ones done in layers above and in the container.

There's one thing you can do quite easily: make sure the actual data of your app/container resides within volumes (or on a bind mounted volume), stop the old container and start a new container using an updated image with `--volumes-from` from the old container. This is pretty much what you're asking for, except it's done by using another workflow. This is the recommended way to achieve what you want.

I'm going to close this issue now since it's been answered. Please feel free to comment.
