### ISSUE TITLE
ADD does not support FTP URLs

### ISSUE THREAD

**Issue by dtenenba** [docker/docker#9314]
Hi,

I would like to use the ADD command in a Dockerfile with an FTP url, but it doesn't appear to work.

My Dockerfile has this line in it:

    ADD ftp://ftp.stat.math.ethz.ch/Software/R/R-devel.tar.gz /tmp/R-source/

And when I attempt to build it, I get:

    Step 5 : ADD ftp://ftp.stat.math.ethz.ch/Software/R/R-devel.tar.gz /tmp/R-source/

    2014/11/24 10:49:46 ftp://ftp.stat.math.ethz.ch/Software/R/R-devel.tar.gz: no such file or directory

Unfortunately, the tarball I am trying to download is not available at an HTTP url. Can ADD be modified to support FTP URLs?

I am aware that I could use `RUN curl...` to download from this URL, but I want the behavior of ADD which checks to see if the URL contents have changed and invalidates the cache if they have.

**Comment by bw2** [comment]
+1

**Comment by thaJeztah** [comment]
We haven't seen more requests for this, so I'm closing this as it's not a priority

**Comment by hznut** [comment]
+1 Need support for FTP and sambashare

**Comment by nick4fake** [comment]
+1

**Comment by GeekLogan** [comment]
+1

**Comment by ahwagner** [comment]
Hey @thaJeztah, are we supposed to make additional requests to re-open this issue by adding comments? Or is subscribing to this page as @GordonTheTurtle suggests enough?

Either way, +1.

**Comment by thaJeztah** [comment]
@ahwagner it would help if you could describe your use case; t.b.h., we're in doubt if we want to add more complexity to `ADD`, there's already a lot of things it does. Adding support for ftp would probably require implementing a whole ftp client (what about sftp, etc etc)

**Comment by justincormack** [comment]
Also most providers are in the process of phasing out anonymous FTP support.


On 27 Feb 2017 13:30, "Sebastiaan van Stijn" <notifications@github.com>
wrote:

@ahwagner <https://github.com/ahwagner> it would help if you could describe
your use case; t.b.h., we're in doubt if we want to add more complexity to
ADD, there's already a lot of things it does. Adding support for ftp would
probably require implementing a whole ftp client (what about sftp, etc etc)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/docker/docker/issues/9314#issuecomment-282860181>, or mute
the thread

**Comment by GeekLogan** [comment]
@thaJeztah while I can not speak for others, but my primary desire for this feature is rooted in the ability to pull public scientific data into Docker containers at deploy-time. Much of it is stored in public FTP servers which have not/will not be updated to another storage scheme in the foreseeable future.

Example:
https://www.ncbi.nlm.nih.gov/books/NBK158899/

**Comment by thaJeztah** [comment]
If it's at deploy time, adding support for ftp to `ADD` won't be of much help, as that's only during _build_

**Comment by pgcalixto** [comment]
+1 for FTP support.

I was trying to download a file with FTP using `ADD`, during build time, and I couldn't.

Also, some images, like [Ubuntu:16.04](https://hub.docker.com/_/ubuntu/) (the one I'm using), do **not** have cURL installed. So, instead of just adding one file to Docker's `ADD` command:

```Dockerfile
ADD http-file-01 \
    http-file-02 \
    ...
    ftp-file \
    ...
    <path>
```

I'd have to add one more Docker command, adding one more layer to the image, and increasing the size of the image for installing cURL:

```Dockerfile
RUN apt-get update \
 && apt-get install curl \
 && curl -u user:password 'ftp://host/file' -o myfile
```
