### ISSUE TITLE
Pulling image "hello-world" (or any other image) terminates with an "unexpected EOF" error

### ISSUE THREAD

**Issue by jenny11** [docker/docker#9434]
I'm new to Docker and I face this issue when I'm connected to a VPN using CISCO AnyConnect.

When I do a "docker run hello-world", it terminates with an "unexpected EOF" error. After which no docker commands run and I get a "Is Docker daemon running" error

While on VPN, if I open "https://index.docker.io/v1/repositories/hello-world/images" in the browser. It shows up a page containing some checksum values. Which seems like its working correctly.

Oh, and this earlier worked on a VPN. It stopped suddenly today (could it be something to do with mirroring)

Host machine: Windows 7. Virtual Box: Linux64bit
Docker version:1.2.0

**Comment by rlegrand** [comment]
Hello,

I have the same error but on widows:
<code>
FATA[0060] An error occurred trying to connect: Get https://192.168.59.103:2376/v1.18/containers/json: unexpected EOF
</code>
I also have Cisco AnyConnect but don't know if it's related because the problem also occurs when the cisco service is down.

Adding a static route seems to be the easier way to solve the problem on mac os:
<code>
sudo route -nv add -net 192.168.56 -interface vboxnet0
</code>

But I'm not comfortable at all with network config, and don't know how to achieve this on windows.
Any idea/suggestion?
