### ISSUE TITLE
Cannot start container ... fork/exec /var/lib/docker/init/dockerinit-1.3.2: invalid argument

### ISSUE THREAD

**Issue by redirect11** [docker/docker#9473]
I'm trying to install docker on a Joyent VPS. We have a ubuntu 12.04 (2.4.2) image from joyent that come with a custom 3.8.6  kernel (3.8.6-joyent-ubuntu-12-opt). No problem installing but, when i try to run:

```
sudo docker run -i -t ubuntu /bin/bash
```

i get this error:
```
2014/12/03 10:13:16 Error response from daemon: Cannot start container f640794402711820dcbb52a046714aff0e630dd6d709c2403faa687a61588644: fork/exec /var/lib/docker/init/dockerinit-1.3.2: invalid argument
```

but i don't know how to debug the problem.

Thanks in advance

**Comment by unclejack** [comment]
@redirect11 That kernel has been deprecated and is no longer on `https://www.kernel.org` (and hasn't been there for a long time). Please use official kernels provided by the Linux distribution you're using.

The following kernels are used for these distributions:
Ubuntu 12.04 - please install and use linux-generic-lts-trusty
Ubuntu 14.04 - the default linux-image-generic package should be good
Debian 7 - please install a kernel from the backports
Debian 8 - please use the provided kernel or a newer packaged version

We don't support kernels provided by service providers. That's not because we're being mean to the service providers or to the clients of those service providers, it's because there are way too many providers to be able to support each and every configuration.
