### ISSUE TITLE
Docker should observe --insecure-registry with authentication

### ISSUE THREAD

**Issue by phemmer** [docker/docker#9570]
docker refuses to authenticate to a private registry over http even with the `--insecure-registry` enabled.

```
# docker push localhost:8000/scratch
The push refers to a repository [localhost:8000/scratch] (len: 1)
Sending image list
Pushing repository localhost:8000/scratch (1 tags)

2014/12/08 16:42:12 HTTP code 401, Docker will not send auth headers over HTTP.
```

**Comment by tiborvass** [comment]
@ewindisch what do you think about this issue? Should we allow this for insecure registries?

**Comment by tiborvass** [comment]
The conclusion of my conversation with @ewindisch is that we need to inform the user (possibly with a prompt) that their credentials can be sent in an insecure way.

**Comment by jfrazelle** [comment]
I do not think we want this. It would be advocating sending credentials over http, ping @ewindisch

**Comment by phemmer** [comment]
If the user wants to do something dangerous, that's the user's problem, not docker's.

If the docker daemon, and registry are on a private network, cleartext credentials are not as much of an issue. You are basically forcing users to setup SSL, which can be a significant chore, and cost money.

Plus we're not even talking about adding code to allow this feature, we're talking about removing code.

**Comment by jfrazelle** [comment]
Ya maybe just needs a warning? idk

also self-signed ssl certs are free ;) but I see your point

**Comment by xiaods** [comment]
self-signed ssl is good fit for requirement. i don't think we need add this feature on this request.

**Comment by visualphoenix** [comment]
Can we get this fixed in 1.7.x?

**Comment by ewindisch** [comment]
Should be a DO NOT FIX. Self-signed SSL works. I know there is an argument (such as @phemmer's) that users can choose to shoot themselves in the foot, but we can also choose not to let users do bad things. Best practices only need exist when there is an option to do it the wrong way.

**Comment by phemmer** [comment]
By that argument, the `--insecure-registry` option should be removed.

**Comment by calavera** [comment]
Do we have any resolution here? What's `--insecure-registry` for then?

**Comment by ewindisch** [comment]
@phemmer yes, I would agree. It is why we did not immediately support --insecure-registry.

@calavera an insecure-registry can allow users to upload and download images without authentication. It is not secure.

**Comment by tiborvass** [comment]
@ewindisch But @phemmer's point is that **`--insecure-registry` is not secure** is a tautology.

**Comment by ewindisch** [comment]
One major issue is that the insecure-registry setting is daemon-level, but the authentication details are provided by the client. The client trusts the daemon not to willy-nilly send those credentials in cleartext over the wire.

**Comment by tiborvass** [comment]
@ewindisch do you want to bring --insecure-registry to the client then?

**Comment by ewindisch** [comment]
@tiborvass it would be the minimum requirement. Overall, I'd rather address what @phemmer calls "a significant chore and costs money". Setting up SSL should require neither significant effort nor money.

**Comment by tiborvass** [comment]
@ewindisch @dmp42 @jfrazelle @diogomonica 

3 facts:
- everybody wants `--insecure` on the client, I got a lot of heat because I implemented it on the daemon, thinking that is the right thing.
- `--insecure` on the client would actually solve the issue at hand: if the user wants to leak his information, so be it. We could implement it with a confirmation prompt like mentioned earlier in this issue.
- the best option we all want for our users is for them to install CAs and certs as easily as running one single zero config command. letsencrypt.org is cool but I'm thinking more about automagic CA management discovery++. Once this is in place, we could deprecate `--insecure` altogether.

**Comment by jfrazelle** [comment]
I disagree with no. 2 tho, if they want to leak their information then they
should not use docker, they can just post their credentials on their
facebook page and be done with it.

i think we should at the very least not allow them to send creds over http

**Comment by phemmer** [comment]
> One major issue is that the insecure-registry setting is daemon-level, but the authentication details are provided by the client. The client trusts the daemon not to willy-nilly send those credentials in cleartext over the wire.

But the daemon ignoring the client's trust that it won't send/receive images in the clear is OK?

> if they want to leak their information then they
should not use docker, they can just post their credentials on their
facebook page and be done with it.

This is a bit over dramatic, and an incorrect assessment as well.
Just because the user provided the `--insecure` argument does not mean the information will be leaked. It is entirely possible for the docker daemon and the registry to sit on the same network, or even the same host, where connection snooping is not an issue.

**Comment by mbentley** [comment]
If allowing the sending of credentials over HTTP was accepted, I would think that one would want to require an insecure flag be required on the client and the daemon.  I would personally rather see us not allow sending of credentials over clear text since you can generate your own self signed SSL certs but I also understand there are edge cases, hence requiring a client and daemon flag for an operation to succeed.  Even at that, a warning that data is being sent in clear text should still be present.

**Comment by jfrazelle** [comment]
I understand the scenario when it is all running on the same host anyways
behind a firewall etc but we have no way of knowing that is the case and
not that someone is sending plain text creds over a public network and that
is why I do not think we should allow it at all.

**Comment by dmp42** [comment]
@jfrazelle agreed - but then we do that for --insecure itself: when people use that flag, they expose themselves to trivial downgrade attacks and subsequently remote code execution, not to mention they do send their (possibly critical) data (eg: layers) over plain text.

**Comment by jfrazelle** [comment]
The fact we already allow somethings over plain text should not be a justification for allowing more, imo. It's unfortunate that ever saw the light of day ;) but I think my opinion is pretty clear at this point so I'll exit the bike shed :) y'all can decide from here

**Comment by ewindisch** [comment]
> @phemmer "But the daemon ignoring the client's trust that it won't send/receive images in the clear is OK?"

No, it's not. We should fix this.

@dmp42 you've made the point about sending auth over TLS to servers we have not verified. This should not be happening. If that is happening, it is a bug and we need to fix it.

@mbentley There is really no need to have a flag on the daemon for this at all given that all clients are root-level admins of the machine. If we get RBAC for the daemon, then less privileged users would simply be unable to access these insecure registries.

**Comment by dmp42** [comment]
@jfrazelle @ewindisch would you agree to remove --insecure entirely?

If not, what would you suggest the behavior to be for it? (since in it's current state, it does allow both plain text communication and blind trust of self-signed certs)

Thanks for taking the time to discuss this.

**Comment by ewindisch** [comment]
@dmp42 I am not keen on --insecure-registry, no. We have it because users quite strongly demanded it at a time when this was a radical departure from the status quo and broke many users. At the time we did this, my main objection was that this would be a slippery-slope as it has proven to be.

All cases of '--insecure' be client-initiated and such a behavior would be *critical* for sending auth in the clear or for unverified certs. It may be noteworthy that SSH even allows a plain-text mode at the request of a client, although I imagine this is only ever used for debugging. That said, I've never seen a server that only accepted cleartext login. There is a lesson to be learned here that UX is highly important to security. That users wish to setup cleartext servers at all is a failure in our ability to provide the right user experience for configuring TLS services.

I know it may be controversial, but I'd far rather support a client-side certificate authorization mechanism for self-signed certificates a la SSH than any form of an '--insecure' flag. If users can deal with SSH existing, they can deal with this.

**Comment by Supernomad** [comment]
As a long time proponent of SSL on every web facing application... PERIOD, I feel like I have an interesting perspective on this issue. My reasoning for SSL on all web applications is in fact because they are WEB applications, and the internet is insecure and always will be. 

However requiring, read that as forcing, any sort of specific security implementations is, in my opinion, ridiculous. For instance my current setup, which is essentially multiple geographically dispersed clusters of containers all talking to a central CI environment containing, among other things, a few completely insecure non-web facing registries. 

Why are they completely insecure.  Well because, I already have fully secured IP-SEC tunnels joining the clusters together, so why exactly do I need to have TLS on top of the IP-SEC tunnels? The only thing this would protect against is someone who managed to get into my network, which is physically protected by hardware enterprise firewalls. If that were indeed the case then I have far bigger issues than having an insecure registry. 

The long and short of it is, in an enterprise environment forcing a certain security methodology makes it almost impossible to adopt the technology, unless it happens to fit perfectly with what you already have.

**Comment by visualphoenix** [comment]
@Supernomad :+1: for having a secure back end. However don't hold your breath for an insecure registry. Docker folks are doing what is best for everyone. If you are an enterprise who already has a secure back end then it should be trivial to generate an internally resolvable ssl cert for your internal registry that is valid for all internal hosts. They aren't really forcing anything other than the right play.

**Comment by Supernomad** [comment]
@visualphoenix I completely agree it's not a big deal, I just find it unnecessary to have TLS on the registry. That being said I totally understand that it's best practice, and have no issue with it being the default configuration. I just find it odd that it seems like the consensus to force the situation, as opposed to letting the user decide what they need in terms of security. 

I really just wanted to chime in that there are valid use cases for using an insecure registry without affecting security even in large deployments.

**Comment by LK4D4** [comment]
I think that new registry even supports letsencrypt. `--insecure-registry` is an atavism.
