### ISSUE TITLE
Docker pull stuck when devmapper data pool is full

### ISSUE THREAD

**Issue by chenchun** [docker/docker#9659]
I found when pull a image and extract a layer might make devmapper data pool full, the pull would stuck. And at this time, if we try to stop docker daemon, it results in a defunct process.

**Comment by rhvgoyal** [comment]
By default, if data pool is full, it changes into read only mode and queues up all the pending IO. If pool is not extended with-in 60 seconds, pending IO is failed. So after waiting for 60 seconds, your pull request should fail.

I think there are special ways to change this behavior and wait infinitely. But I don't think docker uses that by default. 

Give me some details about docker version, kernel version and your test environment and I will try to reproduce it.

**Comment by rhvgoyal** [comment]
This is a configuration issue. If user uses lvm thin pool and sets up lvm for automatic extension of pool when it is full, then pool will be automatically extended.

Read docker-storage-setup code now which sets up an lvm thin pool and sets it up for automatic extension.

https://github.com/projectatomic/docker-storage-setup

I think this issue should be closed.

**Comment by vbatts** [comment]
This is true. Expected behavior for any of the storage drivers when its disk runs full varies greatly. `btrfs` is pretty hard to determine that it's full, but output to the user on `docker pull` is a little more indicative (even if it is noisy).

Perhaps this is best closed, and open a proposal or RFC regarding "docker storage driver behavior when storage fills up".

Perhaps with a bit of plumbing, catastrophe can be avoided. Even if that means providing a reduced capability recovery runtime mode.
