### ISSUE TITLE
Removed file comes back after it's removed when using AUFS

### ISSUE THREAD

**Issue by cezarsa** [docker/docker#9690]
Hello, I've hit a weird bug using AUFS that causes a deleted file to come back after the container is committed.
This issue can be easily reproduced with the script below, it involves creating a file inside a directory, and subsequently removing and recreating the whole directory with the file. After that, if we remove and recreate only the directory, the file will come back.
I tested the same script with devicemapper and this bug doesn't happen.

This script better explains it:

```shell
#!/bin/bash

id=$(docker run -d ubuntu:14.04 bash -c "mkdir -p /x && touch /x/a")
docker wait $id
sleep 1
docker commit $id myimg
docker run myimg ls -l /x --time-style=full-iso
id=$(docker run -d myimg bash -c "rm -rf /x && mkdir /x && touch /x/a")
docker wait $id
sleep 1
docker commit $id myimg2
docker run myimg2 ls -l /x --time-style=full-iso
id=$(docker run -d myimg2 bash -c "rm -rf /x && mkdir /x")
docker wait $id
sleep 1
docker commit $id myimg3
docker run myimg3 ls -l /x --time-style=full-iso
```

Output:

```shell
$ bash ~/bug.sh

# mkdir -p /x && touch /x/a
# so far so good.
0
3dd7ee810750e71ae6f2e08bf4c5928e93a79f8f3e79cc2a18cabee137326956
total 0
-rw-r--r-- 1 root root 0 2014-12-16 13:35:43.000000000 +0000 a


# rm -rf /x && mkdir /x && touch /x/a
# still okay, file recreated with new timestamp
0
81b3516ca28a79c277fb05086a009a5cf8c1e337ecf7bb81fc64c220473d1714
total 0
-rw-r--r-- 1 root root 0 2014-12-16 13:35:45.000000000 +0000 a

# rm -rf /x && mkdir /x
# directory should be empty, BUT the file came back with its previous timestamp
0
f99c32be410b257b94f5229cb214dbe04fbac052d9fbec769963168d39dabe05
total 0
-rw-r--r-- 1 root root 0 2014-12-16 13:35:45.000000000 +0000 a
```

System Info:

```
$ uname -a
Linux vagrant-ubuntu-trusty-64 3.13.0-30-generic #55-Ubuntu SMP Fri Jul 4 21:40:53 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

$ docker version
Client version: 1.4.0
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 4595d4f
OS/Arch (client): linux/amd64
Server version: 1.4.0
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 4595d4f

$ docker -D info
Containers: 0
Images: 1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 1
Execution Driver: native-0.2
Kernel Version: 3.13.0-30-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 1
Total Memory: 994 MiB
Name: vagrant-ubuntu-trusty-64
ID: PQVP:BIXD:2YNX:RFWJ:TL4X:EPMD:2MGQ:OAMX:PXVH:RFZT:ZESQ:FOBZ
Debug mode (server): false
Debug mode (client): true
Fds: 18
Goroutines: 21
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```

**Comment by jfrazelle** [comment]
ping @jlhawn @vbatts 

@cezarsa can you try on the latest version of docker

**Comment by cezarsa** [comment]
The same problem still happens, using the same script to reproduce it.

Here are system current settings:
```
$ bash ./bug.sh
0
d7d3ecd0f697e0ff0c6200a9e8abed861dbad943d0e4f1b0943e586753d6f2b5
total 0
-rw-r--r-- 1 root root 0 2015-02-26 21:48:49.000000000 +0000 a
0
ebde6c1128c4c6648b5367d8849ef63ae499fc852718a57f28048e63920e39e4
total 0
-rw-r--r-- 1 root root 0 2015-02-26 21:48:51.000000000 +0000 a
0
7fa6862edbe09f0c62a942a5928a393d9478f097fcf4ed5bcb4d629b04403851
total 0
-rw-r--r-- 1 root root 0 2015-02-26 21:48:51.000000000 +0000 a

$ uname -a
Linux vagrant-ubuntu-trusty-64 3.13.0-30-generic #55-Ubuntu SMP Fri Jul 4 21:40:53 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

$ docker -D info
Containers: 7
Images: 140
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 154
Execution Driver: native-0.2
Kernel Version: 3.13.0-30-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 1
Total Memory: 994 MiB
Name: vagrant-ubuntu-trusty-64
ID: PQVP:BIXD:2YNX:RFWJ:TL4X:EPMD:2MGQ:OAMX:PXVH:RFZT:ZESQ:FOBZ
Debug mode (server): false
Debug mode (client): true
Fds: 19
Goroutines: 20
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```

**Comment by jlhawn** [comment]
So I think this is a bug with the way we export rootfs diffs with AUFS:

```shell
id=$(docker run -d myimg2 bash -c "rm -rf /x && mkdir /x")
docker wait $id
sleep 1
docker commit $id myimg3
```

The `rm -rf /x` command will make an AUFS whiteout file `/.wh.x` which marks the directory as removed in the aufs working branch. But then, `mkdir /x` will replace it with `/x` again but with new mtime, ctime, atime, etc. AUFS will *also* make this new directory "opaque", creating a hidden `.wh..wh..opq` file in this new directory in the working branch (it's not visible in the container). This tells AUFS to hide whatever is in this directory in lower branches, like the `/x/a` file.

The bug comes in when we export the rootfs diff. AUFS does it differently than the other copy-on-write storage drivers. It just exports the working branch, but excludes the hidden `.wh..wh..*` files. All other removed files/dirs are regular "whiteouts", like `.wh.<original_name>`. However, when this exported diff is then applied to a new layer we don't see the `.wh..wh..opq` file so AUFS doesn't know that that directory is "opaque" anymore.

This wouldn't be a problem if we didn't exclude the `.wh..wh..*` files when exporting an AUFS diff.

But if we didn't exclude them then we'd run into another bad issue, different storage drivers calculating different diffs for the same set of changes which results in different Tarsum checksums which are currently used in verifying image content.

I think the solution to this will be to "Stop Using Tarsum to Verify Rootfs Diffs". Then we no longer need to exclude the ".wh..wh..opq" files when exporting an AUFS branch and this problem will be fixed (at least for AUFS).

But then there's another issue: Say you push this diff to the registry and I download it and I'm using the BTRFS storage driver. The other storage drivers don't respect the `.wh..wh..opq` files, so then I'd still see `/x/a` file. The other storage driver `ApplyLayer` methods will have to be updated to to support the "opaque" markers that AUFS produces: when it sees the marker, just remove everything in the directory. Either do this OR make AUFS diffs be generated in the same way (would cause performance hit when doing `docker commit` with AUFS when there's a lot of filesystem entries).

**Comment by jfrazelle** [comment]
op sorry this is a dup of https://github.com/docker/docker/issues/9093 so moving jlhawns awesome comment there
