### ISSUE TITLE
"initgroups, operation not permitted" error in apache2-mpm-itk when inside Docker

### ISSUE THREAD

**Issue by AlekseyMartynov** [docker/docker#9734]
Description of problem: Apache2 with ITK MPM fails inside a Docker container

`docker version`:

    Client version: 1.4.1
    Client API version: 1.16
    Go version (client): go1.3.3
    Git commit (client): 5bc2ff8
    OS/Arch (client): linux/amd64
    Server version: 1.4.1
    Server API version: 1.16
    Go version (server): go1.3.3
    Git commit (server): 5bc2ff8

`docker info`:

    Containers: 3
    Images: 25
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Dirs: 37
    Execution Driver: native-0.2
    Kernel Version: 3.13.0-37-generic
    Operating System: Ubuntu 14.04.1 LTS
    CPUs: 1
    Total Memory: 490 MiB
    Name: temp-droplet
    ID: 6NUW:VWUA:LSXN:CVLO:4ATC:R7OA:7D2I:F5SZ:QHPB:G5KX:U7PC:A25B
    Debug mode (server): false
    Debug mode (client): true
    Fds: 24
    Goroutines: 22
    EventsListeners: 0
    Init Path: /usr/bin/docker
    Docker Root Dir: /var/lib/docker
    WARNING: No swap limit support

`uname -a`: 

    Linux temp-droplet 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details: DigitalOcean droplet, Ubuntu 14.04 x64

Follow the steps below:

    docker run --rm -t -i ubuntu:14.04 bash
    apt-get update
    apt-get install apache2 curl 

    apache2ctl start
    curl http://localhost
    # OK

    # Switch to ITK
    a2dismod mpm_event
    apt-get install apache2-mpm-itk
    apache2ctl stop
    apache2ctl start
    
    curl http://localhost
    # Fails with 500 Internal Server Error
    
    cat /var/log/apache2/error.log

    [Thu Dec 18 22:23:38.399922 2014] [mpm_itk:warn] [pid 4183] (itkmpm: pid=4183 uid=33, gid=33) itk_post_perdir_config(): initgroups(www-data, 33): Operation not permitted

From what I can see, it cannot decode `gid`. It does *not* fail on the host system, fails only inside a container.

Can someone please sort out what is the cause?

**Comment by jfrazelle** [comment]
I think you should refer to forums.docker.com or #docker on IRC freenode for support, I do not think this is a problem with docker itself seeiing as many people run apache in a container

**Comment by palamccc** [comment]
@AlekseyMartynov I'm facing similar issue, did you solve it, did you find a way to run Apache ITK MPM inside Docker ?

**Comment by AlekseyMartynov** [comment]
@palamccc 
No. I ended up using a container-per-user model with the standard MPM. Also I contacted the author the mpm_itk module, and he was not too enthusiastic about Docker :)

**Comment by palamccc** [comment]
@AlekseyMartynov  I managed to run apache mpm itk module, by using docker's --privileged option. 
https://docs.docker.com/reference/run/#runtime-privilege-linux-capabilities-and-lxc-configuration

**Comment by AlekseyMartynov** [comment]
@palamccc thanks for letting know!

**Comment by thaJeztah** [comment]
> I managed to run apache mpm itk module, by using docker's --privileged option.

I'd personally try to avoid using `--privileged` if not really necessary. You might be giving too much permissions to the container, resulting in a less secure setup.

Wondering what the exact use case is here; if I understand correctly, the mpm_itk module allows running multiple vhosts, each running under a different account (uid/gid). I do see this being useful in a traditional shared hosting environment. However, this (to me) sounds like an overlap with what containers offer you; running each vhost in a separate container will give you even more isolation, and sound like a more flexible solution altogether.

Just asking these; is there something you're able to achieve with mpm_itk that you're not able to when running in separate containers?

**Comment by palamccc** [comment]
@thaJeztah  Thanks for your input.

Since i'm trying to run an existing perl+apache+cgi app into docker, and apache is configured to run different cgi scripts with different user ids. Since **i don't have control over app, I've to use --privileged option** to make it work. I understand its bad design, but my requirement is to just make it work in docker.

**Comment by thaJeztah** [comment]
> Since i don't have control over app, I've to use --privileged option to make it work

Yeah, that's always unfortunate. Clear! (I wanted to explain the alternatives; using separate containers, because *in general* I think that's the better approach).

To prevent loosening up the permissions too much (the `--privileged` flag), you might want to look into `--cap-add` and `--cap-drop`; this gives you far more fine-grained control over the capabilities that the container has. If **will** take some research to find which capabilities are needed for your case, but from a security perspective, it is preferable.

You can find the documentation on `--cap-add` / `--cap-drop` here; https://docs.docker.com/reference/run/#runtime-privilege-linux-capabilities-and-lxc-configuration

**Comment by karimkancel** [comment]
The issue is closed but this might help other people. Even though containers are the preferred approach, I must use mpm-itk too. However as @thaJeztah advised earlier I did not want to use `--privileged`. In my case `--cap-add=SYS_NICE --cap-add=DAC_READ_SEARCH` was enough.

**Comment by thaJeztah** [comment]
@karimkancel thanks for adding that info; Since this is really specific to Apache/mpm itk, I don't think this is something for the documentation, but if you happen to have a blog, you could write a short blog post (e.g. "Running apache mpm itk in Docker"), and a link to that blog post can be added to the Docker Weekly newsletter to give it better exposure

**Comment by lordspace** [comment]
@karimkancel Thanks! It worked for me. How did you find about that capability?

**Comment by karimkancel** [comment]
@lordspace It's been a while but I think I got it by reading mpm-itk source. Excerpt from mpm_itk.c:

```c
static int itk_post_drop_privileges(apr_pool_t *pool, server_rec *s)
{
#if HAVE_LIBCAP
    if (ap_itk_enable_caps) {
        cap_t caps;
        cap_value_t suidcaps[] = {
            CAP_SETUID,
            CAP_SETGID,
            CAP_DAC_READ_SEARCH,
            CAP_SYS_NICE,
        };
```
