### ISSUE TITLE
Login apparently ignores insecure-registry option

### ISSUE THREAD

**Issue by rmalveis** [docker/docker#9752]
Hi Guys. I really don't know if it is a bug, but I'm not find any doc about this behavior. 

Teh problem, basically, is that the Login action apparently ignore the --insecure-registry option.

Please follow my steps below to get it clearly:

    root@host:home/rximenes#:apt-get install docker.io #Debian Jessie

    root@host:home/rximenes# docker version
    Client version: 1.3.2
    Client API version: 1.15
    Go version (client): go1.3.2
    Git commit (client): 39fa2fa
    OS/Arch (client): linux/amd64
    Server version: 1.3.2
    Server API version: 1.15
    Go version (server): go1.3.2
    Git commit (server): 39fa2fa

    root@host:/home/rximenes# docker pull private-registry.mydomain.com/path/to/the/image
    2014/12/19 11:27:00 Error: Invalid registry endpoint https://private-registry.mydomain.com/v1/: Get https://private-registry.mydomain.com/v1/_ping: x509: certificate signed by unknown authority. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry private-registry.mydomain.com` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/private-registry.mydomain.com/ca.crt

    root@host:home/rximenes# service docker stop
    root@host:home/rximenes# vim /etc/default/docker #Added the `--insecure-registry private-registry.mydomain.com` as a Daemon Options

Docker Options:
DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4 -b brdg0 --insecure-registry private-registry.mydomain.com"
My "Custom" Bridge is exactly the bridge teached here: https://docs.docker.com/articles/networking/#building-your-own-bridge

    root@host:home/rximenes# service docker start
    root@host:home/rximenes# docker pull private-registry.mydomain.com/path/to/the/image
Pulling repository private-registry.mydomain.com/path/to/the/image #OK -> insecure-registry makes difference
2014/12/19 11:27:56 Authentication is required. # My private registry is behind an Apache 2.2 to basic auth and reverse proxy with self-signed certificate

    root@host:home/rximenes# docker login private-registry.mydomain.com
    Username: <my user>
    Password: <my pass>
    Email: <empty>
    2014/12/19 11:28:13 Error response from daemon: Server Error: Post https://private-registry.mydomain.com/v1/users/: x509: certificate signed by unknown authority #NOK -> Certificate problem not ignored even with the insecure option.

So, as you could see, the option was apparently ignored by Login Action. Was it a expected behavior or a issue?
I think that since the CA self signed need to be ignored in non-prod environments, would make sense if I could Login in using this option too. 

A possible important note: Trying to login using the Docker 1.3.0 it works fine even without the insecure-registry option. Did you revisited this code?

**Comment by Thorndike** [comment]
I am running into the same problem here. Apache as a proxy to the docker registry on a centos 7 VM. Client is "Docker version 1.4.1, build 5bc2ff8" on Ubuntu 14.04. Nither login nor push are working because the --insecure-registry has no effect.

**Comment by gdoffe** [comment]
Same problem than Thorndike. Same versions except that apache proxy is on Ubuntu 14.04.1 64 bits too.

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/9570

**Comment by mochrul** [comment]
I'm not fully agree with closing this ticket because I'm not sure if it can be handled in the same way as the other one.

In the near past my employer created a private docker repository.

This repository has certificate and I want to reach it with a **https** url. So the problem for me is not that the docker refuse authentication in pure http. But I was not able to manage to login to this repository.
Partly because the issue #10150 but also because I was not able to mute certificate problems with --insecure-registry option. In contrast of what the client sad in the error message.

I tried a lot of combination of trying to login with name or IP address (https://docker.local vs https://10.10.10.10) adding the exception to the docker daemon --insecure-registry option and host or ip address or network or url) and also tried with and without installing the ca certificate into the right place (/etc/docker/certs/docker.local/ca.crl)

I was get some type of error messages, some of them is just because of the other bug (when the ca was installed and used) but some of them is in the scope of the --insecure-registry option I think.

$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

https://docs.google.com/spreadsheets/d/1DkfZCA-wR1d-MfNt1bWWeuZLEERbigL_5DgHj_LN6-8/edit?usp=sharing

**Comment by stefanwuthrich** [comment]
same problem here, same env:
➜  ~  docker version                                                                  
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

ca ist from startssl, copied ca.pem to /usr/local/share/ca-certificates
but no chance
url of the reg is https://reg.exponity.ch/v1/_ping

**Comment by DennyZhang** [comment]
@stefanwuthrich

I'm having the exact same problem as you. And my docker version is the same like you.

**Comment by DennyZhang** [comment]
Here are certificate used for different OS
https://golang.org/src/crypto/x509/root_unix.go

    12	var certFiles = []string{
    13		"/etc/ssl/certs/ca-certificates.crt",     // Debian/Ubuntu/Gentoo etc.
    14		"/etc/pki/tls/certs/ca-bundle.crt",       // Fedora/RHEL
    15		"/etc/ssl/ca-bundle.pem",                 // OpenSUSE
    16		"/etc/ssl/cert.pem",                      // OpenBSD
    17		"/usr/local/share/certs/ca-root-nss.crt", // FreeBSD/DragonFly
    18		"/etc/pki/tls/cacert.pem",                // OpenELEC
    19		"/etc/certs/ca-certificates.crt",         // Solaris 11.2+
    20	}
