### ISSUE TITLE
Once container is exited, if I try to start it, get a no such container error.

### ISSUE THREAD

**Issue by Danisan** [docker/docker#9821]
When the container is running:

root@daniel-Inspiron-3421:/opt# docker ps -a
CONTAINER ID        IMAGE                          COMMAND             CREATED              STATUS              PORTS                    NAMES
e58f4c0ceb0f        adhoc/odoo-all-in-one:latest   /bin/bash           About a minute ago   Up About a minute   0.0.0.0:8069->8069/tcp   determined_ritchie   

when I exit it and try to start again:

root@daniel-Inspiron-3421:/opt# docker start 743c18c8d79b
Error response from daemon: No such container: 743c18c8d79b
2014/12/26 20:51:21 Error: failed to start one or more containers

root@daniel-Inspiron-3421:/opt# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

**Comment by unclejack** [comment]
Based on the text of the initially reported issue, this was only a misunderstanding.

The official documentation is extremely useful: https://docs.docker.com/userguide/usingdocker/ (and all pages of the official documentation).

The tutorial found at https://www.docker.com/tryit/ can also be useful.

I'm going to close this issue now because it doesn't appear to be a bug and the discussion can continue even after closing the issue. Please feel free to continue the discussion.
