### ISSUE TITLE
Include Dockerfile source in the image

### ISSUE THREAD

**Issue by dnephin** [docker/docker#9841]
From a discussion on the docker-user mailing list:

It would be nice if the Dockerfile could be included in the image itself.
* it could be used by docker hub to display the source of the image
* if you pull an image from some other registry it would give you some idea of how the image was built

@erikh raised the concern that this could be bad for images with secrets.

This could be implemented as a new flag to `docker build` which would optionally allow you to include the file. That way any image with secrets could omit the flag, for the old behaviour.

`docker build --include-dockerfile` or something like that?

**Comment by duglin** [comment]
In general I agree that more data is probably a good thing, but you need to be careful with opening a can of worms.  As I said above, I doubt the Dockerfile is going to be sufficient in most cases so then we'll probably need to stash the entire build context some place.  This feels like we're asking for people to include their Makefile, or even source, within their exe - feels odd.

Would a metadata field with a URL to the source (like a git repo) be appropriate and useful?  Then its presented in a consistent way, is optional, but when present isn't a lot of data - just a URL.  Doesn't add bloat to the image.

**Comment by thaJeztah** [comment]
I see that it wasn't mentioned here, but @ibuildthecloud very recently created a proposal for meta-data in docker that will be of interest for anyone following this issue. The proposal can be found here; https://github.com/docker/docker/pull/9882

**Comment by thaJeztah** [comment]
@dnephin do you think this needs to be part of docker's core functionality? I like the idea in general, but the discussion above raised various cases where a Dockerfile isn't even used.

https://github.com/docker/docker/pull/9882 will (probably) be implemented in 1.6 and would make it possible to store the Dockerfile as meta-data (label) using an external tool or some scripting.

**Comment by frank-dspeed** [comment]
cant we simply log all builds (the log from building an image) to a default location inside image and add a -log switch to docker build? so for image creators that whant to store the build steps of a build it adds .docker.build.containerid.log

so that it stores a log for every docker build tiggered by the docker build command 1 log file per build container. This enables for example that i do a docker build -log ./path/Dockerfile and get a img with all build steps logged by container when i then use the image via from in a other dockerfile and also attach -log to docker build on that it also adds the logs for that so that i could after that rebuild the image from that log and maybe we can make to log formart so easy that we can easy filter for the RUN MAINTAINER VOLUME PARTS and the Resulting screen output 

greetings.

**Comment by ipernet** [comment]
Hi all,

I love ``CONFIG_IKCONFIG`` when dealing with custom Linux Kernels because this is convenient and easy, and I always end up thanking myself for enabling the option! I miss the same possibility of including the recipe (Dockerfile) of an image in Docker, recipe that could then be easily extracted and used/presented by registries and users like described by @dnephin and @thaJeztah.

Using ``LABEL`` for storing an entire  ``Dockerfile `` looks to me tricky (because ``LABEL`` for *Docker images* is about using ``LABEL`` *in* ``Dockerfile``). I decided to give it a try and do an implementation of such a proposal, as an exercice first. It's my very first step in Go programming and Docker coding, so I apology for any mistake. If you have any feedback on the approach or the code, I will be glad to learn from it!

**Implementation**

* **A new flag for docker build**

    ``docker build --help``

```bash

Usage:	docker build [OPTIONS] PATH | URL | -

Build a new image from the source code at PATH

  --include-dockerfile=false    Include the content of the Dockerfile in the 'Dockerfile' field of the generated image
```

* **Embed the original Dockerfile as a new "inspectable" field**

I was really wondering about the storage format of the file, because it made ``docker inspect`` really ugly with plaintext/json. I decided to go with``base64 encoding`` and ``gzip`` content to keep it clean and lightweight.

For the demo I have used the following Dockerfile: https://docs.docker.com/reference/builder/#dockerfile-examples

```bash
# docker build --include-dockerfile -t dockerfiledemo .
...
Successfully built 401311e7cec6
```

* **Usage**

```bash
# docker inspect 401311e7cec6
```

See the new *Dockerfile* node:

```
[
{
    "Id": "401311e7cec6f8ebb6112c68384d6e4a72e36fb13c157d9f295fc574ba0bcbda",
    "Parent": "6d4946999d4fb403f40e151ecbd13cb866da125431eb1df0cdfd4dc72674e3c6",
    "Comment": "",
    "Created": "2015-07-09T17:28:09.396103346Z",
    "Container": "f68f8f25555197e6687770fd5925f7c72f1ee38e37e074a5f3c3e7dfdfef9808",
    "ContainerConfig": {
        "Hostname": "d3659c5e113e",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": null,
        "PublishService": "",
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "Cmd": [
            "/bin/sh",
            "-c",
            "echo moo \u003e oink"
        ],
        "Image": "6d4946999d4fb403f40e151ecbd13cb866da125431eb1df0cdfd4dc72674e3c6",
        "Volumes": null,
        "VolumeDriver": "",
        "WorkingDir": "",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": [],
        "Labels": {}
    },
    "DockerVersion": "1.8.0-dev",
    "Dockerfile": {
        "Format": "base64",
        "Content": "H4sIAAAJbogA/4xS22rbQBB9368YFIhbsGQ7TmIMtambOBCIneCkbkvpw2o1shZLWrEXX176ae239E86WomSPDTEYLQ7s3POmTNzAsuNLA/shJ3Aer56vL1fwstfP+pHA8ZuVveLJuBiV1rHFrPb5RP95ytYS2GVpg+6A3zY+dvHRIkt6kioYsrY3ezT/A6u0QgtKytVOQmeMmlAFnyDQAdnMAGrwFiuLdgMIVUq5hrwgMJZHucYwBrLROlJMLtazOFBq8QJa+qwNh5yEPUDtvq8BF7ZcIMWXJVwi3B6+i8iS2LIcwiPdFRWpsfQKpUbKGsb6BkXGZ6BqrA0JgsN6h1qRubcSI2pOoCiO6yXV686Nmz9aq2il7ct764UXTjs0pjoQemEwKhrobHWyaGT8i12IJGmyvkReJlA2hC/va/DYEAsDcnz4mKbSA0/exFlSdEjWlcRZcWN2ZMS/6atDQ1NEH0mgcHZ8Lwt6zUhqp45q5pZtRTwrpCbzAKZCjH6CcZoLOz5sQuxI4UWEoXGZ6yWYvveM8bcZBAK6KDIFAQtWgDTKfSiOqlFh7H514f7xzlcjPt9drW4rl3+HjRigy4EYUpyaTD+TKtU7f2psTX4UQ9g4XIrqxyblTO0V7yg66tjHLwcYy3Xq6TVhCkp11T7RZLrytmKWjSqQJvJcgO53CJMJpMpjPsjnlyKs9HwMv0PXOHhlCy3b8C7HF8ko9F4KGI8r/v6ptyfX7+pplR7yPiOzN2rtsnuC3bYS5tBj2R3/WI9R/I5QuvVKiLG/gYAAP//K+hvNRcEAAA="
    },
    "Author": "Victor Vieux \u003cvictor@docker.com\u003e",
    "Config": {
        "Hostname": "d3659c5e113e",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": null,
        "PublishService": "",
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "Cmd": [
            "/bin/bash"
        ],
        "Image": "6d4946999d4fb403f40e151ecbd13cb866da125431eb1df0cdfd4dc72674e3c6",
        "Volumes": null,
        "VolumeDriver": "",
        "WorkingDir": "",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": [],
        "Labels": {}
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Size": 4,
    "VirtualSize": 188310853,
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    }
}
]
```

**To extract the original Dockerfile:**

```bash
# docker inspect --format='{{.Dockerfile.Content}}' 401311e7cec6 | base64 --decode | zcat
```

Output:

```
# Nginx
#
# VERSION               0.0.1

FROM      ubuntu
MAINTAINER Victor Vieux <victor@docker.com>

LABEL Description="This image is used to start the foobar executable" Vendor="ACME Products" Version="1.0"
RUN apt-get update && apt-get install -y inotify-tools nginx apache2 openssh-server

# Firefox over VNC
#
# VERSION               0.3

FROM ubuntu

...
```

**Images built without the option will show a null node:**
```
[
{
    "Id": "6d4946999d4fb403f40e151ecbd13cb866da125431eb1df0cdfd4dc72674e3c6",
    "Parent": "9fd3c8c9af32dddb1793ccb5f6535e12d735eacae16f8f8c4214f42f33fe3d29",
    "Comment": "",
    "Created": "2015-07-09T17:26:19.396103346Z",
    "DockerVersion": "1.8.0-dev",
    "Dockerfile": null,
    "Author": "Victor Vieux \u003cvictor@docker.com\u003e",
    ...
```

* **The code behind it:**

https://github.com/docker/docker/compare/master...ipernet:dockerfile-inspect

If anyone is interested for a proper PR/proposal, let me know!

**Comment by rhatdan** [comment]
Why not just add the Dockerfile to the image?  
In the Dockerfile

ADD Dockerfile /root/Dockerfile

Or something like that.  In either case you loose any other data used to build the container.  IE Other stuff you added or copied.

**Comment by ipernet** [comment]
Hi @rhatdan 

I want a "scripting" way to access the Dockerfile, which is much less convenient if you include the file in the image itself.

I understand you loose the "context" and the stuffs added or copied, but to continue with my "cooking" analogy, the "recipe" is to me the most important part, because you can always get the ingredients at some others places.

**Comment by rhatdan** [comment]
I actually had written a patch about a year ago to sort of record this information indirectly inside of the code base.  

One other problem with this is containers can be built using other tools then Dockerfile.

But one thing you could look at would be to just script this into a label.

Ie when you do a docker build wrap it with a script that adds 

LABEL Dockerfile=$(cat Dockerfile)

to a newly generated Dockerfile and use that for the build. You probably would need to handle the returns...

**Comment by rhatdan** [comment]
I actually had written a patch about a year ago to sort of record this information indirectly inside of the code base.  

One other problem with this is containers can be built using other tools then Dockerfile.

But one thing you could look at would be to just script this into a label.

Ie when you do a docker build wrap it with a script that adds 

LABEL Dockerfile=$(cat Dockerfile)

to a newly generated Dockerfile and use that for the build. You probably would need to handle the returns...

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
