### ISSUE TITLE
Proposal: Dockerfile with Tag variable at build

### ISSUE THREAD

**Issue by kgrvamsi** [docker/docker#9844]
Every Image comes up with different tag name with their respective versions or with updated Container image.So can we have Tag variable  to a Dockerfile to get the Exact image instead getting all the images associated.

Example

Dockerfile
`````
FROM dockerfile/ubuntu:<VERSION>
`````
````
docker build  --tag--version 12.04
`````

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/9641

**Comment by jfrazelle** [comment]
see also

**Comment by grossadamm** [comment]
@jfrazelle perhaps I'm misunderstanding, but I don't see a way in those other issues to do something like 

    FROM ubuntu:<version>

and dynamically provide the version. Perhaps there is a different way to accomplish that?

We have a build process that builds up multiple docker containers and our build is fairly slow because of that. They all share the same codebase, so if we could build one base image and tag it with the current build version, and then have the other dockerfiles reference that specific version during their build, that would fantastic.

base image

     FROM debian
     # prepare base image

`docker build -t foo/awesomeapp:454`

webapp dockerfile

    FROM foo/awesomeapp:${BUILD_NUMBER}
    # do webapp stuff

task runner

    FROM foo/awesomeapp:${BUILD_NUMBER}
    # prepare task runner

`docker build -t foo/webapp:454 -e BUILD_NUMBER=454`
`docker build -t foo/task_runner:454 -e BUILD_NUMBER=454 `

**Comment by kevinquinnyo** [comment]
@grossadamm Did you ever figure out a way to do this?  The fact that the issue was closed makes me think I'm missing something but I also don't see the other issues as solving this problem.

I'm also wanting to do something like:

```
FROM ubuntu:${RELEASE}
```

And can only come up with hacky solutions such as a wrapper to replace the value in a Dockerfile before build and such.

**Comment by grossadamm** [comment]
Nope, I never found a way to do it built in. What I ended up doing was using `sed` in our build process to build the dockerfile with the right tag.

Horrible blog post that details the process http://synergydatasystems.github.io/posts/build-docker-containers-from-custom-tag-dynamically/

**Comment by kevinquinnyo** [comment]
@grossadamm Thanks for following up on this!  I actually ended up doing something very similar to this (at least for now).  I am very new to docker, but I'm having trouble balancing the DRY principle with what I see as the Docker-esque philosophy on Dockerfiles.

**Comment by thaJeztah** [comment]
Also see https://github.com/docker/docker/issues/10899 and https://github.com/docker/docker/issues/9731

**Comment by rajivbhati12** [comment]
I see it kind of tricky because it impact the basic build principle of dockfile;
meaning:- every step of dockerfile execute in its own container and get save as a temp image for next step; with this thought; for first line to execute it has be static.
Unless we update FROM to perform extra step something like: if imagename[:tag] not found and appears to be more like variable then interpret it as variable

BTW; I am one add to people in queue waiting or this feature, as this can make CI look clean and not hacky 
So, are there plans to enable this feature?

**Comment by thaJeztah** [comment]
@rajivbhati12 please don't leave the same comment on multiple closed issues

**Comment by behrangsa** [comment]
This syntax is working for me:

```
ARG BASE_TAG

FROM something:${BASE_TAG}
```

And then:

```
$ docker build --build-arg BASE_TAG=some-tag .
```

**Comment by thaJeztah** [comment]
Yes, correct, this is now possible

I think the docs need a slight correction, as it's possible to use an `ARG` in `FROM` (not `ENV`). See https://github.com/moby/moby/issues/18119, and the PR that implemented it https://github.com/moby/moby/pull/31352 (documentation: https://docs.docker.com/engine/reference/builder/#parser-directives

I would recommend setting a default, so that build doesn't fail if you don't specify a tag

For example

```Dockerfile
ARG TAG=latest
FROM ubuntu:${TAG}
```

I think this works as well;

```Dockerfile
ARG TAG
FROM ubuntu:${TAG:-latest}
```

**Comment by rajivbhati12** [comment]
Thanks guys I was really looking for this feature

Not sure if we have plans to support something like:
ARG TAG
FROM ${TAG}

**Comment by thaJeztah** [comment]
@rajivbhati12 should work already;

```bash
docker build --build-arg IMAGE=busybox -<<'EOF'
ARG IMAGE
FROM ${IMAGE}
RUN busybox | head -1
EOF
```

```
Sending build context to Docker daemon  2.048kB
Step 1/3 : ARG IMAGE
Step 2/3 : FROM ${IMAGE}
 ---> f6e427c148a7
Step 3/3 : RUN busybox | head -1
 ---> Running in 7e8fec11c34b
BusyBox v1.28.1 (2018-02-20 17:56:45 UTC) multi-call binary.
Removing intermediate container 7e8fec11c34b
 ---> 3675d0d414ac
Successfully built 3675d0d414ac
```

**Comment by kgrvamsi** [comment]
:100: :)
