### ISSUE TITLE
error rate with devicemapper is surprising

### ISSUE THREAD

**Issue by dirk-thomas** [docker/docker#9865]
I am using *docker* for jobs on a Jenkins farm.
I used the default storage on these Ubuntu Trusty machines (which is `devicemapper` if you don't install `linux-image-extra` explicitly).

Since I have seen way to many errors (which seem to be all related to `devicemapper`) I set up three test jobs.
Each job is identical and basically building and running two Dockerfiles (which are created dynamically).
The only difference is the docker version / configuration:
* Docker 1.4.1 using devicemapper: http://54.183.26.131:8080/view/docker%20testing/job/docker_stress_test_141_devicemapper/
* Docker 1.3.2 using devicemapper: http://54.183.26.131:8080/view/docker%20testing/job/docker_stress_test_132_devicemapper/
* Docker 1.4.1 using aufs: http://54.183.26.131:8080/view/docker%20testing/job/docker_stress_test_141_aufs/

Docker with `aufs` performs flawless (the 4 failed jobs out of 193 are unrelated to docker).

But using `devicemapper` the error rate is extreme.
* with docker 1.4.1 roughly **78 %** of the jobs failed due to errors related to devicemapper
* with docker 1.3.2 roughly **60 %** of the jobs failed due to errors related to devicemapper

Please look at any of the failing jobs for details in the console output (one example http://54.183.26.131:8080/job/docker_stress_test_141_devicemapper/49/console).

I am not sure if the variation is simply the variance of testing only 49 or 192 jobs.
But anyway the error rate I am seeing with `devicemapper` is very surprising to me.

Is there anything I am doing wrong?
Can I provide more information?

If this is a *known* problem shouldn't the users of docker we warned way more explicit about this behavior?

**Comment by unclejack** [comment]
@dirk-thomas There are multiple known problems with multiple open issues for problems related to devicemapper: https://github.com/docker/docker/labels/%2Fsystem%2Fdevicemapper

The fact that devicemapper can run into all kinds of problems is well known and we're aware there are problems. Unfortunately, this is going to take a while to sort out and the final solution might involve switching to something else.

Issues like #4036 and #9562 are issues which describe the exact same problem.

I'm going to close this issue now because everyone knows these issues are known. Please feel free to comment on any of the relevant devicemapper issues.

**Comment by dirk-thomas** [comment]
Closing this as a duplicate is fine for me.

But imo this is not "only" a issue which should be tracked in the issue system. The error rate is basically making docker using devicemapper unusable (at least on some systems?).

The installation instruction do not mention this at all. Also e.g. the Ubuntu package does *not* have the necessary dependencies to pull in the parts necessary to use AUFS. Both makes this problem not discoverable to users.

I have switched to AUFS after spending hours in trying and reading. I am pretty sure that effort could be reduced for many users by adding appropriate information to the website.
