### ISSUE TITLE
Docker logs return exit code 1 in case of broken pipe

### ISSUE THREAD

**Issue by mapio** [docker/docker#9897]
How to reproduce:

```
$ did=$(docker run -d busybox sh -c 'while true; do echo "Hello, world"; sleep 1; done')
$ docker logs $did; echo $?
Hello, world
Hello, world
Hello, world
Hello, world
Hello, world
Hello, world
Hello, world
Hello, world
Hello, world
0
$ docker logs $did |head -n 1; echo $?
Hello, world
time="2015-01-04T23:27:21+01:00" level="fatal" msg="write /dev/stdout: broken pipe" 
1
```

as you can see, the second run of `docker logs` through a pipe returns an exit code of 1 (and an error message). This should not happen, for instance 

```
$ cat /etc/passwd | head -n1; echo $?
##
0
```

clearly `cat` does not complain about the broken pipe…

**Comment by duglin** [comment]
try: echo $PIPESTATUS
instead of: echo $?

**Comment by mapio** [comment]
I got the same:

```
$ docker logs $did |head -n 1; echo $PIPESTATUS
Hello, world
time="2015-01-05T15:27:06+01:00" level="fatal" msg="write /dev/stdout: broken pipe" 
1
```

(my shell has `shopt -o -s pipefail` configured by default.

My point is that `docker logs` should not return an error exit code in case its output is truncated. No other command I know does that… (I cited `cat`, but any other, say: `ls`, `df`, `uptime`…)

**Comment by duglin** [comment]
Not sure its a clear as that, for me I see:
yes | head -n1 ; echo $PIPESTATUS
y
141

so some commands do check for an error while trying to write to stdout and bubble that error back to the user.  btw, cat does the same thing.  Try:
yes | head -n100000 > y
cat y | head -n1 ; echo $PIPESTATUS
I get:
cat y | head -n1 ; echo $PIPESTATUS
y
141

I get his from 'ls' too:
ls -R | head -n1 ; echo $PIPESTATUS
.:
141

I think you didn't notice it for some of your commands because of the buffering being done - meaning the writing side was able to write all of its output to the buffer before the reading side shut it down.

I think this is easy enough to change though if the maintainers would like to - but I'm included to think that its working correctly.

**Comment by mapio** [comment]
You are right, I run your tests with `cat` and `ls` and got the same result (error exit codes). So apparently I was completely mislead by the buffering.

I agree that is more common (if not right, at this point) the present behaviour.

I'm closing this.
