### ISSUE TITLE
How to share images between multiple docker hosts?

### ISSUE THREAD

**Issue by ninglee** [docker/docker#9935]
I have two or more hosts and installed docker in each.
If I want to use some image, such as `ubuntu`, I must execute the `docker pull` on each host to download from docker-hub.
I think it's slowly.

As we know, each docker stores the images in local `/var/lib/docker` directory. So can I store the images in a shared disk array and mount as `/var/lib/docker` directory on every hosts. Then one host `pull` the image once, other hosts can use the image directly. Because they use the same `/var/lib/docker`. Of course, a little change to docker is needed to support this.

Is it possible or a good way? Why docker is not designed like this?

**Comment by ninglee** [comment]
If shared disk can be used, at least 2 benefit:
1) only one host pull the image, other hosts needn't download. It's faster.
2) all images only have one copy, not N copies. (N is number of hosts).  It can save the disk space.

**Comment by unclejack** [comment]
@ninglee You need to set up a private registry to mirror images from the public registry. Please look at https://github.com/docker/docker-registry/ and at the `--mirror` option described here: https://docs.docker.com/reference/commandline/cli/.

I'm going to close this issue now since the question was answered. Sharing `/var/lib/docker` isn't possible.

**Comment by faddat** [comment]
Actually, I'm looking into sharing /var/lib/docker between hosts.  Basically, I want to ensure that each host has access to the other hosts' images and containers.  Is having each host mount an nfs share to /var/lib/docker a workable solution to this?  If no, then how might I accomplish this?

**Comment by thaJeztah** [comment]
No, don't do that; `/var/lib/docker` is intended to be managed by a single daemon; having multiple daemons share the same directory is asking for trouble

**Comment by faddat** [comment]
Okay, I'll not do that.  What do you think the way to go is?  I've looked at a number of models for handling storage, but none has seemed ideal to me just yet.

**Comment by thaJeztah** [comment]
There's experimental support for external graph drivers;https://github.com/docker/docker/blob/master/experimental/plugins_graphdriver.md, for example https://github.com/hustcat/docker-graph-driver. I haven't used this plugin myself, and there may be others, so all at your own risk here :smile:

Otherwise, setup a private registry as mentioned above

**Comment by faddat** [comment]
Hey, it's all Open Source, we've all seen the Warranty ;).



Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by vishaltvarun** [comment]
@faddat I ran into the same problem of sharing images between multiple docker daemons. Is there a workable solution available?. If not any other suggestions would be appreciated.

**Comment by faddat** [comment]
@vishaltvarun 
How about we compare up our approaches that didn't work?  get ahold of me on hangouts:  faddat@gmail.com 

:)

-Jake

**Comment by aashidham** [comment]
Now that Linux 4.5 allows overlayfs to work cleanly with nfs mounts (http://www.spinics.net/lists/linux-fsdevel/msg93672.html), there could be some way that Docker running on modern Linux (with overlay2) could leverage this for a shared image store. What options should I set on the `dockerd` runtime to make this work?

**Comment by faddat** [comment]
I'm not too sure, but I am sure that I'm interested.

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by thaJeztah** [comment]
The `/var/lib/docker` directory is not designed to be shared by multiple daemons. Even though the _storage_ could work, multiple daemons acting on the same store is asking for trouble. For example; daemon A has a container running that uses the `foobar` image, but daemon B does not have containers running; doing `docker image remove foobar` on daemon B would delete the image, while it's still in use by a container.

**Comment by Puneeth-n** [comment]
@thaJeztah so I'm guessing setting up a local registry is "the way" to share pre-built images across multiple docker hosts.

**Comment by pauldotknopf** [comment]
I have an OS that reboots into separate images from grub. What happens if I reuse ```/var/lib/docker``` across reboots in different distribution/docker versions?

How compatible is ```/var/lib/docker``` across different docker versions? Going forwards and backwards in versions?

**Comment by xtroncode** [comment]
Hey @Puneeth-n I am trying to achieve the same. Were you able to figure out a way ? 
Is having a local-registry the only way ? but this still has the overhead of duplicating images across instances. 
Also even with a local registry it doesn't seem that I'll be able to use buildkit's mount type cache and will have to resort to export/import layers to/from the local registry.

**Comment by jaens** [comment]
> Sharing /var/lib/docker isn't possible.

What? It's of course theoretically possible to share the local storage backend remotely.

Case in point: https://github.com/psviderski/unregistry <sup>("Push docker images directly to remote servers without an external registry")</sup> does that, but depends on the _containerd_ storage backend, which is unfortunately backward incompatible (because Docker has not implemented migrations for it, yet, anyway).

The only real blocker could be that Docker has not opened up the default storage backend enough to support it natively.

---

Top comments on HN for the _unregistry_ project:

> [shykes](https://news.ycombinator.com/item?id=44323506):
>
> Docker creator here. I love this. In my opinion the ideal design would have been:
>
> 1. No distinction between docker engine and docker registry. Just a single server that can store, transfer and run containers as needed. It would have been a much more robust building block, and would have avoided the regrettable drift between how the engine & registry store images.

---

> [richardc323](https://news.ycombinator.com/item?id=44322119)
>
> I naively sent the Docker developers a PR[1] to add this functionality into mainline Docker back in 2015. I was rapidly redirected into helping out in other areas - not having to use a registry undermined their business model too much I guess.
